/* Quiz Time! — "Történelem magyarul" kérdésbank.
   M(kérdés, helyesVálasz, rossz1, rossz2, rossz3)
   A helyes válasz mindig a második paraméter; az alkalmazás
   minden megjelenítésnél összekeveri a négy lehetőséget. */

var M = function (q, a, w1, w2, w3) { return { cat: "hungarian", q: q, a: a, w: [w1, w2, w3] }; };

var QUESTIONS_HU = [

  /* ========== MAGYAR TÖRTÉNELEM — A kezdetek és az Árpád-kor ========== */
  M("Melyik évben történt a honfoglalás?", "895-ben", "1000-ben", "1526-ban", "1241-ben"),
  M("Ki vezette a honfoglaló magyar törzseket?", "Árpád fejedelem", "Szent István", "Attila", "Géza fejedelem"),
  M("Ki volt a hunok leghíresebb, rettegett királya?", "Attila", "Árpád", "Csaba", "Koppány"),
  M("Hány magyar törzs kötött vérszerződést a hagyomány szerint?", "Hét", "Öt", "Tíz", "Három"),
  M("Merre vezettek a magyar kalandozó hadjáratok a 10. században?", "Nyugat-Európába", "Ázsiába", "Afrikába", "Skandináviába"),
  M("Hol szenvedtek döntő vereséget a kalandozó magyarok 955-ben?", "Augsburgnál", "Mohácsnál", "Muhinál", "Világosnál"),
  M("Ki volt Szent István édesapja?", "Géza fejedelem", "Árpád", "Koppány", "Szent László"),
  M("Ki volt az első magyar király?", "Szent István", "Árpád", "Mátyás", "Géza"),
  M("Mikor koronázták királlyá Szent Istvánt?", "1000 táján", "895-ben", "1241-ben", "1526-ban"),
  M("Kitől kért és kapott koronát Szent István?", "A pápától", "A német-római császártól", "A bizánci császártól", "A francia királytól"),
  M("Ki volt István nagy ellenfele a fejedelmi hatalomért?", "Koppány", "Géza", "Imre herceg", "Szent László"),
  M("Kihez írta Szent István az Intelmeket?", "Imre herceghez", "Szent Lászlóhoz", "Gézához", "Mátyáshoz"),
  M("Mi a Szent Jobb?", "Szent István épen maradt jobb keze", "Egy középkori kard", "A koronázási palást", "Egy régi zászló"),
  M("Melyik uralkodóház adta első királyainkat?", "Az Árpád-ház", "A Habsburg-ház", "Az Anjou-ház", "A Hunyadi család"),
  M("Melyik lovagkirályunkat avatták szentté?", "Szent Lászlót", "II. Lajost", "Zsigmondot", "IV. Bélát"),
  M("Melyik királyunk mondta ki: boszorkányok pedig nincsenek?", "Könyves Kálmán", "Szent István", "Mátyás", "II. András"),
  M("Melyik évben adta ki II. András az Aranybullát?", "1222-ben", "1000-ben", "1526-ban", "1848-ban"),
  M("Mikor pusztított a tatárjárás Magyarországon?", "1241–42-ben", "1526-ban", "895-ben", "1686-ban"),
  M("Ki volt a király a tatárjárás idején?", "IV. Béla", "Szent István", "Mátyás", "II. Lajos"),
  M("Hol szenvedett vereséget a magyar sereg a tatároktól?", "Muhinál", "Mohácsnál", "Augsburgnál", "Világosnál"),
  M("Mit tett IV. Béla a tatárjárás után?", "Kővárakat építtetett", "Lemondott a trónról", "A tatárokhoz csatlakozott", "Külföldre költözött"),
  M("Miért nevezik IV. Bélát a második honalapítónak?", "Újjáépítette az elpusztult országot", "Ő vezette a honfoglalást", "Ő alapította az első egyetemet", "Ő hozta a kereszténységet"),
  M("Mikor halt ki az Árpád-ház férfiága?", "1301-ben", "1526-ban", "1000-ben", "1456-ban"),
  M("Hol koronázták a középkori magyar királyokat?", "Székesfehérváron", "Debrecenben", "Szegeden", "Pécsett"),
  M("Mi volt a magyar királyok koronázási ékszere?", "A Szent Korona", "Az Aranybulla", "A jogar nélküli gyűrű", "A turulmadaras pajzs"),

  /* ========== MAGYAR TÖRTÉNELEM — Vegyesházi királyok és a Hunyadiak ========== */
  M("Melyik királyunk veretett először aranyforintot?", "Károly Róbert", "Szent István", "IV. Béla", "II. Lajos"),
  M("Melyik királyunk volt egyszerre magyar és lengyel király?", "Nagy Lajos", "Mátyás", "Szent István", "IV. Béla"),
  M("Melyik magyar király lett német-római császár is?", "Luxemburgi Zsigmond", "Mátyás", "Nagy Lajos", "II. Lajos"),
  M("Ki győzött 1456-ban a nándorfehérvári csatában?", "Hunyadi János", "Hunyadi Mátyás", "Dobó István", "Zrínyi Miklós"),
  M("Minek az emlékére szól máig a déli harangszó?", "A nándorfehérvári diadalnak", "A mohácsi csatának", "A honfoglalásnak", "Az államalapításnak"),
  M("Melyik városban született Hunyadi Mátyás?", "Kolozsváron", "Budán", "Szegeden", "Esztergomban"),
  M("Mi volt Mátyás király mellékneve?", "Az Igazságos", "A Hódító", "A Nagy", "A Bölcs"),
  M("Hogy hívták Mátyás király híres zsoldosseregét?", "Fekete sereg", "Vörös sereg", "Királyi gárda", "Vitézlő rend"),
  M("Hogy nevezték Mátyás király díszes kódexeit?", "Corvináknak", "Aranybulláknak", "Intelmeknek", "Krónikáknak"),
  M("Ki vezette az 1514-es parasztfelkelést?", "Dózsa György", "Hunyadi János", "Rákóczi Ferenc", "Bocskai István"),

  /* ========== MAGYAR TÖRTÉNELEM — Török kor ========== */
  M("Mikor volt a mohácsi csata?", "1526-ban", "1456-ban", "1241-ben", "1686-ban"),
  M("Ki ellen harcolt a magyar sereg Mohácsnál?", "A törökök ellen", "A tatárok ellen", "Az osztrákok ellen", "A németek ellen"),
  M("Melyik magyar király esett el a mohácsi csatában?", "II. Lajos", "Mátyás", "Szent László", "IV. Béla"),
  M("Melyik szultán vezette a törököket Mohácsnál?", "Szulejmán", "Szaladin", "Oszmán", "Musztafa"),
  M("Hány részre szakadt Magyarország a török korban?", "Három részre", "Két részre", "Négy részre", "Öt részre"),
  M("Ki védte meg Eger várát 1552-ben?", "Dobó István", "Zrínyi Miklós", "Hunyadi János", "Rákóczi Ferenc"),
  M("Melyik regény meséli el az egri vár ostromát?", "Az Egri csillagok", "A Pál utcai fiúk", "A kőszívű ember fiai", "Az aranyember"),
  M("Ki írta az Egri csillagokat?", "Gárdonyi Géza", "Jókai Mór", "Petőfi Sándor", "Molnár Ferenc"),
  M("Ki volt a szigetvári hős, aki 1566-ban kirohant a várból?", "Zrínyi Miklós", "Dobó István", "Hunyadi János", "Bocskai István"),
  M("Kik voltak a hajdúk, akiket Bocskai István letelepített?", "Vitéz szabadcsapatok katonái", "Török adószedők", "Osztrák hivatalnokok", "Olasz kereskedők"),
  M("Melyik erdélyi fejedelem korát nevezik Erdély aranykorának?", "Bethlen Gábor korát", "Dózsa György korát", "II. Lajos korát", "Könyves Kálmán korát"),
  M("Mikor foglalták vissza Budát a töröktől?", "1686-ban", "1526-ban", "1552-ben", "1848-ban"),
  M("Melyik várat védte hősiesen Zrínyi Ilona?", "Munkács várát", "Eger várát", "Szigetvárt", "Buda várát"),

  /* ========== MAGYAR TÖRTÉNELEM — Rákóczi és a reformkor ========== */
  M("Ki vezette az 1703-ban kezdődött szabadságharcot?", "II. Rákóczi Ferenc", "Kossuth Lajos", "Széchenyi István", "Dózsa György"),
  M("Hogy hívták Rákóczi katonáit?", "Kurucoknak", "Labancoknak", "Huszároknak", "Hajdúknak"),
  M("Hogy hívták a Habsburgok oldalán álló katonákat?", "Labancoknak", "Kurucoknak", "Janicsároknak", "Gárdistáknak"),
  M("Melyik török városban élte le száműzetését Rákóczi?", "Rodostóban", "Isztambulban", "Ankarában", "Kairóban"),
  M("Ki írta a híres törökországi leveleket Rákóczi udvarából?", "Mikes Kelemen", "Petőfi Sándor", "Kölcsey Ferenc", "Arany János"),
  M("Melyik Habsburg uralkodónőnek ajánlották a magyar rendek életüket és vérüket?", "Mária Teréziának", "Erzsébet királynénak", "Zita királynénak", "Viktóriának"),
  M("Ki vezette a magyar nyelvújítást?", "Kazinczy Ferenc", "Petőfi Sándor", "Arany János", "Jókai Mór"),
  M("Kit nevezünk a legnagyobb magyarnak?", "Széchenyi Istvánt", "Kossuth Lajost", "Petőfi Sándort", "Deák Ferencet"),
  M("Melyik híres dunai híd fűződik Széchenyi nevéhez?", "A Lánchíd", "Az Erzsébet híd", "A Margit híd", "A Szabadság híd"),
  M("Melyik tudós társaság alapítására ajánlotta fel Széchenyi egyévi jövedelmét?", "A Magyar Tudományos Akadémiáéra", "Az első egyetemére", "A Nemzeti Színházéra", "Az első bankéra"),
  M("Ki kezdeményezte a Tisza szabályozását?", "Széchenyi István", "Kossuth Lajos", "Petőfi Sándor", "Görgei Artúr"),
  M("Kiről nevezték el a Lánchíd budai hídfőjének terét?", "Clark Ádámról", "Széchenyi Istvánról", "Kossuth Lajosról", "Deák Ferencről"),
  M("Kit neveztek árvízi hajósnak az 1838-as pesti árvíz idején?", "Wesselényi Miklóst", "Széchenyi Istvánt", "Kossuth Lajost", "Petőfi Sándort"),
  M("Mikor épült meg az első magyar vasútvonal Pest és Vác között?", "1846-ban", "1746-ban", "1896-ban", "1920-ban"),
  M("Ki írta a Himnuszt?", "Kölcsey Ferenc", "Vörösmarty Mihály", "Petőfi Sándor", "Arany János"),
  M("Ki zenésítette meg a Himnuszt?", "Erkel Ferenc", "Liszt Ferenc", "Bartók Béla", "Kodály Zoltán"),
  M("Ki írta a Szózatot?", "Vörösmarty Mihály", "Kölcsey Ferenc", "Petőfi Sándor", "Ady Endre"),
  M("Ki írta a Bánk bán című drámát?", "Katona József", "Erkel Ferenc", "Madách Imre", "Jókai Mór"),
  M("Ki komponálta a Bánk bán című operát?", "Erkel Ferenc", "Katona József", "Liszt Ferenc", "Bartók Béla"),

  /* ========== MAGYAR TÖRTÉNELEM — 1848–49 ========== */
  M("Mikor tört ki a pesti forradalom?", "1848. március 15-én", "1849. október 6-án", "1867. június 8-án", "1956. október 23-án"),
  M("Ki szavalta el a Nemzeti dalt a Nemzeti Múzeumnál?", "Petőfi Sándor", "Arany János", "Kossuth Lajos", "Vörösmarty Mihály"),
  M("Hogyan kezdődik a Nemzeti dal?", "Talpra magyar, hí a haza!", "Hazádnak rendületlenül!", "Isten, áldd meg a magyart!", "Még kér a nép!"),
  M("Mi volt a márciusi ifjak 12 pontjának első követelése?", "Sajtószabadság", "Új király", "Vasútépítés", "Adómentesség"),
  M("Ki volt az első felelős magyar kormány miniszterelnöke?", "Batthyány Lajos", "Kossuth Lajos", "Széchenyi István", "Deák Ferenc"),
  M("Ki lett a szabadságharc kormányzó-elnöke?", "Kossuth Lajos", "Batthyány Lajos", "Görgei Artúr", "Petőfi Sándor"),
  M("Melyik lengyel származású tábornok lett a székelyek legendás vezére?", "Bem József", "Görgei Artúr", "Klapka György", "Damjanich János"),
  M("Hol tette le a fegyvert a magyar sereg 1849-ben?", "Világosnál", "Mohácsnál", "Muhinál", "Aradon"),
  M("Ki volt a szabadságharc fővezére, aki Világosnál letette a fegyvert?", "Görgei Artúr", "Bem József", "Kossuth Lajos", "Batthyány Lajos"),
  M("Hány vértanút végeztek ki Aradon 1849. október 6-án?", "Tizenhármat", "Hetet", "Húszat", "Hármat"),
  M("Melyik csatában tűnt el Petőfi Sándor?", "A segesvári csatában", "A mohácsi csatában", "A muhi csatában", "Az augsburgi csatában"),
  M("Ki volt Petőfi Sándor felesége?", "Szendrey Júlia", "Laborfalvi Róza", "Erzsébet királyné", "Lónyay Erzsébet"),

  /* ========== MAGYAR TÖRTÉNELEM — Kiegyezéstől a millenniumig ========== */
  M("Melyik évben volt a kiegyezés?", "1867-ben", "1848-ban", "1920-ban", "1896-ban"),
  M("Kit neveznek a haza bölcsének?", "Deák Ferencet", "Kossuth Lajost", "Széchenyi Istvánt", "Batthyány Lajost"),
  M("Kit koronáztak magyar királlyá 1867-ben?", "Ferenc Józsefet", "Ferenc Ferdinándot", "IV. Károlyt", "Miksát"),
  M("Ki volt Sisi, a magyarok kedvelt királynéja?", "Erzsébet királyné", "Mária Terézia", "Zita királyné", "Viktória királynő"),
  M("Minek az ezredik évfordulóját ünnepelte az ország 1896-ban?", "A honfoglalásnak", "Az államalapításnak", "A kiegyezésnek", "A mohácsi csatának"),
  M("Milyen közlekedési újdonság épült a millenniumra Budapesten?", "A földalatti vasút", "Az első villamos", "A fogaskerekű", "A libegő"),
  M("Melyik budapesti tér épült a millenniumi ünnepségekre?", "A Hősök tere", "A Kossuth tér", "A Deák tér", "A Móricz Zsigmond körtér"),
  M("Ki tervezte az Országházat?", "Steindl Imre", "Ybl Miklós", "Pollack Mihály", "Lechner Ödön"),
  M("Ki tervezte a Magyar Nemzeti Múzeumot?", "Pollack Mihály", "Steindl Imre", "Ybl Miklós", "Clark Ádám"),
  M("Ki tervezte a budapesti Operaházat?", "Ybl Miklós", "Pollack Mihály", "Steindl Imre", "Lechner Ödön"),
  M("Ki írta a Toldit?", "Arany János", "Petőfi Sándor", "Jókai Mór", "Madách Imre"),
  M("Ki írta Az ember tragédiáját?", "Madách Imre", "Katona József", "Arany János", "Vörösmarty Mihály"),
  M("Ki írta A Pál utcai fiúkat?", "Molnár Ferenc", "Gárdonyi Géza", "Móricz Zsigmond", "Karinthy Frigyes"),
  M("Ki írta A kőszívű ember fiait?", "Jókai Mór", "Gárdonyi Géza", "Mikszáth Kálmán", "Móricz Zsigmond"),
  M("Melyik magyar orvost nevezik az anyák megmentőjének?", "Semmelweis Ignácot", "Szent-Györgyi Albertet", "Selye Jánost", "Bay Zoltánt"),
  M("Mit vezetett be Semmelweis Ignác a szülészeten?", "A kézfertőtlenítést", "Az altatást", "A röntgent", "A védőoltást"),
  M("Ki komponálta a Magyar rapszódiákat?", "Liszt Ferenc", "Erkel Ferenc", "Bartók Béla", "Kodály Zoltán"),
  M("Melyik két zeneszerző járta a falvakat magyar népdalokat gyűjteni?", "Bartók Béla és Kodály Zoltán", "Liszt Ferenc és Erkel Ferenc", "Lehár Ferenc és Kálmán Imre", "Erkel Ferenc és Liszt Ferenc"),
  M("Melyik magyar feltaláló alkotta meg a telefonhírmondót?", "Puskás Tivadar", "Bíró László", "Jedlik Ányos", "Irinyi János"),
  M("Melyik magyar bencés szerzetes-tudós alkotta meg az első dinamót?", "Jedlik Ányos", "Irinyi János", "Puskás Tivadar", "Bláthy Ottó"),

  /* ========== MAGYAR TÖRTÉNELEM — A 20. század ========== */
  M("Melyik birodalom trónörököse volt Ferenc Ferdinánd?", "Az Osztrák–Magyar Monarchiáé", "A Német Birodalomé", "Az Orosz Birodalomé", "A Török Birodalomé"),
  M("Mikor bomlott fel az Osztrák–Magyar Monarchia?", "1918-ban", "1867-ben", "1945-ben", "1848-ban"),
  M("Ki volt az őszirózsás forradalom után az első köztársasági elnök?", "Károlyi Mihály", "Horthy Miklós", "Kun Béla", "Tisza István"),
  M("Ki vezette az 1919-es Tanácsköztársaságot?", "Kun Béla", "Károlyi Mihály", "Horthy Miklós", "Kádár János"),
  M("Mikor írták alá a trianoni békediktátumot?", "1920-ban", "1918-ban", "1945-ben", "1867-ben"),
  M("Hol írták alá a trianoni békét?", "Párizs mellett, a Trianon-palotában", "Bécsben", "Londonban", "Berlinben"),
  M("Területének körülbelül mekkora részét vesztette el Magyarország Trianonban?", "Kétharmadát", "Egytizedét", "Felét", "Egyharmadát"),
  M("Ki volt Magyarország kormányzója a két világháború között?", "Horthy Miklós", "Kádár János", "Rákosi Mátyás", "Károlyi Mihály"),
  M("Ki mentett meg több ezer budapesti üldözöttet 1944-ben svéd menlevelekkel?", "Raoul Wallenberg", "Winston Churchill", "Charles de Gaulle", "Oskar Schindler"),
  M("Melyik évben ért véget Budapest ostroma?", "1945-ben", "1944-ben", "1956-ban", "1939-ben"),
  M("Melyik pénzt váltotta fel a forint 1946-ban?", "A pengőt", "A koronát", "A dénárt", "Az eurót"),
  M("Miről nevezetes a pengő utolsó időszaka?", "A világtörténelem legnagyobb inflációjáról", "Aranyból verték", "A leghosszabb ideig használt pénz volt", "Csak papírból készült"),
  M("Ki volt az ötvenes évek rettegett kommunista diktátora Magyarországon?", "Rákosi Mátyás", "Kádár János", "Nagy Imre", "Horthy Miklós"),
  M("Mikor tört ki az 1956-os forradalom?", "Október 23-án", "Március 15-én", "Augusztus 20-án", "Október 6-án"),
  M("Ki volt az 1956-os forradalom miniszterelnöke?", "Nagy Imre", "Kádár János", "Rákosi Mátyás", "Antall József"),
  M("Mi lett az 1956-os forradalom egyik legfőbb jelképe?", "A lyukas zászló", "A fekete zászló", "A fehér galamb", "A vörös csillag"),
  M("Melyik szobrot döntötte le a tömeg 1956. október 23-án?", "A Sztálin-szobrot", "A Lenin-szobrot", "A Kossuth-szobrot", "A Szabadság-szobrot"),
  M("Hogy nevezték az 1956-ban harcoló fiatal felkelőket?", "Pesti srácoknak", "Kurucoknak", "Honvédeknek", "Hajdúknak"),
  M("Mi lett Nagy Imre sorsa a forradalom leverése után?", "Kivégezték", "Külföldre menekült", "Visszatérhetett a politikába", "Börtönben halt meg öregkorában"),
  M("Ki vezette Magyarországot 1956 után több mint három évtizeden át?", "Kádár János", "Rákosi Mátyás", "Nagy Imre", "Antall József"),
  M("Mikor temették újra ünnepélyesen Nagy Imrét?", "1989-ben", "1958-ban", "1990-ben", "2000-ben"),
  M("Hol nyitották meg a határt a keletnémet menekültek előtt a páneurópai pikniken?", "Sopronnál", "Szegednél", "Debrecennél", "Pécsnél"),
  M("Mikor volt a rendszerváltás Magyarországon?", "1989–90-ben", "1956-ban", "1978-ban", "2004-ben"),
  M("Ki volt a rendszerváltás utáni első szabadon választott miniszterelnök?", "Antall József", "Göncz Árpád", "Horn Gyula", "Németh Miklós"),
  M("Ki volt a rendszerváltás utáni első köztársasági elnök?", "Göncz Árpád", "Antall József", "Mádl Ferenc", "Sólyom László"),
  M("Melyik világhírű regényt fordította magyarra Göncz Árpád?", "A Gyűrűk Urát", "A Harry Pottert", "Az Egri csillagokat", "A Micimackót"),
  M("Mikor tért haza a Szent Korona az Egyesült Államokból?", "1978-ban", "1946-ban", "1990-ben", "2000-ben"),
  M("Mikor lépett be Magyarország a NATO-ba?", "1999-ben", "2004-ben", "1989-ben", "1956-ban"),
  M("Mikor csatlakozott Magyarország az Európai Unióhoz?", "2004-ben", "1999-ben", "1990-ben", "2010-ben"),
  M("Mit ünneplünk augusztus 20-án?", "Az államalapítást és Szent Istvánt", "Az 1848-as forradalmat", "Az 1956-os forradalmat", "A honfoglalást"),
  M("Mire emlékezünk október 6-án?", "Az aradi vértanúkra", "Az 1956-os forradalomra", "A mohácsi csatára", "A kiegyezésre"),
  M("Mire emlékezünk március 15-én?", "Az 1848-as forradalomra", "Az 1956-os forradalomra", "Trianonra", "Az államalapításra"),

  /* ========== MAGYAR TÖRTÉNELEM — Feltalálók, tudósok, művészek, sport ========== */
  M("Miért kapott Nobel-díjat Szent-Györgyi Albert?", "A C-vitamin kutatásáért", "A penicillinért", "A röntgensugárzásért", "A DNS felfedezéséért"),
  M("Melyik magyar városban kutatta Szent-Györgyi a paprikát?", "Szegeden", "Debrecenben", "Pécsett", "Győrben"),
  M("Mit talált fel Rubik Ernő?", "A bűvös kockát", "A golyóstollat", "A gyufát", "A helikoptert"),
  M("Melyik magyar feltaláló alkotta meg a golyóstollat?", "Bíró László", "Rubik Ernő", "Irinyi János", "Jedlik Ányos"),
  M("Ki találta fel a zajtalanul gyulladó biztonsági gyufát?", "Irinyi János", "Bíró László", "Puskás Tivadar", "Kandó Kálmán"),
  M("Melyik magyar mérnök volt a villamos vasút úttörője?", "Kandó Kálmán", "Bíró László", "Irinyi János", "Rubik Ernő"),
  M("Melyik magyar tudóst tartják a modern számítógép egyik atyjának?", "Neumann Jánost", "Teller Edét", "Szilárd Leót", "Gábor Dénest"),
  M("Melyik magyar fizikust nevezik a hidrogénbomba atyjának?", "Teller Edét", "Neumann Jánost", "Wigner Jenőt", "Bay Zoltánt"),
  M("Ki kapott Nobel-díjat a holográfia feltalálásáért?", "Gábor Dénes", "Wigner Jenő", "Hevesy György", "Szent-Györgyi Albert"),
  M("Melyik magyar író kapott irodalmi Nobel-díjat 2002-ben?", "Kertész Imre", "Jókai Mór", "Márai Sándor", "Móricz Zsigmond"),
  M("Ki volt az Aranycsapat legendás kapitánya?", "Puskás Ferenc", "Grosics Gyula", "Hidegkuti Nándor", "Kocsis Sándor"),
  M("Melyik évben győzte le az Aranycsapat Angliát Londonban 6:3-ra?", "1953-ban", "1954-ben", "1966-ban", "1938-ban"),
  M("Melyik csapattól szenvedett vereséget a magyar válogatott az 1954-es vb-döntőben?", "A nyugatnémet csapattól", "A brazil csapattól", "Az angol csapattól", "Az olasz csapattól"),
  M("Melyik spanyol klubban lett világsztár Puskás Ferenc?", "A Real Madridban", "A Barcelonában", "A Sevillában", "A Valenciában"),
  M("Melyik magyar úszónő nyert olimpiai aranyat már 14 évesen 1988-ban?", "Egerszegi Krisztina", "Hosszú Katinka", "Kovács Ágnes", "Darnyi Tamásné"),
  M("Melyik magyar öklöző nyert három olimpiai aranyérmet?", "Papp László", "Puskás Ferenc", "Balczó András", "Kokó"),
  M("Melyik városban készül a világhírű Zsolnay porcelán?", "Pécsett", "Herenden", "Szegeden", "Miskolcon"),
  M("Melyik faluban készül a híres herendi porcelán?", "Herenden", "Pécsett", "Kalocsán", "Hollóházán... Tokajban"),
  M("Melyik magyar bort nevezte XIV. Lajos a királyok borának?", "A tokaji aszút", "Az egri bikavért", "A villányi vörösbort", "A badacsonyi szürkebarátot"),
  M("Kiknek az ételéből lett a világhírű gulyás?", "A pásztorokéból", "A halászokéból", "A királyi szakácsokéból", "A katonákéból"),
  M("Melyik két város híres a magyar fűszerpaprikáról?", "Szeged és Kalocsa", "Debrecen és Miskolc", "Pécs és Győr", "Eger és Tokaj"),
  M("Melyik magyar találmány hódította meg a világot 1974 után színes forgatható kockaként?", "A Rubik-kocka", "A dinamó", "A golyóstoll", "A gyufa"),
  M("Melyik magyar mérnökcsoport alkotta meg a transzformátort?", "Bláthy, Déri és Zipernowsky", "Bánki és Csonka", "Irinyi és Jedlik", "Puskás és Bíró"),
  M("Mit alkotott meg Bánki Donát és Csonka János?", "A porlasztót (karburátort)", "A telefont", "A villanykörtét", "A gőzmozdonyt"),
  M("Melyik magyar vegyész kapott Nobel-díjat a radioaktív nyomjelzésért?", "Hevesy György", "Szent-Györgyi Albert", "Oláh György", "Wigner Jenő"),

  /* ========== VILÁGTÖRTÉNELEM MAGYARUL — Ókor ========== */
  M("Melyik nép építette a gízai piramisokat?", "Az egyiptomiak", "A rómaiak", "A görögök", "A perzsák"),
  M("Hogy hívják az ókori Egyiptom képírását?", "Hieroglifáknak", "Rovásírásnak", "Cirill betűknek", "Ékírásnak"),
  M("Ki volt Egyiptom híres királynője?", "Kleopátra", "Mária Terézia", "Viktória", "Erzsébet"),
  M("Melyik országban rendezték az ókori olimpiai játékokat?", "Görögországban", "Itáliában", "Egyiptomban", "Perzsiában"),
  M("Melyik ókori városban született a demokrácia?", "Athénban", "Rómában", "Spártában", "Trójában"),
  M("Melyik ókori görög város volt híres kemény harcosairól?", "Spárta", "Athén", "Trója", "Olümpia"),
  M("Milyen csellel jutottak be a görögök Trójába?", "Egy hatalmas falóval", "Alagutat ástak", "Létrákkal másztak be éjjel", "Megvesztegették az őröket"),
  M("Ki volt a világhódító makedón király?", "Nagy Sándor", "Julius Caesar", "Attila", "Hannibál"),
  M("Milyen nyelven beszéltek az ókori rómaiak?", "Latinul", "Görögül", "Olaszul", "Spanyolul"),
  M("Ki volt Róma híres hadvezére, akit március idusán gyilkoltak meg?", "Julius Caesar", "Augustus", "Néró", "Hadrianus"),
  M("Hogy hívják Róma hatalmas ókori arénáját?", "Colosseum", "Parthenon", "Akropolisz", "Fórum Palota"),
  M("Melyik vulkán temette be Pompeji városát?", "A Vezúv", "Az Etna", "A Fudzsi", "A Kilauea"),
  M("Milyen állatokkal kelt át Hannibál az Alpokon?", "Elefántokkal", "Tevékkel", "Lovakkal", "Bivalyokkal"),
  M("Ki volt Róma első császára?", "Augustus", "Julius Caesar", "Néró", "Hadrianus"),
  M("Miért épült a kínai nagy fal?", "A támadók távoltartására", "Árvizek ellen", "Kereskedelmi útnak", "A császár palotájának"),
  M("Kik harcoltak a római arénákban a nép szórakoztatására?", "Gladiátorok", "Szamurájok", "Lovagok", "Vikingek"),
  M("Melyik folyó éltette az ókori Egyiptomot?", "A Nílus", "A Duna", "A Tigris", "Az Amazonas"),
  M("Hogyan őrizték meg az egyiptomiak halottaikat?", "Múmiaként", "Hamvasztással", "Jégbe fagyasztva", "Tengerbe temetve"),
  M("Ki írta az Iliász és az Odüsszeia eposzokat?", "Homérosz", "Szophoklész", "Platón", "Arisztotelész"),
  M("Melyik görög filozófus volt Nagy Sándor nevelője?", "Arisztotelész", "Szókratész", "Platón", "Püthagorasz"),
  M("Melyik görög filozófust ítélték bürökpohár kiivására?", "Szókratészt", "Arisztotelészt", "Homéroszt", "Euklidészt"),
  M("Ki kiáltotta a fürdőben: Heuréka!?", "Arkhimédész", "Arisztotelész", "Homérosz", "Nagy Sándor"),
  M("Melyik kis folyón kelt át Caesar e szavakkal: a kocka el van vetve?", "A Rubiconon", "A Níluson", "A Dunán", "A Tiberisen"),
  M("Ki vezette a rabszolgák nagy felkelését Róma ellen?", "Spartacus", "Hannibál", "Augustus", "Attila"),
  M("Nagyjából mikor bukott meg a Nyugatrómai Birodalom?", "476-ban", "1000-ben", "100-ban", "1492-ben"),
  M("Melyik országban találták meg az agyagkatonák hadseregét?", "Kínában", "Egyiptomban", "Görögországban", "Mexikóban"),
  M("Mit kötött össze a selyemút?", "Kínát és Európát", "Afrikát és Amerikát", "Rómát és Egyiptomot", "Indiát és Ausztráliát"),
  M("Milyen növényből készítettek írólapot az egyiptomiak?", "Papiruszból", "Bambuszból", "Tölgyfakéregből", "Gyapotból"),
  M("Minek a testét kapta a gízai nagy szfinx?", "Oroszlánét", "Lóét", "Sasét", "Krokodilét"),

  /* ========== VILÁGTÖRTÉNELEM MAGYARUL — Középkor és újkor ========== */
  M("Kit koronáztak császárrá 800 karácsonyán Rómában?", "Nagy Károlyt", "Napóleont", "Caesart", "Barbarossa Frigyest"),
  M("Honnan jöttek a rettegett viking harcosok?", "Skandináviából", "Afrikából", "Ázsiából", "Dél-Amerikából"),
  M("Ki egyesítette hatalmas birodalomba a mongol törzseket?", "Dzsingisz kán", "Attila", "Szulejmán", "Nagy Sándor"),
  M("Melyik itáliai utazó jutott el Kínába a 13. században?", "Marco Polo", "Kolumbusz", "Magellán", "Vasco da Gama"),
  M("Melyik szent városért folytak a keresztes hadjáratok?", "Jeruzsálemért", "Rómáért", "Athénért", "Párizsért"),
  M("Mi volt a fekete halál, amely a 14. században végigsöpört Európán?", "Pestisjárvány", "Nagy tűzvész", "Éhínség", "Háború"),
  M("Melyik francia hőslány vezette győzelemre a francia sereget?", "Jeanne d'Arc", "Marie Antoinette", "Marie Curie", "Sisi"),
  M("Mikor foglalták el a törökök Konstantinápolyt?", "1453-ban", "1066-ban", "1215-ben", "1776-ban"),
  M("Hogy hívják ma Konstantinápolyt?", "Isztambulnak", "Athénnak", "Ankarának", "Kairónak"),
  M("Ki találta fel a könyvnyomtatást Európában?", "Johannes Gutenberg", "Thomas Edison", "Leonardo da Vinci", "Alexander Graham Bell"),
  M("Mi volt Gutenberg első nagy nyomtatott könyve?", "A Biblia", "Egy szakácskönyv", "Egy szótár", "Egy meséskönyv"),
  M("Ki festette a Mona Lisát?", "Leonardo da Vinci", "Michelangelo", "Picasso", "Van Gogh"),
  M("Ki festette ki a Sixtus-kápolna mennyezetét?", "Michelangelo", "Leonardo da Vinci", "Raffaello", "Rembrandt"),
  M("Melyik országban született a reneszánsz?", "Itáliában", "Angliában", "Franciaországban", "Egyiptomban"),
  M("Melyik évben ért partot Kolumbusz Amerikában?", "1492-ben", "1526-ban", "1776-ban", "1215-ben"),
  M("Melyik ország zászlaja alatt hajózott Kolumbusz?", "Spanyolországé", "Portugáliáé", "Angliáé", "Itáliáé"),
  M("Kinek az expedíciója kerülte meg elsőként a Földet?", "Magelláné", "Kolumbuszé", "Marco Polóé", "Vasco da Gamáé"),
  M("Melyik mai országban élt az azték birodalom?", "Mexikóban", "Peruban", "Egyiptomban", "Indiában"),
  M("Melyik nép építette a Machu Picchut?", "Az inkák", "Az aztékok", "A rómaiak", "A vikingek"),
  M("Ki írta a Rómeó és Júliát?", "William Shakespeare", "Charles Dickens", "Jókai Mór", "Molière"),
  M("Melyik angol királynak volt hat felesége?", "VIII. Henriknek", "Oroszlánszívű Richárdnak", "György királynak", "Vilmos hercegnek"),
  M("Ki indította el a reformációt 1517-ben?", "Luther Márton", "Kálvin János", "VIII. Henrik", "Gutenberg"),
  M("Ki hirdette, hogy a Föld kering a Nap körül?", "Kopernikusz", "Arisztotelész", "Ptolemaiosz", "Newton"),
  M("Melyik tudóst állították bíróság elé, mert a Föld mozgását tanította?", "Galileit", "Newtont", "Darwint", "Einsteint"),
  M("Milyen műszerrel kutatta Galilei az eget?", "Távcsővel", "Mikroszkóppal", "Iránytűvel", "Nagyítóval"),
  M("Ki volt Oroszország első cárja?", "Rettegett Iván", "Nagy Péter", "Nagy Katalin", "II. Miklós"),
  M("Melyik orosz cár építtette Szentpétervárt?", "Nagy Péter", "Rettegett Iván", "II. Miklós", "Lenin"),
  M("Melyik francia király építtette a versailles-i palotát?", "XIV. Lajos, a Napkirály", "Napóleon", "Nagy Károly", "XVI. Lajos"),
  M("Mi volt XIV. Lajos híres mellékneve?", "A Napkirály", "Az Oroszlánszívű", "A Rettegett", "A Bölcs"),
  M("Mikor égett le London nagy része a nagy tűzvészben?", "1666-ban", "1566-ban", "1766-ban", "1866-ban"),
  M("Kinek a fejére esett a legenda szerint az alma?", "Isaac Newtonéra", "Galileiére", "Einsteinére", "Darwinéra"),
  M("Milyen természeti erőt magyarázott meg Newton?", "A gravitációt", "Az elektromosságot", "A mágnesességet", "A hangot"),
  M("Hány évesen kezdett zenét szerezni Mozart?", "Öt évesen", "Tizenöt évesen", "Húsz évesen", "Harminc évesen"),
  M("Melyik országban született Mozart?", "Ausztriában", "Németországban", "Itáliában", "Magyarországon"),
  M("Melyik zeneszerző alkotott tovább süketen is?", "Beethoven", "Mozart", "Bach", "Vivaldi"),
  M("Ki komponálta A négy évszakot?", "Vivaldi", "Mozart", "Beethoven", "Liszt"),

  /* ========== VILÁGTÖRTÉNELEM MAGYARUL — Forradalmak kora ========== */
  M("Mikor tört ki a nagy francia forradalom?", "1789-ben", "1848-ban", "1492-ben", "1914-ben"),
  M("Melyik párizsi börtönt rohamozta meg a nép 1789-ben?", "A Bastille-t", "A Louvre-t", "A Towert", "A Konciergerie-t... Rómában"),
  M("Melyik francia királynénak tulajdonítják tévesen: Egyenek kalácsot!?", "Marie Antoinette-nek", "Jeanne d'Arcnak", "Sisinek", "Viktóriának"),
  M("Milyen szerkezettel végezték ki a francia forradalom elítéltjeit?", "Guillotine-nal", "Karddal", "Máglyán", "Kötéllel"),
  M("Melyik szigeten született Napóleon?", "Korzikán", "Elbán", "Szent Ilonán", "Szicílián"),
  M("Hol szenvedte el Napóleon a végső vereséget 1815-ben?", "Waterloonál", "Trafalgarnál", "Mohácsnál", "Verdunnél"),
  M("Melyik szigetre száműzték Napóleont végleg?", "Szent Ilonára", "Elbára", "Korzikára", "Máltára"),
  M("Melyik admirális győzte le a francia flottát Trafalgarnál?", "Nelson", "Drake", "Cook", "Kolumbusz"),
  M("Melyik királynő uralkodott Nagy-Britanniában a 19. század nagy részében?", "Viktória", "I. Erzsébet", "II. Erzsébet", "Anna"),
  M("Ki dolgozta ki az evolúció elméletét?", "Charles Darwin", "Isaac Newton", "Albert Einstein", "Galilei"),
  M("Ki találta fel a dinamitot, és alapította a híres díjakat?", "Alfred Nobel", "Thomas Edison", "Marie Curie", "Rubik Ernő"),
  M("Ki kapott elsőként két Nobel-díjat?", "Marie Curie", "Einstein", "Szent-Györgyi Albert", "Fleming"),
  M("Ki fedezte fel a veszettség elleni oltást?", "Louis Pasteur", "Alexander Fleming", "Semmelweis Ignác", "Jonas Salk"),
  M("Ki írta a Karácsonyi éneket a fösvény Scrooge-ról?", "Charles Dickens", "Shakespeare", "Andersen", "Jókai Mór"),
  M("Ki festette a híres Napraforgókat?", "Vincent van Gogh", "Leonardo da Vinci", "Michelangelo", "Munkácsy Mihály"),
  M("Ki komponálta A diótörő című balettet?", "Csajkovszkij", "Mozart", "Liszt Ferenc", "Verdi"),
  M("Hol rendezték az első újkori olimpiát 1896-ban?", "Athénban", "Párizsban", "Londonban", "Budapesten"),
  M("Milyen alkalomra épült az Eiffel-torony?", "Az 1889-es világkiállításra", "Az olimpiára", "Napóleon koronázására", "A forradalom századik... ötvenedik évfordulójára"),
  M("Melyik két tengert köti össze a Szuezi-csatorna?", "A Földközi-tengert és a Vörös-tengert", "A Fekete-tengert és a Kaszpi-tengert", "Az Atlanti- és a Csendes-óceánt", "Az Északi- és a Balti-tengert"),
  M("Melyik országot sújtotta a nagy burgonyavész az 1840-es években?", "Írországot", "Franciaországot", "Lengyelországot", "Svédországot"),

  /* ========== VILÁGTÖRTÉNELEM MAGYARUL — A 20. század ========== */
  M("Melyik évben süllyedt el a Titanic?", "1912-ben", "1905-ben", "1923-ban", "1898-ban"),
  M("Mivel ütközött össze a Titanic?", "Egy jégheggyel", "Egy másik hajóval", "Egy bálnával", "Egy zátonnyal... a kikötőben"),
  M("Melyik évben tört ki az első világháború?", "1914-ben", "1939-ben", "1918-ban", "1900-ban"),
  M("Kinek a meggyilkolása robbantotta ki az első világháborút?", "Ferenc Ferdinándé", "Ferenc Józsefé", "Lincolné", "II. Miklósé"),
  M("Melyik városban gyilkolták meg Ferenc Ferdinándot?", "Szarajevóban", "Bécsben", "Budapesten", "Belgrádban"),
  M("Mikor ért véget az első világháború?", "1918-ban", "1914-ben", "1945-ben", "1920-ban"),
  M("Melyik évben volt az oroszországi forradalom?", "1917-ben", "1905-ben", "1939-ben", "1848-ban"),
  M("Ki vezette az 1917-es orosz forradalmat?", "Lenin", "Sztálin", "II. Miklós", "Gorbacsov"),
  M("Ki volt az utolsó orosz cár?", "II. Miklós", "Nagy Péter", "Rettegett Iván", "I. Sándor"),
  M("Melyik évben kezdődött a második világháború?", "1939-ben", "1914-ben", "1945-ben", "1929-ben"),
  M("Ki volt Németország diktátora a második világháborúban?", "Adolf Hitler", "Sztálin", "Mussolini", "Vilmos császár"),
  M("Ki volt Nagy-Britannia híres miniszterelnöke a második világháborúban?", "Winston Churchill", "Margaret Thatcher", "Tony Blair", "Chamberlain... Amerikában"),
  M("Hol szálltak partra a szövetségesek 1944. június 6-án?", "Normandiában", "Szicíliában", "Görögországban", "Hollandiában"),
  M("Mikor ért véget a második világháború?", "1945-ben", "1939-ben", "1918-ban", "1950-ben"),
  M("Melyik városra dobták az első atombombát?", "Hirosimára", "Tokióra", "Berlinre", "Nagaszakira... elsőként"),
  M("Kiről nevezetes a világhírű amszterdami napló?", "Anne Frankról", "Sisiről", "Marie Curie-ről", "Florence Nightingale-ről"),
  M("Melyik két nagyhatalom állt szemben a hidegháborúban?", "Az USA és a Szovjetunió", "Anglia és Franciaország", "Kína és Japán", "Németország és Itália"),
  M("Melyik várost osztotta ketté a hírhedt fal?", "Berlint", "Párizst", "Bécset", "Moszkvát"),
  M("Mikor omlott le a berlini fal?", "1989-ben", "1969-ben", "1999-ben", "1979-ben"),
  M("Mi volt az első műhold neve?", "Szputnyik", "Apollo", "Voyager", "Hubble"),
  M("Ki volt az első ember a világűrben?", "Jurij Gagarin", "Neil Armstrong", "Buzz Aldrin", "John Glenn"),
  M("Ki volt az első nő a világűrben?", "Valentyina Tyereskova", "Sally Ride", "Amelia Earhart", "Marie Curie"),
  M("Ki lépett először a Holdra?", "Neil Armstrong", "Buzz Aldrin", "Jurij Gagarin", "John Glenn"),
  M("Melyik évben szállt le az ember a Holdon?", "1969-ben", "1959-ben", "1979-ben", "1949-ben"),
  M("Ki fedezte fel a penicillint?", "Alexander Fleming", "Louis Pasteur", "Semmelweis Ignác", "Marie Curie"),
  M("Melyik tudós híres a relativitáselméletről?", "Albert Einstein", "Isaac Newton", "Neumann János", "Galilei"),
  M("Ki vezette Indiát a függetlenséghez erőszakmentes úton?", "Mahatma Gandhi", "Nelson Mandela", "Churchill", "Buddha"),
  M("Ki lett Dél-Afrika első fekete elnöke?", "Nelson Mandela", "Mahatma Gandhi", "Desmond Tutu", "Kofi Annan"),
  M("Ki volt Nagy-Britannia első női miniszterelnöke?", "Margaret Thatcher", "Viktória királynő", "II. Erzsébet", "Diana hercegné"),
  M("Melyik lengyel pápa lett világszerte szeretett egyházfő 1978-ban?", "II. János Pál", "XXIII. János", "VI. Pál", "Ferenc pápa"),
  M("Melyik városban segítette Teréz anya a legszegényebbeket?", "Kalkuttában", "Kairóban", "Rómában", "Manilában"),
  M("Melyik atomerőműben történt súlyos baleset 1986-ban?", "Csernobilban", "Pakson", "Fukusimában", "Szarajevóban"),
  M("Mikor bomlott fel a Szovjetunió?", "1991-ben", "1985-ben", "1979-ben", "1999-ben"),
  M("Mikor egyesült újra Németország?", "1990-ben", "1980-ban", "2000-ben", "1970-ben"),
  M("Melyik alagút köti össze Angliát Franciaországgal?", "A Csalagút (Csatorna-alagút)", "A Szent Gotthárd-alagút", "A Mont Blanc-alagút", "A Boszporusz-alagút"),

  /* ========== AMERIKAI TÖRTÉNELEM MAGYARUL ========== */
  M("Mikor írták alá az amerikai Függetlenségi nyilatkozatot?", "1776-ban", "1620-ban", "1865-ben", "1492-ben"),
  M("Ki volt az Egyesült Államok első elnöke?", "George Washington", "Abraham Lincoln", "Thomas Jefferson", "Benjamin Franklin"),
  M("Melyik országtól vívta ki függetlenségét Amerika?", "Nagy-Britanniától", "Franciaországtól", "Spanyolországtól", "Hollandiától"),
  M("Melyik óceánon kelt át a zarándokok Mayflower hajója 1620-ban?", "Az Atlanti-óceánon", "A Csendes-óceánon", "Az Indiai-óceánon", "A Jeges-tengeren"),
  M("Ki volt az elnök az amerikai polgárháború idején?", "Abraham Lincoln", "George Washington", "Kennedy", "Roosevelt"),
  M("Mit törölt el az Egyesült Államokban a 13. alkotmánykiegészítés?", "A rabszolgaságot", "Az adókat", "A vasutat", "A királyságot"),
  M("Hogyan halt meg Abraham Lincoln?", "Merénylet áldozata lett egy színházban", "Betegségben hunyt el", "Csatában esett el", "Hajótörésben halt meg"),
  M("Mit kerestek az aranyásók Kaliforniában 1849-ben?", "Aranyat", "Ezüstöt", "Gyémántot", "Kőolajat"),
  M("Ki találta fel a villanykörtét?", "Thomas Edison", "Alexander Graham Bell", "Henry Ford", "Samuel Morse"),
  M("Ki találta fel a telefont?", "Alexander Graham Bell", "Thomas Edison", "Puskás Tivadar", "Samuel Morse"),
  M("Melyik autógyáros vezette be a futószalagos gyártást?", "Henry Ford", "Thomas Edison", "Rockefeller", "Carnegie"),
  M("Kik repültek elsőként motoros repülőgéppel 1903-ban?", "A Wright fivérek", "A Montgolfier fivérek", "Lindbergh és Earhart", "A Grimm fivérek"),
  M("Melyik országtól vásárolta meg Amerika Alaszkát?", "Oroszországtól", "Kanadától", "Franciaországtól", "Spanyolországtól"),
  M("Melyik ország ajándékozta Amerikának a Szabadság-szobrot?", "Franciaország", "Anglia", "Olaszország", "Spanyolország"),
  M("Melyik város kikötőjében áll a Szabadság-szobor?", "New Yorkéban", "Bostonéban", "Washingtonéban", "Los Angelesében"),
  M("Melyik évben omlott össze a New York-i tőzsde?", "1929-ben", "1919-ben", "1941-ben", "1956-ban"),
  M("Mi következett az 1929-es tőzsdekrach után?", "A nagy gazdasági világválság", "Az aranyláz", "A polgárháború", "A vadnyugat kora"),
  M("Melyik amerikai támaszpontot támadta meg Japán 1941-ben?", "Pearl Harbort", "New Yorkot", "San Franciscót", "Alaszkát"),
  M("Melyik elnök rendelte el az atombomba bevetését?", "Harry Truman", "Roosevelt", "Kennedy", "Eisenhower"),
  M("Melyik elnököt gyilkolták meg Dallasban 1963-ban?", "John F. Kennedyt", "Abraham Lincolnt", "Nixont", "Reagant"),
  M("Mi volt Martin Luther King leghíresebb beszédének címe?", "Van egy álmom", "Vér, veríték és könnyek", "A nép hangja", "Szabadság vagy halál"),
  M("Mit tagadott meg Rosa Parks a buszon?", "Nem adta át az ülőhelyét", "Nem fizetett jegyet", "Nem szállt le a végállomáson", "Nem mutatta meg iratait"),
  M("Melyik amerikai űrhajós mondta: Kis lépés egy embernek, hatalmas ugrás az emberiségnek?", "Neil Armstrong", "Buzz Aldrin", "John Glenn", "Gagarin"),
  M("Melyik botrányba bukott bele Nixon elnök?", "A Watergate-botrányba", "A teadélután-botrányba", "Az olajbotrányba", "A vasútbotrányba"),
  M("Kit neveztek a rock and roll királyának?", "Elvis Presleyt", "Frank Sinatrát", "Michael Jacksont", "Johnny Casht"),
  M("Ki alkotta meg Miki egér figuráját?", "Walt Disney", "Andersen", "A Grimm fivérek", "Chaplin"),
  M("Melyik hegyoldalba faragták négy amerikai elnök arcát?", "A Rushmore-hegybe", "A Sziklás-hegységbe", "A Grand Canyonba", "Az Appalache-okba"),
  M("Melyik amerikai elnök volt korábban hollywoodi színész?", "Ronald Reagan", "Jimmy Carter", "Nixon", "Kennedy"),
  M("Hány csillag van az amerikai zászlón?", "Ötven", "Negyvennyolc", "Ötvenkettő", "Tizenhárom"),
  M("Mit ünnepelnek az amerikaiak július 4-én?", "A függetlenség napját", "Az alkotmány napját", "A hálaadást", "Az elnök születésnapját"),

  /* ========== MÉG TÖBB MAGYAR MŰVELTSÉG ========== */
  M("Melyik magyar festő lett világhírű Párizsban a 19. században?", "Munkácsy Mihály", "Csontváry", "Rippl-Rónai", "Szinyei Merse Pál"),
  M("Mit ábrázol a Feszty-körkép?", "A magyarok bejövetelét", "A mohácsi csatát", "Buda visszafoglalását", "Az 1848-as forradalmat"),
  M("Melyik uralkodót nevezték kalapos királynak, mert nem koronáztatta meg magát?", "II. Józsefet", "Ferenc Józsefet", "Mária Teréziát", "V. Ferdinándot"),
  M("Hogyan halt meg Erzsébet királyné, Sisi?", "Merénylet áldozata lett Genfben", "Betegségben hunyt el Bécsben", "Lovasbalesetben halt meg", "Hajótörésben veszett oda"),
  M("Melyik olasz városban halt meg az emigráns Kossuth Lajos?", "Torinóban", "Rómában", "Velencében", "Milánóban"),
  M("Milyen politikát folytatott Deák Ferenc az önkényuralom éveiben?", "Passzív ellenállást", "Fegyveres harcot", "Nyílt együttműködést", "Emigrációt"),
  M("Melyik Arany János-ballada szól az elnyomott walesi énekesekről?", "A walesi bárdok", "A Toldi", "Az Ágnes asszony", "A Családi kör"),
  M("Ki írta a János vitézt?", "Petőfi Sándor", "Arany János", "Vörösmarty Mihály", "Gárdonyi Géza"),
  M("Ki írta Az arany ember című regényt?", "Jókai Mór", "Mikszáth Kálmán", "Móricz Zsigmond", "Gárdonyi Géza"),
  M("Ki írta a Szent Péter esernyője című regényt?", "Mikszáth Kálmán", "Jókai Mór", "Molnár Ferenc", "Karinthy Frigyes"),
  M("Melyik folyóirat volt a 20. század eleji magyar irodalom zászlóshajója?", "A Nyugat", "A Kelet", "A Hajnal", "Az Új Idők"),
  M("Ki írta a Mama című verset?", "József Attila", "Ady Endre", "Petőfi Sándor", "Radnóti Miklós"),
  M("Ki volt az első magyar olimpiai bajnok 1896-ban?", "Hajós Alfréd", "Puskás Ferenc", "Papp László", "Egerszegi Krisztina"),
  M("Ki volt az első magyar űrhajós?", "Farkas Bertalan", "Neumann János", "Teller Ede", "Bay Zoltán"),
  M("Melyik csapatsportban nyert Magyarország kilenc olimpiai aranyat?", "Vízilabdában", "Labdarúgásban", "Kézilabdában", "Kosárlabdában"),
  M("Melyik magyar úszónőt nevezték Iron Ladynek?", "Hosszú Katinkát", "Egerszegi Krisztinát", "Kovács Ágnest", "Szilágyi Lilianát"),
  M("Ki festette a Magányos cédrus című képet?", "Csontváry Kosztka Tivadar", "Munkácsy Mihály", "Rippl-Rónai József", "Szinyei Merse Pál"),
  M("Miről híres világszerte a Kodály-módszer?", "Az ének-zene tanításáról", "A nyelvtanításról", "A matematikaoktatásról", "A tornagyakorlatokról"),
  M("Ki komponálta A víg özvegy című operettet?", "Lehár Ferenc", "Kálmán Imre", "Erkel Ferenc", "Liszt Ferenc"),
  M("Ki írta a Csárdáskirálynő című operettet?", "Kálmán Imre", "Lehár Ferenc", "Erkel Ferenc", "Bartók Béla"),
  M("Ki alapította a budapesti Zeneakadémiát?", "Liszt Ferenc", "Erkel Ferenc", "Kodály Zoltán", "Bartók Béla"),
  M("Melyik híres vendéglős nevét viseli a diós-csokoládés palacsinta?", "Gundel Károlyét", "Dobos C. Józsefét", "Ruszwurmét", "Auguszt Józsefét"),
  M("Melyik város volt a királyi Magyarország fővárosa a török időkben?", "Pozsony", "Buda", "Debrecen", "Szeged"),
  M("Melyik királyunk alapított egyetemet Pécsett 1367-ben?", "Nagy Lajos", "Mátyás", "Szent István", "Károly Róbert"),

  /* ========== MÉG TÖBB VILÁGTÖRTÉNELEM MAGYARUL ========== */
  M("Melyik viking hajós jutott el Amerikába csaknem 500 évvel Kolumbusz előtt?", "Leif Erikson", "Erik, a Vörös... fia nélkül", "Knut király", "Harald király"),
  M("Melyik birodalmat kormányozta Nagy Károly?", "A Frank Birodalmat", "A Római Birodalmat", "A Mongol Birodalmat", "Az Oszmán Birodalmat"),
  M("Melyik erdőben bujkált Robin Hood?", "A sherwoodi erdőben", "A Fekete-erdőben", "A bakonyi erdőben", "A windsori parkban"),
  M("Mi volt Artúr király legendás kardjának neve?", "Excalibur", "Durandal", "Balmung", "A Szent Kard"),
  M("Melyik legendás király lovagjai ültek a kerekasztal körül?", "Artúr királyé", "Richárd királyé", "Károly királyé", "Vilmos királyé"),
  M("Ki győzött 1066-ban a hastingsi csatában?", "Hódító Vilmos", "Oroszlánszívű Richárd", "Artúr király", "Nagy Károly"),
  M("Melyik angol királyt kényszerítették a Magna Carta kiadására?", "Földnélküli Jánost", "VIII. Henriket", "Hódító Vilmost", "György királyt"),
  M("Melyik két ország vívta a százéves háborút?", "Anglia és Franciaország", "Spanyolország és Portugália", "Itália és Görögország", "Ausztria és Poroszország"),
  M("Melyik ország nemzeti hőse Tell Vilmos?", "Svájcé", "Ausztriáé", "Németországé", "Hollandiáé"),
  M("Melyik világhírű regényalak kastélyát képzelik Erdélybe?", "Drakula grófét", "Frankensteinét", "Robin Hoodét", "Zorróét"),
  M("Melyik ország harcos rendje voltak a szamurájok?", "Japáné", "Kínáé", "Mongóliáé", "Koreáé"),
  M("Melyik portugál hajós ért el elsőként tengeren Indiába?", "Vasco da Gama", "Kolumbusz", "Magellán", "Cook kapitány"),
  M("Melyik hódító döntötte meg az aztékok birodalmát?", "Hernán Cortés", "Francisco Pizarro", "Kolumbusz", "Napóleon"),
  M("Melyik hódító döntötte meg az inkák birodalmát?", "Francisco Pizarro", "Hernán Cortés", "Vasco da Gama", "Magellán"),
  M("Mi volt az aztékok tavon épült fővárosa?", "Tenochtitlán", "Machu Picchu", "Cuzco", "Chichén Itzá"),
  M("Ki volt VIII. Henrik lánya, Anglia nagy királynője?", "I. Erzsébet", "Viktória", "II. Erzsébet", "Stuart Mária"),
  M("Melyik ország flottája győzte le a spanyol Armadát 1588-ban?", "Angliáé", "Franciaországé", "Hollandiáé", "Portugáliáé"),
  M("Melyik országban élt a festő Rembrandt?", "Hollandiában", "Itáliában", "Franciaországban", "Spanyolországban"),
  M("Melyik országban született Johann Sebastian Bach?", "Németországban", "Ausztriában", "Itáliában", "Magyarországon"),
  M("Melyik ország nagy cárnője volt Nagy Katalin?", "Oroszországé", "Ausztriáé", "Svédországé", "Lengyelországé"),
  M("Melyik óceán szigeteit térképezte fel James Cook kapitány?", "A Csendes-óceánét", "Az Atlanti-óceánét", "A Jeges-tengerét", "Az Indiai-óceán... partjait csak"),
  M("Minek használta Nagy-Britannia kezdetben Ausztráliát?", "Fegyenctelepnek", "Aranybányának", "Üdülőhelynek", "Kereskedelmi kikötőnek"),
  M("Ki szabadította fel Dél-Amerika nagy részét a spanyol uralom alól?", "Simón Bolívar", "Zapata", "Kolumbusz", "Pizarro"),
  M("Melyik országtól lett független Mexikó?", "Spanyolországtól", "Portugáliától", "Franciaországtól", "Angliától"),
  M("Melyik kő segített megfejteni az egyiptomi hieroglifákat?", "A rosette-i kő", "A Szent Korona", "A runakő", "A babiloni tábla"),
  M("Ki építette az első sikeres gőzmozdonyokat?", "George Stephenson", "Henry Ford", "James Watt", "A Wright fivérek"),
  M("Ki tökéletesítette a gőzgépet?", "James Watt", "Stephenson", "Edison", "Newton"),
  M("Milyen eljárás teszi tartósan biztonságossá a tejet?", "A pasztörizálás", "A fagyasztás", "A sózás", "A füstölés"),
  M("Ki volt a modern betegápolás megteremtője?", "Florence Nightingale", "Teréz anya", "Marie Curie", "Semmelweis Ignác"),
  M("Milyen jelekből áll a Morse-ábécé?", "Pontokból és vonásokból", "Színekből", "Számokból", "Hangjegyekből"),
  M("Ki írta a 80 nap alatt a Föld körül című regényt?", "Jules Verne", "Charles Dickens", "Mark Twain", "Jókai Mór"),
  M("Melyik országból származott a nagy meseíró, Andersen?", "Dániából", "Németországból", "Svédországból", "Hollandiából"),
  M("Melyik országban gyűjtötték meséiket a Grimm fivérek?", "Németországban", "Dániában", "Franciaországban", "Angliában"),
  M("Mit vágott le magáról Van Gogh?", "A fél fülét", "A haját", "A szakállát", "Az egyik ujját"),
  M("Melyik városban adják át a Nobel-békedíjat?", "Oslóban", "Stockholmban", "Genfben", "Párizsban"),
  M("Ki érte el elsőként a Déli-sarkot?", "Roald Amundsen", "Robert Scott", "Robert Peary", "Shackleton"),
  M("Melyik két óceánt köti össze a Panama-csatorna?", "Az Atlanti- és a Csendes-óceánt", "Az Atlanti- és az Indiai-óceánt", "A Csendes- és a Jeges-tengert", "A Földközi- és a Vörös-tengert"),
  M("Melyik országban alapította Henri Dunant a Vöröskeresztet?", "Svájcban", "Franciaországban", "Amerikában", "Angliában"),
  M("Ki repülte át elsőként egyedül, leszállás nélkül az Atlanti-óceánt?", "Charles Lindbergh", "Amelia Earhart", "A Wright fivérek", "Gagarin"),
  M("Ki volt az első nő, aki egyedül átrepülte az Atlanti-óceánt?", "Amelia Earhart", "Valentyina Tyereskova", "Sally Ride", "Marie Curie"),
  M("Mi volt az 1937-ben lángra lobbant Hindenburg?", "Egy hatalmas léghajó", "Egy óceánjáró", "Egy tengeralattjáró", "Egy gőzmozdony"),
  M("Melyik városnál fordult meg a második világháború a keleti fronton?", "Sztálingrádnál", "Berlinnél", "Párizsnál", "Varsónál"),
  M("Ki törte fel a németek Enigma kódológépét?", "Alan Turing", "Einstein", "Neumann János", "Churchill"),
  M("Melyik városban van az ENSZ székháza?", "New Yorkban", "Genfben", "Párizsban", "Londonban"),
  M("Melyik katonai szövetség alakult meg 1949-ben?", "A NATO", "A Varsói Szerződés", "Az Európai Unió", "Az ENSZ"),
  M("Mit segített újjáépíteni a Marshall-terv?", "A háború utáni Európát", "Japánt", "Dél-Amerikát", "Afrikát"),
  M("Mit szállítottak a repülők a berlini légihídon?", "Élelmiszert és ellátmányt", "Fegyvereket", "Katonákat", "Csak postát"),
  M("Melyik évben tört ki a koreai háború?", "1950-ben", "1945-ben", "1939-ben", "1965-ben"),
  M("Melyik két vezető nézett farkasszemet a kubai rakétaválságban?", "Kennedy és Hruscsov", "Reagan és Gorbacsov", "Churchill és Sztálin", "Nixon és Brezsnyev"),
  M("Melyik országban zajlott 1968-ban a prágai tavasz?", "Csehszlovákiában", "Lengyelországban", "Magyarországon", "Jugoszláviában"),
  M("Melyik lengyel munkásvezető alapította a Szolidaritás mozgalmat?", "Lech Walesa", "II. János Pál", "Gorbacsov", "Havel"),
  M("Melyik szovjet vezető hirdette meg a peresztrojkát?", "Gorbacsov", "Sztálin", "Hruscsov", "Brezsnyev"),
  M("Mi választotta el a hidegháborúban Nyugat-Európát Kelet-Európától?", "A vasfüggöny", "A kínai nagy fal", "A Maginot-vonal", "A Csalagút"),
  M("Ki mászta meg elsőként a Mount Everestet Tenzing Norgajjal?", "Edmund Hillary", "Amundsen", "Scott", "Messner... egyedül"),
  M("Ki hajtotta végre a világ első szívátültetését?", "Christiaan Barnard", "Semmelweis Ignác", "Fleming", "Salk"),
  M("Melyik két tudós írta le a DNS szerkezetét?", "Watson és Crick", "A Wright fivérek", "A Curie házaspár", "Bánki és Csonka"),
  M("Miről volt híres a Concorde repülőgép?", "Gyorsabban repült a hangnál", "Pilóta nélkül szállt", "Napenergiával működött", "Függőlegesen szállt fel"),
  M("Melyik angol városból indult a Beatles együttes?", "Liverpoolból", "Londonból", "Manchesterből", "Oxfordból"),
  M("Melyik városban halt meg Diana hercegné?", "Párizsban", "Londonban", "Monacóban", "Rómában"),
  M("Kinek épült a legnagyobb gízai piramis?", "Kheopsz fáraónak", "Kleopátrának", "Tutanhamonnak", "Ramszesznek"),
  M("Ki találta meg Tutanhamon sírját 1922-ben?", "Howard Carter", "Kolumbusz", "Darwin", "Indiana Jones"),
  M("Kinek az elrablása robbantotta ki a monda szerint a trójai háborút?", "Szép Helénáé", "Kleopátráé", "Pénelopéé", "Aphroditéé"),
  M("Kiket szoptatott a monda szerint egy anyafarkas?", "Romulust és Remust", "Zeuszt és Hérát", "A Grimm fivéreket", "Héraklészt és Hektórt"),
  M("Ki volt a görög istenek királya?", "Zeusz", "Apollón", "Poszeidón", "Héraklész"),
  M("Minek állít emléket a maratoni futás?", "A győzelmi hírt vivő görög futárnak", "Egy híres lóversenynek", "Az olimpiai lángnak", "Egy római hadjáratnak"),
  M("Melyik nép találta fel a puskaport?", "A kínaiak", "A rómaiak", "Az egyiptomiak", "A vikingek"),
  M("Melyik országban áll az őskori Stonehenge kőköre?", "Angliában", "Franciaországban", "Görögországban", "Egyiptomban"),
  M("Melyik vallást alapította Mohamed próféta?", "Az iszlámot", "A buddhizmust", "A kereszténységet", "A hinduizmust"),
  M("Melyik vallás fűződik Buddha nevéhez?", "A buddhizmus", "Az iszlám", "A taoizmus", "A sintoizmus"),
  M("Melyik ország nagy bölcse volt Konfuciusz?", "Kínáé", "Japáné", "Indiáé", "Perzsiáé")
];
