/* Quiz Time! — question bank.
   H(question, correctAnswer, wrong1, wrong2, wrong3) = History
   G(question, correctAnswer, wrong1, wrong2, wrong3) = Geography
   The correct answer is always the second argument; the app
   shuffles the four choices every time a question is shown. */

var H = function (q, a, w1, w2, w3) { return { cat: "history", q: q, a: a, w: [w1, w2, w3] }; };
var G = function (q, a, w1, w2, w3) { return { cat: "geography", q: q, a: a, w: [w1, w2, w3] }; };

var QUESTIONS = [

  /* ==================== HISTORY — Ancient times ==================== */
  H("Which ancient people built the pyramids of Giza?", "The Egyptians", "The Romans", "The Greeks", "The Vikings"),
  H("What is the picture-writing of ancient Egypt called?", "Hieroglyphics", "Calligraphy", "The alphabet", "Braille"),
  H("Who discovered the tomb of King Tutankhamun in 1922?", "Howard Carter", "Charles Darwin", "Marco Polo", "Neil Armstrong"),
  H("Cleopatra was the famous queen of which land?", "Egypt", "Greece", "Rome", "Persia"),
  H("In which country did the ancient Olympic Games begin?", "Greece", "Italy", "Egypt", "France"),
  H("Which ancient city is called the birthplace of democracy?", "Athens", "Rome", "Cairo", "London"),
  H("Which ancient Greek city was famous for its tough warriors?", "Sparta", "Venice", "Paris", "Alexandria"),
  H("In the famous legend, the Greeks used a giant wooden horse to enter which city?", "Troy", "Athens", "Rome", "Carthage"),
  H("Alexander the Great was the king of which ancient kingdom?", "Macedonia", "England", "China", "Egypt"),
  H("What language did the ancient Romans speak?", "Latin", "Greek", "French", "English"),
  H("Julius Caesar was a famous leader of which empire?", "The Roman Empire", "The British Empire", "The Egyptian Empire", "The Chinese Empire"),
  H("On which date was Julius Caesar assassinated?", "The Ides of March (March 15)", "New Year's Day", "The Fourth of July", "Christmas Day"),
  H("What is the name of the huge arena in Rome where gladiators fought?", "The Colosseum", "The Parthenon", "Big Ben", "The Louvre"),
  H("Which volcano buried the Roman city of Pompeii in ash?", "Mount Vesuvius", "Mount Everest", "Mount Fuji", "Mount Rushmore"),
  H("The general Hannibal famously crossed the Alps with which animals?", "Elephants", "Camels", "Horses only", "Lions"),
  H("Who was the first emperor of Rome?", "Augustus", "Napoleon", "Alexander", "Charlemagne"),
  H("The Romans built long channels to carry water to their cities. What are they called?", "Aqueducts", "Pyramids", "Canoes", "Windmills"),
  H("Why was the Great Wall of China built?", "To keep out invaders", "To hold back floods", "As a royal palace", "As a trade market"),
  H("Which ancient wonder of the world is still standing in Egypt today?", "The Great Pyramid of Giza", "The Hanging Gardens", "The Lighthouse of Alexandria", "The Colossus of Rhodes"),
  H("The Parthenon is a famous ancient temple in which city?", "Athens", "Rome", "Cairo", "Istanbul"),
  H("Gladiators fought for crowds in which ancient empire?", "Ancient Rome", "Ancient Egypt", "The Aztec Empire", "The Viking lands"),
  H("Ancient Egyptian life depended on which great river?", "The Nile", "The Amazon", "The Mississippi", "The Thames"),
  H("The Great Sphinx of Egypt has the head of a person and the body of which animal?", "A lion", "A horse", "An eagle", "A crocodile"),
  H("The marathon race is named after a battle in which ancient country?", "Greece", "Italy", "Spain", "China"),
  H("Ancient Egyptians preserved their dead as what?", "Mummies", "Statues", "Paintings", "Fossils"),

  /* ==================== HISTORY — Middle Ages & Renaissance ==================== */
  H("Who won the Battle of Hastings in 1066?", "William the Conqueror", "Julius Caesar", "Napoleon", "King Arthur"),
  H("Which English king was forced to accept the Magna Carta?", "King John", "King Henry VIII", "King George III", "King Richard III"),
  H("In what year was the Magna Carta sealed?", "1215", "1066", "1492", "1776"),
  H("What was the Black Death, which swept Europe in the 1300s?", "A deadly plague", "A great fire", "A long war", "A famous storm"),
  H("The Vikings came from which part of the world?", "Scandinavia", "Africa", "South America", "Australia"),
  H("Which Viking explorer reached North America about 500 years before Columbus?", "Leif Erikson", "Christopher Columbus", "Ferdinand Magellan", "Captain Cook"),
  H("Joan of Arc was a young heroine of which country?", "France", "England", "Spain", "Italy"),
  H("Genghis Khan built a huge empire leading which people?", "The Mongols", "The Romans", "The Vikings", "The Aztecs"),
  H("The explorer Marco Polo made his famous journey to which land?", "China", "America", "Australia", "Egypt"),
  H("The Crusades were fought over which holy city?", "Jerusalem", "Paris", "Rome", "Athens"),
  H("Knights of the Middle Ages followed a code of honor called what?", "Chivalry", "Democracy", "Alchemy", "Diplomacy"),
  H("What is the water-filled ditch around a castle called?", "A moat", "A well", "A dam", "A trench"),
  H("Who invented the printing press around 1440?", "Johannes Gutenberg", "Thomas Edison", "Benjamin Franklin", "Alexander Graham Bell"),
  H("Who painted the Mona Lisa?", "Leonardo da Vinci", "Michelangelo", "Pablo Picasso", "Vincent van Gogh"),
  H("Who painted the ceiling of the Sistine Chapel?", "Michelangelo", "Leonardo da Vinci", "Rembrandt", "Monet"),
  H("The Renaissance, a great rebirth of art and learning, began in which country?", "Italy", "England", "Russia", "Egypt"),
  H("In what year did Christopher Columbus first sail across the Atlantic?", "1492", "1776", "1215", "1620"),
  H("Christopher Columbus sailed under the flag of which country?", "Spain", "England", "France", "Portugal"),
  H("Which of these was one of Columbus's three ships?", "The Santa María", "The Mayflower", "The Titanic", "The Queen Mary"),
  H("Whose expedition was the first to sail all the way around the world?", "Ferdinand Magellan's", "Christopher Columbus's", "Marco Polo's", "Captain Ahab's"),
  H("The Aztec Empire was located in which modern-day country?", "Mexico", "Egypt", "Spain", "India"),
  H("The Inca Empire built its famous mountain cities on which continent?", "South America", "Africa", "Europe", "Australia"),
  H("Machu Picchu was built by which ancient people?", "The Incas", "The Romans", "The Egyptians", "The Vikings"),
  H("Who wrote the play 'Romeo and Juliet'?", "William Shakespeare", "Charles Dickens", "Mark Twain", "Jane Austen"),
  H("What was the name of Shakespeare's famous theatre in London?", "The Globe", "The Palladium", "The Coliseum", "The Apollo"),

  /* ==================== HISTORY — Early modern times ==================== */
  H("King Henry VIII of England is famous for having how many wives?", "Six", "Two", "Ten", "One"),
  H("Henry VIII was the king of which country?", "England", "France", "Spain", "Germany"),
  H("Elizabeth I was a famous queen of which country?", "England", "Russia", "Sweden", "Portugal"),
  H("Which country defeated the Spanish Armada in 1588?", "England", "France", "Italy", "Greece"),
  H("What was the name of the ship that carried the Pilgrims to America in 1620?", "The Mayflower", "The Santa María", "The Titanic", "The Endeavour"),
  H("Where did the Pilgrims land in 1620?", "Plymouth, Massachusetts", "New York City", "Miami, Florida", "San Francisco"),
  H("The Pilgrims shared the first Thanksgiving feast with whom?", "Native Americans", "French explorers", "Spanish sailors", "Roman soldiers"),
  H("Isaac Newton is famous for explaining which force, after seeing an apple fall?", "Gravity", "Electricity", "Magnetism", "Steam power"),
  H("In what year did the French Revolution begin?", "1789", "1492", "1914", "1620"),
  H("Which famous prison did the people of Paris storm in 1789?", "The Bastille", "Alcatraz", "The Tower of London", "Sing Sing"),
  H("Which French queen is often (wrongly) said to have declared 'Let them eat cake'?", "Marie Antoinette", "Queen Victoria", "Cleopatra", "Queen Elizabeth I"),
  H("At which battle was Napoleon finally defeated in 1815?", "Waterloo", "Gettysburg", "Hastings", "Normandy"),
  H("Napoleon Bonaparte crowned himself emperor of which country?", "France", "England", "Russia", "Austria"),
  H("In what year was the American Declaration of Independence signed?", "1776", "1620", "1865", "1901"),
  H("Who was the main author of the Declaration of Independence?", "Thomas Jefferson", "George Washington", "Abraham Lincoln", "Benjamin Franklin"),
  H("Who was the first president of the United States?", "George Washington", "Abraham Lincoln", "Thomas Jefferson", "John Adams"),
  H("The Boston Tea Party was a protest against what?", "British taxes", "The price of coffee", "A new railroad", "The king's birthday"),
  H("What did the colonists throw into the harbor at the Boston Tea Party?", "Tea", "Coffee", "Gold", "Cotton"),
  H("In which city was the United States Constitution written?", "Philadelphia", "Washington, D.C.", "Boston", "New York"),
  H("Paul Revere took a famous midnight ride to warn that who was coming?", "The British", "The pirates", "The French", "The Spanish"),
  H("The American Revolution was fought between America and which country?", "Great Britain", "France", "Spain", "Mexico"),
  H("Benjamin Franklin famously flew what in a lightning storm?", "A kite", "A flag", "A hot-air balloon", "A model airplane"),
  H("In 1803 the United States bought the huge Louisiana Territory from which country?", "France", "Spain", "England", "Russia"),
  H("Which two explorers led the famous expedition to America's West in 1804?", "Lewis and Clark", "Stanley and Livingstone", "Wright and Wright", "Watson and Crick"),
  H("Sacagawea was the Native American woman who helped guide which expedition?", "Lewis and Clark", "Columbus", "The Mayflower", "Magellan"),

  /* ==================== HISTORY — The 1800s ==================== */
  H("In which years was the American Civil War fought?", "1861 to 1865", "1776 to 1781", "1914 to 1918", "1939 to 1945"),
  H("In the Civil War, what was the Northern side called?", "The Union", "The Confederacy", "The Alliance", "The Colonies"),
  H("Who was president of the United States during the Civil War?", "Abraham Lincoln", "George Washington", "Theodore Roosevelt", "Ulysses S. Grant"),
  H("What is the name of Abraham Lincoln's most famous short speech?", "The Gettysburg Address", "The New Deal", "The I Have a Dream speech", "The Farewell Address"),
  H("Who assassinated Abraham Lincoln?", "John Wilkes Booth", "Lee Harvey Oswald", "Benedict Arnold", "Jesse James"),
  H("Where was Abraham Lincoln when he was shot?", "Ford's Theatre", "The White House", "A train station", "Gettysburg"),
  H("Lincoln's Emancipation Proclamation was a step toward ending what?", "Slavery", "Taxes", "The gold rush", "The railroads"),
  H("Which brave woman guided many enslaved people to freedom on the Underground Railroad?", "Harriet Tubman", "Betsy Ross", "Amelia Earhart", "Florence Nightingale"),
  H("Who wrote the anti-slavery novel 'Uncle Tom's Cabin'?", "Harriet Beecher Stowe", "Mark Twain", "Jane Austen", "Louisa May Alcott"),
  H("What great project, finished in 1869, connected America's east and west coasts?", "The Transcontinental Railroad", "The Panama Canal", "The Interstate Highway", "The Brooklyn Bridge"),
  H("Who invented the telephone?", "Alexander Graham Bell", "Thomas Edison", "Henry Ford", "Samuel Morse"),
  H("Who invented the first practical electric light bulb?", "Thomas Edison", "Alexander Graham Bell", "Isaac Newton", "Albert Einstein"),
  H("Which queen ruled Britain for most of the 1800s?", "Queen Victoria", "Queen Elizabeth II", "Queen Anne", "Queen Mary"),
  H("In what year did the California Gold Rush begin in earnest?", "1849", "1776", "1929", "1901"),
  H("The 'forty-niners' rushed to California in search of what?", "Gold", "Oil", "Diamonds", "Silver"),
  H("Charles Darwin is famous for his theory of what?", "Evolution", "Gravity", "Relativity", "Electricity"),
  H("Florence Nightingale is remembered as the founder of modern what?", "Nursing", "Banking", "Photography", "Teaching"),
  H("Samuel Morse invented a famous code made of what?", "Dots and dashes", "Colors and shapes", "Numbers only", "Musical notes"),
  H("The first women's rights convention in America was held in 1848 in which town?", "Seneca Falls, New York", "Dallas, Texas", "Miami, Florida", "Denver, Colorado"),
  H("Pioneer families traveled the Oregon Trail in what?", "Covered wagons", "Steamboats", "Trains", "Cars"),
  H("The Pony Express used riders on horseback to deliver what?", "Mail", "Milk", "Newspapers only", "Gold bars"),
  H("In 1867 the United States bought Alaska from which country?", "Russia", "Canada", "France", "Spain"),
  H("General Custer made his famous 'last stand' at which battle?", "Little Bighorn", "Gettysburg", "Bunker Hill", "Waterloo"),
  H("The Homestead Act offered settlers what if they farmed it?", "Free land", "Free horses", "Free gold", "Free houses in the city"),
  H("Which amendment to the U.S. Constitution ended slavery?", "The 13th Amendment", "The 1st Amendment", "The 19th Amendment", "The 21st Amendment"),

  /* ==================== HISTORY — The 1900s ==================== */
  H("In what year did the Wright brothers make the first airplane flight?", "1903", "1929", "1876", "1945"),
  H("Where did the Wright brothers make their first flight?", "Kitty Hawk, North Carolina", "New York City", "Los Angeles, California", "Miami, Florida"),
  H("In what year did the Titanic sink?", "1912", "1905", "1923", "1898"),
  H("What did the Titanic hit before it sank?", "An iceberg", "A whale", "Another ship", "A reef"),
  H("In what year did World War I begin?", "1914", "1939", "1918", "1900"),
  H("World War I was sparked by the assassination of which man?", "Archduke Franz Ferdinand", "Abraham Lincoln", "Julius Caesar", "Napoleon"),
  H("In what year did World War I end?", "1918", "1914", "1945", "1920"),
  H("Which war is famous for soldiers fighting from muddy trenches?", "World War I", "The Civil War", "The Revolutionary War", "The Cold War"),
  H("Which amendment gave American women the right to vote?", "The 19th Amendment", "The 13th Amendment", "The 5th Amendment", "The 2nd Amendment"),
  H("In what year did American women win the right to vote?", "1920", "1865", "1776", "1950"),
  H("What style of music gave the Roaring Twenties its soundtrack?", "Jazz", "Rock and roll", "Opera", "Disco"),
  H("During Prohibition, what was banned in the United States?", "Alcohol", "Coffee", "Dancing", "Automobiles"),
  H("In what year did the great stock market crash happen?", "1929", "1919", "1941", "1955"),
  H("What is the hard period after the 1929 crash called?", "The Great Depression", "The Cold War", "The Gold Rush", "The Renaissance"),
  H("Which president created the 'New Deal' to fight the Great Depression?", "Franklin D. Roosevelt", "Abraham Lincoln", "Richard Nixon", "George Washington"),
  H("Amelia Earhart was the first woman to do what?", "Fly solo across the Atlantic", "Climb Mount Everest", "Swim the English Channel", "Walk on the moon"),
  H("Who discovered penicillin, the first great antibiotic?", "Alexander Fleming", "Thomas Edison", "Marie Antoinette", "Henry Ford"),
  H("In what year did World War II begin in Europe?", "1939", "1914", "1945", "1929"),
  H("Who was the dictator of Germany during World War II?", "Adolf Hitler", "Joseph Stalin", "Napoleon", "Kaiser Wilhelm"),
  H("On what date was Pearl Harbor attacked?", "December 7, 1941", "July 4, 1776", "June 6, 1944", "November 11, 1918"),
  H("Pearl Harbor is located in which U.S. state?", "Hawaii", "California", "Florida", "Alaska"),
  H("The D-Day invasion of 1944 landed on the beaches of which region?", "Normandy, France", "Sicily, Italy", "The coast of Spain", "The coast of England"),
  H("On what date did the D-Day landings take place?", "June 6, 1944", "December 7, 1941", "July 4, 1776", "May 8, 1950"),
  H("Who was Britain's famous prime minister during World War II?", "Winston Churchill", "Margaret Thatcher", "Tony Blair", "King George"),
  H("In what year did World War II end?", "1945", "1939", "1918", "1950"),
  H("The first atomic bomb used in war was dropped on which city?", "Hiroshima", "Tokyo", "Berlin", "London"),
  H("The Holocaust was the murder of six million people, mostly from which group?", "Jewish people", "Roman soldiers", "French farmers", "British sailors"),
  H("Anne Frank is remembered around the world for what?", "Her diary", "Her paintings", "Her flying records", "Her nursing"),
  H("The wartime poster figure 'Rosie the Riveter' stood for what?", "Women working in factories", "Farmers growing corn", "Soldiers overseas", "Nurses in hospitals"),
  H("The Cold War was a long rivalry between the United States and which country?", "The Soviet Union", "Germany", "Japan", "Mexico"),
  H("What was the name of the first satellite launched into space in 1957?", "Sputnik", "Apollo", "Voyager", "Hubble"),
  H("Who was the first human being to travel into space?", "Yuri Gagarin", "Neil Armstrong", "John Glenn", "Buzz Aldrin"),
  H("Who was the first American in space?", "Alan Shepard", "Neil Armstrong", "Charles Lindbergh", "Howard Hughes"),
  H("Who was the first person to walk on the moon?", "Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"),
  H("In what year did astronauts first land on the moon?", "1969", "1959", "1979", "1949"),
  H("Neil Armstrong's first words on the moon began 'That's one small step for...'", "man", "science", "America", "the future"),
  H("In which city was President John F. Kennedy assassinated?", "Dallas", "Washington, D.C.", "New York", "Chicago"),
  H("What is the name of Martin Luther King Jr.'s most famous speech?", "I Have a Dream", "The Gettysburg Address", "Give Me Liberty", "The New Frontier"),
  H("Rosa Parks became famous for refusing to do what?", "Give up her bus seat", "Pay a tax", "Leave a restaurant", "Sign a paper"),
  H("The Montgomery Bus Boycott took place in which state?", "Alabama", "New York", "California", "Texas"),
  H("The Berlin Wall divided which city into east and west?", "Berlin", "Paris", "London", "Moscow"),
  H("In what year did the Berlin Wall come down?", "1989", "1969", "1999", "1979"),
  H("Which president led America through the Cuban Missile Crisis of 1962?", "John F. Kennedy", "Richard Nixon", "Franklin D. Roosevelt", "Jimmy Carter"),
  H("The Watergate scandal led to the resignation of which president?", "Richard Nixon", "John F. Kennedy", "Ronald Reagan", "Harry Truman"),
  H("Who was Britain's first female prime minister?", "Margaret Thatcher", "Queen Victoria", "Florence Nightingale", "Jane Austen"),
  H("Mahatma Gandhi led which country to independence using peaceful protest?", "India", "China", "Egypt", "Brazil"),
  H("Nelson Mandela became the first Black president of which country?", "South Africa", "Kenya", "Egypt", "Brazil"),
  H("Who developed the first successful polio vaccine?", "Jonas Salk", "Alexander Fleming", "Louis Pasteur", "Marie Curie"),
  H("Albert Einstein is most famous for his theory of what?", "Relativity", "Gravity", "Evolution", "Electricity"),
  H("Who invented the World Wide Web in 1989?", "Tim Berners-Lee", "Thomas Edison", "Bill Nye", "Alexander Graham Bell"),

  /* ==================== GEOGRAPHY — World capitals ==================== */
  G("What is the capital of France?", "Paris", "London", "Rome", "Madrid"),
  G("What is the capital of Italy?", "Rome", "Venice", "Milan", "Florence"),
  G("What is the capital of Spain?", "Madrid", "Barcelona", "Seville", "Lisbon"),
  G("What is the capital of Japan?", "Tokyo", "Kyoto", "Osaka", "Beijing"),
  G("What is the capital of Egypt?", "Cairo", "Alexandria", "Athens", "Casablanca"),
  G("What is the capital of Canada?", "Ottawa", "Toronto", "Vancouver", "Montreal"),
  G("What is the capital of Australia?", "Canberra", "Sydney", "Melbourne", "Brisbane"),
  G("What is the capital of Germany?", "Berlin", "Munich", "Hamburg", "Frankfurt"),
  G("What is the capital of Russia?", "Moscow", "St. Petersburg", "Kyiv", "Warsaw"),
  G("What is the capital of China?", "Beijing", "Shanghai", "Hong Kong", "Tokyo"),
  G("What is the capital of the United Kingdom?", "London", "Manchester", "Liverpool", "Dublin"),
  G("What is the capital of Greece?", "Athens", "Sparta", "Rome", "Istanbul"),
  G("What is the capital of Portugal?", "Lisbon", "Madrid", "Porto", "Barcelona"),
  G("What is the capital of Austria?", "Vienna", "Salzburg", "Berlin", "Zurich"),
  G("What is the capital of the Netherlands?", "Amsterdam", "Brussels", "Rotterdam", "Copenhagen"),
  G("What is the capital of Norway?", "Oslo", "Stockholm", "Copenhagen", "Helsinki"),
  G("What is the capital of Sweden?", "Stockholm", "Oslo", "Helsinki", "Gothenburg"),
  G("What is the capital of Denmark?", "Copenhagen", "Oslo", "Amsterdam", "Stockholm"),
  G("What is the capital of Finland?", "Helsinki", "Stockholm", "Oslo", "Reykjavik"),
  G("What is the capital of Poland?", "Warsaw", "Krakow", "Prague", "Budapest"),
  G("What is the capital of Hungary?", "Budapest", "Vienna", "Prague", "Bucharest"),
  G("What is the capital of the Czech Republic?", "Prague", "Vienna", "Warsaw", "Budapest"),
  G("What is the capital of Ireland?", "Dublin", "Belfast", "Cork", "Edinburgh"),
  G("What is the capital of Switzerland?", "Bern", "Zurich", "Geneva", "Basel"),
  G("What is the capital of Belgium?", "Brussels", "Amsterdam", "Antwerp", "Paris"),
  G("What is the capital of Turkey?", "Ankara", "Istanbul", "Athens", "Cairo"),
  G("What is the capital of India?", "New Delhi", "Mumbai", "Kolkata", "Bangalore"),
  G("What is the capital of Brazil?", "Brasília", "Rio de Janeiro", "São Paulo", "Buenos Aires"),
  G("What is the capital of Argentina?", "Buenos Aires", "Santiago", "Lima", "Rio de Janeiro"),
  G("What is the capital of Mexico?", "Mexico City", "Cancún", "Guadalajara", "Acapulco"),
  G("What is the capital of the United States?", "Washington, D.C.", "New York City", "Los Angeles", "Chicago"),
  G("What is the capital of Cuba?", "Havana", "Miami", "San Juan", "Kingston"),
  G("What is the capital of Peru?", "Lima", "Santiago", "Bogotá", "Quito"),
  G("What is the capital of Chile?", "Santiago", "Lima", "Buenos Aires", "La Paz"),
  G("What is the capital of Kenya?", "Nairobi", "Cairo", "Lagos", "Cape Town"),
  G("What is the capital of South Korea?", "Seoul", "Busan", "Tokyo", "Beijing"),
  G("What is the capital of Thailand?", "Bangkok", "Hanoi", "Singapore", "Manila"),
  G("What is the capital of Vietnam?", "Hanoi", "Ho Chi Minh City", "Bangkok", "Seoul"),
  G("What is the capital of Iceland?", "Reykjavik", "Oslo", "Helsinki", "Copenhagen"),
  G("What is the capital of New Zealand?", "Wellington", "Auckland", "Sydney", "Christchurch"),
  G("What is the capital of Scotland?", "Edinburgh", "Glasgow", "London", "Dublin"),
  G("What is the capital of Morocco?", "Rabat", "Casablanca", "Marrakesh", "Cairo"),
  G("What is the capital of Saudi Arabia?", "Riyadh", "Dubai", "Mecca", "Cairo"),
  G("What is the capital of Ukraine?", "Kyiv", "Moscow", "Warsaw", "Minsk"),
  G("What is the capital of Romania?", "Bucharest", "Budapest", "Sofia", "Belgrade"),

  /* ==================== GEOGRAPHY — U.S. state capitals ==================== */
  G("What is the capital of California?", "Sacramento", "Los Angeles", "San Francisco", "San Diego"),
  G("What is the capital of Texas?", "Austin", "Houston", "Dallas", "San Antonio"),
  G("What is the capital of New York State?", "Albany", "New York City", "Buffalo", "Rochester"),
  G("What is the capital of Florida?", "Tallahassee", "Miami", "Orlando", "Tampa"),
  G("What is the capital of Illinois?", "Springfield", "Chicago", "Peoria", "Rockford"),
  G("What is the capital of Arizona?", "Phoenix", "Tucson", "Flagstaff", "Las Vegas"),
  G("What is the capital of Hawaii?", "Honolulu", "Maui", "Hilo", "Kona"),
  G("What is the capital of Colorado?", "Denver", "Boulder", "Colorado Springs", "Aspen"),
  G("What is the capital of Massachusetts?", "Boston", "Cambridge", "Springfield", "Salem"),
  G("What is the capital of Georgia?", "Atlanta", "Savannah", "Augusta", "Athens"),
  G("What is the capital of Tennessee?", "Nashville", "Memphis", "Knoxville", "Chattanooga"),
  G("What is the capital of Washington State?", "Olympia", "Seattle", "Spokane", "Tacoma"),
  G("What is the capital of Nevada?", "Carson City", "Las Vegas", "Reno", "Henderson"),
  G("What is the capital of Louisiana?", "Baton Rouge", "New Orleans", "Shreveport", "Lafayette"),
  G("What is the capital of Pennsylvania?", "Harrisburg", "Philadelphia", "Pittsburgh", "Allentown"),

  /* ==================== GEOGRAPHY — Rivers ==================== */
  G("Which river is usually called the longest in the world?", "The Nile", "The Mississippi", "The Thames", "The Danube"),
  G("Which river flows through the heart of Paris?", "The Seine", "The Thames", "The Nile", "The Rhine"),
  G("Which river flows through London?", "The Thames", "The Seine", "The Danube", "The Volga"),
  G("Which mighty river flows past New Orleans into the Gulf of Mexico?", "The Mississippi", "The Colorado", "The Hudson", "The Amazon"),
  G("Which great river flows through Egypt?", "The Nile", "The Amazon", "The Congo", "The Tigris"),
  G("Which river flows through the city of Rome?", "The Tiber", "The Seine", "The Po", "The Danube"),
  G("What is the longest river in Europe?", "The Volga", "The Thames", "The Seine", "The Rhine"),
  G("What is the longest river in Asia?", "The Yangtze", "The Nile", "The Mississippi", "The Amazon"),
  G("Which river carved the Grand Canyon?", "The Colorado River", "The Mississippi River", "The Missouri River", "The Rio Grande"),
  G("The Amazon River flows through which continent?", "South America", "Africa", "Asia", "Australia"),
  G("Which river flows through both Vienna and Budapest?", "The Danube", "The Rhine", "The Seine", "The Volga"),
  G("Which river forms much of the border between the United States and Mexico?", "The Rio Grande", "The Mississippi", "The Colorado", "The Hudson"),

  /* ==================== GEOGRAPHY — Mountains ==================== */
  G("What is the tallest mountain in the world?", "Mount Everest", "Mount Kilimanjaro", "Mont Blanc", "Mount Fuji"),
  G("Mount Everest is part of which mountain range?", "The Himalayas", "The Alps", "The Rockies", "The Andes"),
  G("What is the tallest mountain in Africa?", "Mount Kilimanjaro", "Mount Everest", "Mont Blanc", "Mount Fuji"),
  G("What is the tallest mountain in North America?", "Denali", "Mount Everest", "Pikes Peak", "Mount Fuji"),
  G("Which famous mountain range runs through Switzerland?", "The Alps", "The Andes", "The Rockies", "The Himalayas"),
  G("Which mountain range runs down the west side of South America?", "The Andes", "The Alps", "The Rockies", "The Urals"),
  G("Which mountain range stretches through the western United States and Canada?", "The Rocky Mountains", "The Appalachians", "The Alps", "The Andes"),
  G("Mount Fuji is the famous snow-capped mountain of which country?", "Japan", "China", "Switzerland", "Chile"),
  G("The famous Matterhorn peak is part of which mountain range?", "The Alps", "The Himalayas", "The Rockies", "The Andes"),
  G("Which older, gentler mountain range runs along the eastern United States?", "The Appalachians", "The Rockies", "The Sierra Nevada", "The Alps"),

  /* ==================== GEOGRAPHY — Oceans, seas & lakes ==================== */
  G("What is the largest ocean in the world?", "The Pacific Ocean", "The Atlantic Ocean", "The Indian Ocean", "The Arctic Ocean"),
  G("What is the second-largest ocean?", "The Atlantic Ocean", "The Pacific Ocean", "The Arctic Ocean", "The Indian Ocean"),
  G("What is the smallest, coldest ocean?", "The Arctic Ocean", "The Pacific Ocean", "The Atlantic Ocean", "The Indian Ocean"),
  G("Which ocean lies between Africa and Australia?", "The Indian Ocean", "The Atlantic Ocean", "The Arctic Ocean", "The Pacific Ocean"),
  G("Which sea lies between Europe and Africa?", "The Mediterranean Sea", "The Caribbean Sea", "The Red Sea", "The North Sea"),
  G("Which sea is so salty that people float easily on it?", "The Dead Sea", "The Mediterranean Sea", "The Baltic Sea", "The Caribbean Sea"),
  G("What is the largest lake in the world?", "The Caspian Sea", "Lake Superior", "Lake Michigan", "Lake Tahoe"),
  G("What is the deepest lake in the world?", "Lake Baikal", "Lake Erie", "Lake Superior", "Loch Ness"),
  G("How many Great Lakes are there in North America?", "Five", "Three", "Seven", "Ten"),
  G("Which of these is NOT one of the Great Lakes?", "Lake Tahoe", "Lake Superior", "Lake Erie", "Lake Michigan"),
  G("What is the deepest place in all the oceans?", "The Mariana Trench", "The Grand Canyon", "The Dead Sea", "The Bermuda Triangle"),

  /* ==================== GEOGRAPHY — Deserts ==================== */
  G("What is the largest hot desert in the world?", "The Sahara", "The Gobi", "The Mojave", "The Atacama"),
  G("The Sahara Desert is on which continent?", "Africa", "Asia", "Australia", "South America"),
  G("The Gobi Desert is on which continent?", "Asia", "Africa", "North America", "Europe"),
  G("The Atacama, the driest desert on Earth, is in which country?", "Chile", "Egypt", "Australia", "Mexico"),
  G("Which desert covers much of the southwestern United States near Las Vegas?", "The Mojave", "The Sahara", "The Gobi", "The Kalahari"),

  /* ==================== GEOGRAPHY — Continents & countries ==================== */
  G("How many continents are there?", "Seven", "Five", "Six", "Nine"),
  G("What is the largest continent?", "Asia", "Africa", "Europe", "North America"),
  G("What is the smallest continent?", "Australia", "Europe", "Antarctica", "South America"),
  G("Which continent is the coldest?", "Antarctica", "Europe", "Asia", "North America"),
  G("What is the largest country in the world by area?", "Russia", "China", "The United States", "Australia"),
  G("What is the second-largest country in the world by area?", "Canada", "Brazil", "India", "Mexico"),
  G("Which country has the most people in the world today?", "India", "The United States", "Russia", "Brazil"),
  G("What is the smallest country in the world?", "Vatican City", "Monaco", "Luxembourg", "Iceland"),
  G("Which country is shaped like a boot?", "Italy", "France", "Spain", "Greece"),
  G("What is the largest country in South America?", "Brazil", "Argentina", "Peru", "Chile"),
  G("Kangaroos and koalas are found in the wild in which country?", "Australia", "Brazil", "South Africa", "India"),
  G("Which country is known as the Land of the Rising Sun?", "Japan", "China", "Egypt", "Spain"),
  G("Which country is famous for tulips and windmills?", "The Netherlands", "France", "Italy", "Greece"),
  G("The pyramids of Giza are in which country?", "Egypt", "Mexico", "Greece", "Peru"),
  G("Which country has a red maple leaf on its flag?", "Canada", "The United States", "Japan", "Switzerland"),
  G("Which country sits partly in Europe and partly in Asia?", "Turkey", "France", "Spain", "Egypt"),
  G("The Great Barrier Reef lies off the coast of which country?", "Australia", "Brazil", "Mexico", "India"),
  G("The Amazon rainforest is mostly in which country?", "Brazil", "Mexico", "Egypt", "Spain"),
  G("Which Italian city is famous for its canals and gondolas?", "Venice", "Rome", "Milan", "Naples"),
  G("Which continent has no permanent human residents?", "Antarctica", "Australia", "South America", "Africa"),
  G("On which continent do penguins live in the wild?", "Antarctica", "The Arctic", "Europe", "North America"),

  /* ==================== GEOGRAPHY — Famous landmarks ==================== */
  G("The Eiffel Tower stands in which city?", "Paris", "London", "Rome", "New York"),
  G("The Statue of Liberty stands in the harbor of which city?", "New York City", "Boston", "Washington, D.C.", "Philadelphia"),
  G("The Statue of Liberty was a gift to America from which country?", "France", "England", "Italy", "Spain"),
  G("The Golden Gate Bridge is in which city?", "San Francisco", "New York", "Seattle", "Los Angeles"),
  G("The Grand Canyon is in which U.S. state?", "Arizona", "Colorado", "Nevada", "Utah"),
  G("Mount Rushmore, with the faces of four presidents, is in which state?", "South Dakota", "North Dakota", "Wyoming", "Montana"),
  G("Niagara Falls sits on the border between the United States and which country?", "Canada", "Mexico", "France", "Iceland"),
  G("The Great Wall is in which country?", "China", "Japan", "India", "Egypt"),
  G("The Taj Mahal is in which country?", "India", "Egypt", "Turkey", "China"),
  G("The ancient Colosseum stands in which city?", "Rome", "Athens", "Paris", "Cairo"),
  G("The famous clock tower known as Big Ben is in which city?", "London", "Paris", "New York", "Sydney"),
  G("The famous Opera House with sail-shaped roofs is in which city?", "Sydney", "London", "Venice", "San Francisco"),
  G("The ancient mountain city of Machu Picchu is in which country?", "Peru", "Mexico", "Egypt", "Greece"),
  G("The giant Christ the Redeemer statue overlooks which city?", "Rio de Janeiro", "Buenos Aires", "Mexico City", "Lisbon"),
  G("The famous Leaning Tower is in which Italian city?", "Pisa", "Rome", "Venice", "Florence"),
  G("The Panama Canal connects which two oceans?", "The Atlantic and the Pacific", "The Atlantic and the Indian", "The Pacific and the Arctic", "The Indian and the Arctic"),
  G("The Suez Canal is in which country?", "Egypt", "Panama", "Turkey", "Greece"),

  /* ==================== GEOGRAPHY — The United States & the world ==================== */
  G("What is the largest U.S. state by area?", "Alaska", "Texas", "California", "Montana"),
  G("What is the smallest U.S. state?", "Rhode Island", "Delaware", "Hawaii", "Connecticut"),
  G("Which state is nicknamed the Sunshine State?", "Florida", "California", "Arizona", "Hawaii"),
  G("Which state is nicknamed the Lone Star State?", "Texas", "Arizona", "Nevada", "Oklahoma"),
  G("Which state is famous for growing potatoes?", "Idaho", "Florida", "Maine", "Kansas"),
  G("Which state is nicknamed the Aloha State?", "Hawaii", "Florida", "California", "Alaska"),
  G("Which American city is nicknamed the Windy City?", "Chicago", "New York", "Boston", "Seattle"),
  G("Yellowstone, America's first national park, is mostly in which state?", "Wyoming", "Colorado", "California", "Alaska"),
  G("The Great Salt Lake is in which state?", "Utah", "Nevada", "Arizona", "New Mexico"),
  G("Which U.S. state reaches the farthest north?", "Alaska", "Maine", "Washington", "Minnesota"),
  G("The Everglades wetlands are in which state?", "Florida", "Louisiana", "Georgia", "Texas"),
  G("Which American city is nicknamed the Big Apple?", "New York City", "Los Angeles", "Chicago", "Miami"),
  G("The equator crosses which of these continents?", "South America", "Europe", "Australia", "Antarctica"),
  G("The prime meridian, where world time begins, passes through which city?", "London", "Paris", "New York", "Rome"),
  G("The North Pole sits in the middle of which ocean?", "The Arctic Ocean", "The Pacific Ocean", "The Atlantic Ocean", "The Indian Ocean"),

  /* ==================== HISTORY — More ancient & classical ==================== */
  H("Which Roman emperor built a famous wall across northern Britain?", "Hadrian", "Nero", "Caligula", "Marcus Aurelius"),
  H("The Rosetta Stone helped scholars finally read what?", "Egyptian hieroglyphics", "Viking runes", "Chinese characters", "Roman numerals"),
  H("The ancient city of Babylon stood in which modern country?", "Iraq", "Egypt", "Greece", "Spain"),
  H("The famous Hanging Gardens were said to be in which city?", "Babylon", "Athens", "Rome", "Cairo"),
  H("Which ancient people invented paper?", "The Chinese", "The Romans", "The Vikings", "The Aztecs"),
  H("Which ancient people of Mesopotamia invented the first writing?", "The Sumerians", "The Vikings", "The Incas", "The Celts"),
  H("Which ancient sea traders were famous for their purple dye?", "The Phoenicians", "The Mongols", "The Saxons", "The Franks"),
  H("Who wrote the ancient Greek epics the Iliad and the Odyssey?", "Homer", "Aesop", "Socrates", "Plato"),
  H("Which ancient Greek is famous for short stories with morals, like 'The Tortoise and the Hare'?", "Aesop", "Homer", "Euclid", "Archimedes"),
  H("Which Greek philosopher was the personal teacher of Alexander the Great?", "Aristotle", "Socrates", "Homer", "Pythagoras"),
  H("Which Greek philosopher was sentenced to drink poison hemlock?", "Socrates", "Aristotle", "Plato", "Homer"),
  H("Which ancient Greek is called the father of geometry?", "Euclid", "Homer", "Aesop", "Alexander"),
  H("Which ancient inventor shouted 'Eureka!' in his bathtub?", "Archimedes", "Aristotle", "Julius Caesar", "Homer"),
  H("Julius Caesar started a civil war by crossing which small river?", "The Rubicon", "The Nile", "The Danube", "The Thames"),
  H("Spartacus was famous as what?", "A gladiator who led a slave revolt", "A Greek poet", "An Egyptian king", "A Roman emperor"),
  H("Which Roman town was buried by Mount Vesuvius along with Pompeii?", "Herculaneum", "Ostia", "Ravenna", "Naples"),
  H("Which Roman emperor first embraced Christianity?", "Constantine", "Nero", "Julius Caesar", "Hadrian"),
  H("In roughly what year did the Western Roman Empire fall?", "AD 476", "AD 1000", "AD 100", "AD 1492"),
  H("The buried Terracotta Army of clay soldiers was discovered in which country?", "China", "Egypt", "Greece", "Mexico"),
  H("Who was the first emperor of China?", "Qin Shi Huang", "Confucius", "Kublai Khan", "Mao"),
  H("The Silk Road was an ancient trade route connecting China with what?", "Europe", "Australia", "North America", "Antarctica"),
  H("The wise teacher Confucius lived in which land?", "China", "Greece", "Egypt", "Persia"),
  H("Ancient Egyptians wrote on sheets made from which plant?", "Papyrus", "Bamboo", "Oak bark", "Cotton"),
  H("At which narrow pass did 300 Spartans make their famous stand?", "Thermopylae", "Marathon", "Troy", "Olympia"),
  H("Which Roman general famously fell in love with Cleopatra?", "Mark Antony", "Hadrian", "Constantine", "Spartacus"),
  H("Who was the Roman god of war?", "Mars", "Jupiter", "Neptune", "Apollo"),
  H("What was the main public square of ancient Rome called?", "The Forum", "The Agora", "The Plaza", "The Piazza"),
  H("What races were held at Rome's Circus Maximus?", "Chariot races", "Horse and buggy races", "Foot races only", "Boat races"),
  H("The ancient lighthouse wonder of the world stood in which Egyptian city?", "Alexandria", "Cairo", "Giza", "Luxor"),
  H("Who was the king of the Greek gods?", "Zeus", "Apollo", "Hercules", "Poseidon"),
  H("Mount Olympus was said to be the home of what?", "The Greek gods", "The Roman senate", "The pharaohs", "The Vikings"),
  H("Pompeii lay hidden for centuries under what?", "Volcanic ash", "Desert sand", "Jungle vines", "Sea water"),

  /* ==================== HISTORY — More Middle Ages & Renaissance ==================== */
  H("Who crowned Charlemagne emperor in the year 800?", "The Pope", "Napoleon", "The king of England", "A Viking chief"),
  H("What was the name of King Arthur's legendary sword?", "Excalibur", "Durandal", "The Claymore", "Glamdring"),
  H("King Arthur's knights famously gathered around what?", "The Round Table", "The Long Bench", "The Great Fire", "The Stone Circle"),
  H("In which forest did Robin Hood hide from the Sheriff?", "Sherwood Forest", "The Black Forest", "Nottingham Woods", "Epping Forest"),
  H("The famous Bayeux Tapestry tells the story of which event?", "The Battle of Hastings", "The Crusades", "The Black Death", "The Great Fire of London"),
  H("What style of soaring, pointed-arch cathedrals rose in the Middle Ages?", "Gothic", "Baroque", "Art Deco", "Modernist"),
  H("King Richard the Lionheart of England fought in which wars?", "The Crusades", "The World Wars", "The Wars of the Roses", "The Napoleonic Wars"),
  H("In what year did Constantinople fall to the Ottoman Turks?", "1453", "1066", "1215", "1776"),
  H("The great city of Constantinople is known today as what?", "Istanbul", "Athens", "Cairo", "Baghdad"),
  H("The Hundred Years' War was fought between which two countries?", "England and France", "Spain and Portugal", "Italy and Greece", "Russia and Sweden"),
  H("About how long did the Hundred Years' War actually last?", "116 years", "Exactly 100 years", "50 years", "200 years"),
  H("In legend, William Tell shot an arrow through what on his son's head?", "An apple", "A pear", "A hat", "A candle"),
  H("Marco Polo served at the court of which great khan?", "Kublai Khan", "Genghis Khan", "Attila", "Tamerlane"),
  H("The beautiful Alhambra palace in Spain was built by whom?", "The Moors", "The Romans", "The Vikings", "The Greeks"),
  H("Before printing, books in Europe were copied by hand mostly by whom?", "Monks", "Knights", "Kings", "Merchants"),
  H("The samurai were the warrior class of which country?", "Japan", "China", "Mongolia", "Korea"),
  H("What was the samurai code of honor called?", "Bushido", "Chivalry", "Karate", "Origami"),
  H("Typhoons called 'kamikaze' twice saved which country from Mongol invasion?", "Japan", "England", "Egypt", "India"),
  H("The real prince Vlad the Impaler inspired which famous fictional character?", "Count Dracula", "Frankenstein", "Robin Hood", "King Arthur"),
  H("What was the first major book Gutenberg printed?", "The Bible", "A dictionary", "A cookbook", "A songbook"),
  H("Leonardo da Vinci painted 'The Last Supper' on a wall in which city?", "Milan", "Rome", "Paris", "Venice"),
  H("Who carved the giant marble statue of David?", "Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"),
  H("When Columbus landed in the Americas, where did he believe he was?", "The Indies, near Asia", "Africa", "Australia", "A new continent"),
  H("Which Portuguese explorer first sailed around Africa to reach India?", "Vasco da Gama", "Christopher Columbus", "Marco Polo", "Captain Cook"),
  H("The Spanish conqueror Hernán Cortés defeated which empire?", "The Aztec Empire", "The Inca Empire", "The Roman Empire", "The Ottoman Empire"),
  H("The Spanish conqueror Francisco Pizarro defeated which empire?", "The Inca Empire", "The Aztec Empire", "The Mongol Empire", "The Persian Empire"),
  H("What was the name of the Aztec capital, built on a lake?", "Tenochtitlan", "Machu Picchu", "Cusco", "Chichen Itza"),
  H("Martin Luther set off which great religious movement in 1517?", "The Reformation", "The Renaissance", "The Crusades", "The Enlightenment"),
  H("Luther nailed his famous 95 Theses to a church door in which town?", "Wittenberg", "Rome", "Paris", "Geneva"),
  H("Henry VIII broke England away from which church?", "The Roman Catholic Church", "The Greek Orthodox Church", "The Lutheran Church", "The Church of Sweden"),
  H("Copernicus shocked the world by saying the Earth moves around what?", "The Sun", "The Moon", "The stars", "Nothing — it stands still"),
  H("Galileo studied the night sky with which improved instrument?", "The telescope", "The microscope", "The compass", "The sextant"),
  H("Galileo was put on trial for teaching what?", "That the Earth moves around the Sun", "That the Earth is flat", "That the Moon is made of rock", "That stars are far away"),
  H("The Wars of the Roses were fought over the throne of which country?", "England", "France", "Spain", "Scotland"),
  H("What were the mock battles called where knights charged with lances?", "Jousting tournaments", "Fencing matches", "Duels", "Melees only"),
  H("Knights on horseback charged with long poles called what?", "Lances", "Javelins", "Pikes", "Spears"),
  H("What was medieval armor of small interlocking metal rings called?", "Chain mail", "Plate mail", "Ring plate", "Iron weave"),
  H("What was a young knight-in-training called?", "A squire", "A serf", "A jester", "A friar"),

  /* ==================== HISTORY — More early modern times ==================== */
  H("Ivan the Terrible was the first crowned tsar of which country?", "Russia", "Poland", "Austria", "Sweden"),
  H("Peter the Great built which grand new capital city for Russia?", "St. Petersburg", "Moscow", "Kyiv", "Warsaw"),
  H("Catherine the Great was a famous empress of which country?", "Russia", "France", "Austria", "Spain"),
  H("Which French king built the glittering Palace of Versailles?", "Louis XIV", "Napoleon", "Charlemagne", "Louis XVI"),
  H("What was Louis XIV's famous nickname?", "The Sun King", "The Lionheart", "The Great Bear", "The Iron Duke"),
  H("In what year did the Great Fire of London burn?", "1666", "1566", "1766", "1866"),
  H("Where did the Great Fire of London start?", "In a bakery", "In a palace", "In a church", "In a theater"),
  H("Guy Fawkes was caught trying to blow up what in 1605?", "The English Parliament", "The Tower of London", "Buckingham Palace", "London Bridge"),
  H("Oliver Cromwell ruled England after which conflict?", "The English Civil War", "The Hundred Years' War", "The Crusades", "The Napoleonic Wars"),
  H("The great painter Rembrandt came from which country?", "The Netherlands", "Italy", "France", "Spain"),
  H("Mozart was born in which country?", "Austria", "Germany", "Italy", "Hungary"),
  H("Mozart began composing music at about what age?", "Five", "Fifteen", "Twenty", "Thirty"),
  H("Beethoven kept composing great music even after losing his what?", "Hearing", "Sight", "Voice", "Right hand"),
  H("Which composer wrote 'The Four Seasons'?", "Vivaldi", "Mozart", "Beethoven", "Chopin"),
  H("The composer Johann Sebastian Bach came from which country?", "Germany", "Austria", "Italy", "France"),
  H("Captain James Cook is famous for exploring which ocean?", "The Pacific", "The Arctic", "The Atlantic", "The Indian... coast of Africa"),
  H("Britain first used Australia as what?", "A prison colony", "A trading post only", "A vacation land", "A gold mine"),
  H("The guillotine became a grim symbol of which revolution?", "The French Revolution", "The American Revolution", "The Russian Revolution", "The Industrial Revolution"),
  H("To which remote island was Napoleon finally exiled?", "St. Helena", "Elba", "Corsica", "Sicily"),
  H("Which island did Napoleon escape from before his final defeat?", "Elba", "St. Helena", "Malta", "Crete"),
  H("Admiral Nelson won his famous 1805 sea battle at which cape?", "Trafalgar", "Waterloo", "Normandy", "Dunkirk"),
  H("The Boston Massacre helped spark which war?", "The American Revolution", "The Civil War", "The War of 1812", "The French Revolution"),
  H("Who declared 'Give me liberty, or give me death!'?", "Patrick Henry", "George Washington", "Paul Revere", "Benjamin Franklin"),
  H("The cracked Liberty Bell is kept in which city?", "Philadelphia", "Boston", "Washington, D.C.", "New York"),
  H("Betsy Ross is celebrated for sewing what?", "An early American flag", "The first quilt", "Washington's coat", "The Mayflower's sails"),
  H("Who was the first president to live in the White House?", "John Adams", "George Washington", "Thomas Jefferson", "Abraham Lincoln"),
  H("Who wrote the words to 'The Star-Spangled Banner'?", "Francis Scott Key", "Betsy Ross", "John Adams", "Samuel Morse"),
  H("During the War of 1812, British troops burned which famous building?", "The White House", "Independence Hall", "The Alamo", "Federal Hall"),
  H("Simón Bolívar helped free much of which continent from Spain?", "South America", "Africa", "Asia", "Australia"),
  H("Mexico won its independence from which country?", "Spain", "France", "Portugal", "England"),
  H("The Rosetta Stone was found by soldiers serving which leader?", "Napoleon", "Julius Caesar", "Queen Victoria", "Alexander the Great"),
  H("Jane Austen wrote which beloved novel?", "Pride and Prejudice", "Jane Eyre", "Little Women", "Wuthering Heights"),
  H("Which English queen was nicknamed 'Bloody Mary'?", "Mary I", "Elizabeth I", "Victoria", "Anne"),
  H("Sir Walter Raleigh is credited with bringing which crops to England?", "Tobacco and potatoes", "Tea and rice", "Corn and beans", "Sugar and coffee"),
  H("Blackbeard was a famous what?", "Pirate", "King", "Painter", "Explorer"),
  H("What was the skull-and-crossbones pirate flag called?", "The Jolly Roger", "The Black Death", "The Sea Devil", "The Crossbones Banner"),
  H("The town of Salem, Massachusetts is remembered for which 1692 events?", "Witch trials", "Gold rush", "Tea party", "Earthquake"),
  H("Marie Curie won how many Nobel Prizes?", "Two", "One", "Three", "None"),
  H("Marie Curie is famous for her research on what?", "Radioactivity", "Gravity", "Electricity", "Vaccines"),
  H("The Tudor rose combined which two colors of warring houses?", "Red and white", "Blue and gold", "Green and white", "Purple and red"),

  /* ==================== HISTORY — More of the 1800s ==================== */
  H("George Stephenson was a pioneer of what?", "Steam locomotives", "Airplanes", "Automobiles", "Telephones"),
  H("Robert Fulton made which invention practical in America?", "The steamboat", "The airplane", "The bicycle", "The elevator"),
  H("Louis Pasteur invented which process that makes milk safe?", "Pasteurization", "Refrigeration", "Fermentation", "Condensation"),
  H("Louis Pasteur developed a life-saving vaccine against which disease?", "Rabies", "Polio", "Measles", "Smallpox"),
  H("Alfred Nobel, founder of the Nobel Prizes, invented what?", "Dynamite", "The telephone", "The light bulb", "The radio"),
  H("Charles Dickens wrote which famous Christmas story?", "A Christmas Carol", "The Night Before Christmas", "The Nutcracker", "Miracle on 34th Street"),
  H("Who created the detective Sherlock Holmes?", "Arthur Conan Doyle", "Charles Dickens", "Agatha Christie", "Mark Twain"),
  H("Vincent van Gogh painted famous pictures of which flowers?", "Sunflowers", "Roses", "Tulips", "Daisies"),
  H("Vincent van Gogh famously cut off part of his own what?", "Ear", "Finger", "Hair", "Beard"),
  H("Which composer wrote the Christmas ballet 'The Nutcracker'?", "Tchaikovsky", "Mozart", "Beethoven", "Strauss"),
  H("The first modern Olympic Games of 1896 were held in which city?", "Athens", "Paris", "London", "Rome"),
  H("The Eiffel Tower was built for which event?", "The 1889 World's Fair", "The 1900 Olympics", "Napoleon's coronation", "The French Revolution"),
  H("The Suez Canal connects the Mediterranean Sea with which sea?", "The Red Sea", "The Black Sea", "The Dead Sea", "The North Sea"),
  H("The huge volcanic eruption of Krakatoa in 1883 happened in which country?", "Indonesia", "Italy", "Japan", "Mexico"),
  H("The terrible potato famine of the 1840s struck which country?", "Ireland", "France", "Poland", "Sweden"),
  H("Ellis Island in New York welcomed millions of what?", "Immigrants", "Soldiers", "Gold miners", "Tourists"),
  H("What invention put the Pony Express out of business?", "The telegraph", "The automobile", "The airplane", "The radio"),
  H("Buffalo Bill Cody was famous for what kind of show?", "Wild West shows", "Magic shows", "Circus acrobatics", "Opera"),
  H("The famous gunfight at the O.K. Corral happened in which town?", "Tombstone, Arizona", "Dodge City, Kansas", "Deadwood, South Dakota", "Santa Fe, New Mexico"),
  H("Jesse James was a famous American what?", "Outlaw", "Sheriff", "President", "Inventor"),
  H("Mark Twain wrote about which mischievous boy?", "Tom Sawyer", "Oliver Twist", "Peter Pan", "Pinocchio"),
  H("Before airplanes, the Wright brothers ran what kind of shop?", "A bicycle shop", "A bakery", "A print shop", "A blacksmith shop"),
  H("What became America's first national park in 1872?", "Yellowstone", "Yosemite", "The Grand Canyon", "The Everglades"),
  H("Clara Barton founded which American organization?", "The American Red Cross", "The Girl Scouts", "The Salvation Army", "The Peace Corps"),
  H("The International Red Cross was founded in which country?", "Switzerland", "The United States", "France", "England"),
  H("Who co-wrote 'The Communist Manifesto'?", "Karl Marx", "Lenin", "Stalin", "Napoleon"),
  H("Who was Queen Victoria's beloved husband?", "Prince Albert", "Prince Philip", "King George", "Prince Edward"),
  H("Frontiersman Davy Crockett died defending which fort?", "The Alamo", "Fort Knox", "Fort Sumter", "West Point"),
  H("The Alamo stands in which Texas city?", "San Antonio", "Houston", "Dallas", "Austin"),
  H("Texas won its independence from which country?", "Mexico", "Spain", "France", "England"),
  H("The 'Trail of Tears' was the forced march of whom?", "Native Americans", "Gold miners", "Confederate soldiers", "Railroad workers"),
  H("Which president's face is on the American penny?", "Abraham Lincoln", "George Washington", "Thomas Jefferson", "Theodore Roosevelt"),
  H("Along with Washington, Jefferson, and Lincoln, who is carved on Mount Rushmore?", "Theodore Roosevelt", "Franklin D. Roosevelt", "John F. Kennedy", "Andrew Jackson"),
  H("The teddy bear was named after which president?", "Theodore Roosevelt", "Thomas Jefferson", "Harry Truman", "William Taft"),
  H("The Brooklyn Bridge connects Brooklyn with which island?", "Manhattan", "Staten Island", "Long Island's east end", "Ellis Island"),
  H("Louis Braille invented a reading system for whom?", "Blind people", "Deaf people", "Sailors", "Soldiers"),
  H("How is Braille writing read?", "By touch, with the fingertips", "With special glasses", "By listening", "With a magnifying glass"),
  H("Levi Strauss became famous for making what?", "Blue jeans", "Cowboy hats", "Leather boots", "Flannel shirts"),
  H("The first great World's Fair of 1851 was held in which city?", "London", "Paris", "New York", "Chicago"),
  H("A great earthquake and fire destroyed much of which city in 1906?", "San Francisco", "Chicago", "New York", "Los Angeles"),
  H("Which president led the building of the Panama Canal?", "Theodore Roosevelt", "Abraham Lincoln", "Woodrow Wilson", "Herbert Hoover"),
  H("Who was the U.S. president during World War I?", "Woodrow Wilson", "Theodore Roosevelt", "Franklin D. Roosevelt", "Calvin Coolidge"),

  /* ==================== HISTORY — More of the 1900s ==================== */
  H("The Titanic was sailing from Southampton to which city?", "New York", "Boston", "Miami", "Lisbon"),
  H("What did the Titanic's band famously do as the ship sank?", "Kept playing music", "Rowed a lifeboat", "Jumped first", "Fell silent"),
  H("What was Henry Ford's famous affordable car called?", "The Model T", "The Mustang", "The Beetle", "The Cadillac"),
  H("Henry Ford made cars cheap by perfecting what?", "The assembly line", "The gas engine", "The rubber tire", "The car radio"),
  H("Who led the first expedition to reach the South Pole?", "Roald Amundsen", "Robert Falcon Scott", "Ernest Shackleton", "Robert Peary"),
  H("Explorer Robert Falcon Scott died returning from where?", "The South Pole", "The North Pole", "Mount Everest", "The Amazon"),
  H("Which explorer is usually credited as first to reach the North Pole?", "Robert Peary", "Roald Amundsen", "Christopher Columbus", "Marco Polo"),
  H("What was the name of Shackleton's ship, crushed by Antarctic ice?", "Endurance", "Discovery", "Terror", "Beagle"),
  H("In what year did the Panama Canal open?", "1914", "1869", "1945", "1900"),
  H("The 'Red Baron' was a famous World War I what?", "German fighter pilot", "Russian general", "British spy", "French tank commander"),
  H("On what date is Armistice Day, ending World War I?", "November 11", "July 4", "December 7", "June 6"),
  H("Which treaty officially ended World War I?", "The Treaty of Versailles", "The Treaty of Paris", "The Magna Carta", "The Yalta Agreement"),
  H("In what year was the Russian Revolution?", "1917", "1905", "1939", "1848"),
  H("Who led the Russian Revolution of 1917?", "Lenin", "Stalin", "Nicholas II", "Trotsky alone"),
  H("Who was the last tsar of Russia?", "Nicholas II", "Peter the Great", "Ivan the Terrible", "Alexander I"),
  H("What did the letters USSR stand for?", "Union of Soviet Socialist Republics", "United States of Southern Russia", "Union of Slavic Sovereign Regions", "United Soviet States of Russia"),
  H("Joseph Stalin ruled which country?", "The Soviet Union", "Germany", "China", "Yugoslavia"),
  H("What was Charles Lindbergh's famous airplane called?", "The Spirit of St. Louis", "The Flyer", "The Enola Gay", "The Concorde"),
  H("Lindbergh flew nonstop and alone from New York to which city in 1927?", "Paris", "London", "Rome", "Berlin"),
  H("What was the first major talking movie, released in 1927?", "The Jazz Singer", "Gone with the Wind", "The Wizard of Oz", "Casablanca"),
  H("Who created Mickey Mouse?", "Walt Disney", "Jim Henson", "Charles Schulz", "Dr. Seuss"),
  H("The Hindenburg, which caught fire in 1937, was what kind of craft?", "A giant airship", "An ocean liner", "A submarine", "An airplane"),
  H("In what year was the Empire State Building completed?", "1931", "1911", "1951", "1971"),
  H("In what year did the Golden Gate Bridge open?", "1937", "1907", "1957", "1977"),
  H("Jesse Owens won four gold medals at which Olympic Games?", "Berlin 1936", "Los Angeles 1932", "London 1948", "Rome 1960"),
  H("Germany, Italy, and Japan formed which World War II alliance?", "The Axis", "The Allies", "The League", "The Union"),
  H("Britain, the United States, and the Soviet Union were part of which side in World War II?", "The Allies", "The Axis", "The Central Powers", "The Coalition"),
  H("The Battle of Britain was fought mainly where?", "In the air", "At sea", "In the desert", "In the mountains"),
  H("What was Britain's secret World War II code-breaking center called?", "Bletchley Park", "Scotland Yard", "Whitehall", "Camp David"),
  H("Alan Turing helped crack which German code machine?", "Enigma", "Morse", "Cipher-X", "The Red Machine"),
  H("From which French port were British troops rescued by small boats in 1940?", "Dunkirk", "Normandy", "Calais... in 1944", "Marseille"),
  H("Which general promised 'I shall return' — and did?", "Douglas MacArthur", "George Patton", "Dwight Eisenhower", "Ulysses S. Grant"),
  H("Which president made the decision to drop the atomic bomb?", "Harry Truman", "Franklin D. Roosevelt", "Dwight Eisenhower", "Herbert Hoover"),
  H("V-E Day celebrated victory where?", "In Europe", "In the Pacific", "In Africa", "At sea"),
  H("In what year was the United Nations founded?", "1945", "1919", "1960", "1939"),
  H("The United Nations headquarters is in which city?", "New York", "Geneva", "Paris", "London"),
  H("The Marshall Plan spent billions to rebuild what after World War II?", "Europe", "Japan", "South America", "The American South"),
  H("During the Berlin Airlift, Allied planes delivered what to the city?", "Food and supplies", "Weapons", "Soldiers", "Mail only"),
  H("In what year did the Korean War begin?", "1950", "1945", "1939", "1965"),
  H("Who was the first woman to travel into space?", "Valentina Tereshkova", "Sally Ride", "Amelia Earhart", "Mae Jemison"),
  H("Who was the first American to orbit the Earth?", "John Glenn", "Neil Armstrong", "Alan Shepard", "Buzz Aldrin"),
  H("Which troubled moon mission radioed 'Houston, we've had a problem'?", "Apollo 13", "Apollo 11", "Apollo 1", "Gemini 4"),
  H("Who was the second person to walk on the moon?", "Buzz Aldrin", "Neil Armstrong", "John Glenn", "Michael Collins"),
  H("Who was called the King of Rock and Roll?", "Elvis Presley", "Frank Sinatra", "Johnny Cash", "Chuck Berry"),
  H("The Beatles came from which English city?", "Liverpool", "London", "Manchester", "Birmingham"),
  H("The famous Woodstock music festival happened in which year?", "1969", "1959", "1979", "1989"),
  H("In what year was Queen Elizabeth II crowned?", "1953", "1945", "1963", "1937"),
  H("Who first climbed Mount Everest in 1953, along with Tenzing Norgay?", "Edmund Hillary", "George Mallory", "Reinhold Messner", "Robert Peary"),
  H("Roger Bannister was the first person to run what?", "A mile in under four minutes", "A marathon in under three hours", "100 meters in under ten seconds", "Around the world"),
  H("Dr. Christiaan Barnard performed the world's first what in 1967?", "Heart transplant", "X-ray", "Open-brain surgery", "Laser eye surgery"),
  H("Which two scientists described the structure of DNA?", "Watson and Crick", "Lewis and Clark", "Wright and Wright", "Marie and Pierre Curie"),
  H("The Concorde airplane was famous for flying how?", "Faster than the speed of sound", "Without any pilots", "On solar power", "Upside down"),
  H("Martin Luther King Jr. won which famous international prize?", "The Nobel Peace Prize", "The Pulitzer Prize", "An Olympic medal", "An Academy Award"),
  H("Which president signed the Civil Rights Act of 1964?", "Lyndon B. Johnson", "John F. Kennedy", "Richard Nixon", "Dwight Eisenhower"),
  H("Who was the first African American justice on the Supreme Court?", "Thurgood Marshall", "Martin Luther King Jr.", "Frederick Douglass", "Barack Obama"),
  H("Who was the first woman on the U.S. Supreme Court?", "Sandra Day O'Connor", "Ruth Bader Ginsburg", "Eleanor Roosevelt", "Susan B. Anthony"),
  H("Sally Ride was the first American woman to do what?", "Travel into space", "Fly across the Atlantic", "Climb Mount Everest", "Win an Olympic gold"),
  H("In what year did the Space Shuttle first fly?", "1981", "1969", "1991", "1975"),
  H("The 1986 Chernobyl nuclear accident happened in which present-day country?", "Ukraine", "Poland", "Hungary", "Germany"),
  H("Which president said, 'Mr. Gorbachev, tear down this wall!'?", "Ronald Reagan", "Jimmy Carter", "George Washington", "John F. Kennedy"),
  H("In what year was Germany reunited into one country?", "1990", "1980", "2000", "1970"),
  H("In what year did the Soviet Union break apart?", "1991", "1985", "1979", "1999"),
  H("The Hubble Space Telescope was launched in which year?", "1990", "1969", "2005", "1980"),
  H("The Channel Tunnel runs under the sea between England and which country?", "France", "Ireland", "Belgium", "The Netherlands"),
  H("In 1997, Hong Kong was returned to which country?", "China", "Japan", "Britain... it kept it", "Portugal"),
  H("Who found the wreck of the Titanic in 1985?", "Robert Ballard", "Jacques Cousteau", "James Cameron", "Neil Armstrong"),
  H("Princess Diana died in a car crash in which city?", "Paris", "London", "Monaco", "Rome"),
  H("The 'Y2K' worry of 1999 was about what failing?", "Computers", "Airplanes", "Telephones", "Power dams only"),
  H("Mother Teresa spent her life helping the poor of which city?", "Calcutta", "Cairo", "Rio de Janeiro", "Manila"),
  H("Pope John Paul II came from which country?", "Poland", "Italy", "Spain", "Ireland"),
  H("The gangster Al Capone was finally jailed for what?", "Tax evasion", "Bank robbery", "Smuggling", "Kidnapping"),
  H("The Dust Bowl of the 1930s devastated which American region?", "The Great Plains", "New England", "The Pacific Coast", "The Deep South... swamps"),
  H("Who wrote 'The Grapes of Wrath' about Dust Bowl families?", "John Steinbeck", "Mark Twain", "Ernest Hemingway", "F. Scott Fitzgerald"),
  H("The Hoover Dam holds back which river?", "The Colorado River", "The Mississippi River", "The Columbia River", "The Rio Grande"),
  H("The secret Manhattan Project built what?", "The atomic bomb", "The first computer", "The first jet", "The Pentagon"),
  H("Albert Einstein was born in which country?", "Germany", "The United States", "Austria", "Switzerland"),
  H("During World War II, rationing meant families got limited amounts of what?", "Food and everyday goods", "Newspapers", "Movie tickets", "Mail"),
  H("World War II 'victory gardens' encouraged families to do what?", "Grow their own vegetables", "Plant flowers for soldiers", "Raise chickens for the army", "Sell their lawns"),
  H("The G.I. Bill helped returning veterans pay for what?", "College and homes", "Cars only", "Vacations", "Uniforms"),
  H("Historic Route 66 ran from Chicago to which city?", "Los Angeles", "Miami", "Seattle", "New Orleans"),
  H("The transistor, heart of modern electronics, was invented where?", "Bell Labs", "NASA", "Harvard University", "The Pentagon"),
  H("Which space agency was created in 1958, partly in answer to Sputnik?", "NASA", "The United Nations", "The Air Force", "SpaceX"),
  H("Fidel Castro led a 1959 revolution in which country?", "Cuba", "Mexico", "Spain", "Brazil"),
  H("The failed Bay of Pigs invasion of 1961 targeted which country?", "Cuba", "Vietnam", "Korea", "Panama"),
  H("What was the goal of the Apollo program?", "Landing people on the moon", "Building a space station", "Reaching Mars", "Launching satellites only"),
  H("What was the name of Apollo 11's lunar lander?", "The Eagle", "The Falcon", "The Columbia", "The Enterprise"),
  H("What was Skylab?", "America's first space station", "A famous telescope", "A moon rover", "A spy plane"),
  H("Who coined the phrase 'the Iron Curtain'?", "Winston Churchill", "Harry Truman", "Joseph Stalin", "Franklin D. Roosevelt"),
  H("The 1980 'Miracle on Ice' was a famous upset in which sport?", "Hockey", "Figure skating", "Skiing", "Basketball"),
  H("About how many years did the Berlin Wall stand?", "28 years", "10 years", "50 years", "5 years"),
  H("Which president had been a peanut farmer?", "Jimmy Carter", "Ronald Reagan", "Gerald Ford", "George Bush"),
  H("Which president had been a Hollywood actor?", "Ronald Reagan", "Jimmy Carter", "Richard Nixon", "Lyndon Johnson"),
  H("Who was the first Catholic president of the United States?", "John F. Kennedy", "Franklin D. Roosevelt", "Harry Truman", "Dwight Eisenhower"),
  H("Which president proposed the League of Nations after World War I?", "Woodrow Wilson", "Theodore Roosevelt", "Warren Harding", "Herbert Hoover"),
  H("Which amendment ended Prohibition?", "The 21st Amendment", "The 18th Amendment", "The 13th Amendment", "The 19th Amendment"),
  H("The 'unsinkable' Molly Brown survived which disaster?", "The sinking of the Titanic", "The Hindenburg fire", "The San Francisco earthquake", "The Chicago fire"),
  H("The 'Great War' was later renamed what?", "World War I", "World War II", "The Cold War", "The Civil War"),
  H("Who is the only president elected four times?", "Franklin D. Roosevelt", "George Washington", "Abraham Lincoln", "Theodore Roosevelt"),

  /* ==================== GEOGRAPHY — More world capitals ==================== */
  G("What is the capital of Nigeria?", "Abuja", "Lagos", "Cairo", "Nairobi"),
  G("What is the capital of Ethiopia?", "Addis Ababa", "Cairo", "Lagos", "Khartoum"),
  G("What is the capital of Ghana?", "Accra", "Lagos", "Dakar", "Nairobi"),
  G("What is the capital of Algeria?", "Algiers", "Tunis", "Tripoli", "Casablanca"),
  G("What is the capital of Tunisia?", "Tunis", "Algiers", "Tripoli", "Cairo"),
  G("What is the capital of Libya?", "Tripoli", "Tunis", "Cairo", "Benghazi"),
  G("What is the capital of Sudan?", "Khartoum", "Cairo", "Addis Ababa", "Nairobi"),
  G("What is the capital of Iraq?", "Baghdad", "Tehran", "Damascus", "Riyadh"),
  G("What is the capital of Iran?", "Tehran", "Baghdad", "Kabul", "Istanbul"),
  G("What is the capital of Afghanistan?", "Kabul", "Islamabad", "Tehran", "Baghdad"),
  G("What is the capital of Pakistan?", "Islamabad", "Karachi", "Lahore", "Kabul"),
  G("What is the capital of Bangladesh?", "Dhaka", "Kolkata", "Kathmandu", "Mumbai"),
  G("What is the capital of Nepal?", "Kathmandu", "New Delhi", "Dhaka", "Lhasa"),
  G("What is the capital of the Philippines?", "Manila", "Jakarta", "Bangkok", "Hanoi"),
  G("What is the capital of Indonesia?", "Jakarta", "Manila", "Kuala Lumpur", "Singapore"),
  G("What is the capital of Malaysia?", "Kuala Lumpur", "Jakarta", "Singapore", "Bangkok"),
  G("What is the capital of Mongolia?", "Ulaanbaatar", "Beijing", "Astana", "Seoul"),
  G("What is the capital of Lebanon?", "Beirut", "Damascus", "Amman", "Cairo"),
  G("What is the capital of Syria?", "Damascus", "Beirut", "Baghdad", "Amman"),
  G("What is the capital of Jordan?", "Amman", "Damascus", "Beirut", "Riyadh"),
  G("What is the capital of Qatar?", "Doha", "Dubai", "Abu Dhabi", "Kuwait City"),
  G("What is the capital of the United Arab Emirates?", "Abu Dhabi", "Dubai", "Doha", "Riyadh"),
  G("What is the capital of Kuwait?", "Kuwait City", "Doha", "Riyadh", "Abu Dhabi"),
  G("What is the capital of Bulgaria?", "Sofia", "Bucharest", "Belgrade", "Athens"),
  G("What is the capital of Serbia?", "Belgrade", "Zagreb", "Sofia", "Sarajevo"),
  G("What is the capital of Croatia?", "Zagreb", "Belgrade", "Ljubljana", "Sarajevo"),
  G("What is the capital of Slovakia?", "Bratislava", "Prague", "Budapest", "Ljubljana"),
  G("What is the capital of Slovenia?", "Ljubljana", "Bratislava", "Zagreb", "Vienna"),
  G("What is the capital of Estonia?", "Tallinn", "Riga", "Vilnius", "Helsinki"),
  G("What is the capital of Latvia?", "Riga", "Tallinn", "Vilnius", "Minsk"),
  G("What is the capital of Lithuania?", "Vilnius", "Riga", "Tallinn", "Warsaw"),
  G("What is the capital of Belarus?", "Minsk", "Kyiv", "Moscow", "Vilnius"),
  G("What is the capital of the country of Georgia?", "Tbilisi", "Yerevan", "Baku", "Atlanta"),
  G("What is the capital of Armenia?", "Yerevan", "Tbilisi", "Baku", "Ankara"),
  G("What is the capital of Azerbaijan?", "Baku", "Yerevan", "Tbilisi", "Tehran"),
  G("What is the capital of Luxembourg?", "Luxembourg City", "Brussels", "Bern", "Amsterdam"),
  G("What is the capital of Colombia?", "Bogotá", "Caracas", "Lima", "Quito"),
  G("What is the capital of Venezuela?", "Caracas", "Bogotá", "Quito", "Panama City"),
  G("What is the capital of Ecuador?", "Quito", "Lima", "Bogotá", "La Paz"),
  G("What is the capital of Uruguay?", "Montevideo", "Buenos Aires", "Asunción", "Santiago"),
  G("What is the capital of Paraguay?", "Asunción", "Montevideo", "La Paz", "Lima"),
  G("What is the capital of Costa Rica?", "San José", "Panama City", "Managua", "Havana"),
  G("What is the capital of Panama?", "Panama City", "San José", "Bogotá", "Managua"),
  G("What is the capital of Jamaica?", "Kingston", "Havana", "Nassau", "Port-au-Prince"),
  G("What is the capital of Haiti?", "Port-au-Prince", "Santo Domingo", "Kingston", "Havana"),
  G("What is the capital of the Dominican Republic?", "Santo Domingo", "Port-au-Prince", "San Juan", "Kingston"),
  G("What is the capital of Guatemala?", "Guatemala City", "Mexico City", "San José", "Tegucigalpa"),
  G("What is the capital of Wales?", "Cardiff", "Swansea", "Edinburgh", "Belfast"),
  G("What is the capital of Northern Ireland?", "Belfast", "Dublin", "Cardiff", "Glasgow"),
  G("What is the capital of Malta?", "Valletta", "Nicosia", "Palermo", "Athens"),
  G("What is the capital of Cyprus?", "Nicosia", "Valletta", "Athens", "Beirut"),
  G("What is the capital of Albania?", "Tirana", "Skopje", "Sofia", "Athens"),
  G("What is the capital of Bosnia and Herzegovina?", "Sarajevo", "Belgrade", "Zagreb", "Skopje"),
  G("What is the capital of Zimbabwe?", "Harare", "Nairobi", "Cape Town", "Lusaka"),
  G("What is the capital of Uganda?", "Kampala", "Nairobi", "Kigali", "Addis Ababa"),
  G("What is the capital of Senegal?", "Dakar", "Accra", "Abuja", "Bamako"),
  G("What is the capital of Angola?", "Luanda", "Kinshasa", "Harare", "Windhoek"),
  G("What is the capital of Madagascar?", "Antananarivo", "Nairobi", "Port Louis", "Maputo"),

  /* ==================== GEOGRAPHY — The rest of the U.S. state capitals ==================== */
  G("What is the capital of Alabama?", "Montgomery", "Birmingham", "Mobile", "Huntsville"),
  G("What is the capital of Alaska?", "Juneau", "Anchorage", "Fairbanks", "Nome"),
  G("What is the capital of Arkansas?", "Little Rock", "Fayetteville", "Memphis", "Hot Springs"),
  G("What is the capital of Connecticut?", "Hartford", "New Haven", "Bridgeport", "Stamford"),
  G("What is the capital of Delaware?", "Dover", "Wilmington", "Newark", "Baltimore"),
  G("What is the capital of Idaho?", "Boise", "Twin Falls", "Pocatello", "Spokane"),
  G("What is the capital of Indiana?", "Indianapolis", "Fort Wayne", "Gary", "Bloomington"),
  G("What is the capital of Iowa?", "Des Moines", "Cedar Rapids", "Omaha", "Davenport"),
  G("What is the capital of Kansas?", "Topeka", "Wichita", "Kansas City", "Dodge City"),
  G("What is the capital of Kentucky?", "Frankfort", "Louisville", "Lexington", "Bowling Green"),
  G("What is the capital of Maine?", "Augusta", "Portland", "Bangor", "Bar Harbor"),
  G("What is the capital of Maryland?", "Annapolis", "Baltimore", "Washington", "Frederick"),
  G("What is the capital of Michigan?", "Lansing", "Detroit", "Grand Rapids", "Ann Arbor"),
  G("What is the capital of Minnesota?", "St. Paul", "Minneapolis", "Duluth", "Rochester"),
  G("What is the capital of Mississippi?", "Jackson", "Biloxi", "Natchez", "Gulfport"),
  G("What is the capital of Missouri?", "Jefferson City", "St. Louis", "Kansas City", "Springfield"),
  G("What is the capital of Montana?", "Helena", "Billings", "Missoula", "Bozeman"),
  G("What is the capital of Nebraska?", "Lincoln", "Omaha", "Grand Island", "Sioux City"),
  G("What is the capital of New Hampshire?", "Concord", "Manchester", "Nashua", "Portsmouth"),
  G("What is the capital of New Jersey?", "Trenton", "Newark", "Atlantic City", "Jersey City"),
  G("What is the capital of New Mexico?", "Santa Fe", "Albuquerque", "Las Cruces", "Roswell"),
  G("What is the capital of North Carolina?", "Raleigh", "Charlotte", "Durham", "Asheville"),
  G("What is the capital of North Dakota?", "Bismarck", "Fargo", "Grand Forks", "Minot"),
  G("What is the capital of Ohio?", "Columbus", "Cleveland", "Cincinnati", "Toledo"),
  G("What is the capital of Oklahoma?", "Oklahoma City", "Tulsa", "Norman", "Wichita"),
  G("What is the capital of Oregon?", "Salem", "Portland", "Eugene", "Bend"),
  G("What is the capital of Rhode Island?", "Providence", "Newport", "Warwick", "Hartford"),
  G("What is the capital of South Carolina?", "Columbia", "Charleston", "Myrtle Beach", "Savannah"),
  G("What is the capital of South Dakota?", "Pierre", "Sioux Falls", "Rapid City", "Fargo"),
  G("What is the capital of Utah?", "Salt Lake City", "Provo", "Ogden", "Moab"),
  G("What is the capital of Vermont?", "Montpelier", "Burlington", "Stowe", "Concord"),
  G("What is the capital of Virginia?", "Richmond", "Virginia Beach", "Norfolk", "Alexandria"),
  G("What is the capital of West Virginia?", "Charleston", "Wheeling", "Morgantown", "Huntington"),
  G("What is the capital of Wisconsin?", "Madison", "Milwaukee", "Green Bay", "Kenosha"),
  G("What is the capital of Wyoming?", "Cheyenne", "Jackson", "Casper", "Laramie"),

  /* ==================== GEOGRAPHY — State nicknames ==================== */
  G("Which state is nicknamed the Golden State?", "California", "Colorado", "Florida", "Nevada"),
  G("Which state is nicknamed the Empire State?", "New York", "Texas", "Illinois", "Virginia"),
  G("Which state is nicknamed the Garden State?", "New Jersey", "Oregon", "Vermont", "Georgia"),
  G("Which state is nicknamed the Keystone State?", "Pennsylvania", "Ohio", "Kentucky", "Kansas"),
  G("Which state is nicknamed the Buckeye State?", "Ohio", "Indiana", "Iowa", "Nebraska"),
  G("Which state is nicknamed the Bluegrass State?", "Kentucky", "Tennessee", "Virginia", "Missouri"),
  G("Which state is nicknamed the Peach State?", "Georgia", "South Carolina", "Alabama", "Florida"),
  G("Which state is nicknamed the Sunflower State?", "Kansas", "Nebraska", "Oklahoma", "Iowa"),
  G("Which state is nicknamed the Green Mountain State?", "Vermont", "New Hampshire", "Maine", "Colorado"),
  G("Which state is nicknamed the Granite State?", "New Hampshire", "Vermont", "Rhode Island", "Montana"),
  G("Which state is nicknamed the Ocean State?", "Rhode Island", "Hawaii", "Florida", "Maine"),
  G("Which state is nicknamed the Show-Me State?", "Missouri", "Mississippi", "Michigan", "Montana"),
  G("Which state is nicknamed the Hoosier State?", "Indiana", "Illinois", "Iowa", "Idaho"),
  G("Which state is nicknamed the Badger State?", "Wisconsin", "Michigan", "Minnesota", "Wyoming"),
  G("Which state is nicknamed the Wolverine State?", "Michigan", "Wisconsin", "Montana", "Alaska"),
  G("Which state is nicknamed the Pelican State?", "Louisiana", "Florida", "Mississippi", "Texas"),
  G("Which state is nicknamed the Magnolia State?", "Mississippi", "Alabama", "Georgia", "Louisiana"),
  G("Which state is nicknamed the Volunteer State?", "Tennessee", "Kentucky", "Virginia", "Arkansas"),
  G("Which state is nicknamed the Beehive State?", "Utah", "Nevada", "Arizona", "New Mexico"),
  G("Which state is nicknamed the Silver State?", "Nevada", "Colorado", "Montana", "Arizona"),
  G("Which state is nicknamed the Centennial State?", "Colorado", "Wyoming", "Utah", "Kansas"),
  G("Which state is nicknamed the Evergreen State?", "Washington", "Oregon", "Vermont", "Maine"),
  G("Which state is nicknamed the Beaver State?", "Oregon", "Washington", "Idaho", "Michigan"),
  G("Which state is nicknamed the Last Frontier?", "Alaska", "Montana", "Wyoming", "Hawaii"),
  G("Which state is nicknamed the First State?", "Delaware", "Virginia", "Massachusetts", "Maryland"),

  /* ==================== GEOGRAPHY — More rivers & lakes ==================== */
  G("Which sacred river flows across northern India?", "The Ganges", "The Nile", "The Amazon", "The Volga"),
  G("The Mekong River flows through which part of the world?", "Southeast Asia", "South America", "Africa", "Europe"),
  G("The mighty Congo River is on which continent?", "Africa", "Asia", "South America", "Australia"),
  G("Victoria Falls is on which African river?", "The Zambezi", "The Nile", "The Congo", "The Niger"),
  G("Which great river flows through Germany past castles and vineyards?", "The Rhine", "The Seine", "The Thames", "The Volga"),
  G("What is the longest river in Italy?", "The Po", "The Tiber", "The Arno", "The Rhone"),
  G("Which river flows along the west side of Manhattan?", "The Hudson", "The Mississippi", "The Potomac", "The Charles"),
  G("Which river flows through Washington, D.C.?", "The Potomac", "The Hudson", "The Delaware", "The James"),
  G("Which is China's famous 'Yellow River'?", "The Huang He", "The Yangtze", "The Mekong", "The Ganges"),
  G("What is Australia's longest river?", "The Murray", "The Darling Creek", "The Outback River", "The Sydney"),
  G("Which river carries water from the Great Lakes to the Atlantic?", "The St. Lawrence", "The Mississippi", "The Hudson", "The Colorado"),
  G("The Amazon River empties into which ocean?", "The Atlantic", "The Pacific", "The Indian", "The Arctic"),
  G("The Nile empties into which sea?", "The Mediterranean", "The Red Sea", "The Black Sea", "The Dead Sea"),
  G("The Niagara River connects Lake Erie with which lake?", "Lake Ontario", "Lake Huron", "Lake Michigan", "Lake Superior"),
  G("What is the longest river in France?", "The Loire", "The Seine", "The Rhone", "The Rhine"),
  G("The Danube empties into which sea?", "The Black Sea", "The Mediterranean", "The Baltic", "The North Sea"),
  G("The Volga empties into which body of water?", "The Caspian Sea", "The Black Sea", "The Baltic Sea", "The Arctic Ocean"),
  G("The Mississippi River begins in which state?", "Minnesota", "Louisiana", "Missouri", "Montana"),
  G("The Colorado River empties toward which gulf?", "The Gulf of California", "The Gulf of Mexico", "Hudson Bay", "The Bay of Bengal"),
  G("The Orinoco River flows mainly through which country?", "Venezuela", "Egypt", "India", "Spain"),
  G("What is the largest lake in Africa?", "Lake Victoria", "Lake Baikal", "Lake Superior", "Loch Ness"),
  G("Lake Titicaca sits high in the mountains between Peru and which country?", "Bolivia", "Chile", "Brazil", "Ecuador"),
  G("Lake Tahoe lies on the border of California and which state?", "Nevada", "Oregon", "Arizona", "Utah"),
  G("Crater Lake, America's deepest lake, is in which state?", "Oregon", "Washington", "Colorado", "Montana"),
  G("Which Great Lake lies entirely inside the United States?", "Lake Michigan", "Lake Superior", "Lake Erie", "Lake Ontario"),
  G("Lake Mead was created by which dam?", "The Hoover Dam", "The Grand Coulee Dam", "The Aswan Dam", "The Three Gorges Dam"),
  G("Loch Ness, home of the legendary monster, is in which country?", "Scotland", "Ireland", "Wales", "Norway"),
  G("The United States shares the Great Lakes with which country?", "Canada", "Mexico", "Greenland", "Russia"),
  G("Which is the largest of the Great Lakes?", "Lake Superior", "Lake Michigan", "Lake Erie", "Lake Ontario"),
  G("Angel Falls, the world's tallest waterfall, is in which country?", "Venezuela", "Brazil", "Canada", "Zimbabwe"),

  /* ==================== GEOGRAPHY — More mountains & volcanoes ==================== */
  G("What is the tallest mountain in South America?", "Aconcagua", "Mount Everest", "Denali", "Mont Blanc"),
  G("What is the tallest peak in the Alps?", "Mont Blanc", "The Matterhorn", "Mount Etna", "Ben Nevis"),
  G("What is the second-tallest mountain in the world?", "K2", "Kilimanjaro", "Denali", "Mont Blanc"),
  G("Which mountains form the border between Europe and Asia?", "The Urals", "The Alps", "The Andes", "The Rockies"),
  G("The Pyrenees mountains separate France from which country?", "Spain", "Italy", "Germany", "Switzerland"),
  G("Table Mountain overlooks which South African city?", "Cape Town", "Johannesburg", "Cairo", "Nairobi"),
  G("Mount Vesuvius looms over which Italian city?", "Naples", "Rome", "Venice", "Milan"),
  G("Mount Etna is a volcano on which island?", "Sicily", "Sardinia", "Crete", "Corsica"),
  G("The Kilauea volcano is in which U.S. state?", "Hawaii", "Alaska", "Washington", "California"),
  G("Pikes Peak is a famous mountain in which state?", "Colorado", "Utah", "Wyoming", "Montana"),
  G("Ben Nevis, the tallest mountain in Britain, is in which country?", "Scotland", "England", "Wales", "Ireland"),
  G("What is the tallest mountain in Europe?", "Mount Elbrus", "Mont Blanc", "The Matterhorn", "Mount Olympus"),
  G("What is the tallest mountain in the lower 48 states?", "Mount Whitney", "Denali", "Pikes Peak", "Mount Rainier"),
  G("Japan's Mount Fuji is what kind of mountain?", "A volcano", "A granite dome", "A sand dune", "A coral peak"),
  G("Which volcano erupted dramatically in Washington State in 1980?", "Mount St. Helens", "Mount Rainier", "Kilauea", "Mount Shasta"),
  G("Mount Kilimanjaro rises in which country?", "Tanzania", "Kenya", "Egypt", "South Africa"),
  G("What is the highest mountain in Greece?", "Mount Olympus", "Mount Etna", "Mont Blanc", "Mount Athos"),
  G("Mount Everest sits on the border of Nepal and which country?", "China", "India", "Pakistan", "Russia"),

  /* ==================== GEOGRAPHY — Islands ==================== */
  G("What is the largest island in the world?", "Greenland", "Australia", "Madagascar", "Iceland"),
  G("Madagascar lies off the coast of which continent?", "Africa", "Asia", "South America", "Australia"),
  G("Which island does the 'boot' of Italy appear to kick?", "Sicily", "Sardinia", "Corsica", "Malta"),
  G("What is the largest island in the Caribbean?", "Cuba", "Jamaica", "Puerto Rico", "Barbados"),
  G("What is the largest island of Japan?", "Honshu", "Hokkaido", "Okinawa", "Kyushu"),
  G("Tasmania is an island state of which country?", "Australia", "New Zealand", "England", "Canada"),
  G("Napoleon was born on which island?", "Corsica", "Elba", "Sicily", "Malta"),
  G("Sardinia is a large island belonging to which country?", "Italy", "Spain", "France", "Greece"),
  G("What is the largest Greek island?", "Crete", "Rhodes", "Santorini", "Corfu"),
  G("The island of Bali is part of which country?", "Indonesia", "Thailand", "The Philippines", "India"),
  G("Puerto Rico is a territory of which country?", "The United States", "Spain", "Mexico", "Cuba"),
  G("Which Atlantic island gives its name to a mysterious 'triangle'?", "Bermuda", "Iceland", "Madeira", "Malta"),
  G("The Galápagos Islands belong to which country?", "Ecuador", "Peru", "Chile", "Mexico"),
  G("Easter Island, famous for its giant stone heads, belongs to which country?", "Chile", "Peru", "Mexico", "Australia"),
  G("Manhattan is an island in which city?", "New York City", "Boston", "Chicago", "Miami"),
  G("Which country is nicknamed the Land of Fire and Ice?", "Iceland", "Norway", "Greenland", "Finland"),
  G("Which teardrop-shaped island country lies just south of India?", "Sri Lanka", "Madagascar", "The Maldives", "Bali"),
  G("Greenland belongs to which country?", "Denmark", "Canada", "Norway", "Iceland"),

  /* ==================== GEOGRAPHY — Seas & straits ==================== */
  G("The Strait of Gibraltar separates Europe from which continent?", "Africa", "Asia", "South America", "Australia"),
  G("The Bering Strait separates Alaska from which country?", "Russia", "Canada", "Japan", "China"),
  G("The English Channel separates England from which country?", "France", "Ireland", "Spain", "Norway"),
  G("The Red Sea lies between Africa and which peninsula?", "The Arabian Peninsula", "Italy", "Florida", "Scandinavia"),
  G("The Baltic Sea is in which part of Europe?", "The north", "The south", "The west", "The east... of Asia"),
  G("The Black Sea lies north of which country?", "Turkey", "Egypt", "Spain", "India"),
  G("The Adriatic Sea lies along the east coast of which country?", "Italy", "Spain", "France", "Portugal"),
  G("The Aegean Sea lies between Greece and which country?", "Turkey", "Italy", "Egypt", "Spain"),
  G("Cuba, Jamaica, and the Bahamas are islands in which sea?", "The Caribbean Sea", "The Mediterranean Sea", "The Baltic Sea", "The Coral Sea"),
  G("Which gulf lies along the southern coast of the United States?", "The Gulf of Mexico", "The Persian Gulf", "The Gulf of Alaska", "The Bay of Biscay"),
  G("The huge Hudson Bay is in which country?", "Canada", "The United States", "Russia", "Greenland"),
  G("The oil-rich Persian Gulf is in which region?", "The Middle East", "South America", "Southeast Asia", "North Africa"),

  /* ==================== GEOGRAPHY — Cities & famous places ==================== */
  G("Which city is called the City of Light?", "Paris", "London", "Venice", "Vienna"),
  G("Which city is called the Eternal City?", "Rome", "Athens", "Jerusalem", "Cairo"),
  G("Which American city is nicknamed the Motor City?", "Detroit", "Chicago", "Cleveland", "Pittsburgh"),
  G("Which American city is nicknamed Music City?", "Nashville", "Memphis", "New Orleans", "Austin"),
  G("Which city is called the City of Brotherly Love?", "Philadelphia", "Boston", "Washington, D.C.", "Baltimore"),
  G("Which American city is nicknamed the Emerald City?", "Seattle", "Portland", "Denver", "San Francisco"),
  G("Which city is nicknamed the Mile High City?", "Denver", "Salt Lake City", "Phoenix", "Albuquerque"),
  G("Which city is nicknamed Sin City?", "Las Vegas", "Miami", "Atlantic City", "New Orleans"),
  G("Which city throws the famous Mardi Gras celebration?", "New Orleans", "Miami", "Nashville", "Memphis"),
  G("Hollywood is a neighborhood of which city?", "Los Angeles", "San Francisco", "New York", "Miami"),
  G("Silicon Valley, home of computer companies, is near which city?", "San Francisco", "Seattle", "Boston", "Austin"),
  G("Walt Disney World is in which state?", "Florida", "California", "Texas", "Nevada"),
  G("The original Disneyland is in which state?", "California", "Florida", "New York", "Arizona"),
  G("Times Square glows in the heart of which city?", "New York City", "Las Vegas", "Chicago", "Toronto"),
  G("The Space Needle tower rises over which city?", "Seattle", "Toronto", "San Francisco", "Houston"),
  G("The Gateway Arch stands in which city?", "St. Louis", "Chicago", "Kansas City", "Memphis"),
  G("The old island prison of Alcatraz sits in which bay?", "San Francisco Bay", "New York Harbor", "Boston Harbor", "Chesapeake Bay"),
  G("Buckingham Palace is the royal residence in which city?", "London", "Paris", "Edinburgh", "Dublin"),
  G("The Palace of Versailles is just outside which city?", "Paris", "London", "Vienna", "Brussels"),
  G("The Kremlin fortress is in which city?", "Moscow", "St. Petersburg", "Kyiv", "Warsaw"),
  G("The ancient Acropolis rises above which city?", "Athens", "Rome", "Istanbul", "Cairo"),
  G("The mysterious stone circle of Stonehenge is in which country?", "England", "Scotland", "Ireland", "France"),
  G("The rose-red city of Petra, carved into cliffs, is in which country?", "Jordan", "Egypt", "Greece", "Morocco"),
  G("The great temple of Angkor Wat is in which country?", "Cambodia", "Thailand", "India", "China"),
  G("The giant red rock Uluru rises in which country?", "Australia", "Egypt", "The United States", "South Africa"),
  G("The famous Oktoberfest is held in which German city?", "Munich", "Berlin", "Hamburg", "Frankfurt"),
  G("The running of the bulls takes place in which Spanish city?", "Pamplona", "Madrid", "Barcelona", "Seville"),
  G("Which city hosts the world's most famous Carnival?", "Rio de Janeiro", "Venice", "New Orleans", "Barcelona"),
  G("What is the largest city in Canada?", "Toronto", "Ottawa", "Vancouver", "Montreal"),
  G("What is the largest city in Australia?", "Sydney", "Canberra", "Melbourne", "Perth"),

  /* ==================== GEOGRAPHY — Countries & world facts ==================== */
  G("What is the largest city in Brazil?", "São Paulo", "Rio de Janeiro", "Brasília", "Buenos Aires"),
  G("What is the largest city in the United States?", "New York City", "Los Angeles", "Chicago", "Houston"),
  G("What is the second-largest city in the United States?", "Los Angeles", "Chicago", "Houston", "Philadelphia"),
  G("What is the largest city in Turkey?", "Istanbul", "Ankara", "Izmir", "Antalya"),
  G("Which country is famous for its deep coastal fjords?", "Norway", "Spain", "Egypt", "Brazil"),
  G("Which country is called the Land of a Thousand Lakes?", "Finland", "Sweden", "Canada", "Switzerland"),
  G("Flamenco dancing comes from which country?", "Spain", "Italy", "Mexico", "Portugal"),
  G("Sushi comes from which country?", "Japan", "China", "Thailand", "Korea"),
  G("Tacos and mariachi music come from which country?", "Mexico", "Spain", "Brazil", "Cuba"),
  G("Curry dishes are a famous tradition of which country?", "India", "Japan", "Greece", "Peru"),
  G("Which country is the world's most famous maple syrup maker?", "Canada", "The United States", "Norway", "Russia"),
  G("Which country is famous for fine chocolate and precise watches?", "Switzerland", "Belgium... only watches", "Austria", "Germany"),
  G("The flag called the Union Jack belongs to which country?", "The United Kingdom", "Australia", "The United States", "Canada"),
  G("How many stars are on the American flag?", "50", "48", "52", "13"),
  G("How many stripes are on the American flag?", "13", "50", "10", "15"),
  G("Which country's flag is a single red circle on white?", "Japan", "China", "South Korea", "Turkey"),
  G("What are the colors of the French flag?", "Blue, white, and red", "Green, white, and red", "Red and yellow", "Blue and yellow"),
  G("Which country spans eleven time zones?", "Russia", "The United States", "China", "Canada"),
  G("Which long, thin country runs down South America's Pacific coast?", "Chile", "Argentina", "Peru", "Colombia"),
  G("Much of which European country lies below sea level?", "The Netherlands", "Switzerland", "Spain", "Austria"),
  G("Which South American country is named after the equator?", "Ecuador", "Bolivia", "Colombia", "Paraguay"),
  G("What is another name for the aurora borealis?", "The Northern Lights", "The Midnight Sun", "The Southern Cross", "The Evening Star"),
  G("Antarctica's ice holds most of the world's what?", "Fresh water", "Salt", "Gold", "Oil")
];
