/* Quiz Time! — question bank.
   H(question, correctAnswer, wrong1, wrong2, wrong3) = History
   G(question, correctAnswer, wrong1, wrong2, wrong3) = Geography
   The correct answer is always the second argument; the app
   shuffles the four choices every time a question is shown. */

var H = function (q, a, w1, w2, w3) { return { cat: "history", q: q, a: a, w: [w1, w2, w3] }; };
var G = function (q, a, w1, w2, w3) { return { cat: "geography", q: q, a: a, w: [w1, w2, w3] }; };

var QUESTIONS = [

  /* ==================== HISTORY — Ancient times ==================== */
  H("Which ancient people built the pyramids of Giza?", "The Egyptians", "The Romans", "The Greeks", "The Vikings"),
  H("What is the picture-writing of ancient Egypt called?", "Hieroglyphics", "Calligraphy", "The alphabet", "Braille"),
  H("Who discovered the tomb of King Tutankhamun in 1922?", "Howard Carter", "Charles Darwin", "Marco Polo", "Neil Armstrong"),
  H("Cleopatra was the famous queen of which land?", "Egypt", "Greece", "Rome", "Persia"),
  H("In which country did the ancient Olympic Games begin?", "Greece", "Italy", "Egypt", "France"),
  H("Which ancient city is called the birthplace of democracy?", "Athens", "Rome", "Cairo", "London"),
  H("Which ancient Greek city was famous for its tough warriors?", "Sparta", "Venice", "Paris", "Alexandria"),
  H("In the famous legend, the Greeks used a giant wooden horse to enter which city?", "Troy", "Athens", "Rome", "Carthage"),
  H("Alexander the Great was the king of which ancient kingdom?", "Macedonia", "England", "China", "Egypt"),
  H("What language did the ancient Romans speak?", "Latin", "Greek", "French", "English"),
  H("Julius Caesar was a famous leader of which empire?", "The Roman Empire", "The British Empire", "The Egyptian Empire", "The Chinese Empire"),
  H("On which date was Julius Caesar assassinated?", "The Ides of March (March 15)", "New Year's Day", "The Fourth of July", "Christmas Day"),
  H("What is the name of the huge arena in Rome where gladiators fought?", "The Colosseum", "The Parthenon", "Big Ben", "The Louvre"),
  H("Which volcano buried the Roman city of Pompeii in ash?", "Mount Vesuvius", "Mount Everest", "Mount Fuji", "Mount Rushmore"),
  H("The general Hannibal famously crossed the Alps with which animals?", "Elephants", "Camels", "Horses only", "Lions"),
  H("Who was the first emperor of Rome?", "Augustus", "Napoleon", "Alexander", "Charlemagne"),
  H("The Romans built long channels to carry water to their cities. What are they called?", "Aqueducts", "Pyramids", "Canoes", "Windmills"),
  H("Why was the Great Wall of China built?", "To keep out invaders", "To hold back floods", "As a royal palace", "As a trade market"),
  H("Which ancient wonder of the world is still standing in Egypt today?", "The Great Pyramid of Giza", "The Hanging Gardens", "The Lighthouse of Alexandria", "The Colossus of Rhodes"),
  H("The Parthenon is a famous ancient temple in which city?", "Athens", "Rome", "Cairo", "Istanbul"),
  H("Gladiators fought for crowds in which ancient empire?", "Ancient Rome", "Ancient Egypt", "The Aztec Empire", "The Viking lands"),
  H("Ancient Egyptian life depended on which great river?", "The Nile", "The Amazon", "The Mississippi", "The Thames"),
  H("The Great Sphinx of Egypt has the head of a person and the body of which animal?", "A lion", "A horse", "An eagle", "A crocodile"),
  H("The marathon race is named after a battle in which ancient country?", "Greece", "Italy", "Spain", "China"),
  H("Ancient Egyptians preserved their dead as what?", "Mummies", "Statues", "Paintings", "Fossils"),

  /* ==================== HISTORY — Middle Ages & Renaissance ==================== */
  H("Who won the Battle of Hastings in 1066?", "William the Conqueror", "Julius Caesar", "Napoleon", "King Arthur"),
  H("Which English king was forced to accept the Magna Carta?", "King John", "King Henry VIII", "King George III", "King Richard III"),
  H("In what year was the Magna Carta sealed?", "1215", "1066", "1492", "1776"),
  H("What was the Black Death, which swept Europe in the 1300s?", "A deadly plague", "A great fire", "A long war", "A famous storm"),
  H("The Vikings came from which part of the world?", "Scandinavia", "Africa", "South America", "Australia"),
  H("Which Viking explorer reached North America about 500 years before Columbus?", "Leif Erikson", "Christopher Columbus", "Ferdinand Magellan", "Captain Cook"),
  H("Joan of Arc was a young heroine of which country?", "France", "England", "Spain", "Italy"),
  H("Genghis Khan built a huge empire leading which people?", "The Mongols", "The Romans", "The Vikings", "The Aztecs"),
  H("The explorer Marco Polo made his famous journey to which land?", "China", "America", "Australia", "Egypt"),
  H("The Crusades were fought over which holy city?", "Jerusalem", "Paris", "Rome", "Athens"),
  H("Knights of the Middle Ages followed a code of honor called what?", "Chivalry", "Democracy", "Alchemy", "Diplomacy"),
  H("What is the water-filled ditch around a castle called?", "A moat", "A well", "A dam", "A trench"),
  H("Who invented the printing press around 1440?", "Johannes Gutenberg", "Thomas Edison", "Benjamin Franklin", "Alexander Graham Bell"),
  H("Who painted the Mona Lisa?", "Leonardo da Vinci", "Michelangelo", "Pablo Picasso", "Vincent van Gogh"),
  H("Who painted the ceiling of the Sistine Chapel?", "Michelangelo", "Leonardo da Vinci", "Rembrandt", "Monet"),
  H("The Renaissance, a great rebirth of art and learning, began in which country?", "Italy", "England", "Russia", "Egypt"),
  H("In what year did Christopher Columbus first sail across the Atlantic?", "1492", "1776", "1215", "1620"),
  H("Christopher Columbus sailed under the flag of which country?", "Spain", "England", "France", "Portugal"),
  H("Which of these was one of Columbus's three ships?", "The Santa María", "The Mayflower", "The Titanic", "The Queen Mary"),
  H("Whose expedition was the first to sail all the way around the world?", "Ferdinand Magellan's", "Christopher Columbus's", "Marco Polo's", "Captain Ahab's"),
  H("The Aztec Empire was located in which modern-day country?", "Mexico", "Egypt", "Spain", "India"),
  H("The Inca Empire built its famous mountain cities on which continent?", "South America", "Africa", "Europe", "Australia"),
  H("Machu Picchu was built by which ancient people?", "The Incas", "The Romans", "The Egyptians", "The Vikings"),
  H("Who wrote the play 'Romeo and Juliet'?", "William Shakespeare", "Charles Dickens", "Mark Twain", "Jane Austen"),
  H("What was the name of Shakespeare's famous theatre in London?", "The Globe", "The Palladium", "The Coliseum", "The Apollo"),

  /* ==================== HISTORY — Early modern times ==================== */
  H("King Henry VIII of England is famous for having how many wives?", "Six", "Two", "Ten", "One"),
  H("Henry VIII was the king of which country?", "England", "France", "Spain", "Germany"),
  H("Elizabeth I was a famous queen of which country?", "England", "Russia", "Sweden", "Portugal"),
  H("Which country defeated the Spanish Armada in 1588?", "England", "France", "Italy", "Greece"),
  H("What was the name of the ship that carried the Pilgrims to America in 1620?", "The Mayflower", "The Santa María", "The Titanic", "The Endeavour"),
  H("Where did the Pilgrims land in 1620?", "Plymouth, Massachusetts", "New York City", "Miami, Florida", "San Francisco"),
  H("The Pilgrims shared the first Thanksgiving feast with whom?", "Native Americans", "French explorers", "Spanish sailors", "Roman soldiers"),
  H("Isaac Newton is famous for explaining which force, after seeing an apple fall?", "Gravity", "Electricity", "Magnetism", "Steam power"),
  H("In what year did the French Revolution begin?", "1789", "1492", "1914", "1620"),
  H("Which famous prison did the people of Paris storm in 1789?", "The Bastille", "Alcatraz", "The Tower of London", "Sing Sing"),
  H("Which French queen is often (wrongly) said to have declared 'Let them eat cake'?", "Marie Antoinette", "Queen Victoria", "Cleopatra", "Queen Elizabeth I"),
  H("At which battle was Napoleon finally defeated in 1815?", "Waterloo", "Gettysburg", "Hastings", "Normandy"),
  H("Napoleon Bonaparte crowned himself emperor of which country?", "France", "England", "Russia", "Austria"),
  H("In what year was the American Declaration of Independence signed?", "1776", "1620", "1865", "1901"),
  H("Who was the main author of the Declaration of Independence?", "Thomas Jefferson", "George Washington", "Abraham Lincoln", "Benjamin Franklin"),
  H("Who was the first president of the United States?", "George Washington", "Abraham Lincoln", "Thomas Jefferson", "John Adams"),
  H("The Boston Tea Party was a protest against what?", "British taxes", "The price of coffee", "A new railroad", "The king's birthday"),
  H("What did the colonists throw into the harbor at the Boston Tea Party?", "Tea", "Coffee", "Gold", "Cotton"),
  H("In which city was the United States Constitution written?", "Philadelphia", "Washington, D.C.", "Boston", "New York"),
  H("Paul Revere took a famous midnight ride to warn that who was coming?", "The British", "The pirates", "The French", "The Spanish"),
  H("The American Revolution was fought between America and which country?", "Great Britain", "France", "Spain", "Mexico"),
  H("Benjamin Franklin famously flew what in a lightning storm?", "A kite", "A flag", "A hot-air balloon", "A model airplane"),
  H("In 1803 the United States bought the huge Louisiana Territory from which country?", "France", "Spain", "England", "Russia"),
  H("Which two explorers led the famous expedition to America's West in 1804?", "Lewis and Clark", "Stanley and Livingstone", "Wright and Wright", "Watson and Crick"),
  H("Sacagawea was the Native American woman who helped guide which expedition?", "Lewis and Clark", "Columbus", "The Mayflower", "Magellan"),

  /* ==================== HISTORY — The 1800s ==================== */
  H("In which years was the American Civil War fought?", "1861 to 1865", "1776 to 1781", "1914 to 1918", "1939 to 1945"),
  H("In the Civil War, what was the Northern side called?", "The Union", "The Confederacy", "The Alliance", "The Colonies"),
  H("Who was president of the United States during the Civil War?", "Abraham Lincoln", "George Washington", "Theodore Roosevelt", "Ulysses S. Grant"),
  H("What is the name of Abraham Lincoln's most famous short speech?", "The Gettysburg Address", "The New Deal", "The I Have a Dream speech", "The Farewell Address"),
  H("Who assassinated Abraham Lincoln?", "John Wilkes Booth", "Lee Harvey Oswald", "Benedict Arnold", "Jesse James"),
  H("Where was Abraham Lincoln when he was shot?", "Ford's Theatre", "The White House", "A train station", "Gettysburg"),
  H("Lincoln's Emancipation Proclamation was a step toward ending what?", "Slavery", "Taxes", "The gold rush", "The railroads"),
  H("Which brave woman guided many enslaved people to freedom on the Underground Railroad?", "Harriet Tubman", "Betsy Ross", "Amelia Earhart", "Florence Nightingale"),
  H("Who wrote the anti-slavery novel 'Uncle Tom's Cabin'?", "Harriet Beecher Stowe", "Mark Twain", "Jane Austen", "Louisa May Alcott"),
  H("What great project, finished in 1869, connected America's east and west coasts?", "The Transcontinental Railroad", "The Panama Canal", "The Interstate Highway", "The Brooklyn Bridge"),
  H("Who invented the telephone?", "Alexander Graham Bell", "Thomas Edison", "Henry Ford", "Samuel Morse"),
  H("Who invented the first practical electric light bulb?", "Thomas Edison", "Alexander Graham Bell", "Isaac Newton", "Albert Einstein"),
  H("Which queen ruled Britain for most of the 1800s?", "Queen Victoria", "Queen Elizabeth II", "Queen Anne", "Queen Mary"),
  H("In what year did the California Gold Rush begin in earnest?", "1849", "1776", "1929", "1901"),
  H("The 'forty-niners' rushed to California in search of what?", "Gold", "Oil", "Diamonds", "Silver"),
  H("Charles Darwin is famous for his theory of what?", "Evolution", "Gravity", "Relativity", "Electricity"),
  H("Florence Nightingale is remembered as the founder of modern what?", "Nursing", "Banking", "Photography", "Teaching"),
  H("Samuel Morse invented a famous code made of what?", "Dots and dashes", "Colors and shapes", "Numbers only", "Musical notes"),
  H("The first women's rights convention in America was held in 1848 in which town?", "Seneca Falls, New York", "Dallas, Texas", "Miami, Florida", "Denver, Colorado"),
  H("Pioneer families traveled the Oregon Trail in what?", "Covered wagons", "Steamboats", "Trains", "Cars"),
  H("The Pony Express used riders on horseback to deliver what?", "Mail", "Milk", "Newspapers only", "Gold bars"),
  H("In 1867 the United States bought Alaska from which country?", "Russia", "Canada", "France", "Spain"),
  H("General Custer made his famous 'last stand' at which battle?", "Little Bighorn", "Gettysburg", "Bunker Hill", "Waterloo"),
  H("The Homestead Act offered settlers what if they farmed it?", "Free land", "Free horses", "Free gold", "Free houses in the city"),
  H("Which amendment to the U.S. Constitution ended slavery?", "The 13th Amendment", "The 1st Amendment", "The 19th Amendment", "The 21st Amendment"),

  /* ==================== HISTORY — The 1900s ==================== */
  H("In what year did the Wright brothers make the first airplane flight?", "1903", "1929", "1876", "1945"),
  H("Where did the Wright brothers make their first flight?", "Kitty Hawk, North Carolina", "New York City", "Los Angeles, California", "Miami, Florida"),
  H("In what year did the Titanic sink?", "1912", "1905", "1923", "1898"),
  H("What did the Titanic hit before it sank?", "An iceberg", "A whale", "Another ship", "A reef"),
  H("In what year did World War I begin?", "1914", "1939", "1918", "1900"),
  H("World War I was sparked by the assassination of which man?", "Archduke Franz Ferdinand", "Abraham Lincoln", "Julius Caesar", "Napoleon"),
  H("In what year did World War I end?", "1918", "1914", "1945", "1920"),
  H("Which war is famous for soldiers fighting from muddy trenches?", "World War I", "The Civil War", "The Revolutionary War", "The Cold War"),
  H("Which amendment gave American women the right to vote?", "The 19th Amendment", "The 13th Amendment", "The 5th Amendment", "The 2nd Amendment"),
  H("In what year did American women win the right to vote?", "1920", "1865", "1776", "1950"),
  H("What style of music gave the Roaring Twenties its soundtrack?", "Jazz", "Rock and roll", "Opera", "Disco"),
  H("During Prohibition, what was banned in the United States?", "Alcohol", "Coffee", "Dancing", "Automobiles"),
  H("In what year did the great stock market crash happen?", "1929", "1919", "1941", "1955"),
  H("What is the hard period after the 1929 crash called?", "The Great Depression", "The Cold War", "The Gold Rush", "The Renaissance"),
  H("Which president created the 'New Deal' to fight the Great Depression?", "Franklin D. Roosevelt", "Abraham Lincoln", "Richard Nixon", "George Washington"),
  H("Amelia Earhart was the first woman to do what?", "Fly solo across the Atlantic", "Climb Mount Everest", "Swim the English Channel", "Walk on the moon"),
  H("Who discovered penicillin, the first great antibiotic?", "Alexander Fleming", "Thomas Edison", "Marie Antoinette", "Henry Ford"),
  H("In what year did World War II begin in Europe?", "1939", "1914", "1945", "1929"),
  H("Who was the dictator of Germany during World War II?", "Adolf Hitler", "Joseph Stalin", "Napoleon", "Kaiser Wilhelm"),
  H("On what date was Pearl Harbor attacked?", "December 7, 1941", "July 4, 1776", "June 6, 1944", "November 11, 1918"),
  H("Pearl Harbor is located in which U.S. state?", "Hawaii", "California", "Florida", "Alaska"),
  H("The D-Day invasion of 1944 landed on the beaches of which region?", "Normandy, France", "Sicily, Italy", "The coast of Spain", "The coast of England"),
  H("On what date did the D-Day landings take place?", "June 6, 1944", "December 7, 1941", "July 4, 1776", "May 8, 1950"),
  H("Who was Britain's famous prime minister during World War II?", "Winston Churchill", "Margaret Thatcher", "Tony Blair", "King George"),
  H("In what year did World War II end?", "1945", "1939", "1918", "1950"),
  H("The first atomic bomb used in war was dropped on which city?", "Hiroshima", "Tokyo", "Berlin", "London"),
  H("The Holocaust was the murder of six million people, mostly from which group?", "Jewish people", "Roman soldiers", "French farmers", "British sailors"),
  H("Anne Frank is remembered around the world for what?", "Her diary", "Her paintings", "Her flying records", "Her nursing"),
  H("The wartime poster figure 'Rosie the Riveter' stood for what?", "Women working in factories", "Farmers growing corn", "Soldiers overseas", "Nurses in hospitals"),
  H("The Cold War was a long rivalry between the United States and which country?", "The Soviet Union", "Germany", "Japan", "Mexico"),
  H("What was the name of the first satellite launched into space in 1957?", "Sputnik", "Apollo", "Voyager", "Hubble"),
  H("Who was the first human being to travel into space?", "Yuri Gagarin", "Neil Armstrong", "John Glenn", "Buzz Aldrin"),
  H("Who was the first American in space?", "Alan Shepard", "Neil Armstrong", "Charles Lindbergh", "Howard Hughes"),
  H("Who was the first person to walk on the moon?", "Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"),
  H("In what year did astronauts first land on the moon?", "1969", "1959", "1979", "1949"),
  H("Neil Armstrong's first words on the moon began 'That's one small step for...'", "man", "science", "America", "the future"),
  H("In which city was President John F. Kennedy assassinated?", "Dallas", "Washington, D.C.", "New York", "Chicago"),
  H("What is the name of Martin Luther King Jr.'s most famous speech?", "I Have a Dream", "The Gettysburg Address", "Give Me Liberty", "The New Frontier"),
  H("Rosa Parks became famous for refusing to do what?", "Give up her bus seat", "Pay a tax", "Leave a restaurant", "Sign a paper"),
  H("The Montgomery Bus Boycott took place in which state?", "Alabama", "New York", "California", "Texas"),
  H("The Berlin Wall divided which city into east and west?", "Berlin", "Paris", "London", "Moscow"),
  H("In what year did the Berlin Wall come down?", "1989", "1969", "1999", "1979"),
  H("Which president led America through the Cuban Missile Crisis of 1962?", "John F. Kennedy", "Richard Nixon", "Franklin D. Roosevelt", "Jimmy Carter"),
  H("The Watergate scandal led to the resignation of which president?", "Richard Nixon", "John F. Kennedy", "Ronald Reagan", "Harry Truman"),
  H("Who was Britain's first female prime minister?", "Margaret Thatcher", "Queen Victoria", "Florence Nightingale", "Jane Austen"),
  H("Mahatma Gandhi led which country to independence using peaceful protest?", "India", "China", "Egypt", "Brazil"),
  H("Nelson Mandela became the first Black president of which country?", "South Africa", "Kenya", "Egypt", "Brazil"),
  H("Who developed the first successful polio vaccine?", "Jonas Salk", "Alexander Fleming", "Louis Pasteur", "Marie Curie"),
  H("Albert Einstein is most famous for his theory of what?", "Relativity", "Gravity", "Evolution", "Electricity"),
  H("Who invented the World Wide Web in 1989?", "Tim Berners-Lee", "Thomas Edison", "Bill Nye", "Alexander Graham Bell"),

  /* ==================== GEOGRAPHY — World capitals ==================== */
  G("What is the capital of France?", "Paris", "London", "Rome", "Madrid"),
  G("What is the capital of Italy?", "Rome", "Venice", "Milan", "Florence"),
  G("What is the capital of Spain?", "Madrid", "Barcelona", "Seville", "Lisbon"),
  G("What is the capital of Japan?", "Tokyo", "Kyoto", "Osaka", "Beijing"),
  G("What is the capital of Egypt?", "Cairo", "Alexandria", "Athens", "Casablanca"),
  G("What is the capital of Canada?", "Ottawa", "Toronto", "Vancouver", "Montreal"),
  G("What is the capital of Australia?", "Canberra", "Sydney", "Melbourne", "Brisbane"),
  G("What is the capital of Germany?", "Berlin", "Munich", "Hamburg", "Frankfurt"),
  G("What is the capital of Russia?", "Moscow", "St. Petersburg", "Kyiv", "Warsaw"),
  G("What is the capital of China?", "Beijing", "Shanghai", "Hong Kong", "Tokyo"),
  G("What is the capital of the United Kingdom?", "London", "Manchester", "Liverpool", "Dublin"),
  G("What is the capital of Greece?", "Athens", "Sparta", "Rome", "Istanbul"),
  G("What is the capital of Portugal?", "Lisbon", "Madrid", "Porto", "Barcelona"),
  G("What is the capital of Austria?", "Vienna", "Salzburg", "Berlin", "Zurich"),
  G("What is the capital of the Netherlands?", "Amsterdam", "Brussels", "Rotterdam", "Copenhagen"),
  G("What is the capital of Norway?", "Oslo", "Stockholm", "Copenhagen", "Helsinki"),
  G("What is the capital of Sweden?", "Stockholm", "Oslo", "Helsinki", "Gothenburg"),
  G("What is the capital of Denmark?", "Copenhagen", "Oslo", "Amsterdam", "Stockholm"),
  G("What is the capital of Finland?", "Helsinki", "Stockholm", "Oslo", "Reykjavik"),
  G("What is the capital of Poland?", "Warsaw", "Krakow", "Prague", "Budapest"),
  G("What is the capital of Hungary?", "Budapest", "Vienna", "Prague", "Bucharest"),
  G("What is the capital of the Czech Republic?", "Prague", "Vienna", "Warsaw", "Budapest"),
  G("What is the capital of Ireland?", "Dublin", "Belfast", "Cork", "Edinburgh"),
  G("What is the capital of Switzerland?", "Bern", "Zurich", "Geneva", "Basel"),
  G("What is the capital of Belgium?", "Brussels", "Amsterdam", "Antwerp", "Paris"),
  G("What is the capital of Turkey?", "Ankara", "Istanbul", "Athens", "Cairo"),
  G("What is the capital of India?", "New Delhi", "Mumbai", "Kolkata", "Bangalore"),
  G("What is the capital of Brazil?", "Brasília", "Rio de Janeiro", "São Paulo", "Buenos Aires"),
  G("What is the capital of Argentina?", "Buenos Aires", "Santiago", "Lima", "Rio de Janeiro"),
  G("What is the capital of Mexico?", "Mexico City", "Cancún", "Guadalajara", "Acapulco"),
  G("What is the capital of the United States?", "Washington, D.C.", "New York City", "Los Angeles", "Chicago"),
  G("What is the capital of Cuba?", "Havana", "Miami", "San Juan", "Kingston"),
  G("What is the capital of Peru?", "Lima", "Santiago", "Bogotá", "Quito"),
  G("What is the capital of Chile?", "Santiago", "Lima", "Buenos Aires", "La Paz"),
  G("What is the capital of Kenya?", "Nairobi", "Cairo", "Lagos", "Cape Town"),
  G("What is the capital of South Korea?", "Seoul", "Busan", "Tokyo", "Beijing"),
  G("What is the capital of Thailand?", "Bangkok", "Hanoi", "Singapore", "Manila"),
  G("What is the capital of Vietnam?", "Hanoi", "Ho Chi Minh City", "Bangkok", "Seoul"),
  G("What is the capital of Iceland?", "Reykjavik", "Oslo", "Helsinki", "Copenhagen"),
  G("What is the capital of New Zealand?", "Wellington", "Auckland", "Sydney", "Christchurch"),
  G("What is the capital of Scotland?", "Edinburgh", "Glasgow", "London", "Dublin"),
  G("What is the capital of Morocco?", "Rabat", "Casablanca", "Marrakesh", "Cairo"),
  G("What is the capital of Saudi Arabia?", "Riyadh", "Dubai", "Mecca", "Cairo"),
  G("What is the capital of Ukraine?", "Kyiv", "Moscow", "Warsaw", "Minsk"),
  G("What is the capital of Romania?", "Bucharest", "Budapest", "Sofia", "Belgrade"),

  /* ==================== GEOGRAPHY — U.S. state capitals ==================== */
  G("What is the capital of California?", "Sacramento", "Los Angeles", "San Francisco", "San Diego"),
  G("What is the capital of Texas?", "Austin", "Houston", "Dallas", "San Antonio"),
  G("What is the capital of New York State?", "Albany", "New York City", "Buffalo", "Rochester"),
  G("What is the capital of Florida?", "Tallahassee", "Miami", "Orlando", "Tampa"),
  G("What is the capital of Illinois?", "Springfield", "Chicago", "Peoria", "Rockford"),
  G("What is the capital of Arizona?", "Phoenix", "Tucson", "Flagstaff", "Las Vegas"),
  G("What is the capital of Hawaii?", "Honolulu", "Maui", "Hilo", "Kona"),
  G("What is the capital of Colorado?", "Denver", "Boulder", "Colorado Springs", "Aspen"),
  G("What is the capital of Massachusetts?", "Boston", "Cambridge", "Springfield", "Salem"),
  G("What is the capital of Georgia?", "Atlanta", "Savannah", "Augusta", "Athens"),
  G("What is the capital of Tennessee?", "Nashville", "Memphis", "Knoxville", "Chattanooga"),
  G("What is the capital of Washington State?", "Olympia", "Seattle", "Spokane", "Tacoma"),
  G("What is the capital of Nevada?", "Carson City", "Las Vegas", "Reno", "Henderson"),
  G("What is the capital of Louisiana?", "Baton Rouge", "New Orleans", "Shreveport", "Lafayette"),
  G("What is the capital of Pennsylvania?", "Harrisburg", "Philadelphia", "Pittsburgh", "Allentown"),

  /* ==================== GEOGRAPHY — Rivers ==================== */
  G("Which river is usually called the longest in the world?", "The Nile", "The Mississippi", "The Thames", "The Danube"),
  G("Which river flows through the heart of Paris?", "The Seine", "The Thames", "The Nile", "The Rhine"),
  G("Which river flows through London?", "The Thames", "The Seine", "The Danube", "The Volga"),
  G("Which mighty river flows past New Orleans into the Gulf of Mexico?", "The Mississippi", "The Colorado", "The Hudson", "The Amazon"),
  G("Which great river flows through Egypt?", "The Nile", "The Amazon", "The Congo", "The Tigris"),
  G("Which river flows through the city of Rome?", "The Tiber", "The Seine", "The Po", "The Danube"),
  G("What is the longest river in Europe?", "The Volga", "The Thames", "The Seine", "The Rhine"),
  G("What is the longest river in Asia?", "The Yangtze", "The Nile", "The Mississippi", "The Amazon"),
  G("Which river carved the Grand Canyon?", "The Colorado River", "The Mississippi River", "The Missouri River", "The Rio Grande"),
  G("The Amazon River flows through which continent?", "South America", "Africa", "Asia", "Australia"),
  G("Which river flows through both Vienna and Budapest?", "The Danube", "The Rhine", "The Seine", "The Volga"),
  G("Which river forms much of the border between the United States and Mexico?", "The Rio Grande", "The Mississippi", "The Colorado", "The Hudson"),

  /* ==================== GEOGRAPHY — Mountains ==================== */
  G("What is the tallest mountain in the world?", "Mount Everest", "Mount Kilimanjaro", "Mont Blanc", "Mount Fuji"),
  G("Mount Everest is part of which mountain range?", "The Himalayas", "The Alps", "The Rockies", "The Andes"),
  G("What is the tallest mountain in Africa?", "Mount Kilimanjaro", "Mount Everest", "Mont Blanc", "Mount Fuji"),
  G("What is the tallest mountain in North America?", "Denali", "Mount Everest", "Pikes Peak", "Mount Fuji"),
  G("Which famous mountain range runs through Switzerland?", "The Alps", "The Andes", "The Rockies", "The Himalayas"),
  G("Which mountain range runs down the west side of South America?", "The Andes", "The Alps", "The Rockies", "The Urals"),
  G("Which mountain range stretches through the western United States and Canada?", "The Rocky Mountains", "The Appalachians", "The Alps", "The Andes"),
  G("Mount Fuji is the famous snow-capped mountain of which country?", "Japan", "China", "Switzerland", "Chile"),
  G("The famous Matterhorn peak is part of which mountain range?", "The Alps", "The Himalayas", "The Rockies", "The Andes"),
  G("Which older, gentler mountain range runs along the eastern United States?", "The Appalachians", "The Rockies", "The Sierra Nevada", "The Alps"),

  /* ==================== GEOGRAPHY — Oceans, seas & lakes ==================== */
  G("What is the largest ocean in the world?", "The Pacific Ocean", "The Atlantic Ocean", "The Indian Ocean", "The Arctic Ocean"),
  G("What is the second-largest ocean?", "The Atlantic Ocean", "The Pacific Ocean", "The Arctic Ocean", "The Indian Ocean"),
  G("What is the smallest, coldest ocean?", "The Arctic Ocean", "The Pacific Ocean", "The Atlantic Ocean", "The Indian Ocean"),
  G("Which ocean lies between Africa and Australia?", "The Indian Ocean", "The Atlantic Ocean", "The Arctic Ocean", "The Pacific Ocean"),
  G("Which sea lies between Europe and Africa?", "The Mediterranean Sea", "The Caribbean Sea", "The Red Sea", "The North Sea"),
  G("Which sea is so salty that people float easily on it?", "The Dead Sea", "The Mediterranean Sea", "The Baltic Sea", "The Caribbean Sea"),
  G("What is the largest lake in the world?", "The Caspian Sea", "Lake Superior", "Lake Michigan", "Lake Tahoe"),
  G("What is the deepest lake in the world?", "Lake Baikal", "Lake Erie", "Lake Superior", "Loch Ness"),
  G("How many Great Lakes are there in North America?", "Five", "Three", "Seven", "Ten"),
  G("Which of these is NOT one of the Great Lakes?", "Lake Tahoe", "Lake Superior", "Lake Erie", "Lake Michigan"),
  G("What is the deepest place in all the oceans?", "The Mariana Trench", "The Grand Canyon", "The Dead Sea", "The Bermuda Triangle"),

  /* ==================== GEOGRAPHY — Deserts ==================== */
  G("What is the largest hot desert in the world?", "The Sahara", "The Gobi", "The Mojave", "The Atacama"),
  G("The Sahara Desert is on which continent?", "Africa", "Asia", "Australia", "South America"),
  G("The Gobi Desert is on which continent?", "Asia", "Africa", "North America", "Europe"),
  G("The Atacama, the driest desert on Earth, is in which country?", "Chile", "Egypt", "Australia", "Mexico"),
  G("Which desert covers much of the southwestern United States near Las Vegas?", "The Mojave", "The Sahara", "The Gobi", "The Kalahari"),

  /* ==================== GEOGRAPHY — Continents & countries ==================== */
  G("How many continents are there?", "Seven", "Five", "Six", "Nine"),
  G("What is the largest continent?", "Asia", "Africa", "Europe", "North America"),
  G("What is the smallest continent?", "Australia", "Europe", "Antarctica", "South America"),
  G("Which continent is the coldest?", "Antarctica", "Europe", "Asia", "North America"),
  G("What is the largest country in the world by area?", "Russia", "China", "The United States", "Australia"),
  G("What is the second-largest country in the world by area?", "Canada", "Brazil", "India", "Mexico"),
  G("Which country has the most people in the world today?", "India", "The United States", "Russia", "Brazil"),
  G("What is the smallest country in the world?", "Vatican City", "Monaco", "Luxembourg", "Iceland"),
  G("Which country is shaped like a boot?", "Italy", "France", "Spain", "Greece"),
  G("What is the largest country in South America?", "Brazil", "Argentina", "Peru", "Chile"),
  G("Kangaroos and koalas are found in the wild in which country?", "Australia", "Brazil", "South Africa", "India"),
  G("Which country is known as the Land of the Rising Sun?", "Japan", "China", "Egypt", "Spain"),
  G("Which country is famous for tulips and windmills?", "The Netherlands", "France", "Italy", "Greece"),
  G("The pyramids of Giza are in which country?", "Egypt", "Mexico", "Greece", "Peru"),
  G("Which country has a red maple leaf on its flag?", "Canada", "The United States", "Japan", "Switzerland"),
  G("Which country sits partly in Europe and partly in Asia?", "Turkey", "France", "Spain", "Egypt"),
  G("The Great Barrier Reef lies off the coast of which country?", "Australia", "Brazil", "Mexico", "India"),
  G("The Amazon rainforest is mostly in which country?", "Brazil", "Mexico", "Egypt", "Spain"),
  G("Which Italian city is famous for its canals and gondolas?", "Venice", "Rome", "Milan", "Naples"),
  G("Which continent has no permanent human residents?", "Antarctica", "Australia", "South America", "Africa"),
  G("On which continent do penguins live in the wild?", "Antarctica", "The Arctic", "Europe", "North America"),

  /* ==================== GEOGRAPHY — Famous landmarks ==================== */
  G("The Eiffel Tower stands in which city?", "Paris", "London", "Rome", "New York"),
  G("The Statue of Liberty stands in the harbor of which city?", "New York City", "Boston", "Washington, D.C.", "Philadelphia"),
  G("The Statue of Liberty was a gift to America from which country?", "France", "England", "Italy", "Spain"),
  G("The Golden Gate Bridge is in which city?", "San Francisco", "New York", "Seattle", "Los Angeles"),
  G("The Grand Canyon is in which U.S. state?", "Arizona", "Colorado", "Nevada", "Utah"),
  G("Mount Rushmore, with the faces of four presidents, is in which state?", "South Dakota", "North Dakota", "Wyoming", "Montana"),
  G("Niagara Falls sits on the border between the United States and which country?", "Canada", "Mexico", "France", "Iceland"),
  G("The Great Wall is in which country?", "China", "Japan", "India", "Egypt"),
  G("The Taj Mahal is in which country?", "India", "Egypt", "Turkey", "China"),
  G("The ancient Colosseum stands in which city?", "Rome", "Athens", "Paris", "Cairo"),
  G("The famous clock tower known as Big Ben is in which city?", "London", "Paris", "New York", "Sydney"),
  G("The famous Opera House with sail-shaped roofs is in which city?", "Sydney", "London", "Venice", "San Francisco"),
  G("The ancient mountain city of Machu Picchu is in which country?", "Peru", "Mexico", "Egypt", "Greece"),
  G("The giant Christ the Redeemer statue overlooks which city?", "Rio de Janeiro", "Buenos Aires", "Mexico City", "Lisbon"),
  G("The famous Leaning Tower is in which Italian city?", "Pisa", "Rome", "Venice", "Florence"),
  G("The Panama Canal connects which two oceans?", "The Atlantic and the Pacific", "The Atlantic and the Indian", "The Pacific and the Arctic", "The Indian and the Arctic"),
  G("The Suez Canal is in which country?", "Egypt", "Panama", "Turkey", "Greece"),

  /* ==================== GEOGRAPHY — The United States & the world ==================== */
  G("What is the largest U.S. state by area?", "Alaska", "Texas", "California", "Montana"),
  G("What is the smallest U.S. state?", "Rhode Island", "Delaware", "Hawaii", "Connecticut"),
  G("Which state is nicknamed the Sunshine State?", "Florida", "California", "Arizona", "Hawaii"),
  G("Which state is nicknamed the Lone Star State?", "Texas", "Arizona", "Nevada", "Oklahoma"),
  G("Which state is famous for growing potatoes?", "Idaho", "Florida", "Maine", "Kansas"),
  G("Which state is nicknamed the Aloha State?", "Hawaii", "Florida", "California", "Alaska"),
  G("Which American city is nicknamed the Windy City?", "Chicago", "New York", "Boston", "Seattle"),
  G("Yellowstone, America's first national park, is mostly in which state?", "Wyoming", "Colorado", "California", "Alaska"),
  G("The Great Salt Lake is in which state?", "Utah", "Nevada", "Arizona", "New Mexico"),
  G("Which U.S. state reaches the farthest north?", "Alaska", "Maine", "Washington", "Minnesota"),
  G("The Everglades wetlands are in which state?", "Florida", "Louisiana", "Georgia", "Texas"),
  G("Which American city is nicknamed the Big Apple?", "New York City", "Los Angeles", "Chicago", "Miami"),
  G("The equator crosses which of these continents?", "South America", "Europe", "Australia", "Antarctica"),
  G("The prime meridian, where world time begins, passes through which city?", "London", "Paris", "New York", "Rome"),
  G("The North Pole sits in the middle of which ocean?", "The Arctic Ocean", "The Pacific Ocean", "The Atlantic Ocean", "The Indian Ocean")
];
