-- Népmesék és közmondások: 322 questions in Hungarian.
--
-- Written so the correct answer is never the longest option -- the tell that
-- made the Psychology bank guessable without reading the prompt. All four
-- choices share one type and grammatical form.
insert into public.quiz_questions (
  id,
  category_id,
  prompt,
  correct_answer,
  wrong_answers,
  language_code,
  grade_level,
  subject,
  display_order,
  is_active
)
select
  'magyar_nepmesek_' || lpad(question.ordinality::text, 4, '0'),
  'magyar_nepmesek',
  question.item ->> 'p',
  question.item ->> 'a',
  array(select jsonb_array_elements_text(question.item -> 'w')),
  'hu',
  null,
  question.item ->> 's',
  question.ordinality::integer,
  true
from jsonb_array_elements($questions$
[
  {"a": "aranyat lel", "p": "Fejezze be: „Ki korán kel, …”", "s": "Közmondások", "w": ["ezüstöt talál", "sokra viheti", "kincset gyűjt"]},
  {"a": "maga esik bele", "p": "Fejezze be: „Aki másnak vermet ás, …”", "s": "Közmondások", "w": ["maga is beleesik", "kétszer bűnhődik", "hamar megbánja"]},
  {"a": "a fájától", "p": "Fejezze be: „Nem esik messze az alma …”", "s": "Közmondások", "w": ["a tövétől", "az ágától", "a kertjétől"]},
  {"a": "tovább érsz", "p": "Fejezze be: „Lassan járj, …”", "s": "Közmondások", "w": ["messzebb jutsz", "hamarabb érsz", "kevesebbet esel"]},
  {"a": "amíg meleg", "p": "Fejezze be: „Addig üsd a vasat, …”", "s": "Közmondások", "w": ["amíg forró", "amíg ki nem hűl", "amíg bírod erővel"]},
  {"a": "ne nézd a fogát", "p": "Fejezze be: „Ajándék lónak …”", "s": "Közmondások", "w": ["ne nézd a korát", "ne nézd a színét", "ne nézd a lábát"]},
  {"a": "ami fénylik", "p": "Fejezze be: „Nem mind arany, …”", "s": "Közmondások", "w": ["ami csillog", "ami sárga", "ami szemet szúr"]},
  {"a": "úgy arat", "p": "Fejezze be: „Ki mint vet, …”", "s": "Közmondások", "w": ["úgy gyűjt", "annyit arat", "úgy takarít be"]},
  {"a": "sokra megy", "p": "Fejezze be: „Sok kicsi …”", "s": "Közmondások", "w": ["nagyot ad ki", "sokat ér együtt", "többre viszi"]},
  {"a": "mint megijedni", "p": "Fejezze be: „Jobb félni, …”", "s": "Közmondások", "w": ["mint utólag bánni", "mint bajba jutni", "mint később sírni"]},
  {"a": "szalonna", "p": "Fejezze be: „Kutyából nem lesz …”", "s": "Közmondások", "w": ["kolbász", "sonka", "disznóhús"]},
  {"a": "makkal álmodik", "p": "Fejezze be: „Éhes disznó …”", "s": "Közmondások", "w": ["mindent felfal", "korpával is beéri", "a vályút keresi"]},
  {"a": "ne is egyék", "p": "Fejezze be: „Aki nem dolgozik, …”", "s": "Közmondások", "w": ["ne is egyen", "éhen marad estig", "ne várjon vacsorát"]},
  {"a": "ebgondolat", "p": "Fejezze be: „Késő bánat …”", "s": "Közmondások", "w": ["hiú ábránd", "üres beszéd", "nagy keserűség"]},
  {"a": "három napig tart", "p": "Fejezze be: „Minden csoda …”", "s": "Közmondások", "w": ["két napig tart", "egy hétig tart", "csak rövid ideig tart"]},
  {"a": "rózsát terem", "p": "Fejezze be: „Türelem …”", "s": "Közmondások", "w": ["gyümölcsöt hoz", "sok jót terem", "békességet ad"]},
  {"a": "de erős", "p": "Fejezze be: „Kicsi a bors, …”", "s": "Közmondások", "w": ["de csípős", "de drága", "de nagy az ereje"]},
  {"a": "a napot", "p": "Fejezze be: „Nyugtával dicsérd …”", "s": "Közmondások", "w": ["a munkát", "az utat", "a jó napot"]},
  {"a": "ne halaszd holnapra", "p": "Fejezze be: „Amit ma megtehetsz, …”", "s": "Közmondások", "w": ["ne hagyd másra soha", "ne tedd el a jövő hétre", "ne bízd senki másra"]},
  {"a": "jön meg az étvágy", "p": "Fejezze be: „Evés közben …”", "s": "Közmondások", "w": ["múlik el az éhség", "nő meg a jókedv", "jön meg a jó kedve"]},
  {"a": "nem csinál nyarat", "p": "Fejezze be: „Egy fecske …”", "s": "Közmondások", "w": ["nem hoz tavaszt", "nem csinál tavaszt", "nem jelent nyarat"]},
  {"a": "annyi szokás", "p": "Fejezze be: „Ahány ház, …”", "s": "Közmondások", "w": ["annyi szabály", "annyi vélemény", "annyi gazda"]},
  {"a": "ha a szél nem fújja", "p": "Fejezze be: „Nem zörög a haraszt, …”", "s": "Közmondások", "w": ["ha a szél nem mozgatja", "ha nincsen ott a szél", "ha nem jár arra senki"]},
  {"a": "többet lát", "p": "Fejezze be: „Több szem …”", "s": "Közmondások", "w": ["jobban lát", "mindent észrevesz", "messzebbre lát"]},
  {"a": "tövis nélkül", "p": "Fejezze be: „Nincsen rózsa …”", "s": "Közmondások", "w": ["illat nélkül", "levél nélkül", "szép szirmok nélkül"]},
  {"a": "ameddig a takaród ér", "p": "Fejezze be: „Addig nyújtózkodj, …”", "s": "Közmondások", "w": ["ameddig az ágyad ér", "ameddig a lábad bírja", "ameddig az erőd bírja"]},
  {"a": "holtig tanul", "p": "Fejezze be: „A jó pap …”", "s": "Közmondások", "w": ["sokat tanul", "mindig tanul", "élete végéig tanul"]},
  {"a": "Isten végez", "p": "Fejezze be: „Ember tervez, …”", "s": "Közmondások", "w": ["a sors dönt", "az élet másképp hoz", "az idő elrendezi"]},
  {"a": "az nem harap", "p": "Fejezze be: „Amelyik kutya ugat, …”", "s": "Közmondások", "w": ["attól ne félj", "az messze marad", "az nem is bánt"]},
  {"a": "partot mos", "p": "Fejezze be: „Lassú víz …”", "s": "Közmondások", "w": ["mélyre ás", "messze fut", "lassan halad előre"]},
  {"a": "keveset fog", "p": "Fejezze be: „Aki sokat markol, …”", "s": "Közmondások", "w": ["semmit sem fog", "keveset tart meg", "mindent elejt"]},
  {"a": "az Isten is megsegít", "p": "Fejezze be: „Segíts magadon, …”", "s": "Közmondások", "w": ["és minden jóra fordul", "és más is melléd áll", "akkor boldogulsz is"]},
  {"a": "talál szemet", "p": "Fejezze be: „Vak tyúk is …”", "s": "Közmondások", "w": ["talál magot", "talál búzát", "megleli a szemet"]},
  {"a": "mint holnap egy túzok", "p": "Fejezze be: „Jobb ma egy veréb, …”", "s": "Közmondások", "w": ["mint holnap egy galamb", "mint holnap két veréb", "mint jövőre egy sas"]},
  {"a": "úgy alussza álmát", "p": "Fejezze be: „Ki mint veti ágyát, …”", "s": "Közmondások", "w": ["úgy pihen meg rajta", "olyan az éjszakája", "úgy is alszik rajta"]},
  {"a": "ott hullik a forgács", "p": "Fejezze be: „Ahol fát vágnak, …”", "s": "Közmondások", "w": ["ott száll a fűrészpor", "ott törik az ág is", "ott nagy a zaj"]},
  {"a": "kinek a papné", "p": "Fejezze be: „Kinek a pap, …”", "s": "Közmondások", "w": ["kinek a kántor", "kinek a templom", "kinek a harangozó"]},
  {"a": "de nem bírja a farka", "p": "Fejezze be: „Sokat akar a szarka, …”", "s": "Közmondások", "w": ["de kevés hozzá az ereje", "de nem viszi el mind", "de elszáll a szárnya"]},
  {"a": "kétszer fárad", "p": "Fejezze be: „A rest …”", "s": "Közmondások", "w": ["sokat pihen", "mindig panaszkodik", "semmire sem jut"]},
  {"a": "olyan a törülköző", "p": "Fejezze be: „Amilyen a mosdó, …”", "s": "Közmondások", "w": ["olyan a szappan is", "olyan a tisztaság", "olyan a vize is"]},
  {"a": "aki gyorsan ad", "p": "Fejezze be: „Kétszer ad, …”", "s": "Közmondások", "w": ["aki szívesen ad", "aki azonnal ad", "aki jó szívvel ad"]},
  {"a": "megnyalja a sót", "p": "Fejezze be: „A vén kecske is …”", "s": "Közmondások", "w": ["megkívánja a sót", "megeszi a zöldet", "elmegy a legelőre"]},
  {"a": "nem kell cégér", "p": "Fejezze be: „Jó bornak …”", "s": "Közmondások", "w": ["nem kell hirdetés", "nem kell dicséret", "nem kell szép címke"]},
  {"a": "anyja sem érti a szavát", "p": "Fejezze be: „Néma gyereknek …”", "s": "Közmondások", "w": ["az anyja sem ért a szaván", "senki sem érti a baját", "az apja sem érti a kérését"]},
  {"a": "a medve bőrére", "p": "Fejezze be: „Ne igyál előre …”", "s": "Közmondások", "w": ["a nyúl bőrére", "a farkas bőrére", "a szarvas bőrére"]},
  {"a": "a mennykő", "p": "Fejezze be: „Csalánba nem üt …”", "s": "Közmondások", "w": ["a villám", "a jégeső", "semmiféle baj"]},
  {"a": "nem fér meg egy csárdában", "p": "Fejezze be: „Két dudás …”", "s": "Közmondások", "w": ["nem fér el egy faluban", "nem fér meg egy szobában", "nem tud egyszerre játszani"]},
  {"a": "vihart arat", "p": "Fejezze be: „Aki szelet vet, …”", "s": "Közmondások", "w": ["esőt arat", "szélvészt arat", "nagy bajt arat"]},
  {"a": "mos", "p": "Fejezze be: „Kéz kezet …”", "s": "Közmondások", "w": ["fog", "keres", "melegít"]},
  {"a": "sok az alja", "p": "Fejezze be: „Sok beszédnek …”", "s": "Közmondások", "w": ["nincs haszna", "kevés a haszna", "rossz a vége"]},
  {"a": "hallgatni arany", "p": "Fejezze be: „Beszélni ezüst, …”", "s": "Közmondások", "w": ["hallgatni jobb", "a csend aranyat ér", "hallgatni bölcsebb"]},
  {"a": "hogy nagyfejű", "p": "Fejezze be: „Bagoly mondja verébnek, …”", "s": "Közmondások", "w": ["hogy csúnya", "hogy kicsi a szeme", "hogy nagy a csőre"]},
  {"a": "toldd meg egy lépéssel", "p": "Fejezze be: „Ha rövid a kardod, …”", "s": "Közmondások", "w": ["lépj közelebb az ellenhez", "toldd meg egy arasszal", "végy másikat helyette"]},
  {"a": "olyan a fogadjisten", "p": "Fejezze be: „Amilyen az adjonisten, …”", "s": "Közmondások", "w": ["olyan a köszönés is", "olyan a válasz rá", "olyan a fogadtatás is"]},
  {"a": "megtalálja", "p": "Fejezze be: „Zsák a foltját …”", "s": "Közmondások", "w": ["megleli", "keresi", "előbb-utóbb megleli"]},
  {"a": "ha megtartják, úgy jó", "p": "Fejezze be: „Az ígéret szép szó, …”", "s": "Közmondások", "w": ["de kevés ér valamit", "ha beváltják, az a jó", "de nem mindig tartják meg"]},
  {"a": "Mohácsnál", "p": "Fejezze be: „Több is veszett …”", "s": "Közmondások", "w": ["Muhinál", "a csatában", "a nagy háborúban"]},
  {"a": "pokolra kell annak menni", "p": "Fejezze be: „Aki dudás akar lenni, …”", "s": "Közmondások", "w": ["sokat kell gyakorolnia", "erdőbe kell annak menni", "sok keserűséget kell tűrnie"]},
  {"a": "elsózza a levest", "p": "Fejezze be: „Sok szakács …”", "s": "Közmondások", "w": ["megrontja a levest", "sokáig főzi a levest", "összevész a konyhán"]},
  {"a": "ökör lesz belőled", "p": "Fejezze be: „Tanulj tinó, …”", "s": "Közmondások", "w": ["nagy marha lesz belőled", "erős lesz a vállad", "hasznodat veszik majd"]},
  {"a": "mégis megbotlik", "p": "Fejezze be: „A lónak négy lába van, …”", "s": "Közmondások", "w": ["mégis elesik néha", "mégis megcsúszik olykor", "mégis elfárad egyszer"]},
  {"a": "teszi az embert", "p": "Fejezze be: „Nem a ruha …”", "s": "Közmondások", "w": ["mutatja az embert", "adja a becsületet", "teszi széppé az embert"]},
  {"a": "lassan őrölnek", "p": "Fejezze be: „Isten malmai …”", "s": "Közmondások", "w": ["mindig őrölnek", "sosem állnak meg", "aprólékosan őrölnek"]},
  {"a": "hamar megöregszik", "p": "Fejezze be: „Aki kíváncsi, …”", "s": "Közmondások", "w": ["sokat megtud", "hamar bajba kerül", "előbb-utóbb ráfizet"]},
  {"a": "nem vész el", "p": "Fejezze be: „Rossz pénz …”", "s": "Közmondások", "w": ["nem fogy el", "megint felbukkan", "sosem megy veszendőbe"]},
  {"a": "rossz ember nem lehet", "p": "Fejezze be: „Aki a virágot szereti, …”", "s": "Közmondások", "w": ["jó ember hírében áll", "annak kedves a lelke", "az jószívű ember lehet"]},
  {"a": "híg a leve", "p": "Fejezze be: „Olcsó húsnak …”", "s": "Közmondások", "w": ["rossz az íze", "kevés a haszna", "gyenge a minősége"]},
  {"a": "annyi ember vagy", "p": "Fejezze be: „Ahány nyelvet beszélsz, …”", "s": "Közmondások", "w": ["annyi hazád van", "annyi barátod lesz", "annyi utat ismersz"]},
  {"a": "kint s bent egeret", "p": "Fejezze be: „Nem fog a macska egyszerre …”", "s": "Közmondások", "w": ["két helyen egeret", "kint és bent is egeret", "a padláson és a pincében"]},
  {"a": "de ember az emberrel igen", "p": "Fejezze be: „Hegy a heggyel nem találkozik, …”", "s": "Közmondások", "w": ["de az emberek igen", "de a folyók igen", "de két ember előbb-utóbb igen"]},
  {"a": "a legjobb szakács", "p": "Fejezze be: „Az éhség …”", "s": "Közmondások", "w": ["a legjobb fűszer", "a legrosszabb tanácsadó", "a legnagyobb úr"]},
  {"a": "vízzel főz", "p": "Fejezze be: „Szegény ember …”", "s": "Közmondások", "w": ["sóval főz", "kenyeret eszik", "kevésből gazdálkodik"]},
  {"a": "nem fáj fejem", "p": "Fejezze be: „Ne szólj szám, …”", "s": "Közmondások", "w": ["nem lesz bajom", "nem ér gáncs", "nem fáj a fejem sem"]},
  {"a": "elvész a gyerek", "p": "Fejezze be: „Sok bába közt …”", "s": "Közmondások", "w": ["elvész a rend", "nagy a zűrzavar", "nem születik meg a gyerek"]},
  {"a": "de legjobb otthon", "p": "Fejezze be: „Mindenütt jó, …”", "s": "Közmondások", "w": ["de otthon a legjobb", "a haza a legszebb", "de szebb a szülőföld"]},
  {"a": "az egérnek halál", "p": "Fejezze be: „Ami a macskának játék, …”", "s": "Közmondások", "w": ["az egérnek nagy baj", "az egérnek keserves", "az egérnek szomorú"]},
  {"a": "ne vegye magára", "p": "Fejezze be: „Akinek nem inge, …”", "s": "Közmondások", "w": ["ne húzza magára", "az ne sértődjön meg", "ne haragudjon érte"]},
  {"a": "megárt a sok", "p": "Fejezze be: „Jóból is …”", "s": "Közmondások", "w": ["elég a kevés", "sok a túlzás", "megárthat a túl sok"]},
  {"a": "mint soha", "p": "Fejezze be: „Jobb későn, …”", "s": "Közmondások", "w": ["mint sosem", "mint semmikor", "mint egyáltalán nem"]},
  {"a": "egyszer lent", "p": "Fejezze be: „Egyszer fent, …”", "s": "Közmondások", "w": ["másszor lent", "aztán megint lent", "máskor pedig lent"]},
  {"a": "úgy puffan", "p": "Fejezze be: „Ahogy esik, …”", "s": "Közmondások", "w": ["úgy koppan", "úgy hullik", "olyan a hangja"]},
  {"a": "kis helyen is elfér", "p": "Fejezze be: „Sok jó ember …”", "s": "Közmondások", "w": ["egy asztalnál is elfér", "sok helyet foglal el", "mindig együtt marad"]},
  {"a": "ebül vész el", "p": "Fejezze be: „Ebül szerzett jószág …”", "s": "Közmondások", "w": ["hamar elfogy", "nem hoz áldást", "sosem marad meg soká"]},
  {"a": "megeszik a disznók", "p": "Fejezze be: „Ki korpa közé keveredik, …”", "s": "Közmondások", "w": ["rossz vége lesz annak", "bajba kerül hamarosan", "megszólja majd a falu"]},
  {"a": "embert barátjáról", "p": "Fejezze be: „Madarat tolláról, …”", "s": "Közmondások", "w": ["embert a szaváról", "embert a tettéről", "embert a ruhájáról"]},
  {"a": "mint a sánta kutyát", "p": "Fejezze be: „Hazug embert hamarabb utolérik, …”", "s": "Közmondások", "w": ["mint a futó nyulat", "mint a béna lovat", "mint a sánta szamarat"]},
  {"a": "az nyer", "p": "Fejezze be: „Aki mer, …”", "s": "Közmondások", "w": ["az győz", "az kap", "az viszi el"]},
  {"a": "disznót győz", "p": "Fejezze be: „Sok lúd …”", "s": "Közmondások", "w": ["farkast győz", "medvét is győz", "a rókát is legyőzi"]},
  {"a": "a nagyot nem érdemli", "p": "Fejezze be: „Aki a kicsit nem becsüli, …”", "s": "Közmondások", "w": ["a nagyot sem kapja meg", "az sokra nem viszi", "a nagyot sem becsüli"]},
  {"a": "derű", "p": "Fejezze be: „Borúra …”", "s": "Közmondások", "w": ["eső", "napfény", "szép idő jön"]},
  {"a": "ne menjen az erdőbe", "p": "Fejezze be: „Aki fél a farkastól, …”", "s": "Közmondások", "w": ["ne járjon a mezőn", "maradjon a faluban", "ne induljon vadászni"]},
  {"a": "a kerítés", "p": "Fejezze be: „Nem kolbászból van …”", "s": "Közmondások", "w": ["a palánk", "a ház fala", "a szomszéd kapuja"]},
  {"a": "kutyavásár", "p": "Fejezze be: „Egyszer volt Budán …”", "s": "Közmondások", "w": ["lóvásár", "nagy vásár", "országos vásár"]},
  {"a": "forgandó", "p": "Fejezze be: „A szerencse …”", "s": "Közmondások", "w": ["vak", "csalfa", "változékony"]},
  {"a": "megülni", "p": "Fejezze be: „Nem lehet egy fenékkel két lovat …”", "s": "Közmondások", "w": ["hajtani", "meglovagolni", "egyszerre megülni"]},
  {"a": "nem kap rétest estére", "p": "Fejezze be: „Aki nem lép egyszerre, …”", "s": "Közmondások", "w": ["nem kap kalácsot estére", "lemarad a sorból", "nem kap vacsorát este"]},
  {"a": "ajtó mögött a helye", "p": "Fejezze be: „Fogadatlan prókátornak …”", "s": "Közmondások", "w": ["nem jár érte köszönet", "kevés a becsülete", "sehol sincsen helye"]},
  {"a": "szőrével", "p": "Fejezze be: „Kutyaharapást …”", "s": "Közmondások", "w": ["vizével", "sebtapasszal", "jó szóval gyógyítják"]},
  {"a": "a falra", "p": "Fejezze be: „Ne fesd az ördögöt …”", "s": "Közmondások", "w": ["az ajtóra", "a kapura", "a ház falára"]},
  {"a": "nem alszik", "p": "Fejezze be: „Az ördög …”", "s": "Közmondások", "w": ["nem pihen", "sosem alszik el", "mindig figyel"]},
  {"a": "ne beszéljen arabusul", "p": "Fejezze be: „Aki nem tud arabusul, …”", "s": "Közmondások", "w": ["ne szóljon arabusul", "ne kezdjen bele soha", "hallgasson inkább róla"]},
  {"a": "mint kolbász", "p": "Fejezze be: „Több nap, …”", "s": "Közmondások", "w": ["mint ünnep", "mint vasárnap", "mint hurka és kolbász"]},
  {"a": "a magyar", "p": "Fejezze be: „Sírva vigad …”", "s": "Közmondások", "w": ["a székely", "a cigány", "a jó ember"]},
  {"a": "aki utoljára nevet", "p": "Fejezze be: „Az nevet igazán, …”", "s": "Közmondások", "w": ["aki jóízűen nevet", "aki legtovább nevet", "aki sokat nevet az életben"]},
  {"a": "olyan a fia", "p": "Fejezze be: „Amilyen az apa, …”", "s": "Közmondások", "w": ["olyan a lánya", "olyan a gyermeke", "olyan a családja"]},
  {"a": "olyan a lánya", "p": "Fejezze be: „Amilyen az anya, …”", "s": "Közmondások", "w": ["olyan a fia", "olyan a menye", "olyan a gyermeke"]},
  {"a": "a világ", "p": "Fejezze be: „Szemesnek áll …”", "s": "Közmondások", "w": ["az élet", "a szerencse", "minden jó dolog"]},
  {"a": "ott ne keress", "p": "Fejezze be: „Ahol nincs, …”", "s": "Közmondások", "w": ["ott ne kérj", "onnan ne várj", "ott hiába kutatsz"]},
  {"a": "vízzé", "p": "Fejezze be: „Vér nem válik …”", "s": "Közmondások", "w": ["tejjé", "borrá", "olajjá"]},
  {"a": "nem vájja ki a szemét", "p": "Fejezze be: „Holló a hollónak …”", "s": "Közmondások", "w": ["nem árt a másiknak", "nem csípi meg a szárnyát", "nem tesz rosszat soha"]},
  {"a": "jól seper", "p": "Fejezze be: „Új seprű …”", "s": "Közmondások", "w": ["jobban seper", "tisztára seper", "sokáig seper"]},
  {"a": "míg el nem törik", "p": "Fejezze be: „Addig jár a korsó a kútra, …”", "s": "Közmondások", "w": ["amíg meg nem telik", "míg össze nem törik", "amíg ki nem lyukad"]},
  {"a": "a tolvajt", "p": "Fejezze be: „Alkalom szüli …”", "s": "Közmondások", "w": ["a bűnt", "a gazembert", "a rossz embert"]},
  {"a": "százat csinál", "p": "Fejezze be: „Egy bolond …”", "s": "Közmondások", "w": ["sokat csinál", "tízet is csinál", "másokat is elront"]},
  {"a": "nem szégyen", "p": "Fejezze be: „Szegénység …”", "s": "Közmondások", "w": ["nem bűn", "nem gyalázat", "nem nagy dicsőség"]},
  {"a": "bölcs maradtál volna", "p": "Fejezze be: „Ha hallgattál volna, …”", "s": "Közmondások", "w": ["okos maradtál volna", "nem lenne most bajod", "megmaradt volna a jó híred"]},
  {"a": "olyan a gyümölcse", "p": "Fejezze be: „Amilyen a fa, …”", "s": "Közmondások", "w": ["olyan az árnyéka", "olyan a virága is", "olyan a termése lesz"]},
  {"a": "szaladj", "p": "Fejezze be: „Ha adnak, vedd el; ha ütnek, …”", "s": "Közmondások", "w": ["ne szólj", "kiálts", "fuss el gyorsan"]},
  {"a": "ahogy főzik", "p": "Fejezze be: „Nem eszik olyan forrón a kását, …”", "s": "Közmondások", "w": ["amikor megfő", "amint kifőzik", "ahogyan tálalják"]},
  {"a": "A gyerek a szülőjére üt.", "p": "Mit jelent: „Nem esik messze az alma a fájától”?", "s": "Közmondás jelentése", "w": ["A fa alatt terem a gyümölcs.", "A kert közelében van a ház.", "Az alma hamar leesik a fáról."]},
  {"a": "Együtt a gyengék is győznek.", "p": "Mit jelent: „Sok lúd disznót győz”?", "s": "Közmondás jelentése", "w": ["A liba erősebb, mint a disznó.", "Sok állat kell egy jó udvarba.", "A disznó fél a szárnyasoktól."]},
  {"a": "A rossz ember nem változik.", "p": "Mit jelent: „Kutyából nem lesz szalonna”?", "s": "Közmondás jelentése", "w": ["A kutyahús nem ehető meg.", "A kutya szereti a szalonnát.", "A hentesnek jó húsra van szüksége."]},
  {"a": "Jobb előre óvatosnak lenni.", "p": "Mit jelent: „Jobb félni, mint megijedni”?", "s": "Közmondás jelentése", "w": ["Jobb bátran szembenézni mindennel.", "A félelem mindig rossz tanácsadó.", "Az ijedtség hamar elmúlik."]},
  {"a": "A korán kelő többre jut.", "p": "Mit jelent: „Ki korán kel, aranyat lel”?", "s": "Közmondás jelentése", "w": ["Hajnalban fényes az ég.", "Aranyat hajnalban találni.", "Aki sokat alszik, beteg lesz."]},
  {"a": "Ügyetlennek is van szerencséje.", "p": "Mit jelent: „Vak tyúk is talál szemet”?", "s": "Közmondás jelentése", "w": ["A vak tyúkot kézből kell etetni.", "A tyúkok jól látnak sötétben is.", "A baromfi mindig talál magot."]},
  {"a": "A csendes ember is sokat tesz.", "p": "Mit jelent: „Lassú víz partot mos”?", "s": "Közmondás jelentése", "w": ["A lassú folyó nem veszélyes.", "A víz lassan tisztítja a partot.", "A folyóban jó fürödni nyáron."]},
  {"a": "A rosszakaró maga jár pórul.", "p": "Mit jelent: „Aki másnak vermet ás, maga esik bele”?", "s": "Közmondás jelentése", "w": ["A gödröt mindig be kell temetni.", "Vadászni csapdával is szoktak.", "A mély gödör veszélyes a jószágra."]},
  {"a": "A szép látszat sokszor csal.", "p": "Mit jelent: „Nem mind arany, ami fénylik”?", "s": "Közmondás jelentése", "w": ["Az arany mindig fényesen csillog.", "A régi ékszer sokat érhet.", "A fényes fém értékes szokott lenni."]},
  {"a": "Aki mindent akar, keveset ér el.", "p": "Mit jelent: „Aki sokat markol, keveset fog”?", "s": "Közmondás jelentése", "w": ["Aki nagy marokkal fog, sokat visz haza.", "A nagy kéz több gabonát emel.", "Sok kis marok tesz ki egy zsákot."]},
  {"a": "Az ajándékot ne bíráld.", "p": "Mit jelent: „Ajándék lónak ne nézd a fogát”?", "s": "Közmondás jelentése", "w": ["Nézd meg a ló fogát.", "Lovat csak vásárban végy.", "A ló foga elárulja a korát."]},
  {"a": "Használd ki a jó alkalmat.", "p": "Mit jelent: „Addig üsd a vasat, amíg meleg”?", "s": "Közmondás jelentése", "w": ["Melegíts vasat!", "A hideg vasat nehéz hajlítani.", "A kovács forrón dolgozik a vassal."]},
  {"a": "A kicsi is lehet nagy erejű.", "p": "Mit jelent: „Kicsi a bors, de erős”?", "s": "Közmondás jelentése", "w": ["A bors csípős fűszer a konyhában.", "A bors messzi földről érkezik.", "A fűszereket kicsi zacskóban árulják."]},
  {"a": "Apránként is nagy dolog gyűlik.", "p": "Mit jelent: „Sok kicsi sokra megy”?", "s": "Közmondás jelentése", "w": ["A kicsi gyerekek gyorsan nőnek meg.", "Sok apró tárgy sok helyet foglal.", "A kevés pénz hamar elfogy."]},
  {"a": "Rossz társaság bajba sodor.", "p": "Mit jelent: „Aki korpa közé keveredik, megeszik a disznók”?", "s": "Közmondás jelentése", "w": ["A korpát a disznók szeretik.", "A malacokat korpával etetik.", "A korpa olcsó takarmány télen."]},
  {"a": "Ügyesen helytáll.", "p": "Mit jelent: „kivágja a rezet”?", "s": "Szólások", "w": ["Rezet bányász.", "Kidobja a régi holmiját.", "Hangosan kiabál mindenkivel."]},
  {"a": "Ismeretlen áru.", "p": "Mit jelent: „zsákbamacska”?", "s": "Szólások", "w": ["Házi macska.", "Zsákban hordott élelem.", "Olcsó vásári portéka."]},
  {"a": "Nagyon sürgőssé vált.", "p": "Mit jelent: „körmére ég a munka”?", "s": "Szólások", "w": ["Elrontotta a munkáját.", "Nehéz fizikai munkát végez.", "Megégette a kezét munka közben."]},
  {"a": "Visszautasítja a kérőt.", "p": "Mit jelent: „kosarat ad”?", "s": "Szólások", "w": ["Kosarat fon vesszőből.", "Gyümölcsöt visz a betegnek.", "Ajándékot ad a vendégnek."]},
  {"a": "Kifecseg egy titkot.", "p": "Mit jelent: „eljár a szája”?", "s": "Szólások", "w": ["Sokat eszik és iszik.", "Hangosan énekel mindig.", "Gyakran jár vendégségbe."]},
  {"a": "Becsap valakit.", "p": "Mit jelent: „lóvá tesz”?", "s": "Szólások", "w": ["Lovat ad.", "Lóra ültet valakit.", "Megtanít valakit lovagolni."]},
  {"a": "Éhen marad, koplal.", "p": "Mit jelent: „felkopik az álla”?", "s": "Szólások", "w": ["Borotválkozik.", "Megnő a szakálla.", "Sokáig alszik reggel."]},
  {"a": "Gyorsan és jól dolgozik.", "p": "Mit jelent: „ég a keze alatt a munka”?", "s": "Szólások", "w": ["Munka közben megégeti magát.", "Tűz mellett szokott dolgozni.", "Nem szeret dolgozni soha."]},
  {"a": "Bajba került.", "p": "Mit jelent: „benne van a pácban”?", "s": "Szólások", "w": ["Húst pácol.", "Melegen fürdik otthon.", "Sokat eszik a savanyúból."]},
  {"a": "Magára haragít valakit.", "p": "Mit jelent: „kihúzza a gyufát”?", "s": "Szólások", "w": ["Tüzet gyújt a kályhában.", "Kiveszi a dobozból a gyufát.", "Cigarettára gyújt gyorsan."]},
  {"a": "Mellé áll és védi.", "p": "Mit jelent: „fogja a pártját”?", "s": "Szólások", "w": ["Politikai pártba lép.", "Pártot alapít a faluban.", "Megfogja valaki kezét."]},
  {"a": "Nincs semmi értelme.", "p": "Mit jelent: „se füle, se farka”?", "s": "Szólások", "w": ["Nagyon rövid az állat.", "Elveszett a kisállat.", "Csonka lett a szobor."]},
  {"a": "Nagyon sok van belőle.", "p": "Mit jelent: „se szeri, se száma”?", "s": "Szólások", "w": ["Nincs rajta szám és jelzés.", "Elszámolni sem lehet vele.", "Kevés maradt belőle."]},
  {"a": "Van rejtegetnivalója.", "p": "Mit jelent: „vaj van a fején”?", "s": "Szólások", "w": ["Vajat kent a hajára.", "Nagyon rendetlen ember.", "Elfelejtette a kalapját."]},
  {"a": "Sírdogál, könnyezik.", "p": "Mit jelent: „itatja az egereket”?", "s": "Szólások", "w": ["Egeret itat.", "Vizet visz az állatoknak.", "Tejet tesz ki a pincébe."]},
  {"a": "Jönnek még jobb idők.", "p": "Mit jelent: „lesz még szőlő, lágy kenyér”?", "s": "Szólások", "w": ["Ősszel érik meg a szőlő.", "Kenyeret sütnek a faluban.", "Bort fognak inni a lakodalmon."]},
  {"a": "Szorult helyzetbe jut.", "p": "Mit jelent: „kutyaszorítóba kerül”?", "s": "Szólások", "w": ["Kutyák közé keveredik az utcán.", "Kis helyre zárják be.", "Megharapja egy kutya."]},
  {"a": "Bosszúságot okoz neki.", "p": "Mit jelent: „borsot tör az orra alá”?", "s": "Szólások", "w": ["Fűszert őröl a konyhában.", "Megtréfálja a vendégeit.", "Tüsszentésre készteti."]},
  {"a": "Jól és sokat beszél.", "p": "Mit jelent: „felvágták a nyelvét”?", "s": "Szólások", "w": ["Megsérült a szája.", "Beszédhibával küzd.", "Orvoshoz kellett vinni."]},
  {"a": "Türelmetlenül vár.", "p": "Mit jelent: „tűkön ül”?", "s": "Szólások", "w": ["Varrni tanul éppen.", "Kényelmetlen a széke.", "Szúrós a ruhája."]},
  {"a": "Semmit nem ér.", "p": "Mit jelent: „fabatkát sem ér”?", "s": "Szólások", "w": ["Fajáték.", "Kevés pénzbe kerül.", "Régi pénzérme neve."]},
  {"a": "Összetartanak titokban.", "p": "Mit jelent: „egy gyékényen árulnak”?", "s": "Szólások", "w": ["A piacon árulnak együtt.", "Gyékényt fonnak eladásra.", "Egy standon dolgoznak ketten."]},
  {"a": "Makacsul ragaszkodik hozzá.", "p": "Mit jelent: „köti az ebet a karóhoz”?", "s": "Szólások", "w": ["Kutyát köt ki az udvaron.", "Kerítést épít a kertben.", "Nem engedi ki az állatot sétálni."]},
  {"a": "Döntő összecsapást vállal.", "p": "Mit jelent: „kenyértörésre viszi”?", "s": "Szólások", "w": ["Kenyeret szeg az asztalnál.", "Vendégséget rendez.", "Megosztja az ételét."]},
  {"a": "Nagyot túloz.", "p": "Mit jelent: „elveti a sulykot”?", "s": "Szólások", "w": ["Magot vet.", "Elhajítja a szerszámot.", "Abbahagyja a munkát."]},
  {"a": "Szomorkodik.", "p": "Mit jelent: „lóg az orra”?", "s": "Szólások", "w": ["Náthás.", "Nagyon hosszú az orra.", "Lehajtja a fejét fáradtan."]},
  {"a": "Megsértődik.", "p": "Mit jelent: „felhúzza az orrát”?", "s": "Szólások", "w": ["Szimatol.", "Felemeli a fejét büszkén.", "Náthás lett hirtelen."]},
  {"a": "Elmondja a bánatát.", "p": "Mit jelent: „kiönti a szívét”?", "s": "Szólások", "w": ["Kiborul a víz.", "Nagyon megijed valamitől.", "Szerelmes lesz valakibe."]},
  {"a": "Hibát követ el.", "p": "Mit jelent: „bakot lő”?", "s": "Szólások", "w": ["Vadászik.", "Kecskét vásárol a piacon.", "Célba lő a versenyen."]},
  {"a": "Gyanút kelt benne.", "p": "Mit jelent: „szeget üt a fejébe”?", "s": "Szólások", "w": ["Megüti a fejét valahol.", "Munka közben kalapál.", "Fejfájása lesz estére."]},
  {"a": "Végre boldogul.", "p": "Mit jelent: „zöld ágra vergődik”?", "s": "Szólások", "w": ["Felmászik egy fára.", "Kertészkedni kezd.", "Tavasszal kimegy a rétre."]},
  {"a": "Nem mer a lényegre térni.", "p": "Mit jelent: „kerülgeti, mint macska a forró kását”?", "s": "Szólások", "w": ["Óvatosan eszi az ételt.", "Fél a konyhai tűztől.", "Körbejárja a forró fazekat."]},
  {"a": "Erősen gondolkodik.", "p": "Mit jelent: „töri a fejét”?", "s": "Szólások", "w": ["Beveri a fejét az ajtóba.", "Fejfájás gyötri.", "Diót tör a konyhában."]},
  {"a": "Jó sokat iszik.", "p": "Mit jelent: „felönt a garatra”?", "s": "Szólások", "w": ["Gabonát önt.", "Vizet tölt a kútba.", "Megtölti a hombárt."]},
  {"a": "Titokban összejátszanak.", "p": "Mit jelent: „egy követ fújnak”?", "s": "Szólások", "w": ["Követ hordanak az útra.", "Üveget fújnak a műhelyben.", "Egy helyen dolgoznak."]},
  {"a": "Nem enged a magáéból.", "p": "Mit jelent: „nem enged a negyvennyolcból”?", "s": "Szólások", "w": ["Kevesli a bért.", "Nem fizet ki egy összeget.", "Negyvennyolc évig dolgozik."]},
  {"a": "Meglepetésében elnémul.", "p": "Mit jelent: „eláll a szava”?", "s": "Szólások", "w": ["Megfájdul a torka.", "Visszavonja az ígéretét.", "Rekedt lesz a beszédtől."]},
  {"a": "Nyomtalanul eltűnik.", "p": "Mit jelent: „lába kel”?", "s": "Szólások", "w": ["Járni tanul a kisgyerek.", "Elindul sétálni.", "Meggyógyul a lábbaja."]},
  {"a": "Nyoma sem maradt.", "p": "Mit jelent: „híre-hamva sincs”?", "s": "Szólások", "w": ["Rossz híre kelt a faluban.", "Elégett a nagy tűzben.", "Nem ismerik a nevét."]},
  {"a": "Lehetetlen dolog.", "p": "Mit jelent: „fából vaskarika”?", "s": "Szólások", "w": ["Fából készült játék.", "Régi kovácsmunka.", "Erős szekérkerék."]},
  {"a": "Hiábavaló beszéd.", "p": "Mit jelent: „falra hányt borsó”?", "s": "Szólások", "w": ["Rendetlenség a konyhában.", "Elszórt vetőmag.", "Falra dobott étel."]},
  {"a": "Nagy szerencséje van.", "p": "Mit jelent: „ördöge van”?", "s": "Szólások", "w": ["Gonosz ember hírében áll.", "Rossz álmai vannak.", "Fél a sötétben járni."]},
  {"a": "Csínyt követ el.", "p": "Mit jelent: „rossz fát tesz a tűzre”?", "s": "Szólások", "w": ["Nedves fával fűt be.", "Rosszul rakja meg a kályhát.", "Füstöl a kéménye."]},
  {"a": "Kiderül a titok.", "p": "Mit jelent: „kibújik a szög a zsákból”?", "s": "Szólások", "w": ["Elszakad a zsák alja.", "Kiömlik a gabona.", "Megsérül valaki a zsáktól."]},
  {"a": "Nehéz feladatba kezd.", "p": "Mit jelent: „nagy fába vágja a fejszéjét”?", "s": "Szólások", "w": ["Fát vág az erdőben.", "Új fejszét vásárol.", "Kidönt egy öreg tölgyet."]},
  {"a": "Már nincs ott.", "p": "Mit jelent: „hűlt helye”?", "s": "Szólások", "w": ["Kihűlt az étele.", "Hideg a szobája.", "Fázik a lakásban."]},
  {"a": "Nem sikerül neki.", "p": "Mit jelent: „csütörtököt mond”?", "s": "Szólások", "w": ["Napot mond.", "Csütörtökön beszél.", "Elhalasztja a találkozót."]},
  {"a": "Nagyon dicsekszik.", "p": "Mit jelent: „veri a mellét”?", "s": "Szólások", "w": ["Köhög és fullad.", "Mellkasi fájdalma van.", "Kalapál a műhelyben."]},
  {"a": "Nem értik meg egymást.", "p": "Mit jelent: „két malomban őrölnek”?", "s": "Szólások", "w": ["Két malom dolgozik együtt.", "Sok lisztet készítenek.", "Molnárként dolgoznak ketten."]},
  {"a": "Nagyon szegény.", "p": "Mit jelent: „ágrólszakadt”?", "s": "Szólások", "w": ["Leesett egy fáról.", "Törött ág a földön.", "Sérült lett a karja."]},
  {"a": "Elszalad, megszökik.", "p": "Mit jelent: „kereket old”?", "s": "Szólások", "w": ["Leszereli a szekér kerekét.", "Kerékpárt javít.", "Kioldja a kötelet."]},
  {"a": "Tőrbe csal valakit.", "p": "Mit jelent: „lépre csal”?", "s": "Szólások", "w": ["Lépesmézet készít.", "Méheket tart a kertben.", "Lépcsőn vezet fel."]},
  {"a": "Megjárja, baja lesz.", "p": "Mit jelent: „megüti a bokáját”?", "s": "Szólások", "w": ["Elesik és megsérül.", "Megrúgja a székét.", "Fájdalom hasít a lábába."]},
  {"a": "Szítja a veszekedést.", "p": "Mit jelent: „olajat önt a tűzre”?", "s": "Szólások", "w": ["Meggyújtja az olajlámpát.", "Olajjal főz a konyhában.", "Tüzet rak az udvaron."]},
  {"a": "Megmutatja valódi arcát.", "p": "Mit jelent: „kimutatja a foga fehérét”?", "s": "Szólások", "w": ["Nevet és mosolyog sokat.", "Fogat mos a fürdőben.", "Az orvosnál kinyitja a száját."]},
  {"a": "Tapintatlanul kezd bele.", "p": "Mit jelent: „ajtóstul ront a házba”?", "s": "Szólások", "w": ["Betöri a ház ajtaját.", "Hívatlanul jön vendégségbe.", "Elrontja az ajtó zárját."]},
  {"a": "Csak csendesen!", "p": "Mit jelent: „hátrább az agarakkal”?", "s": "Szólások", "w": ["Gyerünk!", "Indulj el a vadászatra!", "Kösd meg a vadászebeket!"]},
  {"a": "Figyelmesen hallgat.", "p": "Mit jelent: „hegyezi a fülét”?", "s": "Szólások", "w": ["Fáj a füle a hidegtől.", "Rosszul hall mindent.", "Ceruzát hegyez az asztalnál."]},
  {"a": "Sokat ígér, keveset ad.", "p": "Mit jelent: „fűt-fát ígér”?", "s": "Szólások", "w": ["Tűzifát árul a piacon.", "Fákat ültet a kert végében.", "Befűti a szobát melegre."]},
  {"a": "Megpihen a régi sikerén.", "p": "Mit jelent: „babérjain ül”?", "s": "Szólások", "w": ["Fűszernövényt termeszt.", "Koszorút készít az ünnepre.", "Kényelmes karosszékben ül."]},
  {"a": "Rosszul jár.", "p": "Mit jelent: „pórul jár”?", "s": "Szólások", "w": ["Sokat gyalogol.", "Porosan érkezik haza.", "Por száll a szemébe."]},
  {"a": "Önállóvá tesz valakit.", "p": "Mit jelent: „szárnyára bocsát”?", "s": "Szólások", "w": ["Madarat enged szabadon.", "Repülni tanít egy fiókát.", "Szélnek ereszti a lovakat."]},
  {"a": "Ijedtében elhallgat.", "p": "Mit jelent: „torkára forr a szó”?", "s": "Szólások", "w": ["Megfájdul a torka.", "Forró teát iszik.", "Megégeti a száját az étel."]},
  {"a": "Nincs kedve hozzá.", "p": "Mit jelent: „nem fűlik hozzá a foga”?", "s": "Szólások", "w": ["Fáj a foga.", "Nem szereti a meleg ételt.", "Fogorvoshoz kell mennie."]},
  {"a": "Örömmel elfogadja.", "p": "Mit jelent: „kapva kap rajta”?", "s": "Szólások", "w": ["Elkapja a labdát.", "Kapát vesz a kezébe.", "Gyorsan megfogja a kezét."]},
  {"a": "Röviden összefoglalva.", "p": "Mit jelent: „egy szó mint száz”?", "s": "Szólások", "w": ["Százszor elmondja ugyanazt.", "Sokat beszél hiába.", "Egy szót sem szól többet."]},
  {"a": "Gyémánt félkrajcárt", "p": "Mit talált a kiskakas a szemétdombon?", "s": "Népmesék", "w": ["Egy fényes rézgombot", "Aranygyűrűt", "Ezüstpénzt"]},
  {"a": "A török császár", "p": "Ki vette el a kiskakas kincsét?", "s": "Népmesék", "w": ["A gonosz szomszéd", "A falu bírója", "A vándor katona"]},
  {"a": "A begyébe", "p": "Mibe szívta fel a kiskakas a vizet?", "s": "Népmesék", "w": ["A szárnyába", "A csőrébe", "A tolla alá"]},
  {"a": "A kútba", "p": "Hová dobatta a császár a kiskakast először?", "s": "Népmesék", "w": ["A tóba", "A folyóba", "A kemencébe"]},
  {"a": "Szídd fel, begyem, a vizet!", "p": "Mit mondott a kiskakas a kútban?", "s": "Népmesék", "w": ["Ereszd ki, begyem, a vizet!", "Szídd fel, begyem, a méheket!", "Ereszd ki, begyem, a méheket!"]},
  {"a": "Méhekkel", "p": "Mivel csípette meg a kiskakas a császárt?", "s": "Népmesék", "w": ["Darazsakkal", "Hangyákkal", "Szúnyogokkal"]},
  {"a": "A császár kincsét", "p": "Mit szerzett meg végül a kiskakas?", "s": "Népmesék", "w": ["Egy szép házat", "Egy zsák aranyat", "A császár lovát és kocsiját"]},
  {"a": "Kiskakas", "p": "Milyen állat a gyémánt félkrajcár mesehőse?", "s": "Népmesék", "w": ["Kismalac", "Kisliba", "Kiscsirke"]},
  {"a": "Egy kőből", "p": "Miből főzött levest a furfangos vándor?", "s": "Népmesék", "w": ["Egy csontból", "Egy fadarabból", "Egy marék lisztből"]},
  {"a": "A követ", "p": "Mit tett a vándor a fazékba legelőször?", "s": "Népmesék", "w": ["A sót", "A húst", "A zsírt és a hagymát"]},
  {"a": "Sót, zsírt, húst", "p": "Mit adott az asszony sorra a kőleveshez?", "s": "Népmesék", "w": ["Csak hideg vizet", "Kenyeret, bort és kalácsot", "Semmit sem adott"]},
  {"a": "A furfang többre visz.", "p": "Mi a kőleves meséjének tanulsága?", "s": "Népmesék", "w": ["Az éhes ember mindent megeszik.", "A kő megízesíti a levest.", "Vendéget mindig kell várni."]},
  {"a": "Egy paszuly", "p": "Mi nőtt az égig a mesében?", "s": "Népmesék", "w": ["Egy kukoricaszár", "Egy napraforgó", "Egy tölgyfa"]},
  {"a": "Felmászott a paszulyon.", "p": "Hogyan jutott fel a fiú az égbe?", "s": "Népmesék", "w": ["Madár vitte fel a hátán.", "Létrát állított a hegyre.", "Sárkány repítette fel."]},
  {"a": "A bab", "p": "Melyik növény az égig érő paszuly?", "s": "Népmesék", "w": ["A borsó", "A lencse", "A csicseriborsó"]},
  {"a": "A sóhoz", "p": "Mihez hasonlította a legkisebb királylány a szeretetét?", "s": "Népmesék", "w": ["A mézhez", "Az aranyhoz", "A napfényhez"]},
  {"a": "Mert sóhoz hasonlította.", "p": "Miért haragudott meg a király a legkisebb lányára?", "s": "Népmesék", "w": ["Mert nem akart férjhez menni.", "Mert elszökött a palotából.", "Mert nem szerette az apját."]},
  {"a": "Elzavarta a palotából.", "p": "Mit tett a király a legkisebb lányával?", "s": "Népmesék", "w": ["Bezárta a toronyba.", "Férjhez adta a szomszédba.", "Megbocsátott neki azonnal."]},
  {"a": "Só nélkül főzetett ebédet.", "p": "Hogyan bizonyította igazát a király lánya?", "s": "Népmesék", "w": ["Sok sót tett az ételbe.", "Levelet írt az apjának.", "Elmondta a bánatát a népnek."]},
  {"a": "A só nagyon értékes.", "p": "Mit tanult meg a király a só meséjében?", "s": "Népmesék", "w": ["Az arany a fontos.", "A lányok mind hálátlanok.", "A szakácsok sokat hibáznak."]},
  {"a": "Három", "p": "Hány lánya volt a királynak a só meséjében?", "s": "Népmesék", "w": ["Kettő", "Négy", "Hét lánya volt"]},
  {"a": "Egy fehér ló", "p": "Ki volt Fehérlófia anyja?", "s": "Népmesék", "w": ["Egy szegény asszony", "Egy tündér", "Egy vasorrú bába"]},
  {"a": "Fanyűvő, Kőmorzsoló, Vasgyúró", "p": "Hogy hívták Fehérlófia három társát?", "s": "Népmesék", "w": ["Favágó, Kőmorzsoló, Vashajlító", "Fanyűvő, Kőfaragó, Vaskovács", "Fanyűvő, Kőhajító, Vasverő"]},
  {"a": "Az alvilágba", "p": "Hová ereszkedett le Fehérlófia?", "s": "Népmesék", "w": ["A tenger mélyére", "Egy barlangba", "A királyi pincébe"]},
  {"a": "A sárkányokat", "p": "Kiket győzött le Fehérlófia odalent?", "s": "Népmesék", "w": ["Az óriásokat", "A boszorkányokat", "A rablóvezéreket"]},
  {"a": "Egy griffmadár", "p": "Mi vitte fel Fehérlófiát a föld színére?", "s": "Népmesék", "w": ["Egy táltos paripa", "Egy nagy sas", "Egy hosszú kötél"]},
  {"a": "A saját húsával", "p": "Mivel etette Fehérlófia a griffmadarat?", "s": "Népmesék", "w": ["Kenyérrel és borral", "Gyümölccsel és vízzel", "Bárányhússal"]},
  {"a": "Beszorította a szakállát.", "p": "Hogyan fogta meg Fehérlófia a szakállas kis embert?", "s": "Népmesék", "w": ["Kötéllel megkötözte.", "Csapdát ásott neki.", "Lóháton üldözte a nagy erdőn."]},
  {"a": "A padláson", "p": "Hol lógott a kis gömböc?", "s": "Népmesék", "w": ["A kamrában", "A kéményben", "A konyha sarkában"]},
  {"a": "Mindenkit lenyelt.", "p": "Mit csinált a kis gömböc?", "s": "Népmesék", "w": ["Mindig énekelt.", "Elgurult a faluból.", "Sok ételt készített."]},
  {"a": "Csikótojásnak", "p": "Minek nézték a rátótiak a tököt?", "s": "Népmesék", "w": ["Nagy káposztafejnek", "Dinnyének", "Nagy kőnek"]},
  {"a": "Ráültek, hogy kikeljen.", "p": "Mit csináltak a rátótiak a tökkel?", "s": "Népmesék", "w": ["Megették vacsorára.", "Eladták a vásárban.", "Elgurították a patakhoz."]},
  {"a": "Egy nyúl", "p": "Mi ugrott ki a bokorból Rátóton?", "s": "Népmesék", "w": ["Egy róka", "Egy őz", "Egy kiscsikó"]},
  {"a": "Hármat", "p": "Hány kívánságot kapott a szegény ember?", "s": "Népmesék", "w": ["Kettőt", "Egyet", "Hetet kapott"]},
  {"a": "Egy szál kolbász", "p": "Mi volt a szegény ember első kívánsága?", "s": "Népmesék", "w": ["Egy zsák arany", "Egy szép ház", "Egy nagy darab hús"]},
  {"a": "Az asszony orrára", "p": "Hová nőtt oda a kívánt kolbász?", "s": "Népmesék", "w": ["A férfi fejére", "Az asztal közepére", "A ház tetejére"]},
  {"a": "Hogy a kolbász lejöjjön.", "p": "Mire kellett a harmadik kívánság?", "s": "Népmesék", "w": ["Hogy gazdagok legyenek.", "Hogy új házuk legyen.", "Hogy sok ételük legyen télre."]},
  {"a": "Akkora, mint egy babszem", "p": "Mekkora volt Babszem Jankó?", "s": "Népmesék", "w": ["Akkora, mint egy hordó", "Akkora, mint egy ház", "Akkora, mint egy nagy ökör"]},
  {"a": "A kis termetéről", "p": "Miről kapta a nevét Babszem Jankó?", "s": "Népmesék", "w": ["A bátorságáról", "Az okosságáról", "A szüleinek nevéről"]},
  {"a": "Terülj, terülj, asztalkám!", "p": "Mit mondtak a varázsasztalnak?", "s": "Népmesék", "w": ["Nyílj ki, nyílj ki, asztalkám!", "Fordulj, fordulj, asztalkám!", "Teríts meg, teríts meg, asztal!"]},
  {"a": "Megtelt étellel az asztal.", "p": "Mi történt a varázsszó után?", "s": "Népmesék", "w": ["Elrepült az asztal.", "Eltűnt a ház a szem elől.", "Aranypénz hullott a földre."]},
  {"a": "Hozzáragadt.", "p": "Mi történt azzal, aki hozzáért az aranyszőrű bárányhoz?", "s": "Népmesék", "w": ["Gazdag lett.", "Elaludt azonnal.", "Aranyat talált a zsebében."]},
  {"a": "Megnevettette a királylányt.", "p": "Mit ért el a fiú az aranyszőrű báránnyal?", "s": "Népmesék", "w": ["Meggyógyította a királyt.", "Megnyerte a nagy versenyt.", "Elnyerte a fele királyságot is."]},
  {"a": "Értette az állatok szavát.", "p": "Mi volt a juhász titka az egyik mesében?", "s": "Népmesék", "w": ["Látta a jövőt álmában.", "Aranyat tudott csinálni.", "Repülni tudott a levegőben."]},
  {"a": "Mert meghalt volna.", "p": "Miért hallgatott az állatok nyelvét értő juhász?", "s": "Népmesék", "w": ["Mert félt a királytól.", "Mert néma volt.", "Mert nem hitték volna el."]},
  {"a": "Egy macska", "p": "Milyen állat volt Kacor király?", "s": "Népmesék", "w": ["Egy kakas", "Egy kutya", "Egy kisegér"]},
  {"a": "Az erdő állatait", "p": "Kiket ijesztett meg Kacor király?", "s": "Népmesék", "w": ["A falusiakat", "A katonákat", "A vásári kereskedőket"]},
  {"a": "Az aranyalmákat", "p": "Mit loptak el éjszakánként Árgyélus kertjéből?", "s": "Népmesék", "w": ["Az aranyszőrű bárányt", "A szép virágokat", "A kincseket"]},
  {"a": "Tündérszép Ilona", "p": "Ki volt Árgyélus királyfi szerelme?", "s": "Népmesék", "w": ["Világszép Nádszálkisasszony", "A vasorrú bába", "A hétfejű sárkány"]},
  {"a": "Egy nádszálban", "p": "Hol rejtőzött Világszép Nádszálkisasszony?", "s": "Népmesék", "w": ["Egy üveghegyben", "Egy toronyban", "Egy nagy tóban"]},
  {"a": "Az örök életet", "p": "Mit keresett a halhatatlanságra vágyó királyfi?", "s": "Népmesék", "w": ["A hétfejű sárkányt", "Az apja kincsét", "A tündérek országát"]},
  {"a": "Három", "p": "Hány fia van rendszerint a mesebeli szegény embernek?", "s": "Népmesék", "w": ["Kettő", "Hét", "Tizenkettő"]},
  {"a": "A legkisebb", "p": "Melyik fiú jár szerencsével a magyar mesékben?", "s": "Népmesék", "w": ["A legidősebb", "A középső", "A legerősebb"]},
  {"a": "Hármat", "p": "Hány próbát kell a mesehősnek kiállnia?", "s": "Népmesék", "w": ["Kettőt", "Ötöt", "Hetet vagy nyolcat"]},
  {"a": "Kacsalábon", "p": "Min forog a mesebeli vár?", "s": "Népmesék", "w": ["Aranyoszlopon", "Kerékagyon", "Üveggömbön"]},
  {"a": "Nagyot lehet vele lépni.", "p": "Mire jó a hétmérföldes csizma?", "s": "Népmesék", "w": ["Melegen tartja a lábat.", "Vízen is lehet benne járni.", "Szebbé teszi a viselőjét."]},
  {"a": "Az élet vizét", "p": "Mit hoz a mesehős a beteg királynak?", "s": "Népmesék", "w": ["Az arany almát", "A tündérek kincsét", "A sárkány fogát"]},
  {"a": "Álruhában", "p": "Hogyan járt Mátyás király a nép között?", "s": "Mátyás-mondák", "w": ["Díszes hintón", "Katonákkal", "Lóháton, koronával"]},
  {"a": "oda az igazság", "p": "Fejezze be: „Meghalt Mátyás, …”", "s": "Mátyás-mondák", "w": ["oda a jó világ", "vége a békének", "elveszett az ország"]},
  {"a": "Az igazságos", "p": "Milyen jelzővel emlegetik Mátyás királyt?", "s": "Mátyás-mondák", "w": ["A bölcs", "A hódító", "A győzhetetlen"]},
  {"a": "Kecskén", "p": "Min érkezett az okos lány a királyhoz?", "s": "Mátyás-mondák", "w": ["Szamáron", "Lovon", "Ökrös szekéren"]},
  {"a": "Halászhálóba", "p": "Mibe burkolózott az okos lány?", "s": "Mátyás-mondák", "w": ["Szőnyegbe", "Báránybőrbe", "Fehér lepedőbe"]},
  {"a": "Két galambot", "p": "Milyen ajándékot vitt az okos lány?", "s": "Mátyás-mondák", "w": ["Egy kosár almát", "Egy szép kendőt", "Egy zsák búzát"]},
  {"a": "Elrepült", "p": "Mi történt az okos lány ajándékával?", "s": "Mátyás-mondák", "w": ["Megszökött a kosárból", "Elaludt", "A király megette"]},
  {"a": "Se felöltözve, se meztelenül", "p": "Hogyan kellett az okos lánynak öltöznie?", "s": "Mátyás-mondák", "w": ["Csak fehér ruhában", "A legszebb ünneplő ruhában", "Se szegényen, se gazdagon öltözve"]},
  {"a": "Ajándékot", "p": "Mit kellett az okos lánynak hoznia is, meg nem is?", "s": "Mátyás-mondák", "w": ["Kenyeret", "Bort és kalácsot", "Egy szép ruhát"]},
  {"a": "Mátyás király", "p": "Ki lett az okos lány férje a mondában?", "s": "Mátyás-mondák", "w": ["A falu bírója", "Egy gazdag kereskedő", "Egy vitéz katona"]},
  {"a": "Fát vágott.", "p": "Mit tett Mátyás a kolozsvári bíró udvarán?", "s": "Mátyás-mondák", "w": ["Vacsorát főzött.", "Lovat patkolt.", "Tüzet gyújtott."]},
  {"a": "Budán", "p": "Hol volt a mondabeli híres kutyavásár?", "s": "Mátyás-mondák", "w": ["Pesten", "Szegeden", "Debrecenben"]},
  {"a": "Ami elmúlt, nem jön vissza.", "p": "Mit jelent: „Egyszer volt Budán kutyavásár”?", "s": "Mátyás-mondák", "w": ["Sok kutyát árulnak a piacon.", "Budán olcsó volt a vásár.", "Minden évben van egy vásár."]},
  {"a": "Mert igazságos volt.", "p": "Miért szerette a nép Mátyás királyt?", "s": "Mátyás-mondák", "w": ["Mert sok háborút nyert.", "Mert nagyon gazdag volt.", "Mert szép palotát épített."]},
  {"a": "Egyszer volt, hol nem volt…", "p": "Hogyan kezdődik a legtöbb magyar népmese?", "s": "Mesei fordulatok", "w": ["Réges-régen, messzi földön…", "Élt egyszer egy messzi országban…", "Volt egyszer egy nagy király…"]},
  {"a": "Hol volt, hol nem volt…", "p": "Melyik a mese régi kezdő formulája?", "s": "Mesei fordulatok", "w": ["Messze földön, régen…", "Volt egyszer egy nagy erdő…", "Élt egyszer egy jó király…"]},
  {"a": "Itt a vége, fuss el véle!", "p": "Hogyan végződik sok magyar népmese?", "s": "Mesei fordulatok", "w": ["Így volt, vége volt, igaz volt.", "Ennyi volt, nincsen tovább.", "Vége a szép történetnek."]},
  {"a": "míg meg nem haltak", "p": "Fejezze be: „Boldogan éltek, …”", "s": "Mesei fordulatok", "w": ["amíg éltek a földön", "és soha nem búsultak", "és sok gyerekük lett"]},
  {"a": "járjon utána", "p": "Fejezze be: „Aki nem hiszi, …”", "s": "Mesei fordulatok", "w": ["kérdezze meg", "menjen oda el", "nézzen a szemembe"]},
  {"a": "ha meg nem haltak", "p": "Fejezze be: „Még ma is élnek, …”", "s": "Mesei fordulatok", "w": ["ha el nem mentek", "boldogságban élnek", "ha jól emlékszem rá"]},
  {"a": "Az Óperenciás-tengeren túl", "p": "Hol van a mesebeli messzi ország?", "s": "Mesei fordulatok", "w": ["A nagy hegyek mögött", "A folyó másik partján", "Az égig érő fa legtetején túl"]},
  {"a": "Nagyon messzi vidék.", "p": "Mit jelent a mesében a „hetedhét ország”?", "s": "Mesei fordulatok", "w": ["Hét szomszédos falu.", "A király hét tartománya.", "Hét nap járóföld gyalog."]},
  {"a": "Nehezen járható hegy.", "p": "Mi az üveghegy a mesékben?", "s": "Mesei fordulatok", "w": ["Kristályból csiszolt palota.", "Az üvegfúvók faluja.", "Egy nagy tó közepe."]},
  {"a": "Parazsat", "p": "Mit eszik a táltos ló?", "s": "Mesei fordulatok", "w": ["Zabot", "Szénát", "Aranyalmát"]},
  {"a": "Rút, sovány gebe", "p": "Milyennek látszik a táltos ló először?", "s": "Mesei fordulatok", "w": ["Szép aranyszőrű ló", "Fekete csődör", "Kicsi, szürke csikó"]},
  {"a": "Úgy menjen-e, mint a gondolat?", "p": "Mit kérdez a táltos ló a gazdájától?", "s": "Mesei fordulatok", "w": ["Mennyi abrakot kapjon az úton?", "Merre keressék a sárkány várát?", "Meddig tart még a hosszú út?"]},
  {"a": "Vándorló diák", "p": "Ki a garabonciás?", "s": "Mesei fordulatok", "w": ["A király szolgája", "Falusi tanító", "Kovácsmester"]},
  {"a": "Sárkányon", "p": "Min lovagol a garabonciás?", "s": "Mesei fordulatok", "w": ["Seprűnyélen", "Táltos lovon", "Viharfelhőn"]},
  {"a": "Tejet", "p": "Mit kér a garabonciás a háziaktól?", "s": "Mesei fordulatok", "w": ["Kenyeret", "Bort", "Pénzt és ruhát"]},
  {"a": "A hétfejű", "p": "Melyik sárkány szerepel a legtöbb mesében?", "s": "Mesei fordulatok", "w": ["A kétfejű", "A tízfejű", "A húszfejű sárkány"]},
  {"a": "A királykisasszonyt", "p": "Kit rabol el a sárkány a mesékben?", "s": "Mesei fordulatok", "w": ["A szegény ember fiát", "A juhász nyáját", "A falu bíróját"]},
  {"a": "Seprűnyélen", "p": "Min repül a mesebeli boszorkány?", "s": "Mesei fordulatok", "w": ["Sárkányháton", "Szélben szállva", "Nagy fekete madáron"]},
  {"a": "Gonosz boszorkány", "p": "Ki a vasorrú bába?", "s": "Mesei fordulatok", "w": ["Öreg falusi asszony", "Kovácsmester felesége", "Bába a szülés mellett"]},
  {"a": "Öreganyám", "p": "Hogyan szólítja a hős a vasorrú bábát?", "s": "Mesei fordulatok", "w": ["Jó asszony", "Nagyságos úrnő", "Kedves nénike"]},
  {"a": "Fele királyságot", "p": "Mit kap a hős a mese végén?", "s": "Mesei fordulatok", "w": ["Egy szép házat", "Egy nagy darab földet", "Egy zsák aranyat"]},
  {"a": "Tündér Ilona", "p": "Ki a tündérek királynője a magyar mesékben?", "s": "Mesei fordulatok", "w": ["Vasorrú bába", "Nádszálkisasszony", "Aranyhajú Julcsa"]},
  {"a": "Hipp-hopp, ott legyek, ahol akarok!", "p": "Mi a mesehős varázsigéje?", "s": "Mesei fordulatok", "w": ["Szél, szél, vigyél el, ahova akarom!", "Repülj, repülj, szép szőnyegem!", "Nyílj ki, nagy hegy, ereszd be!"]},
  {"a": "Életre kelti a halottat.", "p": "Mit tesz a mesebeli élő víz?", "s": "Mesei fordulatok", "w": ["Frissen fakadt forrásvíz.", "Sosem fagy be télen sem.", "Gyógyítja a beteg állatot."]},
  {"a": "A griffmadár", "p": "Milyen madár segíti a hőst az alvilágból?", "s": "Mesei fordulatok", "w": ["A táltos sas", "A fehér galamb", "A holló és a varjú"]},
  {"a": "Hét országra szólót", "p": "Milyen lakodalmat csaptak a mese végén?", "s": "Mesei fordulatok", "w": ["Három napig tartót", "Csendes, kicsi lakodalmat", "Egy egész évig tartót"]},
  {"a": "Fanyűvő", "p": "Ki tépi ki a fákat a mesében?", "s": "Mesei fordulatok", "w": ["Kőmorzsoló", "Vasgyúró", "Vashegyi vitéz"]},
  {"a": "Kőmorzsoló", "p": "Ki morzsolja a követ a mesében?", "s": "Mesei fordulatok", "w": ["Fanyűvő", "Vasgyúró", "Hegyhengergető"]},
  {"a": "Nagy füllentés.", "p": "Mit jelent: „mese habbal”?", "s": "Mesei fordulatok", "w": ["Habos torta.", "Gyerekeknek szóló könyv.", "Esti mese lefekvés előtt."]},
  {"a": "A dió", "p": "Kívül kerek, belül kerek, mégis négyen laknak benne.", "s": "Találós kérdések", "w": ["A mogyoró", "Az alma", "A tojás"]},
  {"a": "A fa", "p": "Nyáron ruhát ölt, télen levetkőzik.", "s": "Találós kérdések", "w": ["A hegy", "A folyó", "A szél"]},
  {"a": "A tűz", "p": "Ha eszik, él; ha iszik, meghal.", "s": "Találós kérdések", "w": ["A hal", "A madár", "A virág"]},
  {"a": "A tojás", "p": "Egy hordóban kétféle bor, mégsem keveredik.", "s": "Találós kérdések", "w": ["A dió", "A kút", "A boroshordó"]},
  {"a": "Az év", "p": "Van egy fa, tizenkét ága, minden ágon négy fészek.", "s": "Találós kérdések", "w": ["A hét", "A nap", "Az öreg tölgyfa"]},
  {"a": "A gödör", "p": "Minél többet vesznek el belőle, annál nagyobb lesz.", "s": "Találós kérdések", "w": ["A hegy", "A kenyér", "A búzaföld"]},
  {"a": "A gyertya", "p": "Minél tovább áll, annál rövidebb lesz.", "s": "Találós kérdések", "w": ["A fa", "Az árnyék", "A hosszú kötél"]},
  {"a": "Az óra", "p": "Éjjel-nappal jár, mégsem mozdul el a helyéről.", "s": "Találós kérdések", "w": ["A szél", "A folyó", "A vándormadár"]},
  {"a": "A fésű", "p": "Fogai vannak, mégsem harap.", "s": "Találós kérdések", "w": ["A kefe", "A kanál", "A kalapács"]},
  {"a": "A krumpli", "p": "Van szeme, de nem lát.", "s": "Találós kérdések", "w": ["A gomb", "A kulcs", "Az ablaküveg"]},
  {"a": "Az üveg", "p": "Van nyaka, de nincsen feje.", "s": "Találós kérdések", "w": ["A kanál", "A pohár", "A tányér"]},
  {"a": "A neved", "p": "A tiéd, mégis mások használják többet.", "s": "Találós kérdések", "w": ["A kezed", "A házad", "A jó ruhád"]},
  {"a": "A víz", "p": "Mennél többet mosod, annál piszkosabb lesz.", "s": "Találós kérdések", "w": ["A kéz", "A ruha", "A konyharuha"]},
  {"a": "Az ember", "p": "Reggel négy lábon, délben kettőn, este hármon jár.", "s": "Találós kérdések", "w": ["A macska", "A ló", "Az öreg kutya"]},
  {"a": "A fenyő", "p": "Télen-nyáron zöld a ruhája.", "s": "Találós kérdések", "w": ["A tölgy", "A nyírfa", "A szilva"]},
  {"a": "A lépcső", "p": "Fel is megy, le is megy, mégis egy helyben marad.", "s": "Találós kérdések", "w": ["A madár", "A felhő", "A hegyi ösvény"]},
  {"a": "Az írás", "p": "Fehér mező, fekete a vetés.", "s": "Találós kérdések", "w": ["A kenyér", "A havas rét", "A szántóföld"]},
  {"a": "A cukor", "p": "Fehér, mint a hó; édes, mint a méz.", "s": "Találós kérdések", "w": ["A tej", "A liszt", "A méhek méze"]},
  {"a": "A madár", "p": "Tolla van, mégsem ír vele senki.", "s": "Találós kérdések", "w": ["A párna", "A kalap", "A tintatartó"]},
  {"a": "Az út", "p": "Hegyen-völgyön átmegy, mégsem mozdul.", "s": "Találós kérdések", "w": ["A szél", "A folyó", "A vasúti sín"]},
  {"a": "A holnap", "p": "Mindig jön, de sohasem érkezik meg.", "s": "Találós kérdések", "w": ["A vonat", "A posta", "A nyári eső"]},
  {"a": "A csend", "p": "Ha kimondod, abban a percben megszűnik.", "s": "Találós kérdések", "w": ["A szó", "A titok", "A hosszú hallgatás"]}
]
$questions$::jsonb)
  with ordinality as question(item, ordinality);

do $validation$
begin
  if (
    select count(*) from public.quiz_questions
    where category_id = 'magyar_nepmesek' and is_active
  ) <> 322 then
    raise exception 'Népmesék és közmondások must contain exactly 322 active questions';
  end if;

  if exists (
    select 1
    from public.quiz_questions as question
    where question.category_id = 'magyar_nepmesek'
      and (
        cardinality(question.wrong_answers) <> 3
        or (
          select count(distinct lower(trim(answer)))
          from unnest(question.wrong_answers) as answer
        ) <> 3
        or exists (
          select 1
          from unnest(question.wrong_answers) as answer
          where lower(trim(answer)) = lower(trim(question.correct_answer))
        )
      )
  ) then
    raise exception 'Népmesék és közmondások: every question needs three distinct wrong answers';
  end if;

  if exists (
    select 1
    from public.quiz_questions as proposed
    join public.quiz_questions as existing
      on lower(trim(existing.prompt)) = lower(trim(proposed.prompt))
     and existing.id <> proposed.id
    where proposed.category_id = 'magyar_nepmesek'
  ) then
    raise exception 'Népmesék és közmondások: a prompt is already used by another question';
  end if;
end;
$validation$;
