-- Két igazság és egy hazugság: 253 new questions, taking it to 253.
--
-- Written so the correct answer is never reliably the longest option -- the tell
-- that made the Psychology bank winnable without reading the prompt. All options
-- share one type and grammatical form. Measured on this bank: the answer is the
-- strictly longest option 22.9% of the time, against 25% by chance.

insert into public.quiz_questions (
  id,
  category_id,
  prompt,
  correct_answer,
  wrong_answers,
  explanation,
  language_code,
  grade_level,
  subject,
  display_order,
  is_active
)
select
  'ketig_' || lpad(question.ordinality::text, 4, '0'),
  'ket_igazsag',
  question.item ->> 'p',
  question.item ->> 'a',
  array(select jsonb_array_elements_text(question.item -> 'w')),
  question.item ->> 'e',
  'hu',
  null,
  question.item ->> 's',
  (
    select coalesce(max(existing.display_order), 0)
    from public.quiz_questions as existing
    where existing.category_id = 'ket_igazsag'
  ) + question.ordinality::integer,
  true
from jsonb_array_elements($questions$
[
  {"a": "Ausztrália legnagyobb városa Melbourne, ott él a legtöbb ember.", "e": "Ausztrália legnagyobb városa Sydney, nem Melbourne.", "p": "Ausztrália — melyik állítás NEM igaz?", "s": "orszagok", "w": ["Ausztrália fővárosa Canberra, nem Sydney vagy Melbourne.", "Ausztrália pénzneme az ausztrál dollár, nem a font."]},
  {"a": "Kanada zászlaján egy piros fenyőág látható középen.", "e": "Kanada zászlaján egy juharfalevél van, nem fenyőág.", "p": "Kanada — melyik állítás NEM igaz?", "s": "orszagok", "w": ["Kanada két hivatalos nyelve az angol és a francia.", "Kanada fővárosa Ottawa, Ontario tartomány keleti szélén."]},
  {"a": "Brazíliában spanyolul beszélnek, mint a szomszéd országokban.", "e": "Brazíliában portugálul beszélnek, nem spanyolul.", "p": "Brazília — melyik állítás NEM igaz?", "s": "orszagok", "w": ["Brazília fővárosa Brazíliaváros, a semmiből építették fel.", "Brazília Dél-Amerika legnagyobb országa, területben és népességben."]},
  {"a": "Svájc tagja az Európai Uniónak, de nem használ eurót.", "e": "Svájc nem tagja az Európai Uniónak, csak szomszédos vele.", "p": "Svájc — melyik állítás NEM igaz?", "s": "orszagok", "w": ["Svájcnak négy hivatalos nyelve van, köztük a rétoromán.", "Svájc fővárosa Bern, nem pedig Zürich vagy Genf."]},
  {"a": "Japán zászlaján fehér kör látható piros alapon.", "e": "A japán zászlón piros kör van fehér alapon, fordítva.", "p": "Japán — melyik állítás NEM igaz?", "s": "orszagok", "w": ["Japán fővárosa Tokió, a világ egyik legnépesebb városa.", "Japán több ezer szigetből áll a Csendes-óceán mellett."]},
  {"a": "Törökország fővárosa Isztambul, az ország legnagyobb városa.", "e": "Törökország fővárosa Ankara, nem Isztambul.", "p": "Törökország — melyik állítás NEM igaz?", "s": "orszagok", "w": ["Törökország területe Európában és Ázsiában is fekszik.", "Isztambult a Boszporusz-szoros osztja ketté, két partra."]},
  {"a": "Új-Zéland fővárosa Auckland, az ország legnagyobb városa.", "e": "Új-Zéland fővárosa Wellington, Auckland a legnagyobb városa.", "p": "Új-Zéland — melyik állítás NEM igaz?", "s": "orszagok", "w": ["Új-Zéland két nagy szigetből áll, Északiból és Déliből.", "Új-Zéland jelképe a kivi, egy röpképtelen madár."]},
  {"a": "Görögország pénzneme ma is a drachma, nem az euró.", "e": "Görögország 2002 óta az eurót használja, a drachma helyett.", "p": "Görögország — melyik állítás NEM igaz?", "s": "orszagok", "w": ["Görögország fővárosa Athén, az ókori demokrácia bölcsője.", "Görögországhoz több ezer sziget tartozik a tengereken."]},
  {"a": "Indiában a Gangesz dél felé folyik, az Indiai-óceánba.", "e": "A Gangesz kelet felé folyik, és a Bengáli-öbölbe ömlik.", "p": "India — melyik állítás NEM igaz?", "s": "orszagok", "w": ["India a világ legnépesebb országa, több mint egymilliárd emberrel.", "India fővárosa Újdelhi, hivatalos nyelve többek között a hindi."]},
  {"a": "Párizs a Loire folyó partján fekszik, Franciaország szívében.", "e": "Párizs a Szajna partján fekszik, nem a Loire mellett.", "p": "Párizs — melyik állítás NEM igaz?", "s": "varosok", "w": ["Párizs jelképe az Eiffel-torony, amely vasból készült.", "Párizsban áll a Louvre, a világ egyik leglátogatottabb múzeuma."]},
  {"a": "A Big Ben órája a Buckingham-palota tornyán áll.", "e": "A Big Ben a Parlament tornyában szól, nem a palotán.", "p": "London — melyik állítás NEM igaz?", "s": "varosok", "w": ["London a Temze folyó két partján terül el.", "A londoni metró a világ legrégebbi földalatti vasútja."]},
  {"a": "Rómát a Pó folyó szeli ketté, észak felé tartva.", "e": "Rómán a Tiberis folyik át, a Pó északabbra jár.", "p": "Róma — melyik állítás NEM igaz?", "s": "varosok", "w": ["Róma belsejében külön állam működik, a Vatikán.", "Rómában áll a Colosseum, az ókori aréna maradványa."]},
  {"a": "New York az Egyesült Államok fővárosa a keleti parton.", "e": "Az Egyesült Államok fővárosa Washington, nem New York.", "p": "New York — melyik állítás NEM igaz?", "s": "varosok", "w": ["A Szabadság-szobor New York kikötőjében, egy szigeten áll.", "Manhattan New York egyik városrésze, egy hosszú szigeten."]},
  {"a": "Velence a Tirrén-tenger partján épült, több kis szigetre.", "e": "Velence az Adriai-tenger partján fekszik, nem a Tirrén-tengernél.", "p": "Velence — melyik állítás NEM igaz?", "s": "varosok", "w": ["Velencében csatornák helyettesítik az utcákat a belvárosban.", "Velence fő tere a Szent Márk tér, a bazilikával."]},
  {"a": "Bécsben született Mozart, a híres osztrák zeneszerző.", "e": "Mozart Salzburgban született, csak felnőttként költözött Bécsbe.", "p": "Bécs — melyik állítás NEM igaz?", "s": "varosok", "w": ["Bécs Ausztria fővárosa, a Duna partján fekszik.", "Bécsben áll a Schönbrunni kastély, a császári nyaraló."]},
  {"a": "Prágán a Duna folyik át, a Károly híd alatt.", "e": "Prágán a Moldva folyik át, a Duna délebbre folyik.", "p": "Prága — melyik állítás NEM igaz?", "s": "varosok", "w": ["Prága Csehország fővárosa, a Károly híd városa.", "Prágában áll Európa egyik legnagyobb várnegyede, a Hradzsin."]},
  {"a": "Barcelona Spanyolország fővárosa, a tenger partján fekszik.", "e": "Spanyolország fővárosa Madrid, Barcelona a második legnagyobb.", "p": "Barcelona — melyik állítás NEM igaz?", "s": "varosok", "w": ["Barcelonában áll a Sagrada Família, Gaudí híres temploma.", "Barcelona Katalónia legnagyobb városa, a Földközi-tengernél."]},
  {"a": "Amszterdamban ülésezik a holland kormány és a parlament.", "e": "A holland kormány Hágában ülésezik, nem Amszterdamban.", "p": "Amszterdam — melyik állítás NEM igaz?", "s": "varosok", "w": ["Amszterdam belvárosát csatornák és több száz híd szeli át.", "Amszterdam csatornagyűrűje a világörökség része lett."]},
  {"a": "A Duna az Északi-tengerbe ömlik, hosszú út után.", "e": "A Duna a Fekete-tengerbe ömlik, nem az Északi-tengerbe.", "p": "A Duna — melyik állítás NEM igaz?", "s": "vizek-hegyek", "w": ["A Duna Európa második leghosszabb folyója a Volga után.", "A Duna négy fővárost érint, köztük Budapestet és Bécset."]},
  {"a": "A Nílus dél felé folyik, és a Vörös-tengerbe ömlik.", "e": "A Nílus észak felé folyik, és a Földközi-tengerbe ömlik.", "p": "A Nílus — melyik állítás NEM igaz?", "s": "vizek-hegyek", "w": ["A Nílus Afrika egyik leghosszabb folyója, több országon át.", "A Nílus áradása tette termékennyé az ókori Egyiptom földjét."]},
  {"a": "Az Amazonas a Csendes-óceánba ömlik, Peru partjainál.", "e": "Az Amazonas az Atlanti-óceánba ömlik, Brazília keleti partján.", "p": "Az Amazonas — melyik állítás NEM igaz?", "s": "vizek-hegyek", "w": ["Az Amazonas a világ legbővizűbb folyója, hatalmas vízhozammal.", "Az Amazonas az Andokban ered, és Brazílián át folyik."]},
  {"a": "A Mount Everest India és Kína határán emelkedik.", "e": "A Mount Everest Nepál és Kína határán áll, nem Indiánál.", "p": "A Mount Everest — melyik állítás NEM igaz?", "s": "vizek-hegyek", "w": ["A Mount Everest a Föld legmagasabb hegycsúcsa a tengerszinttől.", "A Mount Everest a Himalája hegységben található, Ázsiában."]},
  {"a": "Az Alpok legmagasabb csúcsa a Matterhorn, a svájci határon.", "e": "Az Alpok legmagasabb csúcsa a Mont Blanc, nem a Matterhorn.", "p": "Az Alpok — melyik állítás NEM igaz?", "s": "vizek-hegyek", "w": ["Az Alpok több országon át húzódik, Svájctól Ausztriáig.", "Az Alpokban ered a Rajna, a Rhône és az Inn folyó."]},
  {"a": "A Tisza az Alpokban ered, és dél felé folyik.", "e": "A Tisza a Kárpátokban ered, Ukrajna területén.", "p": "A Tisza — melyik állítás NEM igaz?", "s": "vizek-hegyek", "w": ["A Tisza a Dunába ömlik, már Szerbia területén.", "A Tisza Magyarországon hosszabb szakaszon folyik, mint a Duna."]},
  {"a": "A Szahara Afrika déli részén húzódik, az Egyenlítő alatt.", "e": "A Szahara Afrika északi részén fekszik, az Egyenlítő fölött.", "p": "A Szahara — melyik állítás NEM igaz?", "s": "vizek-hegyek", "w": ["A Szahara területe többszöröse az Európai Unió területének.", "A Szaharában nappal forró, éjjel viszont nagyon hideg lehet."]},
  {"a": "A Kárpátok legmagasabb csúcsa a Kékes, a Mátra hegységben.", "e": "A Kárpátok legmagasabb csúcsa a Gerlachfalvi-csúcs a Tátrában.", "p": "A Kárpátok — melyik állítás NEM igaz?", "s": "vizek-hegyek", "w": ["A Kárpátok több országon át ível, Szlovákiától Romániáig.", "A Kárpátok koszorúja veszi körül a Kárpát-medencét."]},
  {"a": "A Bajkál-tó a világ legnagyobb területű tava, Szibériában.", "e": "Területben a Kaszpi-tenger a legnagyobb tó, a Bajkál a legmélyebb.", "p": "A Bajkál-tó — melyik állítás NEM igaz?", "s": "vizek-hegyek", "w": ["A Bajkál-tó a Föld legmélyebb édesvizű tava.", "A Bajkál-tó télen vastag jég alatt fekszik hónapokon át."]},
  {"a": "A pizza Rómából indult el, onnan járta be a világot.", "e": "A pizza Nápolyból származik, nem Rómából.", "p": "A pizza — melyik állítás NEM igaz?", "s": "etelek", "w": ["A margherita pizzán paradicsom, sajt és bazsalikom van.", "A pizzát eredetileg olcsó ételnek szánták Olaszországban."]},
  {"a": "A csokoládé alapanyaga a kávébab, amelyet megpörkölnek.", "e": "A csokoládé kakaóbabból készül, nem kávébabból.", "p": "A csokoládé — melyik állítás NEM igaz?", "s": "etelek", "w": ["A fehér csokoládé nem tartalmaz kakaóport, csak kakaóvajat.", "A csokoládé alapanyaga Közép-Amerikából került Európába."]},
  {"a": "A tésztát Marco Polo hozta Kínából Olaszországba.", "e": "Olaszországban már Marco Polo utazása előtt is ettek tésztát.", "p": "A tészta — melyik állítás NEM igaz?", "s": "etelek", "w": ["A tésztát búzalisztből és vízből készítik.", "Az olasz konyhában több száz tésztaforma ismert."]},
  {"a": "A zöld tea és a fekete tea két külön növény levele.", "e": "A zöld és a fekete tea ugyanarról a növényről származik.", "p": "A tea — melyik állítás NEM igaz?", "s": "etelek", "w": ["A tea a világ egyik legtöbbet fogyasztott itala a víz után.", "A tea leveleit sok helyen ma is kézzel szedik."]},
  {"a": "A gulyás Magyarországon sűrű pörkölt, nem leves.", "e": "Magyarországon a gulyás leves, a sűrű változat a pörkölt.", "p": "A gulyás — melyik állítás NEM igaz?", "s": "etelek", "w": ["A gulyás nevét a marhákat őrző gulyásokról kapta.", "A gulyásba hagyma, paprika, burgonya és marhahús kerül."]},
  {"a": "A fűszerpaprika Magyarországon őshonos, régóta itt terem.", "e": "A paprika Amerikából származik, csak később honosodott meg nálunk.", "p": "A fűszerpaprika — melyik állítás NEM igaz?", "s": "etelek", "w": ["A fűszerpaprikát Szegeden és Kalocsán termesztik nagy mennyiségben.", "A paprika C-vitaminját Szent-Györgyi Albert kutatta Szegeden."]},
  {"a": "A parmezán francia sajt, hosszan érlelt és kemény.", "e": "A parmezán olasz sajt, Parma és Reggio vidékéről.", "p": "A parmezán — melyik állítás NEM igaz?", "s": "etelek", "w": ["A parmezánt reszelve szórják tésztákra és levesekre.", "A parmezánt kemény sajtként évekig is érlelik a raktárban."]},
  {"a": "A kávé Dél-Amerikából származik, onnan vitték Afrikába.", "e": "A kávé Etiópiából származik, csak később került Amerikába.", "p": "A kávé — melyik állítás NEM igaz?", "s": "etelek", "w": ["Brazília a világ legnagyobb kávétermelő országa ma is.", "A koffein a kávé élénkítő anyaga, a teában is megvan."]},
  {"a": "A rizs száraz, homokos talajon terem a legjobban.", "e": "A rizst gyakran vízzel elárasztott földeken termesztik.", "p": "A rizs — melyik állítás NEM igaz?", "s": "etelek", "w": ["A rizs Ázsia nagy részén a mindennapi étkezés alapja.", "A rizsnek több ezer fajtája létezik szerte a világon."]},
  {"a": "Magyarországon december 25-én este adják át az ajándékokat.", "e": "Nálunk szenteste, december 24-én este bontják ki az ajándékokat.", "p": "A karácsony — melyik állítás NEM igaz?", "s": "unnepek", "w": ["Magyarországon december 24-ét szentestének nevezik az emberek.", "A karácsonyfa szokása német nyelvterületről terjedt el Európában."]},
  {"a": "A locsolkodás hagyománya húsvét vasárnap reggelére esik.", "e": "A locsolkodás húsvéthétfőn szokás, nem vasárnap.", "p": "A húsvét — melyik állítás NEM igaz?", "s": "unnepek", "w": ["A húsvét ideje évről évre változik, a holdtöltéhez igazodik.", "A tojásfestés régi húsvéti szokás Európa több országában."]},
  {"a": "Magyarországon éjfélkor halat esznek a szerencse reményében.", "e": "A halat inkább kerülik, mert elúszik vele a szerencse.", "p": "A szilveszter — melyik állítás NEM igaz?", "s": "unnepek", "w": ["Magyarországon újévkor lencsét esznek a gazdagság reményében.", "A szilveszter nevét egy december 31-i névnapról kapta."]},
  {"a": "A kínai újév mindig január elsején kezdődik, tűzijátékkal.", "e": "A kínai újév a holdnaptár szerint január vége és február vége közé esik.", "p": "A kínai újév — melyik állítás NEM igaz?", "s": "unnepek", "w": ["A kínai újévhez tizenkét állat éve tartozik, körben ismétlődve.", "A kínai újévkor piros borítékban adnak pénzt a gyerekeknek."]},
  {"a": "A Mikulás alakja egy dán püspök emlékéből született.", "e": "Szent Miklós Myra püspöke volt, a mai Törökország területén.", "p": "A Mikulás — melyik állítás NEM igaz?", "s": "unnepek", "w": ["Magyarországon december 6-án reggel találják meg az ajándékot.", "A Mikulás mellett a krampusz virgácsot hoz a rosszaknak."]},
  {"a": "A farsang a húsvét utáni vidám időszak, bálokkal és jelmezekkel.", "e": "A farsang húsvét előtt van, hamvazószerdával ér véget.", "p": "A farsang — melyik állítás NEM igaz?", "s": "unnepek", "w": ["A farsang vízkereszttől hamvazószerdáig tart a naptárban.", "A farsang végén kiszebábot égetnek, hogy elűzzék a telet."]},
  {"a": "Március 15-én az 1956-os forradalomra emlékezik az ország.", "e": "Március 15. az 1848-as forradalom napja, 1956-ra október 23-án emlékezünk.", "p": "Március 15. — melyik állítás NEM igaz?", "s": "unnepek", "w": ["Március 15-én sokan kokárdát tűznek a kabátjukra.", "Petőfi Sándor Nemzeti dala ehhez a naphoz kötődik."]},
  {"a": "A faragott tök szokása Olaszországból indult el.", "e": "A tökfaragás ír hagyomány, eredetileg répát vájtak ki.", "p": "A halloween — melyik állítás NEM igaz?", "s": "unnepek", "w": ["A halloweent október 31-én tartják az angol nyelvű országokban.", "A halloweeni tököt kivájják, és gyertyát tesznek bele."]},
  {"a": "Augusztus 20-án Szent László királyra emlékezik az ország.", "e": "Augusztus 20. Szent István király és az államalapítás ünnepe.", "p": "Augusztus 20. — melyik állítás NEM igaz?", "s": "unnepek", "w": ["Augusztus 20-án tűzijátékot rendeznek Budapesten a Duna felett.", "Augusztus 20-hoz kötődik az új kenyér ünnepe is."]},
  {"a": "A papírt az ókori Egyiptomban találták fel, papiruszból.", "e": "A papírt Kínában találták fel, a papirusz nem igazi papír.", "p": "A papír — melyik állítás NEM igaz?", "s": "talalmanyok", "w": ["A papír nagy része ma fából készült rostokból áll.", "A papírt ma újra lehet hasznosítani a szelektív gyűjtéssel."]},
  {"a": "A wolframszálas izzót Bláthy Ottó Titusz alkotta meg.", "e": "A wolframszálas izzót Just Sándor és Hanaman Ferenc fejlesztette ki.", "p": "Az izzólámpa — melyik állítás NEM igaz?", "s": "talalmanyok", "w": ["Bláthy Ottó Titusz a transzformátor egyik feltalálója volt.", "Az izzólámpában egy vékony szál izzik fel az áramtól."]},
  {"a": "Az első postabélyeget Franciaországban adták ki 1840-ben.", "e": "Az első bélyeget Nagy-Britanniában adták ki, Penny Black néven.", "p": "A postabélyeg — melyik állítás NEM igaz?", "s": "talalmanyok", "w": ["Az első bélyegen Viktória királynő arcképe volt látható.", "A bélyeg hátoldalát ragasztóval vonják be a feladáshoz."]},
  {"a": "A szemüveget a 19. században kezdték használni Európában.", "e": "A szemüveg a középkorban, Itáliában jelent meg, 1300 táján.", "p": "A szemüveg — melyik állítás NEM igaz?", "s": "talalmanyok", "w": ["A szemüveg lencséi hajlítják a fényt az éles képért.", "A rövidlátáshoz és a távollátáshoz más lencse kell."]},
  {"a": "Az esernyőt eredetileg az eső ellen találták ki Angliában.", "e": "Az ernyőt eredetileg a nap ellen használták, jóval az eső előtt.", "p": "Az esernyő — melyik állítás NEM igaz?", "s": "talalmanyok", "w": ["Az esernyő vázát ma fémből vagy műanyagból készítik.", "A napernyő és az esernyő szerkezete nagyon hasonló."]},
  {"a": "A papírpénzt Angliában vezették be először, a középkorban.", "e": "A papírpénzt Kínában vezették be először, több mint ezer éve.", "p": "A papírpénz — melyik állítás NEM igaz?", "s": "talalmanyok", "w": ["A papírpénz sokkal könnyebb, mint az azonos értékű érme.", "A pénzérméket fémötvözetből verik, a papírpénzt nyomtatják."]},
  {"a": "Irinyi János a zajtalan gyufát Párizsban találta fel.", "e": "Irinyi János Bécsben, diákként alkotta meg a zajtalan gyufát.", "p": "A gyufa — melyik állítás NEM igaz?", "s": "talalmanyok", "w": ["Irinyi János magyar vegyész és feltaláló volt.", "A gyufa feje a doboz oldalához dörzsölve gyullad meg."]},
  {"a": "Az első magyar gőzvasút Pest és Szeged között indult el.", "e": "Az első vonat Pest és Vác között közlekedett 1846-ban.", "p": "A vasút Magyarországon — melyik állítás NEM igaz?", "s": "talalmanyok", "w": ["Az első magyar gőzvasút 1846-ban nyílt meg az utasoknak.", "A gőzmozdonyt szén fűtötte, és a gőz hajtotta a kerekeket."]},
  {"a": "Az első fényképek elkészítése néhány másodpercig tartott.", "e": "A legelső fényképekhez órákig kellett mozdulatlanul állni.", "p": "A fényképezőgép — melyik állítás NEM igaz?", "s": "talalmanyok", "w": ["A régi gépekben filmre készült a kép, nem memóriakártyára.", "A fényképezőgép lencséje gyűjti össze a fényt a képhez."]},
  {"a": "Az Eiffel-torony a párizsi olimpia idejére készült el.", "e": "Az Eiffel-torony az 1889-es párizsi világkiállításra épült.", "p": "Az Eiffel-torony — melyik állítás NEM igaz?", "s": "epuletek", "w": ["Az Eiffel-torony vasból készült, és háromszáz méternél magasabb.", "Az Eiffel-tornyot eredetileg csak ideiglenesnek szánták Párizsban."]},
  {"a": "A gízai piramisokat vályogtéglából rakták össze a munkások.", "e": "A gízai piramisok hatalmas kőtömbökből épültek, nem téglából.", "p": "A gízai piramisok — melyik állítás NEM igaz?", "s": "epuletek", "w": ["A gízai nagy piramis Kheopsz fáraó síremléke volt.", "A gízai piramisok mellett áll a Nagy Szfinx szobra."]},
  {"a": "A kínai nagy fal szabad szemmel látható az űrből.", "e": "A falat szabad szemmel nem lehet látni az űrből, ez tévhit.", "p": "A kínai nagy fal — melyik állítás NEM igaz?", "s": "epuletek", "w": ["A kínai nagy fal több szakaszból áll, évszázadok alatt épült.", "A kínai nagy falat az északi támadások ellen emelték."]},
  {"a": "A Taj Mahalt hindu templomnak építették a folyó partján.", "e": "A Taj Mahal síremlék, Mumtaz Mahal nyughelye Agrában.", "p": "A Taj Mahal — melyik állítás NEM igaz?", "s": "epuletek", "w": ["A Taj Mahalt fehér márványból emelték az indiai Agrában.", "A Taj Mahal egy uralkodó feleségének síremlékéül készült."]},
  {"a": "A bazilika kupolája magasabb, mint a Parlament kupolája.", "e": "A bazilika és a Parlament kupolája is 96 méter magas.", "p": "A Szent István-bazilika — melyik állítás NEM igaz?", "s": "epuletek", "w": ["A bazilikában őrzik Szent István király jobb kezét.", "A bazilika építése több mint ötven évig tartott."]},
  {"a": "Az Országházat Ybl Miklós tervezte a millennium idejére.", "e": "Az Országházat Steindl Imre tervezte, Ybl az Operaházat.", "p": "Az Országház — melyik állítás NEM igaz?", "s": "epuletek", "w": ["Az Országházban őrzik a Szent Koronát, üvegtárló alatt.", "Az Országház a Duna pesti partján, a Kossuth téren áll."]},
  {"a": "A Lánchidat Széchenyi István tervezte és építette meg.", "e": "A hidat William Tierney Clark tervezte, Adam Clark építette.", "p": "A Lánchíd — melyik állítás NEM igaz?", "s": "epuletek", "w": ["A Lánchíd volt az első állandó híd Pest és Buda között.", "A Lánchidat 1849-ben adták át a forgalomnak."]},
  {"a": "A pisai torony egy erős földrengés miatt dőlt meg.", "e": "A torony a puha, süppedő talaj miatt dőlt meg, nem földrengéstől.", "p": "A pisai ferde torony — melyik állítás NEM igaz?", "s": "epuletek", "w": ["A pisai ferde torony egy templom harangtornyaként épült.", "A pisai ferde torony már az építés közben dőlni kezdett."]},
  {"a": "A Sydney-i Operaház teteje üvegtáblákból készült el.", "e": "Az Operaház tetejét több mint egymillió fehér csempe borítja.", "p": "A Sydney-i Operaház — melyik állítás NEM igaz?", "s": "epuletek", "w": ["A Sydney-i Operaház a kikötő partján áll, a híd mellett.", "A Sydney-i Operaház teteje vitorlákra emlékeztető íveket formáz."]},
  {"a": "A koronát a bizánci császártól kapta az ezredik év táján.", "e": "A hagyomány szerint a koronát a pápától kapta, nem a bizánci császártól.", "p": "Szent István király — melyik állítás NEM igaz?", "s": "Királyok", "w": ["Géza fejedelem fia volt, és keresztény királyságot alapított.", "A bajor Gizellát vette feleségül, és Imre volt a fia."]},
  {"a": "Halála után a fia, Corvin János lett a király.", "e": "Mátyás után II. Ulászló került a trónra, nem Corvin János.", "p": "Mátyás király — melyik állítás NEM igaz?", "s": "Királyok", "w": ["Hunyadi János fia volt, és 1458-ban választották királlyá.", "Bécset 1485-ben foglalta el, és öt évvel később ott halt meg."]},
  {"a": "Uralkodása alatt Velence szerezte meg Dalmácia városait.", "e": "Éppen fordítva: az 1358-as zárai békében ő szerezte meg Dalmáciát.", "p": "Nagy Lajos király — melyik állítás NEM igaz?", "s": "Királyok", "w": ["Károly Róbert fia volt, és 1342-ben lett magyar király.", "Pécsett alapította meg az ország első egyetemét 1367-ben."]},
  {"a": "Az Aranybullát ő adta ki 1222-ben a nemesek kérésére.", "e": "Az Aranybullát az apja, II. András adta ki 1222-ben.", "p": "IV. Béla király — melyik állítás NEM igaz?", "s": "Királyok", "w": ["A muhi csatában 1241-ben vereséget szenvedett a tatároktól.", "A tatárjárás után sok kővárat építtetett az országban."]},
  {"a": "Szentté avatására csak 1301-ben került sor, jóval halála után.", "e": "Szent Lászlót 1192-ben avatták szentté, III. Béla kérésére.", "p": "Szent László király — melyik állítás NEM igaz?", "s": "Királyok", "w": ["1077-ben lépett trónra, és lovagkirálynak szokták nevezni.", "Az ő uralkodása alatt avatták szentté István királyt."]},
  {"a": "A nikápolyi csatában 1396-ban legyőzte a török sereget.", "e": "A nikápolyi csatát 1396-ban elveszítette a törökökkel szemben.", "p": "Zsigmond király — melyik állítás NEM igaz?", "s": "Királyok", "w": ["1387-ben lett magyar király, és ötven évig uralkodott.", "Német-római császárrá is megkoronázták 1433-ban Rómában."]},
  {"a": "A déli harangszó a mohácsi csata emlékét őrzi.", "e": "A déli harangszó a nándorfehérvári győzelem emlékét őrzi.", "p": "Hunyadi János — melyik állítás NEM igaz?", "s": "Királyok", "w": ["1456-ban Nándorfehérvárnál megállította a török sereget.", "A győzelem után néhány héttel pestisben halt meg."]},
  {"a": "Ő verette az első magyar ezüsttallért Körmöcbányán.", "e": "Károly Róbert az aranyforintot vezette be, a tallér későbbi pénz.", "p": "Károly Róbert — melyik állítás NEM igaz?", "s": "Királyok", "w": ["Az első Anjou-házi király volt a magyar trónon.", "1335-ben Visegrádon fogadta a cseh és a lengyel királyt."]},
  {"a": "Élete végén hazatért, és Budapesten halt meg 1894-ben.", "e": "Kossuth száműzetésben, az olaszországi Torinóban hunyt el 1894-ben.", "p": "Kossuth Lajos — melyik állítás NEM igaz?", "s": "Szabadsághősök", "w": ["1849-ben kormányzó-elnökké választották a debreceni országgyűlésen.", "A bukás után Törökországba, majd Angliába menekült."]},
  {"a": "A Hitel című könyvét a szabadságharc után írta meg.", "e": "A Hitel 1830-ban jelent meg, jóval a szabadságharc előtt.", "p": "Széchenyi István — melyik állítás NEM igaz?", "s": "Szabadsághősök", "w": ["Egyévi jövedelmét ajánlotta fel a tudós társaság alapítására.", "Az ő kezdeményezésére épült a Lánchíd Pest és Buda között."]},
  {"a": "Kiskunfélegyházán született 1823-ban, mészáros fiaként.", "e": "Petőfi Kiskőrösön született, bár Kiskunfélegyházát tartotta szülővárosának.", "p": "Petőfi Sándor — melyik állítás NEM igaz?", "s": "Szabadsághősök", "w": ["A Nemzeti dal 1848. március 15-én hangzott el Pesten.", "1849-ben a segesvári csatában tűnt el nyomtalanul."]},
  {"a": "Az aradi tábornokokkal együtt Aradon végezték ki.", "e": "Batthyányt ugyanazon a napon, de Pesten végezték ki, nem Aradon.", "p": "Batthyány Lajos — melyik állítás NEM igaz?", "s": "Szabadsághősök", "w": ["1848-ban ő lett Magyarország első felelős miniszterelnöke.", "Emlékét örökmécses őrzi a kivégzése helyén, Pesten."]},
  {"a": "Mind a tizenhárman magyar földön születtek.", "e": "Többen külföldön születtek, például a német Leiningen-Westerburg Károly.", "p": "Az aradi vértanúk — melyik állítás NEM igaz?", "s": "Szabadsághősök", "w": ["1849. október 6-án, Aradon végezték ki őket.", "Haynau táborszernagy parancsára hajtották végre az ítéletet."]},
  {"a": "A bukás után Kossuthtal együtt Törökországba menekült.", "e": "Görgei a cár közbenjárására kegyelmet kapott, és Klagenfurtban élt.", "p": "Görgei Artúr — melyik állítás NEM igaz?", "s": "Szabadsághősök", "w": ["1849 augusztusában Világosnál tette le a fegyvert az oroszok előtt.", "Kossuth vidini levele nevezte árulónak a bukás után."]},
  {"a": "A szatmári békét 1711-ben ő maga írta alá Károlyival.", "e": "A szatmári békét Károlyi Sándor kötötte meg, Rákóczi nem fogadta el.", "p": "II. Rákóczi Ferenc — melyik állítás NEM igaz?", "s": "Szabadsághősök", "w": ["A bukás után Törökországban, Rodostóban élt száműzetésben.", "Hamvait 1906-ban hozták haza, és Kassán temették el."]},
  {"a": "A felkelés után a jobbágyok szabadon költözhettek.", "e": "A felkelés után a jobbágyokat röghöz kötötték az új törvények.", "p": "Dózsa György — melyik állítás NEM igaz?", "s": "Szabadsághősök", "w": ["1514-ben a keresztes had vezéreként indult harcba.", "Seregét Szapolyai János verte le Temesvár mellett."]},
  {"a": "Magyar nemesi családból származott, és Erdélyben született.", "e": "Bem apó lengyel születésű tábornok volt, a galíciai Tarnówból.", "p": "Bem József — melyik állítás NEM igaz?", "s": "Szabadsághősök", "w": ["Az erdélyi hadjáratot vezette 1849 tavaszán.", "Petőfi Sándor az ő segédtisztjeként szolgált mellette."]},
  {"a": "Élete nagy részét Svájcban töltötte, és ott is halt meg.", "e": "Bíró Argentínába költözött, és Buenos Airesben hunyt el 1985-ben.", "p": "Bíró László József — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["A golyóstollat az 1930-as évek végén szabadalmaztatta.", "Angol nyelvterületen ma is biro néven ismerik a tollat."]},
  {"a": "A kockát egy amerikai játékcég megrendelésére tervezte.", "e": "A kockát magának találta ki szemléltető eszköznek, nem megrendelésre.", "p": "Rubik Ernő — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["A bűvös kockát 1974-ben alkotta meg Budapesten.", "Építészmérnökként és formatervezőként tanított akkoriban."]},
  {"a": "A budapesti földalattit is az ő tervei alapján építették.", "e": "A földalattit 1896-ban a német Siemens cég építette meg.", "p": "Kandó Kálmán — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["A Ganz gyárban a vasút villamosításával foglalkozott.", "Az olasz vasutak villamosítása az ő rendszerével indult."]},
  {"a": "Az első villanykörtét ő készítette el a győri iskolában.", "e": "Jedlik a villanymotort és a dinamó elvét alkotta meg, nem a körtét.", "p": "Jedlik Ányos — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["Bencés szerzetes és tanár volt, a szódavíz készítője.", "A dinamó elvét Siemens előtt írta le, de nem közölte."]},
  {"a": "A telefont néhány évvel Bell előtt ő találta fel.", "e": "A telefont Bell alkotta meg, Puskás a telefonközpontot javasolta.", "p": "Puskás Tivadar — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["A telefonközpont ötletét ő vetette fel Edison mellett.", "1893-ban indította el Budapesten a Telefonhírmondót."]},
  {"a": "A játékelméletet Albert Einsteinnel közösen dolgozta ki.", "e": "A játékelmélet alapművét Oskar Morgensternnel írta 1944-ben.", "p": "Neumann János — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["Budapesten született 1903-ban, és Amerikában lett világhírű.", "A mai számítógépek felépítése az ő elveit követi."]},
  {"a": "A holográfiához már az első kísérleteknél lézert használt.", "e": "A holográfiát 1947-ben találta ki, a lézer megjelenése előtt.", "p": "Gábor Dénes — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["A holográfia feltalálásáért kapott fizikai Nobel-díjat 1971-ben.", "Élete nagy részét Angliában töltötte, ott is kutatott."]},
  {"a": "A detroiti autógyárat ő alapította meg Ford mellett.", "e": "A gyárat Henry Ford alapította, Galamb a T-modellt tervezte.", "p": "Galamb József — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["Makón született, és fiatalon Amerikába ment szerencsét próbálni.", "A Ford T-modelljének ő volt a fő tervezője."]},
  {"a": "Munkáját már életében az egész világon elismerték.", "e": "Az Appendixre életében alig figyeltek, elismerése halála után jött.", "p": "Bolyai János — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["Apja könyvének függelékeként adta közre a felfedezését.", "Katonatisztként szolgált, miközben matematikával foglalkozott."]},
  {"a": "Kutatásaiért fizikai Nobel-díjat kapott 1911-ben.", "e": "Eötvös sosem kapott Nobel-díjat, bár az ingája világhírű lett.", "p": "Eötvös Loránd — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["A torziós ingájával a föld alatti kőzeteket vizsgálta.", "Apja, Eötvös József író és miniszter volt."]},
  {"a": "Élete végéig a budapesti egyetemen tanított fizikát.", "e": "Wigner az Egyesült Államokban, a princetoni egyetemen dolgozott.", "p": "Wigner Jenő — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["1963-ban fizikai Nobel-díjat kapott az atommag kutatásáért.", "Budapesten Neumann Jánossal járt ugyanabba a gimnáziumba."]},
  {"a": "Élete végén hazatért, és a Műegyetemen tanított Budapesten.", "e": "Kármán az amerikai Caltechen dolgozott, és 1963-ban Aachenben halt meg.", "p": "Kármán Tódor — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["Az áramlástan kutatója volt, róla nevezték el az örvénysort.", "Apja, Kármán Mór a budapesti Mintagimnáziumot szervezte meg."]},
  {"a": "Kísérletét az amerikaiak előtt, elsőként végezte el.", "e": "Az amerikai Diana-kísérlet néhány héttel megelőzte Bay mérését.", "p": "Bay Zoltán — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["Az újpesti Egyesült Izzó kutatólaboratóriumát vezette.", "1946-ban sikerült radarjelet visszakapnia a Holdról."]},
  {"a": "Munkájáért orvosi Nobel-díjat kapott az ötvenes években.", "e": "Selyét sokszor jelölték, de Nobel-díjat sosem kapott.", "p": "Selye János — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["A stressz fogalmát ő vezette be az orvostudományba.", "Élete nagy részében Kanadában, Montrealban kutatott."]},
  {"a": "A háború után Angliában telepedett le, és ott kutatott.", "e": "Szent-Györgyi az Egyesült Államokba költözött, Woods Hole-ba.", "p": "Szent-Györgyi Albert — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["1937-ben Nobel-díjat kapott a C-vitamin kutatásáért.", "A C-vitamint a szegedi paprikából vonta ki nagy mennyiségben."]},
  {"a": "Felfedezését az orvosok azonnal elfogadták és bevezették.", "e": "Kortársai sokáig elutasították, igazát csak később ismerték el.", "p": "Semmelweis Ignác — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["A kézmosás bevezetésével mentette meg a szülő nők életét.", "Bécsben ismerte fel a gyermekágyi láz igazi okát."]},
  {"a": "Élete végén a Nemzeti Színház igazgatója lett Pesten.", "e": "Arany a Magyar Tudományos Akadémia főtitkára volt, nem színigazgató.", "p": "Arany János — melyik állítás NEM igaz?", "s": "Írók", "w": ["A Toldi című költeményével lett ismert 1846-ban.", "Petőfi Sándorral szoros barátságot kötött, és leveleztek."]},
  {"a": "A Nemzeti dal szövegét ő írta a Pilvax kávéházban.", "e": "A Nemzeti dal Petőfi verse, Jókai regényíróként lett halhatatlan.", "p": "Jókai Mór — melyik állítás NEM igaz?", "s": "Írók", "w": ["Az arany ember és A kőszívű ember fiai is az ő regénye.", "A márciusi ifjak közé tartozott 1848-ban Pesten."]},
  {"a": "A darab tizenöt színe mind a magyar történelemben játszódik.", "e": "A színek a világtörténelemben játszódnak, Egyiptomtól a jövőig.", "p": "Madách Imre — melyik állítás NEM igaz?", "s": "Írók", "w": ["Az ember tragédiája című drámai költeményt ő írta.", "Művét Arany János ajánlására adták ki és mutatták be."]},
  {"a": "A Pál utcai fiúk című regényt is ő írta meg.", "e": "A Pál utcai fiúkat Molnár Ferenc írta 1906-ban.", "p": "Mikszáth Kálmán — melyik állítás NEM igaz?", "s": "Írók", "w": ["A Szent Péter esernyője és a Beszterce ostroma az ő regénye.", "Íróként és országgyűlési képviselőként is dolgozott."]},
  {"a": "Leghíresebb regénye Buda 1552-es ostromáról szól.", "e": "A regény az egri vár ostromáról szól, Dobó István vezetésével.", "p": "Gárdonyi Géza — melyik állítás NEM igaz?", "s": "Írók", "w": ["Az Egri csillagok című regényével lett halhatatlan.", "Élete második felét Egerben töltötte, a vár tövében."]},
  {"a": "A Pál utcai fiúk a Duna-parti Ferencvárosban játszódik.", "e": "A regény a józsefvárosi grund körül játszódik, a Pál utcában.", "p": "Molnár Ferenc — melyik állítás NEM igaz?", "s": "Írók", "w": ["A Pál utcai fiúk című regénye 1906-ban jelent meg.", "Liliom című darabjából Amerikában musical is készült."]},
  {"a": "A Nyugat főszerkesztőjeként dolgozott a harmincas években.", "e": "A Szép Szó című folyóirat szerkesztője volt, nem a Nyugaté.", "p": "József Attila — melyik állítás NEM igaz?", "s": "Írók", "w": ["A Tiszta szívvel című verse miatt tanácsolták el Szegedről.", "1905-ben született Budapesten, a Ferencvárosban."]},
  {"a": "A Nyugat című folyóiratot ő alapította és szerkesztette.", "e": "A Nyugatot 1908-ban Ignotus, Osvát Ernő és Fenyő Miksa indította.", "p": "Ady Endre — melyik állítás NEM igaz?", "s": "Írók", "w": ["Az Új versek című kötete 1906-ban keltett nagy feltűnést.", "Párizsba többször utazott, és Léda volt a nagy szerelme."]},
  {"a": "Első sikerét egy verseskötettel aratta a század elején.", "e": "Az áttörést a Hét krajcár című novellája hozta meg 1908-ban.", "p": "Móricz Zsigmond — melyik állítás NEM igaz?", "s": "Írók", "w": ["A Légy jó mindhalálig című regénye Debrecenben játszódik.", "A Nyugat szerkesztője volt Babits Mihállyal együtt."]},
  {"a": "Élete végén Budapesten halt meg, a Zeneakadémia épületében.", "e": "Liszt 1886-ban a németországi Bayreuthban hunyt el.", "p": "Liszt Ferenc — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["1811-ben Doborjánban született, és zongoraművész lett.", "A budapesti Zeneakadémia első elnöke volt 1875-től."]},
  {"a": "A Szózat zenéjét is ő szerezte Vörösmarty versére.", "e": "A Szózat zenéjét Egressy Béni szerezte 1843-ban.", "p": "Erkel Ferenc — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["A Bánk bán és a Hunyadi László is az ő operája.", "Az Operaház első igazgatója és karmestere volt."]},
  {"a": "Egyetlen operája A csodálatos mandarin címet viseli.", "e": "Egyetlen operája A kékszakállú herceg vára, a mandarin némajáték.", "p": "Bartók Béla — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["Kodály Zoltánnal együtt gyűjtötte a magyar népdalokat.", "1940-ben Amerikába költözött, és ott halt meg 1945-ben."]},
  {"a": "Az Allegro barbaro című zongoradarab is az ő műve.", "e": "Az Allegro barbarót Bartók Béla írta 1911-ben.", "p": "Kodály Zoltán — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["A Háry János című daljátékot ő szerezte.", "Az énektanítás módszerét világszerte az ő nevéhez kötik."]},
  {"a": "A Csárdáskirálynő zenéjét is ő szerezte 1915-ben.", "e": "A Csárdáskirálynő Kálmán Imre operettje, 1915-ből.", "p": "Lehár Ferenc — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["A víg özvegy című operettje tette világhírűvé.", "Komáromban született, és katonakarmesterként kezdte."]},
  {"a": "Pályáját a Zeneakadémián Bartók tanítványaként kezdte.", "e": "Kálmán Koessler János tanítványa volt, Bartókkal egy időben.", "p": "Kálmán Imre — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["A Csárdáskirálynő és a Marica grófnő is az ő operettje.", "1938-ban elhagyta Bécset, és Amerikába költözött."]},
  {"a": "Először a szabadságharc idején csendült fel Debrecenben.", "e": "A Himnuszt már 1844-ben bemutatták, évekkel a szabadságharc előtt.", "p": "A Himnusz — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["Szövegét Kölcsey Ferenc írta 1823-ban Szatmárcsekén.", "Zenéjét Erkel Ferenc szerezte egy pályázatra 1844-ben."]},
  {"a": "A Csillagok háborúja zenéjét is ő szerezte Hollywoodban.", "e": "A Csillagok háborúja zenéjét John Williams írta 1977-ben.", "p": "Rózsa Miklós — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["A Ben-Hur zenéjéért Oscar-díjat kapott 1960-ban.", "Budapesten született, és Amerikában lett filmzeneszerző."]},
  {"a": "Az 1954-es világbajnokság döntőjét is megnyerte Svájcban.", "e": "Az 1954-es döntőt 3:2-re elveszítette a nyugatnémetek ellen.", "p": "Az Aranycsapat — melyik állítás NEM igaz?", "s": "Sportolók", "w": ["1953-ban Londonban 6:3-ra győzte le az angol válogatottat.", "Az 1952-es helsinki olimpián aranyérmet nyert a csapat."]},
  {"a": "Mellúszásban lett világhírű, abban nyerte az érmeit.", "e": "Egerszegi háton volt verhetetlen, ott nyerte az aranyérmeit.", "p": "Egerszegi Krisztina — melyik állítás NEM igaz?", "s": "Sportolók", "w": ["Tizennégy évesen nyert olimpiai aranyérmet Szöulban.", "Barcelonában három aranyérmet szerzett egyetlen olimpián."]},
  {"a": "Profi világbajnoki címet is szerzett a hatvanas években.", "e": "Profiként Európa-bajnok lett, világbajnoki meccsre nem engedték.", "p": "Papp László — melyik állítás NEM igaz?", "s": "Sportolók", "w": ["Három egymást követő olimpián nyert aranyérmet ökölvívásban.", "Az első keleti sportoló volt, aki profiként versenyezhetett."]},
  {"a": "Első olimpiai aranyát Pekingben szerezte 2008-ban.", "e": "Első olimpiai aranyérmét 2016-ban, Rióban nyerte meg.", "p": "Hosszú Katinka — melyik állítás NEM igaz?", "s": "Sportolók", "w": ["A 2016-os riói olimpián három aranyérmet nyert.", "Vasladynek becézik a rengeteg versenyszáma miatt."]},
  {"a": "Párbajtőrben lett a legeredményesebb magyar vívó.", "e": "Gerevich kardvívó volt, minden aranyérmét kardban nyerte.", "p": "Gerevich Aladár — melyik állítás NEM igaz?", "s": "Sportolók", "w": ["Hat olimpián nyert aranyérmet, ez máig páratlan teljesítmény.", "Utolsó aranyérmét ötvenévesen szerezte meg Rómában."]},
  {"a": "A sakkvilágbajnoki címet 2005-ben nyerte meg Budapesten.", "e": "Polgár Judit nem lett világbajnok, de a világranglista nyolcadikja volt.", "p": "Polgár Judit — melyik állítás NEM igaz?", "s": "Sportolók", "w": ["Tizenöt évesen lett nagymester, megdöntve Fischer rekordját.", "Sosem indult a női világbajnokságon, a férfiak közt játszott."]},
  {"a": "Első aranyérmét húszévesen, a berlini olimpián szerezte.", "e": "Első olimpiai aranyát 1952-ben, Helsinkiben nyerte, harmincegy évesen.", "p": "Keleti Ágnes — melyik állítás NEM igaz?", "s": "Sportolók", "w": ["Öt olimpiai aranyérmet nyert tornában az ötvenes években.", "Az 1956-os melbourne-i olimpia után Izraelbe költözött."]},
  {"a": "Aranyérmeit egy budapesti fedett uszodában szerezte.", "e": "A versenyeket a hideg tengerben rendezték, a görög Zea-öbölben.", "p": "Hajós Alfréd — melyik állítás NEM igaz?", "s": "Sportolók", "w": ["Az első újkori olimpián, 1896-ban nyert úszásban aranyérmet.", "Építészként a margitszigeti uszodát is ő tervezte."]},
  {"a": "Eljutott Mongóliáig, ahol megtalálta a magyarok rokonait.", "e": "Az őshazát sosem találta meg, Dardzsilingben érte a halál 1842-ben.", "p": "Kőrösi Csoma Sándor — melyik állítás NEM igaz?", "s": "Felfedezők", "w": ["Gyalog indult keletre, hogy megkeresse a magyarok őshazáját.", "Megírta az első tibeti-angol szótárt és nyelvtankönyvet."]},
  {"a": "Kínáig jutott el, és Pekingben töltött két évet.", "e": "Vámbéry Perzsián át Bukharáig és Szamarkandig jutott, Kínába nem.", "p": "Vámbéry Ármin — melyik állítás NEM igaz?", "s": "Felfedezők", "w": ["Dervisnek öltözve utazta be Közép-Ázsiát az 1860-as években.", "Hazatérve a pesti egyetem keleti nyelvek tanára lett."]},
  {"a": "Ő fedezte fel a Viktória-vízesést, és el is nevezte.", "e": "A Viktória-vízesést David Livingstone írta le 1855-ben.", "p": "Magyar László — melyik állítás NEM igaz?", "s": "Felfedezők", "w": ["Afrikában, főleg Angola vidékén kutatott a 19. században.", "Egy helyi törzsfőnök lányát vette feleségül odakint."]},
  {"a": "A Nílus forrását is ő találta meg az útja során.", "e": "A Nílus forrásvidékét John Speke írta le, nem Teleki Sámuel.", "p": "Teleki Sámuel — melyik állítás NEM igaz?", "s": "Felfedezők", "w": ["1888-ban ő fedezte fel a Rudolf-tavat Kelet-Afrikában.", "Expedíciója ugyanabban az évben a Stefánia-tavat is megtalálta."]},
  {"a": "Autó helyett tevekaravánnal járta be a sivatagot.", "e": "Almásy autóval és repülővel járta a sivatagot, nem tevével.", "p": "Almásy László — melyik állítás NEM igaz?", "s": "Felfedezők", "w": ["A Szaharában kutatott, és megtalálta az úszók barlangját.", "Alakja ihlette Az angol beteg című regény főhősét."]},
  {"a": "Utazásairól szóló könyve még életében nagy siker lett.", "e": "Gyűjtését csak halála után dolgozták fel és adták ki.", "p": "Reguly Antal — melyik állítás NEM igaz?", "s": "Felfedezők", "w": ["Az Urál vidékére utazott, hogy a rokon népeket kutassa.", "A vogulok és az osztjákok nyelvét gyűjtötte össze."]},
  {"a": "A delfin alvás közben mindkét agyféltekéjével egyszerre pihen.", "e": "A delfin mindig csak az egyik agyféltekéjével alszik.", "p": "A delfin — melyik állítás NEM igaz?", "s": "Állatok", "w": ["A delfin emlős, és a víz felszínén vesz levegőt.", "A delfinek hangok visszhangjával tájékozódnak a víz alatt."]},
  {"a": "A virágport a kaptárban a herék gyűjtik be.", "e": "A virágport a dolgozó méhek gyűjtik, a herék nem.", "p": "A méhek — melyik állítás NEM igaz?", "s": "Állatok", "w": ["A méhek tánccal mutatják meg a virágok irányát.", "Egy méhcsaládban egyetlen petéző királynő él."]},
  {"a": "Az elefánt agyarai valójában megnyúlt szemfogak.", "e": "Az agyarak valójában megnyúlt metszőfogak.", "p": "Az elefánt — melyik állítás NEM igaz?", "s": "Állatok", "w": ["Az elefánt a legnagyobb ma élő szárazföldi állat.", "Az elefánt az ormányával iszik és fog meg tárgyakat."]},
  {"a": "Az Északi-sarkon nagy pingvintelepek élnek a jégen.", "e": "Az Északi-sarkon nem élnek pingvinek, csak a délin.", "p": "A pingvinek — melyik állítás NEM igaz?", "s": "Állatok", "w": ["A pingvinek nem tudnak repülni, de jól úsznak.", "A pingvinek szinte mind a déli féltekén élnek."]},
  {"a": "A zsiráf sosem fekszik le, állva alszik egész életében.", "e": "A zsiráf le tud feküdni, bár ritkán és rövid időre.", "p": "A zsiráf — melyik állítás NEM igaz?", "s": "Állatok", "w": ["A zsiráf nyakában hét csigolya van, mint az emberében.", "A zsiráf a legmagasabb ma élő szárazföldi állat."]},
  {"a": "A denevérek teljesen vakok, semmit sem látnak.", "e": "A denevérek jól látnak, a visszhang csak segíti őket.", "p": "A denevér — melyik állítás NEM igaz?", "s": "Állatok", "w": ["A denevér az egyetlen igazán repülni tudó emlős.", "Sok denevér a hangja visszhangjával tájékozódik."]},
  {"a": "A polip vére a benne lévő vastól piros színű.", "e": "A polip vére rezet tartalmaz, ezért kékes.", "p": "A polip — melyik állítás NEM igaz?", "s": "Állatok", "w": ["A polipnak három szíve és nyolc karja van.", "A polip pillanatok alatt megváltoztatja a színét."]},
  {"a": "A teknős ki tud bújni a páncéljából, ha akar.", "e": "A páncél a csontvázához nőtt, sosem hagyhatja el.", "p": "A teknős — melyik állítás NEM igaz?", "s": "Állatok", "w": ["A teknős páncélja a gerincéhez és a bordáihoz nőtt.", "Egyes teknősfajok száz évnél tovább is elélnek."]},
  {"a": "A kolibri Európa erdeiben is gyakori madár.", "e": "A kolibrik csak Amerikában élnek.", "p": "A kolibri — melyik állítás NEM igaz?", "s": "Állatok", "w": ["A kolibri a madarak közül hátrafelé is tud repülni.", "A kolibri egy helyben lebegve issza a nektárt."]},
  {"a": "A napraforgó Afrikából került Európába a középkorban.", "e": "A napraforgó Amerikából érkezett Európába.", "p": "A napraforgó — melyik állítás NEM igaz?", "s": "Növények", "w": ["A fiatal napraforgó feje követi a Nap járását.", "A napraforgó magjából finom étolajat sajtolnak."]},
  {"a": "A fatörzsbe vésett jel évről évre feljebb kerül.", "e": "A törzs csak vastagszik, a jel ugyanolyan magasan marad.", "p": "A fák növekedése — melyik állítás NEM igaz?", "s": "Növények", "w": ["A fa a leveleiben napfényből készít cukrot.", "A fa évgyűrűiből leolvasható a törzs kora."]},
  {"a": "A moha mindig a fák északi oldalán nő.", "e": "A moha ott nő, ahol nedves, nem csak északon.", "p": "A moha — melyik állítás NEM igaz?", "s": "Növények", "w": ["A moha nem hoz virágot, spórákkal szaporodik.", "A moha az árnyékos, nedves helyeket kedveli."]},
  {"a": "A paradicsomot már az ókori rómaiak is termesztették.", "e": "A paradicsom csak Amerika felfedezése után jutott Európába.", "p": "A paradicsom — melyik állítás NEM igaz?", "s": "Növények", "w": ["A paradicsom a növénytan szerint bogyótermés.", "A paradicsom a burgonyával egy növénycsaládba tartozik."]},
  {"a": "A kaktuszok eredeti hazája Afrika száraz vidéke.", "e": "A kaktuszok szinte kizárólag Amerikában őshonosak.", "p": "A kaktusz — melyik állítás NEM igaz?", "s": "Növények", "w": ["A kaktusz tövisei valójában átalakult levelek.", "A kaktusz a vastag szárában raktározza a vizet."]},
  {"a": "A gombák napfényből készítik a tápanyagukat.", "e": "A gombák készen veszik fel a tápanyagot a környezetükből.", "p": "A gombák — melyik állítás NEM igaz?", "s": "Növények", "w": ["A gombák külön országot alkotnak az élővilágban.", "A kalapos gomba a föld alatti fonalak termőteste."]},
  {"a": "A bambusz a pálmafélék közé tartozó fa.", "e": "A bambusz fű, nem pálma, és nincs igazi fatörzse.", "p": "A bambusz — melyik állítás NEM igaz?", "s": "Növények", "w": ["A bambusz a fűfélék családjába tartozik.", "A bambusz a leggyorsabban növő növények közé tartozik."]},
  {"a": "A kék rózsa régi, természetben is termő fajta.", "e": "Természetben nem terem kék rózsa.", "p": "A rózsa — melyik állítás NEM igaz?", "s": "Növények", "w": ["A rózsa tövisei a szár apró kinövései.", "A rózsa termése a piros csipkebogyó."]},
  {"a": "A pitypang virága éjszaka is nyitva marad.", "e": "A pitypang virága estére becsukódik.", "p": "A pitypang — melyik állítás NEM igaz?", "s": "Növények", "w": ["A pitypang magját apró ejtőernyő viszi a szélben.", "A pitypang letört szárából fehér tejnedv folyik."]},
  {"a": "A Holdnak saját fénye van, ezért világít éjjel.", "e": "A Hold a Nap fényét veri vissza.", "p": "A Hold — melyik állítás NEM igaz?", "s": "Az űr", "w": ["A Hold mindig ugyanazt az oldalát fordítja felénk.", "A Hold vonzása okozza az apályt és a dagályt."]},
  {"a": "A Mars a Földnél közelebb kering a Naphoz.", "e": "A Mars a Földnél távolabb kering a Naptól.", "p": "A Mars — melyik állítás NEM igaz?", "s": "Az űr", "w": ["A Marsnak két apró holdja kering körülötte.", "A Mars felszínét vas-oxid festi vörösre."]},
  {"a": "A Merkúr a Naptól számított második bolygó.", "e": "A Merkúr a Naphoz legközelebbi, első bolygó.", "p": "A Naprendszer — melyik állítás NEM igaz?", "s": "Az űr", "w": ["A Naprendszerben nyolc bolygó kering a Nap körül.", "A Jupiter a Naprendszer legnagyobb bolygója."]},
  {"a": "A csillagok maguktól, szabálytalanul pislognak az égen.", "e": "A pislogást a Föld mozgó levegője okozza.", "p": "A csillagok — melyik állítás NEM igaz?", "s": "Az űr", "w": ["A csillagok a fényüket a saját magjukban termelik.", "A Napon kívüli legközelebbi csillag fénye évekig utazik."]},
  {"a": "Az űrállomás egy helyben áll a Föld felett.", "e": "Az űrállomás óriási sebességgel kering a Föld körül.", "p": "Az űrállomás — melyik állítás NEM igaz?", "s": "Az űr", "w": ["Az űrállomás másfél óra alatt kerüli meg a Földet.", "Az űrhajósok a falhoz rögzített zsákban alszanak."]},
  {"a": "Az üstökös csóvája mindig a mozgása mögött húzódik.", "e": "A csóva mindig a Nappal ellentétes irányba mutat.", "p": "Az üstökös — melyik állítás NEM igaz?", "s": "Az űr", "w": ["Az üstökösök jégből és porból álló égitestek.", "A Halley-üstökös nagyjából hetvenöt évente tér vissza."]},
  {"a": "Nyáron azért van meleg, mert közelebb vagyunk a Naphoz.", "e": "Az évszakokat a Föld tengelyének dőlése okozza.", "p": "Az évszakok — melyik állítás NEM igaz?", "s": "Az űr", "w": ["A déli féltekén karácsony idején nyár van.", "Június végén nálunk a leghosszabb a nappal."]},
  {"a": "A Vénusz sokkal nagyobb bolygó, mint a Föld.", "e": "A Vénusz majdnem pontosan akkora, mint a Föld.", "p": "A Vénusz — melyik állítás NEM igaz?", "s": "Az űr", "w": ["A Vénuszt esthajnalcsillagnak is szokták nevezni.", "A Vénusz felszíne forróbb, mint a Merkúré."]},
  {"a": "A hullócsillagok mindig leérnek a Föld felszínéig.", "e": "A legtöbb meteor elég a levegőben, és sosem ér földet.", "p": "A hullócsillag — melyik állítás NEM igaz?", "s": "Az űr", "w": ["A hullócsillag a légkörben elégő porszem.", "Augusztusban sok hullócsillag látszik az égen."]},
  {"a": "A cápák a bálnák közeli rokonai a tengerben.", "e": "A cápák halak, a bálnák viszont emlősök.", "p": "A cápák — melyik állítás NEM igaz?", "s": "A tenger", "w": ["A cápa csontváza porcból, nem csontból áll.", "A cápa fogai egész életében újranőnek."]},
  {"a": "A kék bálna nagy halakra vadászik a mélyben.", "e": "A kék bálna apró rákokkal, krillel táplálkozik.", "p": "A kék bálna — melyik állítás NEM igaz?", "s": "A tenger", "w": ["A kék bálna a valaha élt legnagyobb állat.", "A bálnák a felszínen fújják ki a levegőt."]},
  {"a": "A medúza váza vékony porcokból épül fel.", "e": "A medúzának egyáltalán nincs váza.", "p": "A medúza — melyik állítás NEM igaz?", "s": "A tenger", "w": ["A medúza teste szinte teljesen vízből áll.", "A medúzának nincs se szíve, se agya."]},
  {"a": "A csikóhal a tenger leggyorsabb halai közé tartozik.", "e": "A csikóhal az egyik leglassabban úszó hal.", "p": "A csikóhal — melyik állítás NEM igaz?", "s": "A tenger", "w": ["A csikóhalnál a hím hordja ki a kicsinyeket.", "A csikóhal a farkával kapaszkodik a növényekbe."]},
  {"a": "A lazac egész életét a nyílt tengeren tölti.", "e": "A lazac édesvízben születik, és oda tér vissza ívni.", "p": "A lazac — melyik állítás NEM igaz?", "s": "A tenger", "w": ["A lazac a tengerből folyóba úszik fel ívni.", "A lazac húsa a táplálékától lesz rózsaszín."]},
  {"a": "A napfény a tenger legmélyebb pontjáig is lejut.", "e": "A napfény néhány száz méter alatt teljesen elfogy.", "p": "A mélytenger — melyik állítás NEM igaz?", "s": "A tenger", "w": ["Az óceán legmélyebb pontja több mint tíz kilométer.", "Sok mélytengeri állat saját fényt bocsát ki."]},
  {"a": "A tengerek vize mindenhol ugyanolyan sós.", "e": "A Balti-tenger például jóval kevésbé sós.", "p": "A tengervíz — melyik állítás NEM igaz?", "s": "A tenger", "w": ["A tengervíz az édesvíznél alacsonyabb fokon fagy meg.", "A tengervizet szomjúság ellen nem lehet inni."]},
  {"a": "A hullámmal maga a víz utazik el a partig.", "e": "A víz nagyrészt helyben köröz, csak az energia halad.", "p": "A hullámok — melyik állítás NEM igaz?", "s": "A tenger", "w": ["A hullámokat többnyire a szél kelti a felszínen.", "A cunamit gyakran tenger alatti földrengés okozza."]},
  {"a": "A gyöngy a kagyló megkeményedett tojása.", "e": "A gyöngy egy beszorult szemcse köré rakódó gyöngyház.", "p": "A gyöngy — melyik állítás NEM igaz?", "s": "A tenger", "w": ["A gyöngy a kagyló belsejében növekszik meg.", "A kagyló héja két összecsukható részből áll."]},
  {"a": "A dörgést a felhők egymásnak ütődése kelti.", "e": "A dörgést a villámtól hirtelen felforrósodó levegő okozza.", "p": "A villámlás — melyik állítás NEM igaz?", "s": "Időjárás", "w": ["A villám fénye előbb ér ide, mint a hangja.", "A villám többször is becsaphat ugyanarra a helyre."]},
  {"a": "A szivárvány pontosan hét éles színsávból áll.", "e": "A színek folyamatosan mennek át egymásba.", "p": "A szivárvány — melyik állítás NEM igaz?", "s": "Időjárás", "w": ["A szivárvány a Nappal szemközti égen látszik.", "A szivárványt a vízcseppekben megtörő fény kelti."]},
  {"a": "A hó a felhőben megfagyott esőcseppekből lesz.", "e": "A hókristály közvetlenül a vízpárából épül fel.", "p": "A hó — melyik állítás NEM igaz?", "s": "Időjárás", "w": ["A hópelyhek hat ágú jégkristályokból állnak.", "A friss hó jó szigetelő, védi a talajt."]},
  {"a": "A felhő azért lebeg, mert könnyebb a levegőnél.", "e": "A cseppek olyan aprók, hogy a mozgó levegő fenntartja őket.", "p": "A felhők — melyik állítás NEM igaz?", "s": "Időjárás", "w": ["A felhők apró vízcseppekből és jégkristályokból állnak.", "A magas, fátyolos felhők jégkristályokból állnak."]},
  {"a": "A szél mindig a melegebb helyről a hidegebb felé fúj.", "e": "A szél a nagyobb nyomású hely felől fúj az alacsonyabb felé.", "p": "A szél — melyik állítás NEM igaz?", "s": "Időjárás", "w": ["A szelet a levegő nyomáskülönbsége kelti.", "A szelet arról az égtájról nevezzük el, ahonnan fúj."]},
  {"a": "A jégszem belül egyetlen tömör jégdarab.", "e": "A jégszem rétegesen épül fel, mint a hagyma.", "p": "A jégeső — melyik állítás NEM igaz?", "s": "Időjárás", "w": ["A jégszemek a zivatarfelhő feláramlásában nőnek nagyra.", "A jégeső nyáron, nagy melegben is előfordul."]},
  {"a": "A ködöt a talajból felszálló por okozza.", "e": "A ködöt a levegőben lebegő apró vízcseppek okozzák.", "p": "A köd — melyik állítás NEM igaz?", "s": "Időjárás", "w": ["A köd a talaj közelében képződő felhő.", "A köd gyakran tiszta éjszaka után, hajnalban képződik."]},
  {"a": "A tornádó és a hurrikán ugyanannak a neve.", "e": "A hurrikán óriási tengeri vihar, a tornádó kicsi örvény.", "p": "A tornádó — melyik állítás NEM igaz?", "s": "Időjárás", "w": ["A tornádó a felhőből lenyúló, forgó légörvény.", "A legtöbb tornádó az Egyesült Államokban pusztít."]},
  {"a": "A hulló esőcsepp könnycsepp alakúra nyúlik.", "e": "A hulló esőcsepp gömbölyű, alul kissé lapos.", "p": "Az esőcsepp — melyik állítás NEM igaz?", "s": "Időjárás", "w": ["Az eső a felhő cseppjeinek összetapadásából lesz.", "A nagy esőcsepp gyorsabban esik, mint a kicsi."]},
  {"a": "A szív izmait akarattal is tudjuk irányítani.", "e": "A szívizom akaratunktól függetlenül dolgozik.", "p": "A szív — melyik állítás NEM igaz?", "s": "Az emberi test", "w": ["A szívnek két pitvara és két kamrája van.", "A szív a mellkas közepén, kissé balra fekszik."]},
  {"a": "Az agyunknak csak a tized részét használjuk.", "e": "Az agy minden része dolgozik, ez régi tévhit.", "p": "Az agy — melyik állítás NEM igaz?", "s": "Az emberi test", "w": ["Az agy a szervezet energiájának ötödét használja.", "Az agy szövetében nincs fájdalomérző idegvégződés."]},
  {"a": "A csontok élettelen, kemény anyagból állnak.", "e": "A csont élő szövet, erekkel és idegekkel.", "p": "A csontok — melyik állítás NEM igaz?", "s": "Az emberi test", "w": ["A felnőtt ember testében 206 csont van.", "A csecsemőnek több csontja van, mint a felnőttnek."]},
  {"a": "A bőr külső rétege élő, osztódó sejtekből áll.", "e": "A bőr legkülső rétegét elhalt sejtek alkotják.", "p": "A bőr — melyik állítás NEM igaz?", "s": "Az emberi test", "w": ["A bőr az ember legnagyobb kiterjedésű szerve.", "A bőrünk napfény hatására D-vitamint állít elő."]},
  {"a": "A vér a vénákban kék, a levegőtől lesz piros.", "e": "A vér mindig piros, a vénák csak kéknek látszanak.", "p": "A vér — melyik állítás NEM igaz?", "s": "Az emberi test", "w": ["A vörösvérsejtek szállítják az oxigént a szervekhez.", "A vörösvérsejtek a csontok belsejében képződnek."]},
  {"a": "A lenyelt rágógumi hét évig marad a gyomorban.", "e": "A rágógumi néhány nap alatt távozik a szervezetből.", "p": "Az emésztés — melyik állítás NEM igaz?", "s": "Az emberi test", "w": ["A táplálék nagy része a vékonybélben szívódik fel.", "A gyomor sósavat termel az emésztéshez."]},
  {"a": "A sárgarépától élesebb lesz a látásunk.", "e": "A sárgarépa nem élesíti a látást, ez tévhit.", "p": "A szem — melyik állítás NEM igaz?", "s": "Az emberi test", "w": ["A szemünk fordított képet vetít a recehártyára.", "A pupilla sötétben kitágul, hogy több fény jusson be."]},
  {"a": "A haj és a köröm a halál után is tovább nő.", "e": "Csak úgy tűnik, mert a bőr összehúzódik körülöttük.", "p": "A haj és a köröm — melyik állítás NEM igaz?", "s": "Az emberi test", "w": ["A haj és a köröm ugyanabból az anyagból épül fel.", "A hajszál a hajhagymánál nő, nem a végénél."]},
  {"a": "A nyelv más-más részén érezzük az alapízeket.", "e": "A nyelv minden része érzi az összes alapízt.", "p": "A nyelv — melyik állítás NEM igaz?", "s": "Az emberi test", "w": ["A nyelv izmokból álló, mozgékony szerv a szájban.", "A nyelven és a szájpadláson ízlelőbimbók vannak."]},
  {"a": "A tiszta víz jól vezeti az elektromos áramot.", "e": "A vizet a benne oldott sók teszik vezetővé.", "p": "A tiszta víz — melyik állítás NEM igaz?", "s": "Mindennapi tudomány", "w": ["A víz fagyáskor kitágul, ezért úszik a jég.", "A víz molekulája két hidrogénből és egy oxigénből áll."]},
  {"a": "A kettétört mágnesnek egy pólusa marad.", "e": "Minden darabnak újra északi és déli pólusa lesz.", "p": "A mágnes — melyik állítás NEM igaz?", "s": "Mindennapi tudomány", "w": ["A mágnesnek mindig van északi és déli pólusa.", "A mágnes a vasat vonzza, az alumíniumot nem."]},
  {"a": "A hang az űr légüres terében is terjed.", "e": "A hangnak közeg kell, az űrben nem terjed.", "p": "A hang — melyik állítás NEM igaz?", "s": "Mindennapi tudomány", "w": ["A hang sokkal lassabban terjed, mint a fény.", "A hang vízben gyorsabban terjed, mint levegőben."]},
  {"a": "A madár azért nem sérül a dróton, mert könnyű.", "e": "A madár csak egy vezetéket ér, így nincs áramkör.", "p": "Az elektromos áram — melyik állítás NEM igaz?", "s": "Mindennapi tudomány", "w": ["A rézhuzal jól vezeti az elektromos áramot.", "A gumi jó szigetelő, ezért nem vezeti az áramot."]},
  {"a": "A gyertya lángja a szilárd viaszt égeti el.", "e": "A gyertya a kanócon elpárolgott viaszt égeti.", "p": "A gyertya lángja — melyik állítás NEM igaz?", "s": "Mindennapi tudomány", "w": ["A gyertya lángjának oxigénre van szüksége.", "Az olajtüzet vízzel oltani nagyon veszélyes."]},
  {"a": "A takaró alvás közben maga is meleget termel.", "e": "A takaró csak bent tartja a test saját melegét.", "p": "A takaró — melyik állítás NEM igaz?", "s": "Mindennapi tudomány", "w": ["A meleg levegő felszáll a hidegebb helyére.", "A fém hidegebbnek tűnik a fánál, mert jobban vezet."]},
  {"a": "A mikrohullámú sütő belülről kifelé melegít.", "e": "A mikrohullám a külső rétegeket melegíti, onnan terjed beljebb.", "p": "A mikrohullámú sütő — melyik állítás NEM igaz?", "s": "Mindennapi tudomány", "w": ["A mikrohullámú sütő a víz molekuláit rezgeti.", "A fémtárgy szikrázhat a mikrohullámú sütőben."]},
  {"a": "A forró csapvíz önmagában megöli a baktériumokat.", "e": "A csapvíz ehhez nem elég forró, a szappan számít.", "p": "A kézmosás — melyik állítás NEM igaz?", "s": "Mindennapi tudomány", "w": ["A szappan segít leoldani a zsírt a bőrről.", "A kézmosásnál a dörzsölés is fontos, nemcsak a víz."]},
  {"a": "A hőmérőben a higany a hidegtől tágul ki.", "e": "A higany melegben tágul, ezért emelkedik a szál.", "p": "A hőmérő — melyik állítás NEM igaz?", "s": "Mindennapi tudomány", "w": ["A víz a tengerszinten száz fokon forr.", "A hegyekben a víz alacsonyabb hőmérsékleten forr."]},
  {"a": "Erzsébetet a saját fia, I. Jakab követte a trónon.", "e": "I. Jakab a rokona volt, Skóciai Mária fia, nem Erzsébeté.", "p": "I. Erzsébet angol királynő — melyik állítás NEM igaz?", "s": "Uralkodók", "w": ["Erzsébet VIII. Henrik és Anna Boleyn lánya volt.", "Uralkodása idején szenvedett vereséget a spanyol Armada."]},
  {"a": "Élete utolsó éveit Elba szigetén töltötte száműzetésben.", "e": "Napóleon utolsó éveit Szent Ilona szigetén töltötte.", "p": "Napóleon — melyik állítás NEM igaz?", "s": "Uralkodók", "w": ["Napóleon Korzika szigetén született, 1769 nyarán.", "Waterloonál szenvedte el az utolsó vereségét 1815-ben."]},
  {"a": "Nagy Sándor ötvenéves korában halt meg Babilonban.", "e": "Nagy Sándor mindössze harminckét évesen halt meg.", "p": "Nagy Sándor — melyik állítás NEM igaz?", "s": "Uralkodók", "w": ["Fiatalon Arisztotelész volt a tanítómestere Makedóniában.", "Hadserege eljutott Indiáig, majd onnan visszafordult."]},
  {"a": "Viktória a bátyjától örökölte az angol trónt.", "e": "Viktória a nagybátyjától, IV. Vilmostól örökölte a trónt.", "p": "Viktória királynő — melyik állítás NEM igaz?", "s": "Uralkodók", "w": ["Viktória hatvanhárom évig ült Anglia trónján.", "Férjétől, Albert hercegtől kilenc gyermeke született."]},
  {"a": "XIV. Lajos a francia forradalomban vesztette el trónját.", "e": "A forradalom XVI. Lajos trónját döntötte meg, 1792-ben.", "p": "XIV. Lajos francia király — melyik állítás NEM igaz?", "s": "Uralkodók", "w": ["XIV. Lajos építtette ki a versailles-i kastélyt.", "Hosszú uralkodása alatt a Napkirály nevet kapta."]},
  {"a": "Caesar volt a Római Birodalom első császára.", "e": "Róma első császára Augustus lett, Caesar fogadott fia.", "p": "Julius Caesar — melyik állítás NEM igaz?", "s": "Uralkodók", "w": ["Caesar naptárreformja vezette be a szökőévet.", "Hosszú háborúban hódította meg Galliát Rómának."]},
  {"a": "Nagy Károly udvara a mai Párizs helyén állt.", "e": "Nagy Károly székhelye Aachen volt, nem Párizs.", "p": "Nagy Károly — melyik állítás NEM igaz?", "s": "Uralkodók", "w": ["Nagy Károlyt 800 karácsonyán koronázták császárrá Rómában.", "Birodalma Nyugat-Európa nagy részére kiterjedt akkoriban."]},
  {"a": "Kleopátra a gízai piramisok építése idején élt.", "e": "A gízai piramisok több mint kétezer évvel korábban épültek.", "p": "Kleopátra — melyik állítás NEM igaz?", "s": "Uralkodók", "w": ["Kleopátra az ókori Egyiptom utolsó uralkodója volt.", "Kleopátra a görög eredetű Ptolemaiosz-családból származott."]},
  {"a": "Uralkodása alatt Moszkva maradt az ország fővárosa.", "e": "Nagy Péter 1712-ben Szentpétervárra tette át a fővárost.", "p": "Nagy Péter orosz cár — melyik állítás NEM igaz?", "s": "Uralkodók", "w": ["Nagy Péter szakálladót vetett ki a nemesekre.", "Nyugat-Európába utazott, ahol hajóépítést is tanult."]},
  {"a": "Marie Curie fedezte fel a röntgensugárzást is.", "e": "A röntgensugárzást Wilhelm Röntgen fedezte fel 1895-ben.", "p": "Marie Curie — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["Marie Curie két tudományos Nobel-díjat is kapott.", "Lengyelországban született, de Párizsban élt és dolgozott."]},
  {"a": "Einstein megbukott matematikából a diákévei alatt.", "e": "Einstein kiváló matematikus volt már diákkorában is.", "p": "Albert Einstein — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["Einstein a fényelektromos hatásért kapott Nobel-díjat.", "Németországban született, élete végén Amerikában élt."]},
  {"a": "Newton az oxfordi egyetemen tanult és tanított.", "e": "Newton a cambridge-i egyetemen tanult és tanított.", "p": "Isaac Newton — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["Newton fogalmazta meg a mozgás három törvényét.", "Prizmával bontotta színeire a fehér fényt."]},
  {"a": "Darwin elmélete a szerzett tulajdonságok öröklődésén alapult.", "e": "A szerzett tulajdonságok öröklődése Lamarck elmélete volt.", "p": "Charles Darwin — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["Darwin a Beagle nevű hajón utazta körbe a Földet.", "A Galápagos-szigetek madarai is felkeltették a figyelmét."]},
  {"a": "Galilei találta fel a távcsövet Itáliában.", "e": "A távcsövet Hollandiában találták fel, Galilei tökéletesítette.", "p": "Galileo Galilei — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["Galilei távcsővel figyelte meg a Jupiter holdjait.", "Azt vallotta, hogy a Föld kering a Nap körül."]},
  {"a": "Pasteur fedezte fel a penicillint a laboratóriumában.", "e": "A penicillint Alexander Fleming fedezte fel 1928-ban.", "p": "Louis Pasteur — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["Pasteur dolgozta ki a veszettség elleni oltást.", "A tej pasztőrözése az ő nevét őrzi."]},
  {"a": "Kopernikusz fiatalon, húszévesen adta ki a könyvét.", "e": "Kopernikusz könyve 1543-ban, halála évében jelent meg.", "p": "Kopernikusz — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["Kopernikusz szerint a Nap áll a világ közepén.", "Lengyel csillagász volt, egyházi tisztséget is viselt."]},
  {"a": "Mendel felfedezései már életében világhírűvé tették.", "e": "Mendel munkáját csak halála után, 1900 körül fedezték fel.", "p": "Gregor Mendel — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["Mendel borsónövényeken végezte az öröklődési kísérleteit.", "Szerzetesként élt és dolgozott egy brünni kolostorban."]},
  {"a": "Archimédész számolta ki először a Föld kerületét.", "e": "A Föld kerületét Eratoszthenész számolta ki először.", "p": "Archimédész — melyik állítás NEM igaz?", "s": "Tudósok", "w": ["Archimédész a szicíliai Szirakuzában élt és dolgozott.", "Az ő nevéhez fűződik a felhajtóerő törvénye."]},
  {"a": "Edison találta fel a telefont a laboratóriumában.", "e": "A telefont Alexander Graham Bell szabadalmaztatta 1876-ban.", "p": "Thomas Edison — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["Edison több mint ezer szabadalmat jegyeztetett be.", "Az ő nevéhez fűződik a hangrögzítő fonográf."]},
  {"a": "Bell a rádió feltalálásáért kapott fizikai Nobel-díjat.", "e": "A rádióért Guglielmo Marconi kapott Nobel-díjat 1909-ben.", "p": "Alexander Graham Bell — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["Bell egész életében siketek tanításával is foglalkozott.", "Skóciában született, majd Észak-Amerikában élt és dolgozott."]},
  {"a": "Braille írása a latin betűk vonalait követi.", "e": "A Braille-írás hat kiemelkedő pontból álló jelekkel dolgozik.", "p": "Louis Braille — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["Braille tapintható írást dolgozott ki a vakoknak.", "Ő maga is gyermekkorától kezdve vak volt."]},
  {"a": "Diesel a benzinmotor feltalálója is volt egyben.", "e": "A benzinmotort Nikolaus Otto és Gottlieb Daimler fejlesztette ki.", "p": "Rudolf Diesel — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["Diesel német mérnök volt, a motorja róla kapta nevét.", "A motorja gyújtógyertya nélkül is működik."]},
  {"a": "Tesla egész pályáján Edison mellett dolgozott.", "e": "Tesla csak rövid ideig dolgozott Edisonnál, majd szakítottak.", "p": "Nikola Tesla — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["Tesla a váltakozó áram rendszerét fejlesztette ki.", "Szerb családban született, Amerikában lett híres."]},
  {"a": "Watt építette az első gőzmozdonyt Angliában.", "e": "Az első gőzmozdonyt Richard Trevithick építette 1804-ben.", "p": "James Watt — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["Watt tette sokkal hatékonyabbá a gőzgépet.", "A teljesítmény mértékegysége az ő nevét viseli."]},
  {"a": "Benz vezette be a futószalagos gyártást az iparban.", "e": "A futószalagos autógyártást Henry Ford vezette be.", "p": "Karl Benz — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["Benz 1886-ban szabadalmaztatta a háromkerekű gépkocsiját.", "Felesége hosszú útra vitte a kocsit reklámként."]},
  {"a": "A Nobel-díjak között matematikai díj is van.", "e": "Matematikai Nobel-díj nincs, a matematikusok Fields-érmet kapnak.", "p": "Alfred Nobel — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["Nobel a dinamit feltalálásával lett gazdag ember.", "Vagyonából alapították a róla elnevezett díjakat."]},
  {"a": "Volta fedezte fel az áram mágneses hatását.", "e": "Az áram mágneses hatását Hans Christian Ørsted fedezte fel.", "p": "Alessandro Volta — melyik állítás NEM igaz?", "s": "Feltalálók", "w": ["Volta készítette el az első működő elemet.", "A feszültség mértékegysége az ő nevét viseli."]},
  {"a": "Kolumbusz élete végéig tudta, hogy új földrészt talált.", "e": "Kolumbusz haláláig azt hitte, hogy Ázsia partjaihoz jutott.", "p": "Kolumbusz Kristóf — melyik állítás NEM igaz?", "s": "Felfedezők", "w": ["Kolumbusz 1492-ben indult el Spanyolországból nyugat felé.", "Három hajóval kelt át az Atlanti-óceánon."]},
  {"a": "Magellán maga tért vissza hajójával Spanyolországba.", "e": "Magellán útközben meghalt, Elcano vezette haza a hajót.", "p": "Magellán — melyik állítás NEM igaz?", "s": "Felfedezők", "w": ["Magellán expedíciója hajózta körbe elsőként a Földet.", "Portugál volt, de a spanyol királyt szolgálta."]},
  {"a": "Marco Polo kínai nyelven írta meg a könyvét.", "e": "Könyvét egy fogolytársa jegyezte le, itáliai nyelven.", "p": "Marco Polo — melyik állítás NEM igaz?", "s": "Felfedezők", "w": ["Marco Polo Velencéből indult el a távoli Ázsiába.", "Kublaj kán udvarában töltött hosszú éveket."]},
  {"a": "Cook érte el elsőként Ausztrália nyugati partját.", "e": "Ausztrália nyugati partját holland hajósok találták meg előbb.", "p": "James Cook — melyik állítás NEM igaz?", "s": "Felfedezők", "w": ["Cook három nagy utat tett a Csendes-óceánon.", "Ő térképezte fel Új-Zéland hosszú partvidékét."]},
  {"a": "Riválisa, Scott, néhány héttel korábban ért a sarkra.", "e": "Scott csak egy hónappal Amundsen után ért oda.", "p": "Roald Amundsen — melyik állítás NEM igaz?", "s": "Felfedezők", "w": ["Amundsen csapata érte el elsőként a Déli-sarkot.", "Norvég sarkkutató volt, és kutyaszánokkal utazott."]},
  {"a": "Vasco da Gama a spanyol király megbízásából indult.", "e": "Vasco da Gama a portugál király megbízásából hajózott.", "p": "Vasco da Gama — melyik állítás NEM igaz?", "s": "Felfedezők", "w": ["Vasco da Gama hajóval jutott el Indiába.", "Afrika déli csúcsát megkerülve hajózott tovább."]},
  {"a": "Ibn Battúta sosem jutott el Indiába az útjain.", "e": "Ibn Battúta évekig élt Indiában, a delhi szultán szolgálatában.", "p": "Ibn Battúta — melyik állítás NEM igaz?", "s": "Felfedezők", "w": ["Ibn Battúta Marokkóból indult el hosszú utazásaira.", "Mintegy harminc évig járta Afrikát és Ázsiát."]},
  {"a": "Livingstone megtalálta a Nílus forrását Afrikában.", "e": "Livingstone hiába kereste a Nílus forrását, nem találta meg.", "p": "David Livingstone — melyik állítás NEM igaz?", "s": "Felfedezők", "w": ["Livingstone skót orvos és misszionárius volt.", "Ő nevezte el a Viktória-vízesést Afrikában."]},
  {"a": "Armstrong volt az első ember a világűrben.", "e": "Az első ember az űrben Jurij Gagarin volt.", "p": "Neil Armstrong — melyik állítás NEM igaz?", "s": "Felfedezők", "w": ["Armstrong 1969-ben lépett először a Holdra.", "Az Apollo-11 parancsnokaként repült az űrbe."]},
  {"a": "Shakespeare a Rómeó és Júliát Velencébe helyezte.", "e": "A Rómeó és Júlia Veronában játszódik, nem Velencében.", "p": "William Shakespeare — melyik állítás NEM igaz?", "s": "Írók", "w": ["Shakespeare az angliai Stratford kisvárosában született.", "Darabjait a londoni Globe színházban játszották."]},
  {"a": "Regényének főhőse egy fiatal spanyol király.", "e": "Don Quijote idős vidéki nemes volt, nem király.", "p": "Cervantes — melyik állítás NEM igaz?", "s": "Írók", "w": ["Cervantes írta a Don Quijote című regényt.", "Spanyol író volt, katonaként is szolgált."]},
  {"a": "A Piroska és a farkas is Andersen meséje.", "e": "A Piroska és a farkas a Grimm testvérek gyűjtéséből ismert.", "p": "Hans Christian Andersen — melyik állítás NEM igaz?", "s": "Írók", "w": ["Andersen dán meseíró volt, Odenséban született.", "Ő írta A rút kiskacsa című mesét."]},
  {"a": "A Grimm testvérek maguk találták ki a meséiket.", "e": "A Grimmék mesélőktől gyűjtötték össze a történeteket.", "p": "A Grimm testvérek — melyik állítás NEM igaz?", "s": "Írók", "w": ["A Grimm testvérek német népmeséket gyűjtöttek össze.", "Nyelvészként nagy német szótáron is dolgoztak."]},
  {"a": "Tolsztoj élete végén irodalmi Nobel-díjat kapott.", "e": "Tolsztoj sosem kapott Nobel-díjat, bár többször jelölték.", "p": "Lev Tolsztoj — melyik állítás NEM igaz?", "s": "Írók", "w": ["Tolsztoj írta a Háború és béke című regényt.", "Orosz gróf volt, nagy birtokon élt."]},
  {"a": "Dickens leghíresebb regénye a Robinson Crusoe.", "e": "A Robinson Crusoe-t Daniel Defoe írta, jóval korábban.", "p": "Charles Dickens — melyik állítás NEM igaz?", "s": "Írók", "w": ["Dickens regényei folytatásokban jelentek meg újságokban.", "Gyerekként egy londoni gyárban kellett dolgoznia."]},
  {"a": "Christie írta a Sherlock Holmes-történeteket is.", "e": "Sherlock Holmes alakját Arthur Conan Doyle írta meg.", "p": "Agatha Christie — melyik állítás NEM igaz?", "s": "Írók", "w": ["Christie találta ki Hercule Poirot alakját.", "Könyveit több mint száz nyelvre lefordították."]},
  {"a": "A Nyomorultak a francia forradalom idején játszódik.", "e": "A Nyomorultak az 1830-as évek Párizsában játszódik.", "p": "Victor Hugo — melyik állítás NEM igaz?", "s": "Írók", "w": ["Hugo írta A párizsi Notre-Dame című regényt.", "Sokáig száműzetésben élt egy csatornai szigeten."]},
  {"a": "Mark Twain volt az író valódi neve.", "e": "Valódi neve Samuel Clemens volt, a Mark Twain álnév.", "p": "Mark Twain — melyik állítás NEM igaz?", "s": "Írók", "w": ["Twain a Mississippi partján töltötte a gyerekkorát.", "Ő írta meg Tom Sawyer kalandjait."]},
  {"a": "Mozart Bécsben született, és ott is nőtt fel.", "e": "Mozart Salzburgban született, Bécsbe felnőttként költözött.", "p": "Mozart — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["Mozart gyerekként európai udvarokban lépett fel.", "A Varázsfuvola című opera az ő műve."]},
  {"a": "Beethoven tíz szimfóniát fejezett be élete során.", "e": "Beethoven kilenc szimfóniát fejezett be, a tizedik vázlat maradt.", "p": "Beethoven — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["Beethoven Bonnban született, majd Bécsben lett híres.", "Romló hallása ellenére is komponált tovább."]},
  {"a": "Bach az operáiról vált világszerte ismertté.", "e": "Bach egyetlen operát sem írt, egyházi zenéje tette híressé.", "p": "Johann Sebastian Bach — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["Bach sok gyermeke közül többen is zenészek lettek.", "Lipcsében dolgozott hosszú éveken át kántorként."]},
  {"a": "Chopin hosszú, nyolcvan évig tartó életet élt.", "e": "Chopin mindössze harminckilenc évesen halt meg Párizsban.", "p": "Chopin — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["Chopin lengyel volt, de Párizsban élt felnőttként.", "Szinte csak zongorára írta a műveit."]},
  {"a": "Vivaldi életében egyetlen operát sem írt.", "e": "Vivaldi sok operát is írt a velencei színházaknak.", "p": "Vivaldi — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["Vivaldi írta A négy évszak című műveket.", "Velencében egy lányiskolában tanított zenét évekig."]},
  {"a": "A Carmen című opera szintén Verdi műve.", "e": "A Carment Georges Bizet francia zeneszerző írta.", "p": "Giuseppe Verdi — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["Verdi olasz operaszerző volt, az Aida az ő műve.", "Operáit a milánói Scalában is játszották."]},
  {"a": "Haydn Mozart tanára volt a salzburgi években.", "e": "Haydn Mozart barátja volt, és Beethovent tanította Bécsben.", "p": "Joseph Haydn — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["Haydn hosszú évekig az Esterházy családnál szolgált.", "Nagy szerepe volt a szimfónia kialakulásában."]},
  {"a": "Csajkovszkij szerezte a Bolero című zenét.", "e": "A Bolerót Maurice Ravel írta 1928-ban.", "p": "Csajkovszkij — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["Csajkovszkij írta a Diótörő című balettet.", "Orosz zeneszerző volt, fiatalon jogot tanult."]},
  {"a": "Wagner a zongoraversenyeiről lett igazán világhírű.", "e": "Wagnert az operái tették híressé, nem a zongoraművei.", "p": "Richard Wagner — melyik állítás NEM igaz?", "s": "Zeneszerzők", "w": ["Wagner saját operaházat építtetett magának Bayreuthban.", "Operáinak szövegkönyvét is ő maga írta."]},
  {"a": "Leonardo festette ki a Sixtus-kápolna mennyezetét.", "e": "A Sixtus-kápolna mennyezetét Michelangelo festette ki.", "p": "Leonardo da Vinci — melyik állítás NEM igaz?", "s": "Művészek", "w": ["Leonardo festette meg a Mona Lisa című híres képet.", "Repülő szerkezeteket is tervezett a jegyzeteiben."]},
  {"a": "A Dávid-szobrot egykor Rómában állították fel.", "e": "A Dávid-szobor Firenzében áll, nem Rómában.", "p": "Michelangelo — melyik állítás NEM igaz?", "s": "Művészek", "w": ["Michelangelo faragta ki a Dávid-szobrot márványból.", "A Sixtus-kápolna mennyezetét is ő festette."]},
  {"a": "Van Gogh Franciaországban született és ott nőtt fel.", "e": "Van Gogh Hollandiában született, felnőttként ment Franciaországba.", "p": "Van Gogh — melyik állítás NEM igaz?", "s": "Művészek", "w": ["Van Gogh festette a Csillagos éj című képet.", "Testvérével, Theóval sok levelet váltott évekig."]},
  {"a": "Picasso mindig ugyanabban a stílusban festett.", "e": "Picasso stílusa sokszor változott, a kék korszaktól a kubizmusig.", "p": "Picasso — melyik állítás NEM igaz?", "s": "Művészek", "w": ["Picasso Spanyolországban született, de Franciaországban élt.", "A kubizmus irányzat egyik megteremtője volt."]},
  {"a": "Monet a szobrairól is világhírűvé vált.", "e": "Monet festő volt, szobrokat nem készített.", "p": "Claude Monet — melyik állítás NEM igaz?", "s": "Művészek", "w": ["Monet a kertjét és a tavirózsáit sokszor megfestette.", "Az impresszionizmus az ő képéről kapta a nevét."]},
  {"a": "Rembrandt nagy vagyont hagyott a családjára.", "e": "Rembrandt csődbe ment, és szegényen halt meg.", "p": "Rembrandt — melyik állítás NEM igaz?", "s": "Művészek", "w": ["Rembrandt holland festő volt, sok önarcképet festett.", "Az Éjjeli őrjárat az ő nagy méretű képe."]},
  {"a": "Dalí az impresszionista festők közé tartozott.", "e": "Dalí a szürrealista irányzat legismertebb festője volt.", "p": "Salvador Dalí — melyik állítás NEM igaz?", "s": "Művészek", "w": ["Dalí spanyol festő volt, feltűnő bajuszt viselt.", "Képein gyakran elolvadó órák jelennek meg."]},
  {"a": "Rodin a szobrait fából faragta ki a műhelyében.", "e": "Rodin bronzból és márványból dolgozott, nem fából.", "p": "Auguste Rodin — melyik állítás NEM igaz?", "s": "Művészek", "w": ["Rodin híres szobra A gondolkodó címet viseli.", "Francia szobrász volt, és Párizsban dolgozott."]},
  {"a": "Vermeer több ezer képet festett élete során.", "e": "Vermeertől alig harmincöt festmény maradt fenn.", "p": "Vermeer — melyik állítás NEM igaz?", "s": "Művészek", "w": ["Vermeer holland festő volt, Delftben élt.", "A Leány gyöngy fülbevalóval az ő híres festménye."]}
]
$questions$::jsonb)
  with ordinality as question(item, ordinality);

do $validation$
begin
  if (
    select count(*) from public.quiz_questions
    where category_id = 'ket_igazsag' and is_active
  ) <> 253 then
    raise exception 'Két igazság és egy hazugság must contain exactly 253 active questions';
  end if;

  if exists (
    select 1
    from public.quiz_questions as question
    where question.category_id = 'ket_igazsag'
      and (
        cardinality(question.wrong_answers) <> 2
        or (
          select count(distinct lower(trim(answer)))
          from unnest(question.wrong_answers) as answer
        ) <> 2
        or exists (
          select 1
          from unnest(question.wrong_answers) as answer
          where lower(trim(answer)) = lower(trim(question.correct_answer))
        )
      )
  ) then
    raise exception 'Két igazság és egy hazugság: every question needs 2 distinct wrong answer(s)';
  end if;

  -- Scoped to the rows this migration inserts. The unscoped form also fires on
  -- a duplicate that was already in the bank -- "What was the Hanseatic League?"
  -- sits in both History and Time Traveler and has since August -- which says
  -- nothing about whether this batch is clean.
  if exists (
    select 1
    from public.quiz_questions as proposed
    join public.quiz_questions as existing
      on lower(trim(existing.prompt)) = lower(trim(proposed.prompt))
     and existing.id <> proposed.id
    where proposed.id like 'ketig\_%'
  ) then
    raise exception 'Két igazság és egy hazugság: a new prompt is already used by another question';
  end if;
end;
$validation$;
