-- Magyar irodalom: 415 questions in Hungarian.
--
-- Written so the correct answer is never the longest option -- the tell that
-- made the Psychology bank guessable without reading the prompt. All four
-- choices share one type and grammatical form.
insert into public.quiz_questions (
  id,
  category_id,
  prompt,
  correct_answer,
  wrong_answers,
  language_code,
  grade_level,
  subject,
  display_order,
  is_active
)
select
  'magyar_irodalom_' || lpad(question.ordinality::text, 4, '0'),
  'magyar_irodalom',
  question.item ->> 'p',
  question.item ->> 'a',
  array(select jsonb_array_elements_text(question.item -> 'w')),
  'hu',
  null,
  question.item ->> 's',
  question.ordinality::integer,
  true
from jsonb_array_elements($questions$
[
  {"a": "Petőfi Sándor", "p": "Ki írta a Nemzeti dal című verset?", "s": "Költők és versek", "w": ["Arany János", "Kölcsey Ferenc", "Vörösmarty Mihály"]},
  {"a": "Petőfi Sándor", "p": "Ki írta a János vitéz című elbeszélő költeményt?", "s": "Költők és versek", "w": ["Arany János", "Fazekas Mihály", "Vörösmarty Mihály"]},
  {"a": "Kukorica Jancsi", "p": "Ki a János vitéz főhőse?", "s": "Költők és versek", "w": ["Toldi Miklós", "Lúdas Matyi", "Bornemissza Gergely"]},
  {"a": "Iluskát", "p": "Kit szeret Kukorica Jancsi a János vitézben?", "s": "Költők és versek", "w": ["Melindát", "Tündét", "Vicuskát"]},
  {"a": "János vitéz", "p": "Milyen nevet kap Kukorica Jancsi a huszároknál?", "s": "Költők és versek", "w": ["Háry János", "Toldi Miklós", "Bolond Istók"]},
  {"a": "Tündérország", "p": "Melyik ország királya lesz János vitéz?", "s": "Költők és versek", "w": ["Franciaország", "Törökország", "Óriások országa"]},
  {"a": "Nagyfaluban", "p": "Melyik faluban él Toldi Miklós a mű elején?", "s": "Költők és versek", "w": ["Rodostóban", "Szalontán", "Nagyszalontán"]},
  {"a": "Bence", "p": "Ki Toldi Miklós hűséges öreg szolgája?", "s": "Költők és versek", "w": ["Tiborc", "Balga", "Jumurdzsák"]},
  {"a": "György", "p": "Hogy hívják Toldi Miklós irigy bátyját?", "s": "Költők és versek", "w": ["Lőrinc", "Bence", "Lajos"]},
  {"a": "Egy malomkövet", "p": "Mit dob Toldi a bátyja szolgái közé?", "s": "Költők és versek", "w": ["Egy kaszát", "Egy buzogányt", "Egy szekérrudat"]},
  {"a": "A szekér rúdját", "p": "Mit emel fel Toldi egy kézzel, hogy utat mutasson?", "s": "Költők és versek", "w": ["A malomkövet", "A vár kapuját", "Egy nagy zászlórudat"]},
  {"a": "Két farkassal", "p": "Milyen vadakkal küzd meg Toldi a nádasban?", "s": "Költők és versek", "w": ["Két medvével", "Egy vadkannal", "Három kuvasszal"]},
  {"a": "Egy megvadult bikát", "p": "Melyik állatot fékezi meg Toldi Pesten?", "s": "Költők és versek", "w": ["Egy dühöngő medvét", "Egy szilaj vadlovat", "Egy elszabadult farkast"]},
  {"a": "A cseh vitézzel", "p": "Kivel vív meg Toldi a dunai szigeten?", "s": "Költők és versek", "w": ["A török basával", "A német lovaggal", "A lengyel daliával"]},
  {"a": "Nagy Lajos", "p": "Melyik király fogadja szolgálatába Toldi Miklóst?", "s": "Költők és versek", "w": ["IV. Béla", "Szent István", "Mátyás király"]},
  {"a": "Toldi estéje", "p": "Melyik Arany-mű zárja a Toldi-trilógiát?", "s": "Költők és versek", "w": ["Toldi szerelme", "Buda halála", "Az elveszett alkotmány"]},
  {"a": "A Toldival", "p": "Melyik művével lett Arany János egy csapásra híres?", "s": "Költők és versek", "w": ["A Családi körrel", "A walesi bárdokkal", "Az Ágnes asszonnyal"]},
  {"a": "Nagyszalontán", "p": "Melyik városban volt Arany János jegyző?", "s": "Költők és versek", "w": ["Nagykőrösön", "Debrecenben", "Kiskunfélegyházán"]},
  {"a": "Nagykőrösön", "p": "Melyik városban tanított Arany János a gimnáziumban?", "s": "Költők és versek", "w": ["Szegeden", "Sárospatakon", "Nagyszalontán"]},
  {"a": "Arany János", "p": "Ki írta A walesi bárdok című balladát?", "s": "Költők és versek", "w": ["Petőfi Sándor", "Vajda János", "Vörösmarty Mihály"]},
  {"a": "Ötszáz", "p": "Hány bárd ment máglyára A walesi bárdokban?", "s": "Költők és versek", "w": ["Száz", "Ezer", "Háromszáz"]},
  {"a": "Montgomery", "p": "Melyik vár ura vendégeli meg Edward királyt?", "s": "Költők és versek", "w": ["Drégely", "Szigetvár", "Székesfehérvár"]},
  {"a": "Tetemre hívás", "p": "Melyik Arany-ballada hőse Bárczi Benő?", "s": "Költők és versek", "w": ["Ágnes asszony", "Vörös Rébék", "Szondi két apródja"]},
  {"a": "Ágnes asszony", "p": "Melyik Arany-ballada hőse mossa örökké a véres leplet?", "s": "Költők és versek", "w": ["Vörös Rébék", "Mátyás anyja", "Szondi két apródja"]},
  {"a": "Drégely alatt", "p": "Melyik vár alatt játszódik a Szondi két apródja?", "s": "Költők és versek", "w": ["Eger alatt", "Buda alatt", "Szigetvár falai alatt"]},
  {"a": "Mátyás anyja", "p": "Melyik Arany-ballada hőse Szilágyi Erzsébet?", "s": "Költők és versek", "w": ["Ágnes asszony", "V. László", "Szondi két apródja"]},
  {"a": "Hunorról és Magyarról", "p": "Kiről szól Arany Rege a csodaszarvasról című műve?", "s": "Költők és versek", "w": ["Attiláról és Budáról", "Álmosról és Árpádról", "Csabáról és Aladárról"]},
  {"a": "Kiskőrösön", "p": "Melyik városban született Petőfi Sándor?", "s": "Költők és versek", "w": ["Nagyszalontán", "Szabadszálláson", "Kiskunfélegyházán"]},
  {"a": "Arany Jánossal", "p": "Melyik költővel levelezett Petőfi a Toldi megjelenése után?", "s": "Költők és versek", "w": ["Vajda Jánossal", "Tompa Mihállyal", "Vörösmarty Mihállyal"]},
  {"a": "Füstbe ment terv", "p": "Melyik versben nem tudja Petőfi köszönteni az anyját?", "s": "Költők és versek", "w": ["Anyám tyúkja", "Egy estém otthon", "A jó öreg kocsmáros"]},
  {"a": "Anyám tyúkja", "p": "Melyik Petőfi-vers szól a szobában lakó jószágról?", "s": "Költők és versek", "w": ["Füstbe ment terv", "Megy a juhász szamáron", "Falu végén kurta kocsma"]},
  {"a": "Morzsa", "p": "Hogy hívják a kutyát az Anyám tyúkja című versben?", "s": "Költők és versek", "w": ["Bodri", "Sajó", "Bundás"]},
  {"a": "Koltón", "p": "Hol írta Petőfi a Szeptember végén című verset?", "s": "Költők és versek", "w": ["Pesten", "Szalontán", "Debrecenben"]},
  {"a": "A feleségéhez", "p": "Kihez szól a Szeptember végén című vers?", "s": "Költők és versek", "w": ["Az anyjához", "Arany Jánoshoz", "A szülőföldjéhez"]},
  {"a": "A Tiszáról", "p": "Melyik folyóról írt Petőfi híres verset?", "s": "Költők és versek", "w": ["A Dunáról", "A Marosról", "A Körösökről"]},
  {"a": "A pusztát", "p": "Melyik tájat magasztalja Petőfi Az alföld című versben?", "s": "Költők és versek", "w": ["A Kárpátokat", "Az erdélyi hegyeket", "A Balaton-felvidéket"]},
  {"a": "Az apostol", "p": "Melyik Petőfi-mű hőse Szilveszter?", "s": "Költők és versek", "w": ["János vitéz", "Bolond Istók", "A helység kalapácsa"]},
  {"a": "A helység kalapácsa", "p": "Melyik Petőfi-mű komikus eposz?", "s": "Költők és versek", "w": ["Az apostol", "János vitéz", "A természet vadvirága"]},
  {"a": "Pató Pál úr", "p": "Melyik Petőfi-vers hőse a halogató földesúr?", "s": "Költők és versek", "w": ["Az apostol", "A négyökrös szekér", "Falu végén kurta kocsma"]},
  {"a": "Egy gondolat bánt engemet", "p": "Melyik versében nem akar Petőfi ágyban meghalni?", "s": "Költők és versek", "w": ["A XIX. század költői", "Föltámadott a tenger", "Beszél a fákkal a bús őszi szél"]},
  {"a": "Vörösmarty Mihály", "p": "Ki írta A vén cigány című verset?", "s": "Költők és versek", "w": ["Petőfi Sándor", "Arany János", "Csokonai Vitéz Mihály"]},
  {"a": "Zalán futása", "p": "Melyik Vörösmarty-mű a honfoglalásról szóló eposz?", "s": "Költők és versek", "w": ["A vén cigány", "Csongor és Tünde", "Gondolatok a könyvtárban"]},
  {"a": "Szatmárcsekén", "p": "Melyik faluban írta Kölcsey a Himnuszt?", "s": "Költők és versek", "w": ["Koltón", "Szalontán", "Kiskunfélegyházán"]},
  {"a": "A Himnusz", "p": "Melyik vers alcíme: A magyar nép zivataros századaiból?", "s": "Költők és versek", "w": ["A Szózat", "A Nemzeti dal", "A walesi bárdok"]},
  {"a": "Egressy Béni", "p": "Ki zenésítette meg a Szózatot?", "s": "Költők és versek", "w": ["Erkel Ferenc", "Liszt Ferenc", "Kodály Zoltán"]},
  {"a": "A magyar kultúra napját", "p": "Melyik napot ünnepeljük a Himnusz születésnapján?", "s": "Költők és versek", "w": ["A költészet napját", "A magyar nyelv napját", "A magyar tudomány napját"]},
  {"a": "József Attiláé", "p": "Melyik költő születésnapja a magyar költészet napja?", "s": "Költők és versek", "w": ["Arany Jánosé", "Petőfi Sándoré", "Vörösmarty Mihályé"]},
  {"a": "Kölcsey Ferenc", "p": "Ki írta a Huszt című epigrammát?", "s": "Költők és versek", "w": ["Berzsenyi Dániel", "Janus Pannonius", "Vörösmarty Mihály"]},
  {"a": "A Parainesis", "p": "Melyik Kölcsey-mű intelem az unokaöccséhez?", "s": "Költők és versek", "w": ["A Huszt", "A Zrínyi dala", "A Vanitatum vanitas"]},
  {"a": "Vajda János", "p": "Ki írta a Húsz év múlva című verset?", "s": "Költők és versek", "w": ["Arany János", "Tóth Árpád", "Juhász Gyula"]},
  {"a": "Vajda Jánosé", "p": "Melyik költő múzsája volt Gina?", "s": "Költők és versek", "w": ["Ady Endréé", "Petőfi Sándoré", "Csokonai Vitéz Mihályé"]},
  {"a": "1908-ban", "p": "Melyik évben indult a Nyugat című folyóirat?", "s": "Nyugat és a huszadik század", "w": ["1919-ben", "1890-ben", "1937-ben"]},
  {"a": "Ady Endrét", "p": "Ki volt a Nyugat első nemzedékének vezéralakja?", "s": "Nyugat és a huszadik század", "w": ["Tóth Árpádot", "Juhász Gyulát", "Kosztolányi Dezsőt"]},
  {"a": "Új versek", "p": "Melyik kötete hozta meg Ady hírnevét 1906-ban?", "s": "Nyugat és a huszadik század", "w": ["Vér és arany", "A halottak élén", "Az Illés szekerén"]},
  {"a": "Nagyváradon", "p": "Melyik városban dolgozott újságíróként a fiatal Ady?", "s": "Nyugat és a huszadik század", "w": ["Szegeden", "Debrecenben", "Székesfehérvárott"]},
  {"a": "Párizsba", "p": "Melyik nagyvárosba utazott Ady Lédával?", "s": "Nyugat és a huszadik század", "w": ["Bécsbe", "Rómába", "Konstantinápolyba"]},
  {"a": "Csinszka", "p": "Ki volt Ady Endre felesége?", "s": "Nyugat és a huszadik század", "w": ["Léda", "Lilla", "Szendrey Júlia"]},
  {"a": "A magyar Ugaron", "p": "Melyik Ady-vers szól az elvadult, műveletlen magyar tájról?", "s": "Nyugat és a huszadik század", "w": ["Héja-nász az avaron", "Lédával a bálban", "Emlékezés egy nyár-éjszakára"]},
  {"a": "Párisban járt az Ősz", "p": "Melyik Ady-vers szól az őszi Párizsról?", "s": "Nyugat és a huszadik század", "w": ["A Tisza-parton", "Harc a Nagyúrral", "Emlékezés egy nyár-éjszakára"]},
  {"a": "Babits Mihály", "p": "Ki írta a Jónás könyve című művet?", "s": "Nyugat és a huszadik század", "w": ["Juhász Gyula", "Szabó Lőrinc", "Kosztolányi Dezső"]},
  {"a": "A gólyakalifa", "p": "Melyik Babits-regény hőse Tábory Elemér?", "s": "Nyugat és a huszadik század", "w": ["Halálfiai", "Timár Virgil fia", "Az európai irodalom története"]},
  {"a": "Az Isteni színjátékot", "p": "Melyik nagy olasz művet fordította magyarra Babits?", "s": "Nyugat és a huszadik század", "w": ["A Dekameront", "Az Új életet", "A Megszabadított Jeruzsálemet"]},
  {"a": "Édes Anna", "p": "Melyik Kosztolányi-regény hőse egy cseléd?", "s": "Nyugat és a huszadik század", "w": ["Pacsirta", "Aranysárkány", "Nero, a véres költő"]},
  {"a": "Pacsirta", "p": "Melyik Kosztolányi-regény hőse a szülei mellett élő lány?", "s": "Nyugat és a huszadik század", "w": ["Édes Anna", "Aranysárkány", "Nero, a véres költő"]},
  {"a": "Kosztolányi Dezső", "p": "Ki írta az Esti Kornél című novelláskötetet?", "s": "Nyugat és a huszadik század", "w": ["Krúdy Gyula", "Karinthy Frigyes", "Tersánszky Józsi Jenő"]},
  {"a": "Sárszegen", "p": "Melyik kitalált városban játszódik a Pacsirta?", "s": "Nyugat és a huszadik század", "w": ["Árkodon", "Glogován", "Nagyfaluban"]},
  {"a": "Aranysárkány", "p": "Melyik Kosztolányi-regény hőse Novák Antal tanár?", "s": "Nyugat és a huszadik század", "w": ["Édes Anna", "Pacsirta", "Nero, a véres költő"]},
  {"a": "Kosztolányi Dezső", "p": "Ki írta A szegény kisgyermek panaszai című kötetet?", "s": "Nyugat és a huszadik század", "w": ["Juhász Gyula", "Karinthy Frigyes", "Tersánszky Józsi Jenő"]},
  {"a": "Juhász Gyula", "p": "Ki írta az Anna örök című verset?", "s": "Nyugat és a huszadik század", "w": ["Tóth Árpád", "Szabó Lőrinc", "Kosztolányi Dezső"]},
  {"a": "Tóth Árpád", "p": "Ki írta az Elégia egy rekettyebokorhoz című verset?", "s": "Nyugat és a huszadik század", "w": ["Ady Endre", "Juhász Gyula", "Kosztolányi Dezső"]},
  {"a": "Budapesten", "p": "Melyik városban született József Attila?", "s": "Nyugat és a huszadik század", "w": ["Szegeden", "Szabadkán", "Balatonszárszón"]},
  {"a": "Mosónő volt", "p": "Mi volt József Attila édesanyjának a foglalkozása?", "s": "Nyugat és a huszadik század", "w": ["Varrónő volt", "Tanítónő volt", "Cselédlány volt"]},
  {"a": "Tiszta szívvel", "p": "Melyik verse miatt küldték el József Attilát a szegedi egyetemről?", "s": "Nyugat és a huszadik század", "w": ["Mama", "Levegőt!", "Curriculum vitae"]},
  {"a": "Mama", "p": "Melyik József Attila-vers szól a ruhát mosó anyáról?", "s": "Nyugat és a huszadik század", "w": ["Altató", "Óda", "Kertész leszek"]},
  {"a": "Balázst", "p": "Kit ringat el a dal József Attila Altató című versében?", "s": "Nyugat és a huszadik század", "w": ["Lacit", "Petit", "Bandikát"]},
  {"a": "A Dunánál", "p": "Melyik József Attila-vers kezdődik a rakodóparton?", "s": "Nyugat és a huszadik század", "w": ["Óda", "Eszmélet", "Külvárosi éj"]},
  {"a": "32 éves", "p": "Hány éves volt József Attila a Születésnapomra írásakor?", "s": "Nyugat és a huszadik század", "w": ["18 éves", "26 éves", "40 éves"]},
  {"a": "Balatonszárszón", "p": "Hol halt meg József Attila 1937-ben?", "s": "Nyugat és a huszadik század", "w": ["Budapesten", "Szegeden", "Balatonalmádiban"]},
  {"a": "A Bori noteszben", "p": "Melyik füzetben maradtak fenn Radnóti utolsó versei?", "s": "Nyugat és a huszadik század", "w": ["A Tajtékos égben", "A Meredek útban", "Az Ikrek hava füzetben"]},
  {"a": "Razglednicák", "p": "Melyik Radnóti-versciklus négy rövid darabból áll?", "s": "Nyugat és a huszadik század", "w": ["Eclogák", "Nyolcadik ecloga", "Erőltetett menet"]},
  {"a": "Nem tudhatom", "p": "Melyik Radnóti-vers kezdődik a szülőhaza vallomásával?", "s": "Nyugat és a huszadik század", "w": ["Hetedik ecloga", "Erőltetett menet", "Levél a hitveshez"]},
  {"a": "Az eclogát", "p": "Milyen ókori műfajt újított fel Radnóti a háború alatt?", "s": "Nyugat és a huszadik század", "w": ["Az ódát", "Az epigrammát", "A hősi eposzt"]},
  {"a": "Szabó Lőrinc", "p": "Ki írta a Lóci óriás lesz című verset?", "s": "Nyugat és a huszadik század", "w": ["Weöres Sándor", "Nemes Nagy Ágnes", "Kosztolányi Dezső"]},
  {"a": "Illyés Gyula", "p": "Ki írta az Egy mondat a zsarnokságról című verset?", "s": "Nyugat és a huszadik század", "w": ["Nagy László", "Weöres Sándor", "Pilinszky János"]},
  {"a": "Puszták népe", "p": "Melyik Illyés-mű a pusztai cselédek életéről szól?", "s": "Nyugat és a huszadik század", "w": ["Kháron ladikja", "Hunok Párisban", "Egy mondat a zsarnokságról"]},
  {"a": "Weöres Sándor", "p": "Ki írta a Bóbita című gyermekverset?", "s": "Nyugat és a huszadik század", "w": ["Nagy László", "Csukás István", "Nemes Nagy Ágnes"]},
  {"a": "Galagonya", "p": "Melyik Weöres-vers szól az őszi éjjel izzó bokorról?", "s": "Nyugat és a huszadik század", "w": ["Bóbita", "Száncsengő", "Buba éneke"]},
  {"a": "Psyché", "p": "Melyik Weöres-mű egy kitalált költőnő verseskönyve?", "s": "Nyugat és a huszadik század", "w": ["Bóbita", "Rongyszőnyeg", "A holdbeli csónakos"]},
  {"a": "Pilinszky János", "p": "Ki írta az Apokrif című verset?", "s": "Nyugat és a huszadik század", "w": ["Nagy László", "Illyés Gyula", "Nemes Nagy Ágnes"]},
  {"a": "Nagy László", "p": "Ki írta a Ki viszi át a Szerelmet című verset?", "s": "Nyugat és a huszadik század", "w": ["Illyés Gyula", "Weöres Sándor", "Pilinszky János"]},
  {"a": "Az egyperces novellát", "p": "Milyen műfajt tett híressé Örkény István?", "s": "Nyugat és a huszadik század", "w": ["A tárcát", "A karcolatot", "Az elbeszélő költeményt"]},
  {"a": "Tóték", "p": "Melyik Örkény-dráma hőse a Tót család?", "s": "Nyugat és a huszadik század", "w": ["Macskajáték", "Pisti a vérzivatarban", "Az ötödik pecsét"]},
  {"a": "Így írtok ti", "p": "Melyik Karinthy-kötet híres írók stílusát figurázza ki?", "s": "Nyugat és a huszadik század", "w": ["Tanár úr kérem", "Görbe tükör", "Utazás a koponyám körül"]},
  {"a": "Tanár úr kérem", "p": "Melyik Karinthy-kötet szól a diákévekről?", "s": "Nyugat és a huszadik század", "w": ["Így írtok ti", "Capillária", "Utazás a koponyám körül"]},
  {"a": "Szindbád", "p": "Melyik Krúdy-hős járja a régi Magyarország vendéglőit?", "s": "Nyugat és a huszadik század", "w": ["Esti Kornél", "Kakuk Marci", "Nyilas Misi"]},
  {"a": "Iskola a határon", "p": "Melyik Ottlik-regény katonaiskolában játszódik?", "s": "Nyugat és a huszadik század", "w": ["Iszony", "Rozsdatemető", "A befejezetlen mondat"]},
  {"a": "Németh László", "p": "Ki írta az Iszony című regényt?", "s": "Nyugat és a huszadik század", "w": ["Déry Tibor", "Sánta Ferenc", "Kosztolányi Dezső"]},
  {"a": "Góg és Magóg fia vagyok én", "p": "Melyik Ady-vers kezdődik a bibliai Góg és Magóg nevével?", "s": "Nyugat és a huszadik század", "w": ["A magyar Ugaron", "A Tisza-parton", "Emlékezés egy nyár-éjszakára"]},
  {"a": "Komáromban", "p": "Melyik városban született Jókai Mór?", "s": "Regények és íróik", "w": ["Szabadkán", "Debrecenben", "Kiskunfélegyházán"]},
  {"a": "Jókai Mór", "p": "Ki írta A kőszívű ember fiai című regényt?", "s": "Regények és íróik", "w": ["Mikszáth Kálmán", "Móricz Zsigmond", "Kemény Zsigmond"]},
  {"a": "Jókai Mór", "p": "Ki írta az Egy magyar nábob című regényt?", "s": "Regények és íróik", "w": ["Eötvös József", "Mikszáth Kálmán", "Kemény Zsigmond"]},
  {"a": "Egy magyar nábob", "p": "Melyik Jókai-regény folytatása a Kárpáthy Zoltán?", "s": "Regények és íróik", "w": ["Az arany ember", "Fekete gyémántok", "A kőszívű ember fiai"]},
  {"a": "Laborfalvi Róza", "p": "Ki volt Jókai Mór első felesége?", "s": "Regények és íróik", "w": ["Szendrey Júlia", "Vajda Julianna", "Déryné Széppataki Róza"]},
  {"a": "Mikszáth Kálmán", "p": "Ki írta A Noszty fiú esete Tóth Marival című regényt?", "s": "Regények és íróik", "w": ["Móricz Zsigmond", "Jókai Mór", "Kosztolányi Dezső"]},
  {"a": "Beszterce ostroma", "p": "Melyik Mikszáth-regény hőse Pongrácz István gróf?", "s": "Regények és íróik", "w": ["Különös házasság", "A fekete város", "Szent Péter esernyője"]},
  {"a": "Különös házasság", "p": "Melyik Mikszáth-regény hőse Buttler János gróf?", "s": "Regények és íróik", "w": ["A fekete város", "Beszterce ostroma", "A Noszty fiú esete Tóth Marival"]},
  {"a": "Az a fekete folt", "p": "Melyik novella hőse a juhász Olej Tamás?", "s": "Regények és íróik", "w": ["A néhai bárány", "Bede Anna tartozása", "Szegény Gélyi János lovai"]},
  {"a": "Hét krajcár", "p": "Melyik novellával lett híres Móricz Zsigmond 1908-ban?", "s": "Regények és íróik", "w": ["Barbárok", "Tragédia", "Szegény emberek"]},
  {"a": "Móricz Zsigmond", "p": "Ki írta a Légy jó mindhalálig című regényt?", "s": "Regények és íróik", "w": ["Gárdonyi Géza", "Móra Ferenc", "Kosztolányi Dezső"]},
  {"a": "Rokonok", "p": "Melyik Móricz-regény hőse Kopjáss István?", "s": "Regények és íróik", "w": ["Úri muri", "Árvácska", "Boldog ember"]},
  {"a": "Úri muri", "p": "Melyik Móricz-regény hőse Szakhmáry Zoltán?", "s": "Regények és íróik", "w": ["Rokonok", "Sárarany", "Az Isten háta mögött"]},
  {"a": "Árvácska", "p": "Melyik Móricz-regény hősnője egy állami gondozott kislány?", "s": "Regények és íróik", "w": ["Pillangó", "Boldog ember", "Az Isten háta mögött"]},
  {"a": "Báthory Gábor", "p": "Melyik erdélyi fejedelem a hőse Móricz Tündérkert című regényének?", "s": "Regények és íróik", "w": ["Bethlen Gábor", "Bocskai István", "Rákóczi György"]},
  {"a": "Gárdonyi Géza", "p": "Ki írta az Egri csillagok című regényt?", "s": "Regények és íróik", "w": ["Jókai Mór", "Móra Ferenc", "Mikszáth Kálmán"]},
  {"a": "Egerben", "p": "Melyik városban élt és halt meg Gárdonyi Géza?", "s": "Regények és íróik", "w": ["Szegeden", "Komáromban", "Nagyszalontán"]},
  {"a": "A láthatatlan ember", "p": "Melyik Gárdonyi-regény játszódik Attila udvarában?", "s": "Regények és íróik", "w": ["Isten rabjai", "Egri csillagok", "Szunyoghy miatyánkja"]},
  {"a": "Isten rabjai", "p": "Melyik Gárdonyi-regény szól Árpád-házi Margitról?", "s": "Regények és íróik", "w": ["Ida regénye", "Ábel és Eszter", "A láthatatlan ember"]},
  {"a": "Móra Ferenc", "p": "Ki írta a Kincskereső kisködmön című regényt?", "s": "Regények és íróik", "w": ["Gárdonyi Géza", "Fekete István", "Mikszáth Kálmán"]},
  {"a": "Molnár Ferenc", "p": "Ki írta A Pál utcai fiúk című regényt?", "s": "Regények és íróik", "w": ["Móra Ferenc", "Csukás István", "Kosztolányi Dezső"]},
  {"a": "Liliom", "p": "Melyik Molnár-színmű hőse egy hintáslegény?", "s": "Regények és íróik", "w": ["Az ördög", "A testőr", "Játék a kastélyban"]},
  {"a": "Szabó Magda", "p": "Ki írta az Abigél című regényt?", "s": "Regények és íróik", "w": ["Kaffka Margit", "Janikovszky Éva", "Nemes Nagy Ágnes"]},
  {"a": "Az ajtó", "p": "Melyik Szabó Magda-regény hőse Szeredás Emerenc?", "s": "Regények és íróik", "w": ["Freskó", "Katalin utca", "Régimódi történet"]},
  {"a": "Fekete István", "p": "Ki írta a Tüskevár című regényt?", "s": "Regények és íróik", "w": ["Móra Ferenc", "Csukás István", "Gárdonyi Géza"]},
  {"a": "Vuk", "p": "Melyik Fekete István-regény hőse egy rókakölyök?", "s": "Regények és íróik", "w": ["Kele", "Bogáncs", "Tüskevár"]},
  {"a": "Bogáncs", "p": "Melyik Fekete István-regény hőse egy puli kutya?", "s": "Regények és íróik", "w": ["Vuk", "Kele", "Tüskevár"]},
  {"a": "A gólya", "p": "Melyik állat a főhőse Fekete István Kele című regényének?", "s": "Regények és íróik", "w": ["A róka", "A vidra", "A fecske"]},
  {"a": "Eötvös József", "p": "Ki írta A falu jegyzője című regényt?", "s": "Regények és íróik", "w": ["Kemény Zsigmond", "Jókai Mór", "Mikszáth Kálmán"]},
  {"a": "Tamási Áron", "p": "Ki írta az Ábel a rengetegben című regényt?", "s": "Regények és íróik", "w": ["Nyirő József", "Fekete István", "Móricz Zsigmond"]},
  {"a": "A 17. századról", "p": "Melyik század Erdélyéről szól Móricz nagy trilógiája?", "s": "Regények és íróik", "w": ["A 15. századról", "A 19. századról", "A honfoglalás koráról"]},
  {"a": "Az arany ember", "p": "Melyik Jókai-regény hőse Tímár Mihály?", "s": "Regények és íróik", "w": ["Fekete gyémántok", "Szegény gazdagok", "A kőszívű ember fiai"]},
  {"a": "Szent Péter esernyője", "p": "Melyik Mikszáth-regény szól egy piros esernyőről?", "s": "Regények és íróik", "w": ["A fekete város", "Beszterce ostroma", "A Noszty fiú esete Tóth Marival"]},
  {"a": "Dobó István", "p": "Ki védte 1552-ben Eger várát az Egri csillagokban?", "s": "Regényhősök és helyszínek", "w": ["Török Bálint", "Mekcsey István", "Bornemissza Gergely"]},
  {"a": "Egri csillagok", "p": "Melyik regény hőse Bornemissza Gergely?", "s": "Regényhősök és helyszínek", "w": ["Isten rabjai", "A láthatatlan ember", "A kőszívű ember fiai"]},
  {"a": "Cecey Évát", "p": "Kit szeret Bornemissza Gergely az Egri csillagokban?", "s": "Regényhősök és helyszínek", "w": ["Iluskát", "Melindát", "Vitay Ginát"]},
  {"a": "Jumurdzsák", "p": "Ki a félszemű török az Egri csillagokban?", "s": "Regényhősök és helyszínek", "w": ["Ali basa", "Szulejmán", "Török Bálint"]},
  {"a": "Közlegény", "p": "Milyen rangja van egyedül Nemecseknek a fiúk között?", "s": "Regényhősök és helyszínek", "w": ["Hadnagy", "Kapitány", "Főhadnagy"]},
  {"a": "Boka János", "p": "Ki a Pál utcai fiúk vezére?", "s": "Regényhősök és helyszínek", "w": ["Csónakos", "Nemecsek Ernő", "Geréb Dezső"]},
  {"a": "Áts Feri", "p": "Ki a vörösingesek vezére A Pál utcai fiúkban?", "s": "Regényhősök és helyszínek", "w": ["Boka János", "Geréb Dezső", "Nemecsek Ernő"]},
  {"a": "Geréb Dezső", "p": "Ki árulja el a Pál utcai fiúkat?", "s": "Regényhősök és helyszínek", "w": ["Csónakos", "Nemecsek Ernő", "Áts Feri"]},
  {"a": "Grundnak", "p": "Minek nevezik a fiúk a telket A Pál utcai fiúkban?", "s": "Regényhősök és helyszínek", "w": ["Pályának", "Tanyának", "Játszótérnek"]},
  {"a": "A Füvészkertben", "p": "Hol tanyáznak a vörösingesek A Pál utcai fiúkban?", "s": "Regényhősök és helyszínek", "w": ["A grundon", "A Múzeumkertben", "A Margitszigeten"]},
  {"a": "Einstand!", "p": "Mit kiáltanak a Pásztor fiúk, amikor elveszik a golyókat?", "s": "Regényhősök és helyszínek", "w": ["Zsákmány!", "Vigyázz!", "Ez a mienk!"]},
  {"a": "Gittet", "p": "Mit rágtak a gittegylet tagjai A Pál utcai fiúkban?", "s": "Regényhősök és helyszínek", "w": ["Mézet", "Viaszt", "Fenyőgyantát"]},
  {"a": "Tüdőgyulladásban", "p": "Milyen betegségben hal meg Nemecsek?", "s": "Regényhősök és helyszínek", "w": ["Kolerában", "Tífuszban", "Agyhártyagyulladásban"]},
  {"a": "Senki szigete", "p": "Hogy hívják a szigetet, ahová Tímár Mihály menekül?", "s": "Regényhősök és helyszínek", "w": ["Margitsziget", "Csepel-sziget", "Az Aranysziget"]},
  {"a": "Szent Borbála", "p": "Hogy hívják a hajót Az arany emberben?", "s": "Regényhősök és helyszínek", "w": ["Szent Erzsébet", "Szent Katalin", "Szent Margit"]},
  {"a": "A Vaskapunál", "p": "Melyik dunai szorosnál kezdődik Az arany ember?", "s": "Regényhősök és helyszínek", "w": ["A Dunakanyarnál", "A Dévényi-kapunál", "A visegrádi szorosnál"]},
  {"a": "Három", "p": "Hány fia van a kőszívű embernek?", "s": "Regényhősök és helyszínek", "w": ["Kettő", "Négy", "Öt"]},
  {"a": "Jenő", "p": "Melyik Baradlay fiú hal meg a bátyja helyett?", "s": "Regényhősök és helyszínek", "w": ["Ödön", "Richárd", "Kázmér"]},
  {"a": "Ödön helyett", "p": "Kinek a nevében megy a halálba Baradlay Jenő?", "s": "Regényhősök és helyszínek", "w": ["Richárd helyett", "Az apja helyett", "Az anyja helyett"]},
  {"a": "Nyilas Misi", "p": "Ki a Légy jó mindhalálig főhőse?", "s": "Regényhősök és helyszínek", "w": ["Orczy Bálint", "Pósalaky úr", "Doroghy Sanyi"]},
  {"a": "Debrecenben", "p": "Melyik városban játszódik a Légy jó mindhalálig?", "s": "Regényhősök és helyszínek", "w": ["Szegeden", "Egerben", "Székesfehérvárott"]},
  {"a": "Pósalaky úrnak", "p": "Kinek olvas fel újságot Nyilas Misi?", "s": "Regényhősök és helyszínek", "w": ["Orczy Bálintnak", "Valkay tanár úrnak", "Doroghy Sanyikának"]},
  {"a": "Glogován", "p": "Melyik faluban játszódik a Szent Péter esernyője?", "s": "Regényhősök és helyszínek", "w": ["Árkodon", "Sárszegen", "Nagyfaluban"]},
  {"a": "Wibra Gyuri", "p": "Ki keresi az esernyő titkát a Szent Péter esernyőjében?", "s": "Regényhősök és helyszínek", "w": ["Bélyi János", "Gregorics Pál", "Pongrácz István"]},
  {"a": "Veronka", "p": "Hogy hívják a papkisasszonyt a Szent Péter esernyőjében?", "s": "Regényhősök és helyszínek", "w": ["Apolka", "Timéa", "Tóth Mari"]},
  {"a": "A Matulában", "p": "Hol tanul Vitay Gina az Abigél című regényben?", "s": "Regényhősök és helyszínek", "w": ["A Kollégiumban", "A Füvészkertben", "A debreceni gimnáziumban"]},
  {"a": "Árkodon", "p": "Melyik kitalált városban áll a Matula intézet?", "s": "Regényhősök és helyszínek", "w": ["Glogován", "Sárszegen", "Nagyfaluban"]},
  {"a": "Kőnig tanár úr", "p": "Ki rejtőzik Abigél alakja mögött?", "s": "Regényhősök és helyszínek", "w": ["Kalmár tanár úr", "Zsuzsanna nővér", "Torma Gedeon igazgató"]},
  {"a": "A szobor korsójába", "p": "Hová teszik a lányok a kéréseiket az Abigélben?", "s": "Regényhősök és helyszínek", "w": ["A kápolna padjára", "Az igazgató fiókjába", "A könyvtár egyik könyvébe"]},
  {"a": "Ladó Gyula Lajos", "p": "Mi Tutajos igazi neve a Tüskevárban?", "s": "Regényhősök és helyszínek", "w": ["Pondoray Béla", "Matula Gergely", "Bornemissza Gergely"]},
  {"a": "Matula", "p": "Ki a Tüskevár öreg pásztora és tanítómestere?", "s": "Regényhősök és helyszínek", "w": ["Bütyök", "Tutajos", "Nancsi néni"]},
  {"a": "A Kis-Balatonnál", "p": "Hol játszódik a Tüskevár?", "s": "Regényhősök és helyszínek", "w": ["A Tisza mentén", "A Hortobágyon", "A Balaton-felvidéken"]},
  {"a": "Karak", "p": "Ki neveli fel Vukot a szülei halála után?", "s": "Regényhősök és helyszínek", "w": ["Kag", "Iny", "A Simabőrű"]},
  {"a": "Simabőrűnek", "p": "Hogy hívja Vuk az embert a regényben?", "s": "Regényhősök és helyszínek", "w": ["Kétlábúnak", "Vadásznak", "Csupaszképűnek"]},
  {"a": "Egy", "p": "Hány feje van Süsünek, Csukás István sárkányának?", "s": "Regényhősök és helyszínek", "w": ["Kettő", "Három", "Hét"]},
  {"a": "Csukás István", "p": "Ki írta a Pom Pom meséi című könyvet?", "s": "Regényhősök és helyszínek", "w": ["Lázár Ervin", "Fekete István", "Janikovszky Éva"]},
  {"a": "Írisz", "p": "Ki a Tündér Lala című meseregény királynője?", "s": "Regényhősök és helyszínek", "w": ["Tünde", "Ilma", "Amalfi"]},
  {"a": "Kárpáthy János", "p": "Melyik Jókai-hős a gazdag öreg nábob?", "s": "Regényhősök és helyszínek", "w": ["Tímár Mihály", "Baradlay Ödön", "Szentirmay Rudolf"]},
  {"a": "Nedec várát", "p": "Melyik várat védi Pongrácz István gróf Mikszáthnál?", "s": "Regényhősök és helyszínek", "w": ["Eger várát", "Drégely várát", "Szigetvár falait"]},
  {"a": "Katona József", "p": "Melyik magyar szerző írta a Bánk bánt?", "s": "Drámák és színház", "w": ["Madách Imre", "Kisfaludy Károly", "Vörösmarty Mihály"]},
  {"a": "Gertrudis", "p": "Ki a királyné a Bánk bánban?", "s": "Drámák és színház", "w": ["Melinda", "Izidóra", "Boncza Berta"]},
  {"a": "Melinda", "p": "Ki Bánk bán felesége a drámában?", "s": "Drámák és színház", "w": ["Gertrudis", "Izidóra", "Tünde"]},
  {"a": "Tiborc", "p": "Ki a szegény paraszt a Bánk bánban?", "s": "Drámák és színház", "w": ["Biberach", "Petur bán", "Mikhál bán"]},
  {"a": "Ottó", "p": "Ki a királyné öccse a Bánk bánban?", "s": "Drámák és színház", "w": ["Biberach", "Tiborc", "Endre"]},
  {"a": "Petur bán", "p": "Ki az elégedetlen urak vezére a Bánk bánban?", "s": "Drámák és színház", "w": ["Mikhál bán", "Simon bán", "Biberach"]},
  {"a": "II. Endre", "p": "Melyik magyar király szerepel a Bánk bánban?", "s": "Drámák és színház", "w": ["IV. Béla", "Nagy Lajos", "Szent István"]},
  {"a": "Erkel Ferenc", "p": "Ki írta a Bánk bán operáját?", "s": "Drámák és színház", "w": ["Liszt Ferenc", "Egressy Béni", "Kodály Zoltán"]},
  {"a": "Madách Imre", "p": "Melyik magyar szerző írta Az ember tragédiáját?", "s": "Drámák és színház", "w": ["Katona József", "Vörösmarty Mihály", "Csokonai Vitéz Mihály"]},
  {"a": "Tizenötből", "p": "Hány színből áll Az ember tragédiája?", "s": "Drámák és színház", "w": ["Tizenkettőből", "Tizenháromból", "Huszonegyből"]},
  {"a": "Ádám, Éva és Lucifer", "p": "Ki a három főszereplő Az ember tragédiájában?", "s": "Drámák és színház", "w": ["Bánk, Melinda és Ottó", "Csongor, Tünde és Balga", "Toldi, Bence és a király"]},
  {"a": "Arany János", "p": "Melyik költő ajánlotta kiadásra Az ember tragédiáját?", "s": "Drámák és színház", "w": ["Petőfi Sándor", "Vajda János", "Vörösmarty Mihály"]},
  {"a": "A falanszterben", "p": "Melyik színben él munkásként Ádám a Tragédiában?", "s": "Drámák és színház", "w": ["Athénban", "Prágában", "Konstantinápolyban"]},
  {"a": "Az athéniban", "p": "Melyik színben lép fel Ádám Miltiadészként?", "s": "Drámák és színház", "w": ["A rómaiban", "A prágaiban", "A konstantinápolyiban"]},
  {"a": "Kepler", "p": "Melyik csillagász Ádám a prágai színben?", "s": "Drámák és színház", "w": ["Galilei", "Kopernikusz", "Miltiadész"]},
  {"a": "Az eszkimó szín", "p": "Melyik jelenet zárja Ádám álmát a Tragédiában?", "s": "Drámák és színház", "w": ["A londoni szín", "A párizsi szín", "A konstantinápolyi szín"]},
  {"a": "Vörösmarty Mihály", "p": "Ki írta a Csongor és Tünde című drámai költeményt?", "s": "Drámák és színház", "w": ["Katona József", "Madách Imre", "Csokonai Vitéz Mihály"]},
  {"a": "Balga", "p": "Ki Csongor hűséges szolgája?", "s": "Drámák és színház", "w": ["Bence", "Tiborc", "Biberach"]},
  {"a": "Mirígy", "p": "Ki a gonosz boszorkány a Csongor és Tündében?", "s": "Drámák és színház", "w": ["Ledér", "Ilma", "Az Éj királynője"]},
  {"a": "Ilma", "p": "Ki Tünde szolgálója a Csongor és Tündében?", "s": "Drámák és színház", "w": ["Ledér", "Mirígy", "Melinda"]},
  {"a": "Három", "p": "Hány ördögfi civakodik a Csongor és Tündében?", "s": "Drámák és színház", "w": ["Kettő", "Négy", "Hét"]},
  {"a": "1837-ben", "p": "Melyik évben nyílt meg a pesti Nemzeti Színház?", "s": "Drámák és színház", "w": ["1790-ben", "1848-ban", "1861-ben"]},
  {"a": "Ágis tragédiája", "p": "Melyik mű a magyar felvilágosodás nyitó drámája?", "s": "Drámák és színház", "w": ["Bánk bán", "Csongor és Tünde", "Az ember tragédiája"]},
  {"a": "Szigligeti Ede", "p": "Ki írta a Liliomfi című vígjátékot?", "s": "Drámák és színház", "w": ["Katona József", "Kisfaludy Károly", "Molnár Ferenc"]},
  {"a": "Fáklyaláng", "p": "Melyik Illyés-dráma szól Kossuthról és Görgeyről?", "s": "Drámák és színház", "w": ["Tóték", "Macskajáték", "Az ember tragédiája"]},
  {"a": "Kassán", "p": "Melyik városban mutatták be először sikerrel a Bánk bánt?", "s": "Drámák és színház", "w": ["Pesten", "Kolozsvárott", "Székesfehérvárott"]},
  {"a": "A Halotti beszéd", "p": "Melyik a legrégibb ismert magyar nyelvű szöveg?", "s": "Régi magyar irodalom", "w": ["A Szózat", "Az Ómagyar Mária-siralom", "A Szigeti veszedelem"]},
  {"a": "Az Ómagyar Mária-siralom", "p": "Melyik a legrégibb ismert magyar nyelvű vers?", "s": "Régi magyar irodalom", "w": ["Egy katonaének", "A Szigeti veszedelem", "A Halotti beszéd és könyörgés"]},
  {"a": "A Pray-kódex", "p": "Melyik kódex őrizte meg a Halotti beszédet?", "s": "Régi magyar irodalom", "w": ["A Leuveni kódex", "A Bécsi kódex", "A Müncheni kódex"]},
  {"a": "Latinul", "p": "Milyen nyelven írta verseit Janus Pannonius?", "s": "Régi magyar irodalom", "w": ["Magyarul", "Németül", "Ógörögül"]},
  {"a": "Pécsé", "p": "Melyik város püspöke volt Janus Pannonius?", "s": "Régi magyar irodalom", "w": ["Egeré", "Váradé", "Esztergomé"]},
  {"a": "Egy dunántúli mandulafáról", "p": "Melyik Janus Pannonius-vers szól a korán virágzó fáról?", "s": "Régi magyar irodalom", "w": ["Búcsú Váradtól", "Pannónia dicsérete", "Mikor a táborban megbetegedett"]},
  {"a": "Balassi Bálintot", "p": "Kit tartunk az első nagy magyar nyelvű lírikusnak?", "s": "Régi magyar irodalom", "w": ["Janus Pannoniust", "Zrínyi Miklóst", "Tinódi Lantos Sebestyént"]},
  {"a": "Háromból", "p": "Hány sorból áll egy Balassi-strófa?", "s": "Régi magyar irodalom", "w": ["Kettőből", "Négyből", "Tizennégyből"]},
  {"a": "Esztergomnál", "p": "Melyik vár ostrománál esett el Balassi Bálint?", "s": "Régi magyar irodalom", "w": ["Egernél", "Szigetvárnál", "Székesfehérvárnál"]},
  {"a": "Históriás énekben", "p": "Milyen műfajban énekelte meg Tinódi Eger ostromát?", "s": "Régi magyar irodalom", "w": ["Balladában", "Eposzban", "Elbeszélő költeményben"]},
  {"a": "Zrínyi Miklós", "p": "Ki írta a Szigeti veszedelem című eposzt?", "s": "Régi magyar irodalom", "w": ["Balassi Bálint", "Gyöngyösi István", "Tinódi Lantos Sebestyén"]},
  {"a": "A költő dédapjáról", "p": "Kiről szól a Szigeti veszedelem?", "s": "Régi magyar irodalom", "w": ["A költő apjáról", "A költő bátyjáról", "A költő nagybátyjáról"]},
  {"a": "Az török áfium", "p": "Melyik Zrínyi-röpirat jelszava: Ne bántsd a magyart?", "s": "Régi magyar irodalom", "w": ["A Szigeti veszedelem", "A Vitéz hadnagy", "A Mátyás király életéről"]},
  {"a": "Rodostóban", "p": "Hol írta Mikes Kelemen a Törökországi leveleket?", "s": "Régi magyar irodalom", "w": ["Bécsben", "Párizsban", "Konstantinápolyban"]},
  {"a": "Az édes nénjéhez", "p": "Kihez címezte Mikes a törökországi leveleit?", "s": "Régi magyar irodalom", "w": ["Az édesanyjához", "A fejedelemhez", "A bujdosó társaihoz"]},
  {"a": "Rákóczi Ferenc", "p": "Melyik fejedelem kíséretében élt Mikes Rodostóban?", "s": "Régi magyar irodalom", "w": ["Bethlen Gábor", "Bocskai István", "Thököly Imre"]},
  {"a": "Kazinczy Ferenc", "p": "Ki volt a nyelvújítás vezéralakja?", "s": "Régi magyar irodalom", "w": ["Bessenyei György", "Berzsenyi Dániel", "Csokonai Vitéz Mihály"]},
  {"a": "Széphalmon", "p": "Melyik faluban élt Kazinczy Ferenc?", "s": "Régi magyar irodalom", "w": ["Niklán", "Szatmárcsekén", "Alsósztregován"]},
  {"a": "Fogságom naplója", "p": "Melyik Kazinczy-mű szól a fogság éveiről?", "s": "Régi magyar irodalom", "w": ["Tövisek és virágok", "Pályám emlékezete", "Ortológus és neológus"]},
  {"a": "Debrecenhez", "p": "Melyik városhoz kötődik Csokonai Vitéz Mihály?", "s": "Régi magyar irodalom", "w": ["Szegedhez", "Pécshez", "Székesfehérvárhoz"]},
  {"a": "Vajda Juliannát", "p": "Kit nevezett Lillának Csokonai a verseiben?", "s": "Régi magyar irodalom", "w": ["Szendrey Júliát", "Laborfalvi Rózát", "Sárvári Annát"]},
  {"a": "A Dorottya", "p": "Melyik Csokonai-mű vígeposz?", "s": "Régi magyar irodalom", "w": ["A Reményhez", "Az estve", "A Magánossághoz"]},
  {"a": "Niklán", "p": "Melyik faluban élt Berzsenyi Dániel?", "s": "Régi magyar irodalom", "w": ["Széphalmon", "Szatmárcsekén", "Alsósztregován"]},
  {"a": "A közelítő tél", "p": "Melyik Berzsenyi-vers szól az ősz elmúlásáról?", "s": "Régi magyar irodalom", "w": ["A magyarokhoz", "Osztályrészem", "Levéltöredék barátnémhoz"]},
  {"a": "Fazekas Mihály", "p": "Ki írta a Lúdas Matyi című művet?", "s": "Régi magyar irodalom", "w": ["Csokonai Vitéz Mihály", "Berzsenyi Dániel", "Kisfaludy Károly"]},
  {"a": "Döbrögi úron", "p": "Kin áll bosszút Lúdas Matyi?", "s": "Régi magyar irodalom", "w": ["Pató Pál úron", "Toldi Györgyön", "Brazovics uramon"]},
  {"a": "Háromszor", "p": "Hányszor veri vissza Matyi a sérelmét?", "s": "Régi magyar irodalom", "w": ["Kétszer", "Négyszer", "Ötvenszer"]},
  {"a": "Libákat", "p": "Mit vitt eladni Matyi a döbrögi vásárra?", "s": "Régi magyar irodalom", "w": ["Kacsákat", "Malacokat", "Tyúkokat"]},
  {"a": "Apáczai Csere János", "p": "Ki írta a Magyar Encyclopaediát?", "s": "Régi magyar irodalom", "w": ["Károli Gáspár", "Pázmány Péter", "Szenczi Molnár Albert"]},
  {"a": "A franciaországi változásokra", "p": "Melyik Batsányi-vers figyelmeztet a párizsi eseményekre?", "s": "Régi magyar irodalom", "w": ["A látó", "Tűnődés", "Levél Szentjóbi Szabó Lászlóhoz"]},
  {"a": "A balladát", "p": "Melyik műfajt hívják tragédiának dalban elbeszélve?", "s": "Irodalmi fogalmak", "w": ["Az eposzt", "Az elégiát", "Az epigrammát"]},
  {"a": "Tizennégyből", "p": "Hány sorból áll a szonett?", "s": "Irodalmi fogalmak", "w": ["Nyolcból", "Tizenhatból", "Tizenkettőből"]},
  {"a": "A Toldi", "p": "Melyik mű elbeszélő költemény?", "s": "Irodalmi fogalmak", "w": ["A Bánk bán", "Az ember tragédiája", "A Szigeti veszedelem"]},
  {"a": "Drámai költemény", "p": "Milyen műfajú Az ember tragédiája?", "s": "Irodalmi fogalmak", "w": ["Ballada", "Verses regény", "Elbeszélő költemény"]},
  {"a": "Eposz", "p": "Milyen műfajú a Szigeti veszedelem?", "s": "Irodalmi fogalmak", "w": ["Ballada", "Verses regény", "Elbeszélő költemény"]},
  {"a": "Tragédia", "p": "Milyen műfajú a Bánk bán?", "s": "Irodalmi fogalmak", "w": ["Vígjáték", "Verses regény", "Elbeszélő költemény"]},
  {"a": "Líra, epika, dráma", "p": "Mi a három irodalmi műnem?", "s": "Irodalmi fogalmak", "w": ["Vers, próza, mese", "Dal, ballada, eposz", "Regény, novella, dráma"]},
  {"a": "Az epikába", "p": "Melyik műnembe tartozik a regény?", "s": "Irodalmi fogalmak", "w": ["A lírába", "A drámába", "A színjátékba"]},
  {"a": "Epigramma", "p": "Melyik műfaj rövid, csattanós vers?", "s": "Irodalmi fogalmak", "w": ["Elégia", "Ballada", "Elbeszélő költemény"]},
  {"a": "Az óda", "p": "Melyik műfaj emelkedett hangú, magasztaló költemény?", "s": "Irodalmi fogalmak", "w": ["A ballada", "Az epigramma", "A verses regény"]},
  {"a": "Az elégia", "p": "Melyik műfaj bánatos, elmélkedő hangú vers?", "s": "Irodalmi fogalmak", "w": ["Az óda", "A ballada", "Az epigramma"]},
  {"a": "Hasonlat", "p": "Hogy hívjuk a mint szóval alkotott költői képet?", "s": "Irodalmi fogalmak", "w": ["Metafora", "Alliteráció", "Megszemélyesítés"]},
  {"a": "Azonosítást", "p": "Mit nevezünk metaforának?", "s": "Irodalmi fogalmak", "w": ["Rímelést", "Betűismétlést", "Összehasonlítást"]},
  {"a": "Alliteráció", "p": "Mi a betűrím másik neve?", "s": "Irodalmi fogalmak", "w": ["Keresztrím", "Metafora", "Megszemélyesítés"]},
  {"a": "Refrén", "p": "Hogy hívjuk a versszakok végén visszatérő sort?", "s": "Irodalmi fogalmak", "w": ["Rím", "Ütem", "Verslábak"]},
  {"a": "Páros rím", "p": "Melyik rímképlet az aabb?", "s": "Irodalmi fogalmak", "w": ["Keresztrím", "Ölelkező rím", "Félrím"]},
  {"a": "Keresztrím", "p": "Melyik rímképlet az abab?", "s": "Irodalmi fogalmak", "w": ["Páros rím", "Ölelkező rím", "Bokorrím"]},
  {"a": "Ölelkező rím", "p": "Melyik rímképlet az abba?", "s": "Irodalmi fogalmak", "w": ["Páros rím", "Keresztrím", "Belső rímelés"]},
  {"a": "Hatból", "p": "Hány verslábból áll a hexameter?", "s": "Irodalmi fogalmak", "w": ["Négyből", "Ötből", "Tizennégyből"]},
  {"a": "Hexameter és pentameter", "p": "Milyen sorpárból áll a disztichon?", "s": "Irodalmi fogalmak", "w": ["Két hexameter", "Két pentameter", "Hexameter és Balassi-sor"]},
  {"a": "A szótagok hosszúságára", "p": "Mire épül az időmértékes verselés?", "s": "Irodalmi fogalmak", "w": ["A sorok számára", "A rímek rendjére", "A hangsúlyos ütemek rendjére"]},
  {"a": "Ütemhangsúlyos", "p": "Mi a magyaros verselés másik neve?", "s": "Irodalmi fogalmak", "w": ["Időmértékes", "Szabad vers", "Rímtelen verselés"]},
  {"a": "Monológ", "p": "Hogy hívjuk a színpadi magánbeszédet?", "s": "Irodalmi fogalmak", "w": ["Párbeszéd", "Prológus", "Jelenet"]},
  {"a": "Felvonásokra", "p": "Milyen nagyobb egységekre osztják a színdarabot?", "s": "Irodalmi fogalmak", "w": ["Fejezetekre", "Versszakokra", "Szakaszokra"]},
  {"a": "Invokáció", "p": "Hogy hívják az eposz elején a múzsához szóló kérést?", "s": "Irodalmi fogalmak", "w": ["Propozíció", "Enumeráció", "In medias res"]},
  {"a": "A dolgok közepébe vágást", "p": "Mit jelent az in medias res kifejezés?", "s": "Irodalmi fogalmak", "w": ["A hősök felsorolását", "A múzsa megszólítását", "A történet végének elmesélését"]},
  {"a": "A novella", "p": "Melyik műfaj rövid, egy eseményre épülő próza?", "s": "Irodalmi fogalmak", "w": ["A regény", "Az eposz", "Az elbeszélő költemény"]},
  {"a": "Az anekdota", "p": "Melyik műfaj rövid, tréfás, valós történet?", "s": "Irodalmi fogalmak", "w": ["A ballada", "Az elégia", "A verses regény"]},
  {"a": "Énekeknek", "p": "Minek nevezzük a Toldi nagyobb egységeit?", "s": "Irodalmi fogalmak", "w": ["Felvonásoknak", "Fejezeteknek", "Versszakoknak"]},
  {"a": "Veronában", "p": "Melyik városban játszódik a Rómeó és Júlia?", "s": "Világirodalom magyarul", "w": ["Velencében", "Firenzében", "Koppenhágában"]},
  {"a": "Shakespeare", "p": "Ki írta a Hamlet című tragédiát?", "s": "Világirodalom magyarul", "w": ["Molière", "Szophoklész", "Dosztojevszkij"]},
  {"a": "Dánia", "p": "Melyik ország királyfia Hamlet?", "s": "Világirodalom magyarul", "w": ["Norvégia", "Skócia", "Anglia"]},
  {"a": "Arany János", "p": "Ki fordította magyarra a Hamletet?", "s": "Világirodalom magyarul", "w": ["Petőfi Sándor", "Babits Mihály", "Vörösmarty Mihály"]},
  {"a": "Szentivánéji álom", "p": "Melyik Shakespeare-vígjáték szereplője Puck?", "s": "Világirodalom magyarul", "w": ["Macbeth", "A velencei kalmár", "Vízkereszt, vagy amit akartok"]},
  {"a": "Othello", "p": "Melyik Shakespeare-dráma hőse Jago és Desdemona?", "s": "Világirodalom magyarul", "w": ["Macbeth", "Lear király", "Rómeó és Júlia"]},
  {"a": "Három", "p": "Hány lánya van Lear királynak?", "s": "Világirodalom magyarul", "w": ["Kettő", "Négy", "Hét"]},
  {"a": "Vörösmarty Mihály", "p": "Melyik magyar költő fordította le a Lear királyt?", "s": "Világirodalom magyarul", "w": ["Arany János", "Petőfi Sándor", "Csokonai Vitéz Mihály"]},
  {"a": "Phileas Fogg", "p": "Melyik Verne-hős kerüli meg a Földet nyolcvan nap alatt?", "s": "Világirodalom magyarul", "w": ["Nemo kapitány", "Sándor Mátyás", "Grant kapitány"]},
  {"a": "Passepartout", "p": "Hogy hívják Phileas Fogg inasát?", "s": "Világirodalom magyarul", "w": ["Ayrton", "Nemo", "Sándor Mátyás"]},
  {"a": "Nemo", "p": "Melyik Verne-hős a Nautilus kapitánya?", "s": "Világirodalom magyarul", "w": ["Grant", "Fogg", "Ayrton"]},
  {"a": "Sándor Mátyás", "p": "Melyik Verne-regény hőse magyar főúr?", "s": "Világirodalom magyarul", "w": ["Kétévi vakáció", "A rejtelmes sziget", "Utazás a Holdba"]},
  {"a": "Defoe", "p": "Ki írta a Robinson Crusoe című regényt?", "s": "Világirodalom magyarul", "w": ["Swift", "Verne", "Dickens"]},
  {"a": "Pénteknek", "p": "Hogy hívja Robinson a megmentett bennszülöttet?", "s": "Világirodalom magyarul", "w": ["Szombatnak", "Vasárnapnak", "Hétfőnek"]},
  {"a": "Gulliver utazásai", "p": "Melyik regényben él a törpék országa, Lilliput?", "s": "Világirodalom magyarul", "w": ["Robinson Crusoe", "Kétévi vakáció", "A rejtelmes sziget"]},
  {"a": "Cervantes", "p": "Ki írta a Don Quijote című regényt?", "s": "Világirodalom magyarul", "w": ["Molière", "Dickens", "Shakespeare"]},
  {"a": "Sancho Panza", "p": "Hogy hívják Don Quijote fegyverhordozóját?", "s": "Világirodalom magyarul", "w": ["Rosinante", "Dulcinea", "Robinson Crusoe"]},
  {"a": "Szélmalmokkal", "p": "Mivel harcol Don Quijote a híres jelenetben?", "s": "Világirodalom magyarul", "w": ["Oroszlánokkal", "Kalózokkal", "Óriáskígyókkal"]},
  {"a": "Az Iliász", "p": "Melyik eposz hőse Akhilleusz?", "s": "Világirodalom magyarul", "w": ["Az Odüsszeia", "Az Aeneis", "Az Isteni színjáték"]},
  {"a": "Ithakába", "p": "Melyik szigetre igyekszik haza Odüsszeusz?", "s": "Világirodalom magyarul", "w": ["Krétára", "Trójába", "Szicíliába"]},
  {"a": "Egy küklopszot", "p": "Milyen szörnyet vakít meg Odüsszeusz a barlangban?", "s": "Világirodalom magyarul", "w": ["Egy szirént", "Egy kentaurt", "Egy óriáskígyót"]},
  {"a": "Vergilius", "p": "Ki vezeti Dantét a Pokolban?", "s": "Világirodalom magyarul", "w": ["Beatrice", "Homérosz", "Odüsszeusz"]},
  {"a": "Goethe", "p": "Ki írta a Faust című drámai költeményt?", "s": "Világirodalom magyarul", "w": ["Schiller", "Molière", "Shakespeare"]},
  {"a": "A nyomorultak", "p": "Melyik regény hőse Jean Valjean?", "s": "Világirodalom magyarul", "w": ["Twist Olivér", "Goriot apó", "A párizsi Notre-Dame"]},
  {"a": "A párizsi Notre-Dame", "p": "Melyik regény hőse a púpos Quasimodo?", "s": "Világirodalom magyarul", "w": ["A nyomorultak", "Monte Cristo grófja", "Az öreg halász és a tenger"]},
  {"a": "Dickens", "p": "Ki írta a Twist Olivér című regényt?", "s": "Világirodalom magyarul", "w": ["Defoe", "Hugo", "Stendhal"]},
  {"a": "Tolsztoj", "p": "Ki írta a Háború és béke című regényt?", "s": "Világirodalom magyarul", "w": ["Csehov", "Gogol", "Dosztojevszkij"]},
  {"a": "Bűn és bűnhődés", "p": "Melyik regény hőse Raszkolnyikov?", "s": "Világirodalom magyarul", "w": ["Holt lelkek", "Háború és béke", "A Karamazov testvérek"]},
  {"a": "Puskin", "p": "Ki írta az Anyegin című verses regényt?", "s": "Világirodalom magyarul", "w": ["Gogol", "Csehov", "Tolsztoj"]},
  {"a": "Sirály", "p": "Melyik Csehov-dráma címe egy madarat említ?", "s": "Világirodalom magyarul", "w": ["Három nővér", "Ványa bácsi", "Cseresznyéskert"]},
  {"a": "Mark Twain", "p": "Melyik amerikai író írta Tom Sawyer történetét?", "s": "Világirodalom magyarul", "w": ["Hemingway", "Jack London", "Saint-Exupéry"]},
  {"a": "Jack London", "p": "Ki írta A vadon szava című regényt?", "s": "Világirodalom magyarul", "w": ["Mark Twain", "Hemingway", "Saint-Exupéry"]},
  {"a": "Hemingway", "p": "Ki írta Az öreg halász és a tenger című kisregényt?", "s": "Világirodalom magyarul", "w": ["Mark Twain", "Jack London", "Saint-Exupéry"]},
  {"a": "Saint-Exupéry", "p": "Ki írta A kis herceg című mesét?", "s": "Világirodalom magyarul", "w": ["Kästner", "Andersen", "Selma Lagerlöf"]},
  {"a": "A rókát", "p": "Melyik állatot szelídíti meg a kis herceg?", "s": "Világirodalom magyarul", "w": ["A bárányt", "A kígyót", "Az elefántot"]},
  {"a": "Harisnyás Pippi", "p": "Melyik regény hősnője a világ legerősebb kislánya?", "s": "Világirodalom magyarul", "w": ["A két Lotti", "A kis herceg", "Emil és a detektívek"]},
  {"a": "Janikovszky Éva", "p": "Ki írta a Ha én felnőtt volnék című könyvet?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Szabó Magda", "Lázár Ervin", "Nemes Nagy Ágnes"]},
  {"a": "Réber László", "p": "Melyik rajzoló illusztrálta Janikovszky Éva könyveit?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Kass János", "Würtz Ádám", "Reich Károly"]},
  {"a": "Bálint Ágnes", "p": "Ki írta a Frakk, a macskák réme című mesét?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Marék Veronika", "Csukás István", "Janikovszky Éva"]},
  {"a": "Bálint Ágnes", "p": "Ki írta a Mazsola című meséskönyvet?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Marék Veronika", "Lázár Ervin", "Nemes Nagy Ágnes"]},
  {"a": "Marék Veronika", "p": "Ki írta a Kippkopp-meséket?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Bálint Ágnes", "Csukás István", "Janikovszky Éva"]},
  {"a": "Egy kandúr", "p": "Melyik állat Csukás István Mirr-Murr nevű hőse?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Egy kutya", "Egy sárkány", "Egy kismalac"]},
  {"a": "Csukás István", "p": "Ki írta a Keménykalap és krumpliorr című regényt?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Lázár Ervin", "Bálint Ágnes", "Janikovszky Éva"]},
  {"a": "Lázár Ervin", "p": "Ki írta A Hétfejű Tündér című mesekönyvet?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Csukás István", "Bálint Ágnes", "Janikovszky Éva"]},
  {"a": "Egy oroszlán", "p": "Melyik állat Lázár Ervin Bruckner Szigfrid nevű hőse?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Egy medve", "Egy szamár", "Egy vaddisznó"]},
  {"a": "Szabó Magda", "p": "Ki írta a Sziget-kék című meseregényt?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Lázár Ervin", "Bálint Ágnes", "Janikovszky Éva"]},
  {"a": "Szabó Magda", "p": "Ki írta a Bárány Boldizsár című verses mesét?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Weöres Sándor", "Zelk Zoltán", "Nemes Nagy Ágnes"]},
  {"a": "Zelk Zoltán", "p": "Ki írta A három nyúl című verses mesét?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Weöres Sándor", "Kormos István", "Nemes Nagy Ágnes"]},
  {"a": "Egy medvebocs", "p": "Melyik állat Kormos István Vackor nevű hőse?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Egy nyúl", "Egy kiskutya", "Egy erdei manó"]},
  {"a": "Nemes Nagy Ágnes", "p": "Ki írta a Bors néni könyve című verseskötetet?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Weöres Sándor", "Zelk Zoltán", "Tamkó Sirató Károly"]},
  {"a": "Arany Lacinak", "p": "Melyik Petőfi-verset írta a költő egy kisfiúnak?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Anyám tyúkja", "István öcsémhez", "A jó öreg kocsmáros"]},
  {"a": "Móra Ferenc", "p": "Ki írta a Zengő ABC című gyermekverset?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Weöres Sándor", "Zelk Zoltán", "Janikovszky Éva"]},
  {"a": "A cinege cipője", "p": "Melyik Móra-vers szól egy fázós kis madárról?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Zengő ABC", "Dióbél királyfi", "A didergő király"]},
  {"a": "Bóbita", "p": "Melyik kötetben gyűjtötte össze Weöres a gyerekverseit?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Psyché", "Rongyszőnyeg", "A holdbeli csónakos"]},
  {"a": "1978-ban", "p": "Melyik évben mutatta be a televízió az Abigélt?", "s": "Gyermek- és ifjúsági irodalom", "w": ["1968-ban", "1985-ben", "1990-ben"]},
  {"a": "Téli berek", "p": "Melyik Fekete István-regény a Tüskevár folytatása?", "s": "Gyermek- és ifjúsági irodalom", "w": ["Vuk", "Bogáncs", "Ballagó idő"]},
  {"a": "Jó kedvvel, bőséggel", "p": "Fejezze be: Isten, áldd meg a magyart...", "s": "Híres sorok", "w": ["Békével, jó kedvvel", "Bő kenyérrel, borral", "Sok örömmel, bőséggel"]},
  {"a": "A múltat s jövendőt", "p": "Fejezze be: Megbűnhődte már e nép...", "s": "Híres sorok", "w": ["A múltat és a jövőt", "A bűnt és a jövendőt", "A régmúltat s a jövőt"]},
  {"a": "Kárpát szent bércére", "p": "Fejezze be: Őseinket felhozád...", "s": "Híres sorok", "w": ["Kárpát magas ormára", "Kárpát szent ormaira", "Kárpát sziklás ormára"]},
  {"a": "Bendegúznak vére", "p": "Fejezze be: Általad nyert szép hazát...", "s": "Híres sorok", "w": ["Árpád népe", "Bendegúz népe", "A magyaroknak vére"]},
  {"a": "Most kőhalom", "p": "Fejezze be: Vár állott...", "s": "Híres sorok", "w": ["Most rom", "Ma már kőhalom", "Most puszta kőhalom"]},
  {"a": "Légy híve, oh magyar", "p": "Fejezze be: Hazádnak rendületlenűl...", "s": "Híres sorok", "w": ["Maradj híve, magyar", "Légy hű fia, magyar", "Légy hű szolgája, magyar"]},
  {"a": "Mely ápol s eltakar", "p": "Fejezze be: Bölcsőd az s majdan sírod is...", "s": "Híres sorok", "w": ["Mely ringat s eltakar", "Amely majd eltakar", "Mely ápol és majd eltakar"]},
  {"a": "Nincsen számodra hely", "p": "Fejezze be: A nagy világon e kivűl...", "s": "Híres sorok", "w": ["Nincsen több otthonod", "Nem vár rád más haza", "Nincs másik hazád, magyar"]},
  {"a": "Itt élned, halnod kell", "p": "Fejezze be: Áldjon vagy verjen sors keze...", "s": "Híres sorok", "w": ["Itt van a te helyed", "Itt kell megmaradnod", "Itt élned s meghalnod kell"]},
  {"a": "Hiában onta vért", "p": "Fejezze be: Az nem lehet, hogy annyi szív...", "s": "Híres sorok", "w": ["Hiába dobogott", "Hiába vérezett el", "Hiába onta drága vért"]},
  {"a": "Egy jobb kor, mely után", "p": "Fejezze be: Még jőni kell, még jőni fog...", "s": "Híres sorok", "w": ["Egy szebb kor, mely után", "Egy új idő, amelyre", "Egy boldogabb kor, melyre"]},
  {"a": "Hí a haza", "p": "Fejezze be: Talpra magyar...", "s": "Híres sorok", "w": ["Szól a haza", "Hív a hazád", "Itt hív a haza"]},
  {"a": "Most vagy soha", "p": "Fejezze be: Itt az idő...", "s": "Híres sorok", "w": ["Most vagy sosem", "Itt a nagy idő", "Most vagy sohasem"]},
  {"a": "Ez a kérdés, válasszatok", "p": "Fejezze be: Rabok legyünk vagy szabadok...", "s": "Híres sorok", "w": ["Ez a kérdés, feleljetek", "Itt a kérdés, válasszatok", "Ez a nagy kérdés, döntsetek"]},
  {"a": "Esküszünk", "p": "Fejezze be: A magyarok istenére...", "s": "Híres sorok", "w": ["Fogadjuk", "Így esküszünk", "Esküdjünk mind"]},
  {"a": "Ki most, ha kell, halni nem mer", "p": "Fejezze be: Sehonnai bitang ember...", "s": "Híres sorok", "w": ["Aki most halni nem mer", "Ki most a halált nem meri", "Ki most, ha kell, nem mer meghalni"]},
  {"a": "Jobban ékesíti a kart", "p": "Fejezze be: Fényesebb a láncnál a kard...", "s": "Híres sorok", "w": ["Jobban díszíti a kart", "Szebben ékesíti a kart", "Sokkal szebben áll a karon"]},
  {"a": "Unokáink leborulnak", "p": "Fejezze be: Hol sírjaink domborulnak...", "s": "Híres sorok", "w": ["Unokáink térdepelnek", "Gyermekeink leborulnak", "Az unokák majd ott sírnak"]},
  {"a": "Léptet fakó lován", "p": "Fejezze be: Edward király, angol király...", "s": "Híres sorok", "w": ["Ül a fakó lován", "Üget fakó lován", "Léptet a fakó lovon"]},
  {"a": "A velszi tartomány", "p": "Fejezze be: Hadd látom, úgymond, mennyit ér...", "s": "Híres sorok", "w": ["Az új tartományom", "Ez a hódolt tartomány", "A meghódított tartomány"]},
  {"a": "Hol aznap este szállt", "p": "Fejezze be: Montgomery a vár neve...", "s": "Híres sorok", "w": ["Ahol az este szállt", "Hol aznap éjjel szállt", "Hol az nap estve megszállt"]},
  {"a": "Lángsírba velszi bárd", "p": "Fejezze be: Ötszáz, bizony, dalolva ment...", "s": "Híres sorok", "w": ["A máglyára velszi bárd", "Tűzhalálba velszi bárd", "Lángsírba mind a velszi bárd"]},
  {"a": "Melyet zeng velszi bárd", "p": "Fejezze be: Átok fejedre minden dal...", "s": "Híres sorok", "w": ["Amelyet zeng a bárd", "Mit énekel velszi bárd", "Melyet dalol a velszi bárd"]},
  {"a": "London utcáin ez", "p": "Fejezze be: Ha, ha! mi zúg? Mi éji dal...", "s": "Híres sorok", "w": ["A város utcáin ez", "London falai közt", "London minden utcáján"]},
  {"a": "Tikkadt szöcskenyájak legelésznek rajta", "p": "Fejezze be: Ég a napmelegtől a kopár szík sarja...", "s": "Híres sorok", "w": ["Fáradt szöcskenyájak legelésznek rajta", "Tikkadt szöcskeseregek legelnek rajta", "Tikkadt szöcskenyájak legelésznek alatta"]},
  {"a": "Messziről lobogva tenger pusztaságon", "p": "Fejezze be: Mint ha pásztortűz ég őszi éjszakákon...", "s": "Híres sorok", "w": ["Messziről lobogva néma pusztaságon", "Távolról lobogva tenger pusztaságon", "Messziről világít a tenger pusztaságon"]},
  {"a": "Szép magyar vitézek, aranyos leventék", "p": "Fejezze be: Hej, ha én is, én is köztetek mehetnék...", "s": "Híres sorok", "w": ["Szép magyar vitézek, deli hős leventék", "Bátor magyar vitézek, aranyos leventék", "Szép magyar leventék, aranyos vitézek"]},
  {"a": "Feketén bólingat az eperfa lombja", "p": "Fejezze be: Este van, este van: kiki nyugalomba...", "s": "Híres sorok", "w": ["Feketén bólogat az eperfa lombja", "Sötéten bólingat az eperfa lombja", "Feketén bólingat a nagy eperfa lombja"]},
  {"a": "Nagyot koppan akkor, azután elhallgat", "p": "Fejezze be: Zúg az éji bogár, nekimegy a falnak...", "s": "Híres sorok", "w": ["Nagyot koppan akkor, aztán elhallgat", "Nagyot koppan ottan, azután elhallgat", "Nagyot koppan akkor, s azután elhallgat"]},
  {"a": "Levelét megírta", "p": "Fejezze be: Szilágyi Erzsébet...", "s": "Híres sorok", "w": ["A levelét írta", "Levelét megírá", "A levelét megírta"]},
  {"a": "Halva találták Bárczi Benőt", "p": "Fejezze be: A radványi sötét erdőben...", "s": "Híres sorok", "w": ["Holtan találták Bárczi Benőt", "Halva lelték meg Bárczi Benőt", "Halva találták meg Bárczi Benőt"]},
  {"a": "Ne hagyj el", "p": "Fejezze be: Oh! irgalom atyja...", "s": "Híres sorok", "w": ["Ne hagyj magamra", "Ne hagyj el engem", "Ne feledkezz el rólam"]},
  {"a": "Fehér lepedőjét mossa", "p": "Fejezze be: Ágnes asszony a patakban...", "s": "Híres sorok", "w": ["A lepedőjét mossa", "Véres lepedőjét mossa", "Fehér lepedőjét mosogatja"]},
  {"a": "Száll az ének, szájrul szájra", "p": "Fejezze be: Száll a madár, ágrul ágra...", "s": "Híres sorok", "w": ["Megy az ének, szájrul szájra", "Száll az ének szájról szájra", "Száll az ének is, szájrul szájra"]},
  {"a": "Még zöldel a nyárfa az ablak előtt", "p": "Fejezze be: Még nyílnak a völgyben a kerti virágok...", "s": "Híres sorok", "w": ["Még zöld a nyárfa az ablak előtt", "Még zöldel a hársfa az ablak előtt", "Még zöldel a nyárfa a kis ház előtt"]},
  {"a": "Már hó takará el a bérci tetőt", "p": "Fejezze be: De látod amottan a téli világot?...", "s": "Híres sorok", "w": ["Már hó takarja el a bérci tetőt", "Már hó borítja el a bérci tetőt", "Már hó takará el a hegyek tetejét"]},
  {"a": "Ülj, hitvesem, ülj az ölembe ide", "p": "Fejezze be: Elhull a virág, eliramlik az élet...", "s": "Híres sorok", "w": ["Jöjj, hitvesem, ülj az ölembe ide", "Ülj ide, hitvesem, ülj az ölembe", "Ülj, hitvesem, ülj a térdemre ide"]},
  {"a": "Azon gondolkodám", "p": "Fejezze be: Egész úton hazafelé...", "s": "Híres sorok", "w": ["Azt gondolgattam", "Azon tűnődtem én", "Azon gondolkodtam"]},
  {"a": "Mint a gyümölcs a fán", "p": "Fejezze be: S én csüggtem ajkán... szótlanúl...", "s": "Híres sorok", "w": ["Mint a virág a fán", "Mint gyümölcs az ágon", "Mint az érett gyümölcs a fán"]},
  {"a": "A szobában lakik itt bent", "p": "Fejezze be: Ej mi a kő! tyúkanyó, kend...", "s": "Híres sorok", "w": ["A szobában lakik idebent", "A házban lakik már itt bent", "A szobánkban lakik itt bent"]},
  {"a": "Hadd beszélek mostan veled", "p": "Fejezze be: Morzsa kutyánk, hegyezd füled...", "s": "Híres sorok", "w": ["Hadd beszéljek mostan veled", "Most beszélni akarok veled", "Hadd beszélek én is most veled"]},
  {"a": "E kettő kell nekem", "p": "Fejezze be: Szabadság, szerelem...", "s": "Híres sorok", "w": ["Ez kell csak énnekem", "E kettő az, ami kell", "Ez a kettő kell nekem"]},
  {"a": "Ágyban, párnák közt halni meg", "p": "Fejezze be: Egy gondolat bánt engemet...", "s": "Híres sorok", "w": ["Ágyban, dunyhák közt halni meg", "Ágyban, párnák között halni", "Az ágyban, párnák közt halni meg"]},
  {"a": "Megállék a kanyargó Tiszánál", "p": "Fejezze be: Nyári napnak alkonyúlatánál...", "s": "Híres sorok", "w": ["Megállék a csendes Tiszánál", "Megálltam a kanyargó Tiszánál", "Megállék a kanyargós Tiszánál"]},
  {"a": "Fenyvesekkel vadregényes tája", "p": "Fejezze be: Mit nekem te zordon Kárpátoknak...", "s": "Híres sorok", "w": ["Fenyvesekkel vadregényes bérce", "Fenyveseddel vadregényes tája", "Sziklákkal és fenyvesekkel tája"]},
  {"a": "Madárka szállott rá", "p": "Fejezze be: Reszket a bokor, mert...", "s": "Híres sorok", "w": ["Madár szállott reá", "Madárka röppent rá", "Egy kis madár szállt rá"]},
  {"a": "Ne lógasd a lábadat hiába", "p": "Fejezze be: Húzd rá cigány, megittad az árát...", "s": "Híres sorok", "w": ["Ne lógasd a lábad hiába", "Ne lógassad lábad hiába", "Ne lógasd a két lábadat hiába"]},
  {"a": "Tiszta volt az ég", "p": "Fejezze be: Midőn ezt írtam...", "s": "Híres sorok", "w": ["Derült volt az ég", "Tiszta volt a menny", "Még tiszta volt az ég"]},
  {"a": "És hó és halál", "p": "Fejezze be: Most tél van és csend...", "s": "Híres sorok", "w": ["És hó és a halál", "És fagy és halál", "És hó és néma halál"]},
  {"a": "A világ elébb", "p": "Fejezze be: Ment-e a könyvek által...", "s": "Híres sorok", "w": ["Az ember elébb", "A világ előbbre", "A világ valamivel elébb"]},
  {"a": "Férfi munka volt", "p": "Fejezze be: Ez jó mulatság...", "s": "Híres sorok", "w": ["Nemes munka volt", "Ez férfi munka volt", "Nagy férfimunka volt"]},
  {"a": "Ünnep a világon", "p": "Fejezze be: Lesz még egyszer...", "s": "Híres sorok", "w": ["Öröm a világon", "Ünnepnap a világon", "Nagy ünnep a világon"]},
  {"a": "Mik vogymuk", "p": "Fejezze be: Látjátuk feleim szümtükhel...", "s": "Híres sorok", "w": ["Mik valánk", "Mik vagyunk mi", "Mik vogymuk mi"]},
  {"a": "Ez széles föld felett", "p": "Fejezze be: Vitézek, mi lehet...", "s": "Híres sorok", "w": ["E széles föld felett", "Ez a nagy világ felett", "Ez a széles föld felett"]},
  {"a": "Társak, siessünk", "p": "Fejezze be: Hajrá, fogyjon az út...", "s": "Híres sorok", "w": ["Társaim, siessünk", "Barátok, siessünk", "Kedves társak, siessünk"]},
  {"a": "Égi tűnemény", "p": "Fejezze be: Földiekkel játszó...", "s": "Híres sorok", "w": ["Égi jelenés", "Csalfa tűnemény", "Égi tüneménység"]},
  {"a": "Hajdan erős magyar", "p": "Fejezze be: Romlásnak indult...", "s": "Híres sorok", "w": ["Régen erős magyar", "A hajdan erős magyar", "Már a hajdan erős magyar"]},
  {"a": "Lúdas Matyi vissza", "p": "Fejezze be: Háromszor veri ezt kenden...", "s": "Híres sorok", "w": ["Matyi vissza", "Maga Lúdas Matyi", "Lúdas Matyi még vissza"]},
  {"a": "A gép forog, az alkotó pihen", "p": "Fejezze be: Be van fejezve a nagy mű, igen...", "s": "Híres sorok", "w": ["A gép forog, a mester pihen", "A mű elkészült, az alkotó pihen", "A gép forog, és az alkotó pihen"]},
  {"a": "Küzdj és bízva bízzál", "p": "Fejezze be: Mondottam, ember...", "s": "Híres sorok", "w": ["Küzdj és bízzál", "Küzdj, és bízzál mindig", "Harcolj és bízva bízzál"]},
  {"a": "Vesztes, csak én", "p": "Fejezze be: Nincs a teremtésben...", "s": "Híres sorok", "w": ["Vesztes, csupán én", "Más vesztes, csak én", "Nagyobb vesztes, mint én"]},
  {"a": "Cinkos aki néma", "p": "Fejezze be: Mert vétkesek közt...", "s": "Híres sorok", "w": ["Bűnös, aki néma", "Cinkos az, aki néma", "Cinkos mindenki, aki néma"]},
  {"a": "És itt hagyott minket magunkra", "p": "Fejezze be: Látjátok feleim, egyszerre meghalt...", "s": "Híres sorok", "w": ["S itt hagyott minket magunkra", "És itt hagyott minket egyedül", "És itt hagyott bennünket magunkra"]},
  {"a": "Nem tudom már", "p": "Fejezze be: Milyen volt szőkesége...", "s": "Híres sorok", "w": ["Már nem tudom", "Nem emlékszem", "Azt nem tudom már"]},
  {"a": "Hiába döngetek kaput, falat", "p": "Fejezze be: Góg és Magóg fia vagyok én...", "s": "Híres sorok", "w": ["Hiába verem a kaput, falat", "Hiába döngetem a kaput, falat", "Hiába döngetek kaput és falat"]},
  {"a": "Beszökött az Ősz", "p": "Fejezze be: Párisba tegnap...", "s": "Híres sorok", "w": ["Belopózott az Ősz", "Megérkezett az Ősz", "Beköszöntött az Ősz"]},
  {"a": "Fogom meg a kezedet", "p": "Fejezze be: Már vénülő kezemmel...", "s": "Híres sorok", "w": ["Fogom a te kezedet", "Megfogom a kezedet", "Fogom meg most a kezedet"]},
  {"a": "Se istenem, se hazám", "p": "Fejezze be: Nincsen apám, se anyám...", "s": "Híres sorok", "w": ["Se hazám, se istenem", "Sem istenem, se hazám", "Se istenem és se hazám"]},
  {"a": "Gondolok mindig, meg-megállva", "p": "Fejezze be: Már egy hete csak a mamára...", "s": "Híres sorok", "w": ["Gondolok mindig, megállva", "Gondolok én, meg-megállva", "Gondolok folyton, meg-megállva"]},
  {"a": "Néztem, hogy úszik el a dinnyehéj", "p": "Fejezze be: A rakodópart alsó kövén ültem...", "s": "Híres sorok", "w": ["Néztem, hogy úszik a dinnyehéj", "Láttam, hogy úszik el a dinnyehéj", "Néztem, hogyan úszik el a dinnyehéj"]},
  {"a": "Lehunyja sok szemét a ház", "p": "Fejezze be: Lehunyja kék szemét az ég...", "s": "Híres sorok", "w": ["Becsukja sok szemét a ház", "Lehunyja sok szemét a ház is", "Lehunyja minden szemét a ház"]},
  {"a": "Fát nevelek", "p": "Fejezze be: Kertész leszek...", "s": "Híres sorok", "w": ["Fákat ültetek", "Virágot nevelek", "Szép fákat nevelek"]},
  {"a": "Meglepetés e költemény", "p": "Fejezze be: Harminckét éves lettem én...", "s": "Híres sorok", "w": ["Ajándék e kis költemény", "Meglepetés ez a költemény", "Meglepetés e kis költemény"]},
  {"a": "Nekem szülőhazám", "p": "Fejezze be: Nem tudhatom, hogy másnak e tájék mit jelent...", "s": "Híres sorok", "w": ["Nekem ez a hazám", "Nekem az otthonom", "Nekem a szülőföldem"]},
  {"a": "Fölkél és újra lépked", "p": "Fejezze be: Bolond, ki földre rogyván...", "s": "Híres sorok", "w": ["Fölkel és újra indul", "Feláll és újra lépked", "Fölkél és tovább lépked"]},
  {"a": "Hogy a szegény ember is tudjon nevetni", "p": "Fejezze be: Jól rendelte azt az Isten...", "s": "Híres sorok", "w": ["Hogy a szegény ember is tudjon örülni", "Hogy a szegények is tudjanak nevetni", "Hogy a szegény ember is nevetni tudjon"]},
  {"a": "Körben az angyalok ülnek", "p": "Fejezze be: Bóbita, Bóbita táncol...", "s": "Híres sorok", "w": ["Körben az angyalok állnak", "Körülötte angyalok ülnek", "Körben a kis angyalok ülnek"]},
  {"a": "Izzik a galagonya ruhája", "p": "Fejezze be: Őszi éjjel izzik a galagonya...", "s": "Híres sorok", "w": ["Ég a galagonya ruhája", "Izzik a galagonya bogyója", "Izzik a szép galagonya ruhája"]},
  {"a": "A kicsi kocsi", "p": "Fejezze be: Fut, robog...", "s": "Híres sorok", "w": ["A kis kocsi", "A kicsi szekér", "A kicsike kocsi"]},
  {"a": "Útra kelnék", "p": "Fejezze be: Ó ha cinke volnék...", "s": "Híres sorok", "w": ["Elrepülnék", "Messze szállnék", "Most útra kelnék"]},
  {"a": "Zabszalma", "p": "Fejezze be: Csiribiri csiribiri...", "s": "Híres sorok", "w": ["Szalmaszál", "Hetvenhét", "Karikagyűrű"]},
  {"a": "A Himnusz", "p": "Melyik vers első sora: Isten, áldd meg a magyart?", "s": "Híres sorok", "w": ["A Szózat", "A magyarokhoz", "A Nemzeti dal"]},
  {"a": "A Szózat", "p": "Melyik vers első sora: Hazádnak rendületlenűl?", "s": "Híres sorok", "w": ["A Himnusz", "A Nemzeti dal", "Az Élet vagy halál"]},
  {"a": "A Nemzeti dal", "p": "Melyik vers első sora: Talpra magyar, hí a haza?", "s": "Híres sorok", "w": ["A Szózat", "A Himnusz", "A XIX. század költői"]},
  {"a": "A Családi kör", "p": "Melyik vers első sora: Este van, este van?", "s": "Híres sorok", "w": ["A Toldi", "A walesi bárdok", "A Szeptember végén"]},
  {"a": "A Mama", "p": "Melyik vers első sora: Már egy hete csak a mamára?", "s": "Híres sorok", "w": ["Az Altató", "A Tiszta szívvel", "A Kertész leszek"]},
  {"a": "A Füstbe ment terv", "p": "Melyik vers első sora: Egész úton hazafelé?", "s": "Híres sorok", "w": ["Az Anyám tyúkja", "Az Egy estém otthon", "Az István öcsémhez"]},
  {"a": "Az Anyám tyúkja", "p": "Melyik vers első sora: Ej mi a kő! tyúkanyó, kend?", "s": "Híres sorok", "w": ["A Füstbe ment terv", "A Megy a juhász szamáron", "A Falu végén kurta kocsma"]},
  {"a": "A Szeptember végén", "p": "Melyik vers első sora: Még nyílnak a völgyben a kerti virágok?", "s": "Híres sorok", "w": ["A Reszket a bokor, mert", "Az Itt van az ősz, itt van újra", "A Minek nevezzelek?"]},
  {"a": "A walesi bárdok", "p": "Melyik vers első sora: Edward király, angol király?", "s": "Híres sorok", "w": ["Az Ágnes asszony", "A Mátyás anyja", "A Szondi két apródja"]},
  {"a": "Az Altató", "p": "Melyik vers első sora: Lehunyja kék szemét az ég?", "s": "Híres sorok", "w": ["A Mama", "A Ringató", "A Betlehemi királyok"]},
  {"a": "A Száncsengő", "p": "Melyik Weöres-vers kezdődik így: Éj-mélyből fölzengő?", "s": "Híres sorok", "w": ["A Csiribiri", "A Galagonya", "A Buba éneke"]},
  {"a": "Babits Mihály", "p": "Ki írta ezt a sort: Mert vétkesek közt cinkos aki néma?", "s": "Híres sorok", "w": ["József Attila", "Radnóti Miklós", "Kosztolányi Dezső"]},
  {"a": "József Attila", "p": "Ki írta ezt a sort: Nincsen apám, se anyám?", "s": "Híres sorok", "w": ["Ady Endre", "Radnóti Miklós", "Kosztolányi Dezső"]},
  {"a": "Vörösmarty Mihály", "p": "Ki írta ezt a sort: Lesz még egyszer ünnep a világon?", "s": "Híres sorok", "w": ["Arany János", "Petőfi Sándor", "Csokonai Vitéz Mihály"]},
  {"a": "Madách Imre", "p": "Ki írta ezt a sort: Mondottam, ember: küzdj és bízva bízzál?", "s": "Híres sorok", "w": ["Katona József", "Vörösmarty Mihály", "Csokonai Vitéz Mihály"]},
  {"a": "Zrínyi Miklós", "p": "Ki írta ezt a sort: Ne bántsd a magyart?", "s": "Híres sorok", "w": ["Balassi Bálint", "Mikes Kelemen", "Tinódi Lantos Sebestyén"]},
  {"a": "Petőfi Sándor", "p": "Ki írta ezt a sort: Szabadság, szerelem! E kettő kell nekem?", "s": "Híres sorok", "w": ["Arany János", "Vajda János", "Vörösmarty Mihály"]},
  {"a": "Kölcsey Ferenc", "p": "Ki írta ezt a sort: Hass, alkoss, gyarapíts?", "s": "Híres sorok", "w": ["Berzsenyi Dániel", "Janus Pannonius", "Vörösmarty Mihály"]},
  {"a": "Radnóti Miklós", "p": "Ki írta ezt a sort: Bolond, ki földre rogyván fölkél?", "s": "Híres sorok", "w": ["József Attila", "Illyés Gyula", "Kosztolányi Dezső"]},
  {"a": "Ady Endre", "p": "Ki írta ezt a sort: Párisba tegnap beszökött az Ősz?", "s": "Híres sorok", "w": ["Tóth Árpád", "Juhász Gyula", "Kosztolányi Dezső"]},
  {"a": "Pilinszky János", "p": "Ki írta ezt a sort: Mert elhagyatnak akkor mindenek?", "s": "Híres sorok", "w": ["Nagy László", "Illyés Gyula", "Nemes Nagy Ágnes"]},
  {"a": "Batsányi János", "p": "Ki írta ezt a sort: Vigyázó szemetek Párizsra vessétek?", "s": "Híres sorok", "w": ["Kazinczy Ferenc", "Bessenyei György", "Csokonai Vitéz Mihály"]},
  {"a": "Balassi Bálint", "p": "Ki írta ezt a sort: Adj már csendességet?", "s": "Híres sorok", "w": ["Zrínyi Miklós", "Janus Pannonius", "Tinódi Lantos Sebestyén"]}
]
$questions$::jsonb)
  with ordinality as question(item, ordinality);

do $validation$
begin
  if (
    select count(*) from public.quiz_questions
    where category_id = 'magyar_irodalom' and is_active
  ) <> 415 then
    raise exception 'Magyar irodalom must contain exactly 415 active questions';
  end if;

  if exists (
    select 1
    from public.quiz_questions as question
    where question.category_id = 'magyar_irodalom'
      and (
        cardinality(question.wrong_answers) <> 3
        or (
          select count(distinct lower(trim(answer)))
          from unnest(question.wrong_answers) as answer
        ) <> 3
        or exists (
          select 1
          from unnest(question.wrong_answers) as answer
          where lower(trim(answer)) = lower(trim(question.correct_answer))
        )
      )
  ) then
    raise exception 'Magyar irodalom: every question needs three distinct wrong answers';
  end if;

  if exists (
    select 1
    from public.quiz_questions as proposed
    join public.quiz_questions as existing
      on lower(trim(existing.prompt)) = lower(trim(proposed.prompt))
     and existing.id <> proposed.id
    where proposed.category_id = 'magyar_irodalom'
  ) then
    raise exception 'Magyar irodalom: a prompt is already used by another question';
  end if;
end;
$validation$;
