-- Földrajz magyarul: 518 questions in Hungarian.
--
-- Written so the correct answer is never the longest option -- the tell that
-- made the Psychology bank guessable without reading the prompt. All four
-- choices share one type and grammatical form.
insert into public.quiz_questions (
  id,
  category_id,
  prompt,
  correct_answer,
  wrong_answers,
  language_code,
  grade_level,
  subject,
  display_order,
  is_active
)
select
  'foldrajz_magyarul_' || lpad(question.ordinality::text, 4, '0'),
  'foldrajz_magyarul',
  question.item ->> 'p',
  question.item ->> 'a',
  array(select jsonb_array_elements_text(question.item -> 'w')),
  'hu',
  null,
  question.item ->> 's',
  question.ordinality::integer,
  true
from jsonb_array_elements($questions$
[
  {"a": "Ausztria", "p": "Melyik ország fővárosa Bécs?", "s": "Európai fővárosok", "w": ["Németország", "Svájc", "Szlovénia"]},
  {"a": "Csehország", "p": "Melyik ország fővárosa Prága?", "s": "Európai fővárosok", "w": ["Lengyelország", "Szlovákia", "Ausztria"]},
  {"a": "Lengyelország", "p": "Melyik ország fővárosa Varsó?", "s": "Európai fővárosok", "w": ["Fehéroroszország", "Csehország", "Litvánia"]},
  {"a": "Szlovákia", "p": "Melyik ország fővárosa Pozsony?", "s": "Európai fővárosok", "w": ["Horvátország", "Szlovénia", "Csehország"]},
  {"a": "Szlovénia", "p": "Melyik ország fővárosa Ljubljana?", "s": "Európai fővárosok", "w": ["Horvátország", "Szlovákia", "Ausztria"]},
  {"a": "Horvátország", "p": "Melyik ország fővárosa Zágráb?", "s": "Európai fővárosok", "w": ["Bosznia-Hercegovina", "Szerbia", "Szlovénia"]},
  {"a": "Szerbia", "p": "Melyik ország fővárosa Belgrád?", "s": "Európai fővárosok", "w": ["Horvátország", "Románia", "Bulgária"]},
  {"a": "Románia", "p": "Melyik ország fővárosa Bukarest?", "s": "Európai fővárosok", "w": ["Észak-Macedónia", "Bulgária", "Moldova"]},
  {"a": "Bulgária", "p": "Melyik ország fővárosa Szófia?", "s": "Európai fővárosok", "w": ["Görögország", "Románia", "Szerbia"]},
  {"a": "Görögország", "p": "Melyik ország fővárosa Athén?", "s": "Európai fővárosok", "w": ["Észak-Macedónia", "Olaszország", "Törökország"]},
  {"a": "Portugália", "p": "Melyik ország fővárosa Lisszabon?", "s": "Európai fővárosok", "w": ["Spanyolország", "Olaszország", "Marokkó"]},
  {"a": "Spanyolország", "p": "Melyik ország fővárosa Madrid?", "s": "Európai fővárosok", "w": ["Nagy-Britannia", "Franciaország", "Portugália"]},
  {"a": "Svájc", "p": "Melyik ország fővárosa Bern?", "s": "Európai fővárosok", "w": ["Ausztria", "Hollandia", "Belgium"]},
  {"a": "Norvégia", "p": "Melyik ország fővárosa Oslo?", "s": "Európai fővárosok", "w": ["Svédország", "Finnország", "Dánia"]},
  {"a": "Svédország", "p": "Melyik ország fővárosa Stockholm?", "s": "Európai fővárosok", "w": ["Németország", "Norvégia", "Dánia"]},
  {"a": "Finnország", "p": "Melyik ország fővárosa Helsinki?", "s": "Európai fővárosok", "w": ["Oroszország", "Észtország", "Norvégia"]},
  {"a": "Dánia", "p": "Melyik ország fővárosa Koppenhága?", "s": "Európai fővárosok", "w": ["Németország", "Hollandia", "Norvégia"]},
  {"a": "Izland", "p": "Melyik ország fővárosa Reykjavík?", "s": "Európai fővárosok", "w": ["Finnország", "Írország", "Norvégia"]},
  {"a": "Írország", "p": "Melyik ország fővárosa Dublin?", "s": "Európai fővárosok", "w": ["Nagy-Britannia", "Norvégia", "Izland"]},
  {"a": "Hollandia", "p": "Melyik ország fővárosa Amszterdam?", "s": "Európai fővárosok", "w": ["Németország", "Belgium", "Dánia"]},
  {"a": "Belgium", "p": "Melyik ország fővárosa Brüsszel?", "s": "Európai fővárosok", "w": ["Franciaország", "Luxemburg", "Hollandia"]},
  {"a": "Litvánia", "p": "Melyik ország fővárosa Vilnius?", "s": "Európai fővárosok", "w": ["Lengyelország", "Lettország", "Észtország"]},
  {"a": "Lettország", "p": "Melyik ország fővárosa Riga?", "s": "Európai fővárosok", "w": ["Fehéroroszország", "Észtország", "Litvánia"]},
  {"a": "Észtország", "p": "Melyik ország fővárosa Tallinn?", "s": "Európai fővárosok", "w": ["Oroszország", "Finnország", "Litvánia"]},
  {"a": "Ukrajna", "p": "Melyik ország fővárosa Kijev?", "s": "Európai fővárosok", "w": ["Fehéroroszország", "Oroszország", "Moldova"]},
  {"a": "Minszk", "p": "Melyik város Fehéroroszország fővárosa?", "s": "Európai fővárosok", "w": ["Szmolenszk", "Vilnius", "Kijev"]},
  {"a": "Moldova", "p": "Melyik ország fővárosa Kisinyov?", "s": "Európai fővárosok", "w": ["Bulgária", "Ukrajna", "Románia"]},
  {"a": "Albánia", "p": "Melyik ország fővárosa Tirana?", "s": "Európai fővárosok", "w": ["Görögország", "Montenegró", "Koszovó"]},
  {"a": "Szkopje", "p": "Melyik város Észak-Macedónia fővárosa?", "s": "Európai fővárosok", "w": ["Pristina", "Tirana", "Szófia"]},
  {"a": "Szarajevó", "p": "Melyik város Bosznia-Hercegovina fővárosa?", "s": "Európai fővárosok", "w": ["Banja Luka", "Belgrád", "Zágráb"]},
  {"a": "Montenegró", "p": "Melyik ország fővárosa Podgorica?", "s": "Európai fővárosok", "w": ["Horvátország", "Albánia", "Szerbia"]},
  {"a": "Málta", "p": "Melyik ország fővárosa Valletta?", "s": "Európai fővárosok", "w": ["Görögország", "Ciprus", "Olaszország"]},
  {"a": "Ciprus", "p": "Melyik ország fővárosa Nicosia?", "s": "Európai fővárosok", "w": ["Törökország", "Görögország", "Málta"]},
  {"a": "Párizs", "p": "Melyik város Franciaország fővárosa?", "s": "Európai fővárosok", "w": ["Marseille", "Bordeaux", "Lyon"]},
  {"a": "Róma", "p": "Melyik város Olaszország fővárosa?", "s": "Európai fővárosok", "w": ["Firenze", "Milánó", "Nápoly"]},
  {"a": "Berlin", "p": "Melyik város Németország fővárosa?", "s": "Európai fővárosok", "w": ["Frankfurt", "München", "Hamburg"]},
  {"a": "London", "p": "Melyik város Nagy-Britannia fővárosa?", "s": "Európai fővárosok", "w": ["Manchester", "Edinburgh", "Liverpool"]},
  {"a": "Moszkva", "p": "Melyik város Oroszország fővárosa?", "s": "Európai fővárosok", "w": ["Szentpétervár", "Novoszibirszk", "Kazany"]},
  {"a": "Madrid", "p": "Melyik város Spanyolország fővárosa?", "s": "Európai fővárosok", "w": ["Barcelona", "Valencia", "Sevilla"]},
  {"a": "Ankara", "p": "Melyik város Törökország fővárosa?", "s": "Európai fővárosok", "w": ["Isztambul", "Antalya", "Izmir"]},
  {"a": "Bécs", "p": "Melyik város Ausztria fővárosa?", "s": "Európai fővárosok", "w": ["Innsbruck", "Salzburg", "Graz"]},
  {"a": "Bern", "p": "Melyik város Svájc fővárosa?", "s": "Európai fővárosok", "w": ["Zürich", "Bázel", "Genf"]},
  {"a": "Varsó", "p": "Melyik város Lengyelország fővárosa?", "s": "Európai fővárosok", "w": ["Wrocław", "Krakkó", "Gdańsk"]},
  {"a": "Prága", "p": "Melyik város Csehország fővárosa?", "s": "Európai fővárosok", "w": ["Ostrava", "Brno", "Plzeň"]},
  {"a": "Oslo", "p": "Melyik város Norvégia fővárosa?", "s": "Európai fővárosok", "w": ["Trondheim", "Stavanger", "Bergen"]},
  {"a": "Athén", "p": "Melyik város Görögország fővárosa?", "s": "Európai fővárosok", "w": ["Szaloniki", "Iráklion", "Patra"]},
  {"a": "Bukarest", "p": "Melyik város Románia fővárosa?", "s": "Európai fővárosok", "w": ["Kolozsvár", "Konstanca", "Temesvár"]},
  {"a": "Belgrád", "p": "Melyik város Szerbia fővárosa?", "s": "Európai fővárosok", "w": ["Szabadka", "Újvidék", "Kragujevac"]},
  {"a": "Vaduz", "p": "Melyik város Liechtenstein fővárosa?", "s": "Európai fővárosok", "w": ["San Marino", "Andorra", "Monaco"]},
  {"a": "Dublin", "p": "Melyik város Írország fővárosa?", "s": "Európai fővárosok", "w": ["Limerick", "Belfast", "Cork"]},
  {"a": "Brüsszel", "p": "Melyik város Belgium fővárosa?", "s": "Európai fővárosok", "w": ["Antwerpen", "Charleroi", "Gent"]},
  {"a": "Oroszország", "p": "Melyik Európa legnagyobb területű országa?", "s": "Európa földrajza", "w": ["Franciaország", "Ukrajna", "Svédország"]},
  {"a": "Portugália", "p": "Melyik ország fekszik az Ibériai-félszigeten Spanyolország mellett?", "s": "Európa földrajza", "w": ["Görögország", "Olaszország", "Marokkó"]},
  {"a": "Olaszország", "p": "Melyik ország alakja csizmára hasonlít?", "s": "Európa földrajza", "w": ["Horvátország", "Görögország", "Norvégia"]},
  {"a": "Pireneusok", "p": "Melyik hegység választja el Spanyolországot Franciaországtól?", "s": "Európa földrajza", "w": ["Skandináv-hegység", "Appenninek", "Kárpátok"]},
  {"a": "Alpok", "p": "Melyik hegység húzódik Svájcon és Ausztrián át?", "s": "Európa földrajza", "w": ["Pireneusok", "Appenninek", "Kárpátok"]},
  {"a": "Appenninek", "p": "Melyik hegység húzódik végig Olaszországon?", "s": "Európa földrajza", "w": ["Skandináv-hegység", "Pireneusok", "Kárpátok"]},
  {"a": "Mont Blanc", "p": "Melyik az Alpok legmagasabb hegye?", "s": "Európa földrajza", "w": ["Grossglockner", "Matterhorn", "Jungfrau"]},
  {"a": "Elbrusz", "p": "Melyik hegy a Kaukázus legmagasabb csúcsa?", "s": "Európa földrajza", "w": ["Matterhorn", "Mont Blanc", "Kazbek"]},
  {"a": "Olaszország", "p": "Melyik ország vesz körül teljesen San Marinót?", "s": "Európa földrajza", "w": ["Franciaország", "Spanyolország", "Svájc"]},
  {"a": "Olaszország", "p": "Melyik ország vesz körül teljesen Vatikánvárost?", "s": "Európa földrajza", "w": ["Franciaország", "Görögország", "Svájc"]},
  {"a": "Pireneusok", "p": "Andorra melyik hegységben fekszik?", "s": "Európa földrajza", "w": ["Skandináv-hegység", "Appenninek", "Kárpátok"]},
  {"a": "Norvégia", "p": "Melyik ország fekszik a Skandináv-félsziget nyugati partján?", "s": "Európa földrajza", "w": ["Finnország", "Izland", "Dánia"]},
  {"a": "Balti-tenger", "p": "Melyik tenger választja el Svédországot Finnországtól?", "s": "Európa földrajza", "w": ["Északi-tenger", "Norvég-tenger", "Fehér-tenger"]},
  {"a": "Északi-tenger", "p": "Melyik tenger fekszik Nagy-Britannia és Norvégia között?", "s": "Európa földrajza", "w": ["Földközi-tenger", "Balti-tenger", "Ír-tenger"]},
  {"a": "Adriai-tenger", "p": "Melyik tenger mossa Horvátország partjait?", "s": "Európa földrajza", "w": ["Földközi-tenger", "Égei-tenger", "Jón-tenger"]},
  {"a": "Égei-tenger", "p": "Melyik tenger fekszik Görögország és Törökország között?", "s": "Európa földrajza", "w": ["Fekete-tenger", "Adriai-tenger", "Jón-tenger"]},
  {"a": "Svájc", "p": "Melyik ország ad otthont a Jungfrau hegynek?", "s": "Európa földrajza", "w": ["Franciaország", "Olaszország", "Ausztria"]},
  {"a": "Törökország", "p": "Melyik ország területe Európában és Ázsiában is fekszik?", "s": "Európa földrajza", "w": ["Spanyolország", "Görögország", "Olaszország"]},
  {"a": "Urál", "p": "Melyik hegység választja el Európát Ázsiától?", "s": "Európa földrajza", "w": ["Kaukázus", "Kárpátok", "Balkán"]},
  {"a": "Vatikán", "p": "Melyik a világ legkisebb önálló állama?", "s": "Európa földrajza", "w": ["Liechtenstein", "San Marino", "Monaco"]},
  {"a": "Norvégia", "p": "Melyik ország nem tagja az Európai Uniónak?", "s": "Európa földrajza", "w": ["Horvátország", "Svédország", "Finnország"]},
  {"a": "Brüsszel", "p": "Melyik város ad otthont az Európai Unió fő intézményeinek?", "s": "Európa földrajza", "w": ["Strasbourg", "Amszterdam", "Luxemburg"]},
  {"a": "La Manche", "p": "Melyik tengerszoros választja el Angliát Franciaországtól?", "s": "Európa földrajza", "w": ["Gibraltári-szoros", "Messinai-szoros", "Otrantói-szoros"]},
  {"a": "Edinburgh", "p": "Melyik város Skócia fővárosa?", "s": "Európa földrajza", "w": ["Manchester", "Aberdeen", "Glasgow"]},
  {"a": "Cardiff", "p": "Melyik város Wales fővárosa?", "s": "Európa földrajza", "w": ["Liverpool", "Swansea", "Newport"]},
  {"a": "Belfast", "p": "Melyik város Észak-Írország fővárosa?", "s": "Európa földrajza", "w": ["Londonderry", "Glasgow", "Dublin"]},
  {"a": "Loch Ness", "p": "Melyik skót tóhoz kötődik a híres szörnyről szóló monda?", "s": "Európa földrajza", "w": ["Loch Lomond", "Loch Awe", "Loch Tay"]},
  {"a": "Olaszország", "p": "Melyik országhoz tartozik Szicília szigete?", "s": "Európa földrajza", "w": ["Spanyolország", "Görögország", "Málta"]},
  {"a": "Franciaország", "p": "Melyik országhoz tartozik Korzika szigete?", "s": "Európa földrajza", "w": ["Nagy-Britannia", "Olaszország", "Monaco"]},
  {"a": "Olaszország", "p": "Melyik országhoz tartozik Szardínia szigete?", "s": "Európa földrajza", "w": ["Franciaország", "Görögország", "Spanyolország"]},
  {"a": "Spanyolország", "p": "Melyik országhoz tartozik Mallorca szigete?", "s": "Európa földrajza", "w": ["Nagy-Britannia", "Portugália", "Olaszország"]},
  {"a": "Kréta", "p": "Melyik a legnagyobb görög sziget?", "s": "Európa földrajza", "w": ["Szantorini", "Rodosz", "Korfu"]},
  {"a": "Dánia", "p": "Melyik országhoz tartozik a Feröer szigetcsoport?", "s": "Európa földrajza", "w": ["Norvégia", "Izland", "Skócia"]},
  {"a": "Norvégia", "p": "Melyik ország hosszú partját szabdalják fjordok?", "s": "Európa földrajza", "w": ["Svédország", "Finnország", "Dánia"]},
  {"a": "Hollandia", "p": "Melyik ország hivatalos neve azt jelenti: alacsony földek?", "s": "Európa földrajza", "w": ["Németország", "Belgium", "Dánia"]},
  {"a": "Hollandia", "p": "Melyik ország nagy részét gátak védik a tengertől?", "s": "Európa földrajza", "w": ["Németország", "Belgium", "Dánia"]},
  {"a": "Finnország", "p": "Melyik országot nevezik az ezer tó országának?", "s": "Európa földrajza", "w": ["Oroszország", "Észtország", "Norvégia"]},
  {"a": "Izland", "p": "Melyik ország neve jelenti azt, hogy jég földje?", "s": "Európa földrajza", "w": ["Finnország", "Grönland", "Norvégia"]},
  {"a": "Isztambul", "p": "Melyik város fekszik a Boszporusz két partján?", "s": "Európa földrajza", "w": ["Szentpétervár", "Szaloniki", "Odessza"]},
  {"a": "Norvégia", "p": "Melyik ország legészakibb része nyúlik a sarkkörön túlra?", "s": "Európa földrajza", "w": ["Lettország", "Írország", "Dánia"]},
  {"a": "Luxemburg", "p": "Melyik kis ország határos Németországgal és Franciaországgal is?", "s": "Európa földrajza", "w": ["Liechtenstein", "Szlovénia", "Andorra"]},
  {"a": "Rotterdam", "p": "Melyik város Európa legnagyobb tengeri kikötője?", "s": "Európa földrajza", "w": ["Southampton", "Marseille", "Hamburg"]},
  {"a": "Velence", "p": "Melyik város híres a gondoláiról és a csatornáiról?", "s": "Európa földrajza", "w": ["Szentpétervár", "Amszterdam", "Stockholm"]},
  {"a": "Afrika", "p": "Melyik földrész fekszik a Gibraltári-szorostól délre?", "s": "Európa földrajza", "w": ["Dél-Amerika", "Európa", "Ázsia"]},
  {"a": "Fekete-tenger", "p": "Melyik tenger partján fekszik Odessza?", "s": "Európa földrajza", "w": ["Földközi-tenger", "Azovi-tenger", "Balti-tenger"]},
  {"a": "Fekete-tenger", "p": "A Krím-félsziget melyik tengerbe nyúlik?", "s": "Európa földrajza", "w": ["Földközi-tenger", "Balti-tenger", "Égei-tenger"]},
  {"a": "Oroszország", "p": "Melyik Európa legnépesebb országa?", "s": "Európa földrajza", "w": ["Franciaország", "Németország", "Olaszország"]},
  {"a": "Finnország", "p": "Melyik ország fekszik Svédország és Oroszország között?", "s": "Európa földrajza", "w": ["Lengyelország", "Észtország", "Norvégia"]},
  {"a": "Japán", "p": "Melyik ország fővárosa Tokió?", "s": "Világ fővárosai", "w": ["Dél-Korea", "Vietnam", "Kína"]},
  {"a": "Peking", "p": "Melyik város Kína fővárosa?", "s": "Világ fővárosai", "w": ["Hongkong", "Sanghaj", "Kanton"]},
  {"a": "Dél-Korea", "p": "Melyik ország fővárosa Szöul?", "s": "Világ fővárosai", "w": ["Észak-Korea", "Japán", "Kína"]},
  {"a": "Phenjan", "p": "Melyik város Észak-Korea fővárosa?", "s": "Világ fővárosai", "w": ["Kaeszong", "Puszan", "Szöul"]},
  {"a": "Vietnam", "p": "Melyik ország fővárosa Hanoi?", "s": "Világ fővárosai", "w": ["Kambodzsa", "Thaiföld", "Laosz"]},
  {"a": "Thaiföld", "p": "Melyik ország fővárosa Bangkok?", "s": "Világ fővárosai", "w": ["Kambodzsa", "Mianmar", "Vietnam"]},
  {"a": "Manila", "p": "Melyik város a Fülöp-szigetek fővárosa?", "s": "Világ fővárosai", "w": ["Zamboanga", "Davao", "Cebu"]},
  {"a": "Malajzia", "p": "Melyik ország fővárosa Kuala Lumpur?", "s": "Világ fővárosai", "w": ["Indonézia", "Szingapúr", "Thaiföld"]},
  {"a": "Jakarta", "p": "Melyik város Indonézia legnagyobb városa?", "s": "Világ fővárosai", "w": ["Szurabaja", "Bandung", "Medan"]},
  {"a": "India", "p": "Melyik ország fővárosa Újdelhi?", "s": "Világ fővárosai", "w": ["Pakisztán", "Banglades", "Nepál"]},
  {"a": "Pakisztán", "p": "Melyik ország fővárosa Iszlámábád?", "s": "Világ fővárosai", "w": ["Afganisztán", "Banglades", "India"]},
  {"a": "Banglades", "p": "Melyik ország fővárosa Dakka?", "s": "Világ fővárosai", "w": ["Afganisztán", "Pakisztán", "Mianmar"]},
  {"a": "Nepál", "p": "Melyik ország fővárosa Katmandu?", "s": "Világ fővárosai", "w": ["Banglades", "Mongólia", "Bhután"]},
  {"a": "Afganisztán", "p": "Melyik ország fővárosa Kabul?", "s": "Világ fővárosai", "w": ["Türkmenisztán", "Pakisztán", "Irán"]},
  {"a": "Irán", "p": "Melyik ország fővárosa Teherán?", "s": "Világ fővárosai", "w": ["Afganisztán", "Szíria", "Irak"]},
  {"a": "Irak", "p": "Melyik ország fővárosa Bagdad?", "s": "Világ fővárosai", "w": ["Szaúd-Arábia", "Szíria", "Irán"]},
  {"a": "Szíria", "p": "Melyik ország fővárosa Damaszkusz?", "s": "Világ fővárosai", "w": ["Jordánia", "Libanon", "Irak"]},
  {"a": "Libanon", "p": "Melyik ország fővárosa Bejrút?", "s": "Világ fővárosai", "w": ["Jordánia", "Szíria", "Ciprus"]},
  {"a": "Jordánia", "p": "Melyik ország fővárosa Ammán?", "s": "Világ fővárosai", "w": ["Szaúd-Arábia", "Libanon", "Szíria"]},
  {"a": "Szaúd-Arábia", "p": "Melyik ország fővárosa Rijád?", "s": "Világ fővárosai", "w": ["Egyesült Arab Emírségek", "Katar", "Omán"]},
  {"a": "Mongólia", "p": "Melyik ország fővárosa Ulánbátor?", "s": "Világ fővárosai", "w": ["Kirgizisztán", "Kazahsztán", "Kína"]},
  {"a": "Asztana", "p": "Melyik város Kazahsztán fővárosa?", "s": "Világ fővárosai", "w": ["Karaganda", "Taskent", "Almati"]},
  {"a": "Üzbegisztán", "p": "Melyik ország fővárosa Taskent?", "s": "Világ fővárosai", "w": ["Türkmenisztán", "Kazahsztán", "Mongólia"]},
  {"a": "Azerbajdzsán", "p": "Melyik ország fővárosa Baku?", "s": "Világ fővárosai", "w": ["Türkmenisztán", "Örményország", "Grúzia"]},
  {"a": "Grúzia", "p": "Melyik ország fővárosa Tbiliszi?", "s": "Világ fővárosai", "w": ["Örményország", "Azerbajdzsán", "Törökország"]},
  {"a": "Örményország", "p": "Melyik ország fővárosa Jereván?", "s": "Világ fővárosai", "w": ["Türkmenisztán", "Azerbajdzsán", "Grúzia"]},
  {"a": "Laosz", "p": "Melyik ország fővárosa Vientiane?", "s": "Világ fővárosai", "w": ["Kambodzsa", "Thaiföld", "Vietnam"]},
  {"a": "Kambodzsa", "p": "Melyik ország fővárosa Phnom Penh?", "s": "Világ fővárosai", "w": ["Fülöp-szigetek", "Thaiföld", "Vietnam"]},
  {"a": "Omán", "p": "Melyik ország fővárosa Maszkat?", "s": "Világ fővárosai", "w": ["Bahrein", "Jemen", "Katar"]},
  {"a": "Jemen", "p": "Melyik ország fővárosa Szanaa?", "s": "Világ fővárosai", "w": ["Szaúd-Arábia", "Eritrea", "Omán"]},
  {"a": "Katar", "p": "Melyik ország fővárosa Doha?", "s": "Világ fővárosai", "w": ["Bahrein", "Kuvait", "Omán"]},
  {"a": "Abu-Dzabi", "p": "Melyik város az Egyesült Arab Emírségek fővárosa?", "s": "Világ fővárosai", "w": ["Rász el-Haima", "Sarjah", "Dubaj"]},
  {"a": "Szingapúr", "p": "Melyik ázsiai város egyben önálló ország is?", "s": "Világ fővárosai", "w": ["Kuala Lumpur", "Hongkong", "Bangkok"]},
  {"a": "Colombo", "p": "Melyik város Srí Lanka legnagyobb városa?", "s": "Világ fővárosai", "w": ["Trincomalee", "Kandy", "Galle"]},
  {"a": "Egyiptom", "p": "Melyik ország fővárosa Kairó?", "s": "Világ fővárosai", "w": ["Dél-Szudán", "Szudán", "Líbia"]},
  {"a": "Rabat", "p": "Melyik város Marokkó fővárosa?", "s": "Világ fővárosai", "w": ["Casablanca", "Marrákes", "Fez"]},
  {"a": "Tunézia", "p": "Melyik ország fővárosa Tunisz?", "s": "Világ fővárosai", "w": ["Mauritánia", "Algéria", "Líbia"]},
  {"a": "Algéria", "p": "Melyik ország fővárosa Algír?", "s": "Világ fővárosai", "w": ["Mauritánia", "Tunézia", "Marokkó"]},
  {"a": "Líbia", "p": "Melyik ország fővárosa Tripoli?", "s": "Világ fővárosai", "w": ["Egyiptom", "Tunézia", "Csád"]},
  {"a": "Szudán", "p": "Melyik ország fővárosa Kartúm?", "s": "Világ fővárosai", "w": ["Dél-Szudán", "Egyiptom", "Csád"]},
  {"a": "Kenya", "p": "Melyik ország fővárosa Nairobi?", "s": "Világ fővárosai", "w": ["Tanzánia", "Etiópia", "Uganda"]},
  {"a": "Etiópia", "p": "Melyik ország fővárosa Addisz-Abeba?", "s": "Világ fővárosai", "w": ["Szomália", "Eritrea", "Kenya"]},
  {"a": "Dodoma", "p": "Melyik város Tanzánia hivatalos fővárosa?", "s": "Világ fővárosai", "w": ["Dar es-Salaam", "Zanzibár", "Arusha"]},
  {"a": "Nigéria", "p": "Melyik ország fővárosa Abuja?", "s": "Világ fővárosai", "w": ["Elefántcsontpart", "Kamerun", "Ghána"]},
  {"a": "Lagos", "p": "Melyik város Nigéria legnagyobb városa?", "s": "Világ fővárosai", "w": ["Port Harcourt", "Abuja", "Kano"]},
  {"a": "Ghána", "p": "Melyik ország fővárosa Accra?", "s": "Világ fővárosai", "w": ["Elefántcsontpart", "Nigéria", "Togo"]},
  {"a": "Szenegál", "p": "Melyik ország fővárosa Dakar?", "s": "Világ fővárosai", "w": ["Mauritánia", "Gambia", "Mali"]},
  {"a": "Pretoria", "p": "Melyik város Dél-Afrika közigazgatási fővárosa?", "s": "Világ fővárosai", "w": ["Johannesburg", "Fokváros", "Durban"]},
  {"a": "Kinshasa", "p": "Melyik város a Kongói Demokratikus Köztársaság fővárosa?", "s": "Világ fővárosai", "w": ["Brazzaville", "Lubumbashi", "Luanda"]},
  {"a": "Angola", "p": "Melyik ország fővárosa Luanda?", "s": "Világ fővárosai", "w": ["Mozambik", "Namíbia", "Zambia"]},
  {"a": "Zimbabwe", "p": "Melyik ország fővárosa Harare?", "s": "Világ fővárosai", "w": ["Dél-Afrika", "Botswana", "Zambia"]},
  {"a": "Namíbia", "p": "Melyik ország fővárosa Windhoek?", "s": "Világ fővárosai", "w": ["Botswana", "Angola", "Zambia"]},
  {"a": "Madagaszkár", "p": "Melyik ország fővárosa Antananarivo?", "s": "Világ fővárosai", "w": ["Seychelle-szigetek", "Mauritius", "Mozambik"]},
  {"a": "Washington", "p": "Melyik város az Egyesült Államok fővárosa?", "s": "Világ fővárosai", "w": ["Philadelphia", "New York", "Boston"]},
  {"a": "Ottawa", "p": "Melyik város Kanada fővárosa?", "s": "Világ fővárosai", "w": ["Vancouver", "Montreál", "Toronto"]},
  {"a": "Mexikó", "p": "Melyik ország fővárosa Mexikóváros?", "s": "Világ fővárosai", "w": ["Guatemala", "Honduras", "Kuba"]},
  {"a": "Kuba", "p": "Melyik ország fővárosa Havanna?", "s": "Világ fővárosai", "w": ["Dominikai Köztársaság", "Jamaica", "Haiti"]},
  {"a": "Jamaica", "p": "Melyik ország fővárosa Kingston?", "s": "Világ fővárosai", "w": ["Trinidad és Tobago", "Barbados", "Haiti"]},
  {"a": "Brazíliaváros", "p": "Melyik város Brazília fővárosa?", "s": "Világ fővárosai", "w": ["Rio de Janeiro", "São Paulo", "Salvador"]},
  {"a": "Argentína", "p": "Melyik ország fővárosa Buenos Aires?", "s": "Világ fővárosai", "w": ["Costa Rica", "Uruguay", "Chile"]},
  {"a": "Chile", "p": "Melyik ország fővárosa Santiago?", "s": "Világ fővárosai", "w": ["Argentína", "Bolívia", "Peru"]},
  {"a": "Peru", "p": "Melyik ország fővárosa Lima?", "s": "Világ fővárosai", "w": ["Kolumbia", "Ecuador", "Chile"]},
  {"a": "Kolumbia", "p": "Melyik ország fővárosa Bogotá?", "s": "Világ fővárosai", "w": ["Venezuela", "Ecuador", "Panama"]},
  {"a": "Venezuela", "p": "Melyik ország fővárosa Caracas?", "s": "Világ fővárosai", "w": ["Costa Rica", "Kolumbia", "Guyana"]},
  {"a": "Ecuador", "p": "Melyik ország fővárosa Quito?", "s": "Világ fővárosai", "w": ["Kolumbia", "Bolívia", "Peru"]},
  {"a": "Montevideo", "p": "Melyik város Uruguay fővárosa?", "s": "Világ fővárosai", "w": ["Buenos Aires", "Asunción", "Santiago"]},
  {"a": "Paraguay", "p": "Melyik ország fővárosa Asunción?", "s": "Világ fővárosai", "w": ["Argentína", "Uruguay", "Bolívia"]},
  {"a": "La Paz", "p": "Melyik város Bolívia kormányának székhelye?", "s": "Világ fővárosai", "w": ["Cochabamba", "Santa Cruz", "Sucre"]},
  {"a": "Panama", "p": "Melyik ország fővárosa Panamaváros?", "s": "Világ fővárosai", "w": ["Costa Rica", "Honduras", "Belize"]},
  {"a": "Costa Rica", "p": "Melyik ország fővárosa San José?", "s": "Világ fővárosai", "w": ["El Salvador", "Nicaragua", "Panama"]},
  {"a": "Nicaragua", "p": "Melyik ország fővárosa Managua?", "s": "Világ fővárosai", "w": ["Costa Rica", "Honduras", "Panama"]},
  {"a": "Canberra", "p": "Melyik város Ausztrália fővárosa?", "s": "Világ fővárosai", "w": ["Melbourne", "Brisbane", "Sydney"]},
  {"a": "Wellington", "p": "Melyik város Új-Zéland fővárosa?", "s": "Világ fővárosai", "w": ["Christchurch", "Auckland", "Dunedin"]},
  {"a": "Fidzsi", "p": "Melyik ország fővárosa Suva?", "s": "Világ fővárosai", "w": ["Vanuatu", "Szamoa", "Tonga"]},
  {"a": "Amazonas", "p": "Melyik a világ legbővizűbb folyója?", "s": "Folyók", "w": ["Mississippi", "Nílus", "Kongó"]},
  {"a": "Nílus", "p": "Melyik folyó folyik át Egyiptomon a Földközi-tengerbe?", "s": "Folyók", "w": ["Eufrátesz", "Jordán", "Kongó"]},
  {"a": "Nílus", "p": "Melyik a világ leghosszabb folyója a hagyomány szerint?", "s": "Folyók", "w": ["Mississippi", "Amazonas", "Jangce"]},
  {"a": "Szajna", "p": "Melyik folyó folyik át Párizson?", "s": "Folyók", "w": ["Garonne", "Rhône", "Loire"]},
  {"a": "Temze", "p": "Melyik folyó folyik át Londonon?", "s": "Folyók", "w": ["Severn", "Mersey", "Trent"]},
  {"a": "Tevere", "p": "Melyik folyó folyik át Rómán?", "s": "Folyók", "w": ["Volturno", "Adige", "Arno"]},
  {"a": "Duna", "p": "Melyik folyó folyik át Bécsen és Belgrádon?", "s": "Folyók", "w": ["Visztula", "Rajna", "Elba"]},
  {"a": "Rajna", "p": "Melyik folyó folyik át Kölnön és Rotterdamon?", "s": "Folyók", "w": ["Visztula", "Odera", "Elba"]},
  {"a": "Visztula", "p": "Melyik folyó folyik át Varsón?", "s": "Folyók", "w": ["Dnyeszter", "Odera", "Elba"]},
  {"a": "Elba", "p": "Melyik folyó folyik át Hamburgon?", "s": "Folyók", "w": ["Visztula", "Rajna", "Odera"]},
  {"a": "Moldva", "p": "Melyik folyó folyik át Prágán?", "s": "Folyók", "w": ["Visztula", "Odera", "Elba"]},
  {"a": "Volga", "p": "Melyik Európa leghosszabb folyója?", "s": "Folyók", "w": ["Dnyeper", "Duna", "Urál"]},
  {"a": "Volga", "p": "Melyik folyó torkollik a Kaszpi-tengerbe?", "s": "Folyók", "w": ["Dnyeper", "Don", "Ob"]},
  {"a": "Dnyeper", "p": "Melyik folyó folyik át Kijeven?", "s": "Folyók", "w": ["Dnyeszter", "Volga", "Don"]},
  {"a": "Néva", "p": "Melyik folyó folyik át Szentpéterváron?", "s": "Folyók", "w": ["Volhov", "Onyega", "Dvina"]},
  {"a": "Jangce", "p": "Melyik a leghosszabb folyó Ázsiában?", "s": "Folyók", "w": ["Sárga-folyó", "Gangesz", "Mekong"]},
  {"a": "Sárga-folyó", "p": "Melyik folyó neve Kínában Huanghe?", "s": "Folyók", "w": ["Gyöngy-folyó", "Jangce", "Mekong"]},
  {"a": "Mekong", "p": "Melyik folyó folyik át Vietnamon és Kambodzsán?", "s": "Folyók", "w": ["Brahmaputra", "Gangesz", "Indus"]},
  {"a": "Gangesz", "p": "Melyik folyó szent az indiai hinduk számára?", "s": "Folyók", "w": ["Brahmaputra", "Mekong", "Indus"]},
  {"a": "Indus", "p": "Melyik folyóról kapta India a nevét?", "s": "Folyók", "w": ["Brahmaputra", "Gangesz", "Mekong"]},
  {"a": "Tigris", "p": "Melyik folyó folyik át Bagdadon?", "s": "Folyók", "w": ["Eufrátesz", "Jordán", "Nílus"]},
  {"a": "Amur", "p": "Melyik folyó alkotja Oroszország és Kína határának egy részét?", "s": "Folyók", "w": ["Jenyiszej", "Volga", "Léna"]},
  {"a": "Colorado", "p": "Melyik folyó vájta ki a Grand Canyont?", "s": "Folyók", "w": ["Mississippi", "Rio Grande", "Missouri"]},
  {"a": "Rio Grande", "p": "Melyik folyó alkotja Texas és Mexikó határát?", "s": "Folyók", "w": ["Mississippi", "Colorado", "Missouri"]},
  {"a": "Mackenzie", "p": "Melyik Kanada leghosszabb folyója?", "s": "Folyók", "w": ["Szent Lőrinc", "Fraser", "Yukon"]},
  {"a": "Amazonas", "p": "Melyik folyó folyik át a brazil esőerdőn?", "s": "Folyók", "w": ["Mississippi", "Orinoco", "Paraná"]},
  {"a": "Orinoco", "p": "Melyik folyó folyik át Venezuelán?", "s": "Folyók", "w": ["Magdalena", "Amazonas", "Paraná"]},
  {"a": "Kongó", "p": "Melyik Afrika második leghosszabb folyója?", "s": "Folyók", "w": ["Zambézi", "Limpopo", "Niger"]},
  {"a": "Niger", "p": "Melyik folyóról kapta Nigéria a nevét?", "s": "Folyók", "w": ["Zambézi", "Limpopo", "Kongó"]},
  {"a": "Zambézi", "p": "Melyik folyón található a Viktória-vízesés?", "s": "Folyók", "w": ["Okavango", "Limpopo", "Orange"]},
  {"a": "Murray", "p": "Melyik Ausztrália leghosszabb folyója?", "s": "Folyók", "w": ["Murrumbidgee", "Darling", "Swan"]},
  {"a": "Arno", "p": "Melyik folyó folyik át Firenzén?", "s": "Folyók", "w": ["Tevere", "Adige", "Pó"]},
  {"a": "Pó", "p": "Melyik Olaszország leghosszabb folyója?", "s": "Folyók", "w": ["Tevere", "Adige", "Arno"]},
  {"a": "Tajo", "p": "Melyik folyó torkollik a tengerbe Lisszabonnál?", "s": "Folyók", "w": ["Guadiana", "Douro", "Ebro"]},
  {"a": "Ebro", "p": "Melyik folyó folyik át Zaragozán?", "s": "Folyók", "w": ["Guadalquivir", "Guadiana", "Douro"]},
  {"a": "Rhône", "p": "Melyik folyó folyik Franciaországban délre, a Földközi-tengerbe?", "s": "Folyók", "w": ["Garonne", "Szajna", "Loire"]},
  {"a": "Loire", "p": "Melyik Franciaország leghosszabb folyója?", "s": "Folyók", "w": ["Garonne", "Szajna", "Rhône"]},
  {"a": "Fekete-tenger", "p": "Melyik tengerbe torkollik a Duna?", "s": "Folyók", "w": ["Földközi-tenger", "Adriai-tenger", "Balti-tenger"]},
  {"a": "Északi-tenger", "p": "Melyik tengerbe torkollik a Rajna?", "s": "Folyók", "w": ["Földközi-tenger", "Fekete-tenger", "Balti-tenger"]},
  {"a": "Balti-tenger", "p": "Melyik tengerbe torkollik a Visztula?", "s": "Folyók", "w": ["Földközi-tenger", "Északi-tenger", "Norvég-tenger"]},
  {"a": "Bajkál-tó", "p": "Melyik a világ legmélyebb tava?", "s": "Tavak és tengerek", "w": ["Tanganyika-tó", "Viktória-tó", "Titicaca-tó"]},
  {"a": "Felső-tó", "p": "Melyik a világ legnagyobb édesvízű tava terület szerint?", "s": "Tavak és tengerek", "w": ["Tanganyika-tó", "Viktória-tó", "Bajkál-tó"]},
  {"a": "Viktória-tó", "p": "Melyik Afrika legnagyobb tava?", "s": "Tavak és tengerek", "w": ["Tanganyika-tó", "Malawi-tó", "Csád-tó"]},
  {"a": "Viktória-tó", "p": "Melyik tóból ered a Fehér-Nílus?", "s": "Tavak és tengerek", "w": ["Tanganyika-tó", "Malawi-tó", "Csád-tó"]},
  {"a": "Titicaca-tó", "p": "Melyik a világ legmagasabban fekvő hajózható tava?", "s": "Tavak és tengerek", "w": ["Tanganyika-tó", "Bajkál-tó", "Malawi-tó"]},
  {"a": "Peru és Bolívia", "p": "Melyik két ország osztozik a Titicaca-tavon?", "s": "Tavak és tengerek", "w": ["Ecuador és Kolumbia", "Chile és Argentína", "Brazília és Peru"]},
  {"a": "Holt-tenger", "p": "Melyik a Közel-Kelet rendkívül sós tava?", "s": "Tavak és tengerek", "w": ["Földközi-tenger", "Kaszpi-tenger", "Vörös-tenger"]},
  {"a": "Aral-tó", "p": "Melyik tó zsugorodott össze szinte teljesen Közép-Ázsiában?", "s": "Tavak és tengerek", "w": ["Kaszpi-tenger", "Bajkál-tó", "Balhas-tó"]},
  {"a": "Genfi-tó", "p": "Melyik tavon osztozik Svájc és Franciaország?", "s": "Tavak és tengerek", "w": ["Zürichi-tó", "Bodeni-tó", "Garda-tó"]},
  {"a": "Bodeni-tó", "p": "Melyik tavon osztozik Németország, Ausztria és Svájc?", "s": "Tavak és tengerek", "w": ["Zürichi-tó", "Genfi-tó", "Garda-tó"]},
  {"a": "Garda-tó", "p": "Melyik Olaszország legnagyobb tava?", "s": "Tavak és tengerek", "w": ["Trasimeno-tó", "Maggiore-tó", "Como-tó"]},
  {"a": "Ladoga-tó", "p": "Melyik Európa legnagyobb tava?", "s": "Tavak és tengerek", "w": ["Peipusz-tó", "Onyega-tó", "Genfi-tó"]},
  {"a": "Afrika", "p": "A Tanganyika-tó melyik földrészen fekszik?", "s": "Tavak és tengerek", "w": ["Dél-Amerika", "Európa", "Ázsia"]},
  {"a": "Csád-tó", "p": "Melyik tó zsugorodik a Szahara déli szélén?", "s": "Tavak és tengerek", "w": ["Tanganyika-tó", "Viktória-tó", "Malawi-tó"]},
  {"a": "Ötből", "p": "Hány nagy tóból áll az észak-amerikai Nagy-tavak rendszere?", "s": "Tavak és tengerek", "w": ["Négyből", "Hatból", "Hétből"]},
  {"a": "Kanada és az USA", "p": "A Niagara-vízesés melyik két ország között fekszik?", "s": "Tavak és tengerek", "w": ["Chile és Argentína", "Peru és Bolívia", "Mexikó és Kuba"]},
  {"a": "Angyal-vízesés", "p": "Melyik a világ legmagasabb vízesése?", "s": "Tavak és tengerek", "w": ["Viktória-vízesés", "Niagara-vízesés", "Iguazú-vízesés"]},
  {"a": "Venezuela", "p": "Melyik országban található az Angyal-vízesés?", "s": "Tavak és tengerek", "w": ["Costa Rica", "Kolumbia", "Brazília"]},
  {"a": "Iguazú-vízesés", "p": "Melyik vízesés fekszik Brazília és Argentína határán?", "s": "Tavak és tengerek", "w": ["Viktória-vízesés", "Niagara-vízesés", "Angyal-vízesés"]},
  {"a": "Vörös-tenger", "p": "Melyik tenger fekszik Afrika és az Arab-félsziget között?", "s": "Tavak és tengerek", "w": ["Földközi-tenger", "Fekete-tenger", "Arab-tenger"]},
  {"a": "Tirrén-tenger", "p": "Melyik tenger fekszik Olaszország nyugati partjánál?", "s": "Tavak és tengerek", "w": ["Földközi-tenger", "Adriai-tenger", "Jón-tenger"]},
  {"a": "Sárga-tenger", "p": "Melyik tenger fekszik Kína és Korea között?", "s": "Tavak és tengerek", "w": ["Dél-kínai-tenger", "Japán-tenger", "Jón-tenger"]},
  {"a": "Tasman-tenger", "p": "Melyik tenger fekszik Ausztrália és Új-Zéland között?", "s": "Tavak és tengerek", "w": ["Dél-kínai-tenger", "Arafura-tenger", "Korall-tenger"]},
  {"a": "Korall-tenger", "p": "Melyik tenger fekszik Ausztrália északkeleti partjánál?", "s": "Tavak és tengerek", "w": ["Dél-kínai-tenger", "Arafura-tenger", "Tasman-tenger"]},
  {"a": "Fekete-tenger", "p": "Melyik tenger fekszik Törökország északi partjánál?", "s": "Tavak és tengerek", "w": ["Földközi-tenger", "Márvány-tenger", "Égei-tenger"]},
  {"a": "Márvány-tenger", "p": "Melyik tenger fekszik a Boszporusz és a Dardanellák között?", "s": "Tavak és tengerek", "w": ["Földközi-tenger", "Fekete-tenger", "Égei-tenger"]},
  {"a": "Azovi-tenger", "p": "Melyik tenger fekszik a Fekete-tengertől északkeletre?", "s": "Tavak és tengerek", "w": ["Földközi-tenger", "Márvány-tenger", "Kaszpi-tenger"]},
  {"a": "Barents-tenger", "p": "Melyik tenger mossa Norvégia északi partját?", "s": "Tavak és tengerek", "w": ["Földközi-tenger", "Norvég-tenger", "Fehér-tenger"]},
  {"a": "Karib-tenger", "p": "Melyik tenger fekszik Kuba és Jamaica körül?", "s": "Tavak és tengerek", "w": ["Dél-kínai-tenger", "Földközi-tenger", "Sárga-tenger"]},
  {"a": "Arab-tenger", "p": "Melyik tenger fekszik India nyugati partjánál?", "s": "Tavak és tengerek", "w": ["Dél-kínai-tenger", "Bengáli-öböl", "Vörös-tenger"]},
  {"a": "Perzsa-öböl", "p": "Melyik öböl fekszik Irán és Szaúd-Arábia között?", "s": "Tavak és tengerek", "w": ["Bengáli-öböl", "Mexikói-öböl", "Guineai-öböl"]},
  {"a": "Mexikói-öböl", "p": "Melyik öböl fekszik Texas és Florida partjainál?", "s": "Tavak és tengerek", "w": ["Kaliforniai-öböl", "Bengáli-öböl", "Hudson-öböl"]},
  {"a": "Hudson-öböl", "p": "Melyik nagy öböl nyúlik be Kanada belsejébe?", "s": "Tavak és tengerek", "w": ["Kaliforniai-öböl", "Bengáli-öböl", "Perzsa-öböl"]},
  {"a": "Csendes-óceán", "p": "Melyik a világ legnagyobb óceánja?", "s": "Óceánok és szorosok", "w": ["Északi-Jeges-tenger", "Atlanti-óceán", "Indiai-óceán"]},
  {"a": "Atlanti-óceán", "p": "Melyik a világ második legnagyobb óceánja?", "s": "Óceánok és szorosok", "w": ["Északi-Jeges-tenger", "Csendes-óceán", "Indiai-óceán"]},
  {"a": "Indiai-óceán", "p": "Melyik óceán fekszik Afrika és Ausztrália között?", "s": "Óceánok és szorosok", "w": ["Északi-Jeges-tenger", "Atlanti-óceán", "Csendes-óceán"]},
  {"a": "Jeges-tenger", "p": "Melyik óceán veszi körül az Északi-sarkot?", "s": "Óceánok és szorosok", "w": ["Atlanti-óceán", "Csendes-óceán", "Indiai-óceán"]},
  {"a": "Csendes-óceán", "p": "Melyik óceánban fekszik Hawaii?", "s": "Óceánok és szorosok", "w": ["Északi-Jeges-tenger", "Atlanti-óceán", "Indiai-óceán"]},
  {"a": "Atlanti-óceán", "p": "Melyik óceánban fekszik Izland?", "s": "Óceánok és szorosok", "w": ["Északi-Jeges-tenger", "Csendes-óceán", "Indiai-óceán"]},
  {"a": "Mariana-árok", "p": "Melyik a világ legmélyebb tengeri árka?", "s": "Óceánok és szorosok", "w": ["Puerto Rico-árok", "Tonga-árok", "Jáva-árok"]},
  {"a": "Bering-szoros", "p": "Melyik szoros választja el Ázsiát Észak-Amerikától?", "s": "Óceánok és szorosok", "w": ["Gibraltári-szoros", "Magellán-szoros", "Malaka-szoros"]},
  {"a": "Boszporusz", "p": "Melyik szoros választja el Európát Ázsiától Isztambulnál?", "s": "Óceánok és szorosok", "w": ["Gibraltári-szoros", "Bering-szoros", "Dardanellák"]},
  {"a": "Dardanellák", "p": "Melyik szoros vezet a Márvány-tengerből az Égei-tengerbe?", "s": "Óceánok és szorosok", "w": ["Gibraltári-szoros", "Messinai-szoros", "Boszporusz"]},
  {"a": "Messinai-szoros", "p": "Melyik szoros választja el Szicíliát az olasz szárazföldtől?", "s": "Óceánok és szorosok", "w": ["Gibraltári-szoros", "Otrantói-szoros", "Bering-szoros"]},
  {"a": "Malaka-szoros", "p": "Melyik szoros fekszik Szumátra és a Maláj-félsziget között?", "s": "Óceánok és szorosok", "w": ["Gibraltári-szoros", "Magellán-szoros", "Bering-szoros"]},
  {"a": "Hormuzi-szoros", "p": "Melyik szoros vezet ki a Perzsa-öbölből?", "s": "Óceánok és szorosok", "w": ["Gibraltári-szoros", "Magellán-szoros", "Bering-szoros"]},
  {"a": "Magellán-szoros", "p": "Melyik szoros fekszik Dél-Amerika déli csücskénél?", "s": "Óceánok és szorosok", "w": ["Gibraltári-szoros", "Messinai-szoros", "Bering-szoros"]},
  {"a": "Kercsi-szoros", "p": "Melyik szoros köti össze a Fekete-tengert az Azovi-tengerrel?", "s": "Óceánok és szorosok", "w": ["Gibraltári-szoros", "Dardanellák", "Boszporusz"]},
  {"a": "Cook-szoros", "p": "Melyik szoros választja el Új-Zéland két fő szigetét?", "s": "Óceánok és szorosok", "w": ["Gibraltári-szoros", "Torres-szoros", "Bass-szoros"]},
  {"a": "Bass-szoros", "p": "Melyik szoros választja el Tasmaniát Ausztráliától?", "s": "Óceánok és szorosok", "w": ["Gibraltári-szoros", "Torres-szoros", "Cook-szoros"]},
  {"a": "Szuezi-csatorna", "p": "Melyik csatorna köti össze a Földközi-tengert a Vörös-tengerrel?", "s": "Óceánok és szorosok", "w": ["Korinthoszi-csatorna", "Panama-csatorna", "Kieli-csatorna"]},
  {"a": "Panama-csatorna", "p": "Melyik csatorna vágja át Közép-Amerikát?", "s": "Óceánok és szorosok", "w": ["Korinthoszi-csatorna", "Szuezi-csatorna", "Kieli-csatorna"]},
  {"a": "Egyiptom", "p": "Melyik országban található a Szuezi-csatorna?", "s": "Óceánok és szorosok", "w": ["Szaúd-Arábia", "Izrael", "Szudán"]},
  {"a": "Golf-áramlat", "p": "Melyik meleg tengeráramlat enyhíti Nyugat-Európa éghajlatát?", "s": "Óceánok és szorosok", "w": ["Humboldt-áramlat", "Labrador-áramlat", "Kuroshio-áramlat"]},
  {"a": "Humboldt-áramlat", "p": "Melyik hideg áramlat mossa Dél-Amerika nyugati partját?", "s": "Óceánok és szorosok", "w": ["Kelet-ausztráliai-áramlat", "Labrador-áramlat", "Golf-áramlat"]},
  {"a": "Mount Everest", "p": "Melyik a Föld legmagasabb hegycsúcsa?", "s": "Hegyek és vulkánok", "w": ["Mount Kosciuszko", "Kilimandzsáró", "Aconcagua"]},
  {"a": "Himalája", "p": "Melyik hegységben fekszik a Mount Everest?", "s": "Hegyek és vulkánok", "w": ["Kordillerák", "Kaukázus", "Andok"]},
  {"a": "K2", "p": "Melyik a világ második legmagasabb hegye?", "s": "Hegyek és vulkánok", "w": ["Mount Everest", "Kilimandzsáró", "Aconcagua"]},
  {"a": "Karakorum", "p": "Melyik hegységben található a K2?", "s": "Hegyek és vulkánok", "w": ["Skandináv-hegység", "Himalája", "Kaukázus"]},
  {"a": "Kilimandzsáró", "p": "Melyik Afrika legmagasabb hegye?", "s": "Hegyek és vulkánok", "w": ["Mount Kosciuszko", "Mount Kenya", "Ruwenzori"]},
  {"a": "Tanzánia", "p": "Melyik országban emelkedik a Kilimandzsáró?", "s": "Hegyek és vulkánok", "w": ["Dél-Afrika", "Uganda", "Kenya"]},
  {"a": "Aconcagua", "p": "Melyik Dél-Amerika legmagasabb hegye?", "s": "Hegyek és vulkánok", "w": ["Kilimandzsáró", "Chimborazo", "Cotopaxi"]},
  {"a": "Andok", "p": "Melyik hegység húzódik Dél-Amerika nyugati partján?", "s": "Hegyek és vulkánok", "w": ["Kordillerák", "Himalája", "Atlasz"]},
  {"a": "Andok", "p": "Melyik a világ leghosszabb szárazföldi hegylánca?", "s": "Hegyek és vulkánok", "w": ["Sziklás-hegység", "Himalája", "Alpok"]},
  {"a": "Sziklás-hegység", "p": "Melyik Észak-Amerika nyugati részének leghosszabb hegysége?", "s": "Hegyek és vulkánok", "w": ["Appalache-hegység", "Kaszkád-hegység", "Sierra Nevada"]},
  {"a": "Appalache-hegység", "p": "Melyik régi, kopott hegység fekszik az USA keleti részén?", "s": "Hegyek és vulkánok", "w": ["Nagy-Vízválasztó-hegység", "Sziklás-hegység", "Sierra Nevada"]},
  {"a": "Sierra Nevada", "p": "Melyik hegység fekszik Kalifornia keleti szélén?", "s": "Hegyek és vulkánok", "w": ["Appalache-hegység", "Kaszkád-hegység", "Sziklás-hegység"]},
  {"a": "Kosciuszko", "p": "Melyik hegy Ausztrália legmagasabb pontja?", "s": "Hegyek és vulkánok", "w": ["Kilimandzsáró", "Matterhorn", "Aconcagua"]},
  {"a": "Denali", "p": "Melyik Észak-Amerika legmagasabb hegye?", "s": "Hegyek és vulkánok", "w": ["Mount Whitney", "Mount Rainier", "Mount Logan"]},
  {"a": "Fudzsi", "p": "Melyik Japán legmagasabb hegye?", "s": "Hegyek és vulkánok", "w": ["Kilimandzsáró", "Matterhorn", "Aconcagua"]},
  {"a": "Vezúv", "p": "Melyik vulkán temette be Pompejit?", "s": "Hegyek és vulkánok", "w": ["Stromboli", "Krakatau", "Etna"]},
  {"a": "Etna", "p": "Melyik Európa legmagasabb működő tűzhányója?", "s": "Hegyek és vulkánok", "w": ["Stromboli", "Vezúv", "Hekla"]},
  {"a": "Szicília", "p": "Melyik szigeten emelkedik az Etna?", "s": "Hegyek és vulkánok", "w": ["Szardínia", "Korzika", "Kréta"]},
  {"a": "Krakatau", "p": "Melyik indonéz vulkán tört ki hatalmas erővel 1883-ban?", "s": "Hegyek és vulkánok", "w": ["Popocatépetl", "Pinatubo", "Merapi"]},
  {"a": "Izland", "p": "Melyik szigetország híres gejzírjeiről és vulkánjairól?", "s": "Hegyek és vulkánok", "w": ["Madagaszkár", "Grönland", "Írország"]},
  {"a": "St. Helens", "p": "Melyik amerikai vulkán tört ki 1980-ban?", "s": "Hegyek és vulkánok", "w": ["Popocatépetl", "Mauna Loa", "Kilauea"]},
  {"a": "Kilauea", "p": "Melyik hawaii vulkán ontja gyakran a lávát?", "s": "Hegyek és vulkánok", "w": ["Popocatépetl", "Mauna Loa", "Krakatau"]},
  {"a": "Popocatépetl", "p": "Melyik vulkán emelkedik Mexikóváros közelében?", "s": "Hegyek és vulkánok", "w": ["Kilimandzsáró", "Krakatau", "Cotopaxi"]},
  {"a": "Erebus", "p": "Melyik az Antarktisz működő tűzhányója?", "s": "Hegyek és vulkánok", "w": ["Kilimandzsáró", "Popocatépetl", "Vezúv"]},
  {"a": "Ararát", "p": "Melyik hegyet kötik Noé bárkájához Törökországban?", "s": "Hegyek és vulkánok", "w": ["Kilimandzsáró", "Olümposz", "Sínai"]},
  {"a": "Olümposz", "p": "Melyik hegyen laktak a görög mitológia istenei?", "s": "Hegyek és vulkánok", "w": ["Kilimandzsáró", "Parnasszosz", "Ararát"]},
  {"a": "Atlasz", "p": "Melyik hegység húzódik Marokkón és Algérián át?", "s": "Hegyek és vulkánok", "w": ["Drakensberg", "Himalája", "Kaukázus"]},
  {"a": "Drakensberg", "p": "Melyik hegység húzódik Dél-Afrikában?", "s": "Hegyek és vulkánok", "w": ["Nagy-Vízválasztó", "Ruwenzori", "Atlasz"]},
  {"a": "Tien-san", "p": "Melyik hegység húzódik Kirgizisztánon át Közép-Ázsiában?", "s": "Hegyek és vulkánok", "w": ["Karakorum", "Hindukus", "Pamír"]},
  {"a": "Tibet", "p": "Melyik magas fennsíkot nevezik a világ tetejének?", "s": "Hegyek és vulkánok", "w": ["Patagónia", "Anatólia", "Szahara"]},
  {"a": "Nepál", "p": "Melyik országban emelkedik a Mount Everest déli oldala?", "s": "Hegyek és vulkánok", "w": ["Pakisztán", "Banglades", "Bhután"]},
  {"a": "Asztal-hegy", "p": "Melyik lapos tetejű hegy Fokváros jelképe?", "s": "Hegyek és vulkánok", "w": ["Kilimandzsáró", "Drakensberg", "Mount Kenya"]},
  {"a": "Teide", "p": "Melyik a Kanári-szigetek legmagasabb hegye?", "s": "Hegyek és vulkánok", "w": ["Kilimandzsáró", "Matterhorn", "Vezúv"]},
  {"a": "Skandináv-hegység", "p": "Melyik hegység húzódik a Skandináv-félsziget gerincén?", "s": "Hegyek és vulkánok", "w": ["Nagy-Vízválasztó-hegység", "Pireneusok", "Kárpátok"]},
  {"a": "Kárpátok", "p": "Melyik hegység ívelődik Romániától Szlovákiáig?", "s": "Hegyek és vulkánok", "w": ["Skandináv-hegység", "Pireneusok", "Appenninek"]},
  {"a": "Corcovado", "p": "Melyik hegy fölött áll Rio de Janeiro Krisztus-szobra?", "s": "Hegyek és vulkánok", "w": ["Cukorsüveg-hegy", "Kilimandzsáró", "Aconcagua"]},
  {"a": "Uluru", "p": "Melyik vörös sziklaszirt Ausztrália jelképe?", "s": "Hegyek és vulkánok", "w": ["Mount Augustus", "Kings Canyon", "Kata Tjuta"]},
  {"a": "Himalája", "p": "Melyik hegység választja el Indiát Kínától?", "s": "Hegyek és vulkánok", "w": ["Skandináv-hegység", "Kaukázus", "Kárpátok"]},
  {"a": "Szahara", "p": "Melyik a világ legnagyobb forró sivataga?", "s": "Sivatagok és éghajlat", "w": ["Taklamakán", "Kalahári", "Gobi"]},
  {"a": "Afrika", "p": "Melyik földrészen terül el a Szahara?", "s": "Sivatagok és éghajlat", "w": ["Dél-Amerika", "Ausztrália", "Ázsia"]},
  {"a": "Gobi", "p": "Melyik sivatag terül el Mongólia és Kína határán?", "s": "Sivatagok és éghajlat", "w": ["Taklamakán", "Kalahári", "Szahara"]},
  {"a": "Kalahári", "p": "Melyik sivatag terül el Botswanában és Namíbiában?", "s": "Sivatagok és éghajlat", "w": ["Taklamakán", "Szahara", "Namib"]},
  {"a": "Atacama", "p": "Melyik a világ legszárazabb sivataga Chilében?", "s": "Sivatagok és éghajlat", "w": ["Taklamakán", "Kalahári", "Szahara"]},
  {"a": "Namib", "p": "Melyik sivatag húzódik Namíbia partja mentén?", "s": "Sivatagok és éghajlat", "w": ["Taklamakán", "Kalahári", "Szahara"]},
  {"a": "Thar", "p": "Melyik sivatag terül el India és Pakisztán között?", "s": "Sivatagok és éghajlat", "w": ["Taklamakán", "Kalahári", "Szahara"]},
  {"a": "Rub-al-Kháli", "p": "Melyik homoksivatag borítja az Arab-félsziget déli részét?", "s": "Sivatagok és éghajlat", "w": ["Nagy-Viktória-sivatag", "Taklamakán", "Kalahári"]},
  {"a": "Taklamakán", "p": "Melyik sivatag terül el Nyugat-Kínában?", "s": "Sivatagok és éghajlat", "w": ["Nagy-Viktória", "Kalahári", "Szahara"]},
  {"a": "Nagy-Viktória", "p": "Melyik sivatag terül el Ausztrália belsejében?", "s": "Sivatagok és éghajlat", "w": ["Nagy-Homok-sivatag", "Taklamakán", "Szimpszon"]},
  {"a": "Mojave", "p": "Melyik sivatag terül el Nevada és Kalifornia között?", "s": "Sivatagok és éghajlat", "w": ["Chihuahua", "Szonora", "Gobi"]},
  {"a": "Trópusi", "p": "Melyik éghajlat jellemző az Egyenlítő környékére?", "s": "Sivatagok és éghajlat", "w": ["Sarkvidéki", "Mediterrán", "Sivatagi"]},
  {"a": "Mediterrán", "p": "Melyik éghajlatra jellemző a forró, száraz nyár és az enyhe tél?", "s": "Sivatagok és éghajlat", "w": ["Kontinentális", "Sarkvidéki", "Trópusi"]},
  {"a": "Sarkvidéki", "p": "Milyen éghajlat uralkodik az Antarktiszon?", "s": "Sivatagok és éghajlat", "w": ["Kontinentális", "Mediterrán", "Trópusi"]},
  {"a": "Monszun", "p": "Melyik szél hozza az esős évszakot Indiába?", "s": "Sivatagok és éghajlat", "w": ["Passzátszél", "Ciklon", "Mistral"]},
  {"a": "Tájfun", "p": "Hogyan nevezik a Csendes-óceán trópusi forgószeleit?", "s": "Sivatagok és éghajlat", "w": ["Hurrikán", "Tornádó", "Monszun"]},
  {"a": "Hurrikán", "p": "Hogyan nevezik a Karib-térség trópusi forgószeleit?", "s": "Sivatagok és éghajlat", "w": ["Passzátszél", "Monszun", "Tájfun"]},
  {"a": "Tornádó", "p": "Hogyan nevezik a szárazföld fölött tölcsért formáló forgószelet?", "s": "Sivatagok és éghajlat", "w": ["Passzátszél", "Hurrikán", "Monszun"]},
  {"a": "El Niño", "p": "Hogyan nevezik a Csendes-óceán felmelegedésével járó jelenséget?", "s": "Sivatagok és éghajlat", "w": ["Passzátszél", "Monszun", "Tájfun"]},
  {"a": "Tundra", "p": "Melyik övezetben nem nő fa a hideg és a fagyott talaj miatt?", "s": "Sivatagok és éghajlat", "w": ["Szavanna", "Sztyepp", "Tajga"]},
  {"a": "Tajga", "p": "Hogyan nevezik Szibéria hatalmas tűlevelű erdeit?", "s": "Sivatagok és éghajlat", "w": ["Szavanna", "Sztyepp", "Tundra"]},
  {"a": "Szavanna", "p": "Hogyan nevezik Afrika füves, ritkás fás pusztáit?", "s": "Sivatagok és éghajlat", "w": ["Félsivatag", "Sztyepp", "Tundra"]},
  {"a": "Egyenlítő", "p": "Melyik vonal mentén a legnagyobb a Föld kerülete?", "s": "Sivatagok és éghajlat", "w": ["Greenwichi délkör", "Ráktérítő", "Baktérítő"]},
  {"a": "Ráktérítő", "p": "Melyik térítő halad át a Szaharán?", "s": "Sivatagok és éghajlat", "w": ["Greenwichi délkör", "Egyenlítő", "Baktérítő"]},
  {"a": "Kezdő délkör", "p": "Melyik vonaltól mérik a földrajzi hosszúságot?", "s": "Sivatagok és éghajlat", "w": ["Északi sarkkör", "Egyenlítő", "Ráktérítő"]},
  {"a": "London", "p": "Melyik városon halad át a kezdő délkör?", "s": "Sivatagok és éghajlat", "w": ["Amszterdam", "Párizs", "Madrid"]},
  {"a": "Antarktisz", "p": "Melyik földrészen mérték a Föld leghidegebb hőmérsékletét?", "s": "Sivatagok és éghajlat", "w": ["Észak-Amerika", "Ausztrália", "Európa"]},
  {"a": "Földrengést", "p": "Mit mérnek a Richter-skálával?", "s": "Sivatagok és éghajlat", "w": ["Szélsebességet", "Hőmérsékletet", "Csapadékot"]},
  {"a": "Szökőár", "p": "Hogyan nevezik a földrengés keltette óriáshullámot?", "s": "Sivatagok és éghajlat", "w": ["Hurrikán", "Monszun", "Tájfun"]},
  {"a": "Tűzgyűrű", "p": "Hogyan nevezik a Csendes-óceánt övező vulkános zónát?", "s": "Sivatagok és éghajlat", "w": ["Golf-áramlat", "Szélcsend-öv", "Passzátöv"]},
  {"a": "Nyár", "p": "Melyik évszak van Ausztráliában, amikor Európában tél?", "s": "Sivatagok és éghajlat", "w": ["Tavasz", "Ősz", "Tél"]},
  {"a": "Sarki fény", "p": "Melyik jelenség fest színes fényeket a sarkvidéki égre?", "s": "Sivatagok és éghajlat", "w": ["Napfogyatkozás", "Szivárvány", "Délibáb"]},
  {"a": "Amazónia", "p": "Melyik a Föld legnagyobb összefüggő esőerdeje?", "s": "Sivatagok és éghajlat", "w": ["Kongó-medence", "Új-Guinea", "Borneó"]},
  {"a": "Grönland", "p": "Melyik a világ legnagyobb szigete?", "s": "Szigetek és félszigetek", "w": ["Madagaszkár", "Új-Guinea", "Borneó"]},
  {"a": "Dánia", "p": "Melyik országhoz tartozik Grönland?", "s": "Szigetek és félszigetek", "w": ["Norvégia", "Kanada", "Izland"]},
  {"a": "Új-Guinea", "p": "Melyik a világ második legnagyobb szigete?", "s": "Szigetek és félszigetek", "w": ["Madagaszkár", "Grönland", "Borneó"]},
  {"a": "Borneó", "p": "Melyik a világ harmadik legnagyobb szigete?", "s": "Szigetek és félszigetek", "w": ["Madagaszkár", "Új-Guinea", "Szumátra"]},
  {"a": "Madagaszkár", "p": "Melyik nagy sziget fekszik Afrika keleti partjánál?", "s": "Szigetek és félszigetek", "w": ["Seychelle-szigetek", "Mauritius", "Zanzibár"]},
  {"a": "Borneó", "p": "Melyik sziget oszlik meg Indonézia, Malajzia és Brunei között?", "s": "Szigetek és félszigetek", "w": ["Új-Guinea", "Szumátra", "Celebesz"]},
  {"a": "Honsú", "p": "Melyik Japán legnagyobb szigete?", "s": "Szigetek és félszigetek", "w": ["Hokkaidó", "Sikoku", "Kjúsú"]},
  {"a": "Hispaniola", "p": "Melyik szigeten osztozik Haiti és a Dominikai Köztársaság?", "s": "Szigetek és félszigetek", "w": ["Puerto Rico", "Jamaica", "Kuba"]},
  {"a": "Kuba", "p": "Melyik a Karib-térség legnagyobb szigete?", "s": "Szigetek és félszigetek", "w": ["Hispaniola", "Puerto Rico", "Jamaica"]},
  {"a": "Tasmania", "p": "Melyik sziget fekszik Ausztráliától délre?", "s": "Szigetek és félszigetek", "w": ["Új-Kaledónia", "Új-Zéland", "Új-Guinea"]},
  {"a": "Galápagos", "p": "Melyik szigetcsoport fekszik Ecuadortól nyugatra?", "s": "Szigetek és félszigetek", "w": ["Fidzsi-szigetek", "Kanári-szigetek", "Azori-szigetek"]},
  {"a": "Ecuador", "p": "Melyik országhoz tartoznak a Galápagos-szigetek?", "s": "Szigetek és félszigetek", "w": ["Kolumbia", "Bolívia", "Peru"]},
  {"a": "Húsvét-sziget", "p": "Melyik szigeten állnak a moai nevű hatalmas kőszobrok?", "s": "Szigetek és félszigetek", "w": ["Galápagos-szigetek", "Tahiti", "Hawaii"]},
  {"a": "Chile", "p": "Melyik országhoz tartozik a Húsvét-sziget?", "s": "Szigetek és félszigetek", "w": ["Argentína", "Ecuador", "Peru"]},
  {"a": "Spanyolország", "p": "Melyik ország birtokolja a Kanári-szigeteket?", "s": "Szigetek és félszigetek", "w": ["Nagy-Britannia", "Portugália", "Marokkó"]},
  {"a": "Portugália", "p": "Melyik ország birtokolja az Azori-szigeteket?", "s": "Szigetek és félszigetek", "w": ["Spanyolország", "Marokkó", "Izland"]},
  {"a": "Szicília", "p": "Melyik a Földközi-tenger legnagyobb szigete?", "s": "Szigetek és félszigetek", "w": ["Szardínia", "Korzika", "Ciprus"]},
  {"a": "Srí Lanka", "p": "Melyik szigetország fekszik India déli csücskénél?", "s": "Szigetek és félszigetek", "w": ["Maldív-szigetek", "Indonézia", "Mianmar"]},
  {"a": "Maldív-szigetek", "p": "Melyik szigetország áll apró korallszigetekből az Indiai-óceánon?", "s": "Szigetek és félszigetek", "w": ["Seychelle-szigetek", "Srí Lanka", "Mauritius"]},
  {"a": "Ibériai-félsziget", "p": "Melyik félszigeten fekszik Spanyolország és Portugália?", "s": "Szigetek és félszigetek", "w": ["Peloponnészoszi-félsziget", "Skandináv-félsziget", "Balkán-félsziget"]},
  {"a": "Balkán-félsziget", "p": "Melyik félszigeten fekszik Görögország és Bulgária?", "s": "Szigetek és félszigetek", "w": ["Peloponnészoszi-félsziget", "Ibériai-félsziget", "Krím-félsziget"]},
  {"a": "Skandináv-félsziget", "p": "Melyik félszigeten fekszik Norvégia és Svédország?", "s": "Szigetek és félszigetek", "w": ["Peloponnészoszi-félsziget", "Ibériai-félsziget", "Balkán-félsziget"]},
  {"a": "Appennini-félsziget", "p": "Melyik félszigeten fekszik Olaszország?", "s": "Szigetek és félszigetek", "w": ["Peloponnészoszi-félsziget", "Ibériai-félsziget", "Balkán-félsziget"]},
  {"a": "Arab-félsziget", "p": "Melyik félszigeten fekszik Szaúd-Arábia?", "s": "Szigetek és félszigetek", "w": ["Peloponnészoszi-félsziget", "Ibériai-félsziget", "Balkán-félsziget"]},
  {"a": "Koreai-félsziget", "p": "Melyik félszigeten fekszik Észak-Korea és Dél-Korea?", "s": "Szigetek és félszigetek", "w": ["Peloponnészoszi-félsziget", "Indokínai-félsziget", "Arab-félsziget"]},
  {"a": "Krím-félsziget", "p": "Melyik félsziget nyúlik délről a Fekete-tengerbe?", "s": "Szigetek és félszigetek", "w": ["Peloponnészoszi-félsziget", "Balkán-félsziget", "Kola-félsziget"]},
  {"a": "Kamcsatka", "p": "Melyik orosz félsziget híres a vulkánjairól?", "s": "Szigetek és félszigetek", "w": ["Peloponnészosz", "Anatólia", "Krím"]},
  {"a": "Anatólia", "p": "Melyik félsziget alkotja Törökország ázsiai részét?", "s": "Szigetek és félszigetek", "w": ["Peloponnészosz", "Kamcsatka", "Krím"]},
  {"a": "Florida", "p": "Melyik amerikai félsziget nyúlik délre Kuba felé?", "s": "Szigetek és félszigetek", "w": ["Kaliforniai-félsziget", "Labrador", "Jukatán"]},
  {"a": "Jukatán", "p": "Melyik mexikói félsziget nyúlik a Mexikói-öbölbe?", "s": "Szigetek és félszigetek", "w": ["Kaliforniai-félsziget", "Labrador", "Florida"]},
  {"a": "Labrador", "p": "Melyik nagy félsziget fekszik Kanada keleti részén?", "s": "Szigetek és félszigetek", "w": ["Kaliforniai-félsziget", "Kamcsatka", "Jukatán"]},
  {"a": "Peloponnészosz", "p": "Melyik félsziget alkotja Görögország déli részét?", "s": "Szigetek és félszigetek", "w": ["Kaliforniai-félsziget", "Kamcsatka", "Anatólia"]},
  {"a": "Málta", "p": "Melyik szigetország fekszik Szicíliától délre?", "s": "Szigetek és félszigetek", "w": ["Szardínia", "Korzika", "Ciprus"]},
  {"a": "Jáva", "p": "Melyik Indonézia legnépesebb szigete?", "s": "Szigetek és félszigetek", "w": ["Szumátra", "Celebesz", "Borneó"]},
  {"a": "Spitzbergák", "p": "Melyik norvég szigetcsoport fekszik a Jeges-tengerben?", "s": "Szigetek és félszigetek", "w": ["Feröer-szigetek", "Lofoten", "Izland"]},
  {"a": "Írország", "p": "Melyik sziget Nagy-Britannia nyugati szomszédja?", "s": "Szigetek és félszigetek", "w": ["Man-sziget", "Grönland", "Izland"]},
  {"a": "Tanzánia", "p": "Melyik országhoz tartozik Zanzibár?", "s": "Szigetek és félszigetek", "w": ["Madagaszkár", "Mozambik", "Kenya"]},
  {"a": "Bali", "p": "Melyik indonéz sziget híres üdülőhely?", "s": "Szigetek és félszigetek", "w": ["Szumátra", "Celebesz", "Jáva"]},
  {"a": "Nagy-korallzátony", "p": "Melyik a világ legnagyobb korallzátonya?", "s": "Szigetek és félszigetek", "w": ["Belize-korallzátony", "Maldív-zátony", "Hawaii-zátony"]},
  {"a": "Hét", "p": "Hány földrész van a Földön a hagyományos felosztás szerint?", "s": "Kontinensek és határok", "w": ["Kilenc", "Hat", "Öt"]},
  {"a": "Ázsia", "p": "Melyik a legnagyobb földrész?", "s": "Kontinensek és határok", "w": ["Észak-Amerika", "Afrika", "Európa"]},
  {"a": "Afrika", "p": "Melyik a második legnagyobb földrész?", "s": "Kontinensek és határok", "w": ["Észak-Amerika", "Ausztrália", "Európa"]},
  {"a": "Ausztrália", "p": "Melyik a legkisebb földrész?", "s": "Kontinensek és határok", "w": ["Észak-Amerika", "Antarktisz", "Európa"]},
  {"a": "Antarktisz", "p": "Melyik földrészen nem él állandó lakosság?", "s": "Kontinensek és határok", "w": ["Észak-Amerika", "Ausztrália", "Afrika"]},
  {"a": "Ázsia", "p": "Melyik a legnépesebb földrész?", "s": "Kontinensek és határok", "w": ["Észak-Amerika", "Afrika", "Európa"]},
  {"a": "Dél-Amerika", "p": "Melyik földrészen fekszik Brazília?", "s": "Kontinensek és határok", "w": ["Észak-Amerika", "Ausztrália", "Afrika"]},
  {"a": "Afrika", "p": "Melyik földrészen fekszik Egyiptom?", "s": "Kontinensek és határok", "w": ["Dél-Amerika", "Európa", "Ázsia"]},
  {"a": "Ázsia", "p": "Melyik földrészen fekszik India?", "s": "Kontinensek és határok", "w": ["Dél-Amerika", "Afrika", "Európa"]},
  {"a": "Észak-Amerika", "p": "Melyik földrészen fekszik Mexikó?", "s": "Kontinensek és határok", "w": ["Ausztrália és Óceánia", "Dél-Amerika", "Afrika"]},
  {"a": "Oroszország", "p": "Melyik a világ legnagyobb területű országa?", "s": "Kontinensek és határok", "w": ["Egyesült Államok", "Kanada", "Kína"]},
  {"a": "Kanada", "p": "Melyik a világ második legnagyobb területű országa?", "s": "Kontinensek és határok", "w": ["Egyesült Államok", "Ausztrália", "Brazília"]},
  {"a": "Brazília", "p": "Melyik Dél-Amerika legnagyobb országa?", "s": "Kontinensek és határok", "w": ["Argentína", "Venezuela", "Kolumbia"]},
  {"a": "Algéria", "p": "Melyik Afrika legnagyobb területű országa?", "s": "Kontinensek és határok", "w": ["Dél-Afrika", "Egyiptom", "Szudán"]},
  {"a": "Brazília", "p": "Melyik dél-amerikai ország határos a legtöbb szomszéddal?", "s": "Kontinensek és határok", "w": ["Argentína", "Venezuela", "Kolumbia"]},
  {"a": "Andorra", "p": "Melyik ország határos Franciaországgal és Spanyolországgal is?", "s": "Kontinensek és határok", "w": ["Portugália", "Luxemburg", "Belgium"]},
  {"a": "Spanyolország", "p": "Melyik ország határos Portugáliával?", "s": "Kontinensek és határok", "w": ["Nagy-Britannia", "Franciaország", "Marokkó"]},
  {"a": "Mongólia", "p": "Melyik ország fekszik teljesen Kína és Oroszország között?", "s": "Kontinensek és határok", "w": ["Kirgizisztán", "Üzbegisztán", "Kazahsztán"]},
  {"a": "Dél-Afrika", "p": "Melyik ország veszi körül teljesen Lesothót?", "s": "Kontinensek és határok", "w": ["Madagaszkár", "Mozambik", "Botswana"]},
  {"a": "Chile", "p": "Melyik hosszú, keskeny ország fekszik Dél-Amerika nyugati partján?", "s": "Kontinensek és határok", "w": ["Argentína", "Ecuador", "Peru"]},
  {"a": "Kanada és az USA", "p": "Melyik két ország osztozik a világ leghosszabb határán?", "s": "Kontinensek és határok", "w": ["Oroszország és Kína", "Mexikó és az USA", "India és Kína"]},
  {"a": "Ukrajna", "p": "Melyik ország volt korábban a Szovjetunió része?", "s": "Kontinensek és határok", "w": ["Lengyelország", "Csehország", "Románia"]},
  {"a": "Csehszlovákia", "p": "Melyik ország bomlott két államra 1993-ban?", "s": "Kontinensek és határok", "w": ["Nagy-Britannia", "Jugoszlávia", "Szovjetunió"]},
  {"a": "Jugoszlávia", "p": "Melyik ország bomlott fel több balkáni államra a kilencvenes években?", "s": "Kontinensek és határok", "w": ["Ausztria-Magyarország", "Csehszlovákia", "Szovjetunió"]},
  {"a": "Németország", "p": "Melyik ország egyesült újra 1990-ben?", "s": "Kontinensek és határok", "w": ["Csehszlovákia", "Jugoszlávia", "Ausztria"]},
  {"a": "Dél-Szudán", "p": "Melyik ország vált ki Szudánból 2011-ben?", "s": "Kontinensek és határok", "w": ["Elefántcsontpart", "Eritrea", "Csád"]},
  {"a": "Eswatini", "p": "Melyik afrikai ország viselte korábban a Szváziföld nevet?", "s": "Kontinensek és határok", "w": ["Madagaszkár", "Mozambik", "Botswana"]},
  {"a": "Nagy-Britannia", "p": "Melyik ország lépett ki az Európai Unióból?", "s": "Kontinensek és határok", "w": ["Bosznia-Hercegovina", "Franciaország", "Lengyelország"]},
  {"a": "Dél-Afrika", "p": "Melyik ország déli csücskén áll a Jóreménység foka?", "s": "Kontinensek és határok", "w": ["Madagaszkár", "Namíbia", "Angola"]},
  {"a": "Srí Lanka", "p": "Melyik ország neve volt korábban Ceylon?", "s": "Kontinensek és határok", "w": ["Fülöp-szigetek", "Banglades", "Mianmar"]},
  {"a": "Mianmar", "p": "Melyik ország neve volt korábban Burma?", "s": "Kontinensek és határok", "w": ["Fülöp-szigetek", "Kambodzsa", "Thaiföld"]},
  {"a": "Irán", "p": "Melyik ország neve volt korábban Perzsia?", "s": "Kontinensek és határok", "w": ["Afganisztán", "Törökország", "Irak"]},
  {"a": "Thaiföld", "p": "Melyik ország neve volt korábban Sziám?", "s": "Kontinensek és határok", "w": ["Kambodzsa", "Vietnam", "Laosz"]},
  {"a": "Kongó", "p": "Melyik ország neve volt korábban Zaire?", "s": "Kontinensek és határok", "w": ["Zimbabwe", "Angola", "Zambia"]},
  {"a": "Zimbabwe", "p": "Melyik ország neve volt korábban Rodézia?", "s": "Kontinensek és határok", "w": ["Madagaszkár", "Mozambik", "Zambia"]},
  {"a": "Etiópia", "p": "Melyik ország neve volt korábban Abesszínia?", "s": "Kontinensek és határok", "w": ["Szomália", "Eritrea", "Szudán"]},
  {"a": "Bolívia", "p": "Melyik dél-amerikai ország határos Chilével és Brazíliával is?", "s": "Kontinensek és határok", "w": ["Paraguay", "Ecuador", "Uruguay"]},
  {"a": "Párizs", "p": "Melyik városban áll az Eiffel-torony?", "s": "Nevezetességek és jelképek", "w": ["Marseille", "Brüsszel", "Lyon"]},
  {"a": "Róma", "p": "Melyik városban áll a Kolosszeum?", "s": "Nevezetességek és jelképek", "w": ["Firenze", "Nápoly", "Athén"]},
  {"a": "Pisa", "p": "Melyik olasz városban áll a ferde torony?", "s": "Nevezetességek és jelképek", "w": ["Firenze", "Velence", "Siena"]},
  {"a": "Athén", "p": "Melyik városban áll az Akropolisz?", "s": "Nevezetességek és jelképek", "w": ["Isztambul", "Szaloniki", "Róma"]},
  {"a": "Barcelona", "p": "Melyik városban áll a Sagrada Família?", "s": "Nevezetességek és jelképek", "w": ["Guadalajara", "Sevilla", "Madrid"]},
  {"a": "Granada", "p": "Melyik spanyol városban áll az Alhambra?", "s": "Nevezetességek és jelképek", "w": ["Barcelona", "Sevilla", "Madrid"]},
  {"a": "Anglia", "p": "Melyik országban áll a Stonehenge kőköre?", "s": "Nevezetességek és jelképek", "w": ["Írország", "Skócia", "Wales"]},
  {"a": "Berlin", "p": "Melyik városban áll a Brandenburgi kapu?", "s": "Nevezetességek és jelképek", "w": ["Hamburg", "München", "Drezda"]},
  {"a": "Moszkva", "p": "Melyik városban áll a Kreml?", "s": "Nevezetességek és jelképek", "w": ["Szentpétervár", "Novgorod", "Kazany"]},
  {"a": "Isztambul", "p": "Melyik városban áll a Hagia Szophia?", "s": "Nevezetességek és jelképek", "w": ["Alexandria", "Ankara", "Athén"]},
  {"a": "Jordánia", "p": "Melyik országban található Petra sziklavárosa?", "s": "Nevezetességek és jelképek", "w": ["Szaúd-Arábia", "Egyiptom", "Szíria"]},
  {"a": "Egyiptom", "p": "Melyik országban állnak a gízai piramisok?", "s": "Nevezetességek és jelképek", "w": ["Szaúd-Arábia", "Szudán", "Líbia"]},
  {"a": "Szfinx", "p": "Melyik gízai kőszobornak van oroszlánteste és emberfeje?", "s": "Nevezetességek és jelképek", "w": ["Kolosszus", "Obeliszk", "Piramis"]},
  {"a": "Kína", "p": "Melyik országban áll a Nagy Fal?", "s": "Nevezetességek és jelképek", "w": ["Mongólia", "Japán", "India"]},
  {"a": "Peking", "p": "Melyik kínai városban áll a Tiltott Város?", "s": "Nevezetességek és jelképek", "w": ["Hongkong", "Sanghaj", "Hszian"]},
  {"a": "Hszian", "p": "Melyik kínai városban ásták ki a terrakotta hadsereget?", "s": "Nevezetességek és jelképek", "w": ["Hongkong", "Sanghaj", "Peking"]},
  {"a": "India", "p": "Melyik országban áll a Tádzs Mahal?", "s": "Nevezetességek és jelképek", "w": ["Pakisztán", "Banglades", "Nepál"]},
  {"a": "Ágra", "p": "Melyik indiai városban áll a Tádzs Mahal?", "s": "Nevezetességek és jelképek", "w": ["Jaipur", "Mumbai", "Delhi"]},
  {"a": "Kambodzsa", "p": "Melyik országban áll Angkorvat templomvárosa?", "s": "Nevezetességek és jelképek", "w": ["Fülöp-szigetek", "Thaiföld", "Vietnam"]},
  {"a": "Indonézia", "p": "Melyik országban áll Borobudur buddhista temploma?", "s": "Nevezetességek és jelképek", "w": ["Fülöp-szigetek", "Malajzia", "Thaiföld"]},
  {"a": "Peru", "p": "Melyik országban található Machu Picchu?", "s": "Nevezetességek és jelképek", "w": ["Kolumbia", "Ecuador", "Bolívia"]},
  {"a": "Az inkák", "p": "Melyik nép építette Machu Picchut?", "s": "Nevezetességek és jelképek", "w": ["Az olmékok", "Az aztékok", "A maják"]},
  {"a": "Mexikó", "p": "Melyik országban áll Chichén Itzá piramisa?", "s": "Nevezetességek és jelképek", "w": ["Guatemala", "Honduras", "Belize"]},
  {"a": "Peru", "p": "Melyik országban rajzolták a sivatagba a Nazca-vonalakat?", "s": "Nevezetességek és jelképek", "w": ["Argentína", "Kolumbia", "Chile"]},
  {"a": "New York", "p": "Melyik városban áll a Szabadság-szobor?", "s": "Nevezetességek és jelképek", "w": ["Philadelphia", "Washington", "Boston"]},
  {"a": "Franciaország", "p": "Melyik ország ajándékozta a Szabadság-szobrot Amerikának?", "s": "Nevezetességek és jelképek", "w": ["Nagy-Britannia", "Spanyolország", "Hollandia"]},
  {"a": "San Francisco", "p": "Melyik város jelképe a Golden Gate híd?", "s": "Nevezetességek és jelképek", "w": ["Salt Lake City", "Los Angeles", "Seattle"]},
  {"a": "Arizona", "p": "Melyik amerikai államban található a Grand Canyon?", "s": "Nevezetességek és jelképek", "w": ["Kalifornia", "Colorado", "Nevada"]},
  {"a": "Dél-Dakota", "p": "Melyik amerikai államban áll a Mount Rushmore?", "s": "Nevezetességek és jelképek", "w": ["Massachusetts", "Wyoming", "Montana"]},
  {"a": "Sydney", "p": "Melyik város jelképe a vitorla alakú tetejű Operaház?", "s": "Nevezetességek és jelképek", "w": ["Melbourne", "Brisbane", "Auckland"]},
  {"a": "Brazília", "p": "Melyik országban áll a Megváltó Krisztus hegyi szobra?", "s": "Nevezetességek és jelképek", "w": ["Argentína", "Kolumbia", "Peru"]},
  {"a": "Zimbabwe", "p": "Melyik ország osztozik Zambiával a Viktória-vízesésen?", "s": "Nevezetességek és jelképek", "w": ["Madagaszkár", "Mozambik", "Botswana"]},
  {"a": "Tanzánia", "p": "Melyik országban található a Serengeti nemzeti park?", "s": "Nevezetességek és jelképek", "w": ["Dél-Afrika", "Uganda", "Kenya"]},
  {"a": "Dél-Afrika", "p": "Melyik országban található a Kruger Nemzeti Park?", "s": "Nevezetességek és jelképek", "w": ["Madagaszkár", "Tanzánia", "Kenya"]},
  {"a": "Németország", "p": "Melyik országban áll a Neuschwanstein mesekastély?", "s": "Nevezetességek és jelképek", "w": ["Liechtenstein", "Ausztria", "Svájc"]},
  {"a": "Moszkva", "p": "Melyik városban áll a Vaszilij Blazsennij-székesegyház?", "s": "Nevezetességek és jelképek", "w": ["Szentpétervár", "Novgorod", "Kijev"]},
  {"a": "London", "p": "Melyik városban áll a Big Ben óratornya?", "s": "Nevezetességek és jelképek", "w": ["Manchester", "Edinburgh", "Dublin"]},
  {"a": "Vatikánváros", "p": "Melyik városban áll a Szent Péter-bazilika?", "s": "Nevezetességek és jelképek", "w": ["Konstantinápoly", "Firenze", "Róma"]},
  {"a": "Louvre", "p": "Melyik múzeumban őrzik a Mona Lisát?", "s": "Nevezetességek és jelképek", "w": ["Ermitázs", "Uffizi", "Prado"]},
  {"a": "Szentpétervár", "p": "Melyik városban áll az Ermitázs múzeum?", "s": "Nevezetességek és jelképek", "w": ["Jekatyerinburg", "Moszkva", "Kijev"]},
  {"a": "Kalifornia", "p": "Melyik amerikai államban fekszik a Halál-völgy?", "s": "Nevezetességek és jelképek", "w": ["Massachusetts", "Arizona", "Nevada"]},
  {"a": "Kanada", "p": "Melyik ország zászlaján van vörös juharlevél?", "s": "Nevezetességek és jelképek", "w": ["Ausztrália", "Új-Zéland", "Norvégia"]},
  {"a": "Japán", "p": "Melyik ország zászlaján van vörös kör fehér alapon?", "s": "Nevezetességek és jelképek", "w": ["Banglades", "Dél-Korea", "Kína"]},
  {"a": "Libanon", "p": "Melyik ország zászlaján áll egy cédrusfa?", "s": "Nevezetességek és jelképek", "w": ["Jordánia", "Szíria", "Ciprus"]},
  {"a": "Egyesült Államok", "p": "Melyik ország zászlaján van ötven csillag?", "s": "Nevezetességek és jelképek", "w": ["Bosznia-Hercegovina", "Nagy-Britannia", "Ausztrália"]},
  {"a": "Izrael", "p": "Melyik ország zászlaján van a Dávid-csillag?", "s": "Nevezetességek és jelképek", "w": ["Törökország", "Jordánia", "Libanon"]},
  {"a": "Törökország", "p": "Melyik ország zászlaján van félhold és csillag vörös alapon?", "s": "Nevezetességek és jelképek", "w": ["Szaúd-Arábia", "Pakisztán", "Egyiptom"]},
  {"a": "Bhután", "p": "Melyik ország zászlaján van sárkány?", "s": "Nevezetességek és jelképek", "w": ["Mongólia", "Nepál", "Kína"]},
  {"a": "Nepál", "p": "Melyik ország zászlaja nem négyszögletes?", "s": "Nevezetességek és jelképek", "w": ["Srí Lanka", "Mongólia", "Bhután"]},
  {"a": "Ukrajna", "p": "Melyik ország zászlaja kék-sárga vízszintes sávos?", "s": "Nevezetességek és jelképek", "w": ["Svédország", "Románia", "Moldova"]},
  {"a": "Svédország", "p": "Melyik ország zászlaján van sárga kereszt kék alapon?", "s": "Nevezetességek és jelképek", "w": ["Oroszország", "Norvégia", "Izland"]},
  {"a": "Ausztrália", "p": "Melyik ország címerállata a kenguru és az emu?", "s": "Nevezetességek és jelképek", "w": ["Pápua Új-Guinea", "Indonézia", "Új-Zéland"]},
  {"a": "Új-Zéland", "p": "Melyik ország nemzeti jelképe a kiwi madár?", "s": "Nevezetességek és jelképek", "w": ["Ausztrália", "Indonézia", "Fidzsi"]},
  {"a": "Koppenhága", "p": "Melyik város jelképe a kis hableány szobra?", "s": "Nevezetességek és jelképek", "w": ["Szentpétervár", "Stockholm", "Oslo"]},
  {"a": "Brüsszel", "p": "Melyik város jelképe a Manneken Pis szobor?", "s": "Nevezetességek és jelképek", "w": ["Amszterdam", "Antwerpen", "Párizs"]},
  {"a": "India", "p": "Melyik a világ legnépesebb országa?", "s": "Népesség, nyelvek, pénznemek", "w": ["Indonézia", "Kína", "USA"]},
  {"a": "Kína", "p": "Melyik a világ második legnépesebb országa?", "s": "Népesség, nyelvek, pénznemek", "w": ["Indonézia", "India", "USA"]},
  {"a": "Nigéria", "p": "Melyik a legnépesebb ország Afrikában?", "s": "Népesség, nyelvek, pénznemek", "w": ["Dél-Afrika", "Egyiptom", "Etiópia"]},
  {"a": "A kínai", "p": "Melyik nyelvet beszélik a legtöbben anyanyelvként?", "s": "Népesség, nyelvek, pénznemek", "w": ["A spanyol", "Az angol", "A hindi"]},
  {"a": "Az angol", "p": "Melyik nyelv hivatalos a legtöbb országban?", "s": "Népesség, nyelvek, pénznemek", "w": ["A spanyol", "A francia", "Az arab"]},
  {"a": "Brazília", "p": "Melyik dél-amerikai országban beszélnek portugálul?", "s": "Népesség, nyelvek, pénznemek", "w": ["Argentína", "Venezuela", "Kolumbia"]},
  {"a": "Spanyol", "p": "Melyik nyelvet beszélik Argentínában?", "s": "Népesség, nyelvek, pénznemek", "w": ["Portugál", "Francia", "Olasz"]},
  {"a": "Német", "p": "Melyik nyelv hivatalos Ausztriában?", "s": "Népesség, nyelvek, pénznemek", "w": ["Holland", "Francia", "Olasz"]},
  {"a": "Holland", "p": "Melyik nyelvet beszélik Flandriában, Belgium északi részén?", "s": "Népesség, nyelvek, pénznemek", "w": ["Portugál", "Francia", "Német"]},
  {"a": "Olasz", "p": "Melyik nyelv hivatalos Svájcban a német és a francia mellett?", "s": "Népesség, nyelvek, pénznemek", "w": ["Portugál", "Spanyol", "Holland"]},
  {"a": "Arab", "p": "Melyik nyelvet beszélik Egyiptomban?", "s": "Népesség, nyelvek, pénznemek", "w": ["Perzsa", "Török", "Héber"]},
  {"a": "Irán", "p": "Melyik országban beszélnek perzsául?", "s": "Népesség, nyelvek, pénznemek", "w": ["Törökország", "Pakisztán", "Irak"]},
  {"a": "India", "p": "Melyik országban beszélnek hindiül?", "s": "Népesség, nyelvek, pénznemek", "w": ["Pakisztán", "Banglades", "Nepál"]},
  {"a": "Francia", "p": "Melyik nyelvet beszélik Kanadában az angol mellett?", "s": "Népesség, nyelvek, pénznemek", "w": ["Portugál", "Spanyol", "Holland"]},
  {"a": "Finn és svéd", "p": "Melyik két nyelv hivatalos Finnországban?", "s": "Népesség, nyelvek, pénznemek", "w": ["Finn és norvég", "Finn és orosz", "Finn és észt"]},
  {"a": "Finnugor", "p": "Melyik nyelvcsaládba tartozik a finn nyelv?", "s": "Népesség, nyelvek, pénznemek", "w": ["Indoeurópai", "Germán", "Szláv"]},
  {"a": "Angol", "p": "Melyik nyelvet beszélik Ausztráliában?", "s": "Népesség, nyelvek, pénznemek", "w": ["Holland", "Francia", "Maori"]},
  {"a": "Maori", "p": "Melyik nyelv hivatalos Új-Zélandon az angol mellett?", "s": "Népesség, nyelvek, pénznemek", "w": ["Portugál", "Szamoai", "Fidzsi"]},
  {"a": "Spanyol", "p": "Melyik nyelvet beszélik a legtöbben Mexikóban?", "s": "Népesség, nyelvek, pénznemek", "w": ["Portugál", "Francia", "Angol"]},
  {"a": "Ciprus", "p": "Melyik ország hivatalos nyelve a görög és a török is?", "s": "Népesség, nyelvek, pénznemek", "w": ["Görögország", "Törökország", "Málta"]},
  {"a": "A héber", "p": "Melyik nyelv Izrael hivatalos nyelve?", "s": "Népesség, nyelvek, pénznemek", "w": ["A jiddis", "A perzsa", "Az arab"]},
  {"a": "Mexikó", "p": "Melyik országban él a legtöbb spanyolul beszélő ember?", "s": "Népesség, nyelvek, pénznemek", "w": ["Spanyolország", "Argentína", "Kolumbia"]},
  {"a": "A cirill", "p": "Melyik írást használják Oroszországban?", "s": "Népesség, nyelvek, pénznemek", "w": ["A kínai jelírás", "A latin", "A görög"]},
  {"a": "Malajzia", "p": "Melyik ország hivatalos nyelve a maláj?", "s": "Népesség, nyelvek, pénznemek", "w": ["Fülöp-szigetek", "Thaiföld", "Vietnam"]},
  {"a": "A jen", "p": "Melyik pénznem Japán fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A dollár", "A jüan", "A won"]},
  {"a": "A jüan", "p": "Melyik pénznem Kína fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A dollár", "A jen", "A won"]},
  {"a": "A won", "p": "Melyik pénznem Dél-Korea fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A dollár", "A jüan", "A jen"]},
  {"a": "A font", "p": "Melyik pénznem Nagy-Britannia fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A korona", "A dollár", "Az euró"]},
  {"a": "A rubel", "p": "Melyik pénznem Oroszország fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A hrivnya", "A zloty", "A lej"]},
  {"a": "A rúpia", "p": "Melyik pénznem India fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A dollár", "A dinár", "A jen"]},
  {"a": "A zloty", "p": "Melyik pénznem Lengyelország fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A hrivnya", "A korona", "A lej"]},
  {"a": "A korona", "p": "Melyik pénznem Csehország fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A hrivnya", "A zloty", "A lej"]},
  {"a": "A lej", "p": "Melyik pénznem Románia fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A hrivnya", "A korona", "A zloty"]},
  {"a": "A hrivnya", "p": "Melyik pénznem Ukrajna fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A svájci frank", "A korona", "A zloty"]},
  {"a": "A líra", "p": "Melyik pénznem Törökország fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A svájci frank", "A dinár", "A rijál"]},
  {"a": "A sékel", "p": "Melyik pénznem Izrael fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A svájci frank", "A dinár", "A rijál"]},
  {"a": "A rand", "p": "Melyik pénznem Dél-Afrika fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A svájci frank", "A naira", "A dinár"]},
  {"a": "A real", "p": "Melyik pénznem Brazília fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A svájci frank", "A bolívar", "A peso"]},
  {"a": "A peso", "p": "Melyik pénznem Mexikó fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A svájci frank", "A bolívar", "A real"]},
  {"a": "A baht", "p": "Melyik pénznem Thaiföld fizetőeszköze?", "s": "Népesség, nyelvek, pénznemek", "w": ["A svájci frank", "A ringgit", "A rúpia"]},
  {"a": "Írország", "p": "Melyik országban fizetnek euróval?", "s": "Népesség, nyelvek, pénznemek", "w": ["Svédország", "Norvégia", "Dánia"]},
  {"a": "Svájc", "p": "Melyik nyugat-európai ország nem vezette be az eurót?", "s": "Népesség, nyelvek, pénznemek", "w": ["Németország", "Ausztria", "Belgium"]},
  {"a": "A buddhizmus", "p": "Melyik vallás a legelterjedtebb Thaiföldön?", "s": "Népesség, nyelvek, pénznemek", "w": ["A kereszténység", "A hinduizmus", "Az iszlám"]},
  {"a": "A hinduizmus", "p": "Melyik vallás a legelterjedtebb Indiában?", "s": "Népesség, nyelvek, pénznemek", "w": ["A kereszténység", "A buddhizmus", "Az iszlám"]},
  {"a": "Az iszlám", "p": "Melyik vallás a legelterjedtebb Indonéziában?", "s": "Népesség, nyelvek, pénznemek", "w": ["A kereszténység", "A buddhizmus", "A hinduizmus"]},
  {"a": "Mekka", "p": "Melyik város az iszlám legszentebb városa?", "s": "Népesség, nyelvek, pénznemek", "w": ["Jeruzsálem", "Medina", "Kairó"]},
  {"a": "Vatikán", "p": "Melyik ország lakossága a legkisebb Európában?", "s": "Népesség, nyelvek, pénznemek", "w": ["Liechtenstein", "San Marino", "Monaco"]},
  {"a": "Monaco", "p": "Melyik Európa legsűrűbben lakott apró állama?", "s": "Népesség, nyelvek, pénznemek", "w": ["Liechtenstein", "San Marino", "Málta"]}
]
$questions$::jsonb)
  with ordinality as question(item, ordinality);

do $validation$
begin
  if (
    select count(*) from public.quiz_questions
    where category_id = 'foldrajz_magyarul' and is_active
  ) <> 518 then
    raise exception 'Földrajz magyarul must contain exactly 518 active questions';
  end if;

  if exists (
    select 1
    from public.quiz_questions as question
    where question.category_id = 'foldrajz_magyarul'
      and (
        cardinality(question.wrong_answers) <> 3
        or (
          select count(distinct lower(trim(answer)))
          from unnest(question.wrong_answers) as answer
        ) <> 3
        or exists (
          select 1
          from unnest(question.wrong_answers) as answer
          where lower(trim(answer)) = lower(trim(question.correct_answer))
        )
      )
  ) then
    raise exception 'Földrajz magyarul: every question needs three distinct wrong answers';
  end if;

  if exists (
    select 1
    from public.quiz_questions as proposed
    join public.quiz_questions as existing
      on lower(trim(existing.prompt)) = lower(trim(proposed.prompt))
     and existing.id <> proposed.id
    where proposed.category_id = 'foldrajz_magyarul'
  ) then
    raise exception 'Földrajz magyarul: a prompt is already used by another question';
  end if;
end;
$validation$;
