-- Magyar zene 1970-1989: 268 questions in Hungarian.
--
-- Written so the correct answer is never the longest option -- the tell that
-- made the Psychology bank guessable without reading the prompt. All four
-- choices share one type and grammatical form.
insert into public.quiz_questions (
  id,
  category_id,
  prompt,
  correct_answer,
  wrong_answers,
  language_code,
  grade_level,
  subject,
  display_order,
  is_active
)
select
  'magyar_zene_' || lpad(question.ordinality::text, 4, '0'),
  'magyar_zene',
  question.item ->> 'p',
  question.item ->> 'a',
  array(select jsonb_array_elements_text(question.item -> 'w')),
  'hu',
  null,
  question.item ->> 's',
  question.ordinality::integer,
  true
from jsonb_array_elements($questions$
[
  {"a": "Omega", "p": "Melyik együttesből lépett ki Presser Gábor 1971-ben?", "s": "Beat- és rockegyüttesek", "w": ["Hobo Blues Band", "Metro", "Illés-együttes"]},
  {"a": "Locomotiv GT", "p": "Melyik zenekart alapította Presser, Laux, Frenreisz és Barta?", "s": "Beat- és rockegyüttesek", "w": ["Neoton Família", "Hobo Blues Band", "Edda Művek"]},
  {"a": "Gran Turismo", "p": "Mit rövidít a GT az LGT nevében?", "s": "Beat- és rockegyüttesek", "w": ["Golden Train", "Guitar Team", "General Transport"]},
  {"a": "1971", "p": "Melyik évben alakult meg a Locomotiv GT?", "s": "Beat- és rockegyüttesek", "w": ["1969", "1973", "1977"]},
  {"a": "Locomotiv GT", "p": "Melyik együttes nevét becézik „Loksi”-nak?", "s": "Beat- és rockegyüttesek", "w": ["Hobo Blues Band", "Neoton Família", "Edda Művek"]},
  {"a": "Kóbor János", "p": "Ki volt az Omega énekese?", "s": "Beat- és rockegyüttesek", "w": ["Mihály Tamás", "Debreczeni Ferenc", "Benkő László"]},
  {"a": "Mecky", "p": "Mi volt Kóbor János beceneve?", "s": "Beat- és rockegyüttesek", "w": ["Pici", "Blöró", "Elefánt"]},
  {"a": "Molnár György", "p": "Melyik Omega-tag kapta az „Elefánt” becenevet?", "s": "Beat- és rockegyüttesek", "w": ["Debreczeni Ferenc", "Mihály Tamás", "Benkő László"]},
  {"a": "1962", "p": "Melyik évben alakult meg az Omega?", "s": "Beat- és rockegyüttesek", "w": ["1957", "1967", "1971"]},
  {"a": "öt", "p": "Hány tagú volt az Omega felállása 1971 után?", "s": "Beat- és rockegyüttesek", "w": ["hat", "négy", "hét"]},
  {"a": "Laux József", "p": "Ki volt az LGT első dobosa?", "s": "Beat- és rockegyüttesek", "w": ["Solti János", "Brunner Győző", "Debreczeni Ferenc"]},
  {"a": "Solti János", "p": "Ki lett az LGT dobosa 1977-ben?", "s": "Beat- és rockegyüttesek", "w": ["Debreczeni Ferenc", "Papp Tamás", "Laux József"]},
  {"a": "Somló Tamás", "p": "Ki lépett az LGT-be Frenreisz Károly helyére?", "s": "Beat- és rockegyüttesek", "w": ["Barta Tamás", "Karácsony János", "Solti János"]},
  {"a": "Karácsony János", "p": "Ki lett az LGT gitárosa Barta Tamás után?", "s": "Beat- és rockegyüttesek", "w": ["Somló Tamás", "Frenreisz Károly", "Szűcs Antal Gábor"]},
  {"a": "Hungária", "p": "Melyik együttesben játszott Barta Tamás az LGT előtt?", "s": "Beat- és rockegyüttesek", "w": ["Hobo Blues Band", "Metro", "Omega"]},
  {"a": "Locomotiv GT", "p": "Melyik együttest hagyta el Barta Tamás Amerikában 1974-ben?", "s": "Beat- és rockegyüttesek", "w": ["Omega", "Hobo Blues Band", "Hungária"]},
  {"a": "Locomotiv GT", "p": "Melyik együttes tagja lett Somló Tamás az Omega után?", "s": "Beat- és rockegyüttesek", "w": ["Skorpió", "Piramis", "Hobo Blues Band"]},
  {"a": "Locomotiv GT", "p": "Melyik zenekar volt az első magyar supergroup?", "s": "Beat- és rockegyüttesek", "w": ["Hobo Blues Band", "Taurus", "Skorpió"]},
  {"a": "Miskolc", "p": "Melyik városból indult az Edda Művek?", "s": "Beat- és rockegyüttesek", "w": ["Debrecen", "Székesfehérvár", "Szeged"]},
  {"a": "Pataky Attila", "p": "Ki volt az Edda Művek énekese?", "s": "Beat- és rockegyüttesek", "w": ["Vikidál Gyula", "Révész Sándor", "Deák Bill Gyula"]},
  {"a": "Edda Művek", "p": "Melyik együttes elődje volt a Griff nevű zenekar?", "s": "Beat- és rockegyüttesek", "w": ["Hobo Blues Band", "Karthago", "Beatrice"]},
  {"a": "Nagy Feró", "p": "Ki volt a Beatrice frontembere?", "s": "Beat- és rockegyüttesek", "w": ["Hobo", "Schuster Lóránt", "Pataky Attila"]},
  {"a": "1981", "p": "Melyik évben oszlott fel a Beatrice a hatósági nyomás miatt?", "s": "Beat- és rockegyüttesek", "w": ["1978", "1984", "1987"]},
  {"a": "babos kendő", "p": "Milyen kendő lett a Beatrice jelképe?", "s": "Beat- és rockegyüttesek", "w": ["csíkos kendő", "kockás kendő", "fekete kendő"]},
  {"a": "Beatrice", "p": "Melyik együttes volt az első magyar női popegyüttes?", "s": "Beat- és rockegyüttesek", "w": ["Neoton Família", "Korál", "Hungária"]},
  {"a": "P. Mobil", "p": "Melyik együttest vezette Schuster Lóránt?", "s": "Beat- és rockegyüttesek", "w": ["Korál", "Hobo Blues Band", "Piramis"]},
  {"a": "Perpetuum Mobile", "p": "Mit rövidít a P. Mobil név?", "s": "Beat- és rockegyüttesek", "w": ["Pesti Mobil", "Populáris Mobil", "Progresszív Mobilizmus"]},
  {"a": "P. Mobil", "p": "Melyik együttes elődje volt a Gesarol nevű zenekar?", "s": "Beat- és rockegyüttesek", "w": ["Hobo Blues Band", "Karthago", "Piramis"]},
  {"a": "P. Mobil", "p": "Melyik együttesben énekelt Vikidál Gyula 1980 előtt?", "s": "Beat- és rockegyüttesek", "w": ["Dinamit", "Hobo Blues Band", "Karthago"]},
  {"a": "Dinamit", "p": "Melyik együttes alakult 1979-ben Vikidál Gyulával az élén?", "s": "Beat- és rockegyüttesek", "w": ["Karthago", "Bikini", "Hobo Blues Band"]},
  {"a": "Földes László", "p": "Ki alapította a Hobo Blues Bandet?", "s": "Beat- és rockegyüttesek", "w": ["Deák Bill Gyula", "Tátrai Tibor", "Póka Egon"]},
  {"a": "Földes László", "p": "Mi Hobo igazi neve?", "s": "Beat- és rockegyüttesek", "w": ["Póka Egon", "Schuster Lóránt", "Szigeti Ferenc"]},
  {"a": "1978", "p": "Melyik évben alakult meg a Hobo Blues Band?", "s": "Beat- és rockegyüttesek", "w": ["1973", "1981", "1985"]},
  {"a": "Hobo Blues Band", "p": "Melyik zenekarban énekelt Deák Bill Gyula?", "s": "Beat- és rockegyüttesek", "w": ["Edda Művek", "Locomotiv GT", "Nagy Feró és a Beatrice"]},
  {"a": "Som Lajos", "p": "Ki alapította a Piramist 1972-ben?", "s": "Beat- és rockegyüttesek", "w": ["Frenreisz Károly", "Szigeti Ferenc", "Nagy Feró"]},
  {"a": "Révész Sándor", "p": "Ki lett a Piramis énekese 1975-ben?", "s": "Beat- és rockegyüttesek", "w": ["Vikidál Gyula", "Deák Bill Gyula", "Pataky Attila"]},
  {"a": "Generál", "p": "Melyik együttesben énekelt Révész Sándor a Piramis előtt?", "s": "Beat- és rockegyüttesek", "w": ["Bergendy", "Neoton Família", "Hobo Blues Band"]},
  {"a": "Skorpió", "p": "Melyik együttest alapította Frenreisz Károly 1973-ban?", "s": "Beat- és rockegyüttesek", "w": ["Hobo Blues Band", "Piramis", "Karthago"]},
  {"a": "1973", "p": "Melyik évben alakult meg a Skorpió?", "s": "Beat- és rockegyüttesek", "w": ["1969", "1976", "1980"]},
  {"a": "Metro", "p": "Melyik együttesben játszott Frenreisz Károly az LGT előtt?", "s": "Beat- és rockegyüttesek", "w": ["Omega", "Hobo Blues Band", "Illés-együttes"]},
  {"a": "Szigeti Ferenc", "p": "Ki alapította a Karthagót 1979-ben?", "s": "Beat- és rockegyüttesek", "w": ["Som Lajos", "Nagy Feró", "Frenreisz Károly"]},
  {"a": "1979", "p": "Melyik évben alakult meg a Karthago?", "s": "Beat- és rockegyüttesek", "w": ["1975", "1982", "1985"]},
  {"a": "elefánt", "p": "Melyik állat látható a Karthago első lemezborítóján?", "s": "Beat- és rockegyüttesek", "w": ["oroszlán", "krokodil", "sas"]},
  {"a": "Karthago", "p": "Melyik együttesbe igazolt Gidófalvy Attila 1979-ben?", "s": "Beat- és rockegyüttesek", "w": ["Piramis", "Hobo Blues Band", "Bikini"]},
  {"a": "Balázs Fecó", "p": "Ki volt a Korál frontembere?", "s": "Beat- és rockegyüttesek", "w": ["Demjén Ferenc", "Pataky Attila", "Szigeti Ferenc"]},
  {"a": "Neoton", "p": "Melyik együttesben kezdte pályáját Balázs Fecó?", "s": "Beat- és rockegyüttesek", "w": ["Hobo Blues Band", "Skorpió", "Metro"]},
  {"a": "Demjén Ferenc", "p": "Ki alapította a V’Moto-Rockot 1977-ben?", "s": "Beat- és rockegyüttesek", "w": ["Balázs Fecó", "Frenreisz Károly", "Szigeti Ferenc"]},
  {"a": "1977", "p": "Melyik évben alakult meg a V’Moto-Rock?", "s": "Beat- és rockegyüttesek", "w": ["1972", "1980", "1983"]},
  {"a": "1988", "p": "Melyik évben oszlott fel a V’Moto-Rock?", "s": "Beat- és rockegyüttesek", "w": ["1982", "1985", "1991"]},
  {"a": "Bergendy", "p": "Melyik együttesből lépett ki Demjén Ferenc 1977-ben?", "s": "Beat- és rockegyüttesek", "w": ["Omega", "Skorpió", "Hobo Blues Band"]},
  {"a": "Neoton Família", "p": "Melyik együttes énekesnője volt Csepregi Éva?", "s": "Beat- és rockegyüttesek", "w": ["Hobo Blues Band", "Bikini", "Korál"]},
  {"a": "Neoton Família", "p": "Melyik együttes angol neve volt Newton Family?", "s": "Beat- és rockegyüttesek", "w": ["Omega", "Hobo Blues Band", "Hungária"]},
  {"a": "Nagy Feró", "p": "Ki volt a Bikini első énekese?", "s": "Beat- és rockegyüttesek", "w": ["D. Nagy Lajos", "Vikidál Gyula", "Schuster Lóránt"]},
  {"a": "D. Nagy Lajos", "p": "Ki lett a Bikini énekese Nagy Feró után?", "s": "Beat- és rockegyüttesek", "w": ["Deák Bill Gyula", "Révész Sándor", "Pataky Attila"]},
  {"a": "1982", "p": "Melyik évben alakult meg a Bikini?", "s": "Beat- és rockegyüttesek", "w": ["1978", "1985", "1988"]},
  {"a": "1985", "p": "Melyik évben lépett ki Nagy Feró a Bikiniből?", "s": "Beat- és rockegyüttesek", "w": ["1980", "1983", "1989"]},
  {"a": "Illés Lajos", "p": "Ki volt az Illés-együttes névadója?", "s": "Beat- és rockegyüttesek", "w": ["Bródy János", "Szörényi Levente", "Pásztory Zoltán"]},
  {"a": "zongora", "p": "Melyik hangszeren játszott Illés Lajos?", "s": "Beat- és rockegyüttesek", "w": ["dob", "szaxofon", "basszusgitár"]},
  {"a": "1973", "p": "Melyik évben oszlott fel az Illés-együttes?", "s": "Beat- és rockegyüttesek", "w": ["1969", "1971", "1975"]},
  {"a": "Fonográf", "p": "Melyik együttest alapították az Illés tagjai 1973 végén?", "s": "Beat- és rockegyüttesek", "w": ["Hobo Blues Band", "Korál", "Skorpió"]},
  {"a": "Metro", "p": "Melyik együttes elődje volt a Zenith nevű zenekar?", "s": "Beat- és rockegyüttesek", "w": ["Omega", "Hobo Blues Band", "Piramis"]},
  {"a": "Metro", "p": "Melyik együttesnek volt Sztevanovity Dusán a szövegírója?", "s": "Beat- és rockegyüttesek", "w": ["Omega", "Illés-együttes", "Hobo Blues Band"]},
  {"a": "1972", "p": "Melyik évben oszlott fel a Metro együttes?", "s": "Beat- és rockegyüttesek", "w": ["1968", "1975", "1979"]},
  {"a": "Fenyő Miklós", "p": "Ki volt a Hungária vezetője?", "s": "Beat- és rockegyüttesek", "w": ["Frenreisz Károly", "Novai Gábor", "Szikora Róbert"]},
  {"a": "Dolly", "p": "Ki volt a Hungária énekesnője 1980-tól?", "s": "Beat- és rockegyüttesek", "w": ["Csepregi Éva", "Zalatnay Sarolta", "Szűcs Judith"]},
  {"a": "R-GO", "p": "Melyik együttest alapította Szikora Róbert 1982 után?", "s": "Beat- és rockegyüttesek", "w": ["Bikini", "Dinamit", "Hobo Blues Band"]},
  {"a": "Omega", "p": "Melyik együttes játszott először szintetizátort magyar lemezen?", "s": "Beat- és rockegyüttesek", "w": ["Hobo Blues Band", "Illés-együttes", "Metro"]},
  {"a": "Omega", "p": "Melyik együttes kapott először Liszt Ferenc-díjat a könnyűzenében?", "s": "Beat- és rockegyüttesek", "w": ["Locomotiv GT", "Illés-együttes", "Neoton Família"]},
  {"a": "Omega", "p": "Melyik együttes kísérte Zalatnay Saroltát 1967-ben a győztes dalban?", "s": "Beat- és rockegyüttesek", "w": ["Metro", "Bergendy", "Illés-együttes"]},
  {"a": "Hobo Blues Band", "p": "Melyik együttes tagja volt Póka Egon és Tátrai Tibor is?", "s": "Beat- és rockegyüttesek", "w": ["Nagy Feró és a Beatrice", "Neoton Família", "Edda Művek"]},
  {"a": "Ki mit tud?", "p": "Melyik tehetségkutatón indult Koncz Zsuzsa 1962-ben?", "s": "Énekesek és énekesnők", "w": ["Táncdalfesztivál", "Tessék választani!", "Made in Hungary"]},
  {"a": "Zorán", "p": "Ki nyerte meg az első Ki mit tud?-ot 1962-ben?", "s": "Énekesek és énekesnők", "w": ["Koncz Zsuzsa", "Kovács Kati", "Zalatnay Sarolta"]},
  {"a": "Summertime", "p": "Melyik dal magyar változatával nyert Zorán 1962-ben?", "s": "Énekesek és énekesnők", "w": ["Blue Suede Shoes", "Long Tall Sally", "Yesterday"]},
  {"a": "Kovács Kati", "p": "Ki nyerte meg az 1965-ös Ki mit tud?-ot énekesként?", "s": "Énekesek és énekesnők", "w": ["Koncz Zsuzsa", "Zalatnay Sarolta", "Szűcs Judith"]},
  {"a": "Kovács Kati", "p": "Ki volt az első Táncdalfesztivál győztese?", "s": "Énekesek és énekesnők", "w": ["Koncz Zsuzsa", "Cserháti Zsuzsa", "Zalatnay Sarolta"]},
  {"a": "Kovács Kati", "p": "Ki nyerte meg háromszor is a Táncdalfesztivált?", "s": "Énekesek és énekesnők", "w": ["Zalatnay Sarolta", "Szécsi Pál", "Koncz Zsuzsa"]},
  {"a": "Nem leszek a játékszered", "p": "Melyik dallal nyerte Kovács Kati az első Táncdalfesztivált?", "s": "Énekesek és énekesnők", "w": ["Add már, Uram, az esőt!", "Szólj rám, ha hangosan énekelek", "Újra otthon"]},
  {"a": "Add már, Uram, az esőt!", "p": "Melyik dallal nyert Kovács Kati az 1972-es Táncdalfesztiválon?", "s": "Énekesek és énekesnők", "w": ["Nem leszek a játékszered", "Újra otthon", "Szólj rám, ha hangosan énekelek"]},
  {"a": "Újra otthon", "p": "Melyik dallal nyert Kovács Kati 1981-ben?", "s": "Énekesek és énekesnők", "w": ["Szólj rám, ha hangosan énekelek", "Nem leszek a játékszered", "Add már, Uram, az esőt!"]},
  {"a": "Juventus", "p": "Melyik együttes kísérte Kovács Katit az „Add már, Uram, az esőt!”-ben?", "s": "Énekesek és énekesnők", "w": ["Bergendy", "Locomotiv GT", "Skorpió"]},
  {"a": "Locomotiv GT", "p": "Melyik zenekarral készített Kovács Kati négy albumot?", "s": "Énekesek és énekesnők", "w": ["Omega", "Fonográf", "Hobo Blues Band"]},
  {"a": "V’Moto-Rock", "p": "Melyik együttes kísérte Kovács Kati „Érj utol” című albumát?", "s": "Énekesek és énekesnők", "w": ["Hobo Blues Band", "Fonográf", "Locomotiv GT"]},
  {"a": "Zorán", "p": "Kivel énekelte Kovács Kati a „Játssz még!” című duettet?", "s": "Énekesek és énekesnők", "w": ["Máté Péter", "Demjén Ferenc", "Balázs Fecó"]},
  {"a": "Kovács Kati", "p": "Ki vette fel először a „Szólj rám, ha hangosan énekelek” című dalt?", "s": "Énekesek és énekesnők", "w": ["Koncz Zsuzsa", "Zorán", "Cserháti Zsuzsa"]},
  {"a": "Jelbeszéd", "p": "Melyik Koncz Zsuzsa-albumot vonták ki a boltokból 1973-ban?", "s": "Énekesek és énekesnők", "w": ["Kertész leszek", "Gyerekjátékok", "Valahol"]},
  {"a": "Bródy János", "p": "Ki írta Koncz Zsuzsa dalainak nagy részét?", "s": "Énekesek és énekesnők", "w": ["Presser Gábor", "Szörényi Levente", "Demjén Ferenc"]},
  {"a": "Fonográf", "p": "Melyik zenekar kísérte Koncz Zsuzsát 1974 és 1981 között?", "s": "Énekesek és énekesnők", "w": ["Korál", "Skorpió", "Hobo Blues Band"]},
  {"a": "Cserháti Zsuzsa", "p": "Ki énekelte az „Édes kisfiam” című dalt?", "s": "Énekesek és énekesnők", "w": ["Zalatnay Sarolta", "Koncz Zsuzsa", "Kovács Kati"]},
  {"a": "When a Child Is Born", "p": "Melyik karácsonyi világsláger az „Édes kisfiam” eredetije?", "s": "Énekesek és énekesnők", "w": ["Last Christmas", "Do They Know It’s Christmas?", "Silent Night"]},
  {"a": "Sopot", "p": "Melyik fesztiválon nyert Cserháti Zsuzsa 1979-ben?", "s": "Énekesek és énekesnők", "w": ["Drezda", "Villach", "Castlebar"]},
  {"a": "Szécsi Pál", "p": "Ki énekelte az „Egy szál harangvirág” című dalt?", "s": "Énekesek és énekesnők", "w": ["Aradszky László", "Korda György", "Máté Péter"]},
  {"a": "Csak egy tánc volt", "p": "Melyik dallal lett ismert Szécsi Pál 1967-ben?", "s": "Énekesek és énekesnők", "w": ["Két összeillő ember", "Szeretni bolondulásig", "Egy szál harangvirág"]},
  {"a": "1974", "p": "Melyik évben hunyt el Szécsi Pál?", "s": "Énekesek és énekesnők", "w": ["1971", "1977", "1980"]},
  {"a": "Máté Péter", "p": "Ki énekelte a „Zene nélkül mit érek én?” című dalt?", "s": "Énekesek és énekesnők", "w": ["Szécsi Pál", "Zorán", "Demjén Ferenc"]},
  {"a": "Elmegyek", "p": "Melyik Máté Péter-dal lett Sylvie Vartan előadásában világsláger?", "s": "Énekesek és énekesnők", "w": ["Egy darabot a szívemből", "Szülői ház", "Együttlét"]},
  {"a": "1984", "p": "Melyik évben hunyt el Máté Péter?", "s": "Énekesek és énekesnők", "w": ["1979", "1988", "1991"]},
  {"a": "S. Nagy István", "p": "Ki volt Máté Péter leggyakoribb szerzőtársa?", "s": "Énekesek és énekesnők", "w": ["Bródy János", "Sztevanovity Dusán", "Szenes Iván"]},
  {"a": "Rózsi", "p": "Mi volt Demjén Ferenc beceneve?", "s": "Énekesek és énekesnők", "w": ["Mecky", "Pici", "Elefánt"]},
  {"a": "Bergendy", "p": "Melyik együttesben énekelt Demjén Ferenc 1970-től?", "s": "Énekesek és énekesnők", "w": ["Hobo Blues Band", "Metro", "Omega"]},
  {"a": "Jöjj vissza, vándor", "p": "Melyik dallal mutatkozott be Demjén a Bergendyben?", "s": "Énekesek és énekesnők", "w": ["Fújom a dalt", "Mikor elindul a vonat", "El kell, hogy engedj"]},
  {"a": "Zorán", "p": "Kinek a testvére volt Sztevanovity Dusán?", "s": "Énekesek és énekesnők", "w": ["Presser Gábor", "Kóbor János", "Szörényi Levente"]},
  {"a": "Apám hitte", "p": "Melyik Zorán-dalt dolgozta fel Sylvie Vartan franciául?", "s": "Énekesek és énekesnők", "w": ["Számíthatsz rám", "Szép holnap", "Az ünnep"]},
  {"a": "Bródy János", "p": "Ki írta Zorán „Ne várd a májust” című dalát?", "s": "Énekesek és énekesnők", "w": ["Presser Gábor", "Szörényi Levente", "Dusán"]},
  {"a": "Szűcs Judith", "p": "Melyik énekesnőt hívták „diszkókirálynőnek”?", "s": "Énekesek és énekesnők", "w": ["Csepregi Éva", "Katona Klári", "Zalatnay Sarolta"]},
  {"a": "Táncolj még!", "p": "Melyik dallal tört be Szűcs Judith 1977-ben?", "s": "Énekesek és énekesnők", "w": ["Egy szál harangvirág", "Kell, hogy várj", "Santa Maria"]},
  {"a": "Skorpió", "p": "Melyik zenekarban játszott Szűcs Judith bátyja, Szűcs Antal Gábor?", "s": "Énekesek és énekesnők", "w": ["Omega", "Hobo Blues Band", "Piramis"]},
  {"a": "Szűcs Judith", "p": "Melyik énekesnő lemezét készítette a Skorpió 1985-ben?", "s": "Énekesek és énekesnők", "w": ["Kovács Kati", "Katona Klári", "Zalatnay Sarolta"]},
  {"a": "Neoton", "p": "Melyik együttesben énekelt Katona Klári a pályája elején?", "s": "Énekesek és énekesnők", "w": ["Hobo Blues Band", "Bergendy", "Omega"]},
  {"a": "Demjén Ferenc", "p": "Ki írta Katona Klári dalait 1976 és 1980 között?", "s": "Énekesek és énekesnők", "w": ["Bródy János", "Szörényi Levente", "Presser Gábor"]},
  {"a": "Presser Gábor", "p": "Kivel dolgozott együtt Katona Klári 1981-től?", "s": "Énekesek és énekesnők", "w": ["Bródy János", "Demjén Ferenc", "Szörényi Levente"]},
  {"a": "Titkaim", "p": "Melyik Katona Klári-album hozta élete legnagyobb sikerét?", "s": "Énekesek és énekesnők", "w": ["Láthatod: boldog vagyok", "Savanyú a csokoládé", "Éjszakai üzenet"]},
  {"a": "Nem várok holnapig", "p": "Melyik dallal nyerte Zalatnay Sarolta az 1967-es Táncdalfesztivált?", "s": "Énekesek és énekesnők", "w": ["Hol jár az eszem", "Add már, Uram, az esőt!", "Fák, virágok, fény"]},
  {"a": "London", "p": "Melyik városban élt Zalatnay Sarolta 1967 és 1969 között?", "s": "Énekesek és énekesnők", "w": ["Párizs", "Hamburg", "Stockholm"]},
  {"a": "Csepregi Éva", "p": "Melyik énekesnő volt a Kócbabák tagja?", "s": "Énekesek és énekesnők", "w": ["Zalatnay Sarolta", "Szűcs Judith", "Katona Klári"]},
  {"a": "Omega", "p": "Melyik együttes énekelte a „Gyöngyhajú lány” című dalt?", "s": "Híres dalok és előadóik", "w": ["Illés-együttes", "Hobo Blues Band", "Locomotiv GT"]},
  {"a": "10 000 lépés", "p": "Melyik albumon jelent meg a „Gyöngyhajú lány”?", "s": "Híres dalok és előadóik", "w": ["Gammapolis", "Csillagok útján", "Éjszakai országút"]},
  {"a": "Scorpions", "p": "Melyik együttes dolgozta fel a „Gyöngyhajú lányt” White Dove címmel?", "s": "Híres dalok és előadóik", "w": ["Deep Purple", "Uriah Heep", "Nazareth"]},
  {"a": "Kanye West", "p": "Melyik amerikai rapper használta fel a „Gyöngyhajú lány” dallamát?", "s": "Híres dalok és előadóik", "w": ["Jay-Z", "Kendrick Lamar", "Eminem"]},
  {"a": "Omega", "p": "Melyik együttes énekelte a „Petróleumlámpa” című dalt?", "s": "Híres dalok és előadóik", "w": ["Metro", "Bergendy", "Neoton Família"]},
  {"a": "Omega", "p": "Melyik együttes dala a „Fekete pillangó”?", "s": "Híres dalok és előadóik", "w": ["Hobo Blues Band", "Karthago", "Piramis"]},
  {"a": "Omega", "p": "Melyik együttes dala a „Léna”?", "s": "Híres dalok és előadóik", "w": ["Bikini", "Hobo Blues Band", "Karthago"]},
  {"a": "Omega", "p": "Melyik együttes dala az „Ezüst eső”?", "s": "Híres dalok és előadóik", "w": ["Korál", "Piramis", "Neoton Família"]},
  {"a": "Omega", "p": "Melyik együttes dala a „Nyári éjek asszonya”?", "s": "Híres dalok és előadóik", "w": ["Locomotiv GT", "Hungária", "Bikini"]},
  {"a": "Omega", "p": "Melyik együttes válaszolt a „Hűtlen barátok” című dallal?", "s": "Híres dalok és előadóik", "w": ["Metro", "Illés-együttes", "Piramis"]},
  {"a": "Piramis", "p": "Melyik együttes énekelte a „Szállj fel magasra” című dalt?", "s": "Híres dalok és előadóik", "w": ["Karthago", "Edda Művek", "Hobo Blues Band"]},
  {"a": "Neoton", "p": "Melyik együttes első nagy sikere volt a „Kell, hogy várj”?", "s": "Híres dalok és előadóik", "w": ["Hobo Blues Band", "Hungária", "Bergendy"]},
  {"a": "Neoton Família", "p": "Melyik együttes legnagyobb slágere a „Santa Maria”?", "s": "Híres dalok és előadóik", "w": ["Korál", "Hobo Blues Band", "Bikini"]},
  {"a": "Neoton Família", "p": "Melyik együttes dala a „Don Quijote”?", "s": "Híres dalok és előadóik", "w": ["Edda Művek", "Locomotiv GT", "Hobo Blues Band"]},
  {"a": "Holnap hajnalig", "p": "Melyik Neoton-dallal nyertek 1983-ban a Yamaha fesztiválon?", "s": "Híres dalok és előadóik", "w": ["Hétvégi motorozás", "Don Quijote", "Santa Maria"]},
  {"a": "Karthago", "p": "Melyik együttes dala a „Requiem”?", "s": "Híres dalok és előadóik", "w": ["Piramis", "Hobo Blues Band", "Korál"]},
  {"a": "Locomotiv GT", "p": "Melyik együttes dala a „Ringasd el magad”?", "s": "Híres dalok és előadóik", "w": ["Omega", "Neoton Família", "Illés-együttes"]},
  {"a": "Locomotiv GT", "p": "Melyik együttes énekelte a „Miénk itt a tér” című dalt?", "s": "Híres dalok és előadóik", "w": ["Hobo Blues Band", "Piramis", "Omega"]},
  {"a": "Locomotiv GT", "p": "Melyik együttes dala a „Kék asszony”?", "s": "Híres dalok és előadóik", "w": ["Omega", "Hobo Blues Band", "Illés-együttes"]},
  {"a": "Locomotiv GT", "p": "Melyik együttes dala a „Neked írom a dalt”?", "s": "Híres dalok és előadóik", "w": ["Omega", "Illés-együttes", "Hobo Blues Band"]},
  {"a": "Locomotiv GT", "p": "Melyik együttes dala az „Ő még csak most tizennégy”?", "s": "Híres dalok és előadóik", "w": ["Hobo Blues Band", "Neoton Família", "Bergendy"]},
  {"a": "Locomotiv GT", "p": "Melyik együttes dala a „Mindenki másképp csinálja”?", "s": "Híres dalok és előadóik", "w": ["Omega", "Illés-együttes", "Neoton Família"]},
  {"a": "Locomotiv GT", "p": "Melyik együttes dala a „Nem adom fel”?", "s": "Híres dalok és előadóik", "w": ["Omega", "Bergendy", "Hobo Blues Band"]},
  {"a": "Locomotiv GT", "p": "Melyik együttes első kislemezén jelent meg a „Boldog vagyok”?", "s": "Híres dalok és előadóik", "w": ["Neoton Família", "Piramis", "Omega"]},
  {"a": "Illés-együttes", "p": "Melyik együttes dala az „Amikor én még kissrác voltam”?", "s": "Híres dalok és előadóik", "w": ["Omega", "Hobo Blues Band", "Metro"]},
  {"a": "Illés-együttes", "p": "Melyik együttes dala a „Miért hagytuk, hogy így legyen”?", "s": "Híres dalok és előadóik", "w": ["Omega", "Piramis", "Hobo Blues Band"]},
  {"a": "Illés-együttes", "p": "Melyik együttes dala a „Ne gondold”?", "s": "Híres dalok és előadóik", "w": ["Hobo Blues Band", "Karthago", "Omega"]},
  {"a": "Metro", "p": "Melyik együttes énekelte a „Citromízű banán” című dalt?", "s": "Híres dalok és előadóik", "w": ["Omega", "Illés-együttes", "Hungária"]},
  {"a": "Metro", "p": "Melyik együttes dala az „Ülök egy rózsaszínű kádban”?", "s": "Híres dalok és előadóik", "w": ["Omega", "Hungária", "Neoton Família"]},
  {"a": "Hungária", "p": "Melyik együttes dala a „Limbó hintó”?", "s": "Híres dalok és előadóik", "w": ["Neoton Família", "Skorpió", "Bikini"]},
  {"a": "Hungária", "p": "Melyik együttes dala a „Csavard fel a szőnyeget”?", "s": "Híres dalok és előadóik", "w": ["Bergendy", "Hobo Blues Band", "Skorpió"]},
  {"a": "Beatrice", "p": "Melyik együttes dala a „Jerikó”?", "s": "Híres dalok és előadóik", "w": ["Bikini", "Korál", "Hobo Blues Band"]},
  {"a": "Beatrice", "p": "Melyik együttes dala a „Nagyvárosi farkas”?", "s": "Híres dalok és előadóik", "w": ["Hobo Blues Band", "Edda Művek", "Piramis"]},
  {"a": "Edda Művek", "p": "Melyik együttes dala a „Kölyköd voltam”?", "s": "Híres dalok és előadóik", "w": ["Beatrice", "Hobo Blues Band", "Karthago"]},
  {"a": "Edda Művek", "p": "Melyik együttes dala az „Elhagyom a várost”?", "s": "Híres dalok és előadóik", "w": ["Bikini", "Piramis", "Hobo Blues Band"]},
  {"a": "Edda Művek", "p": "Melyik együttes dala az „Álmodtam egy világot”?", "s": "Híres dalok és előadóik", "w": ["Neoton Família", "Karthago", "Bikini"]},
  {"a": "Edda Művek", "p": "Melyik együttes dala a „Keselyű”?", "s": "Híres dalok és előadóik", "w": ["Beatrice", "Hobo Blues Band", "Skorpió"]},
  {"a": "Balázs Fecó", "p": "Ki énekelte a „Homok a szélben” című dalt?", "s": "Híres dalok és előadóik", "w": ["Révész Sándor", "Pataky Attila", "Demjén Ferenc"]},
  {"a": "Korál", "p": "Melyik együttes dala a „Maradj velem”?", "s": "Híres dalok és előadóik", "w": ["Hobo Blues Band", "Karthago", "Bikini"]},
  {"a": "V’Moto-Rock", "p": "Melyik együttes dala a „Jégszív”?", "s": "Híres dalok és előadóik", "w": ["Edda Művek", "Hobo Blues Band", "Karthago"]},
  {"a": "Dinamit", "p": "Melyik együttes dala a „Tinédzser dal”?", "s": "Híres dalok és előadóik", "w": ["Bikini", "Korál", "Neoton Família"]},
  {"a": "P. Mobil", "p": "Melyik együttes dala „A főnix éjszakája”?", "s": "Híres dalok és előadóik", "w": ["Hobo Blues Band", "Korál", "Bikini"]},
  {"a": "P. Mobil", "p": "Melyik együttes dala a „Csizma az asztalon”?", "s": "Híres dalok és előadóik", "w": ["Bikini", "Neoton Família", "Karthago"]},
  {"a": "Koncz Zsuzsa", "p": "Ki énekelte a „Ha én rózsa volnék” című dalt?", "s": "Híres dalok és előadóik", "w": ["Kovács Kati", "Katona Klári", "Zalatnay Sarolta"]},
  {"a": "Szűcs Judith", "p": "Ki énekelte a „Táncolj még!” című dalt?", "s": "Híres dalok és előadóik", "w": ["Zalatnay Sarolta", "Katona Klári", "Csepregi Éva"]},
  {"a": "V’Moto-Rock", "p": "Melyik együttes dala a „Gyertyák”?", "s": "Híres dalok és előadóik", "w": ["Edda Művek", "Hobo Blues Band", "Beatrice"]},
  {"a": "Presser Gábor", "p": "Ki írta a „Gyöngyhajú lány” zenéjét?", "s": "Dalszerzők és szövegírók", "w": ["Kóbor János", "Benkő László", "Szörényi Levente"]},
  {"a": "Adamis Anna", "p": "Ki írta a „Gyöngyhajú lány” szövegét?", "s": "Dalszerzők és szövegírók", "w": ["Szörényi Levente", "Dusán", "Sülyi Péter"]},
  {"a": "Adamis Anna", "p": "Kit neveztek „az LGT ötödik tagjának”?", "s": "Dalszerzők és szövegírók", "w": ["Dusán", "Szörényi Levente", "Bródy János"]},
  {"a": "Locomotiv GT", "p": "Melyik zenekar szövegeit írta Adamis Anna 1971 és 1976 között?", "s": "Dalszerzők és szövegírók", "w": ["Omega", "Illés-együttes", "Hobo Blues Band"]},
  {"a": "1977", "p": "Melyik évtől írta Sztevanovity Dusán az LGT szövegeit?", "s": "Dalszerzők és szövegírók", "w": ["1971", "1980", "1984"]},
  {"a": "Bródy János", "p": "Ki volt az Illés-együttes fő szövegírója?", "s": "Dalszerzők és szövegírók", "w": ["Szörényi Levente", "Adamis Anna", "Illés Lajos"]},
  {"a": "Szörényi–Bródy", "p": "Melyik szerzőpáros írta az Illés-együttes dalait?", "s": "Dalszerzők és szövegírók", "w": ["Presser–Adamis", "Szörényi–Adamis", "Lerch–Demjén"]},
  {"a": "Sülyi Péter", "p": "Ki volt az Omega szövegírója Adamis Anna után?", "s": "Dalszerzők és szövegírók", "w": ["Dusán", "Horváth Attila", "Szörényi Levente"]},
  {"a": "Horváth Attila", "p": "Ki írta a Korál dalszövegeit?", "s": "Dalszerzők és szövegírók", "w": ["Sztevanovity Dusán", "Bródy János", "Sülyi Péter"]},
  {"a": "Schuster Lóránt", "p": "Ki írta a P. Mobil dalszövegeit?", "s": "Dalszerzők és szövegírók", "w": ["Bródy János", "Sztevanovity Dusán", "Horváth Attila"]},
  {"a": "Presser Gábor", "p": "Ki kapott elsőként Erkel Ferenc-díjat a rockműfajból?", "s": "Dalszerzők és szövegírók", "w": ["Bródy János", "Kóbor János", "Szörényi Levente"]},
  {"a": "Szenes Iván", "p": "Ki írta az „Add már, Uram, az esőt!” szövegét?", "s": "Dalszerzők és szövegírók", "w": ["Sztevanovity Dusán", "S. Nagy István", "Bródy János"]},
  {"a": "Bródy János", "p": "Ki írta a „Ha én rózsa volnék” című dalt?", "s": "Dalszerzők és szövegírók", "w": ["Illés Lajos", "Szörényi Levente", "Presser Gábor"]},
  {"a": "Nagy Feró", "p": "Ki írta a Bikini nagy slágereinek szövegét a kilépése után is?", "s": "Dalszerzők és szövegírók", "w": ["D. Nagy Lajos", "Bródy János", "Sztevanovity Dusán"]},
  {"a": "Szigeti Ferenc", "p": "Ki írta a Karthago „Requiem” című dalát?", "s": "Dalszerzők és szövegírók", "w": ["Gidófalvy Attila", "Som Lajos", "Frenreisz Károly"]},
  {"a": "Zorán", "p": "Kinek az albumait írta Presser Gábor 1977-től?", "s": "Dalszerzők és szövegírók", "w": ["Koncz Zsuzsa", "Cserháti Zsuzsa", "Demjén Ferenc"]},
  {"a": "1983", "p": "Melyik évben mutatták be az István, a királyt?", "s": "Rockoperák és zenés színház", "w": ["1979", "1985", "1987"]},
  {"a": "a Királydombon", "p": "Hol volt az István, a király ősbemutatója?", "s": "Rockoperák és zenés színház", "w": ["a Népstadionban", "a Kisstadionban", "a Nemzeti Színházban"]},
  {"a": "Bródy János", "p": "Ki írta az István, a király szövegkönyvét?", "s": "Rockoperák és zenés színház", "w": ["Szörényi Levente", "Presser Gábor", "Adamis Anna"]},
  {"a": "Szörényi–Bródy", "p": "Melyik szerzőpáros műve az István, a király?", "s": "Rockoperák és zenés színház", "w": ["Presser–Adamis", "Várkonyi–Miklós", "Lerch–Demjén"]},
  {"a": "Ezredforduló", "p": "Melyik dráma alapján készült az István, a király?", "s": "Rockoperák és zenés színház", "w": ["Bánk bán", "Fehér Anna", "Csongor és Tünde"]},
  {"a": "Vikidál Gyula", "p": "Ki játszotta Koppányt az István, a király ősbemutatóján?", "s": "Rockoperák és zenés színház", "w": ["Deák Bill Gyula", "Nagy Feró", "Varga Miklós"]},
  {"a": "Varga Miklós", "p": "Ki játszotta Istvánt az István, a király ősbemutatóján?", "s": "Rockoperák és zenés színház", "w": ["Vikidál Gyula", "Deák Bill Gyula", "Nagy Feró"]},
  {"a": "Illés-együttes", "p": "Melyik együttes dala nyitja az István, a királyt?", "s": "Rockoperák és zenés színház", "w": ["Omega", "Locomotiv GT", "Hobo Blues Band"]},
  {"a": "120 ezer", "p": "Hány néző látta az István, a király ősbemutatóját?", "s": "Rockoperák és zenés színház", "w": ["félmillió", "50 ezer", "20 ezer"]},
  {"a": "Fonográf", "p": "Melyik zenekar játszotta fel az István, a király alapjait?", "s": "Rockoperák és zenés színház", "w": ["Omega", "Hobo Blues Band", "Skorpió"]},
  {"a": "Sztárcsinálók", "p": "Melyik volt az első magyar rockopera?", "s": "Rockoperák és zenés színház", "w": ["A padlás", "Kőműves Kelemen", "István, a király"]},
  {"a": "Várkonyi Mátyás", "p": "Ki írta a Sztárcsinálók zenéjét?", "s": "Rockoperák és zenés színház", "w": ["Szörényi Levente", "Presser Gábor", "Miklós Tibor"]},
  {"a": "1981", "p": "Melyik évben mutatták be a Sztárcsinálókat?", "s": "Rockoperák és zenés színház", "w": ["1977", "1983", "1986"]},
  {"a": "Nero", "p": "Melyik római császárról szól a Sztárcsinálók?", "s": "Rockoperák és zenés színház", "w": ["Caligula", "Marcus Aurelius", "Augustus"]},
  {"a": "Kőműves Kelemen", "p": "Melyik rockballadát mutatták be 1982-ben?", "s": "Rockoperák és zenés színház", "w": ["Fehér Anna", "István, a király", "Atilla – Isten kardja"]},
  {"a": "1988", "p": "Melyik évben mutatták be a Fehér Anna című rockballadát?", "s": "Rockoperák és zenés színház", "w": ["1982", "1985", "1990"]},
  {"a": "Presser Gábor", "p": "Ki írta A padlás című musical zenéjét?", "s": "Rockoperák és zenés színház", "w": ["Szörényi Levente", "Dés László", "Bródy János"]},
  {"a": "1988", "p": "Melyik évben mutatták be A padlást?", "s": "Rockoperák és zenés színház", "w": ["1982", "1985", "1991"]},
  {"a": "a Vígszínház", "p": "Melyik színház zenei vezetője lett Presser Gábor 1978-ban?", "s": "Rockoperák és zenés színház", "w": ["a Madách Színház", "az Operettszínház", "a Nemzeti Színház"]},
  {"a": "Presser Gábor", "p": "Ki írta a Képzelt riport egy amerikai popfesztiválról zenéjét?", "s": "Rockoperák és zenés színház", "w": ["Bródy János", "Dés László", "Szörényi Levente"]},
  {"a": "Déry Tibor", "p": "Kinek a kisregényéből készült a Képzelt riport?", "s": "Rockoperák és zenés színház", "w": ["Boldizsár Miklós", "Örkény István", "Csoóri Sándor"]},
  {"a": "1973", "p": "Melyik évben mutatták be a Képzelt riportot?", "s": "Rockoperák és zenés színház", "w": ["1969", "1977", "1981"]},
  {"a": "Olaszország", "p": "Melyik ország dalfesztiválja volt a Táncdalfesztivál mintája?", "s": "Fesztiválok és zenei élet", "w": ["Franciaország", "Nagy-Britannia", "Lengyelország"]},
  {"a": "1966", "p": "Melyik évben rendezték az első Táncdalfesztivált?", "s": "Fesztiválok és zenei élet", "w": ["1962", "1968", "1970"]},
  {"a": "Stúdió 11", "p": "Melyik rádiózenekar adta a táncdalfesztiválok nagyzenekarának magját?", "s": "Fesztiválok és zenei élet", "w": ["Bergendy", "Juventus", "Locomotiv GT"]},
  {"a": "1962", "p": "Melyik évben indult a Ki mit tud? című vetélkedő?", "s": "Fesztiválok és zenei élet", "w": ["1958", "1965", "1968"]},
  {"a": "Ki mit tud?", "p": "Melyik vetélkedőn tűnt fel a Hungária 1968-ban?", "s": "Fesztiválok és zenei élet", "w": ["Tessék választani!", "Made in Hungary", "Táncdalfesztivál"]},
  {"a": "Made in Hungary", "p": "Melyik rádiós dalversenyen nyert Máté Péter 1973-ban?", "s": "Fesztiválok és zenei élet", "w": ["Ki mit tud?", "Tessék választani!", "Táncdalfesztivál"]},
  {"a": "Erdős Péter", "p": "Ki volt a Magyar Hanglemezgyártó Vállalat mindenható vezetője?", "s": "Fesztiválok és zenei élet", "w": ["Bánki László", "Bolba Lajos", "Schuster Lóránt"]},
  {"a": "Karthago", "p": "Melyik együttes nyitotta meg a Petőfi Csarnokot 1985-ben?", "s": "Fesztiválok és zenei élet", "w": ["Hobo Blues Band", "Bikini", "Edda Művek"]},
  {"a": "a Nyugati pályaudvaron", "p": "Hol tartotta az LGT a búcsúkoncertjeit 1992-ben?", "s": "Fesztiválok és zenei élet", "w": ["a Népstadionban", "a Budapest Sportcsarnokban", "a Kisstadionban"]},
  {"a": "Yamaha-fesztivál", "p": "Melyik tokiói fesztiválon nyert az LGT különdíjat 1971-ben?", "s": "Fesztiválok és zenei élet", "w": ["Sopoti Fesztivál", "Sanremói Fesztivál", "Eurovíziós Dalfesztivál"]},
  {"a": "Neoton Família", "p": "Melyik zenekar turnézott 1981-ben 42 állomással Japánban?", "s": "Fesztiválok és zenei élet", "w": ["Hobo Blues Band", "Locomotiv GT", "Omega"]},
  {"a": "Locomotiv GT", "p": "Melyik zenekar turnézott 1980-ban az Omegával és a Beatricével?", "s": "Fesztiválok és zenei élet", "w": ["Piramis", "Hobo Blues Band", "Edda Művek"]},
  {"a": "az LGT és a Neoton", "p": "Melyik két együttes adta elő a „Magyar a világűrben” című dalt?", "s": "Fesztiválok és zenei élet", "w": ["az Omega és az Illés", "a Piramis és a Korál", "a Bikini és a Karthago"]},
  {"a": "Villach", "p": "Melyik fesztiválon nyert a Karthago nagydíjat 1983-ban?", "s": "Fesztiválok és zenei élet", "w": ["Castlebar", "Drezda", "Sopot"]},
  {"a": "Kopaszkutya", "p": "Melyik film zenéjét adta a Hobo Blues Band 1981-ben?", "s": "Fesztiválok és zenei élet", "w": ["Ballagás", "Szerelem első vérig", "A kenguru"]},
  {"a": "Ezek a fiatalok", "p": "Melyik filmben szerepeltek együtt az Illés, a Metro és az Omega?", "s": "Fesztiválok és zenei élet", "w": ["A kenguru", "Kopaszkutya", "Szép lányok, ne sírjatok!"]},
  {"a": "Miskolcon", "p": "Hol rendezték 1973-ban a „magyar Woodstockot”?", "s": "Fesztiválok és zenei élet", "w": ["Székesfehérváron", "Debrecenben", "Szegeden"]},
  {"a": "10 000 lépés", "p": "Melyik volt az Omega 1969-es nagylemeze?", "s": "Lemezek és albumok", "w": ["Gammapolis", "Csillagok útján", "Trombitás Frédi"]},
  {"a": "Locomotiv GT", "p": "Melyik együttes adta ki a „Loksi” című dupla albumot?", "s": "Lemezek és albumok", "w": ["Omega", "Piramis", "Hobo Blues Band"]},
  {"a": "1980", "p": "Melyik évben jelent meg az Edda Művek első nagylemeze?", "s": "Lemezek és albumok", "w": ["1977", "1983", "1985"]},
  {"a": "Mobilizmo", "p": "Melyik volt a P. Mobil első stúdióalbuma?", "s": "Lemezek és albumok", "w": ["Csizma az asztalon", "Honfoglalás", "Heavy Medal"]},
  {"a": "1980", "p": "Melyik évben jelent meg a Hobo Blues Band első albuma?", "s": "Lemezek és albumok", "w": ["1978", "1983", "1985"]},
  {"a": "Napraforgó", "p": "Melyik album volt a Neoton Família áttörése 1979-ben?", "s": "Lemezek és albumok", "w": ["Menedékház", "Bolond város", "Csak a zene"]},
  {"a": "Hungarian Blues", "p": "Melyik volt Bródy János első szólólemeze?", "s": "Lemezek és albumok", "w": ["Ne szólj szám", "Hang nélkül", "Az utca másik oldalán"]},
  {"a": "Ne szólj szám", "p": "Melyik Bródy-albumon jelent meg újra a „Ha én rózsa volnék”?", "s": "Lemezek és albumok", "w": ["Az utca másik oldalán", "Hang nélkül", "Hungarian Blues"]},
  {"a": "Electromantic", "p": "Melyik volt Presser Gábor első szólólemeze?", "s": "Lemezek és albumok", "w": ["Csak dalok", "Angyalok és emberek", "Kis történetek"]},
  {"a": "Erotika", "p": "Melyik Piramis-album jelent meg 1981-ben?", "s": "Lemezek és albumok", "w": ["Plusz", "Piramis 3.", "A nagy buli"]},
  {"a": "A rohanás", "p": "Melyik volt a Skorpió első albuma?", "s": "Lemezek és albumok", "w": ["Gyere velem!", "Kelj fel!", "Ünnepnap"]},
  {"a": "Hungária", "p": "Melyik együttes adta ki a „Hotel Menthol” című albumot?", "s": "Lemezek és albumok", "w": ["Bikini", "Neoton Família", "Skorpió"]},
  {"a": "Hungária", "p": "Melyik együttes lemeze döntötte meg 1980-ban az eladási rekordot?", "s": "Lemezek és albumok", "w": ["Edda Művek", "Piramis", "Neoton Família"]},
  {"a": "Korál", "p": "Melyik volt a Korál első nagylemeze?", "s": "Lemezek és albumok", "w": ["Homok a szélben", "A túlsó part", "Az óceán"]},
  {"a": "Mondd el", "p": "Melyik Bikini-album fogyott a legnagyobb példányszámban?", "s": "Lemezek és albumok", "w": ["Hova lett...", "Ha volna még időm…", "XX. századi híradó"]},
  {"a": "Utazás", "p": "Melyik volt Szörényi Levente első szólólemeze?", "s": "Lemezek és albumok", "w": ["Hazatérés", "Végtelen úton", "Hungarian Blues"]},
  {"a": "Edda Művek 2.", "p": "Melyik Edda-album dalai hallhatók a Ballagás című filmben?", "s": "Lemezek és albumok", "w": ["Edda Művek 1.", "Edda Művek 3.", "Viszlát Edda!"]},
  {"a": "Locomotiv GT", "p": "Melyik együttes adta ki a „Mindenki” című albumot?", "s": "Lemezek és albumok", "w": ["Neoton Família", "Bergendy", "Omega"]},
  {"a": "Kecskemét", "p": "Melyik városban született Kodály Zoltán?", "s": "Klasszikus magyar zene", "w": ["Doborján", "Nagyszentmiklós", "Debrecen"]},
  {"a": "Galánta", "p": "Melyik faluban járt elemi iskolába Kodály Zoltán?", "s": "Klasszikus magyar zene", "w": ["Kecskemét", "Nagyszombat", "Nagyszentmiklós"]},
  {"a": "1967", "p": "Melyik évben hunyt el Kodály Zoltán?", "s": "Klasszikus magyar zene", "w": ["1945", "1956", "1972"]},
  {"a": "Háry János", "p": "Melyik Kodály-mű daljáték?", "s": "Klasszikus magyar zene", "w": ["Psalmus Hungaricus", "Marosszéki táncok", "Budavári Te Deum"]},
  {"a": "Concerto", "p": "Melyik Kodály-művet a Chicagói Filharmonikusok jubileumára írták?", "s": "Klasszikus magyar zene", "w": ["Háry János", "Psalmus Hungaricus", "Galántai táncok"]},
  {"a": "Kodály Zoltán", "p": "Melyik zeneszerző nevéhez fűződik a magyar énektanítási módszer?", "s": "Klasszikus magyar zene", "w": ["Bartók Béla", "Erkel Ferenc", "Goldmark Károly"]},
  {"a": "New York", "p": "Melyik városban halt meg Bartók Béla?", "s": "Klasszikus magyar zene", "w": ["Buenos Aires", "Bécs", "London"]},
  {"a": "1945", "p": "Melyik évben halt meg Bartók Béla?", "s": "Klasszikus magyar zene", "w": ["1938", "1951", "1956"]},
  {"a": "zongora", "p": "Melyik hangszeren volt Bartók Béla művész?", "s": "Klasszikus magyar zene", "w": ["hegedű", "nagybőgő", "cselló"]},
  {"a": "Kodály Zoltán", "p": "Melyik zeneszerzővel gyűjtött Bartók Béla népdalokat?", "s": "Klasszikus magyar zene", "w": ["Liszt Ferenc", "Erkel Ferenc", "Goldmark Károly"]},
  {"a": "Balázs Béla", "p": "Kinek a misztériumjátékára írta Bartók A kékszakállú herceg várát?", "s": "Klasszikus magyar zene", "w": ["Kosztolányi Dezső", "Móricz Zsigmond", "Babits Mihály"]},
  {"a": "A kékszakállú herceg vára", "p": "Melyik Bartók-mű opera?", "s": "Klasszikus magyar zene", "w": ["A csodálatos mandarin", "Szonáta két zongorára és ütőhangszerekre", "A fából faragott királyfi"]},
  {"a": "Harvard", "p": "Melyik amerikai egyetemen tartott előadásokat Bartók 1940-ben?", "s": "Klasszikus magyar zene", "w": ["Yale", "Columbia", "Princeton"]},
  {"a": "Doborján", "p": "Melyik faluban született Liszt Ferenc?", "s": "Klasszikus magyar zene", "w": ["Nagyszentmiklós", "Kecskemét", "Sopron"]},
  {"a": "Bayreuth", "p": "Melyik német városban halt meg Liszt Ferenc?", "s": "Klasszikus magyar zene", "w": ["Weimar", "Düsseldorf", "Lipcse"]},
  {"a": "Czerny", "p": "Kitől tanult zongorázni Liszt Ferenc Bécsben?", "s": "Klasszikus magyar zene", "w": ["Chopin", "Berlioz", "Beethoven"]},
  {"a": "zongora", "p": "Melyik hangszeren volt Liszt Ferenc világhírű?", "s": "Klasszikus magyar zene", "w": ["csembaló", "orgona", "hegedű"]},
  {"a": "1875", "p": "Melyik évben nyílt meg a budapesti Zeneakadémia?", "s": "Klasszikus magyar zene", "w": ["1867", "1884", "1896"]},
  {"a": "Liszt Ferenc", "p": "Ki volt a budapesti Zeneakadémia első elnöke?", "s": "Klasszikus magyar zene", "w": ["Erkel Ferenc", "Dohnányi Ernő", "Bartók Béla"]},
  {"a": "Erkel Ferenc", "p": "Ki írta a Himnusz zenéjét?", "s": "Klasszikus magyar zene", "w": ["Liszt Ferenc", "Egressy Béni", "Kölcsey Ferenc"]},
  {"a": "Kölcsey Ferenc", "p": "Ki írta a Himnusz versét?", "s": "Klasszikus magyar zene", "w": ["Vörösmarty Mihály", "Petőfi Sándor", "Arany János"]},
  {"a": "Egressy Béni", "p": "Ki írta a Szózat zenéjét?", "s": "Klasszikus magyar zene", "w": ["Erkel Ferenc", "Vörösmarty Mihály", "Liszt Ferenc"]},
  {"a": "Vörösmarty Mihály", "p": "Melyik költő verse a Szózat?", "s": "Klasszikus magyar zene", "w": ["Kölcsey Ferenc", "Petőfi Sándor", "Csokonai Vitéz Mihály"]},
  {"a": "Bánk bán", "p": "Melyik Erkel-opera a legismertebb?", "s": "Klasszikus magyar zene", "w": ["Hunyadi László", "Bátori Mária", "Dózsa György"]},
  {"a": "1861", "p": "Melyik évben mutatták be Erkel Bánk bán című operáját?", "s": "Klasszikus magyar zene", "w": ["1844", "1875", "1884"]},
  {"a": "Bátori Mária", "p": "Melyik volt Erkel Ferenc első operája?", "s": "Klasszikus magyar zene", "w": ["Bánk bán", "Hunyadi László", "Dózsa György"]},
  {"a": "sakk", "p": "Milyen játék mestere volt Erkel Ferenc?", "s": "Klasszikus magyar zene", "w": ["kártya", "biliárd", "tekejáték"]},
  {"a": "1884", "p": "Melyik évben nyílt meg a budapesti Operaház?", "s": "Klasszikus magyar zene", "w": ["1861", "1875", "1896"]},
  {"a": "Omega", "p": "Melyik együttes dala az „Égi vándor”?", "s": "Híres dalok és előadóik", "w": ["Neoton Família", "Karthago", "Korál"]},
  {"a": "Amikor én még kissrác voltam", "p": "Melyik dallal nyert az Illés az 1968-as Táncdalfesztiválon?", "s": "Fesztiválok és zenei élet", "w": ["Nehéz az út", "Miért hagytuk, hogy így legyen", "Légy jó kicsit hozzám"]},
  {"a": "P. Mobil", "p": "Melyik együttes énekese volt Tunyogi Péter?", "s": "Beat- és rockegyüttesek", "w": ["Bikini", "Karthago", "Neoton Família"]},
  {"a": "Cini és a Tinik", "p": "Melyik formációt alapította Zalatnay Sarolta 1976-ban?", "s": "Énekesek és énekesnők", "w": ["Rózsaszín Bombázók", "Mikrolied", "Kócbabák"]},
  {"a": "Human Rights", "p": "Melyik Illés-nagylemez volt beat-oratórium?", "s": "Lemezek és albumok", "w": ["Add a kezed", "Illések és pofonok", "Ezek a fiatalok"]},
  {"a": "Mikrokozmosz", "p": "Melyik Bartók-mű zongoradarabok gyűjteménye?", "s": "Klasszikus magyar zene", "w": ["Concerto", "Cantata profana", "A csodálatos mandarin"]},
  {"a": "Koncz Zsuzsa", "p": "Melyik énekesnő ajánlotta Bródy Jánost az Illés-együttesbe?", "s": "Énekesek és énekesnők", "w": ["Zalatnay Sarolta", "Katona Klári", "Kovács Kati"]}
]
$questions$::jsonb)
  with ordinality as question(item, ordinality);

do $validation$
begin
  if (
    select count(*) from public.quiz_questions
    where category_id = 'magyar_zene' and is_active
  ) <> 268 then
    raise exception 'Magyar zene 1970-1989 must contain exactly 268 active questions';
  end if;

  if exists (
    select 1
    from public.quiz_questions as question
    where question.category_id = 'magyar_zene'
      and (
        cardinality(question.wrong_answers) <> 3
        or (
          select count(distinct lower(trim(answer)))
          from unnest(question.wrong_answers) as answer
        ) <> 3
        or exists (
          select 1
          from unnest(question.wrong_answers) as answer
          where lower(trim(answer)) = lower(trim(question.correct_answer))
        )
      )
  ) then
    raise exception 'Magyar zene 1970-1989: every question needs three distinct wrong answers';
  end if;

  if exists (
    select 1
    from public.quiz_questions as proposed
    join public.quiz_questions as existing
      on lower(trim(existing.prompt)) = lower(trim(proposed.prompt))
     and existing.id <> proposed.id
    where proposed.category_id = 'magyar_zene'
  ) then
    raise exception 'Magyar zene 1970-1989: a prompt is already used by another question';
  end if;
end;
$validation$;
