-- Magyarország földrajza: 355 questions in Hungarian.
--
-- Written so the correct answer is never the longest option -- the tell that
-- made the Psychology bank guessable without reading the prompt. All four
-- choices share one type and grammatical form.
insert into public.quiz_questions (
  id,
  category_id,
  prompt,
  correct_answer,
  wrong_answers,
  language_code,
  grade_level,
  subject,
  display_order,
  is_active
)
select
  'magyar_foldrajz_' || lpad(question.ordinality::text, 4, '0'),
  'magyar_foldrajz',
  question.item ->> 'p',
  question.item ->> 'a',
  array(select jsonb_array_elements_text(question.item -> 'w')),
  'hu',
  null,
  question.item ->> 's',
  question.ordinality::integer,
  true
from jsonb_array_elements($questions$
[
  {"a": "Kecskemét", "p": "Melyik város Bács-Kiskun megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Kiskunfélegyháza", "Kiskunhalas", "Baja"]},
  {"a": "Pécs", "p": "Melyik város Baranya megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Szigetvár", "Mohács", "Siklós"]},
  {"a": "Békéscsaba", "p": "Melyik város Békés megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Mezőkovácsháza", "Orosháza", "Gyula"]},
  {"a": "Miskolc", "p": "Melyik város Borsod-Abaúj-Zemplén megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Sátoraljaújhely", "Kazincbarcika", "Ózd"]},
  {"a": "Szeged", "p": "Melyik város Csongrád-Csanád megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Hódmezővásárhely", "Szentes", "Makó"]},
  {"a": "Eger", "p": "Melyik város Heves megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Gyöngyös", "Hatvan", "Füzesabony"]},
  {"a": "Debrecen", "p": "Melyik város Hajdú-Bihar megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Hajdúszoboszló", "Berettyóújfalu", "Hajdúböszörmény"]},
  {"a": "Győr", "p": "Melyik város Győr-Moson-Sopron megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Mosonmagyaróvár", "Sopron", "Csorna"]},
  {"a": "Szolnok", "p": "Melyik város Jász-Nagykun-Szolnok megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Jászberény", "Mezőtúr", "Karcag"]},
  {"a": "Tatabánya", "p": "Melyik város Komárom-Esztergom megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Nyergesújfalu", "Esztergom", "Komárom"]},
  {"a": "Salgótarján", "p": "Melyik város Nógrád megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Balassagyarmat", "Szécsény", "Pásztó"]},
  {"a": "Kaposvár", "p": "Melyik város Somogy megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Balatonboglár", "Marcali", "Siófok"]},
  {"a": "Nyíregyháza", "p": "Melyik város Szabolcs-Szatmár-Bereg megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Vásárosnamény", "Mátészalka", "Kisvárda"]},
  {"a": "Szekszárd", "p": "Melyik város Tolna megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Dunaföldvár", "Dombóvár", "Paks"]},
  {"a": "Szombathely", "p": "Melyik város Vas megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Szentgotthárd", "Celldömölk", "Sárvár"]},
  {"a": "Veszprém", "p": "Melyik város Veszprém megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Balatonfüred", "Zirc", "Pápa"]},
  {"a": "Zalaegerszeg", "p": "Melyik város Zala megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Zalaszentgrót", "Nagykanizsa", "Lenti"]},
  {"a": "Budapest", "p": "Melyik település Pest megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Szentendre", "Gödöllő", "Vác"]},
  {"a": "Fejér", "p": "Székesfehérvár melyik megye székhelye?", "s": "Megyék és megyeszékhelyek", "w": ["Komárom-Esztergom", "Veszprém", "Tolna"]},
  {"a": "Baranya", "p": "Melyik megye székhelye Pécs?", "s": "Megyék és megyeszékhelyek", "w": ["Bács-Kiskun", "Somogy", "Tolna"]},
  {"a": "Hajdú-Bihar", "p": "Melyik megye székhelye Debrecen?", "s": "Megyék és megyeszékhelyek", "w": ["Szabolcs-Szatmár-Bereg", "Jász-Nagykun-Szolnok", "Békés"]},
  {"a": "Borsod-Abaúj-Zemplén", "p": "Melyik megye székhelye Miskolc?", "s": "Megyék és megyeszékhelyek", "w": ["Szabolcs-Szatmár-Bereg", "Jász-Nagykun-Szolnok", "Heves"]},
  {"a": "Csongrád-Csanád", "p": "Melyik megye székhelye Szeged?", "s": "Megyék és megyeszékhelyek", "w": ["Jász-Nagykun-Szolnok", "Bács-Kiskun", "Békés"]},
  {"a": "Győr-Moson-Sopron", "p": "Melyik megye székhelye Győr?", "s": "Megyék és megyeszékhelyek", "w": ["Borsod-Abaúj-Zemplén", "Komárom-Esztergom", "Vas"]},
  {"a": "Bács-Kiskun", "p": "Melyik megye székhelye Kecskemét?", "s": "Megyék és megyeszékhelyek", "w": ["Jász-Nagykun-Szolnok", "Csongrád-Csanád", "Pest"]},
  {"a": "Jász-Nagykun-Szolnok", "p": "Melyik megye székhelye Szolnok?", "s": "Megyék és megyeszékhelyek", "w": ["Szabolcs-Szatmár-Bereg", "Bács-Kiskun", "Heves"]},
  {"a": "Győr-Moson-Sopron", "p": "Melyik megyében van Sopron?", "s": "Városok és megyéik", "w": ["Borsod-Abaúj-Zemplén", "Komárom-Esztergom", "Vas"]},
  {"a": "Somogy", "p": "Melyik megyében van Siófok?", "s": "Városok és megyéik", "w": ["Veszprém", "Fejér", "Zala"]},
  {"a": "Zala", "p": "Melyik megyében van Keszthely?", "s": "Városok és megyéik", "w": ["Somogy", "Veszprém", "Vas"]},
  {"a": "Zala", "p": "Melyik megyében van Hévíz?", "s": "Városok és megyéik", "w": ["Veszprém", "Somogy", "Fejér"]},
  {"a": "Veszprém", "p": "Melyik megyében van Tihany?", "s": "Városok és megyéik", "w": ["Komárom-Esztergom", "Somogy", "Fejér"]},
  {"a": "Heves", "p": "Melyik megyében van Eger?", "s": "Városok és megyéik", "w": ["Borsod-Abaúj-Zemplén", "Nógrád", "Pest"]},
  {"a": "Heves", "p": "Melyik megyében van Gyöngyös?", "s": "Városok és megyéik", "w": ["Jász-Nagykun-Szolnok", "Nógrád", "Pest"]},
  {"a": "Nógrád", "p": "Melyik megyében van Hollókő?", "s": "Városok és megyéik", "w": ["Borsod-Abaúj-Zemplén", "Heves", "Pest"]},
  {"a": "Borsod-Abaúj-Zemplén", "p": "Melyik megyében van Aggtelek?", "s": "Városok és megyéik", "w": ["Szabolcs-Szatmár-Bereg", "Nógrád", "Heves"]},
  {"a": "Borsod-Abaúj-Zemplén", "p": "Melyik megyében van Tokaj?", "s": "Városok és megyéik", "w": ["Szabolcs-Szatmár-Bereg", "Hajdú-Bihar", "Heves"]},
  {"a": "Borsod-Abaúj-Zemplén", "p": "Melyik megyében van Sárospatak?", "s": "Városok és megyéik", "w": ["Szabolcs-Szatmár-Bereg", "Hajdú-Bihar", "Nógrád"]},
  {"a": "Hajdú-Bihar", "p": "Melyik megyében van Hortobágy?", "s": "Városok és megyéik", "w": ["Szabolcs-Szatmár-Bereg", "Jász-Nagykun-Szolnok", "Békés"]},
  {"a": "Hajdú-Bihar", "p": "Melyik megyében van Hajdúszoboszló?", "s": "Városok és megyéik", "w": ["Jász-Nagykun-Szolnok", "Szabolcs-Szatmár-Bereg", "Békés"]},
  {"a": "Baranya", "p": "Melyik megyében van Villány?", "s": "Városok és megyéik", "w": ["Bács-Kiskun", "Somogy", "Tolna"]},
  {"a": "Baranya", "p": "Melyik megyében van Mohács?", "s": "Városok és megyéik", "w": ["Bács-Kiskun", "Somogy", "Tolna"]},
  {"a": "Baranya", "p": "Melyik megyében van Szigetvár?", "s": "Városok és megyéik", "w": ["Bács-Kiskun", "Somogy", "Tolna"]},
  {"a": "Komárom-Esztergom", "p": "Melyik megyében van Esztergom?", "s": "Városok és megyéik", "w": ["Borsod-Abaúj-Zemplén", "Fejér", "Pest"]},
  {"a": "Komárom-Esztergom", "p": "Melyik megyében van Tatabánya?", "s": "Városok és megyéik", "w": ["Borsod-Abaúj-Zemplén", "Fejér", "Vas"]},
  {"a": "Pest", "p": "Melyik megyében van Visegrád?", "s": "Városok és megyéik", "w": ["Komárom-Esztergom", "Nógrád", "Fejér"]},
  {"a": "Pest", "p": "Melyik megyében van Szentendre?", "s": "Városok és megyéik", "w": ["Komárom-Esztergom", "Nógrád", "Heves"]},
  {"a": "Pest", "p": "Melyik megyében van Gödöllő?", "s": "Városok és megyéik", "w": ["Jász-Nagykun-Szolnok", "Nógrád", "Heves"]},
  {"a": "Bács-Kiskun", "p": "Melyik megyében van Kalocsa?", "s": "Városok és megyéik", "w": ["Jász-Nagykun-Szolnok", "Csongrád-Csanád", "Tolna"]},
  {"a": "Bács-Kiskun", "p": "Melyik megyében van Baja?", "s": "Városok és megyéik", "w": ["Csongrád-Csanád", "Baranya", "Tolna"]},
  {"a": "Békés", "p": "Melyik megyében van Gyula?", "s": "Városok és megyéik", "w": ["Jász-Nagykun-Szolnok", "Csongrád-Csanád", "Hajdú-Bihar"]},
  {"a": "Békés", "p": "Melyik megyében van Szarvas?", "s": "Városok és megyéik", "w": ["Jász-Nagykun-Szolnok", "Csongrád-Csanád", "Hajdú-Bihar"]},
  {"a": "Csongrád-Csanád", "p": "Melyik megyében van Makó?", "s": "Városok és megyéik", "w": ["Jász-Nagykun-Szolnok", "Szabolcs-Szatmár-Bereg", "Békés"]},
  {"a": "Csongrád-Csanád", "p": "Melyik megyében van Ópusztaszer?", "s": "Városok és megyéik", "w": ["Jász-Nagykun-Szolnok", "Bács-Kiskun", "Békés"]},
  {"a": "Tolna", "p": "Melyik megyében van Paks?", "s": "Városok és megyéik", "w": ["Bács-Kiskun", "Baranya", "Fejér"]},
  {"a": "Vas", "p": "Melyik megyében van Sárvár?", "s": "Városok és megyéik", "w": ["Győr-Moson-Sopron", "Veszprém", "Zala"]},
  {"a": "Vas", "p": "Melyik megyében van Kőszeg?", "s": "Városok és megyéik", "w": ["Győr-Moson-Sopron", "Somogy", "Zala"]},
  {"a": "Zala", "p": "Melyik megyében van Nagykanizsa?", "s": "Városok és megyéik", "w": ["Veszprém", "Somogy", "Vas"]},
  {"a": "Somogy", "p": "Melyik megyében van Kaposvár?", "s": "Városok és megyéik", "w": ["Bács-Kiskun", "Baranya", "Tolna"]},
  {"a": "Fejér", "p": "Melyik megyében van Dunaújváros?", "s": "Városok és megyéik", "w": ["Bács-Kiskun", "Tolna", "Pest"]},
  {"a": "Nógrád", "p": "Melyik megyében van Salgótarján?", "s": "Városok és megyéik", "w": ["Borsod-Abaúj-Zemplén", "Heves", "Pest"]},
  {"a": "19", "p": "Hány megye van Magyarországon?", "s": "Megyék és megyeszékhelyek", "w": ["16", "20", "23"]},
  {"a": "Bács-Kiskun", "p": "Melyik megye a legnagyobb területű?", "s": "Megyék és megyeszékhelyek", "w": ["Jász-Nagykun-Szolnok", "Borsod-Abaúj-Zemplén", "Pest"]},
  {"a": "Komárom-Esztergom", "p": "Melyik megye a legkisebb területű?", "s": "Megyék és megyeszékhelyek", "w": ["Szabolcs-Szatmár-Bereg", "Nógrád", "Heves"]},
  {"a": "Pest", "p": "Melyik megyének a legnagyobb a lakossága?", "s": "Megyék és megyeszékhelyek", "w": ["Borsod-Abaúj-Zemplén", "Hajdú-Bihar", "Bács-Kiskun"]},
  {"a": "Zala", "p": "Melyik megye fekszik az ország délnyugati sarkában?", "s": "Megyék és megyeszékhelyek", "w": ["Baranya", "Somogy", "Vas"]},
  {"a": "Északkeleten", "p": "Szabolcs-Szatmár-Bereg az ország melyik részén fekszik?", "s": "Megyék és megyeszékhelyek", "w": ["Északnyugaton", "Délnyugaton", "Délkeleten"]},
  {"a": "Délnyugaton", "p": "Zala megye az ország melyik részén fekszik?", "s": "Megyék és megyeszékhelyek", "w": ["Északnyugaton", "Északkeleten", "Délkeleten"]},
  {"a": "Tolna", "p": "Melyik megye székhelye Szekszárd?", "s": "Megyék és megyeszékhelyek", "w": ["Bács-Kiskun", "Baranya", "Fejér"]},
  {"a": "Somogy", "p": "Melyik megye székhelye Kaposvár?", "s": "Megyék és megyeszékhelyek", "w": ["Bács-Kiskun", "Baranya", "Zala"]},
  {"a": "Heves", "p": "Melyik megye székhelye Eger?", "s": "Megyék és megyeszékhelyek", "w": ["Borsod-Abaúj-Zemplén", "Nógrád", "Pest"]},
  {"a": "Vas", "p": "Melyik megye székhelye Szombathely?", "s": "Megyék és megyeszékhelyek", "w": ["Győr-Moson-Sopron", "Veszprém", "Zala"]},
  {"a": "Nógrád", "p": "Melyik megye székhelye Salgótarján?", "s": "Megyék és megyeszékhelyek", "w": ["Borsod-Abaúj-Zemplén", "Heves", "Pest"]},
  {"a": "Békés", "p": "Melyik megye székhelye Békéscsaba?", "s": "Megyék és megyeszékhelyek", "w": ["Jász-Nagykun-Szolnok", "Csongrád-Csanád", "Hajdú-Bihar"]},
  {"a": "Zala", "p": "Melyik megye székhelye Zalaegerszeg?", "s": "Megyék és megyeszékhelyek", "w": ["Győr-Moson-Sopron", "Veszprém", "Vas"]},
  {"a": "Komárom-Esztergom", "p": "Melyik megye székhelye Tatabánya?", "s": "Megyék és megyeszékhelyek", "w": ["Borsod-Abaúj-Zemplén", "Fejér", "Pest"]},
  {"a": "Veszprém", "p": "Melyik megye székhelye Veszprém?", "s": "Megyék és megyeszékhelyek", "w": ["Komárom-Esztergom", "Somogy", "Fejér"]},
  {"a": "Tisza", "p": "Melyik folyó szakasza a leghosszabb Magyarországon?", "s": "Vízrajz", "w": ["Dráva", "Körös", "Duna"]},
  {"a": "417 kilométer", "p": "Hány kilométer a Duna magyarországi szakasza?", "s": "Vízrajz", "w": ["598 kilométer", "735 kilométer", "250 kilométer"]},
  {"a": "Tisza", "p": "Melyik folyóba ömlik a Maros?", "s": "Vízrajz", "w": ["Dráva", "Körös", "Duna"]},
  {"a": "Duna", "p": "Melyik folyóba ömlik a Sió?", "s": "Vízrajz", "w": ["Tisza", "Dráva", "Rába"]},
  {"a": "Tisza", "p": "Melyik folyóba ömlik a Sajó?", "s": "Vízrajz", "w": ["Bodrog", "Hernád", "Duna"]},
  {"a": "Hernád", "p": "Melyik folyó ömlik a Sajóba?", "s": "Vízrajz", "w": ["Berettyó", "Bodrog", "Zagyva"]},
  {"a": "Sió", "p": "Melyik folyó viszi el a Balaton vizét?", "s": "Vízrajz", "w": ["Kapos", "Zala", "Séd"]},
  {"a": "Zala", "p": "Melyik folyó a Balaton legnagyobb befolyója?", "s": "Vízrajz", "w": ["Kapos", "Sió", "Séd"]},
  {"a": "Zagyva", "p": "Melyik folyó ömlik a Tiszába Szolnoknál?", "s": "Vízrajz", "w": ["Berettyó", "Hernád", "Körös"]},
  {"a": "Tisza és Bodrog", "p": "Melyik két folyó találkozik Tokajnál?", "s": "Vízrajz", "w": ["Tisza és Hernád", "Tisza és Zagyva", "Tisza és Sajó"]},
  {"a": "Rajkánál", "p": "Hol lép be a Duna Magyarország területére?", "s": "Vízrajz", "w": ["Mosonmagyaróvárnál", "Esztergomnál", "Komáromnál"]},
  {"a": "Tiszabecsnél", "p": "Hol lép be a Tisza Magyarországra?", "s": "Vízrajz", "w": ["Vásárosnaménynél", "Tiszaújvárosnál", "Tokajnál"]},
  {"a": "Ukrajna", "p": "Melyik ország felől érkezik a Tisza Magyarországra?", "s": "Vízrajz", "w": ["Horvátország", "Szlovákia", "Románia"]},
  {"a": "Tisza", "p": "Melyik nagy folyónk hagyja el az országot Szegednél?", "s": "Vízrajz", "w": ["Dráva", "Körös", "Duna"]},
  {"a": "Szerbiában", "p": "Melyik országban ömlik a Tisza a Dunába?", "s": "Vízrajz", "w": ["Magyarországon", "Horvátországban", "Romániában"]},
  {"a": "Dráva", "p": "Melyik folyó alkotja a magyar–horvát határ nagy részét?", "s": "Vízrajz", "w": ["Száva", "Mura", "Duna"]},
  {"a": "Ipoly", "p": "Melyik folyó a magyar–szlovák határ Nógrád mellett?", "s": "Vízrajz", "w": ["Zagyva", "Hernád", "Sajó"]},
  {"a": "Duna", "p": "Melyik nagy folyó partján fekszik Mohács?", "s": "Vízrajz", "w": ["Dráva", "Tisza", "Sió"]},
  {"a": "Duna", "p": "Melyik nagy folyó partján fekszik Esztergom?", "s": "Vízrajz", "w": ["Ipoly", "Tisza", "Rába"]},
  {"a": "Duna", "p": "Melyik nagy folyó partján fekszik Vác?", "s": "Vízrajz", "w": ["Zagyva", "Tisza", "Ipoly"]},
  {"a": "Duna", "p": "Melyik nagy folyó partján fekszik Komárom?", "s": "Vízrajz", "w": ["Által-ér", "Rába", "Vág"]},
  {"a": "Duna", "p": "Melyik nagy folyó partján fekszik Baja?", "s": "Vízrajz", "w": ["Dráva", "Tisza", "Sió"]},
  {"a": "Duna", "p": "Melyik nagy folyó partján fekszik Dunaújváros?", "s": "Vízrajz", "w": ["Sárvíz", "Tisza", "Sió"]},
  {"a": "Tisza", "p": "Melyik nagy folyó partján fekszik Szolnok?", "s": "Vízrajz", "w": ["Zagyva", "Körös", "Duna"]},
  {"a": "Tisza", "p": "Melyik nagy folyó partján fekszik Szeged?", "s": "Vízrajz", "w": ["Maros", "Körös", "Duna"]},
  {"a": "Maros", "p": "Melyik folyó partján fekszik Makó?", "s": "Vízrajz", "w": ["Körös", "Tisza", "Duna"]},
  {"a": "Körös", "p": "Melyik folyó partján fekszik Gyula?", "s": "Vízrajz", "w": ["Berettyó", "Maros", "Tisza"]},
  {"a": "Rába", "p": "Melyik folyó partján fekszik Sárvár?", "s": "Vízrajz", "w": ["Marcal", "Répce", "Zala"]},
  {"a": "Zala", "p": "Melyik folyó partján fekszik Zalaegerszeg?", "s": "Vízrajz", "w": ["Marcal", "Kerka", "Mura"]},
  {"a": "Kapos", "p": "Melyik folyó partján fekszik Kaposvár?", "s": "Vízrajz", "w": ["Koppány", "Zala", "Sió"]},
  {"a": "Bodrog", "p": "Melyik folyó partján fekszik Sárospatak?", "s": "Vízrajz", "w": ["Hernád", "Zagyva", "Sajó"]},
  {"a": "Szinva", "p": "Melyik patak folyik át Miskolcon?", "s": "Vízrajz", "w": ["Hernád", "Bodrog", "Tarna"]},
  {"a": "Séd", "p": "Melyik patak partján fekszik Veszprém?", "s": "Vízrajz", "w": ["Marcal", "Kapos", "Zala"]},
  {"a": "Győrben", "p": "Melyik városban találkozik a Rába és a Mosoni-Duna?", "s": "Vízrajz", "w": ["Mosonmagyaróvárott", "Komáromban", "Sopronban"]},
  {"a": "Duna", "p": "Melyik folyón épült a paksi atomerőmű?", "s": "Vízrajz", "w": ["Dráva", "Tisza", "Sió"]},
  {"a": "Balaton", "p": "Melyik Magyarország legnagyobb tava?", "s": "Vízrajz", "w": ["Velencei-tó", "Fertő tó", "Tisza-tó"]},
  {"a": "Fertő tó", "p": "Melyik a Balaton után a legnagyobb természetes tavunk?", "s": "Vízrajz", "w": ["Velencei-tó", "Hévízi-tó", "Öreg-tó"]},
  {"a": "Ausztria", "p": "Melyik országgal osztozunk a Fertő tavon?", "s": "Vízrajz", "w": ["Horvátország", "Szlovákia", "Szlovénia"]},
  {"a": "Fejér", "p": "Melyik megyében fekszik a Velencei-tó?", "s": "Vízrajz", "w": ["Komárom-Esztergom", "Veszprém", "Pest"]},
  {"a": "Tisza-tó", "p": "Melyik Magyarország legnagyobb mesterséges tava?", "s": "Vízrajz", "w": ["Velencei-tó", "Deseda-tó", "Öreg-tó"]},
  {"a": "Kisköre", "p": "Melyik községnél épült a Tisza-tó gátja?", "s": "Vízrajz", "w": ["Abádszalók", "Tiszafüred", "Poroszló"]},
  {"a": "Tiszafüred", "p": "Melyik város fekszik a Tisza-tó partján?", "s": "Vízrajz", "w": ["Tiszaújváros", "Tiszavasvári", "Tiszakécske"]},
  {"a": "Hévízi-tó", "p": "Melyik Magyarország híres meleg vizű gyógytava?", "s": "Vízrajz", "w": ["Velencei-tó", "Vadkerti-tó", "Öreg-tó"]},
  {"a": "Öreg-tó", "p": "Melyik tóról híres Tata?", "s": "Vízrajz", "w": ["Velencei-tó", "Hévízi-tó", "Tisza-tó"]},
  {"a": "77 kilométer", "p": "Milyen hosszú körülbelül a Balaton?", "s": "Vízrajz", "w": ["120 kilométer", "150 kilométer", "45 kilométer"]},
  {"a": "Tihanynál", "p": "Hol a legmélyebb a Balaton?", "s": "Vízrajz", "w": ["Balatonfürednél", "Keszthelynél", "Siófoknál"]},
  {"a": "A déli", "p": "Melyik partja sekélyebb a Balatonnak?", "s": "Vízrajz", "w": ["Az északi", "A keleti", "A nyugati"]},
  {"a": "Somogy", "p": "Melyik megyében fekszik a Balaton déli partja?", "s": "Vízrajz", "w": ["Veszprém", "Fejér", "Zala"]},
  {"a": "Siófok", "p": "Melyik város a Balaton déli partjának fő üdülőhelye?", "s": "Vízrajz", "w": ["Balatonfüred", "Badacsony", "Keszthely"]},
  {"a": "Keszthely", "p": "Melyik város fekszik a Balaton nyugati végénél?", "s": "Vízrajz", "w": ["Balatonalmádi", "Balatonboglár", "Balatonlelle"]},
  {"a": "Balatonfüred", "p": "Melyik város fekszik a Balaton északi partján?", "s": "Vízrajz", "w": ["Balatonszemes", "Balatonboglár", "Balatonlelle"]},
  {"a": "Tihany", "p": "Melyik félsziget nyúlik be a Balatonba?", "s": "Vízrajz", "w": ["Szigliget", "Badacsony", "Fonyód"]},
  {"a": "Gárdony", "p": "Melyik város fekszik a Velencei-tó partján?", "s": "Vízrajz", "w": ["Balatonfüred", "Tiszafüred", "Siófok"]},
  {"a": "Dunakanyar", "p": "Mi a neve a Duna esztergomi és váci közti szakaszának?", "s": "Vízrajz", "w": ["Csepel-sziget", "Szigetköz", "Kisalföld"]},
  {"a": "Szigetköz", "p": "Mi a neve a Duna és a Mosoni-Duna közti tájnak?", "s": "Vízrajz", "w": ["Csallóköz", "Kisalföld", "Hanság"]},
  {"a": "Csepel-sziget", "p": "Melyik nagy sziget kezdődik Budapest déli részén?", "s": "Vízrajz", "w": ["Szentendrei-sziget", "Hajógyári-sziget", "Margitsziget"]},
  {"a": "Budapesten", "p": "Melyik városban van a Széchenyi gyógyfürdő?", "s": "Vízrajz", "w": ["Hajdúszoboszlón", "Debrecenben", "Hévízen"]},
  {"a": "Hajdúszoboszló", "p": "Melyik város híres gyógyfürdőjéről a Hajdúságban?", "s": "Vízrajz", "w": ["Hajdúböszörmény", "Hajdúnánás", "Hajdúdorog"]},
  {"a": "Zalakaros", "p": "Melyik Zala megyei város híres a termálfürdőjéről?", "s": "Vízrajz", "w": ["Zalaegerszeg", "Nagykanizsa", "Keszthely"]},
  {"a": "Harkány", "p": "Melyik baranyai település híres a gyógyfürdőjéről?", "s": "Vízrajz", "w": ["Szigetvár", "Mohács", "Siklós"]},
  {"a": "Bük", "p": "Melyik Vas megyei fürdőhely híres a termálvizéről?", "s": "Vízrajz", "w": ["Szentgotthárd", "Körmend", "Sárvár"]},
  {"a": "A 19. században", "p": "Melyik évszázadban szabályozták a Tisza folyását?", "s": "Vízrajz", "w": ["A 16. században", "A 18. században", "A 20. században"]},
  {"a": "Vásárhelyi Pál", "p": "Ki készítette a Tisza szabályozásának terveit?", "s": "Vízrajz", "w": ["Széchenyi István", "Kossuth Lajos", "Deák Ferenc"]},
  {"a": "A hóolvadás", "p": "Mi okozza a Tisza tavaszi árvizeit?", "s": "Vízrajz", "w": ["A nyári zápor", "A téli fagy", "Az őszi eső"]},
  {"a": "Rába", "p": "Melyik folyó folyik Szentgotthárdtól Győrig?", "s": "Vízrajz", "w": ["Marcal", "Répce", "Zala"]},
  {"a": "Duna", "p": "Melyik folyó szeli ketté Budapestet?", "s": "Vízrajz", "w": ["Zagyva", "Tisza", "Rába"]},
  {"a": "Kékes", "p": "Melyik Magyarország legmagasabb hegycsúcsa?", "s": "Hegyek és tájegységek", "w": ["Istállós-kő", "Kőris-hegy", "Zengő"]},
  {"a": "Mátra", "p": "Melyik hegységben található a Kékes?", "s": "Hegyek és tájegységek", "w": ["Bakony", "Mecsek", "Bükk"]},
  {"a": "1014 méter", "p": "Milyen magas a Kékes?", "s": "Hegyek és tájegységek", "w": ["1250 méter", "959 méter", "682 méter"]},
  {"a": "Egy", "p": "Hány csúcs magasabb ezer méternél Magyarországon?", "s": "Hegyek és tájegységek", "w": ["Három", "Kettő", "Öt"]},
  {"a": "Mátra", "p": "Melyik hegységben található a Galyatető?", "s": "Hegyek és tájegységek", "w": ["Bakony", "Mecsek", "Bükk"]},
  {"a": "Bükk", "p": "Melyik hegység legmagasabb pontja az Istállós-kő?", "s": "Hegyek és tájegységek", "w": ["Bakony", "Mecsek", "Mátra"]},
  {"a": "Mecsek", "p": "Melyik hegység legmagasabb pontja a Zengő?", "s": "Hegyek és tájegységek", "w": ["Bakony", "Vértes", "Bükk"]},
  {"a": "Bakony", "p": "Melyik hegység legmagasabb pontja a Kőris-hegy?", "s": "Hegyek és tájegységek", "w": ["Gerecse", "Vértes", "Mecsek"]},
  {"a": "Börzsöny", "p": "Melyik hegység legmagasabb pontja a Csóványos?", "s": "Hegyek és tájegységek", "w": ["Zempléni-hegység", "Cserhát", "Pilis"]},
  {"a": "Írottkő", "p": "Melyik a Dunántúl legmagasabb pontja?", "s": "Hegyek és tájegységek", "w": ["Kőris-hegy", "Csóványos", "Zengő"]},
  {"a": "Kőszegi-hegység", "p": "Melyik hegységben található az Írottkő?", "s": "Hegyek és tájegységek", "w": ["Soproni-hegység", "Bakony", "Mecsek"]},
  {"a": "Mecsek", "p": "Melyik hegység emelkedik Pécs fölött?", "s": "Hegyek és tájegységek", "w": ["Bakony", "Vértes", "Bükk"]},
  {"a": "Mátra", "p": "Melyik hegység terül el Eger és Gyöngyös között?", "s": "Hegyek és tájegységek", "w": ["Börzsöny", "Cserhát", "Bükk"]},
  {"a": "Bükk", "p": "Melyik hegység terül el Miskolc és Eger között?", "s": "Hegyek és tájegységek", "w": ["Zempléni-hegység", "Cserhát", "Mátra"]},
  {"a": "Cserhát", "p": "Melyik hegység terül el a Börzsöny és a Mátra között?", "s": "Hegyek és tájegységek", "w": ["Zempléni-hegység", "Gerecse", "Bükk"]},
  {"a": "Börzsöny", "p": "Melyik hegység emelkedik a Dunakanyar bal partján?", "s": "Hegyek és tájegységek", "w": ["Visegrádi-hegység", "Cserhát", "Pilis"]},
  {"a": "Pilis", "p": "Melyik hegység húzódik Esztergom és Budapest között?", "s": "Hegyek és tájegységek", "w": ["Gerecse", "Vértes", "Bükk"]},
  {"a": "Északi-középhegység", "p": "Melyik hegységcsoportba tartozik a Mátra?", "s": "Hegyek és tájegységek", "w": ["Dunántúli-középhegység", "Alpokalja", "Mecsek"]},
  {"a": "Északi-középhegység", "p": "Melyik hegységcsoportba tartozik a Bükk?", "s": "Hegyek és tájegységek", "w": ["Dunántúli-középhegység", "Dunántúli-dombság", "Alpokalja"]},
  {"a": "Börzsöny", "p": "Mi az Északi-középhegység legnyugatibb tagja?", "s": "Hegyek és tájegységek", "w": ["Zempléni-hegység", "Cserhát", "Bükk"]},
  {"a": "Bakony", "p": "Melyik hegység lábánál fekszik Veszprém?", "s": "Hegyek és tájegységek", "w": ["Gerecse", "Vértes", "Pilis"]},
  {"a": "Bakony", "p": "Melyik hegység lábánál fekszik Zirc?", "s": "Hegyek és tájegységek", "w": ["Gerecse", "Vértes", "Pilis"]},
  {"a": "Bükk", "p": "Melyik hegység lábánál fekszik Eger?", "s": "Hegyek és tájegységek", "w": ["Zempléni-hegység", "Cserhát", "Mátra"]},
  {"a": "Mátra", "p": "Melyik hegység lábánál fekszik Gyöngyös?", "s": "Hegyek és tájegységek", "w": ["Börzsöny", "Cserhát", "Bükk"]},
  {"a": "Bükk", "p": "Melyik hegység lábánál fekszik Miskolc?", "s": "Hegyek és tájegységek", "w": ["Cserehát", "Zemplén", "Mátra"]},
  {"a": "Alföld", "p": "Melyik síkság Magyarország legnagyobb tájegysége?", "s": "Hegyek és tájegységek", "w": ["Kisalföld", "Mezőföld", "Dunántúl"]},
  {"a": "Dunántúl", "p": "Melyik nagy táj fekszik a Dunától nyugatra?", "s": "Hegyek és tájegységek", "w": ["Kisalföld", "Tiszántúl", "Alföld"]},
  {"a": "Tiszántúl", "p": "Melyik nagy táj fekszik a Tiszától keletre?", "s": "Hegyek és tájegységek", "w": ["Duna–Tisza köze", "Kisalföld", "Dunántúl"]},
  {"a": "Duna–Tisza köze", "p": "Hogyan hívják a Duna és a Tisza közti tájat?", "s": "Hegyek és tájegységek", "w": ["Dunántúli-dombság", "Kisalföld", "Tiszántúl"]},
  {"a": "Kisalföld", "p": "Melyik síkság terül el Győr környékén?", "s": "Hegyek és tájegységek", "w": ["Nagykunság", "Hortobágy", "Alföld"]},
  {"a": "Mezőföld", "p": "Melyik síkság terül el Székesfehérvár és a Duna között?", "s": "Hegyek és tájegységek", "w": ["Nagykunság", "Kisalföld", "Sárrét"]},
  {"a": "Hortobágy", "p": "Melyik puszta terül el Debrecentől nyugatra?", "s": "Hegyek és tájegységek", "w": ["Nagykunság", "Kiskunság", "Nyírség"]},
  {"a": "Kiskunság", "p": "Melyik homokos táj terül el a Duna–Tisza közén?", "s": "Hegyek és tájegységek", "w": ["Nagykunság", "Hortobágy", "Hajdúság"]},
  {"a": "Nyírség", "p": "Melyik táj terül el Nyíregyháza környékén?", "s": "Hegyek és tájegységek", "w": ["Nagykunság", "Hortobágy", "Hajdúság"]},
  {"a": "Hajdúság", "p": "Melyik táj terül el Hajdúböszörmény környékén?", "s": "Hegyek és tájegységek", "w": ["Nagykunság", "Hortobágy", "Nyírség"]},
  {"a": "Karcag", "p": "Melyik város a Nagykunság központja?", "s": "Hegyek és tájegységek", "w": ["Kisújszállás", "Túrkeve", "Mezőtúr"]},
  {"a": "Göcsej", "p": "Melyik dombvidék terül el Zala megye nyugati felén?", "s": "Hegyek és tájegységek", "w": ["Somogyi-dombság", "Zselic", "Őrség"]},
  {"a": "Őrség", "p": "Melyik táj fekszik Vas és Zala megye nyugati szélén?", "s": "Hegyek és tájegységek", "w": ["Szigetköz", "Göcsej", "Hanság"]},
  {"a": "Zselic", "p": "Melyik dombvidék terül el Kaposvár és Pécs között?", "s": "Hegyek és tájegységek", "w": ["Mezőföld", "Göcsej", "Őrség"]},
  {"a": "Hanság", "p": "Melyik lápvidék fekszik a Fertő tó mellett?", "s": "Hegyek és tájegységek", "w": ["Ecsedi-láp", "Szigetköz", "Kisalföld"]},
  {"a": "Békés megyét", "p": "Melyik vidéket nevezik Viharsaroknak?", "s": "Hegyek és tájegységek", "w": ["Szabolcs megyét", "Somogy megyét", "Nógrád megyét"]},
  {"a": "Bazaltból", "p": "Milyen kőzetből állnak a Balaton-felvidék tanúhegyei?", "s": "Hegyek és tájegységek", "w": ["Homokkőből", "Mészkőből", "Gránitból"]},
  {"a": "Ság-hegy", "p": "Melyik tanúhegy áll Celldömölk mellett?", "s": "Hegyek és tájegységek", "w": ["Szent György-hegy", "Badacsony", "Csobánc"]},
  {"a": "Somló", "p": "Melyik tanúhegy áll Devecser közelében?", "s": "Hegyek és tájegységek", "w": ["Szent György-hegy", "Badacsony", "Csobánc"]},
  {"a": "Bükk-fennsík", "p": "Melyik fennsík terül el a Bükk hegységben?", "s": "Hegyek és tájegységek", "w": ["Aggteleki-karszt", "Tapolcai-medence", "Balaton-felvidék"]},
  {"a": "Baradla", "p": "Melyik barlang található Aggteleken?", "s": "Hegyek és tájegységek", "w": ["Szemlő-hegyi", "Pál-völgyi", "Anna-barlang"]},
  {"a": "Bükk", "p": "Melyik hegységben van a Szalajka-völgy?", "s": "Hegyek és tájegységek", "w": ["Zempléni-hegység", "Cserhát", "Mátra"]},
  {"a": "Szilvásváradon", "p": "Melyik faluban nyílik a Szalajka-völgy?", "s": "Hegyek és tájegységek", "w": ["Bükkszentkereszten", "Bélapátfalván", "Mónosbélen"]},
  {"a": "Homokbuckák", "p": "Milyen felszínforma jellemzi a Kiskunságot?", "s": "Hegyek és tájegységek", "w": ["Mészkőszirtek", "Bazaltkúpok", "Löszfalak"]},
  {"a": "Szeged mellett", "p": "Melyik vidéken van Magyarország legalacsonyabb pontja?", "s": "Hegyek és tájegységek", "w": ["Hortobágy szélén", "Nyírség szélén", "Győr mellett"]},
  {"a": "Soproni-hegység", "p": "Melyik hegység terül el Sopron fölött?", "s": "Hegyek és tájegységek", "w": ["Kőszegi-hegység", "Bakony", "Vértes"]},
  {"a": "Vértes", "p": "Melyik hegység húzódik Tatabánya és Székesfehérvár közt?", "s": "Hegyek és tájegységek", "w": ["Gerecse", "Bakony", "Pilis"]},
  {"a": "Balaton-felvidék", "p": "Melyik táj a Balaton és a Bakony között fekszik?", "s": "Hegyek és tájegységek", "w": ["Tapolcai-medence", "Dunántúli-dombság", "Mezőföld"]},
  {"a": "Budapest", "p": "Melyik Magyarország legnépesebb városa?", "s": "Városok", "w": ["Debrecen", "Miskolc", "Szeged"]},
  {"a": "Debrecen", "p": "Melyik Magyarország második legnépesebb városa?", "s": "Városok", "w": ["Székesfehérvár", "Miskolc", "Szeged"]},
  {"a": "Szeged", "p": "Melyik Magyarország harmadik legnépesebb városa?", "s": "Városok", "w": ["Nyíregyháza", "Miskolc", "Pécs"]},
  {"a": "Szeged", "p": "Melyik várost hívják a napfény városának?", "s": "Városok", "w": ["Kecskemét", "Debrecen", "Pécs"]},
  {"a": "Szegeden", "p": "Melyik városban áll a Fogadalmi templom a Dóm téren?", "s": "Városok", "w": ["Debrecenben", "Esztergomban", "Pécsett"]},
  {"a": "Debrecenben", "p": "Melyik városban áll a református Nagytemplom?", "s": "Városok", "w": ["Nyíregyházán", "Miskolcon", "Szegeden"]},
  {"a": "Esztergomban", "p": "Melyik városban áll Magyarország legnagyobb bazilikája?", "s": "Városok", "w": ["Székesfehérváron", "Egerben", "Pécsett"]},
  {"a": "Pécsett", "p": "Melyik városban működött a Zsolnay porcelángyár?", "s": "Városok", "w": ["Kecskeméten", "Hollóházán", "Herenden"]},
  {"a": "Herenden", "p": "Melyik bakonyi faluban készül a híres porcelán?", "s": "Városok", "w": ["Városlődön", "Hollóházán", "Zircen"]},
  {"a": "Pécsett", "p": "Melyik városban alapították az első magyar egyetemet?", "s": "Városok", "w": ["Debrecenben", "Budapesten", "Szegeden"]},
  {"a": "Visegrádon", "p": "Melyik dunakanyari városban áll a fellegvár?", "s": "Városok", "w": ["Esztergomban", "Szentendrén", "Vácott"]},
  {"a": "Szentendre", "p": "Melyik dunakanyari város híres a múzeumairól?", "s": "Városok", "w": ["Dunabogdány", "Esztergom", "Visegrád"]},
  {"a": "Szentendrén", "p": "Melyik városban van a szabadtéri néprajzi múzeum?", "s": "Városok", "w": ["Hódmezővásárhelyen", "Szombathelyen", "Nyíregyházán"]},
  {"a": "Hollókő", "p": "Melyik nógrádi falu került a világörökség listájára?", "s": "Városok", "w": ["Balassagyarmat", "Szécsény", "Rimóc"]},
  {"a": "Szombathely", "p": "Melyik város Vas megye püspöki székhelye?", "s": "Városok", "w": ["Szentgotthárd", "Körmend", "Sárvár"]},
  {"a": "Sopron", "p": "Melyik várost nevezik a leghűségesebb városnak?", "s": "Városok", "w": ["Mosonmagyaróvár", "Szombathely", "Kőszeg"]},
  {"a": "Sopron", "p": "Melyik város fekszik a Fertő tó közelében?", "s": "Városok", "w": ["Mosonmagyaróvár", "Csorna", "Kőszeg"]},
  {"a": "Eger", "p": "Melyik város híres a minaretjéről Észak-Magyarországon?", "s": "Városok", "w": ["Salgótarján", "Gyöngyös", "Miskolc"]},
  {"a": "Lillafüred", "p": "Melyik miskolci üdülőhely híres a vízeséséről?", "s": "Városok", "w": ["Bükkszentkereszt", "Diósgyőr", "Tapolca"]},
  {"a": "Dunaújváros", "p": "Melyik város épült iparvárosként a Duna partján?", "s": "Városok", "w": ["Százhalombatta", "Dunaharaszti", "Dunakeszi"]},
  {"a": "Pakson", "p": "Melyik városban működik Magyarország atomerőműve?", "s": "Városok", "w": ["Dunaújvárosban", "Kalocsán", "Mohácson"]},
  {"a": "Kalocsa", "p": "Melyik alföldi város érseki székhely?", "s": "Városok", "w": ["Kecskemét", "Szolnok", "Baja"]},
  {"a": "Kecskeméten", "p": "Melyik városban áll a Cifrapalota?", "s": "Városok", "w": ["Nyíregyházán", "Debrecenben", "Szegeden"]},
  {"a": "Nyíregyháza", "p": "Melyik város a Nyírség központja?", "s": "Városok", "w": ["Vásárosnamény", "Mátészalka", "Kisvárda"]},
  {"a": "Záhony", "p": "Melyik város fekszik az ukrán határ mellett?", "s": "Városok", "w": ["Vásárosnamény", "Mátészalka", "Kisvárda"]},
  {"a": "Pécs", "p": "Melyik város a Mecsek lábánál fekszik?", "s": "Városok", "w": ["Szigetvár", "Mohács", "Siklós"]},
  {"a": "Fertődön", "p": "Melyik községben áll az Esterházy-kastély?", "s": "Városok", "w": ["Fertőrákoson", "Keszthelyen", "Nagycenken"]},
  {"a": "Keszthelyen", "p": "Melyik városban áll a Festetics-kastély?", "s": "Városok", "w": ["Balatonfüreden", "Fertődön", "Siófokon"]},
  {"a": "Gödöllőn", "p": "Melyik Pest megyei városban áll a Grassalkovich-kastély?", "s": "Városok", "w": ["Nagykőrösön", "Szentendrén", "Cegléden"]},
  {"a": "Zirc", "p": "Melyik bakonyi város híres a ciszterci apátságáról?", "s": "Városok", "w": ["Balatonfüred", "Veszprém", "Pápa"]},
  {"a": "Sárospatak", "p": "Melyik zempléni város híres a református kollégiumáról?", "s": "Városok", "w": ["Sátoraljaújhely", "Szerencs", "Tokaj"]},
  {"a": "Tihany", "p": "Melyik település fölött áll az apátság a Balatonnál?", "s": "Városok", "w": ["Balatonfüred", "Szigliget", "Zamárdi"]},
  {"a": "Balatonfüred", "p": "Melyik város híres a balatoni szívkórházáról?", "s": "Városok", "w": ["Balatonalmádi", "Balatonlelle", "Balatonboglár"]},
  {"a": "Győr", "p": "Melyik város közelében áll a pannonhalmi főapátság?", "s": "Városok", "w": ["Esztergom", "Veszprém", "Sopron"]},
  {"a": "Szegeden", "p": "Melyik városban rendezik a szabadtéri játékokat a Dóm téren?", "s": "Városok", "w": ["Székesfehérváron", "Egerben", "Gyulán"]},
  {"a": "Debrecen", "p": "Melyik nagyvárosunk mellett nem folyik nagy folyó?", "s": "Városok", "w": ["Dunaújváros", "Szolnok", "Szeged"]},
  {"a": "Makó", "p": "Melyik város híres a hagymatermesztéséről?", "s": "Városok", "w": ["Hódmezővásárhely", "Csongrád", "Szentes"]},
  {"a": "Szentes", "p": "Melyik alföldi város híres a hajtatott zöldségeiről?", "s": "Városok", "w": ["Hódmezővásárhely", "Csongrád", "Szolnok"]},
  {"a": "Kecskemét", "p": "Melyik alföldi város híres a kajszibarackjáról?", "s": "Városok", "w": ["Békéscsaba", "Nyíregyháza", "Debrecen"]},
  {"a": "Jászberény", "p": "Melyik város a Jászság központja?", "s": "Városok", "w": ["Jászapáti", "Jászárokszállás", "Jászfényszaru"]},
  {"a": "Hortobágyi", "p": "Melyik volt Magyarország első nemzeti parkja?", "s": "Nemzeti parkok", "w": ["Kiskunsági", "Aggteleki", "Bükki"]},
  {"a": "1973-ban", "p": "Melyik évben alapították a Hortobágyi Nemzeti Parkot?", "s": "Nemzeti parkok", "w": ["1952-ben", "1985-ben", "1996-ban"]},
  {"a": "10", "p": "Hány nemzeti park van Magyarországon?", "s": "Nemzeti parkok", "w": ["12", "14", "6"]},
  {"a": "Aggteleki", "p": "Melyik nemzeti parkban található a Baradla-barlang?", "s": "Nemzeti parkok", "w": ["Duna–Ipoly", "Kiskunsági", "Bükki"]},
  {"a": "Hortobágyi", "p": "Melyik nemzeti park őrzi a Kilenclyukú hidat?", "s": "Nemzeti parkok", "w": ["Balaton-felvidéki", "Körös–Maros", "Kiskunsági"]},
  {"a": "Kiskunsági", "p": "Melyik nemzeti park őrzi a bugaci pusztát?", "s": "Nemzeti parkok", "w": ["Balaton-felvidéki", "Körös–Maros", "Hortobágyi"]},
  {"a": "Őrségi", "p": "Melyik nemzeti park terül el Vas megye nyugati szélén?", "s": "Nemzeti parkok", "w": ["Balaton-felvidéki", "Fertő–Hanság", "Duna–Dráva"]},
  {"a": "Őrségi", "p": "Melyik a legfiatalabb nemzeti parkunk?", "s": "Nemzeti parkok", "w": ["Balaton-felvidéki", "Körös–Maros", "Duna–Ipoly"]},
  {"a": "Fertő–Hanság", "p": "Melyik nemzeti park védi a Fertő tó magyar partját?", "s": "Nemzeti parkok", "w": ["Balaton-felvidéki", "Duna–Ipoly", "Őrségi"]},
  {"a": "Duna–Ipoly", "p": "Melyik nemzeti park terül el a Dunakanyar körül?", "s": "Nemzeti parkok", "w": ["Balaton-felvidéki", "Fertő–Hanság", "Duna–Dráva"]},
  {"a": "Duna–Dráva", "p": "Melyik nemzeti park fekszik Baranya és Tolna déli részén?", "s": "Nemzeti parkok", "w": ["Balaton-felvidéki", "Körös–Maros", "Duna–Ipoly"]},
  {"a": "Körös–Maros", "p": "Melyik nemzeti park védi a Körösök vidékét?", "s": "Nemzeti parkok", "w": ["Balaton-felvidéki", "Fertő–Hanság", "Duna–Dráva"]},
  {"a": "Bükki", "p": "Melyik nemzeti park terül el Miskolc és Eger között?", "s": "Nemzeti parkok", "w": ["Balaton-felvidéki", "Aggteleki", "Őrségi"]},
  {"a": "A Hortobágy", "p": "Melyik magyar puszta került a világörökség listájára?", "s": "Nemzeti parkok", "w": ["A Nagykunság", "A Kiskunság", "A Hajdúság"]},
  {"a": "Az aggteleki", "p": "Melyik barlangrendszer szerepel a világörökség listáján?", "s": "Nemzeti parkok", "w": ["A szemlő-hegyi", "A pálvölgyi", "A tapolcai"]},
  {"a": "A pannonhalmi", "p": "Melyik apátság szerepel a világörökség listáján?", "s": "Nemzeti parkok", "w": ["A bélapátfalvi", "A tihanyi", "A zirci"]},
  {"a": "A Fertő tó", "p": "Melyik tavunk világörökségi helyszín Ausztriával közösen?", "s": "Nemzeti parkok", "w": ["A Velencei-tó", "A Tisza-tó", "A Balaton"]},
  {"a": "1952-ben", "p": "Mikor lett védett terület a Tihanyi-félsziget?", "s": "Nemzeti parkok", "w": ["1973-ban", "1985-ben", "1996-ban"]},
  {"a": "A szürkemarha", "p": "Melyik szarvasmarhafajta a Hortobágy jelképe?", "s": "Nemzeti parkok", "w": ["A jersey-marha", "A pirostarka", "A holstein"]},
  {"a": "A racka", "p": "Melyik juhfajta legel a hortobágyi pusztán?", "s": "Nemzeti parkok", "w": ["A suffolk juh", "A merinó", "A cigája"]},
  {"a": "A boróka", "p": "Melyik cserje jellemző a kiskunsági homokbuckákra?", "s": "Nemzeti parkok", "w": ["A vörösfenyő", "A bükkfa", "A nyírfa"]},
  {"a": "A lipicai", "p": "Melyik ménes híres Szilvásváradon?", "s": "Nemzeti parkok", "w": ["Az arab telivér", "A nóniusz", "A muraközi"]},
  {"a": "Héttel", "p": "Hány országgal határos Magyarország?", "s": "Határok és szomszédok", "w": ["Nyolccal", "Hattal", "Öttel"]},
  {"a": "Ausztria", "p": "Magyarország melyik szomszédja fekszik nyugaton?", "s": "Határok és szomszédok", "w": ["Horvátország", "Szlovákia", "Szlovénia"]},
  {"a": "Szlovákia", "p": "Magyarország melyik szomszédja fekszik északon?", "s": "Határok és szomszédok", "w": ["Horvátország", "Szlovénia", "Ukrajna"]},
  {"a": "Románia", "p": "Magyarország melyik szomszédja fekszik keleten?", "s": "Határok és szomszédok", "w": ["Horvátország", "Szlovákia", "Ukrajna"]},
  {"a": "Ukrajna", "p": "Magyarország melyik szomszédja fekszik északkeleten?", "s": "Határok és szomszédok", "w": ["Horvátország", "Szlovákia", "Románia"]},
  {"a": "Szlovénia", "p": "Magyarország melyik szomszédja a legkisebb területű?", "s": "Határok és szomszédok", "w": ["Horvátország", "Szlovákia", "Ausztria"]},
  {"a": "Szlovákiával", "p": "Melyik szomszéddal a leghosszabb a határunk?", "s": "Határok és szomszédok", "w": ["Horvátországgal", "Ausztriával", "Romániával"]},
  {"a": "Szlovéniával", "p": "Melyik szomszéddal a legrövidebb a határunk?", "s": "Határok és szomszédok", "w": ["Horvátországgal", "Ausztriával", "Ukrajnával"]},
  {"a": "Ukrajna", "p": "Melyik ország felé nyílik a záhonyi határátkelő?", "s": "Határok és szomszédok", "w": ["Horvátország", "Szlovákia", "Románia"]},
  {"a": "Szerbia", "p": "Melyik ország felé nyílik a röszkei határátkelő?", "s": "Határok és szomszédok", "w": ["Horvátország", "Szlovénia", "Románia"]},
  {"a": "Ausztria", "p": "Melyik ország felé nyílik a hegyeshalmi határátkelő?", "s": "Határok és szomszédok", "w": ["Horvátország", "Szlovákia", "Szlovénia"]},
  {"a": "Komárom", "p": "Melyik város fekszik a Duna két partján, a szlovák határon?", "s": "Határok és szomszédok", "w": ["Balassagyarmat", "Esztergom", "Rajka"]},
  {"a": "93 ezer km²", "p": "Mekkora Magyarország területe?", "s": "Határok és szomszédok", "w": ["120 ezer km²", "150 ezer km²", "45 ezer km²"]},
  {"a": "Kilencmillióan", "p": "Hányan élnek körülbelül Magyarországon?", "s": "Határok és szomszédok", "w": ["Tizenötmillióan", "Húszmillióan", "Ötmillióan"]},
  {"a": "Ausztria", "p": "Melyik ország felé vezet az M1-es autópálya?", "s": "Határok és szomszédok", "w": ["Horvátország", "Szlovákia", "Románia"]},
  {"a": "Szeged", "p": "Melyik nagyváros felé vezet az M5-ös autópálya?", "s": "Határok és szomszédok", "w": ["Debrecen", "Miskolc", "Pécs"]},
  {"a": "Pécs", "p": "Melyik nagyváros felé vezet az M6-os autópálya?", "s": "Határok és szomszédok", "w": ["Debrecen", "Miskolc", "Szeged"]},
  {"a": "Debrecen", "p": "Melyik nagyváros felé vezet az M35-ös autópálya?", "s": "Határok és szomszédok", "w": ["Nyíregyháza", "Miskolc", "Szeged"]},
  {"a": "Duna", "p": "Melyik folyó lép be az országba Rajkánál?", "s": "Határok és szomszédok", "w": ["Dráva", "Tisza", "Rába"]},
  {"a": "23", "p": "Hány kerülete van Budapestnek?", "s": "Budapest földrajza", "w": ["18", "20", "25"]},
  {"a": "Pest, Buda, Óbuda", "p": "Melyik három város egyesüléséből jött létre Budapest?", "s": "Budapest földrajza", "w": ["Pest, Óbuda, Kispest", "Buda, Óbuda, Újpest", "Pest, Buda, Csepel"]},
  {"a": "1873-ban", "p": "Melyik évben egyesült Pest, Buda és Óbuda?", "s": "Budapest földrajza", "w": ["1848-ban", "1896-ban", "1920-ban"]},
  {"a": "Buda", "p": "Melyik oldala dombos Budapestnek?", "s": "Budapest földrajza", "w": ["Kőbánya", "Zugló", "Pest"]},
  {"a": "A Lánchíd", "p": "Melyik Budapest legrégibb állandó hídja?", "s": "Budapest földrajza", "w": ["Az Erzsébet híd", "A Szabadság híd", "A Margit híd"]},
  {"a": "1849-ben", "p": "Melyik évben nyílt meg a Lánchíd?", "s": "Budapest földrajza", "w": ["1873-ban", "1896-ban", "1903-ban"]},
  {"a": "A Margitsziget", "p": "Melyik sziget fekszik a Margit híd és az Árpád híd között?", "s": "Budapest földrajza", "w": ["A Szentendrei-sziget", "A Hajógyári-sziget", "A Csepel-sziget"]},
  {"a": "A Megyeri híd", "p": "Melyik Budapest legészakibb Duna-hídja?", "s": "Budapest földrajza", "w": ["A Rákóczi híd", "Az Árpád híd", "A Margit híd"]},
  {"a": "A Szabadság híd", "p": "Melyik híd köti össze a Gellért teret a Fővám térrel?", "s": "Budapest földrajza", "w": ["Az Erzsébet híd", "A Petőfi híd", "A Margit híd"]},
  {"a": "A Lánchíd", "p": "Melyik híd vezet a Clark Ádám térhez?", "s": "Budapest földrajza", "w": ["Az Erzsébet híd", "A Petőfi híd", "A Margit híd"]},
  {"a": "A János-hegy", "p": "Melyik hegy Budapest legmagasabb pontja?", "s": "Budapest földrajza", "w": ["A Hármashatár-hegy", "A Gellért-hegy", "A Sas-hegy"]},
  {"a": "A Gellért-hegy", "p": "Melyik hegyen áll a budapesti Szabadság-szobor?", "s": "Budapest földrajza", "w": ["A Hármashatár-hegy", "A János-hegy", "A Sas-hegy"]},
  {"a": "A János-hegyen", "p": "Melyik budai hegyen áll az Erzsébet-kilátó?", "s": "Budapest földrajza", "w": ["A Széchenyi-hegyen", "A Gellért-hegyen", "A Sas-hegyen"]},
  {"a": "235 méter", "p": "Milyen magas a Gellért-hegy?", "s": "Budapest földrajza", "w": ["1014 méter", "527 méter", "150 méter"]},
  {"a": "A Széchenyi-hegyre", "p": "Melyik hegyre visz fel a fogaskerekű vasút?", "s": "Budapest földrajza", "w": ["A Hármashatár-hegyre", "A Gellért-hegyre", "A Sas-hegyre"]},
  {"a": "Az elsőben", "p": "Melyik kerületben áll a Budai Vár?", "s": "Budapest földrajza", "w": ["A tizenkettedikben", "A harmadikban", "A másodikban"]},
  {"a": "A harmadik", "p": "Hányadik kerület Óbuda?", "s": "Budapest földrajza", "w": ["A tizenharmadik", "A negyedik", "A második"]},
  {"a": "Az ötödik", "p": "Hányadik kerület a Belváros?", "s": "Budapest földrajza", "w": ["A tizenharmadik", "A hetedik", "A hatodik"]},
  {"a": "A huszonegyedik", "p": "Hányadik kerület Csepel?", "s": "Budapest földrajza", "w": ["A huszonharmadik", "A huszonkettedik", "A huszadik"]},
  {"a": "A tizedik", "p": "Hányadik kerület Kőbánya?", "s": "Budapest földrajza", "w": ["A tizenkilencedik", "A nyolcadik", "A huszadik"]},
  {"a": "A tizennegyedik", "p": "Hányadik kerület Zugló?", "s": "Budapest földrajza", "w": ["A tizenharmadik", "A tizenhatodik", "A tizedik"]},
  {"a": "A tizenkettedik", "p": "Melyik budai kerület neve Hegyvidék?", "s": "Budapest földrajza", "w": ["A huszonkettedik", "A tizenegyedik", "A második"]},
  {"a": "A Városliget", "p": "Melyik park szélén áll a Hősök tere?", "s": "Budapest földrajza", "w": ["A Margitsziget", "A Gellért-hegy", "A Népliget"]},
  {"a": "A Népliget", "p": "Melyik Budapest legnagyobb közparkja?", "s": "Budapest földrajza", "w": ["A Margitsziget", "A Városliget", "A Vérmező"]},
  {"a": "Széchenyi", "p": "Melyik gyógyfürdő található a Városligetben?", "s": "Budapest földrajza", "w": ["Palatinus", "Gellért", "Rudas"]},
  {"a": "A Hajógyári-szigeten", "p": "Melyik budapesti szigeten rendezik a Sziget Fesztivált?", "s": "Budapest földrajza", "w": ["A Szentendrei-szigeten", "A Csepel-szigeten", "A Margitszigeten"]},
  {"a": "Az egyes", "p": "Melyik metróvonal a legrégebbi Budapesten?", "s": "Budapest földrajza", "w": ["A hármas", "A négyes", "A kettes"]},
  {"a": "1896-ban", "p": "Melyik évben épült a budapesti földalatti?", "s": "Budapest földrajza", "w": ["1873-ban", "1949-ben", "1900-ban"]},
  {"a": "Négy", "p": "Hány metróvonal működik Budapesten?", "s": "Budapest földrajza", "w": ["Három", "Kettő", "Hat"]},
  {"a": "1,7 millió", "p": "Mekkora Budapest lakossága körülbelül?", "s": "Budapest földrajza", "w": ["3,2 millió", "0,5 millió", "5 millió"]},
  {"a": "Északról", "p": "Melyik irányból érkezik a Duna Budapestre?", "s": "Budapest földrajza", "w": ["Délkeletről", "Nyugatról", "Keletről"]},
  {"a": "Mérsékelt", "p": "Milyen éghajlati övezetben fekszik Magyarország?", "s": "Éghajlat és mezőgazdaság", "w": ["Sarkvidéki", "Mediterrán", "Trópusi"]},
  {"a": "Nyáron", "p": "Melyik évszakban a legmelegebb Magyarországon?", "s": "Éghajlat és mezőgazdaság", "w": ["Tavasszal", "Ősszel", "Télen"]},
  {"a": "Január", "p": "Melyik hónap a leghidegebb Magyarországon?", "s": "Éghajlat és mezőgazdaság", "w": ["November", "December", "Február"]},
  {"a": "Augusztusban", "p": "Melyik hónapban legmelegebb a Balaton vize?", "s": "Éghajlat és mezőgazdaság", "w": ["Szeptemberben", "Októberben", "Júniusban"]},
  {"a": "A Dél-Alföldön", "p": "Melyik országrészen süt a legtöbbet a nap?", "s": "Éghajlat és mezőgazdaság", "w": ["A Nyugat-Dunántúlon", "A Dunakanyarban", "Az Északi-hegyekben"]},
  {"a": "Nyugaton", "p": "Melyik országrészen esik a legtöbb csapadék?", "s": "Éghajlat és mezőgazdaság", "w": ["A Dunakanyarban", "Az Alföldön", "Keleten"]},
  {"a": "Az Alföld", "p": "Melyik nagy tájunk a legszárazabb?", "s": "Éghajlat és mezőgazdaság", "w": ["A Kisalföld", "A Dunántúl", "Az Őrség"]},
  {"a": "600 milliméter", "p": "Mennyi csapadék hullik nálunk évente átlagosan?", "s": "Éghajlat és mezőgazdaság", "w": ["1500 milliméter", "2500 milliméter", "200 milliméter"]},
  {"a": "Tíz fok körül", "p": "Mennyi Magyarország éves középhőmérséklete?", "s": "Éghajlat és mezőgazdaság", "w": ["Harminc fok körül", "Nulla fok körül", "Húsz fok körül"]},
  {"a": "A csernozjom", "p": "Milyen talaj teszi termékennyé az Alföld nagy részét?", "s": "Éghajlat és mezőgazdaság", "w": ["A tőzegtalaj", "A homoktalaj", "A sziktalaj"]},
  {"a": "A szikes", "p": "Milyen talaj jellemző a hortobágyi pusztára?", "s": "Éghajlat és mezőgazdaság", "w": ["A csernozjom", "A homokos", "A tőzeges"]},
  {"a": "Napraforgó", "p": "Melyik olajos növény terem nagy területen az Alföldön?", "s": "Éghajlat és mezőgazdaság", "w": ["Földimogyoró", "Szójabab", "Olajfa"]},
  {"a": "Almát", "p": "Melyik gyümölcsöt termesztik sokat a Nyírségben?", "s": "Éghajlat és mezőgazdaság", "w": ["Őszibarackot", "Narancsot", "Banánt"]},
  {"a": "A Nyírség", "p": "Melyik táj híres a burgonyatermesztéséről?", "s": "Éghajlat és mezőgazdaság", "w": ["A Hortobágy", "A Kisalföld", "A Mezőföld"]},
  {"a": "A hagyma", "p": "Melyik zöldségnövény tette híressé Makót?", "s": "Éghajlat és mezőgazdaság", "w": ["A paradicsom", "A burgonya", "A paprika"]},
  {"a": "A tölgy", "p": "Melyik fa a leggyakoribb a magyar erdőkben?", "s": "Éghajlat és mezőgazdaság", "w": ["A pálma", "A nyírfa", "A fenyő"]},
  {"a": "Körülbelül húsz", "p": "Az ország hány százalékát borítja erdő?", "s": "Éghajlat és mezőgazdaság", "w": ["Körülbelül ötven", "Körülbelül hetven", "Körülbelül öt"]},
  {"a": "Füves puszta", "p": "Milyen természetes növénytakaró jellemezte az Alföldet?", "s": "Éghajlat és mezőgazdaság", "w": ["Mocsári nádas", "Trópusi erdő", "Fenyves erdő"]},
  {"a": "A paksi", "p": "Melyik erőmű adja a magyar áram legnagyobb részét?", "s": "Éghajlat és mezőgazdaság", "w": ["A dunamenti", "A mátrai", "A tiszai"]},
  {"a": "A Hortobágyon", "p": "Melyik tájon legelnek a szürkemarhák és a racka juhok?", "s": "Éghajlat és mezőgazdaság", "w": ["A Kisalföldön", "A Mezőföldön", "Az Őrségben"]},
  {"a": "A Kiskunság", "p": "Melyik táj homokján telepítettek sok szőlőt?", "s": "Éghajlat és mezőgazdaság", "w": ["A Nagykunság", "A Hortobágy", "A Hajdúság"]},
  {"a": "Tokaj", "p": "Melyik borvidék híres az aszúborairól?", "s": "Borvidékek", "w": ["Badacsony", "Villány", "Eger"]},
  {"a": "Eger", "p": "Melyik észak-magyarországi város híres a vörösborairól?", "s": "Borvidékek", "w": ["Salgótarján", "Gyöngyös", "Miskolc"]},
  {"a": "Villány", "p": "Melyik dél-baranyai borvidék híres a vörösborairól?", "s": "Borvidékek", "w": ["Badacsony", "Szekszárd", "Somló"]},
  {"a": "Badacsony", "p": "Melyik borvidék terül el a Balaton északi partján?", "s": "Borvidékek", "w": ["Balatonboglár", "Szekszárd", "Villány"]},
  {"a": "Somló", "p": "Melyik Magyarország legkisebb borvidéke?", "s": "Borvidékek", "w": ["Badacsony", "Villány", "Tokaj"]},
  {"a": "Kunság", "p": "Melyik Magyarország legnagyobb borvidéke?", "s": "Borvidékek", "w": ["Badacsony", "Villány", "Tokaj"]},
  {"a": "Szekszárd", "p": "Melyik tolnai város híres a borvidékéről?", "s": "Borvidékek", "w": ["Dunaföldvár", "Dombóvár", "Paks"]},
  {"a": "Tokaj-Hegyalja", "p": "Melyik borvidék tája került a világörökség listájára?", "s": "Borvidékek", "w": ["Villányi borvidék", "Somlói borvidék", "Egri borvidék"]},
  {"a": "Borsod-Abaúj-Zemplén", "p": "Melyik megyében fekszik a tokaji borvidék nagy része?", "s": "Borvidékek", "w": ["Szabolcs-Szatmár-Bereg", "Hajdú-Bihar", "Heves"]},
  {"a": "Sopron", "p": "Melyik város híres a kékfrankosáról a nyugati határon?", "s": "Borvidékek", "w": ["Mosonmagyaróvár", "Szombathely", "Kőszeg"]},
  {"a": "Mór", "p": "Melyik Fejér megyei város híres a borvidékéről?", "s": "Borvidékek", "w": ["Sárbogárd", "Gárdony", "Bicske"]},
  {"a": "Gyöngyös", "p": "Melyik város a Mátra borvidékének központja?", "s": "Borvidékek", "w": ["Salgótarján", "Hatvan", "Eger"]},
  {"a": "Az ezerjó", "p": "Melyik szőlőfajta tette híressé Mórt?", "s": "Borvidékek", "w": ["A kékfrankos", "A hárslevelű", "A kadarka"]},
  {"a": "A furmint", "p": "Melyik szőlőfajta jellemző Tokaj-Hegyalján?", "s": "Borvidékek", "w": ["A kékfrankos", "A kadarka", "A rizling"]},
  {"a": "22", "p": "Hány borvidék van Magyarországon?", "s": "Borvidékek", "w": ["10", "15", "30"]},
  {"a": "A Dráva", "p": "Melyik folyó választja el Baranyát Horvátországtól?", "s": "Határok és szomszédok", "w": ["A Tisza", "A Mura", "A Duna"]},
  {"a": "Románia", "p": "Melyik ország felé vezet az M43-as autópálya?", "s": "Határok és szomszédok", "w": ["Horvátország", "Szlovákia", "Szerbia"]},
  {"a": "Pest", "p": "Melyik megye veszi körül Budapestet?", "s": "Határok és szomszédok", "w": ["Komárom-Esztergom", "Nógrád", "Fejér"]},
  {"a": "Az Alföldön", "p": "Melyik nagy tájon fekszik az ország nagyobb része?", "s": "Határok és szomszédok", "w": ["A Kisalföldön", "A Dunántúlon", "A hegyekben"]},
  {"a": "Nyár elején", "p": "Melyik évszakban hullik nálunk a legtöbb csapadék?", "s": "Éghajlat és mezőgazdaság", "w": ["Tavasz elején", "Tél közepén", "Ősz végén"]},
  {"a": "A hegyvidéken", "p": "Melyik tájunkon a leghűvösebb a nyár?", "s": "Éghajlat és mezőgazdaság", "w": ["A Kisalföldön", "A Dunántúlon", "Az Alföldön"]},
  {"a": "A Kiskunság", "p": "Melyik táj része a bugaci puszta?", "s": "Nemzeti parkok", "w": ["A Nagykunság", "A Hortobágy", "A Hajdúság"]},
  {"a": "1985-ben", "p": "Melyik évben alapították az Aggteleki Nemzeti Parkot?", "s": "Nemzeti parkok", "w": ["1973-ban", "1996-ban", "2002-ben"]},
  {"a": "1975-ben", "p": "Melyik évben alapították a Kiskunsági Nemzeti Parkot?", "s": "Nemzeti parkok", "w": ["1985-ben", "1996-ban", "2002-ben"]},
  {"a": "2002-ben", "p": "Melyik évben alapították az Őrségi Nemzeti Parkot?", "s": "Nemzeti parkok", "w": ["1973-ban", "1985-ben", "1996-ban"]},
  {"a": "A tizennegyedik", "p": "Hányadik kerületben fekszik a Városliget?", "s": "Budapest földrajza", "w": ["A tizenharmadik", "A tizenkettedik", "A hetedik"]},
  {"a": "A Népliget", "p": "Melyik pesti park fekszik az Üllői út mellett?", "s": "Budapest földrajza", "w": ["A Margitsziget", "A Városliget", "A Vérmező"]}
]
$questions$::jsonb)
  with ordinality as question(item, ordinality);

do $validation$
begin
  if (
    select count(*) from public.quiz_questions
    where category_id = 'magyar_foldrajz' and is_active
  ) <> 355 then
    raise exception 'Magyarország földrajza must contain exactly 355 active questions';
  end if;

  if exists (
    select 1
    from public.quiz_questions as question
    where question.category_id = 'magyar_foldrajz'
      and (
        cardinality(question.wrong_answers) <> 3
        or (
          select count(distinct lower(trim(answer)))
          from unnest(question.wrong_answers) as answer
        ) <> 3
        or exists (
          select 1
          from unnest(question.wrong_answers) as answer
          where lower(trim(answer)) = lower(trim(question.correct_answer))
        )
      )
  ) then
    raise exception 'Magyarország földrajza: every question needs three distinct wrong answers';
  end if;

  if exists (
    select 1
    from public.quiz_questions as proposed
    join public.quiz_questions as existing
      on lower(trim(existing.prompt)) = lower(trim(proposed.prompt))
     and existing.id <> proposed.id
    where proposed.category_id = 'magyar_foldrajz'
  ) then
    raise exception 'Magyarország földrajza: a prompt is already used by another question';
  end if;
end;
$validation$;
