-- Magyar konyha: 306 questions in Hungarian.
--
-- Written so the correct answer is never the longest option -- the tell that
-- made the Psychology bank guessable without reading the prompt. All four
-- choices share one type and grammatical form.
insert into public.quiz_questions (
  id,
  category_id,
  prompt,
  correct_answer,
  wrong_answers,
  language_code,
  grade_level,
  subject,
  display_order,
  is_active
)
select
  'magyar_konyha_' || lpad(question.ordinality::text, 4, '0'),
  'magyar_konyha',
  question.item ->> 'p',
  question.item ->> 'a',
  array(select jsonb_array_elements_text(question.item -> 'w')),
  'hu',
  null,
  question.item ->> 's',
  question.ordinality::integer,
  true
from jsonb_array_elements($questions$
[
  {"a": "Marhahúsból", "p": "Milyen húsból készül a hagyományos gulyásleves?", "s": "Klasszikus ételek", "w": ["Bárányhúsból", "Csirkehúsból", "Pulykahúsból"]},
  {"a": "A paprika", "p": "Melyik fűszer adja a gulyásleves piros színét?", "s": "Klasszikus ételek", "w": ["A sáfrány", "A szerecsendió", "A kurkuma"]},
  {"a": "Marhapásztort", "p": "Mit jelent eredetileg a gulyás szó?", "s": "Klasszikus ételek", "w": ["Halászembert", "Kemencemestert", "Fűszerkereskedőt"]},
  {"a": "Burgonya", "p": "Melyik zöldség kerül a gulyáslevesbe a hagyma mellé?", "s": "Klasszikus ételek", "w": ["Padlizsán", "Karfiol", "Cukkini"]},
  {"a": "Apró tésztadarab", "p": "Mi a csipetke?", "s": "Klasszikus ételek", "w": ["Darált húsgombóc", "Füstölt szalonnafajta", "Savanyított uborka"]},
  {"a": "A pörkölt", "p": "Melyik étel sűrű, nem leves?", "s": "Klasszikus ételek", "w": ["A húsleves", "A palócleves", "A gulyásleves"]},
  {"a": "Hagyma pirításával", "p": "Mivel kezdődik a pörkölt készítése?", "s": "Klasszikus ételek", "w": ["Tojásfehérje felverésével", "Tészta főzésével", "Liszt szitálásával"]},
  {"a": "A pörkölt", "p": "Melyik étel nem tartalmaz tejfölt?", "s": "Klasszikus ételek", "w": ["A meggyleves", "A paprikás csirke", "A székelykáposzta"]},
  {"a": "Tejföllel", "p": "Mivel egészítik ki a paprikást a pörkölthöz képest?", "s": "Klasszikus ételek", "w": ["Citromlével", "Mustárral", "Paradicsommal"]},
  {"a": "Nokedlit", "p": "Melyik köretet adják leggyakrabban a paprikás csirkéhez?", "s": "Klasszikus ételek", "w": ["Hasábburgonyát", "Zsemlegombócot", "Kuszkuszt"]},
  {"a": "Pontyból", "p": "Melyik halból készül leggyakrabban a halászlé?", "s": "Klasszikus ételek", "w": ["Heringből", "Pisztrángból", "Tőkehalból"]},
  {"a": "Bajáról", "p": "Melyik városról kapta nevét a tésztával tálalt halászlé?", "s": "Klasszikus ételek", "w": ["Debrecenről", "Szegedről", "Kecskemétről"]},
  {"a": "Vöröshagyma", "p": "Mi kerül a halászlébe a halon kívül?", "s": "Klasszikus ételek", "w": ["Reszelt sajt", "Darált dió", "Tejszín"]},
  {"a": "Halleves", "p": "Milyen ételfajta a halászlé?", "s": "Klasszikus ételek", "w": ["Halsaláta", "Halpástétom", "Sült hal"]},
  {"a": "Rizs", "p": "Mi van a töltött káposzta töltelékében a hús mellett?", "s": "Klasszikus ételek", "w": ["Búzadara", "Burgonya", "Zsemlemorzsa"]},
  {"a": "Tejfölt", "p": "Mit tesznek a töltött káposzta tetejére?", "s": "Klasszikus ételek", "w": ["Reszelt sajtot", "Porcukrot", "Mustárt"]},
  {"a": "Savanyút", "p": "Milyen káposztát használnak a töltött káposztához?", "s": "Klasszikus ételek", "w": ["Vöröset", "Kelkáposztát", "Kínai kelt"]},
  {"a": "Csülköt", "p": "Melyik füstölt húst főzik a töltött káposztába?", "s": "Klasszikus ételek", "w": ["Bárányt", "Halfilét", "Kacsamellet"]},
  {"a": "Paprika és paradicsom", "p": "Mi a lecsó két fő alapanyaga?", "s": "Klasszikus ételek", "w": ["Sárgarépa és zellergumó", "Uborka és karalábé", "Burgonya és káposzta"]},
  {"a": "Kolbász", "p": "Melyik hús kerül gyakran a lecsóba?", "s": "Klasszikus ételek", "w": ["Bárányborda", "Füstölt sonka", "Marhaszelet"]},
  {"a": "Zöldségétel", "p": "Milyen ételfajta a lecsó?", "s": "Klasszikus ételek", "w": ["Húsleves", "Savanyúság", "Édes sütemény"]},
  {"a": "TV paprikából", "p": "Melyik paprikafajtából készül a lecsó?", "s": "Klasszikus ételek", "w": ["Kaliforniai paprikából", "Cseresznyepaprikából", "Chili paprikából"]},
  {"a": "Főtt tojás", "p": "Mi kerül a rakott krumpliba a burgonya mellé?", "s": "Klasszikus ételek", "w": ["Főtt bab", "Reszelt alma", "Darált dió"]},
  {"a": "Kolbász", "p": "Melyik hús kerül gyakran a rakott krumpliba?", "s": "Klasszikus ételek", "w": ["Pulykamell", "Darált bárány", "Füstölt csülök"]},
  {"a": "Sütőben sül meg", "p": "Hogyan készül el a rakott krumpli?", "s": "Klasszikus ételek", "w": ["Gőz fölött párolódik", "Hideg vízben ázik", "Olajban fő ki"]},
  {"a": "Sűrített zöldségétel", "p": "Mi a főzelék?", "s": "Klasszikus ételek", "w": ["Hideg gyümölcsleves", "Sült húsos egytálétel", "Édes tésztaétel"]},
  {"a": "Lisztből és zsírból", "p": "Miből készül a rántás?", "s": "Klasszikus ételek", "w": ["Tejből és tojásból", "Cukorból és vízből", "Tejfölből és lisztből"]},
  {"a": "Tejfölből és lisztből", "p": "Miből készül a habarás?", "s": "Klasszikus ételek", "w": ["Tojásból és tejszínből", "Zsírból és lisztből", "Vajból és cukorból"]},
  {"a": "A kapor", "p": "Melyik zöldfűszer jár a tökfőzelékhez?", "s": "Klasszikus ételek", "w": ["A rozmaring", "A bazsalikom", "A menta"]},
  {"a": "Főtt tojást", "p": "Mit tesznek a sóskafőzelék tetejére?", "s": "Klasszikus ételek", "w": ["Pirított diót", "Olajbogyót", "Reszelt sajtot"]},
  {"a": "Fasírttal", "p": "Mivel tálalják gyakran a főzeléket?", "s": "Klasszikus ételek", "w": ["Rétestésztával", "Palacsintával", "Süteménnyel"]},
  {"a": "Cérnametéltet", "p": "Melyik tésztát teszik a húslevesbe?", "s": "Klasszikus ételek", "w": ["Spagettit", "Lasagne lapokat", "Rizstésztát"]},
  {"a": "Sárgarépát", "p": "Melyik zöldséget teszik mindig a húslevesbe?", "s": "Klasszikus ételek", "w": ["Padlizsánt", "Cukkinit", "Fejes salátát"]},
  {"a": "Egy színészről", "p": "Kiről nevezték el az újházi tyúkhúslevest?", "s": "Klasszikus ételek", "w": ["Egy tábornokról", "Egy királyról", "Egy festőről"]},
  {"a": "Sertéshúst", "p": "Milyen húst tesznek a székelykáposztába?", "s": "Klasszikus ételek", "w": ["Halfilét", "Pulykacombot", "Bárányhúst"]},
  {"a": "Pörkölt és káposzta", "p": "Melyik két étel keveréke a székelykáposzta?", "s": "Klasszikus ételek", "w": ["Leves és tészta", "Rizs és gomba", "Palacsinta és lekvár"]},
  {"a": "Jókai Mórról", "p": "Kiről nevezték el a csülkös bablevest?", "s": "Klasszikus ételek", "w": ["Mikszáth Kálmánról", "Petőfi Sándorról", "Arany Jánosról"]},
  {"a": "A palócleves", "p": "Melyik zöldbabos leves készül bárányhúsból?", "s": "Klasszikus ételek", "w": ["A gulyásleves", "A Jókai bableves", "A korhelyleves"]},
  {"a": "Meggyből", "p": "Melyik gyümölcsből készül a klasszikus hideg leves?", "s": "Klasszikus ételek", "w": ["Citromból", "Banánból", "Görögdinnyéből"]},
  {"a": "A gyümölcslevest", "p": "Melyik levest tálalják hidegen?", "s": "Klasszikus ételek", "w": ["Az újházi tyúkhúslevest", "A gombalevest", "A bablevest"]},
  {"a": "Liszt, tojás, morzsa", "p": "Mi a panír három rétege sorrendben?", "s": "Klasszikus ételek", "w": ["Tojás, cukor, dara", "Morzsa, tejföl, liszt", "Tojás, liszt, olaj"]},
  {"a": "Borjúhúsból", "p": "Melyik húsból készül a bécsi szelet eredetileg?", "s": "Klasszikus ételek", "w": ["Marhahúsból", "Sertéshúsból", "Csirkehúsból"]},
  {"a": "A burgonya", "p": "Melyik zöldség sül a brassói aprópecsenye mellé?", "s": "Klasszikus ételek", "w": ["A padlizsán", "A karfiol", "A sütőtök"]},
  {"a": "A fokhagyma", "p": "Melyik fűszer jellemző a brassói aprópecsenyére?", "s": "Klasszikus ételek", "w": ["A fahéj", "A szerecsendió", "A vanília"]},
  {"a": "Sós", "p": "Édes vagy sós étel a hortobágyi palacsinta?", "s": "Klasszikus ételek", "w": ["Csípős", "Édes", "Savanyú"]},
  {"a": "Húsos töltelékkel", "p": "Mivel töltik a hortobágyi palacsintát?", "s": "Klasszikus ételek", "w": ["Túróval és mazsolával", "Dióval és lekvárral", "Csokoládékrémmel"]},
  {"a": "A körméből", "p": "Melyik disznóhúsrészből főzik a kocsonyát?", "s": "Klasszikus ételek", "w": ["A tarjájából", "A szűzpecsenyéjéből", "A karajából"]},
  {"a": "Télen", "p": "Melyik évszakban készítik a kocsonyát?", "s": "Klasszikus ételek", "w": ["Tavasszal", "Nyáron", "Kora ősszel"]},
  {"a": "Sült húsokat", "p": "Mit szolgálnak fel a fatányéroson?", "s": "Klasszikus ételek", "w": ["Hideg gyümölcsöket", "Sós süteményeket", "Főtt tésztát"]},
  {"a": "Rizs", "p": "Mi kerül a töltött paprika töltelékébe a hús mellé?", "s": "Klasszikus ételek", "w": ["Kukorica", "Zsemlemorzsa", "Reszelt sajt"]},
  {"a": "Paradicsomból", "p": "Melyik zöldségből készül a töltött paprika mártása?", "s": "Klasszikus ételek", "w": ["Sárgarépából", "Padlizsánból", "Csiperkegombából"]},
  {"a": "Kolbász", "p": "Mi kerül a paprikás krumpliba a burgonya mellé?", "s": "Klasszikus ételek", "w": ["Édes tejszín", "Reszelt alma", "Darált mák"]},
  {"a": "Zsemlegombóc", "p": "Melyik köret jár a vadas marhához?", "s": "Klasszikus ételek", "w": ["Párolt rizs", "Hasábburgonya", "Túrós csusza"]},
  {"a": "Sárgarépából", "p": "Melyik zöldségből készül a vadas mártás?", "s": "Klasszikus ételek", "w": ["Karalábéból", "Céklából", "Csiperkegombából"]},
  {"a": "A gyomorból", "p": "Melyik belsőségből készül a pacalpörkölt?", "s": "Klasszikus ételek", "w": ["A csirkemájból", "A tüdőből", "A veséből"]},
  {"a": "Darált májból", "p": "Miből készül a májgombóc?", "s": "Klasszikus ételek", "w": ["Darált dióból", "Reszelt burgonyából", "Darált halból"]},
  {"a": "Csülköt", "p": "Melyik füstölt húst teszik a bablevesbe?", "s": "Klasszikus ételek", "w": ["Halfilét", "Bárányt", "Kacsamellet"]},
  {"a": "A trappistát", "p": "Melyik sajtot sütik ki leggyakrabban rántva?", "s": "Klasszikus ételek", "w": ["A mozzarellát", "A parmezánt", "A kéksajtot"]},
  {"a": "A slambuc", "p": "Melyik étel készül tarhonyából és krumpliból?", "s": "Klasszikus ételek", "w": ["A túrós csusza", "A rakott kelkáposzta", "A lebbencsleves"]},
  {"a": "Száraz tésztát", "p": "Mit törnek bele a lebbencslevesbe?", "s": "Klasszikus ételek", "w": ["Friss zsemlét", "Darált kekszet", "Pirított zsemlekockát"]},
  {"a": "A gulyás", "p": "Melyik étel neve a pásztorokra utal?", "s": "Klasszikus ételek", "w": ["A töltött káposzta", "A rakott krumpli", "A halászlé"]},
  {"a": "Darált hús", "p": "Mi kerül a rakott kelkáposztába a kel mellé?", "s": "Klasszikus ételek", "w": ["Reszelt alma", "Aszalt szilva", "Mazsola"]},
  {"a": "Szárított paprika", "p": "Mi a pirospaprika alapanyaga?", "s": "Fűszerek és alapanyagok", "w": ["Pirított hagyma", "Őrölt bors", "Szárított paradicsom"]},
  {"a": "Édesnemesnek", "p": "Hogyan hívják a nem csípős fűszerpaprikát?", "s": "Fűszerek és alapanyagok", "w": ["Csípős paprikának", "Erős őrleménynek", "Csemegekrémnek"]},
  {"a": "Amerikából", "p": "Melyik földrészről származik a paprika?", "s": "Fűszerek és alapanyagok", "w": ["Kínából", "Ausztráliából", "Indiából"]},
  {"a": "A törökök", "p": "Melyik nép hozta el hozzánk a paprikát?", "s": "Fűszerek és alapanyagok", "w": ["Az angolok", "A svédek", "A hollandok"]},
  {"a": "A köményt", "p": "Melyik fűszer magját teszik a gulyásba?", "s": "Fűszerek és alapanyagok", "w": ["A szegfűszeget", "A mustármagot", "A kardamomot"]},
  {"a": "A termés", "p": "A kömény melyik növényi rész?", "s": "Fűszerek és alapanyagok", "w": ["A levél", "A virágszirom", "A gyökér"]},
  {"a": "Szárított levél", "p": "Milyen fűszer a majoránna?", "s": "Fűszerek és alapanyagok", "w": ["Őrölt gyökér", "Darált mag", "Szárított virágbimbó"]},
  {"a": "A paprika", "p": "Melyik fűszer színezi pirosra a magyar kolbászt?", "s": "Fűszerek és alapanyagok", "w": ["A szegfűbors", "A kurkuma", "A cékla"]},
  {"a": "A fokhagyma", "p": "Melyik fűszer adja a kolbász jellegzetes illatát?", "s": "Fűszerek és alapanyagok", "w": ["A citromhéj", "A vaníliarúd", "A szegfűbors"]},
  {"a": "Tejszínből", "p": "Miből készül a tejföl?", "s": "Fűszerek és alapanyagok", "w": ["Búzalisztből", "Sertészsírból", "Tojásfehérjéből"]},
  {"a": "Alvadt tejből", "p": "Miből készül a túró?", "s": "Fűszerek és alapanyagok", "w": ["Felvert tojásból", "Darált magvakból", "Főtt burgonyából"]},
  {"a": "Tejszínből", "p": "Miből készül a vaj?", "s": "Fűszerek és alapanyagok", "w": ["Sertészsírból", "Tojássárgájából", "Növényi olajból"]},
  {"a": "Sertészsíron", "p": "Melyik zsiradékon főz hagyományosan a magyar konyha?", "s": "Fűszerek és alapanyagok", "w": ["Olívaolajon", "Vajon", "Napraforgóolajon"]},
  {"a": "Szalonnából", "p": "Miből lesz a tepertő?", "s": "Fűszerek és alapanyagok", "w": ["Marhacsontból", "Kenyérhéjból", "Halbőrből"]},
  {"a": "A tepertő", "p": "Mi marad a zsír kisütése után?", "s": "Fűszerek és alapanyagok", "w": ["A habarás", "A tejszínhab", "A rántás"]},
  {"a": "Szárított tészta", "p": "Mi a tarhonya?", "s": "Fűszerek és alapanyagok", "w": ["Savanyított zöldség", "Őrölt fűszerkeverék", "Füstölt kolbászféle"]},
  {"a": "Lisztből és tojásból", "p": "Miből gyúrják a tarhonyát?", "s": "Fűszerek és alapanyagok", "w": ["Kukoricából és tejből", "Burgonyából és sóból", "Rizsből és vízből"]},
  {"a": "BL 55", "p": "Milyen jelzés van a magyar finomliszt csomagján?", "s": "Fűszerek és alapanyagok", "w": ["T 405", "Type 550", "BL 80"]},
  {"a": "Élesztőt", "p": "Mit tesznek a kenyértésztába, hogy megkeljen?", "s": "Fűszerek és alapanyagok", "w": ["Étkezési szódát", "Zselatint", "Kukoricakeményítőt"]},
  {"a": "Darált olajos mag", "p": "Mi a mák a konyhában?", "s": "Fűszerek és alapanyagok", "w": ["Szárított fűszerlevél", "Édesített tejtermék", "Őrölt gabonaliszt"]},
  {"a": "A vöröshagymát", "p": "Melyik hagymát használják a legtöbb magyar ételhez?", "s": "Fűszerek és alapanyagok", "w": ["A medvehagymát", "A salátahagymát", "A metélőhagymát"]},
  {"a": "Belsőségekből", "p": "Milyen húsból van a hurka?", "s": "Fűszerek és alapanyagok", "w": ["Marhafartőből", "Halhúsból", "Darált pulykamellből"]},
  {"a": "Sertés", "p": "Milyen állat a mangalica?", "s": "Fűszerek és alapanyagok", "w": ["Szarvasmarha", "Baromfi", "Juh"]},
  {"a": "A göndör szőréről", "p": "Miről ismerhető fel a mangalica?", "s": "Fűszerek és alapanyagok", "w": ["A csíkos hátáról", "A hosszú szarváról", "A fekete csőréről"]},
  {"a": "A szürkemarha", "p": "Melyik magyar szarvasmarha híres a hosszú szarváról?", "s": "Fűszerek és alapanyagok", "w": ["A holstein tehén", "A jersey tehén", "A szimentáli tehén"]},
  {"a": "Fűszeres túrókrém", "p": "Mi a körözött?", "s": "Fűszerek és alapanyagok", "w": ["Füstölt kolbászkrém", "Édes gyümölcskrém", "Sós halpástétom"]},
  {"a": "Pirospaprika", "p": "Melyik fűszer van a körözöttben?", "s": "Fűszerek és alapanyagok", "w": ["Fahéj", "Őrölt szegfűszeg", "Vaníliarúd"]},
  {"a": "Főtt szalonna", "p": "Mi az abált szalonna?", "s": "Fűszerek és alapanyagok", "w": ["Nyers szalonna", "Füstölt szalonna", "Rántott szalonna"]},
  {"a": "Füstre akasztják", "p": "Mit csinálnak a hússal a füstöléshez?", "s": "Fűszerek és alapanyagok", "w": ["Fagyasztva szárítják", "Cukorba forgatják", "Tejbe áztatják"]},
  {"a": "Száraz zsemle", "p": "Mi a zsemlemorzsa alapanyaga?", "s": "Fűszerek és alapanyagok", "w": ["Őrölt mogyoró", "Reszelt burgonya", "Darált kukorica"]},
  {"a": "A főtt sonkához", "p": "Melyik ételhez adnak reszelt tormát?", "s": "Fűszerek és alapanyagok", "w": ["A palacsintához", "A rétesekhez", "A somlói galuskához"]},
  {"a": "Szilvából", "p": "Melyik gyümölcsből főzik a sötét, sűrű lekvárt?", "s": "Fűszerek és alapanyagok", "w": ["Sárgabarackból", "Birsalmából", "Ribizliből"]},
  {"a": "Pirospaprikát", "p": "Mit szórnak a szalonnás kenyérre?", "s": "Fűszerek és alapanyagok", "w": ["Fahéjat", "Reszelt csokoládét", "Kakaóport"]},
  {"a": "Galuska", "p": "Mi a nokedli másik neve?", "s": "Tészták és köretek", "w": ["Csusza", "Lebbencs", "Tarhonya"]},
  {"a": "Lisztből és tojásból", "p": "Miből készül a nokedli tésztája?", "s": "Tészták és köretek", "w": ["Burgonyából és tejszínből", "Darából és mézből", "Rizsből és vajból"]},
  {"a": "Szaggatóval", "p": "Mivel juttatják a nokedlit a forró vízbe?", "s": "Tészták és köretek", "w": ["Habverővel", "Húsdarálóval", "Nyújtófával"]},
  {"a": "A túrós csusza", "p": "Melyik étel készül főtt tésztából és túróból?", "s": "Tészták és köretek", "w": ["A mákos guba", "A somlói galuska", "A rakott krumpli"]},
  {"a": "Tepertő", "p": "Mi kerül a túrós csusza tetejére?", "s": "Tészták és köretek", "w": ["Pirított mandula", "Reszelt sajt", "Darált dió"]},
  {"a": "Porcukorral", "p": "Mivel szórják meg a mákos tésztát?", "s": "Tészták és köretek", "w": ["Zsemlemorzsával", "Sóval és borssal", "Reszelt sajttal"]},
  {"a": "A tarhonya", "p": "Melyik köret készül apró szárított tésztából?", "s": "Tészták és köretek", "w": ["A csipetke", "A nokedli", "A zsemlegombóc"]},
  {"a": "Az Alföldnek", "p": "Melyik tájegység köretének tartják a tarhonyát?", "s": "Tészták és köretek", "w": ["A Mátravidéknek", "A Dunántúlnak", "Az Őrségnek"]},
  {"a": "A kovászos uborkát", "p": "Melyik savanyúságot érlelik napon?", "s": "Tészták és köretek", "w": ["A csalamádét", "A savanyú káposztát", "Az ecetes uborkát"]},
  {"a": "Kenyérhéjat", "p": "Mit tesznek a kovászos uborka üvegébe?", "s": "Tészták és köretek", "w": ["Cukros vizet", "Fahéjrudat", "Reszelt almát"]},
  {"a": "A kapor", "p": "Melyik zöldfűszer kerül a kovászos uborkába?", "s": "Tészták és köretek", "w": ["A bazsalikom", "A rozmaring", "A tárkony"]},
  {"a": "Nyáron", "p": "Mikor készül a kovászos uborka?", "s": "Tészták és köretek", "w": ["Télen", "Kora tavasszal", "Karácsonykor"]},
  {"a": "Fejes káposztából", "p": "Miből készül a savanyú káposzta?", "s": "Tészták és köretek", "w": ["Vörös káposztából", "Karalábéból", "Kínai kelkáposztából"]},
  {"a": "Vegyes savanyúság", "p": "Mi a csalamádé?", "s": "Tészták és köretek", "w": ["Sűrű krumplifőzelék", "Sült húsos tál", "Édes befőtt"]},
  {"a": "Sóval és erjesztéssel", "p": "Hogyan savanyítják a káposztát?", "s": "Tészták és köretek", "w": ["Cukorral és sütéssel", "Ecettel és fagyasztással", "Olajjal és füstöléssel"]},
  {"a": "Száraz zsemléből", "p": "Miből készül a zsemlegombóc?", "s": "Tészták és köretek", "w": ["Főtt burgonyából", "Reszelt sajtból", "Darált diófélékből"]},
  {"a": "Csipetkét", "p": "Melyik tésztát teszik a bablevesbe?", "s": "Tészták és köretek", "w": ["Lebbencstésztát", "Cérnametéltet", "Kagylótésztát"]},
  {"a": "Tésztaétel", "p": "Milyen étel a káposztás kocka?", "s": "Tészták és köretek", "w": ["Levesfajta", "Süteményféle", "Savanyúság"]},
  {"a": "Borssal", "p": "Mivel ízesítik a káposztás tésztát?", "s": "Tészták és köretek", "w": ["Vaníliával", "Fahéjjal", "Citromhéjjal"]},
  {"a": "Nokedlit", "p": "Mit adnak leggyakrabban a pörkölt mellé?", "s": "Tészták és köretek", "w": ["Gyümölcssalátát", "Rizsfelfújtat", "Palacsintát"]},
  {"a": "Tészta és burgonya", "p": "Mi a grenadírmars két fő összetevője?", "s": "Tészták és köretek", "w": ["Bab és kolbász", "Rizs és csiperkegomba", "Káposzta és alma"]},
  {"a": "Főtt burgonyából", "p": "Miből készül a krumplis tészta?", "s": "Tészták és köretek", "w": ["Reszelt almából", "Darált húsból", "Őrölt mákos töltelékből"]},
  {"a": "A csemegeuborka", "p": "Melyik savanyúság készül uborkából és ecetből?", "s": "Tészták és köretek", "w": ["A savanyú káposzta", "A kovászos uborka", "A csalamádé"]},
  {"a": "A káposztás tészta", "p": "Melyik tésztaétel édes és sós egyszerre?", "s": "Tészták és köretek", "w": ["A csipetkés bableves", "A hortobágyi palacsinta", "A rakott krumpli"]},
  {"a": "Szabálytalan", "p": "Milyen alakú a csipetke?", "s": "Tészták és köretek", "w": ["Hosszú szalag", "Kerek korong", "Tökéletes kocka"]},
  {"a": "Burgonyából", "p": "Melyik zöldségből készül a leggyakoribb köret?", "s": "Tészták és köretek", "w": ["Édesköményből", "Padlizsánból", "Articsókából"]},
  {"a": "A metéltet", "p": "Melyik tésztát vágják széles szalagokra?", "s": "Tészták és köretek", "w": ["A galuskát", "A tarhonyát", "A csipetkét"]},
  {"a": "A diós tészta", "p": "Melyik tésztaétel készül dióval és cukorral?", "s": "Tészták és köretek", "w": ["A túrós csusza", "A grenadírmars", "A káposztás kocka"]},
  {"a": "Karamell", "p": "Mi van a Dobos-torta tetején?", "s": "Sütemények és desszertek", "w": ["Csokoládémáz", "Tejszínhab", "Porcukor"]},
  {"a": "A cukrászáról", "p": "Kiről nevezték el a Dobos-tortát?", "s": "Sütemények és desszertek", "w": ["Egy városról", "Egy tábornokról", "Egy királynőről"]},
  {"a": "Csokoládés vajkrém", "p": "Milyen krém van a Dobos-tortában?", "s": "Sütemények és desszertek", "w": ["Tejszínhabos krém", "Gyümölcsös zselé", "Vaníliás pudingkrém"]},
  {"a": "Budapesten", "p": "Melyik városban készült először a Dobos-torta?", "s": "Sütemények és desszertek", "w": ["Szombathelyen", "Debrecenben", "Kecskeméten"]},
  {"a": "Pókhálós", "p": "Milyen mintás az Esterházy-torta teteje?", "s": "Sütemények és desszertek", "w": ["Kockás", "Virágmintás", "Pöttyös"]},
  {"a": "Vékonyra húzzák", "p": "Hogyan készül a rétestészta?", "s": "Sütemények és desszertek", "w": ["Vastagra vágják", "Formába öntik", "Kockára szaggatják"]},
  {"a": "Az alma", "p": "Melyik gyümölcs a rétes klasszikus töltelék?", "s": "Sütemények és desszertek", "w": ["Az ananász", "A narancs", "A banán"]},
  {"a": "A túrós rétest", "p": "Melyik túrós édességet sütik rétestésztában?", "s": "Sütemények és desszertek", "w": ["A Rigó Jancsit", "A somlói galuskát", "A mákos gubát"]},
  {"a": "Piskótából", "p": "Milyen tésztából készül a somlói galuska?", "s": "Sütemények és desszertek", "w": ["Rétestésztából", "Kelt tésztából", "Leveles tésztából"]},
  {"a": "A rum", "p": "Melyik szeszes ital kerül a somlói galuskába?", "s": "Sütemények és desszertek", "w": ["A vörösbor", "A pálinka", "A konyak"]},
  {"a": "Mazsolát", "p": "Mit tesznek a somlói galuskába a dió mellé?", "s": "Sütemények és desszertek", "w": ["Olajbogyót", "Kandírozott narancsot", "Aszalt szilvát"]},
  {"a": "Száraz kifliből", "p": "Miből készül a mákos guba?", "s": "Sütemények és desszertek", "w": ["Darált húsból", "Reszelt almából", "Főtt burgonyából"]},
  {"a": "Édes tejjel", "p": "Mivel áztatják meg a mákos guba kifliét?", "s": "Sütemények és desszertek", "w": ["Citromos sziruppal", "Forró olajjal", "Ecetes vízzel"]},
  {"a": "Karácsonykor", "p": "Mikor eszik hagyományosan a mákos gubát?", "s": "Sütemények és desszertek", "w": ["Húsvétkor", "Szilveszterkor", "Pünkösdkor"]},
  {"a": "Liszt, tojás, tej", "p": "Mi a palacsinta három alapanyaga?", "s": "Sütemények és desszertek", "w": ["Dara, olaj, cukor", "Rizs, vaj, méz", "Burgonya, só, tejföl"]},
  {"a": "Diós töltelékkel", "p": "Mivel töltik a Gundel palacsintát?", "s": "Sütemények és desszertek", "w": ["Túrós töltelékkel", "Almás töltelékkel", "Mákos töltelékkel"]},
  {"a": "Csokoládéöntetet", "p": "Mit öntenek a Gundel palacsintára?", "s": "Sütemények és desszertek", "w": ["Meggyszószt", "Vaníliás pudingot", "Karamellkrémet"]},
  {"a": "Porcukorral", "p": "Mivel szórják meg a túrós palacsintát?", "s": "Sütemények és desszertek", "w": ["Reszelt sajttal", "Zsemlemorzsával", "Őrölt paprikával"]},
  {"a": "Kelt tésztából", "p": "Milyen tésztából készül a bejgli?", "s": "Sütemények és desszertek", "w": ["Leveles tésztából", "Omlós tésztából", "Piskótából"]},
  {"a": "Mák és dió", "p": "Melyik két töltelék klasszikus a bejgliben?", "s": "Sütemények és desszertek", "w": ["Alma és szilva", "Kakaó és mogyoró", "Túró és mazsola"]},
  {"a": "Hengeres rúd", "p": "Milyen alakú a bejgli?", "s": "Sütemények és desszertek", "w": ["Golyó alakú", "Lapos korong", "Négyzet alakú"]},
  {"a": "Erdélyből", "p": "Honnan származik a kürtőskalács?", "s": "Sütemények és desszertek", "w": ["A Felvidékről", "A Dunántúlról", "Az Alföldről"]},
  {"a": "Forgó fahengeren", "p": "Hogyan sütik a kürtőskalácsot?", "s": "Sütemények és desszertek", "w": ["Lapos tepsiben", "Zárt formában sütve", "Olajban kisütve"]},
  {"a": "Cukorral", "p": "Mivel forgatják meg a kürtőskalácsot sütés előtt?", "s": "Sütemények és desszertek", "w": ["Liszttel", "Sóval", "Zsemlemorzsával"]},
  {"a": "Egy zenészről", "p": "Kiről nevezték el a Rigó Jancsi süteményt?", "s": "Sütemények és desszertek", "w": ["Egy cukrászról", "Egy szakácsról", "Egy királyról"]},
  {"a": "Csokoládés", "p": "Milyen ízű a Rigó Jancsi?", "s": "Sütemények és desszertek", "w": ["Citromos", "Málnás-tejszínes", "Vaníliás"]},
  {"a": "Kockára", "p": "Milyen alakúra vágják a Rigó Jancsit?", "s": "Sütemények és desszertek", "w": ["Háromszögre", "Rúd alakúra", "Csillag alakúra"]},
  {"a": "Dió és lekvár", "p": "Mi a zserbó két fő rétege?", "s": "Sütemények és desszertek", "w": ["Gesztenye és tejszín", "Alma és tejföl", "Túró és mák"]},
  {"a": "Sárgabarack", "p": "Milyen lekvár van a zserbóban?", "s": "Sütemények és desszertek", "w": ["Csipkebogyó", "Fekete ribizli", "Erdei szeder"]},
  {"a": "Egy cukrászról", "p": "Kiről kapta a nevét a zserbó?", "s": "Sütemények és desszertek", "w": ["Egy költőről", "Egy táncosnőről", "Egy tábornokról"]},
  {"a": "Csokoládé", "p": "Mi van a zserbó tetején?", "s": "Sütemények és desszertek", "w": ["Kandírozott dió", "Tojáshab", "Tejszínhab"]},
  {"a": "Vaníliás krém", "p": "Mi van a krémes két lapja között?", "s": "Sütemények és desszertek", "w": ["Diós töltelék", "Csokoládés ganache", "Gyümölcsös zselé"]},
  {"a": "Leveles tésztából", "p": "Milyen tésztából van a krémes lapja?", "s": "Sütemények és desszertek", "w": ["Kelt tésztából", "Piskótából", "Kevert kakaós tésztából"]},
  {"a": "A tejszínhabtól", "p": "Mitől más a francia krémes?", "s": "Sütemények és desszertek", "w": ["A gyümölcsös rétegtől", "A csokoládémáztól", "A mazsolától"]},
  {"a": "Tejből és tojásból", "p": "Miből készül a madártej?", "s": "Sütemények és desszertek", "w": ["Rizsből és mézből", "Gesztenyéből és rumból", "Lisztből és vajból"]},
  {"a": "Tojáshab", "p": "Mi úszik a madártej tetején?", "s": "Sütemények és desszertek", "w": ["Gyümölcsdarab", "Tejszínhab", "Csokoládéforgács"]},
  {"a": "Zsemlemorzsából", "p": "Miből készül a túrógombóc külseje?", "s": "Sütemények és desszertek", "w": ["Pirított mandulából", "Kekszmorzsából", "Darált dióból"]},
  {"a": "Tejföllel", "p": "Mivel tálalják a túrógombócot?", "s": "Sütemények és desszertek", "w": ["Mustárral", "Sós vajmártással", "Ecetes lével"]},
  {"a": "Szilva", "p": "Mi van a szilvás gombóc belsejében?", "s": "Sütemények és desszertek", "w": ["Sajt", "Dió", "Mazsola"]},
  {"a": "Burgonyából", "p": "Miből gyúrják a szilvás gombóc tésztáját?", "s": "Sütemények és desszertek", "w": ["Gesztenyéből", "Kukoricából", "Rizsből"]},
  {"a": "Morzsába", "p": "Mibe forgatják a szilvás gombócot?", "s": "Sütemények és desszertek", "w": ["Darált dióba", "Kókuszreszelékbe", "Kakaóporba"]},
  {"a": "Palacsintatésztából", "p": "Miből készül a császármorzsa?", "s": "Sütemények és desszertek", "w": ["Leveles tésztából", "Darált kekszből", "Kelt élesztős tésztából"]},
  {"a": "Porcukrot", "p": "Mit szórnak a császármorzsára?", "s": "Sütemények és desszertek", "w": ["Őrölt paprikát", "Reszelt sajtot", "Zsemlemorzsát"]},
  {"a": "Kelt tésztából", "p": "Milyen tésztából készül a farsangi fánk?", "s": "Sütemények és desszertek", "w": ["Piskótatésztából", "Leveles tésztából", "Omlós tésztából"]},
  {"a": "A fehér csíkjáról", "p": "Miről ismerhető fel a szalagos fánk?", "s": "Sütemények és desszertek", "w": ["A csokoládémázáról", "A zöld színéről", "A kockás mintájáról"]},
  {"a": "Lekvárba", "p": "Mibe mártják a fánkot?", "s": "Sütemények és desszertek", "w": ["Olívaolajba", "Tejfölbe", "Ecetbe"]},
  {"a": "Darált diót", "p": "Mit szórnak az aranygaluska darabjai közé?", "s": "Sütemények és desszertek", "w": ["Darált húst", "Reszelt sajtot", "Zsemlemorzsát"]},
  {"a": "Vaníliaöntetet", "p": "Mit öntenek az aranygaluskára?", "s": "Sütemények és desszertek", "w": ["Gyümölcsszószt", "Csokoládékrémet", "Karamellöntetet"]},
  {"a": "Fahéj", "p": "Melyik fűszer van a mézeskalácsban?", "s": "Sütemények és desszertek", "w": ["Majoránna", "Rozmaring", "Kapor"]},
  {"a": "A méz", "p": "Melyik édesítő adja a mézeskalács nevét?", "s": "Sütemények és desszertek", "w": ["A melasz", "A juharszirup", "A nádcukor"]},
  {"a": "Rétegelt sütemény", "p": "Mi a flódni?", "s": "Sütemények és desszertek", "w": ["Sós tésztaétel", "Füstölt halétel", "Hideg gyümölcsleves"]},
  {"a": "A gesztenye", "p": "Melyik töltelék nincs a flódniban?", "s": "Sütemények és desszertek", "w": ["A darált mák", "Az alma", "A dió"]},
  {"a": "Tojáshab", "p": "Mi a Rákóczi túrós teteje?", "s": "Sütemények és desszertek", "w": ["Tejszínhab", "Porcukros máz", "Csokoládémáz"]},
  {"a": "Lekvárcsíkokkal", "p": "Mivel díszítik a Rákóczi túróst?", "s": "Sütemények és desszertek", "w": ["Csokoládéforgáccsal", "Mandulalappal", "Kandírozott gyümölccsel"]},
  {"a": "Tejszínhabot", "p": "Mit tesznek a gesztenyepüré tetejére?", "s": "Sütemények és desszertek", "w": ["Olvasztott vajat", "Zsemlemorzsát", "Reszelt sajtot"]},
  {"a": "Rummal", "p": "Mivel ízesítik a gesztenyepürét?", "s": "Sütemények és desszertek", "w": ["Ecettel", "Fokhagymával", "Mustárral"]},
  {"a": "Omlós tésztából", "p": "Miből van a linzer tésztája?", "s": "Sütemények és desszertek", "w": ["Kelt tésztából", "Piskótatésztából", "Leveles tésztából"]},
  {"a": "Lekvár", "p": "Mi van két linzerlap között?", "s": "Sütemények és desszertek", "w": ["Csokoládé", "Sajtkrém", "Vajkrém"]},
  {"a": "Baracklekvár", "p": "Mi van az isler két lapja között?", "s": "Sütemények és desszertek", "w": ["Túrókrém", "Gesztenyemassza", "Vaníliapuding"]},
  {"a": "Csokoládéval", "p": "Mivel vonják be az islert?", "s": "Sütemények és desszertek", "w": ["Tojáshabbal", "Porcukorral", "Kókuszreszelékkel"]},
  {"a": "Tojás, cukor, liszt", "p": "Mi a piskóta három alapanyaga?", "s": "Sütemények és desszertek", "w": ["Élesztő, vaj és tejföl", "Zsír, só és víz", "Dara, méz és tej"]},
  {"a": "Darált dióval", "p": "Mivel töltik a diós patkót?", "s": "Sütemények és desszertek", "w": ["Darált hússal", "Reszelt sajttal", "Gesztenyével"]},
  {"a": "A korhelylevest", "p": "Melyik levest eszik újév hajnalán?", "s": "Ünnepi ételek", "w": ["A gyümölcslevest", "A karfiollevest", "A húsgombóclevest"]},
  {"a": "Savanyú káposzta", "p": "Mi a korhelyleves alapja?", "s": "Ünnepi ételek", "w": ["Zöldborsó és répa", "Friss paradicsom", "Aszalt szilva"]},
  {"a": "Lencsét", "p": "Melyik hüvelyest eszik újévkor a gazdagságért?", "s": "Ünnepi ételek", "w": ["Zöldborsót", "Csicseriborsót", "Fehér babot"]},
  {"a": "A malacé", "p": "Melyik állat húsa hoz szerencsét újévkor?", "s": "Ünnepi ételek", "w": ["A tyúké", "A halé", "A pulykáé"]},
  {"a": "A szárnyast", "p": "Melyik ételt kerülik újév napján?", "s": "Ünnepi ételek", "w": ["A malacsültet", "A kocsonyát", "A lencsét"]},
  {"a": "A lencsefőzeléket", "p": "Melyik ételt eszik szilveszterkor virslivel?", "s": "Ünnepi ételek", "w": ["A halászlevet", "A töltött káposztát", "A somlói galuskát"]},
  {"a": "Pontyból", "p": "Melyik halból készül a karácsonyi halászlé?", "s": "Ünnepi ételek", "w": ["Tonhalból", "Lazacból", "Pisztrángból"]},
  {"a": "A bejgli", "p": "Melyik sütemény kerül a karácsonyi asztalra?", "s": "Ünnepi ételek", "w": ["A szalagos fánk", "A krémes", "A kürtőskalács"]},
  {"a": "A mákos guba", "p": "Melyik édesség készül száraz kifliből télen?", "s": "Ünnepi ételek", "w": ["A rétes", "A somlói galuska", "A zserbó"]},
  {"a": "A szaloncukor", "p": "Melyik édesség lóg a magyar karácsonyfán?", "s": "Ünnepi ételek", "w": ["A csokitojás", "A marcipánfigura", "A húsvéti nyuszi"]},
  {"a": "Csokoládéból", "p": "Miből van a szaloncukor külseje?", "s": "Ünnepi ételek", "w": ["Kókuszreszelékből", "Karamellrétegből", "Marcipánból"]},
  {"a": "A sonka", "p": "Melyik hús a húsvéti asztal főszereplője?", "s": "Ünnepi ételek", "w": ["A libamáj", "A pulykamell", "A marhanyelv"]},
  {"a": "Tormát", "p": "Mit adnak a húsvéti sonka mellé?", "s": "Ünnepi ételek", "w": ["Almamártást", "Ketchupot", "Mustárolajat"]},
  {"a": "Tojást", "p": "Mit főznek meg a húsvéti sonkával együtt?", "s": "Ünnepi ételek", "w": ["Burgonyát", "Tésztát", "Rizst"]},
  {"a": "Húsvétra", "p": "Melyik ünnepre sütnek fonott kalácsot?", "s": "Ünnepi ételek", "w": ["Szüretre", "Mindenszentekre", "Farsangra"]},
  {"a": "A húsvét", "p": "Melyik ünnep étele a bárány?", "s": "Ünnepi ételek", "w": ["A karácsony", "A farsang", "A szüreti bál"]},
  {"a": "A farsang", "p": "Melyik ünnep süteménye a szalagos fánk?", "s": "Ünnepi ételek", "w": ["A karácsony", "A pünkösd", "A húsvét"]},
  {"a": "Márton-napon", "p": "Melyik napon esznek hagyományosan libát?", "s": "Ünnepi ételek", "w": ["Karácsonykor", "Szent István-napon", "Húsvéthétfőn"]},
  {"a": "Az új kenyér", "p": "Melyik étel jelképezi Szent István napját?", "s": "Ünnepi ételek", "w": ["A mézeskalács", "A halászlé", "A töltött káposzta"]},
  {"a": "Télen", "p": "Mikor tartják a disznótort?", "s": "Ünnepi ételek", "w": ["Húsvét után", "Aratáskor", "Nyáron"]},
  {"a": "A hurka", "p": "Melyik étel készül a disznótoron a belsőségekből?", "s": "Ünnepi ételek", "w": ["A lecsó", "A tarhonya", "A rétes"]},
  {"a": "Savanyúból", "p": "Melyik káposztából készül a toros káposzta?", "s": "Ünnepi ételek", "w": ["Vörösből", "Kelből", "Kínai kelből"]},
  {"a": "Az orjaleves", "p": "Melyik leves készül a disznótoron a csontból?", "s": "Ünnepi ételek", "w": ["A gyümölcsleves", "A korhelyleves", "A palócleves"]},
  {"a": "A pálinka", "p": "Melyik ital dukál a disznótorhoz?", "s": "Ünnepi ételek", "w": ["A pezsgő", "A gyümölcslé", "A limonádé"]},
  {"a": "Szilveszterkor", "p": "Melyik ünnepen isznak pezsgőt éjfélkor?", "s": "Ünnepi ételek", "w": ["Nagypénteken", "Húsvétkor", "Mindenszentekkor"]},
  {"a": "Szív alakúra", "p": "Milyen alakúra szaggatják a mézeskalácsot?", "s": "Ünnepi ételek", "w": ["Szabálytalanra", "Hosszú rúdra", "Lapos rúdra"]},
  {"a": "A húsleves", "p": "Melyik étel a lakodalmak klasszikus levese?", "s": "Ünnepi ételek", "w": ["A meggyleves", "A gyümölcsleves", "A korhelyleves"]},
  {"a": "Kenyérrel és sóval", "p": "Mivel köszöntik a vendéget a magyar házaknál?", "s": "Ünnepi ételek", "w": ["Borral és kaláccsal", "Tejjel és mézzel", "Gyümölccsel és dióval"]},
  {"a": "Szeged", "p": "Melyik város híres a fűszerpaprikájáról?", "s": "Tájjellegű ételek és eredet", "w": ["Székesfehérvár", "Nyíregyháza", "Miskolc"]},
  {"a": "Kalocsa", "p": "Melyik Duna menti város híres a paprikájáról?", "s": "Tájjellegű ételek és eredet", "w": ["Debrecen", "Hódmezővásárhely", "Szombathely"]},
  {"a": "Debrecen", "p": "Melyik városról nevezték el a páros kolbászt?", "s": "Tájjellegű ételek és eredet", "w": ["Kecskemét", "Nagykanizsa", "Szombathely"]},
  {"a": "Gyula és Békéscsaba", "p": "Melyik két város híres a kolbászáról?", "s": "Tájjellegű ételek és eredet", "w": ["Sopron és Szombathely", "Eger és Miskolc", "Pécs és Kaposvár"]},
  {"a": "Békéscsabáé", "p": "Melyik város kolbásza ismert erősebb ízéről?", "s": "Tájjellegű ételek és eredet", "w": ["Debrecené", "Székesfehérváré", "Kecskemété"]},
  {"a": "Vecsés", "p": "Melyik település savanyú káposztája híres?", "s": "Tájjellegű ételek és eredet", "w": ["Szentendre", "Gödöllő", "Balatonfüred"]},
  {"a": "Kecskemété", "p": "Melyik város barackpálinkája híres?", "s": "Tájjellegű ételek és eredet", "w": ["Székesfehérváré", "Tokajé", "Egeré"]},
  {"a": "Szilvából", "p": "Melyik gyümölcsből főzik a szatmári lekvárt?", "s": "Tájjellegű ételek és eredet", "w": ["Ribizliből", "Sárgabarackból", "Birsalmából"]},
  {"a": "Szegedét", "p": "Melyik város halászlevét szűrik át?", "s": "Tájjellegű ételek és eredet", "w": ["Győrét", "Bajáét", "Debrecenét"]},
  {"a": "A Hortobágyról", "p": "Melyik pusztáról kapta nevét a húsos palacsinta?", "s": "Tájjellegű ételek és eredet", "w": ["A Balaton-felvidékről", "A Kiskunságról", "A Bakonyról"]},
  {"a": "Karcagé", "p": "Melyik város birkapörköltje híres?", "s": "Tájjellegű ételek és eredet", "w": ["Soproné", "Balatonfüredé", "Kaposváré"]},
  {"a": "Birkából", "p": "Melyik állat húsából készül a karcagi pörkölt?", "s": "Tájjellegű ételek és eredet", "w": ["Szarvasból", "Halból", "Csirkemellből"]},
  {"a": "Fogast", "p": "Melyik halat fogják a Balatonban?", "s": "Tájjellegű ételek és eredet", "w": ["Tőkehalat", "Tonhalat", "Lazacot"]},
  {"a": "Szilvásváradhoz", "p": "Melyik településhez kötik a pisztrángot?", "s": "Tájjellegű ételek és eredet", "w": ["Hévízhez", "Hajdúszoboszlóhoz", "Mohácshoz"]},
  {"a": "Szegedé", "p": "Melyik város szalámija világhírű?", "s": "Tájjellegű ételek és eredet", "w": ["Pécsé", "Egeré", "Nyíregyházáé"]},
  {"a": "A Hortobágy", "p": "Melyik tájegység étele a slambuc?", "s": "Tájjellegű ételek és eredet", "w": ["A Balaton-felvidék", "A Bakony", "Az Őrség"]},
  {"a": "A Bakony", "p": "Melyik hegység nevét viseli a gombás tokány?", "s": "Tájjellegű ételek és eredet", "w": ["A Mátra", "A Zempléni-hegység", "A Mecsek"]},
  {"a": "Az Alföld", "p": "Melyik vidék étele a lebbencsleves?", "s": "Tájjellegű ételek és eredet", "w": ["A Dunántúl", "Az Őrség", "A Balaton-felvidék"]},
  {"a": "A pálpusztai", "p": "Melyik magyar sajt híres az erős szagáról?", "s": "Tájjellegű ételek és eredet", "w": ["A trappista sajt", "A füstölt sajt", "A juhtúró"]},
  {"a": "Miskolcé", "p": "Melyik város kocsonyafesztiválja ismert?", "s": "Tájjellegű ételek és eredet", "w": ["Szegedé", "Székesfehérváré", "Debrecené"]},
  {"a": "Az Alföldön", "p": "Melyik magyar tájon terem a legtöbb paprika?", "s": "Tájjellegű ételek és eredet", "w": ["A Bakonyban", "A Mátrában", "A Zempléni-hegységben"]},
  {"a": "Pozsony", "p": "Melyik város nevét viseli a mákos kifli?", "s": "Tájjellegű ételek és eredet", "w": ["Székesfehérvár", "Debrecen", "Kaposvár"]},
  {"a": "Gyuláé", "p": "Melyik vidék kolbásza kapott védett nevet?", "s": "Tájjellegű ételek és eredet", "w": ["Salgótarjáné", "Balatonfüredé", "Kaposváré"]},
  {"a": "Ausztriából", "p": "Melyik ország konyhájából jött a bécsi szelet?", "s": "Tájjellegű ételek és eredet", "w": ["Lengyelországból", "Olaszországból", "Spanyolországból"]},
  {"a": "Kukoricadarából", "p": "Miből készül a puliszka?", "s": "Tájjellegű ételek és eredet", "w": ["Darált rizsből", "Reszelt burgonyából", "Búzalisztből"]},
  {"a": "Az aszú", "p": "Melyik a leghíresebb tokaji édes bor?", "s": "Borvidékek és italok", "w": ["A hárslevelű", "A furmint", "A szamorodni"]},
  {"a": "Az édességet", "p": "Mit jelöl a puttonyszám az aszúnál?", "s": "Borvidékek és italok", "w": ["A palack méretét", "Az alkoholfokot", "A szüret évét"]},
  {"a": "Hat", "p": "Hány puttonyos a legédesebb tokaji aszú?", "s": "Borvidékek és italok", "w": ["Öt", "Három", "Négy"]},
  {"a": "A furmint", "p": "Melyik szőlőfajta a tokaji fő fajtája?", "s": "Borvidékek és italok", "w": ["A kadarka", "A juhfark", "A kékfrankos"]},
  {"a": "Ahogy termett", "p": "Mit jelent a szamorodni szó?", "s": "Borvidékek és italok", "w": ["Aranyszínű nedű", "Kétszer főtt", "Hegyi bor"]},
  {"a": "A borok királya", "p": "Melyik királyi mondás dicséri a tokajit?", "s": "Borvidékek és italok", "w": ["A pincék csodája", "Az ország aranya", "A hegyek gyöngye"]},
  {"a": "Vörös", "p": "Milyen színű bor az egri bikavér?", "s": "Borvidékek és italok", "w": ["Fehér", "Rozé", "Aranysárga"]},
  {"a": "Fajták házasítása", "p": "Mi jellemzi a bikavért?", "s": "Borvidékek és italok", "w": ["Gyümölcsök keveréke", "Egyetlen szőlőfajta", "Mézes ízesítés"]},
  {"a": "Szépasszony-völgy", "p": "Hogy hívják Eger híres pincesorát?", "s": "Borvidékek és italok", "w": ["Szalajka-völgy", "Badacsonyi présház", "Zempléni pincesor"]},
  {"a": "A kéknyelű", "p": "Melyik szőlőfajta a badacsonyi különlegesség?", "s": "Borvidékek és italok", "w": ["A kadarka", "A furmint", "A cabernet franc"]},
  {"a": "Somló", "p": "Melyik borvidék bora a juhfark?", "s": "Borvidékek és italok", "w": ["Balatonboglár", "Villány", "Tokaj"]},
  {"a": "Szekszárd", "p": "Melyik borvidék híres a kadarkáról?", "s": "Borvidékek és italok", "w": ["Eger", "Balatonfüred", "Sopron"]},
  {"a": "Móré", "p": "Melyik város bora a híres ezerjó?", "s": "Borvidékek és italok", "w": ["Egeré", "Pécsé", "Balatonfüredé"]},
  {"a": "Debrőről", "p": "Melyik faluból való a híres hárslevelű?", "s": "Borvidékek és italok", "w": ["Badacsonyból", "Villányból", "Somlóról"]},
  {"a": "Gyümölcsből", "p": "Miből főzik a pálinkát?", "s": "Borvidékek és italok", "w": ["Gabonából", "Cukorrépából", "Cukornádból"]},
  {"a": "Lepárlással", "p": "Hogyan készül a pálinka?", "s": "Borvidékek és italok", "w": ["Préseléssel", "Füstöléssel", "Erjesztéssel"]},
  {"a": "Körtéből", "p": "Melyik gyümölcsből készül a vilmospálinka?", "s": "Borvidékek és italok", "w": ["Sárgabarackból", "Cseresznyéből", "Birsalmából"]},
  {"a": "Keserű", "p": "Milyen ízű az Unicum?", "s": "Borvidékek és italok", "w": ["Sós", "Savanykás", "Édes"]},
  {"a": "Gyógynövényekből", "p": "Miből készül az Unicum?", "s": "Borvidékek és italok", "w": ["Gabonából", "Szőlőből", "Erdei gyümölcsökből"]},
  {"a": "A Zwack családhoz", "p": "Melyik családhoz kötődik az Unicum?", "s": "Borvidékek és italok", "w": ["A Zsolnay családhoz", "A Gundel családhoz", "A Dreher családhoz"]},
  {"a": "Gömbölyű", "p": "Milyen az Unicum üvegének alakja?", "s": "Borvidékek és italok", "w": ["Hosszú", "Négyszögletes", "Lapos"]},
  {"a": "Bor és szóda", "p": "Mi a fröccs?", "s": "Borvidékek és italok", "w": ["Sör és limonádé", "Pálinka és méz", "Bor és gyümölcslé"]},
  {"a": "Hosszúlépés", "p": "Mi az 1 deci bor és 2 deci szóda neve?", "s": "Borvidékek és italok", "w": ["Viceházmester", "Nagyfröccs", "Kisfröccs"]},
  {"a": "Két deci", "p": "Hány deci bor van a nagyfröccsben?", "s": "Borvidékek és italok", "w": ["Egy deci", "Három deci", "Négy deci"]},
  {"a": "A sportfröccsben", "p": "Melyik fröccsben van a legtöbb szóda?", "s": "Borvidékek és italok", "w": ["A nagyfröccsben", "A kisfröccsben", "A viceházmesterben"]},
  {"a": "Fahéjat", "p": "Mit tesznek a forralt borba?", "s": "Borvidékek és italok", "w": ["Majoránnát", "Borsot", "Kaprot"]},
  {"a": "Ősszel", "p": "Mikor szüretelik a szőlőt?", "s": "Borvidékek és italok", "w": ["Télen", "Kora tavasszal", "Nyár elején"]},
  {"a": "Negyven fok körül", "p": "Hány fokos általában a pálinka?", "s": "Borvidékek és italok", "w": ["Öt fok körül", "Tíz fok körül", "Nyolcvan fok körül"]},
  {"a": "Kiszedésre a léből", "p": "Mire használják a szűrőkanalat?", "s": "Konyhai szavak és eszközök", "w": ["Tészta vékony nyújtására", "Hús klopfolására", "Tojás felverésére"]},
  {"a": "Habok felverésére", "p": "Mire való a habverő?", "s": "Konyhai szavak és eszközök", "w": ["Hús darálására", "Tészta szaggatására", "Krumpli hámozására"]},
  {"a": "Nyújtófával", "p": "Mivel nyújtják ki a tésztát?", "s": "Konyhai szavak és eszközök", "w": ["Merőkanállal", "Habverővel", "Szűrőkanállal"]},
  {"a": "Klopfolóval", "p": "Mivel puhítják a hússzeletet?", "s": "Konyhai szavak és eszközök", "w": ["Szűrőkanállal", "Habverővel", "Reszelővel"]},
  {"a": "Merőkanállal", "p": "Mivel szedik ki a levest a fazékból?", "s": "Konyhai szavak és eszközök", "w": ["Késsel", "Tésztaszűrővel", "Villával"]},
  {"a": "Bográcsban", "p": "Milyen edényben főznek a szabadban?", "s": "Konyhai szavak és eszközök", "w": ["Tepsiben", "Kuktában", "Palacsintasütőben"]},
  {"a": "Sütésre", "p": "Mire való a tepsi?", "s": "Konyhai szavak és eszközök", "w": ["Tálalásra", "Hűtésre", "Aprításra"]},
  {"a": "Zárt főzőedény", "p": "Mi a kukta?", "s": "Konyhai szavak és eszközök", "w": ["Lyukas szűrő", "Fából készült kanál", "Nyeles serpenyő"]},
  {"a": "Reszelővel", "p": "Mivel reszelik a sajtot?", "s": "Konyhai szavak és eszközök", "w": ["Nyújtófával", "Habverővel", "Merőkanállal"]},
  {"a": "Keverésre", "p": "Mire való a fakanál?", "s": "Konyhai szavak és eszközök", "w": ["Szeletelésre", "Reszelésre", "Hámozásra"]},
  {"a": "Hagyma párolása", "p": "Mit jelent a dinsztelés?", "s": "Konyhai szavak és eszközök", "w": ["Hús füstölése", "Gyümölcs aszalása", "Tészta nyújtása"]},
  {"a": "Kevés lében főzés", "p": "Mit jelent a párolás?", "s": "Konyhai szavak és eszközök", "w": ["Nyílt lángon pirítás", "Bő olajban sütés", "Hideg vízben áztatás"]},
  {"a": "Enyhe forralás", "p": "Mit jelent az abálás?", "s": "Konyhai szavak és eszközök", "w": ["Nyílt tűzön sütés", "Sóban tartósítás", "Hideg füstölés"]},
  {"a": "Megkelesztik", "p": "Mit csinálnak a kelt tésztával sütés előtt?", "s": "Konyhai szavak és eszközök", "w": ["Lereszelik", "Lefagyasztják", "Felaprítják"]},
  {"a": "Az élesztőtől", "p": "Mitől kel meg a kelt tészta?", "s": "Konyhai szavak és eszközök", "w": ["A cukortól", "A sótól", "A tejfölös habtól"]},
  {"a": "Bundázás", "p": "Mit jelent a panírozás?", "s": "Konyhai szavak és eszközök", "w": ["Savanyítás", "Füstölés", "Aszalás"]},
  {"a": "Szárítás", "p": "Mit jelent az aszalás?", "s": "Konyhai szavak és eszközök", "w": ["Sütés", "Fagyasztás", "Erjesztés"]},
  {"a": "Fűszeres áztatás", "p": "Mit jelent a pácolás?", "s": "Konyhai szavak és eszközök", "w": ["Sütőben pirítás", "Lassú szárítás", "Gyors olajos pirítás"]},
  {"a": "Ízesedik", "p": "Mit csinál a hús a pácban?", "s": "Konyhai szavak és eszközök", "w": ["Megkeményedik", "Megszárad", "Megfagy"]},
  {"a": "A sűrítés", "p": "Mi a rántás célja?", "s": "Konyhai szavak és eszközök", "w": ["A hűtés", "A savanyítás", "Az édesítés"]},
  {"a": "Leöntés forró vízzel", "p": "Mit jelent a forrázás?", "s": "Konyhai szavak és eszközök", "w": ["Sütés forró olajban", "Hűtés jeges vízben", "Szárítás meleg levegőn"]},
  {"a": "Szűrővel", "p": "Mivel szűrik le a főtt tésztát?", "s": "Konyhai szavak és eszközök", "w": ["Húsdarálóval", "Nyújtófával", "Habverővel"]},
  {"a": "Apróra darál", "p": "Mit csinál a húsdaráló?", "s": "Konyhai szavak és eszközök", "w": ["Forrón süt", "Vékonyra nyújt", "Hidegen tárol"]},
  {"a": "Burgonya áttörésére", "p": "Mire való a krumplinyomó?", "s": "Konyhai szavak és eszközök", "w": ["Hús füstölésére", "Tojás felverésére", "Tészta hosszú kelesztésére"]},
  {"a": "Fűszerek törése", "p": "Mi a mozsár feladata?", "s": "Konyhai szavak és eszközök", "w": ["Hús vékony szeletelése", "Leves kavarása", "Tészta sütése"]},
  {"a": "Gyúródeszkán", "p": "Min gyúrják a tésztát?", "s": "Konyhai szavak és eszközök", "w": ["Vágódeszkán", "Tésztaszűrőben", "Sütőpapíron"]},
  {"a": "Elsimított adag", "p": "Mit jelent a csapott evőkanál?", "s": "Konyhai szavak és eszközök", "w": ["Fél kanálnyi adag", "Púpozott adag", "Két kanálnyi adag"]},
  {"a": "Dekagrammot", "p": "Melyik mértékegységet használják a magyar receptek?", "s": "Konyhai szavak és eszközök", "w": ["Köbcentimétert", "Unciát", "Fontot"]},
  {"a": "Dekagramm", "p": "Mit jelent a dkg rövidítés?", "s": "Konyhai szavak és eszközök", "w": ["Deciliter", "Dupla kilogramm", "Dekaliter"]},
  {"a": "Decilitert", "p": "Mit jelent a dl a receptekben?", "s": "Konyhai szavak és eszközök", "w": ["Darabszámot", "Dekalitert", "Dekagrammot"]},
  {"a": "Sütőpapírral", "p": "Mivel bélelik ki a tepsit sütés előtt?", "s": "Konyhai szavak és eszközök", "w": ["Alufóliagolyóval", "Nedves ruhával", "Konyharuhával"]},
  {"a": "A csomók eltűnése", "p": "Mi a szitálás célja?", "s": "Konyhai szavak és eszközök", "w": ["A hús puhítása", "Az ízek keveredése", "A tészta megkelése"]},
  {"a": "Galuska készítésére", "p": "Mire használják a nokedliszaggatót?", "s": "Konyhai szavak és eszközök", "w": ["Tészta nyújtására", "Sajt reszelésére", "Hús apróra darálására"]},
  {"a": "Lapos serpenyő", "p": "Mi a palacsintasütő?", "s": "Konyhai szavak és eszközök", "w": ["Fából készült tál", "Magas fazék", "Lyukas szűrőedény"]},
  {"a": "Tojással", "p": "Mivel kenik meg a kalács tetejét sütés előtt?", "s": "Konyhai szavak és eszközök", "w": ["Ecettel", "Olívaolajjal", "Sós vízzel"]},
  {"a": "Tészta gyúrása", "p": "Mit jelent a dagasztás?", "s": "Konyhai szavak és eszközök", "w": ["Cukor olvasztása", "Hús füstölése", "Zöldség savanyítása"]},
  {"a": "Üvegbe", "p": "Mibe teszik a befőttet télire?", "s": "Konyhai szavak és eszközök", "w": ["Papírzacskóba", "Fémtepsibe", "Vászonzsákba"]},
  {"a": "Dunsztolják", "p": "Mit csinálnak a befőttes üveggel lezárás után?", "s": "Konyhai szavak és eszközök", "w": ["Megsütik", "Lefagyasztják", "Megpirítják"]},
  {"a": "Tepertő kiszedésére", "p": "Mire való a lyukas szűrőkanál a zsírban?", "s": "Konyhai szavak és eszközök", "w": ["Kenyér szeletelésére", "Hagyma aprítására", "Tészta hosszú nyújtására"]},
  {"a": "Megnő sütés előtt", "p": "Mi a kelt tészta fő jellemzője?", "s": "Konyhai szavak és eszközök", "w": ["Ropogós és omlós lesz", "Hidegen dermed meg", "Vékonyra nyújtható"]}
]
$questions$::jsonb)
  with ordinality as question(item, ordinality);

do $validation$
begin
  if (
    select count(*) from public.quiz_questions
    where category_id = 'magyar_konyha' and is_active
  ) <> 306 then
    raise exception 'Magyar konyha must contain exactly 306 active questions';
  end if;

  if exists (
    select 1
    from public.quiz_questions as question
    where question.category_id = 'magyar_konyha'
      and (
        cardinality(question.wrong_answers) <> 3
        or (
          select count(distinct lower(trim(answer)))
          from unnest(question.wrong_answers) as answer
        ) <> 3
        or exists (
          select 1
          from unnest(question.wrong_answers) as answer
          where lower(trim(answer)) = lower(trim(question.correct_answer))
        )
      )
  ) then
    raise exception 'Magyar konyha: every question needs three distinct wrong answers';
  end if;

  if exists (
    select 1
    from public.quiz_questions as proposed
    join public.quiz_questions as existing
      on lower(trim(existing.prompt)) = lower(trim(proposed.prompt))
     and existing.id <> proposed.id
    where proposed.category_id = 'magyar_konyha'
  ) then
    raise exception 'Magyar konyha: a prompt is already used by another question';
  end if;
end;
$validation$;
