-- Insert the complete library in one batch. The wrong answer is derived from the
-- correct one, so the pair is always exactly True and False. The subject labels
-- support later review and balancing without appearing in the UI.
insert into public.quiz_questions (
  id,
  category_id,
  prompt,
  correct_answer,
  wrong_answers,
  language_code,
  grade_level,
  subject,
  display_order,
  is_active
)
select
  'tricky_true_false_' || lpad(question.ordinality::text, 4, '0'),
  'tricky_true_false',
  question.item ->> 'p',
  question.item ->> 'a',
  array[
    case when question.item ->> 'a' = 'True' then 'False' else 'True' end
  ]::text[],
  'en',
  null,
  question.item ->> 's',
  question.ordinality::integer,
  true
from jsonb_array_elements($questions$
[
  {"s": "Animal Myths", "p": "Bats are blind.", "a": "False"},
  {"s": "Animal Myths", "p": "Bananas grow on trees.", "a": "False"},
  {"s": "Animal Myths", "p": "An ostrich buries its head in the sand when it is frightened.", "a": "False"},
  {"s": "Animal Myths", "p": "A goldfish can only remember things for a few seconds.", "a": "False"},
  {"s": "Animal Myths", "p": "A camel's hump is a built-in water tank.", "a": "False"},
  {"s": "Animal Myths", "p": "Every shark must keep swimming or it will drown.", "a": "False"},
  {"s": "Animal Myths", "p": "Dogs see the world only in black and white.", "a": "False"},
  {"s": "Animal Myths", "p": "A bull charges because the colour red enrages it.", "a": "False"},
  {"s": "Animal Myths", "p": "Porcupines shoot their quills through the air at attackers.", "a": "False"},
  {"s": "Animal Myths", "p": "A mother bird will abandon a chick that has been touched by a human.", "a": "False"},
  {"s": "Animal Myths", "p": "An owl can turn its head in a complete circle.", "a": "False"},
  {"s": "Animal Myths", "p": "A starfish has no brain.", "a": "True"},
  {"s": "Animal Myths", "p": "An octopus has three hearts.", "a": "True"},
  {"s": "Animal Myths", "p": "Octopus blood is blue.", "a": "True"},
  {"s": "Animal Myths", "p": "A worker honeybee dies after it stings a person.", "a": "True"},
  {"s": "Animal Myths", "p": "A wasp can sting more than once.", "a": "True"},
  {"s": "Animal Myths", "p": "Only female mosquitoes bite people.", "a": "True"},
  {"s": "Animal Myths", "p": "A housefly lives for only 24 hours.", "a": "False"},
  {"s": "Animal Myths", "p": "Slugs and snails are close relatives.", "a": "True"},
  {"s": "Animal Myths", "p": "Cut an earthworm in half and you get two living worms.", "a": "False"},
  {"s": "Animal Myths", "p": "Sloths move slowly because they are lazy.", "a": "False"},
  {"s": "Animal Myths", "p": "Penguins live at the North Pole.", "a": "False"},
  {"s": "Animal Myths", "p": "Polar bears hunt penguins in the wild.", "a": "False"},
  {"s": "Animal Myths", "p": "A polar bear's hairs are clear rather than white.", "a": "True"},
  {"s": "Animal Myths", "p": "A hippopotamus can outrun a person on land.", "a": "True"},
  {"s": "Animal Myths", "p": "A cat always lands on its feet.", "a": "False"},
  {"s": "Animal Myths", "p": "Chameleons change colour mainly to blend into their surroundings.", "a": "False"},
  {"s": "Animal Myths", "p": "Carrots should make up most of a pet rabbit's diet.", "a": "False"},
  {"s": "Animal Myths", "p": "Honeybees can be trained to recognise human faces.", "a": "True"},
  {"s": "Animal Myths", "p": "A duck's quack does not echo.", "a": "False"},
  {"s": "Animal Myths", "p": "Evidence suggests that fish can feel pain.", "a": "True"},
  {"s": "Animal Myths", "p": "The daddy longlegs is one of the most venomous spiders alive.", "a": "False"},
  {"s": "Animal Myths", "p": "A group of crows is called a murder.", "a": "True"},
  {"s": "Animal Myths", "p": "Snakes dislocate their jaws to swallow large prey.", "a": "False"},
  {"s": "Animal Myths", "p": "An elephant is afraid of mice.", "a": "False"},
  {"s": "Animal Myths", "p": "Woodpeckers get concussions from drumming on trees.", "a": "False"},
  {"s": "Animal Myths", "p": "Lemmings deliberately jump off cliffs in mass suicides.", "a": "False"},
  {"s": "Animal Myths", "p": "A bloodhound can follow a scent trail that is days old.", "a": "True"},
  {"s": "Animal Myths", "p": "Sharks are immune to cancer.", "a": "False"},
  {"s": "Animal Myths", "p": "A snail can sleep for months at a time.", "a": "True"},

  {"s": "The Human Body", "p": "People use only ten percent of their brains.", "a": "False"},
  {"s": "The Human Body", "p": "Sweet, salty, sour and bitter are each detected by one fixed zone of the tongue.", "a": "False"},
  {"s": "The Human Body", "p": "Hair and fingernails keep growing after a person dies.", "a": "False"},
  {"s": "The Human Body", "p": "Cracking your knuckles causes arthritis.", "a": "False"},
  {"s": "The Human Body", "p": "Shaving makes hair grow back thicker.", "a": "False"},
  {"s": "The Human Body", "p": "Humans have exactly five senses.", "a": "False"},
  {"s": "The Human Body", "p": "Blood is blue while it is still inside your veins.", "a": "False"},
  {"s": "The Human Body", "p": "Your heart stops beating when you sneeze.", "a": "False"},
  {"s": "The Human Body", "p": "An adult has fewer bones than a newborn baby.", "a": "True"},
  {"s": "The Human Body", "p": "The small intestine is longer than the large intestine.", "a": "True"},
  {"s": "The Human Body", "p": "A giraffe has the same number of neck bones as a human.", "a": "True"},
  {"s": "The Human Body", "p": "Fingerprints differ even between identical twins.", "a": "True"},
  {"s": "The Human Body", "p": "Most of your body heat escapes through your head.", "a": "False"},
  {"s": "The Human Body", "p": "A strong drink genuinely warms your body up in the cold.", "a": "False"},
  {"s": "The Human Body", "p": "Everybody needs exactly eight glasses of water a day.", "a": "False"},
  {"s": "The Human Body", "p": "Sugar makes children hyperactive.", "a": "False"},
  {"s": "The Human Body", "p": "Reading in dim light permanently damages your eyes.", "a": "False"},
  {"s": "The Human Body", "p": "Sitting close to the television ruins your eyesight.", "a": "False"},
  {"s": "The Human Body", "p": "Most of what you call taste actually comes from your sense of smell.", "a": "True"},
  {"s": "The Human Body", "p": "Goose bumps are left over from ancestors who raised their fur for warmth.", "a": "True"},
  {"s": "The Human Body", "p": "A person can live a normal life without a spleen.", "a": "True"},
  {"s": "The Human Body", "p": "Yawning really is contagious.", "a": "True"},
  {"s": "The Human Body", "p": "Wisdom teeth are the first adult teeth to appear.", "a": "False"},
  {"s": "The Human Body", "p": "Stress and spicy food are the main causes of stomach ulcers.", "a": "False"},
  {"s": "The Human Body", "p": "Vitamin C prevents the common cold.", "a": "False"},
  {"s": "The Human Body", "p": "Cold weather itself gives you a cold.", "a": "False"},
  {"s": "The Human Body", "p": "Antibiotics will cure the flu.", "a": "False"},
  {"s": "The Human Body", "p": "Fingers wrinkle in the bath because the skin soaks up water.", "a": "False"},
  {"s": "The Human Body", "p": "The human eye can distinguish millions of colours.", "a": "True"},
  {"s": "The Human Body", "p": "Your sense of smell is linked to memory more directly than your other senses.", "a": "True"},
  {"s": "The Human Body", "p": "Bones are living tissue that repair themselves.", "a": "True"},
  {"s": "The Human Body", "p": "The strongest muscle in the body is the tongue.", "a": "False"},
  {"s": "The Human Body", "p": "Adults keep making new brain cells.", "a": "True"},
  {"s": "The Human Body", "p": "You can be genuinely allergic to water.", "a": "True"},
  {"s": "The Human Body", "p": "Human beings glow very faintly with their own light.", "a": "True"},
  {"s": "The Human Body", "p": "Your stomach lining replaces itself every few days.", "a": "True"},
  {"s": "The Human Body", "p": "A hiccup is a spasm of the diaphragm.", "a": "True"},
  {"s": "The Human Body", "p": "The lungs are both the same size.", "a": "False"},
  {"s": "The Human Body", "p": "Chewing gum takes seven years to leave your stomach.", "a": "False"},
  {"s": "The Human Body", "p": "Tongue rolling is decided by a single gene you inherit.", "a": "False"},

  {"s": "Space and the Sky", "p": "The Great Wall of China can be seen with the naked eye from the Moon.", "a": "False"},
  {"s": "Space and the Sky", "p": "One side of the Moon never receives any sunlight.", "a": "False"},
  {"s": "Space and the Sky", "p": "The seasons happen because Earth moves closer to and farther from the Sun.", "a": "False"},
  {"s": "Space and the Sky", "p": "The North Star is the brightest star in the night sky.", "a": "False"},
  {"s": "Space and the Sky", "p": "Measured from its own base, Mount Everest is the tallest mountain on Earth.", "a": "False"},
  {"s": "Space and the Sky", "p": "Lightning never strikes the same place twice.", "a": "False"},
  {"s": "Space and the Sky", "p": "There is no gravity in space.", "a": "False"},
  {"s": "Space and the Sky", "p": "The Sun looks white when viewed from space.", "a": "True"},
  {"s": "Space and the Sky", "p": "Earth is closest to the Sun in January.", "a": "True"},
  {"s": "Space and the Sky", "p": "A day on Venus lasts longer than a year on Venus.", "a": "True"},
  {"s": "Space and the Sky", "p": "Venus is hotter than Mercury.", "a": "True"},
  {"s": "Space and the Sky", "p": "Saturn is the only planet in our solar system with rings.", "a": "False"},
  {"s": "Space and the Sky", "p": "The Moon is slowly drifting away from Earth.", "a": "True"},
  {"s": "Space and the Sky", "p": "Space is essentially silent.", "a": "True"},
  {"s": "Space and the Sky", "p": "A shooting star is a star.", "a": "False"},
  {"s": "Space and the Sky", "p": "The Sun is mostly hydrogen.", "a": "True"},
  {"s": "Space and the Sky", "p": "Earth is a perfect sphere.", "a": "False"},
  {"s": "Space and the Sky", "p": "A black hole pulls in everything around it like a vacuum cleaner.", "a": "False"},
  {"s": "Space and the Sky", "p": "The asteroid belt is so crowded that spacecraft must dodge rocks constantly.", "a": "False"},
  {"s": "Space and the Sky", "p": "Astronomers still classify Pluto as a planet.", "a": "False"},
  {"s": "Space and the Sky", "p": "Pluto has not completed one orbit of the Sun since it was discovered.", "a": "True"},
  {"s": "Space and the Sky", "p": "A person exposed to space without a suit would explode instantly.", "a": "False"},
  {"s": "Space and the Sky", "p": "The footprints left on the Moon will last for a very long time.", "a": "True"},
  {"s": "Space and the Sky", "p": "Stars twinkle because of Earth's atmosphere.", "a": "True"},
  {"s": "Space and the Sky", "p": "Jupiter is more massive than all the other planets put together.", "a": "True"},
  {"s": "Space and the Sky", "p": "A space rock is called a meteorite once it reaches the ground.", "a": "True"},
  {"s": "Space and the Sky", "p": "The Moon does not rotate, which is why we always see the same face.", "a": "False"},
  {"s": "Space and the Sky", "p": "A comet's tail always trails behind the direction it is travelling.", "a": "False"},
  {"s": "Space and the Sky", "p": "The Sun will eventually collapse into a black hole.", "a": "False"},
  {"s": "Space and the Sky", "p": "The Sun also helps cause the tides on Earth.", "a": "True"},
  {"s": "Space and the Sky", "p": "There are more stars in the universe than grains of sand on Earth's beaches.", "a": "True"},
  {"s": "Space and the Sky", "p": "Mars appears red because of iron in its dust.", "a": "True"},
  {"s": "Space and the Sky", "p": "The Moon is larger than Pluto.", "a": "True"},
  {"s": "Space and the Sky", "p": "You would age slightly differently on a mountain top than at sea level.", "a": "True"},
  {"s": "Space and the Sky", "p": "The light you see from the Sun left it about eight minutes ago.", "a": "True"},
  {"s": "Space and the Sky", "p": "Neptune was found by mathematics before anyone saw it.", "a": "True"},
  {"s": "Space and the Sky", "p": "The Moon has quakes of its own.", "a": "True"},
  {"s": "Space and the Sky", "p": "Saturn would float if you could place it in a large enough ocean.", "a": "True"},
  {"s": "Space and the Sky", "p": "Every star you can see at night is inside our own galaxy.", "a": "False"},
  {"s": "Space and the Sky", "p": "The solar system's planets all orbit in the same direction.", "a": "True"},

  {"s": "History Myths", "p": "Napoleon Bonaparte was unusually short for a man of his time.", "a": "False"},
  {"s": "History Myths", "p": "Viking warriors wore helmets with horns on them.", "a": "False"},
  {"s": "History Myths", "p": "Albert Einstein failed mathematics at school.", "a": "False"},
  {"s": "History Myths", "p": "An apple fell on Isaac Newton's head and gave him the idea of gravity.", "a": "False"},
  {"s": "History Myths", "p": "Educated Europeans in Columbus's day believed the Earth was flat.", "a": "False"},
  {"s": "History Myths", "p": "Marie Antoinette said 'Let them eat cake'.", "a": "False"},
  {"s": "History Myths", "p": "The people convicted at the Salem witch trials were burned at the stake.", "a": "False"},
  {"s": "History Myths", "p": "Roman gladiator contests almost always ended with a death.", "a": "False"},
  {"s": "History Myths", "p": "The great pyramids of Egypt were built by slave labour.", "a": "False"},
  {"s": "History Myths", "p": "Cleopatra was Egyptian by ancestry.", "a": "False"},
  {"s": "History Myths", "p": "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.", "a": "True"},
  {"s": "History Myths", "p": "The Hundred Years' War lasted exactly one hundred years.", "a": "False"},
  {"s": "History Myths", "p": "Nero fiddled while Rome burned.", "a": "False"},
  {"s": "History Myths", "p": "George Washington had a set of wooden teeth.", "a": "False"},
  {"s": "History Myths", "p": "The American Declaration of Independence was signed by everyone on 4 July 1776.", "a": "False"},
  {"s": "History Myths", "p": "Paul Revere rode through the night shouting 'The British are coming!'", "a": "False"},
  {"s": "History Myths", "p": "It is proven that Betsy Ross sewed the first American flag.", "a": "False"},
  {"s": "History Myths", "p": "Thomas Edison invented the first electric light bulb.", "a": "False"},
  {"s": "History Myths", "p": "Coca-Cola invented the modern red-suited image of Santa Claus.", "a": "False"},
  {"s": "History Myths", "p": "Dr Guillotin invented the guillotine.", "a": "False"},
  {"s": "History Myths", "p": "Ancient Greek marble statues were originally left plain white.", "a": "False"},
  {"s": "History Myths", "p": "Julius Caesar was an emperor of Rome.", "a": "False"},
  {"s": "History Myths", "p": "Christopher Columbus proved to the world that the Earth was round.", "a": "False"},
  {"s": "History Myths", "p": "Christopher Columbus set foot on the mainland of what is now the United States.", "a": "False"},
  {"s": "History Myths", "p": "Benjamin Franklin served as a President of the United States.", "a": "False"},
  {"s": "History Myths", "p": "Coffee was thrown into the harbour at the Boston Tea Party.", "a": "False"},
  {"s": "History Myths", "p": "Norse sailors reached North America centuries before Columbus.", "a": "True"},
  {"s": "History Myths", "p": "A knight in armour was so heavy he had to be winched onto his horse.", "a": "False"},
  {"s": "History Myths", "p": "The 'Iron Maiden' was a common torture device in the Middle Ages.", "a": "False"},
  {"s": "History Myths", "p": "People in the Middle Ages almost never washed.", "a": "False"},
  {"s": "History Myths", "p": "Mozart was buried in a shared grave, as was normal practice in Vienna at the time.", "a": "True"},
  {"s": "History Myths", "p": "Beethoven was profoundly deaf when he composed his Ninth Symphony.", "a": "True"},
  {"s": "History Myths", "p": "Vincent van Gogh cut off his entire ear.", "a": "False"},
  {"s": "History Myths", "p": "The shortest war on record lasted less than an hour.", "a": "True"},
  {"s": "History Myths", "p": "Ancient Rome had a population of over one million people.", "a": "True"},
  {"s": "History Myths", "p": "The Olympic Games of 1896 included women competitors.", "a": "False"},
  {"s": "History Myths", "p": "Oxford University is older than the Aztec empire.", "a": "True"},
  {"s": "History Myths", "p": "The fax machine was invented in the same century as the telephone.", "a": "True"},
  {"s": "History Myths", "p": "Spain and the United States were once at war over Cuba.", "a": "True"},
  {"s": "History Myths", "p": "The Titanic sank on its maiden voyage.", "a": "True"},
  {"s": "History Myths", "p": "The Eiffel Tower was meant to be temporary.", "a": "True"},
  {"s": "History Myths", "p": "The Statue of Liberty was a gift from France.", "a": "True"},
  {"s": "History Myths", "p": "Anne Frank and Martin Luther King Jr were born in the same year.", "a": "True"},
  {"s": "History Myths", "p": "The Second World War ended in Europe and Asia on the same day.", "a": "False"},
  {"s": "History Myths", "p": "Queen Victoria reigned for more than sixty years.", "a": "True"},
  {"s": "History Myths", "p": "The Berlin Wall was built to keep people from leaving East Berlin.", "a": "True"},
  {"s": "History Myths", "p": "Hungary's Rubik's Cube was invented by an architect.", "a": "True"},
  {"s": "History Myths", "p": "The last use of the guillotine in France happened in the same decade as the first Star Wars film.", "a": "True"},
  {"s": "History Myths", "p": "Ancient Egyptians had domesticated cats.", "a": "True"},
  {"s": "History Myths", "p": "The Great Fire of London killed thousands of people.", "a": "False"},

  {"s": "Food and Drink", "p": "A banana is a berry.", "a": "True"},
  {"s": "Food and Drink", "p": "A strawberry is a berry.", "a": "False"},
  {"s": "Food and Drink", "p": "A peanut is a nut.", "a": "False"},
  {"s": "Food and Drink", "p": "A tomato is a fruit.", "a": "True"},
  {"s": "Food and Drink", "p": "Honey can stay edible for thousands of years.", "a": "True"},
  {"s": "Food and Drink", "p": "Eating carrots improves your night vision.", "a": "False"},
  {"s": "Food and Drink", "p": "Carrots were originally purple rather than orange.", "a": "True"},
  {"s": "Food and Drink", "p": "Eating after dark automatically makes you gain weight.", "a": "False"},
  {"s": "Food and Drink", "p": "A microwave cooks food from the inside outwards.", "a": "False"},
  {"s": "Food and Drink", "p": "Food heated in a microwave becomes slightly radioactive.", "a": "False"},
  {"s": "Food and Drink", "p": "Chocolate is poisonous to dogs.", "a": "True"},
  {"s": "Food and Drink", "p": "White chocolate contains no cocoa solids.", "a": "True"},
  {"s": "Food and Drink", "p": "Searing a steak seals the juices inside it.", "a": "False"},
  {"s": "Food and Drink", "p": "Adding salt makes a pot of water boil faster.", "a": "False"},
  {"s": "Food and Drink", "p": "Frozen vegetables can be more nutritious than fresh ones.", "a": "True"},
  {"s": "Food and Drink", "p": "Brown eggs are more nutritious than white eggs.", "a": "False"},
  {"s": "Food and Drink", "p": "The colour of an eggshell depends on the breed of hen.", "a": "True"},
  {"s": "Food and Drink", "p": "Lobster was once considered a poor person's food.", "a": "True"},
  {"s": "Food and Drink", "p": "Tomatoes were once widely feared as poisonous in Europe.", "a": "True"},
  {"s": "Food and Drink", "p": "The potato is native to Ireland.", "a": "False"},
  {"s": "Food and Drink", "p": "Ketchup was once sold as a medicine.", "a": "True"},
  {"s": "Food and Drink", "p": "Decaffeinated coffee contains no caffeine whatsoever.", "a": "False"},
  {"s": "Food and Drink", "p": "Green tea and black tea come from the same plant.", "a": "True"},
  {"s": "Food and Drink", "p": "Cinnamon is the bark of a tree.", "a": "True"},
  {"s": "Food and Drink", "p": "Vanilla comes from an orchid.", "a": "True"},
  {"s": "Food and Drink", "p": "Saffron is the most expensive spice by weight.", "a": "True"},
  {"s": "Food and Drink", "p": "Nutmeg and mace come from the same fruit.", "a": "True"},
  {"s": "Food and Drink", "p": "Most wasabi served in restaurants is not real wasabi.", "a": "True"},
  {"s": "Food and Drink", "p": "Drinking milk makes a cold produce more mucus.", "a": "False"},
  {"s": "Food and Drink", "p": "Apple seeds contain a cyanide compound.", "a": "True"},
  {"s": "Food and Drink", "p": "Rhubarb leaves are poisonous.", "a": "True"},
  {"s": "Food and Drink", "p": "Pineapples grow on trees.", "a": "False"},
  {"s": "Food and Drink", "p": "Peppers are measured for heat on the Scoville scale.", "a": "True"},
  {"s": "Food and Drink", "p": "A cucumber is a fruit.", "a": "True"},
  {"s": "Food and Drink", "p": "Almonds are true nuts.", "a": "False"},
  {"s": "Food and Drink", "p": "Coconut water was once used in emergency medicine.", "a": "True"},
  {"s": "Food and Drink", "p": "Bell peppers and chilli peppers are the same species.", "a": "True"},
  {"s": "Food and Drink", "p": "Cheese is one of the oldest processed foods known.", "a": "True"},
  {"s": "Food and Drink", "p": "Bread was baked before pottery was invented.", "a": "True"},
  {"s": "Food and Drink", "p": "Pasta was brought to Italy from China by Marco Polo.", "a": "False"},
  {"s": "Food and Drink", "p": "The croissant was invented in France.", "a": "False"},
  {"s": "Food and Drink", "p": "Goulash was originally a shepherd's meal.", "a": "True"},
  {"s": "Food and Drink", "p": "Paprika is native to Hungary.", "a": "False"},
  {"s": "Food and Drink", "p": "Fortune cookies were invented in China.", "a": "False"},
  {"s": "Food and Drink", "p": "Pumpkin is technically a fruit.", "a": "True"},
  {"s": "Food and Drink", "p": "Rice is grown in more countries than wheat.", "a": "False"},
  {"s": "Food and Drink", "p": "Olive trees can live for over a thousand years.", "a": "True"},
  {"s": "Food and Drink", "p": "Salt was once used to pay wages.", "a": "True"},
  {"s": "Food and Drink", "p": "Sparkling wine was first made by accident.", "a": "True"},
  {"s": "Food and Drink", "p": "Peanut butter can be turned into a diamond-like material under pressure.", "a": "True"},

  {"s": "Everyday Science", "p": "Glass is really a very slow-moving liquid.", "a": "False"},
  {"s": "Everyday Science", "p": "Old window panes are thicker at the bottom because the glass has flowed downwards.", "a": "False"},
  {"s": "Everyday Science", "p": "A penny dropped from a skyscraper would kill a person below.", "a": "False"},
  {"s": "Everyday Science", "p": "Water spirals down a sink the opposite way in the southern hemisphere.", "a": "False"},
  {"s": "Everyday Science", "p": "A lightning rod stops lightning from striking a building.", "a": "False"},
  {"s": "Everyday Science", "p": "Rubber tyres are what protect you from lightning inside a car.", "a": "False"},
  {"s": "Everyday Science", "p": "Metal conducts cold into your hand.", "a": "False"},
  {"s": "Everyday Science", "p": "Under the right conditions, hot water can freeze faster than cold water.", "a": "True"},
  {"s": "Everyday Science", "p": "Sound travels faster through water than through air.", "a": "True"},
  {"s": "Everyday Science", "p": "Diamond and pencil lead are made of the same element.", "a": "True"},
  {"s": "Everyday Science", "p": "Diamond is the hardest natural material known.", "a": "True"},
  {"s": "Everyday Science", "p": "Bleach and ammonia are safe to mix for cleaning.", "a": "False"},
  {"s": "Everyday Science", "p": "Perfectly pure water is a poor conductor of electricity.", "a": "True"},
  {"s": "Everyday Science", "p": "A compass needle points to the true North Pole.", "a": "False"},
  {"s": "Everyday Science", "p": "Earth's magnetic poles have swapped places in the past.", "a": "True"},
  {"s": "Everyday Science", "p": "Antarctica is classified as a desert.", "a": "True"},
  {"s": "Everyday Science", "p": "The Sahara is the largest desert on Earth.", "a": "False"},
  {"s": "Everyday Science", "p": "Aluminium was once more precious than gold.", "a": "True"},
  {"s": "Everyday Science", "p": "Bubble wrap was first sold as wallpaper.", "a": "True"},
  {"s": "Everyday Science", "p": "The microwave oven was discovered by accident.", "a": "True"},
  {"s": "Everyday Science", "p": "Sound cannot travel through solid objects.", "a": "False"},
  {"s": "Everyday Science", "p": "Ice is less dense than the water it floats in.", "a": "True"},
  {"s": "Everyday Science", "p": "Stainless steel can still rust.", "a": "True"},
  {"s": "Everyday Science", "p": "Pure gold does not tarnish.", "a": "True"},
  {"s": "Everyday Science", "p": "A bolt of lightning is hotter than the surface of the Sun.", "a": "True"},
  {"s": "Everyday Science", "p": "Raindrops are shaped like teardrops as they fall.", "a": "False"},
  {"s": "Everyday Science", "p": "You lose weight simply by breathing out.", "a": "True"},
  {"s": "Everyday Science", "p": "Helium can escape Earth's atmosphere into space.", "a": "True"},
  {"s": "Everyday Science", "p": "Hot air rises because it is less dense than cool air.", "a": "True"},
  {"s": "Everyday Science", "p": "A vacuum flask works because a vacuum is a poor conductor of heat.", "a": "True"},
  {"s": "Everyday Science", "p": "Water is the only substance on Earth found naturally as solid, liquid and gas.", "a": "False"},
  {"s": "Everyday Science", "p": "Boiling water always reaches 100 degrees Celsius, whatever the altitude.", "a": "False"},
  {"s": "Everyday Science", "p": "Bananas are slightly radioactive.", "a": "True"},
  {"s": "Everyday Science", "p": "The human body contains enough carbon to make pencil lead.", "a": "True"},
  {"s": "Everyday Science", "p": "Glass can be made from sand.", "a": "True"},
  {"s": "Everyday Science", "p": "A microwave heats food by making water molecules move.", "a": "True"},
  {"s": "Everyday Science", "p": "Cold fusion has been reliably demonstrated in laboratories.", "a": "False"},
  {"s": "Everyday Science", "p": "Rubber is made from a tree sap in its natural form.", "a": "True"},
  {"s": "Everyday Science", "p": "Soap kills germs by dissolving their outer layer.", "a": "True"},
  {"s": "Everyday Science", "p": "Static electricity is more common in dry air.", "a": "True"},

  {"s": "Around the World", "p": "Russia spans eleven time zones.", "a": "True"},
  {"s": "Around the World", "p": "Australia is wider than the Moon.", "a": "True"},
  {"s": "Around the World", "p": "Greenland is larger than Africa.", "a": "False"},
  {"s": "Around the World", "p": "Alaska is both the westernmost and the easternmost state of the United States.", "a": "True"},
  {"s": "Around the World", "p": "Istanbul stands on two continents.", "a": "True"},
  {"s": "Around the World", "p": "Iceland is mostly covered by ice.", "a": "False"},
  {"s": "Around the World", "p": "The Dead Sea is really a lake.", "a": "True"},
  {"s": "Around the World", "p": "Hungary has a short stretch of coastline.", "a": "False"},
  {"s": "Around the World", "p": "Hungary once had access to the sea.", "a": "True"},
  {"s": "Around the World", "p": "The Danube flows through more countries than any other river.", "a": "True"},
  {"s": "Around the World", "p": "The capital of Australia is Sydney.", "a": "False"},
  {"s": "Around the World", "p": "There are more ancient pyramids in Sudan than in Egypt.", "a": "True"},

  {"s": "Words and Numbers", "p": "The correct plural of 'octopus' must be 'octopi'.", "a": "False"},
  {"s": "Words and Numbers", "p": "A billion has always meant the same number in every country.", "a": "False"},
  {"s": "Words and Numbers", "p": "Roman numerals include a symbol for zero.", "a": "False"},
  {"s": "Words and Numbers", "p": "Hungarian and Finnish belong to the same language family.", "a": "True"},
  {"s": "Words and Numbers", "p": "In Hungarian, the family name comes before the given name.", "a": "True"},
  {"s": "Words and Numbers", "p": "English has more native speakers than any other language.", "a": "False"},
  {"s": "Words and Numbers", "p": "The word 'nice' once meant foolish or ignorant.", "a": "True"},
  {"s": "Words and Numbers", "p": "Pi has been calculated exactly.", "a": "False"},

  {"s": "Arts and Entertainment", "p": "The Mona Lisa is a very large painting.", "a": "False"},
  {"s": "Arts and Entertainment", "p": "The Mona Lisa has no visible eyebrows.", "a": "True"},
  {"s": "Arts and Entertainment", "p": "Vincent van Gogh was celebrated as a great painter during his lifetime.", "a": "False"},
  {"s": "Arts and Entertainment", "p": "Sherlock Holmes says 'Elementary, my dear Watson' in the original stories.", "a": "False"},
  {"s": "Arts and Entertainment", "p": "Darth Vader says 'Luke, I am your father' in the film.", "a": "False"},
  {"s": "Arts and Entertainment", "p": "The song 'Happy Birthday to You' was still under copyright in the 21st century.", "a": "True"},
  {"s": "Arts and Entertainment", "p": "Silent films were usually shown without any sound in the cinema.", "a": "False"},
  {"s": "Arts and Entertainment", "p": "'Frankenstein' was written by a teenager.", "a": "True"},

  {"s": "Inventions and Everyday Life", "p": "A marathon is exactly 42 kilometres long.", "a": "False"},
  {"s": "Inventions and Everyday Life", "p": "The Olympic flame has burned without interruption since ancient Greece.", "a": "False"},
  {"s": "Inventions and Everyday Life", "p": "An American dollar bill is made of paper.", "a": "False"},
  {"s": "Inventions and Everyday Life", "p": "The ridges on the edge of a coin are purely decorative.", "a": "False"},
  {"s": "Inventions and Everyday Life", "p": "Electronic mail existed before the World Wide Web.", "a": "True"},
  {"s": "Inventions and Everyday Life", "p": "'Wi-Fi' is short for 'Wireless Fidelity'.", "a": "False"},
  {"s": "Inventions and Everyday Life", "p": "'SOS' stands for 'Save Our Ship'.", "a": "False"},
  {"s": "Inventions and Everyday Life", "p": "The first item ever sold on eBay was a broken laser pointer.", "a": "True"},
  {"s": "Inventions and Everyday Life", "p": "The '@' symbol is older than email.", "a": "True"},
  {"s": "Inventions and Everyday Life", "p": "An early computer fault was traced to a real moth inside the machine.", "a": "True"},
  {"s": "Inventions and Everyday Life", "p": "The first computer programmer is widely considered to have been a woman.", "a": "True"},
  {"s": "Inventions and Everyday Life", "p": "The typewriter was invented before the telephone.", "a": "True"}
]
$questions$::jsonb) with ordinality as question(item, ordinality);

do $validation$
begin
  if (
    select count(*)
    from public.quiz_questions
    where category_id = 'tricky_true_false'
      and is_active
  ) <> 300 then
    raise exception 'Tricky True or False must contain exactly 300 active questions';
  end if;

  if exists (
    select 1
    from public.quiz_questions as question
    where question.category_id = 'tricky_true_false'
      and (
        cardinality(question.wrong_answers) <> 1
        or question.correct_answer not in ('True', 'False')
        or question.wrong_answers[1] = question.correct_answer
      )
  ) then
    raise exception 'Every Tricky True or False question needs one opposing True/False answer';
  end if;

  -- A guessable category is no fun: keep the two answers close to an even split.
  if (
    select count(*)
    from public.quiz_questions
    where category_id = 'tricky_true_false'
      and correct_answer = 'True'
  ) not between 130 and 170 then
    raise exception 'Tricky True or False must stay near an even True/False balance';
  end if;

  if exists (
    select 1
    from public.quiz_questions as proposed
    join public.quiz_questions as existing
      on lower(trim(existing.prompt)) = lower(trim(proposed.prompt))
     and existing.id <> proposed.id
    where proposed.category_id = 'tricky_true_false'
  ) then
    raise exception 'Tricky True or False contains a prompt already used by another question';
  end if;
end;
$validation$;
