-- Természet és tudomány: 519 questions in Hungarian.
--
-- Written so the correct answer is never the longest option -- the tell that
-- made the Psychology bank guessable without reading the prompt. All four
-- choices share one type and grammatical form.
insert into public.quiz_questions (
  id,
  category_id,
  prompt,
  correct_answer,
  wrong_answers,
  language_code,
  grade_level,
  subject,
  display_order,
  is_active
)
select
  'magyar_tudomany_' || lpad(question.ordinality::text, 4, '0'),
  'magyar_tudomany',
  question.item ->> 'p',
  question.item ->> 'a',
  array(select jsonb_array_elements_text(question.item -> 'w')),
  'hu',
  null,
  question.item ->> 's',
  question.ordinality::integer,
  true
from jsonb_array_elements($questions$
[
  {"a": "A kék bálna", "p": "Melyik a legnagyobb ma élő állat?", "s": "Emlősök", "w": ["Az afrikai elefánt", "Az ámbráscet", "A cetcápa"]},
  {"a": "A zsiráf", "p": "Melyik a legmagasabb szárazföldi állat?", "s": "Emlősök", "w": ["Az afrikai elefánt", "A teve", "A strucc"]},
  {"a": "A gepárd", "p": "Melyik a leggyorsabb szárazföldi állat?", "s": "Emlősök", "w": ["Az antilop", "Az oroszlán", "A ló"]},
  {"a": "Az óriáspanda", "p": "Melyik állat táplálkozik szinte csak bambusszal?", "s": "Emlősök", "w": ["A koala", "A lajhár", "A gyűrűsfarkú maki"]},
  {"a": "Négy", "p": "Hány gyomorrésze van a tehénnek?", "s": "Emlősök", "w": ["Kettő", "Egy", "Hat"]},
  {"a": "A denevér", "p": "Melyik emlős tud igazán repülni?", "s": "Emlősök", "w": ["A repülő mókus", "A lajhár", "A vakond"]},
  {"a": "Rovarokat", "p": "Mit eszik a denevérek nagy része?", "s": "Emlősök", "w": ["Gyümölcsöket", "Halakat", "Magvakat"]},
  {"a": "A lajhár", "p": "Melyik állat alszik a nap nagy részében a fán?", "s": "Emlősök", "w": ["A mosómedve", "A borz", "A vidra"]},
  {"a": "Az elefánt", "p": "Melyik a legnagyobb szárazföldi állat?", "s": "Emlősök", "w": ["Az orrszarvú", "A víziló", "A zsiráf"]},
  {"a": "A testét", "p": "Mit hűt le az elefánt a nagy fülével?", "s": "Emlősök", "w": ["A lábát", "Az ormányát", "A hátát"]},
  {"a": "A hód", "p": "Melyik állat épít gátat a patakon?", "s": "Emlősök", "w": ["A vidra", "A pézsmapocok", "A nutria"]},
  {"a": "Hanggal", "p": "Mivel tájékozódik a denevér a sötétben?", "s": "Emlősök", "w": ["Szaglással", "Látással", "Tapintással"]},
  {"a": "A jegesmedve", "p": "Melyik a legnagyobb szárazföldi ragadozó?", "s": "Emlősök", "w": ["A barnamedve", "A szibériai tigris", "Az oroszlán"]},
  {"a": "Fókával", "p": "Mivel táplálkozik főként a jegesmedve?", "s": "Emlősök", "w": ["Hallal", "Rénszarvassal", "Bogyókkal"]},
  {"a": "Zsír", "p": "Mi van a teve púpjában?", "s": "Emlősök", "w": ["Víz", "Izom", "Csontvelő"]},
  {"a": "A vízidisznó", "p": "Melyik a legnagyobb rágcsáló?", "s": "Emlősök", "w": ["A hód", "A pézsmapocok", "A mormota"]},
  {"a": "Tojással", "p": "Hogyan szaporodik a kacsacsőrű emlős?", "s": "Emlősök", "w": ["Elevenszüléssel", "Osztódással", "Bimbózással"]},
  {"a": "A zsírréteg", "p": "Mi védi a fókát a hideg víztől?", "s": "Emlősök", "w": ["A tollazat", "A vastag bunda", "A pikkely"]},
  {"a": "A farkas", "p": "Melyik állat él falkában?", "s": "Emlősök", "w": ["A tigris", "A leopárd", "A jegesmedve"]},
  {"a": "A gepárd", "p": "Melyik nagymacska nem tud üvölteni?", "s": "Emlősök", "w": ["Az oroszlán", "A tigris", "A leopárd"]},
  {"a": "A tigris", "p": "Melyik a legnagyobb nagymacska?", "s": "Emlősök", "w": ["Az oroszlán", "A jaguár", "A leopárd"]},
  {"a": "A rágcsálók", "p": "Melyik állatcsoport fogai egész életében nőnek?", "s": "Emlősök", "w": ["A ragadozók", "A patások", "A főemlősök"]},
  {"a": "A lóé", "p": "Melyik állat kicsinye a csikó?", "s": "Emlősök", "w": ["A tehéné", "A juhé", "A szamáré"]},
  {"a": "Keratinból", "p": "Miből van az orrszarvú szarva?", "s": "Emlősök", "w": ["Csontból", "Elefántcsontból", "Porcból"]},
  {"a": "A medve", "p": "Melyik állat alszik téli álmot a barlangban?", "s": "Emlősök", "w": ["A farkas", "A hiúz", "A róka"]},
  {"a": "Az ámbráscet", "p": "Melyik cet merül a legmélyebbre a zsákmányáért?", "s": "Emlősök", "w": ["A kék bálna", "A barázdásbálna", "A grönlandi bálna"]},
  {"a": "A grönlandi bálna", "p": "Melyik emlős él a legtovább?", "s": "Emlősök", "w": ["Az afrikai elefánt", "A víziló", "Az ember"]},
  {"a": "Egyensúlyozásra", "p": "Mire használja a kenguru a farkát?", "s": "Emlősök", "w": ["Ásásra", "Táplálékszerzésre", "Úszásra"]},
  {"a": "Erszényben", "p": "Hol hordja kicsinyét a kenguru?", "s": "Emlősök", "w": ["A hátán", "A szájában", "A farka alatt"]},
  {"a": "Állandó", "p": "Milyen a delfinek testhőmérséklete?", "s": "Emlősök", "w": ["Változó", "Hideg", "A vízzel azonos"]},
  {"a": "Tüdővel", "p": "Mivel lélegzik a bálna?", "s": "Emlősök", "w": ["Kopoltyúval", "Bőrén át", "Légzsákkal"]},
  {"a": "Egyen", "p": "Hány ujjon jár a ló?", "s": "Emlősök", "w": ["Kettőn", "Hármon", "Négyen"]},
  {"a": "Az emlősök", "p": "Melyik állatcsoportba tartozik a bálna?", "s": "Emlősök", "w": ["A halak", "A hüllők", "A kétéltűek"]},
  {"a": "Tejjel", "p": "Mivel táplálja kicsinyét minden emlős?", "s": "Emlősök", "w": ["Hússal", "Rovarokkal", "Magvakkal"]},
  {"a": "A szaglása", "p": "Melyik érzékszerve a legfejlettebb a kutyának?", "s": "Emlősök", "w": ["A látása", "A tapintása", "Az ízlelése"]},
  {"a": "A ló", "p": "Melyik állat alszik állva is?", "s": "Emlősök", "w": ["A macska", "A kutya", "A mókus"]},
  {"a": "A juhé", "p": "Melyik állat kicsinye a bárány?", "s": "Emlősök", "w": ["A kecskéé", "A szarvasé", "A tehéné"]},
  {"a": "22 hónapig", "p": "Meddig tart az elefánt vemhessége?", "s": "Emlősök", "w": ["9 hónapig", "12 hónapig", "30 hónapig"]},
  {"a": "A delfin", "p": "Melyik emlős tölti egész életét a vízben?", "s": "Emlősök", "w": ["A fóka", "A vidra", "A jegesmedve"]},
  {"a": "A gorilla", "p": "Melyik a legnagyobb főemlős?", "s": "Emlősök", "w": ["A csimpánz", "Az orangután", "A pávián"]},
  {"a": "A strucc", "p": "Melyik a legnagyobb ma élő madár?", "s": "Madarak", "w": ["Az albatrosz", "Az emu", "A kondor"]},
  {"a": "A struccé", "p": "Melyik madár tojása a legnagyobb?", "s": "Madarak", "w": ["A pelikáné", "A hattyúé", "A pingviné"]},
  {"a": "A pingvin", "p": "Melyik madár úszik, de nem repül?", "s": "Madarak", "w": ["A hattyú", "A vadkacsa", "A kárókatona"]},
  {"a": "A vándorsólyom", "p": "Melyik madár a leggyorsabb zuhanórepülésben?", "s": "Madarak", "w": ["A kerecsensólyom", "A fecske", "A sas"]},
  {"a": "Nektárral", "p": "Mivel táplálkozik főként a kolibri?", "s": "Madarak", "w": ["Magvakkal", "Rovarokkal", "Gyümölcsökkel"]},
  {"a": "A kolibri", "p": "Melyik madár tud hátrafelé repülni?", "s": "Madarak", "w": ["A fecske", "A veréb", "A pacsirta"]},
  {"a": "A gólya", "p": "Melyik madár repül ősszel Afrikába?", "s": "Madarak", "w": ["A veréb", "A széncinege", "A holló"]},
  {"a": "Kéményre", "p": "Hova építi fészkét a gólya?", "s": "Madarak", "w": ["Fa odvába", "Nádasba", "Sziklafalra"]},
  {"a": "A kakukk", "p": "Melyik madár más fészkébe rakja a tojását?", "s": "Madarak", "w": ["A szajkó", "A seregély", "A rigó"]},
  {"a": "A bagoly", "p": "Melyik madár vadászik éjszaka?", "s": "Madarak", "w": ["A vércse", "A karvaly", "A sas"]},
  {"a": "A tollak cseréje", "p": "Mit jelent a madarak vedlése?", "s": "Madarak", "w": ["A fészekrakás", "A párkeresés", "A vonulás kezdete"]},
  {"a": "A papagáj", "p": "Melyik madár utánozza az emberi beszédet?", "s": "Madarak", "w": ["A galamb", "A fácán", "A gyöngytyúk"]},
  {"a": "A galamb", "p": "Melyik madár a béke jelképe?", "s": "Madarak", "w": ["A sas", "A pelikán", "A hattyú"]},
  {"a": "A harkály", "p": "Melyik madár kopogtatja a fatörzset?", "s": "Madarak", "w": ["A cinege", "A csuszka", "A fakusz"]},
  {"a": "A tápláléktól", "p": "Mitől rózsaszín a flamingó tolla?", "s": "Madarak", "w": ["A naptól", "A sós víztől", "A meleg éghajlattól"]},
  {"a": "A varjúféléket", "p": "Melyik madárcsoportot tartják a legokosabbnak?", "s": "Madarak", "w": ["A galambféléket", "A récéket", "A tyúkféléket"]},
  {"a": "Egeret", "p": "Mit eszik a bagoly leggyakrabban?", "s": "Madarak", "w": ["Halat", "Magvakat", "Gyümölcsöt"]},
  {"a": "Üreges", "p": "Milyen a madarak csontja?", "s": "Madarak", "w": ["Tömör", "Porcos", "Rugalmas"]},
  {"a": "A kakasé", "p": "Melyik madár hangja a kukorékolás?", "s": "Madarak", "w": ["A tyúké", "A pulykáé", "A gyöngytyúké"]},
  {"a": "A lúdéval", "p": "Melyik madár tollával írtak régen?", "s": "Madarak", "w": ["A tyúkéval", "A hattyúéval", "A pávaéval"]},
  {"a": "A páváé", "p": "Melyik madár farktolla a legszebb?", "s": "Madarak", "w": ["A fácáné", "A galambé", "A sasé"]},
  {"a": "A kolibri", "p": "Melyik a legkisebb madár?", "s": "Madarak", "w": ["A veréb", "A királyka", "A cinege"]},
  {"a": "A toll", "p": "Mi borítja a madarak testét?", "s": "Madarak", "w": ["A szőr", "A pikkely", "A páncél"]},
  {"a": "A bagolyé", "p": "Melyik madár feje fordul szinte körbe?", "s": "Madarak", "w": ["A sasé", "A gólyáé", "A vándorsólyomé"]},
  {"a": "A kárókatona", "p": "Melyik madár úszik a víz alatt halakért?", "s": "Madarak", "w": ["A gólya", "A daru", "A nagy kócsag"]},
  {"a": "Hajnalban", "p": "Mikor énekelnek legtöbbet az énekesmadarak?", "s": "Madarak", "w": ["Délben", "Éjszaka", "Alkonyatkor"]},
  {"a": "Nyolc", "p": "Hány lába van a pókoknak?", "s": "Hüllők, halak, rovarok", "w": ["Hat", "Tíz", "Tizenkettő"]},
  {"a": "Hat", "p": "Hány lába van a rovaroknak?", "s": "Hüllők, halak, rovarok", "w": ["Nyolc", "Négy", "Tíz"]},
  {"a": "A méh", "p": "Melyik rovar készít mézet?", "s": "Hüllők, halak, rovarok", "w": ["A darázs", "A lódarázs", "A hangya"]},
  {"a": "Nektárból", "p": "Miből készül a méz?", "s": "Hüllők, halak, rovarok", "w": ["Virágporból", "Harmatból", "Gyantából"]},
  {"a": "Légcsövekkel", "p": "Mivel lélegeznek a rovarok?", "s": "Hüllők, halak, rovarok", "w": ["Tüdővel", "Kopoltyúval", "A bőrükön át"]},
  {"a": "Lepke", "p": "Mi lesz a hernyóból?", "s": "Hüllők, halak, rovarok", "w": ["Bogár", "Szitakötő", "Szöcske"]},
  {"a": "A bábban", "p": "Miben alakul át a hernyó lepkévé?", "s": "Hüllők, halak, rovarok", "w": ["A tojásban", "A fészekben", "A gubacsban"]},
  {"a": "A szúnyog", "p": "Melyik rovar zümmög a fülünk mellett nyáron?", "s": "Hüllők, halak, rovarok", "w": ["A méh", "A bogár", "A szitakötő"]},
  {"a": "A nőstény", "p": "Melyik szúnyog szívja a vért?", "s": "Hüllők, halak, rovarok", "w": ["A hím", "Mindkettő", "Csak a fiatal"]},
  {"a": "Világít", "p": "Mit tesz a szentjánosbogár éjjel?", "s": "Hüllők, halak, rovarok", "w": ["Énekel", "Alszik", "Fészket épít"]},
  {"a": "Kettő", "p": "Hány szárnya van a légynek?", "s": "Hüllők, halak, rovarok", "w": ["Négy", "Hat", "Nyolc"]},
  {"a": "A pók", "p": "Melyik állat szövi a hálót?", "s": "Hüllők, halak, rovarok", "w": ["A hangya", "A bogár", "A lepke"]},
  {"a": "Növényt", "p": "Mit eszik a sáska?", "s": "Hüllők, halak, rovarok", "w": ["Húst", "Rovart", "Kisebb állatokat"]},
  {"a": "A kígyó", "p": "Melyik állat vedli le a bőrét egészben?", "s": "Hüllők, halak, rovarok", "w": ["A béka", "A hal", "A teknős"]},
  {"a": "A nyelvével", "p": "Mivel érzékeli a kígyó a szagokat?", "s": "Hüllők, halak, rovarok", "w": ["A fülével", "A farkával", "A pikkelyeivel"]},
  {"a": "A hálós piton", "p": "Melyik a leghosszabb kígyó?", "s": "Hüllők, halak, rovarok", "w": ["A zöld anakonda", "A kobra", "A királykobra"]},
  {"a": "A teknős", "p": "Melyik hüllő él a leghosszabb ideig?", "s": "Hüllők, halak, rovarok", "w": ["A kígyó", "A gyík", "A krokodil"]},
  {"a": "A páncél", "p": "Mi védi a teknős testét?", "s": "Hüllők, halak, rovarok", "w": ["A pikkely", "A szőr", "A kemény bőr"]},
  {"a": "A kaméleon", "p": "Melyik állat tud színt váltani?", "s": "Hüllők, halak, rovarok", "w": ["A gekkó", "A leguán", "A vízisikló"]},
  {"a": "Változó", "p": "Milyen a hüllők testhőmérséklete?", "s": "Hüllők, halak, rovarok", "w": ["Állandó", "Mindig meleg", "Mindig hideg"]},
  {"a": "Kopoltyúval", "p": "Mivel lélegzik a hal?", "s": "Hüllők, halak, rovarok", "w": ["Tüdővel", "Bőrén át", "Az úszóhólyaggal"]},
  {"a": "Az úszóhólyag", "p": "Mi segíti a halat a lebegésben?", "s": "Hüllők, halak, rovarok", "w": ["A kopoltyú", "A farokúszó", "Az oldalvonal"]},
  {"a": "A cetcápa", "p": "Melyik a legnagyobb hal?", "s": "Hüllők, halak, rovarok", "w": ["A kék bálna", "A fehér cápa", "A tonhal"]},
  {"a": "Egy", "p": "Hány szíve van a halnak?", "s": "Hüllők, halak, rovarok", "w": ["Kettő", "Három", "Négy"]},
  {"a": "A lazac", "p": "Melyik hal úszik fel a folyón ívni?", "s": "Hüllők, halak, rovarok", "w": ["A ponty", "A csuka", "A harcsa"]},
  {"a": "A fehér cápa", "p": "Melyik a legnagyobb ragadozó hal?", "s": "Hüllők, halak, rovarok", "w": ["A kék cápa", "A kardhal", "Az óriáscápa"]},
  {"a": "Pikkely", "p": "Mi borítja a legtöbb hal testét?", "s": "Hüllők, halak, rovarok", "w": ["Szőr", "Toll", "Kemény páncél"]},
  {"a": "Hideg patakban", "p": "Hol él szívesen a pisztráng?", "s": "Hüllők, halak, rovarok", "w": ["Meleg tóban", "Sós tengerben", "Iszapos árokban"]},
  {"a": "A hangya", "p": "Melyik rovar épít bolyt a földbe?", "s": "Hüllők, halak, rovarok", "w": ["A méh", "A lepke", "A szitakötő"]},
  {"a": "Élelmet", "p": "Mit gyűjt a hangya a bolyba?", "s": "Hüllők, halak, rovarok", "w": ["Vizet", "Köveket", "Falevelet"]},
  {"a": "A szúnyog", "p": "Melyik rovar terjeszti a maláriát?", "s": "Hüllők, halak, rovarok", "w": ["A légy", "A bolha", "A kullancs"]},
  {"a": "A kullancs", "p": "Melyik állat terjeszti a Lyme-kórt?", "s": "Hüllők, halak, rovarok", "w": ["A szúnyog", "A bolha", "A házi légy"]},
  {"a": "Petézik", "p": "Mit csinál a béka a tóban tavasszal?", "s": "Hüllők, halak, rovarok", "w": ["Vedlik", "Alszik", "Fészket rak"]},
  {"a": "Kétéltű", "p": "Milyen állat a béka?", "s": "Hüllők, halak, rovarok", "w": ["Hüllő", "Emlős", "Ízeltlábú"]},
  {"a": "Béka", "p": "Mi lesz az ebihalból?", "s": "Hüllők, halak, rovarok", "w": ["Hal", "Gyík", "Szitakötő"]},
  {"a": "A házát", "p": "Mit visz magával a csiga a hátán?", "s": "Hüllők, halak, rovarok", "w": ["A petéit", "Az élelmét", "A kicsinyeit"]},
  {"a": "A kaméleoné", "p": "Melyik állat nyelve hosszabb a fejénél?", "s": "Hüllők, halak, rovarok", "w": ["A gyíké", "A kígyóé", "A krokodilé"]},
  {"a": "Tíz", "p": "Hány lába van a ráknak?", "s": "Hüllők, halak, rovarok", "w": ["Hat", "Nyolc", "Tizenkettő"]},
  {"a": "A selyemhernyó", "p": "Melyik állat készíti a selymet?", "s": "Hüllők, halak, rovarok", "w": ["A pók", "A méh", "A szentjánosbogár"]},
  {"a": "Négy", "p": "Hány szárnya van a méhnek?", "s": "Hüllők, halak, rovarok", "w": ["Kettő", "Hat", "Nyolc"]},
  {"a": "A békáé", "p": "Melyik állat hangja a brekegés?", "s": "Hüllők, halak, rovarok", "w": ["A gyíké", "A halé", "A teknősé"]},
  {"a": "Levéltetűt", "p": "Mit eszik a katicabogár?", "s": "Hüllők, halak, rovarok", "w": ["Virágport", "Falevelet", "Apró magvakat"]},
  {"a": "A méh", "p": "Melyik rovar pusztul el a csípés után?", "s": "Hüllők, halak, rovarok", "w": ["A darázs", "A szúnyog", "A lódarázs"]},
  {"a": "Oxigént", "p": "Milyen gázt bocsát ki a növény a fotoszintézis során?", "s": "Növények", "w": ["Szén-dioxidot", "Nitrogént", "Vízgőzt"]},
  {"a": "Szén-dioxidot", "p": "Milyen gázt vesz fel a növény a fotoszintézishez?", "s": "Növények", "w": ["Oxigént", "Nitrogént", "Szén-monoxidot"]},
  {"a": "Fényre", "p": "Mire van szüksége a fotoszintézishez a növénynek?", "s": "Növények", "w": ["Sötétre", "Hidegre", "Sós vízre"]},
  {"a": "A klorofill", "p": "Melyik zöld festék végzi a fotoszintézist?", "s": "Növények", "w": ["A keményítő", "A karotin", "A cellulóz"]},
  {"a": "A gyökér", "p": "Melyik növényi rész szívja fel a vizet?", "s": "Növények", "w": ["A levél", "A virág", "A termés"]},
  {"a": "A szár", "p": "Mi szállítja a vizet a levelekhez?", "s": "Növények", "w": ["A virág", "A termés", "A gyökérszőr"]},
  {"a": "A virágból", "p": "Melyik növényi részből lesz a termés?", "s": "Növények", "w": ["A levélből", "A gyökérből", "A szárból"]},
  {"a": "Beporoz", "p": "Mit csinál a méh a virágban?", "s": "Növények", "w": ["Fészkel", "Alszik", "Petét rak"]},
  {"a": "A fenyő", "p": "Melyik fa marad zöld télen is?", "s": "Növények", "w": ["A tölgy", "A nyírfa", "A gesztenyefa"]},
  {"a": "Makkot", "p": "Mit terem a tölgyfa?", "s": "Növények", "w": ["Gesztenyét", "Mogyorót", "Diót"]},
  {"a": "A nyírfáét", "p": "Melyik fa törzsét borítja fehér kéreg?", "s": "Növények", "w": ["A tölgyét", "A fenyőét", "A gesztenyefáét"]},
  {"a": "Az évgyűrűkből", "p": "Miből tudjuk meg a kivágott fa korát?", "s": "Növények", "w": ["A levelekből", "A magasságból", "A kéreg színéből"]},
  {"a": "A búzából", "p": "Melyik növényből készül a kenyér?", "s": "Növények", "w": ["A kukoricából", "A rizsből", "A zabból"]},
  {"a": "A cukorrépából", "p": "Melyik növényből nyerik a cukrot a hűvös éghajlaton?", "s": "Növények", "w": ["A cukornádból", "A kukoricából", "A burgonyafélékből"]},
  {"a": "Termés", "p": "Mi a paradicsom a növénytan szerint?", "s": "Növények", "w": ["Gyökér", "Levél", "Módosult szár"]},
  {"a": "A gumót", "p": "Melyik növényi részt esszük a burgonyánál?", "s": "Növények", "w": ["A gyökeret", "A termést", "A levelet"]},
  {"a": "A gyökerét", "p": "Melyik növényi részt esszük a sárgarépánál?", "s": "Növények", "w": ["A szárát", "A levelét", "A termését"]},
  {"a": "Három", "p": "Hány levele van a lóherének általában?", "s": "Növények", "w": ["Négy", "Kettő", "Öt"]},
  {"a": "A napraforgó", "p": "Melyik virág fordul a nap felé?", "s": "Növények", "w": ["A tulipán", "A rózsa", "A gyöngyvirág"]},
  {"a": "Olajat", "p": "Mit sajtolnak a napraforgó magjából?", "s": "Növények", "w": ["Lisztet", "Cukrot", "Keményítőt"]},
  {"a": "A bambusz", "p": "Melyik növény szára üreges és gyorsan nő?", "s": "Növények", "w": ["A tölgy", "A pálma", "A gesztenyefa"]},
  {"a": "A szárában", "p": "Hol tárolja a kaktusz a vizet?", "s": "Növények", "w": ["A tüskéiben", "A gyökerében", "A virágában"]},
  {"a": "Módosult levél", "p": "Mi a kaktusz tüskéje valójában?", "s": "Növények", "w": ["Módosult gyökér", "Módosult virág", "Kemény kéregdarab"]},
  {"a": "A tavirózsa", "p": "Melyik növény úszik a tó felszínén?", "s": "Növények", "w": ["A nádas", "A sás", "A vízipáfrány"]},
  {"a": "A páfránynak", "p": "Melyik növénynek nincs virága?", "s": "Növények", "w": ["A tulipánnak", "A rózsának", "A napraforgónak"]},
  {"a": "Spórával", "p": "Mivel szaporodik a páfrány?", "s": "Növények", "w": ["Maggal", "Bogyóval", "Gumóval"]},
  {"a": "A magból", "p": "Miből lesz az új növény a földben?", "s": "Növények", "w": ["A levélből", "A virágból", "A termésből"]},
  {"a": "Víz és meleg", "p": "Mi kell a mag csírázásához?", "s": "Növények", "w": ["Fény és szél", "Só és hideg", "Levegő és fagy"]},
  {"a": "Tavasszal", "p": "Melyik évszakban virágzik a hóvirág?", "s": "Növények", "w": ["Nyár végén", "Ősz elején", "Tél közepén"]},
  {"a": "A búza", "p": "Melyik növény terem kalászban?", "s": "Növények", "w": ["A borsó", "A bab", "A napraforgó"]},
  {"a": "Több évig él", "p": "Mit jelent, hogy egy növény évelő?", "s": "Növények", "w": ["Egy évig él", "Csak nyáron él", "Minden évben új"]},
  {"a": "A szél", "p": "Mi viszi a virágport a nyírfánál?", "s": "Növények", "w": ["A méh", "A madár", "Az esővíz"]},
  {"a": "A fenyőé", "p": "Melyik fa termése a toboz?", "s": "Növények", "w": ["A tölgyé", "A nyírfáé", "A gesztenyefáé"]},
  {"a": "A klorofilltől", "p": "Mitől zöld a falevél?", "s": "Növények", "w": ["A napfénytől", "A víztől", "A talaj sóitól"]},
  {"a": "A zöld festék", "p": "Mi tűnik el ősszel a levélből?", "s": "Növények", "w": ["A víz", "A levegő", "A napfény melege"]},
  {"a": "A virágé", "p": "Melyik növényi rész a bibe?", "s": "Növények", "w": ["A levélé", "A gyökéré", "A termésé"]},
  {"a": "A termés", "p": "Mi keletkezik a beporzás után?", "s": "Növények", "w": ["A gyökér", "A levél", "Az új virág"]},
  {"a": "A paratölgyéből", "p": "Melyik fa kérgéből készül a parafa?", "s": "Növények", "w": ["A fenyőéből", "A nyírfáéból", "A vadgesztenyééből"]},
  {"a": "Fából", "p": "Miből készül a papír leggyakrabban?", "s": "Növények", "w": ["Fűből", "Nádból", "Gyapotból"]},
  {"a": "Nektárt", "p": "Mit ad a virág cserébe a beporzó rovarnak?", "s": "Növények", "w": ["Vizet", "Gyantát", "Virágszirmot"]},
  {"a": "A mag terjesztése", "p": "Mi a gyümölcs feladata a növény életében?", "s": "Növények", "w": ["A víz tárolása", "A fény gyűjtése", "A levelek táplálása"]},
  {"a": "206", "p": "Hány csont van a felnőtt ember testében?", "s": "Az emberi test", "w": ["106", "306", "406"]},
  {"a": "A bőr", "p": "Melyik a legnagyobb szervünk?", "s": "Az emberi test", "w": ["A máj", "A tüdő", "A vastagbél"]},
  {"a": "A máj", "p": "Melyik a legnagyobb belső szervünk?", "s": "Az emberi test", "w": ["A vese", "A lép", "A hasnyálmirigy"]},
  {"a": "A vese", "p": "Melyik szerv szűri a vért?", "s": "Az emberi test", "w": ["A tüdő", "A lép", "A nyirokcsomó"]},
  {"a": "A szív", "p": "Melyik szerv pumpálja a vért?", "s": "Az emberi test", "w": ["A máj", "A vese", "A rekeszizom"]},
  {"a": "Kettő", "p": "Hány kamrája van a szívnek?", "s": "Az emberi test", "w": ["Egy", "Négy", "Nyolc"]},
  {"a": "Négy", "p": "Hány ürege van összesen a szívnek?", "s": "Az emberi test", "w": ["Kettő", "Hat", "Nyolc"]},
  {"a": "A máj", "p": "Melyik szerv termeli az epét?", "s": "Az emberi test", "w": ["A vese", "A gyomor", "Az epehólyag"]},
  {"a": "Az epehólyagban", "p": "Hol raktározódik az epe?", "s": "Az emberi test", "w": ["A hasnyálmirigyben", "A vékonybélben", "A gyomorban"]},
  {"a": "A hasnyálmirigy", "p": "Melyik szerv termel inzulint?", "s": "Az emberi test", "w": ["A pajzsmirigy", "A mellékvese", "A csecsemőmirigy"]},
  {"a": "A vékonybélben", "p": "Hol szívódik fel a táplálék nagy része?", "s": "Az emberi test", "w": ["A gyomorban", "A vastagbélben", "A nyelőcsőben"]},
  {"a": "A nyelőcső", "p": "Mi köti össze a szájat a gyomorral?", "s": "Az emberi test", "w": ["A légcső", "A gége", "A patkóbél"]},
  {"a": "A vese", "p": "Melyik szerv választja ki a vizeletet?", "s": "Az emberi test", "w": ["A máj", "A lép", "A húgyhólyag"]},
  {"a": "Oxigén", "p": "Melyik gáz jut a vérbe a tüdőben?", "s": "Az emberi test", "w": ["Nitrogén", "Hidrogén", "Szén-dioxid"]},
  {"a": "Szén-dioxidot", "p": "Melyik gázt fújjuk ki a tüdőnkből?", "s": "Az emberi test", "w": ["Oxigént", "Nitrogént", "Szén-monoxidot"]},
  {"a": "A rekeszizom", "p": "Melyik izom segít a légzésben?", "s": "Az emberi test", "w": ["A szívizom", "A hasizom", "A gerincizom"]},
  {"a": "Kettő", "p": "Hány tüdeje van az embernek?", "s": "Az emberi test", "w": ["Egy", "Három", "Négy"]},
  {"a": "A bal", "p": "Melyik tüdőnk a kisebb?", "s": "Az emberi test", "w": ["A jobb", "Egyforma", "Váltakozva"]},
  {"a": "A combcsont", "p": "Melyik a leghosszabb csontunk?", "s": "Az emberi test", "w": ["A sípcsont", "A felkarcsont", "A kulcscsont"]},
  {"a": "A kengyel", "p": "Melyik a legkisebb csontunk?", "s": "Az emberi test", "w": ["Az üllő", "A kalapács", "A csigolya"]},
  {"a": "A fülben", "p": "Hol van a kengyel nevű csont?", "s": "Az emberi test", "w": ["A kézben", "A lábban", "A gerincben"]},
  {"a": "Hét", "p": "Hány csigolya van a nyakunkban?", "s": "Az emberi test", "w": ["Öt", "Kilenc", "Tizenkettő"]},
  {"a": "Tizenkettő", "p": "Hány pár bordája van az embernek?", "s": "Az emberi test", "w": ["Tíz", "Tizennégy", "Tizennyolc"]},
  {"a": "A csontvelő", "p": "Mi található a csontok belsejében?", "s": "Az emberi test", "w": ["A porc", "Az ízület", "A kötőszövet"]},
  {"a": "A csontvelőben", "p": "Hol keletkeznek a vörösvérsejtek?", "s": "Az emberi test", "w": ["A lépben", "A májban", "A nyirokcsomókban"]},
  {"a": "A vörösvérsejt", "p": "Mi szállítja az oxigént a vérben?", "s": "Az emberi test", "w": ["A fehérvérsejt", "A vérlemezke", "A vérplazma"]},
  {"a": "A fehérvérsejt", "p": "Mi véd a fertőzés ellen a vérben?", "s": "Az emberi test", "w": ["A vörösvérsejt", "A vérlemezke", "A vérplazma"]},
  {"a": "A vérlemezke", "p": "Mi segít a vér alvadásában?", "s": "Az emberi test", "w": ["A vörösvérsejt", "A fehérvérsejt", "A vérplazma"]},
  {"a": "Az artériában", "p": "Melyik érben folyik a vér a szívtől?", "s": "Az emberi test", "w": ["A vénában", "A hajszálérben", "A nyirokérben"]},
  {"a": "32", "p": "Hány foga van egy felnőtt embernek?", "s": "Az emberi test", "w": ["20", "28", "36"]},
  {"a": "20", "p": "Hány tejfoga van a gyermeknek?", "s": "Az emberi test", "w": ["16", "24", "32"]},
  {"a": "A zománc", "p": "Mi a fog külső, kemény rétege?", "s": "Az emberi test", "w": ["A dentin", "A fogbél", "A foggyökér"]},
  {"a": "A fogzománc", "p": "Melyik a legkeményebb anyag a testünkben?", "s": "Az emberi test", "w": ["A csont", "A körömlemez", "A porc"]},
  {"a": "Az agy", "p": "Melyik szerv irányítja a testet?", "s": "Az emberi test", "w": ["A szív", "A máj", "A gerincvelő"]},
  {"a": "A gerincvelő", "p": "Mi köti össze az agyat a testtel?", "s": "Az emberi test", "w": ["A nyelőcső", "A légcső", "Az idegdúcok"]},
  {"a": "A szemmel", "p": "Melyik érzékszervünkkel látunk?", "s": "Az emberi test", "w": ["A füllel", "Az orral", "A nyelvvel"]},
  {"a": "A pupilla", "p": "Mi szabályozza a szembe jutó fényt?", "s": "Az emberi test", "w": ["A szaruhártya", "A szemhéj", "Az ideghártya"]},
  {"a": "Az ideghártyán", "p": "Hol keletkezik a kép a szemben?", "s": "Az emberi test", "w": ["A szaruhártyán", "A pupillában", "A szemlencsében"]},
  {"a": "A dobhártya", "p": "Mi rezeg a fülben a hang hatására?", "s": "Az emberi test", "w": ["A kengyel", "A hallójárat", "A fülkagyló"]},
  {"a": "A fül", "p": "Melyik szervünk segít az egyensúlyban?", "s": "Az emberi test", "w": ["A szem", "Az orr", "A nyelv"]},
  {"a": "A nyelvvel", "p": "Mivel érezzük az ízeket?", "s": "Az emberi test", "w": ["A foggal", "A torokkal", "A szájpadlással"]},
  {"a": "A hámréteg", "p": "Mi a bőr felső rétege?", "s": "Az emberi test", "w": ["Az irha", "A kötőszövet", "A bőralja"]},
  {"a": "Az izzadság", "p": "Mi hűti a testet a bőrön át?", "s": "Az emberi test", "w": ["A vér", "A szőr", "A faggyúmirigy"]},
  {"a": "A melanintól", "p": "Mitől barnul le a bőrünk a napon?", "s": "Az emberi test", "w": ["A klorofilltől", "A vitaminoktól", "Az izzadságtól"]},
  {"a": "A szívizom", "p": "Melyik izom dolgozik megállás nélkül?", "s": "Az emberi test", "w": ["A hasizom", "A karizom", "A rágóizom"]},
  {"a": "Megerősödik", "p": "Mi történik az izommal, ha edzzük?", "s": "Az emberi test", "w": ["Elsorvad", "Megrövidül", "Zsírrá alakul"]},
  {"a": "60 százaléka", "p": "A testünk hány százaléka víz nagyjából?", "s": "Az emberi test", "w": ["20 százaléka", "40 százaléka", "90 százaléka"]},
  {"a": "7-8 óra", "p": "Hány óra alvás ajánlott a felnőttnek?", "s": "Az emberi test", "w": ["3-4 óra", "10-12 óra", "14-15 óra"]},
  {"a": "A REM-alvásban", "p": "Melyik alvási szakaszban álmodunk a legtöbbet?", "s": "Az emberi test", "w": ["A mély alvásban", "Az elalváskor", "Az ébredés előtt"]},
  {"a": "Melatonint", "p": "Mit termel a szervezet sötétben az alváshoz?", "s": "Az emberi test", "w": ["Inzulint", "Adrenalint", "Hemoglobint"]},
  {"a": "A máj", "p": "Melyik szerv raktározza a cukrot?", "s": "Az emberi test", "w": ["A lép", "A vese", "A hasnyálmirigy"]},
  {"a": "Az emésztéshez", "p": "Melyik rendszerhez tartozik a gyomor?", "s": "Az emberi test", "w": ["A légzéshez", "A keringéshez", "Az idegrendszerhez"]},
  {"a": "Az oltás", "p": "Mi véd a fertőző betegségek ellen?", "s": "Orvostudomány", "w": ["A vitamin", "A pihenés", "A testmozgás"]},
  {"a": "A vírusok ellen", "p": "Mi ellen nem hat az antibiotikum?", "s": "Orvostudomány", "w": ["A baktériumok ellen", "A gombák ellen", "Az élősködők ellen"]},
  {"a": "Vírus", "p": "Milyen kórokozó okozza az influenzát?", "s": "Orvostudomány", "w": ["Baktérium", "Gomba", "Élősködő"]},
  {"a": "A D-vitamin", "p": "Melyik vitamin keletkezik a bőrben napfényben?", "s": "Orvostudomány", "w": ["A C-vitamin", "A B-vitamin", "Az A-vitamin"]},
  {"a": "A C-vitamin", "p": "Melyik vitaminból van sok a citromban?", "s": "Orvostudomány", "w": ["A D-vitamin", "A K-vitamin", "Az E-vitamin"]},
  {"a": "A skorbutot", "p": "Melyik betegséget okozza a C-vitamin hiánya?", "s": "Orvostudomány", "w": ["Az angolkórt", "A vérszegénységet", "A cukorbetegséget"]},
  {"a": "A kalcium", "p": "Melyik ásványi anyag kell a csontnak?", "s": "Orvostudomány", "w": ["A vas", "A nátrium", "A magnézium"]},
  {"a": "A vas", "p": "Melyik ásványi anyag kell a vérnek?", "s": "Orvostudomány", "w": ["A kalcium", "A kálium", "A magnézium"]},
  {"a": "36,6 fok", "p": "Mennyi a normális testhőmérséklet?", "s": "Orvostudomány", "w": ["34,5 fok", "38,5 fok", "40,0 fok"]},
  {"a": "A szívet", "p": "Mit hallgat meg az orvos a sztetoszkóppal?", "s": "Orvostudomány", "w": ["A gyomrot", "A vesét", "Az idegeket"]},
  {"a": "A csontokat", "p": "Mit mutat meg jól a röntgenkép?", "s": "Orvostudomány", "w": ["A bőrt", "Az izmokat", "Az idegvégződéseket"]},
  {"a": "A fogakat", "p": "Mit vizsgál a fogorvos?", "s": "Orvostudomány", "w": ["A szemet", "A füleket", "A tüdőt"]},
  {"a": "Segít a védekezésben", "p": "Mi a láz feladata a szervezetben?", "s": "Orvostudomány", "w": ["Csökkenti a vérnyomást", "Növeli az étvágyat", "Felgyorsítja az emésztést"]},
  {"a": "A 0-s", "p": "Melyik vércsoportot hívják egyetemes adónak?", "s": "Orvostudomány", "w": ["Az A-s", "A B-s", "Az AB-s"]},
  {"a": "Megalvad", "p": "Mi történik a vérrel, ha megvágjuk magunkat?", "s": "Orvostudomány", "w": ["Felmelegszik", "Felhígul", "Elszíntelenedik"]},
  {"a": "A baktérium", "p": "Mi okozza a fogszuvasodást?", "s": "Orvostudomány", "w": ["A hideg víz", "A kemény étel", "A sok folyadék"]},
  {"a": "A kórokozók miatt", "p": "Miért mosunk kezet étkezés előtt?", "s": "Orvostudomány", "w": ["A jó illat miatt", "A szokás miatt", "A száraz bőr miatt"]},
  {"a": "Az inzuliné", "p": "Melyik hormon szintje fontos a cukorbetegségben?", "s": "Orvostudomány", "w": ["Az adrenaliné", "A melatoniné", "A tiroxiné"]},
  {"a": "70 körül", "p": "Mennyi a felnőtt nyugalmi pulzusa nagyjából?", "s": "Orvostudomány", "w": ["30 körül", "120 körül", "150 körül"]},
  {"a": "A vérsejteket", "p": "Mit vizsgál a vérkép?", "s": "Orvostudomány", "w": ["A csontokat", "Az idegeket", "A tüdő térfogatát"]},
  {"a": "A látást", "p": "Mit javít a szemüveg?", "s": "Orvostudomány", "w": ["A hallást", "A szaglást", "Az egyensúlyt"]},
  {"a": "A fület", "p": "Melyik érzékszervet segíti a hallókészülék?", "s": "Orvostudomány", "w": ["A szemet", "Az orrot", "A nyelvet"]},
  {"a": "Az izzadás miatt", "p": "Miért kell sok folyadék a nyári melegben?", "s": "Orvostudomány", "w": ["A napfény miatt", "A por miatt", "A szélfúvás miatt"]},
  {"a": "Átterjed másokra", "p": "Mit jelent, hogy egy betegség fertőző?", "s": "Orvostudomány", "w": ["Csak egyszer jön", "Nem gyógyítható", "Örökletes betegség"]},
  {"a": "A könnymirigy", "p": "Melyik mirigy termeli a könnyet?", "s": "Orvostudomány", "w": ["A nyálmirigy", "A pajzsmirigy", "A faggyúmirigy"]},
  {"a": "Az orrot", "p": "Mit tisztít ki a tüsszentés?", "s": "Orvostudomány", "w": ["A tüdőt", "A torkot", "A hörgőket"]},
  {"a": "5 liter", "p": "Mennyi vér van egy felnőtt emberben?", "s": "Orvostudomány", "w": ["1 liter", "10 liter", "20 liter"]},
  {"a": "Öt", "p": "Hány érzékszervünk van a hagyomány szerint?", "s": "Az emberi test", "w": ["Négy", "Hat", "Nyolc"]},
  {"a": "Nyolc", "p": "Hány bolygó kering a Nap körül?", "s": "Naprendszer", "w": ["Hét", "Kilenc", "Tizenkettő"]},
  {"a": "A Merkúr", "p": "Melyik bolygó van a legközelebb a Naphoz?", "s": "Naprendszer", "w": ["A Vénusz", "A Mars", "A Szaturnusz"]},
  {"a": "A Jupiter", "p": "Melyik a legnagyobb bolygó?", "s": "Naprendszer", "w": ["A Szaturnusz", "A Neptunusz", "A Föld"]},
  {"a": "A Merkúr", "p": "Melyik a legkisebb bolygó?", "s": "Naprendszer", "w": ["A Mars", "A Vénusz", "A Neptunusz"]},
  {"a": "A Marsot", "p": "Melyik bolygót hívjuk vörös bolygónak?", "s": "Naprendszer", "w": ["A Vénuszt", "A Merkúrt", "A Jupitert"]},
  {"a": "A Vénusz", "p": "Melyik a legforróbb bolygó?", "s": "Naprendszer", "w": ["A Merkúr", "A Mars", "A Szaturnusz"]},
  {"a": "A Marsnak", "p": "Melyik bolygónak nincsenek gyűrűi?", "s": "Naprendszer", "w": ["A Jupiternek", "A Szaturnusznak", "Az Uránusznak"]},
  {"a": "Jégből és kőből", "p": "Miből állnak a Szaturnusz gyűrűi?", "s": "Naprendszer", "w": ["Vasból és nikkelből", "Folyékony vízből", "Finom vasporból"]},
  {"a": "A harmadik", "p": "Hányadik bolygó a Föld a Naptól?", "s": "Naprendszer", "w": ["A második", "A negyedik", "Az ötödik"]},
  {"a": "A Mars", "p": "Melyik bolygó a Föld szomszédja kifelé?", "s": "Naprendszer", "w": ["A Vénusz", "A Merkúr", "A Jupiter"]},
  {"a": "A Neptunusz", "p": "Melyik bolygó van a legtávolabb a Naptól?", "s": "Naprendszer", "w": ["Az Uránusz", "A Szaturnusz", "A Jupiter"]},
  {"a": "A Plútót", "p": "Melyik égitestet sorolták át 2006-ban?", "s": "Naprendszer", "w": ["A Merkúrt", "Az Uránuszt", "A Neptunuszt"]},
  {"a": "Törpebolygó", "p": "Milyen égitest ma a Plútó?", "s": "Naprendszer", "w": ["Üstökös", "Kisbolygó", "Törpecsillag"]},
  {"a": "Egy", "p": "Hány holdja van a Földnek?", "s": "Naprendszer", "w": ["Kettő", "Három", "Egy sem"]},
  {"a": "Kettő", "p": "Hány holdja van a Marsnak?", "s": "Naprendszer", "w": ["Egy", "Négy", "Tizenkettő"]},
  {"a": "Phobos és Deimos", "p": "Mi a Mars két holdjának neve?", "s": "Naprendszer", "w": ["Io és Europa", "Titán és Rhea", "Ganymedes és Callisto"]},
  {"a": "A Titán", "p": "Melyik a Szaturnusz legnagyobb holdja?", "s": "Naprendszer", "w": ["A Rhea", "Az Iapetus", "A Ganymedes"]},
  {"a": "A Ganymedes", "p": "Melyik a Naprendszer legnagyobb holdja?", "s": "Naprendszer", "w": ["A Hold", "A Titán", "Az Enceladus"]},
  {"a": "A Jupiteren", "p": "Melyik bolygón van a Nagy Vörös Folt?", "s": "Naprendszer", "w": ["A Marson", "A Vénuszon", "A Szaturnuszon"]},
  {"a": "Egy hatalmas vihar", "p": "Mi a Jupiter Nagy Vörös Foltja?", "s": "Naprendszer", "w": ["Egy nagy hegy", "Egy mély kráter", "Egy kiszáradt tenger"]},
  {"a": "Gázból", "p": "Miből áll főleg a Jupiter?", "s": "Naprendszer", "w": ["Kőzetből", "Jégből", "Folyékony vasból"]},
  {"a": "Az Uránusz", "p": "Melyik bolygó forog szinte az oldalán fekve?", "s": "Naprendszer", "w": ["A Jupiter", "A Szaturnusz", "A Neptunusz"]},
  {"a": "A Marson", "p": "Melyik bolygón van a legnagyobb vulkán?", "s": "Naprendszer", "w": ["A Vénuszon", "A Merkúron", "A Jupiteren"]},
  {"a": "Olympus Mons", "p": "Mi a Naprendszer legnagyobb vulkánjának neve?", "s": "Naprendszer", "w": ["Valles Marineris", "Tharsis Montes", "Mare Tranquillitatis"]},
  {"a": "A Föld körül", "p": "Melyik égitest körül kering a Hold?", "s": "Naprendszer", "w": ["A Nap körül", "A Mars körül", "A Jupiter körül"]},
  {"a": "Kb. 1 hónap", "p": "Mennyi idő alatt kerüli meg a Hold a Földet?", "s": "Naprendszer", "w": ["Kb. 1 hét", "Kb. 3 hónap", "Kb. 1 év"]},
  {"a": "Egy év alatt", "p": "Mennyi idő alatt kerüli meg a Föld a Napot?", "s": "Naprendszer", "w": ["Egy hét alatt", "Tíz év alatt", "Egy hónap alatt"]},
  {"a": "A Föld forgásától", "p": "Mitől van a nappal és az éjszaka?", "s": "Naprendszer", "w": ["A Nap mozgásától", "A felhők járásától", "A Hold keringésétől"]},
  {"a": "A Föld ferde tengelyétől", "p": "Mitől vannak az évszakok?", "s": "Naprendszer", "w": ["A Hold vonzásától", "A légkör változásától", "A Naptól való távolságtól"]},
  {"a": "A Naptól", "p": "Honnan van a Hold fénye?", "s": "Naprendszer", "w": ["Saját magától", "A Földtől", "A csillagoktól"]},
  {"a": "Az egyik felét", "p": "Mennyit látunk a Hold felszínéből a Földről?", "s": "Naprendszer", "w": ["A negyedét", "A teljes felszínt", "Csak egy kis foltot"]},
  {"a": "Nincs", "p": "Van-e levegő a Holdon?", "s": "Naprendszer", "w": ["Van, sok", "Van, kevés", "Csak télen"]},
  {"a": "A Hold vonzása", "p": "Mi okozza a tengerek apályát és dagályát?", "s": "Naprendszer", "w": ["A Nap melege", "A szél ereje", "Az óceánok áramlása"]},
  {"a": "A hatoda", "p": "Mekkora a gravitáció a Holdon a földihez képest?", "s": "Naprendszer", "w": ["A fele", "A harmada", "A tizede"]},
  {"a": "A Föld árnyéka", "p": "Mi vetül a Holdra holdfogyatkozáskor?", "s": "Naprendszer", "w": ["A Nap korongja", "A Hold sötét fele", "A csillagok fénye"]},
  {"a": "A Hold", "p": "Mi kerül a Nap elé napfogyatkozáskor?", "s": "Naprendszer", "w": ["A Föld", "A Vénusz", "Egy üstökös"]},
  {"a": "Csillag", "p": "Milyen égitest a Nap?", "s": "Naprendszer", "w": ["Bolygó", "Üstökös", "Törpebolygó"]},
  {"a": "Hidrogénből", "p": "Miből áll főleg a Nap?", "s": "Naprendszer", "w": ["Oxigénből", "Szén-dioxidból", "Folyékony vasból"]},
  {"a": "8 perc alatt", "p": "Mennyi idő alatt ér a Nap fénye a Földre?", "s": "Naprendszer", "w": ["1 perc alatt", "1 óra alatt", "Egy nap alatt"]},
  {"a": "5500 fok", "p": "Mennyi a Nap felszíni hőmérséklete nagyjából?", "s": "Naprendszer", "w": ["100 fok", "1000 fok", "1 millió fok"]},
  {"a": "Hidegebbek", "p": "Milyenek a napfoltok a Nap többi részéhez képest?", "s": "Naprendszer", "w": ["Melegebbek", "Fényesebbek", "Ugyanolyanok"]},
  {"a": "A Neptunuszon", "p": "Melyik bolygón tart legtovább egy év?", "s": "Naprendszer", "w": ["A Jupiteren", "A Marson", "A Szaturnuszon"]},
  {"a": "A Merkúron", "p": "Melyik bolygón telik leggyorsabban egy év?", "s": "Naprendszer", "w": ["A Vénuszon", "A Földön", "A Jupiteren"]},
  {"a": "A Mars és a Jupiter között", "p": "Hol található a kisbolygóöv?", "s": "Naprendszer", "w": ["A Föld és a Mars között", "A Nap és a Merkúr között", "A Szaturnusz és az Uránusz között"]},
  {"a": "Jégből és porból", "p": "Miből áll az üstökös magja?", "s": "Naprendszer", "w": ["Izzó gázból", "Olvadt kőzetből", "Fémekből és kőből"]},
  {"a": "A napszél", "p": "Mi alakítja ki az üstökös csóváját?", "s": "Naprendszer", "w": ["A Föld vonzása", "A saját forgása", "A csillagok fénye"]},
  {"a": "Egy porszemcse", "p": "Mi izzik fel hullócsillagként a légkörben?", "s": "Naprendszer", "w": ["Egy kis üstökös", "Egy távoli csillag", "Egy lehulló műhold"]},
  {"a": "Meteorit", "p": "Hogyan hívjuk a földet ért meteort?", "s": "Naprendszer", "w": ["Meteor", "Kisbolygó", "Üstökösmag"]},
  {"a": "Távolságot", "p": "Mit mérünk fényévben?", "s": "Csillagászat és űrkutatás", "w": ["Időt", "Fényerőt", "A csillag korát"]},
  {"a": "A Nap", "p": "Melyik a hozzánk legközelebbi csillag?", "s": "Csillagászat és űrkutatás", "w": ["A Szíriusz", "A Sarkcsillag", "A Proxima Centauri"]},
  {"a": "A Proxima Centauri", "p": "Melyik csillag van a Naphoz a legközelebb?", "s": "Csillagászat és űrkutatás", "w": ["A Szíriusz", "A Sarkcsillag", "Az Alfa Centauri A"]},
  {"a": "A Sarkcsillag", "p": "Melyik csillag mutatja az északi irányt?", "s": "Csillagászat és űrkutatás", "w": ["A Szíriusz", "A Vega", "Az Esthajnalcsillag"]},
  {"a": "A Szíriusz", "p": "Melyik a legfényesebb csillag az éjszakai égen?", "s": "Csillagászat és űrkutatás", "w": ["A Vega", "A Sarkcsillag", "A Betelgeuze"]},
  {"a": "A Tejútrendszer", "p": "Mi a galaxisunk neve?", "s": "Csillagászat és űrkutatás", "w": ["Az Androméda", "A Nagy Medve", "A Magellán-felhő"]},
  {"a": "Spirál alakú", "p": "Milyen alakú a Tejútrendszer?", "s": "Csillagászat és űrkutatás", "w": ["Gömb alakú", "Kocka alakú", "Szabálytalan alakú"]},
  {"a": "A magfúzió", "p": "Mi ad energiát a csillagoknak?", "s": "Csillagászat és űrkutatás", "w": ["Az égés", "A napszél", "A radioaktivitás"]},
  {"a": "Fehér törpe", "p": "Mi lesz a Napból évmilliárdok múlva?", "s": "Csillagászat és űrkutatás", "w": ["Szupernóva", "Fekete lyuk", "Kettős csillag"]},
  {"a": "Egy csillag robbanását", "p": "Mit nevezünk szupernóvának?", "s": "Csillagászat és űrkutatás", "w": ["Két hold ütközését", "Egy új bolygó születését", "Egy üstökös becsapódását"]},
  {"a": "A fény", "p": "Mi nem tud kiszabadulni a fekete lyukból?", "s": "Csillagászat és űrkutatás", "w": ["A hang", "A hő", "A mágnesesség"]},
  {"a": "Tizenkettő", "p": "Hány csillagkép tartozik az állatövhöz?", "s": "Csillagászat és űrkutatás", "w": ["Nyolc", "Tíz", "Huszonnégy"]},
  {"a": "A Nagy Medve", "p": "Melyik csillagkép hét fényes csillagból áll?", "s": "Csillagászat és űrkutatás", "w": ["A Skorpió", "A Déli Kereszt", "A Kassziopeia"]},
  {"a": "Távcsövet", "p": "Mit használunk a csillagok megfigyelésére?", "s": "Csillagászat és űrkutatás", "w": ["Nagyítót", "Mikroszkópot", "Fényképezőgépet"]},
  {"a": "Galilei", "p": "Ki figyelte meg elsőként a Jupiter holdjait?", "s": "Csillagászat és űrkutatás", "w": ["Kepler", "Newton", "Kopernikusz"]},
  {"a": "Kepler", "p": "Ki írta le a bolygómozgás törvényeit?", "s": "Csillagászat és űrkutatás", "w": ["Galilei", "Newton", "Kopernikusz"]},
  {"a": "A Szovjetunió", "p": "Melyik ország indította az első műholdat?", "s": "Csillagászat és űrkutatás", "w": ["Franciaország", "Nagy-Britannia", "Az Egyesült Államok"]},
  {"a": "1957-ben", "p": "Melyik évben indult az első műhold?", "s": "Csillagászat és űrkutatás", "w": ["1947-ben", "1961-ben", "1969-ben"]},
  {"a": "Egy kutya", "p": "Melyik állat keringett először a Föld körül?", "s": "Csillagászat és űrkutatás", "w": ["Egy majom", "Egy macska", "Egy patkány"]},
  {"a": "Lajka", "p": "Mi volt az első űrbe jutott kutya neve?", "s": "Csillagászat és űrkutatás", "w": ["Belka", "Sztrelka", "Csernuska"]},
  {"a": "Tizenketten", "p": "Hány ember járt eddig a Holdon?", "s": "Csillagászat és űrkutatás", "w": ["Négyen", "Hatan", "Huszonnégyen"]},
  {"a": "Az Apollo", "p": "Melyik program juttatta az embert a Holdra?", "s": "Csillagászat és űrkutatás", "w": ["A Szojuz", "A Gemini", "A Vosztok"]},
  {"a": "Sas", "p": "Mi volt a Holdra először leszálló holdkomp neve?", "s": "Csillagászat és űrkutatás", "w": ["Sólyom", "Kolumbusz", "Szabadság"]},
  {"a": "Az ISS", "p": "Melyik űrállomás kering ma is a Föld körül?", "s": "Csillagászat és űrkutatás", "w": ["A Mir", "A Szaljut", "A Szkájleb"]},
  {"a": "A súlytalanság", "p": "Milyen érzés uralkodik az űrállomáson?", "s": "Csillagászat és űrkutatás", "w": ["A nagy nyomás", "Az erős vonzás", "A nagy hidegérzet"]},
  {"a": "Űrruhát", "p": "Mit visel az űrhajós az űrsétán?", "s": "Csillagászat és űrkutatás", "w": ["Búvárruhát", "Védőköpenyt", "Mentőmellényt"]},
  {"a": "Semmilyen", "p": "Milyen hang hallatszik az űrben?", "s": "Csillagászat és űrkutatás", "w": ["Halk zúgás", "Éles sípolás", "Mély dübörgés"]},
  {"a": "Mert nincs levegő", "p": "Miért nincs hang az űrben?", "s": "Csillagászat és űrkutatás", "w": ["Mert túl hideg van", "Mert nincs gravitáció", "Mert túl nagy a távolság"]},
  {"a": "A Hubble", "p": "Melyik űrtávcső készíti a híres felvételeket?", "s": "Csillagászat és űrkutatás", "w": ["A Kepler", "A Voyager", "A Cassini"]},
  {"a": "A Voyager 1", "p": "Melyik űrszonda jutott először a Naprendszeren túlra?", "s": "Csillagászat és űrkutatás", "w": ["A Pioneer 10", "A Cassini", "A New Horizons"]},
  {"a": "A Marsra", "p": "Melyik bolygóra küldtek több robotjárművet?", "s": "Csillagászat és űrkutatás", "w": ["A Vénuszra", "A Merkúrra", "A Jupiterre"]},
  {"a": "Vizet", "p": "Mit keresnek elsősorban a kutatók a Marson?", "s": "Csillagászat és űrkutatás", "w": ["Olajat", "Aranyat", "Széndarabokat"]},
  {"a": "A kiáramló gáz", "p": "Mi emeli fel a rakétát az űrbe?", "s": "Csillagászat és űrkutatás", "w": ["A légcsavar", "A szárnya", "A sűrített levegő"]},
  {"a": "Régi műholdakat", "p": "Mit nevezünk űrszemétnek?", "s": "Csillagászat és űrkutatás", "w": ["Kis üstökösöket", "Meteoritdarabokat", "Hulló csillagokat"]},
  {"a": "Egyiken sem", "p": "Melyik bolygón járt eddig ember?", "s": "Csillagászat és űrkutatás", "w": ["A Marson", "A Vénuszon", "A Jupiteren"]},
  {"a": "A Szovjetunió", "p": "Melyik ország juttatott először embert az űrbe?", "s": "Csillagászat és űrkutatás", "w": ["Kína", "Németország", "Az Egyesült Államok"]},
  {"a": "1980-ban", "p": "Melyik évben repült az első magyar űrhajós?", "s": "Csillagászat és űrkutatás", "w": ["1970-ben", "1975-ben", "1985-ben"]},
  {"a": "A Szaljut-6-on", "p": "Melyik űrállomáson járt az első magyar űrhajós?", "s": "Csillagászat és űrkutatás", "w": ["Az ISS-en", "A Szkájlebben", "A Mir űrállomáson"]},
  {"a": "Fekete", "p": "Milyen színű az égbolt az űrből nézve?", "s": "Csillagászat és űrkutatás", "w": ["Kék", "Szürke", "Sötétlila"]},
  {"a": "Nagy síkságok", "p": "Mik a Hold sötét foltjai szabad szemmel?", "s": "Csillagászat és űrkutatás", "w": ["Mély óceánok", "Sűrű erdők", "Hatalmas tavak"]},
  {"a": "Becsapódások", "p": "Mi hozta létre a Hold krátereit?", "s": "Csillagászat és űrkutatás", "w": ["Vulkánok", "Földrengések", "Erős szélviharok"]},
  {"a": "Mert nincs szél", "p": "Miért maradnak meg a lábnyomok a Holdon?", "s": "Csillagászat és űrkutatás", "w": ["Mert mély a por", "Mert nagyon hideg", "Mert nincs gravitáció"]},
  {"a": "A Vénusznak", "p": "Melyik bolygónak leghosszabb a napja?", "s": "Csillagászat és űrkutatás", "w": ["A Merkúrnak", "A Marsnak", "A Jupiternek"]},
  {"a": "Vízcseppekből", "p": "Miből állnak a felhők?", "s": "Időjárás és éghajlat", "w": ["Füstből", "Levegőből", "Porszemcsékből"]},
  {"a": "A gomolyfelhő", "p": "Melyik felhő hozza a zivatart?", "s": "Időjárás és éghajlat", "w": ["A rétegfelhő", "A bárányfelhő", "A fátyolfelhő"]},
  {"a": "A villám", "p": "Melyik jelenség előzi meg a mennydörgést?", "s": "Időjárás és éghajlat", "w": ["A szél", "A jégeső", "A szivárvány"]},
  {"a": "A fény gyorsabb", "p": "Miért látjuk a villámot a dörgés előtt?", "s": "Időjárás és éghajlat", "w": ["A hang erősebb", "A villám közelebb van", "A hang később keletkezik"]},
  {"a": "A felmelegedő levegőtől", "p": "Mitől dörög az ég?", "s": "Időjárás és éghajlat", "w": ["Az eső kopogásától", "A szél süvítésétől", "A felhők összecsapásától"]},
  {"a": "0 fokon", "p": "Hány fokon fagy meg a víz?", "s": "Időjárás és éghajlat", "w": ["10 fokon", "32 fokon", "100 fokon"]},
  {"a": "100 fokon", "p": "Hány fokon forr a víz?", "s": "Időjárás és éghajlat", "w": ["0 fokon", "50 fokon", "200 fokon"]},
  {"a": "Hajnalban", "p": "Mikor keletkezik a harmat?", "s": "Időjárás és éghajlat", "w": ["Délben", "Napnyugtakor", "Kora délután"]},
  {"a": "Alacsony felhő", "p": "Mi a köd valójában?", "s": "Időjárás és éghajlat", "w": ["Hideg levegő", "Sűrű porfelhő", "Füst a levegőben"]},
  {"a": "Fagyott vízpárából", "p": "Miből lesz a hó?", "s": "Időjárás és éghajlat", "w": ["Fagyott esőcseppből", "Apró jégdarabból", "Hideg porszemből"]},
  {"a": "Jégdarabka", "p": "Mi hullik jégesőkor?", "s": "Időjárás és éghajlat", "w": ["Fagyott hó", "Kemény harmat", "Sűrű zúzmara"]},
  {"a": "Eső után napsütésben", "p": "Mikor keletkezik a szivárvány?", "s": "Időjárás és éghajlat", "w": ["Hóesés közben", "Sűrű ködben", "Naplemente után sötétben"]},
  {"a": "Hetet", "p": "Hány színt szoktak számolni a szivárványban?", "s": "Időjárás és éghajlat", "w": ["Ötöt", "Kilencet", "Tizenkettőt"]},
  {"a": "A légnyomás különbsége", "p": "Mi okozza a szelet?", "s": "Időjárás és éghajlat", "w": ["A Föld forgása", "A felhők mozgása", "A Nap sugárzásának ereje"]},
  {"a": "Barométerrel", "p": "Mivel mérjük a légnyomást?", "s": "Időjárás és éghajlat", "w": ["Hőmérővel", "Szélmérővel", "Csapadékmérővel"]},
  {"a": "Romló időt", "p": "Mit jelez a süllyedő légnyomás?", "s": "Időjárás és éghajlat", "w": ["Derült időt", "Erős fagyot", "Hosszú szárazságot"]},
  {"a": "Hőmérővel", "p": "Mivel mérjük a hőmérsékletet?", "s": "Időjárás és éghajlat", "w": ["Barométerrel", "Szélmérővel", "Páratartalom-mérővel"]},
  {"a": "Télen", "p": "Melyik évszakban legrövidebb a nappal?", "s": "Időjárás és éghajlat", "w": ["Nyáron", "Ősszel", "Tavasszal"]},
  {"a": "Nyáron", "p": "Melyik évszakban leghosszabb a nappal?", "s": "Időjárás és éghajlat", "w": ["Télen", "Ősszel", "Tavasszal"]},
  {"a": "Négy", "p": "Hány évszak van nálunk?", "s": "Időjárás és éghajlat", "w": ["Kettő", "Három", "Hat"]},
  {"a": "Június 21-én", "p": "Mikor van az év leghosszabb napja?", "s": "Időjárás és éghajlat", "w": ["Március 21-én", "December 21-én", "Szeptember 23-án"]},
  {"a": "Március 21-én", "p": "Mikor van a tavaszi napéjegyenlőség?", "s": "Időjárás és éghajlat", "w": ["Június 21-én", "Február 1-jén", "Szeptember 23-án"]},
  {"a": "Az esőt és a havat", "p": "Mit nevezünk csapadéknak?", "s": "Időjárás és éghajlat", "w": ["A szelet és a ködöt", "A felhőt és a párát", "A fagyot és a meleget"]},
  {"a": "Vízgőz a levegőben", "p": "Mi a pára?", "s": "Időjárás és éghajlat", "w": ["Por a levegőben", "Füst a levegőben", "Hideg levegő télen"]},
  {"a": "Gázzá válik", "p": "Mi történik a vízzel párolgáskor?", "s": "Időjárás és éghajlat", "w": ["Jéggé válik", "Eltűnik teljesen", "Nehezebbé válik"]},
  {"a": "A párolgás", "p": "Mi a víz körforgásának első lépése?", "s": "Időjárás és éghajlat", "w": ["A csapadék", "A lecsapódás", "A beszivárgás"]},
  {"a": "Erős forgószél", "p": "Mi a hurrikán?", "s": "Időjárás és éghajlat", "w": ["Nagy hóvihar", "Hideg légáramlat", "Hosszú szárazság"]},
  {"a": "Forgó légtölcsér", "p": "Mi jellemzi a tornádót?", "s": "Időjárás és éghajlat", "w": ["Hideg esőfelhő", "Lassú légmozgás", "Hatalmas jégtábla"]},
  {"a": "A légkör megtartja a hőt", "p": "Mit jelent az üvegházhatás?", "s": "Időjárás és éghajlat", "w": ["A felhők eltűnnek", "A Nap közelebb kerül", "A levegő elfogy a Földön"]},
  {"a": "A szén-dioxid", "p": "Melyik gáz erősíti az üvegházhatást?", "s": "Időjárás és éghajlat", "w": ["Az oxigén", "A nitrogén", "A szén-monoxid"]},
  {"a": "Meleg és csapadékos", "p": "Milyen az éghajlat az Egyenlítő közelében?", "s": "Időjárás és éghajlat", "w": ["Hideg és száraz", "Hűvös és szeles", "Változó és mérsékelt"]},
  {"a": "Fagyott pára", "p": "Mi a zúzmara?", "s": "Időjárás és éghajlat", "w": ["Olvadt hó", "Finom jégeső", "Hideg harmat"]},
  {"a": "Hidegebb", "p": "Milyen a levegő hőmérséklete magasabban?", "s": "Időjárás és éghajlat", "w": ["Melegebb", "Ugyanolyan", "Változatlan"]},
  {"a": "A fény szóródásától", "p": "Mitől kék az égbolt?", "s": "Időjárás és éghajlat", "w": ["A tenger színétől", "A levegő színétől", "A Nap sugarainak melegétől"]},
  {"a": "A vörös", "p": "Melyik szín uralkodik az égen naplementekor?", "s": "Időjárás és éghajlat", "w": ["A kék", "A zöld", "A világoslila"]},
  {"a": "Tartós szárazságot", "p": "Mit nevezünk aszálynak?", "s": "Időjárás és éghajlat", "w": ["Erős szélvihart", "Hosszú hideg időt", "Hirtelen felhőszakadást"]},
  {"a": "A kéreg", "p": "Mi a Föld legkülső, szilárd rétege?", "s": "A Föld", "w": ["A köpeny", "A külső mag", "A belső mag"]},
  {"a": "A mag", "p": "Mi van a Föld középpontjában?", "s": "A Föld", "w": ["A kéreg", "A köpeny", "A magmatenger"]},
  {"a": "Vasból", "p": "Miből áll főleg a Föld magja?", "s": "A Föld", "w": ["Kőzetből", "Aranyból", "Olvadt jégből"]},
  {"a": "A magma", "p": "Mi az izzó, olvadt kőzet a föld alatt?", "s": "A Föld", "w": ["A láva", "A bazalt", "A homokkő"]},
  {"a": "Lávának", "p": "Hogyan hívjuk a felszínre ömlő magmát?", "s": "A Föld", "w": ["Magmának", "Hamunak", "Bazaltnak"]},
  {"a": "Hamu", "p": "Mi tör ki a vulkánból a láván kívül?", "s": "A Föld", "w": ["Homok", "Jég", "Sós víz"]},
  {"a": "A kőzetlemezek mozgása", "p": "Mi okozza a földrengést?", "s": "A Föld", "w": ["A Hold vonzása", "Az erős szélviharok", "A vulkánok hőmérséklete"]},
  {"a": "A földrengést", "p": "Mit mér a szeizmográf?", "s": "A Föld", "w": ["A légnyomást", "A csapadékot", "A hőmérsékletet"]},
  {"a": "Óriási hullámot", "p": "Mit nevezünk szökőárnak?", "s": "A Föld", "w": ["Nagy hóvihart", "Erős forgószelet", "Hosszú szárazságot"]},
  {"a": "Egy földrengés", "p": "Mi indítja el leggyakrabban a szökőárt?", "s": "A Föld", "w": ["Egy nagy vihar", "A Hold vonzása", "A tenger felmelegedése"]},
  {"a": "Növényi maradványból", "p": "Miből lesz a szén a föld alatt?", "s": "A Föld", "w": ["Állati csontokból", "Megfagyott vízből", "Homokból és agyagból"]},
  {"a": "Élőlények maradványaiból", "p": "Miből keletkezik a kőolaj?", "s": "A Föld", "w": ["Olvadt kőzetből", "Vulkáni hamuból", "Sós tengervíz maradékából"]},
  {"a": "A víz", "p": "Mi vájja ki a cseppkőbarlangot?", "s": "A Föld", "w": ["A szél", "A jég", "A földrengés"]},
  {"a": "Szénből", "p": "Melyik elemből áll a gyémánt?", "s": "A Föld", "w": ["Kvarcból", "Mészkőből", "Vasércből"]},
  {"a": "A gyémánt", "p": "Melyik a legkeményebb ásvány?", "s": "A Föld", "w": ["A kvarc", "A gránit", "A smaragd"]},
  {"a": "Magmás kőzet", "p": "Milyen kőzet a gránit?", "s": "A Föld", "w": ["Vulkáni hamu", "Üledékes kőzet", "Átalakult kőzet"]},
  {"a": "Üledékes kőzet", "p": "Milyen kőzet a homokkő?", "s": "A Föld", "w": ["Magmás kőzet", "Olvadt kőzet", "Átalakult kőzet"]},
  {"a": "A víz sodrása", "p": "Mi hordja el a partot a folyónál?", "s": "A Föld", "w": ["A szél ereje", "A nap melege", "A halak mozgása"]},
  {"a": "Kb. háromnegyede", "p": "Mekkora része víz a Föld felszínének?", "s": "A Föld", "w": ["Kb. a fele", "Kb. a negyede", "Kb. a tizedrésze"]},
  {"a": "Sós", "p": "Milyen a tengervíz íze?", "s": "A Föld", "w": ["Édes", "Keserű", "Íztelen"]},
  {"a": "A kőzetekből", "p": "Honnan kerül a só a tengerbe?", "s": "A Föld", "w": ["Az esővízből", "A halaktól", "A tengeri növényekből"]},
  {"a": "A földrészek mozgását", "p": "Mit jelent a kontinensvándorlás?", "s": "A Föld", "w": ["A folyók áradását", "A tengerek apadását", "A hegységek magasodását"]},
  {"a": "4,5 milliárd", "p": "Hány éves nagyjából a Föld?", "s": "A Föld", "w": ["1 millió", "100 millió", "500 milliárd"]},
  {"a": "Hegység", "p": "Mi keletkezik két ütköző kőzetlemezből?", "s": "A Föld", "w": ["Óceán", "Sivatag", "Homokdűne"]},
  {"a": "A felszín koptatását", "p": "Mit jelent az erózió?", "s": "A Föld", "w": ["A kőzet olvadását", "A talaj gazdagodását", "A hegyek emelkedését"]},
  {"a": "A humusz", "p": "Mi a talaj legfelső, sötét rétege?", "s": "A Föld", "w": ["Az agyag", "A homok", "Az altalaj"]},
  {"a": "A humusztól", "p": "Mitől termékeny a talaj?", "s": "A Föld", "w": ["A homoktól", "A kavicstól", "A kőzetlisztektől"]},
  {"a": "A Földet borító levegőt", "p": "Mit nevezünk légkörnek?", "s": "A Föld", "w": ["A felhők együttesét", "A szelek rendszerét", "A magas hegyek levegőjét"]},
  {"a": "Az ózonréteg", "p": "Melyik réteg véd az ibolyántúli sugárzástól?", "s": "A Föld", "w": ["A felhőréteg", "A troposzféra", "A sztratoszféra"]},
  {"a": "Jégből", "p": "Miből áll a gleccser?", "s": "A Föld", "w": ["Hóból", "Kőzetből", "Fagyott sárból"]},
  {"a": "Olvad", "p": "Mi történik a jégtakaróval melegedéskor?", "s": "A Föld", "w": ["Növekszik", "Megkeményedik", "Elszíneződik"]},
  {"a": "A koruk sorrendjét", "p": "Mit mutat meg a kőzetrétegek sorrendje?", "s": "A Föld", "w": ["A hegység magasságát", "A kőzetek keménységét", "A talaj termékenységét"]},
  {"a": "Üledékes kőzetben", "p": "Hol találunk kövületeket leggyakrabban?", "s": "A Föld", "w": ["Vulkáni lávában", "Olvadt magmában", "Frissen hullott hóban"]},
  {"a": "Ősi élőlény nyoma", "p": "Mi a kövület?", "s": "A Föld", "w": ["Régi kőszerszám", "Vulkáni kőzetdarab", "Különleges tengeri kavics"]},
  {"a": "66 millió éve", "p": "Mikor haltak ki a dinoszauruszok?", "s": "A Föld", "w": ["1 millió éve", "10 ezer éve", "500 millió éve"]},
  {"a": "Egy nagy becsapódás", "p": "Mi okozta valószínűleg a dinoszauruszok kihalását?", "s": "A Föld", "w": ["Egy hatalmas árvíz", "Egy hosszú jégkorszak", "A tengerek kiszáradása"]},
  {"a": "A gravitáció", "p": "Mi húz mindent a Föld középpontja felé?", "s": "Fizika a hétköznapokban", "w": ["A súrlódás", "A légnyomás", "A mágnesesség"]},
  {"a": "Newton", "p": "Ki írta le a gravitáció törvényét?", "s": "Fizika a hétköznapokban", "w": ["Galilei", "Kepler", "Arkhimédész"]},
  {"a": "Egyszerre érnek le", "p": "Melyik tárgy esik gyorsabban légüres térben?", "s": "Fizika a hétköznapokban", "w": ["A nehezebb tárgy", "A könnyebb tárgy", "A nagyobb felületű"]},
  {"a": "A súrlódás", "p": "Mi lassítja a mozgó tárgyat a földön?", "s": "Fizika a hétköznapokban", "w": ["A gravitáció", "A légnyomás", "A mágnesesség"]},
  {"a": "Kitágítja", "p": "Mit tesz a hő a fémekkel?", "s": "Fizika a hétköznapokban", "w": ["Összehúzza", "Megkeményíti", "Elszínteleníti"]},
  {"a": "Felfelé", "p": "Merre száll a meleg levegő?", "s": "Fizika a hétköznapokban", "w": ["Lefelé", "Oldalra", "Körbe-körbe"]},
  {"a": "Könnyebb a víznél", "p": "Miért úszik a fa a vízen?", "s": "Fizika a hétköznapokban", "w": ["Nagyobb a víznél", "Melegebb a víznél", "Több levegőt tartalmaz"]},
  {"a": "A felhajtóerő", "p": "Melyik erő emeli meg a testet a vízben?", "s": "Fizika a hétköznapokban", "w": ["A súrlódás", "A gravitáció", "A központi erő"]},
  {"a": "Az áramerősséget", "p": "Mit mérünk amperben?", "s": "Fizika a hétköznapokban", "w": ["A feszültséget", "Az ellenállást", "Az elektromos munkát"]},
  {"a": "A feszültséget", "p": "Mit mérünk voltban?", "s": "Fizika a hétköznapokban", "w": ["Az ellenállást", "A teljesítményt", "Az áramerősséget"]},
  {"a": "A teljesítményt", "p": "Mit mérünk wattban?", "s": "Fizika a hétköznapokban", "w": ["A feszültséget", "Az ellenállást", "Az áramerősséget"]},
  {"a": "A réz", "p": "Melyik anyag vezeti jól az áramot?", "s": "Fizika a hétköznapokban", "w": ["A fa", "A gumi", "A műanyag"]},
  {"a": "A gumi", "p": "Melyik anyag szigetel jól?", "s": "Fizika a hétköznapokban", "w": ["A réz", "A vas", "Az alumínium"]},
  {"a": "A mágnes", "p": "Mi vonzza a vasat?", "s": "Fizika a hétköznapokban", "w": ["A réz", "A fa", "A műanyag"]},
  {"a": "Kettő", "p": "Hány pólusa van a mágnesnek?", "s": "Fizika a hétköznapokban", "w": ["Egy", "Három", "Négy"]},
  {"a": "Taszítják egymást", "p": "Mi történik két azonos mágnespólussal?", "s": "Fizika a hétköznapokban", "w": ["Vonzzák egymást", "Összeolvadnak", "Semmi sem történik"]},
  {"a": "Északra", "p": "Merre mutat az iránytű?", "s": "Fizika a hétköznapokban", "w": ["Délre", "Keletre", "Nyugatra"]},
  {"a": "300 ezer km/s", "p": "Mekkora a fény sebessége nagyjából?", "s": "Fizika a hétköznapokban", "w": ["3 ezer km/s", "30 ezer km/s", "3 millió km/s"]},
  {"a": "A fény", "p": "Melyik gyorsabb: a fény vagy a hang?", "s": "Fizika a hétköznapokban", "w": ["A hang", "Egyforma", "Attól függ"]},
  {"a": "Légüres térben", "p": "Miben nem terjed a hang?", "s": "Fizika a hétköznapokban", "w": ["Vízben", "Fémben", "Meleg levegőben"]},
  {"a": "A rezgésszámtól", "p": "Mitől függ a hang magassága?", "s": "Fizika a hétköznapokban", "w": ["A hangerőtől", "A távolságtól", "A levegő nyomásától"]},
  {"a": "Visszaverődő hang", "p": "Mi a visszhang?", "s": "Fizika a hétköznapokban", "w": ["Nagyon halk hang", "Két egyforma hang", "Lassan terjedő hang"]},
  {"a": "A szivárvány színeire", "p": "Milyen színekre bontja a fényt a prizma?", "s": "Fizika a hétköznapokban", "w": ["Sárgára és zöldre", "Fekete-fehér színekre", "Csak a pirosra és kékre"]},
  {"a": "Mindet", "p": "Melyik színt nyeli el a fekete ruha?", "s": "Fizika a hétköznapokban", "w": ["Csak a pirosat", "Csak a kéket", "Egyet sem"]},
  {"a": "Elnyeli a fényt", "p": "Miért melegszik fel jobban a sötét ruha?", "s": "Fizika a hétköznapokban", "w": ["Vastagabb anyagú", "Szorosabban szőtt", "Visszaveri a fényt"]},
  {"a": "Visszaverődik", "p": "Mi történik a fénnyel a tükörnél?", "s": "Fizika a hétköznapokban", "w": ["Elnyelődik", "Szétszóródik", "Megtörik és eltűnik"]},
  {"a": "Megtörik a fény", "p": "Miért látszik törtnek a kanál a vízben?", "s": "Fizika a hétköznapokban", "w": ["Lassabban mozog", "Meghajlik a kanál", "Nagyobbnak látszik"]},
  {"a": "Emelő", "p": "Milyen egyszerű gép az olló?", "s": "Fizika a hétköznapokban", "w": ["Csiga", "Lejtő", "Csavar"]},
  {"a": "Az emelést", "p": "Mit könnyít meg a csiga használata?", "s": "Fizika a hétköznapokban", "w": ["A forgatást", "A hűtést", "A mérést"]},
  {"a": "Munkavégző képességet", "p": "Mit nevezünk energiának?", "s": "Fizika a hétköznapokban", "w": ["Nagy sebességet", "Erős mágnesességet", "Hosszan tartó mozgást"]},
  {"a": "Mozgási energia", "p": "Milyen energia van a mozgó tárgyban?", "s": "Fizika a hétköznapokban", "w": ["Hőenergia", "Vegyi energia", "Helyzeti energia"]},
  {"a": "Fénnyé és hővé", "p": "Mivé alakul az áram a villanykörtében?", "s": "Fizika a hétköznapokban", "w": ["Hanggá és rezgéssé", "Mágnesességgé", "Mozgási energiává"]},
  {"a": "A szél", "p": "Mi hajtja a szélmalom kerekét?", "s": "Fizika a hétköznapokban", "w": ["A víz", "A gőz", "Az elektromosság"]},
  {"a": "A gőz", "p": "Mi hajtja a gőzgépet?", "s": "Fizika a hétköznapokban", "w": ["A szél", "A víz", "Az elektromosság"]},
  {"a": "Vezetéssel", "p": "Hogyan terjed a hő a fémrúdban?", "s": "Fizika a hétköznapokban", "w": ["Áramlással", "Sugárzással", "Kisugárzással"]},
  {"a": "Sugárzással", "p": "Hogyan jut el a Nap melege a Földre?", "s": "Fizika a hétköznapokban", "w": ["Vezetéssel", "Áramlással", "A szél útján"]},
  {"a": "Nő", "p": "Mi történik a víz térfogatával fagyáskor?", "s": "Fizika a hétköznapokban", "w": ["Csökken", "Nem változik", "Felére csökken"]},
  {"a": "Kisebb", "p": "Milyen a jég sűrűsége a vízéhez képest?", "s": "Fizika a hétköznapokban", "w": ["Nagyobb", "Azonos", "Sokkal nagyobb"]},
  {"a": "Fordított", "p": "Milyen a tükörkép a valósághoz képest?", "s": "Fizika a hétköznapokban", "w": ["Kisebb", "Nagyobb", "Színtelen"]},
  {"a": "A szárny", "p": "Mi tartja fenn a repülőgépet a levegőben?", "s": "Fizika a hétköznapokban", "w": ["A motor", "A kerék", "A légcsavar"]},
  {"a": "A meleg levegő", "p": "Mi emeli fel a hőlégballont?", "s": "Fizika a hétköznapokban", "w": ["A sűrű levegő", "A hideg levegő", "Az erős oldalszél"]},
  {"a": "Nitrogénből", "p": "Melyik gázból van a legtöbb a levegőben?", "s": "Kémia", "w": ["Oxigénből", "Hidrogénből", "Szén-dioxidból"]},
  {"a": "21 százalék", "p": "Hány százalék oxigén van a levegőben?", "s": "Kémia", "w": ["10 százalék", "50 százalék", "78 százalék"]},
  {"a": "H2O", "p": "Mi a víz vegyjele?", "s": "Kémia", "w": ["CO2", "O2", "NaCl"]},
  {"a": "Hidrogénből és oxigénből", "p": "Melyik két elemből áll a víz?", "s": "Kémia", "w": ["Szénből és oxigénből", "Nitrogénből és szénből", "Hidrogénből és nitrogénből"]},
  {"a": "Nátrium-klorid", "p": "Mi a konyhasó vegyi neve?", "s": "Kémia", "w": ["Kálium-nitrát", "Magnézium-oxid", "Kalcium-karbonát"]},
  {"a": "CO2", "p": "Mi a szén-dioxid vegyjele?", "s": "Kémia", "w": ["CO", "H2O", "O2"]},
  {"a": "Oxigénre", "p": "Melyik gázra van szükségünk a légzéshez?", "s": "Kémia", "w": ["Nitrogénre", "Hidrogénre", "Szén-dioxidra"]},
  {"a": "A hidrogén", "p": "Melyik a legkönnyebb elem?", "s": "Kémia", "w": ["A hélium", "Az oxigén", "A nitrogén"]},
  {"a": "Héliummal", "p": "Melyik gázzal töltik a szálló léggömböt?", "s": "Kémia", "w": ["Oxigénnel", "Nitrogénnel", "Szén-dioxiddal"]},
  {"a": "Három", "p": "Hány halmazállapota van a víznek?", "s": "Kémia", "w": ["Kettő", "Négy", "Öt"]},
  {"a": "Szilárd", "p": "Mi a víz halmazállapota 0 fok alatt?", "s": "Kémia", "w": ["Légnemű", "Folyékony", "Cseppfolyós"]},
  {"a": "Szilárdból folyékony", "p": "Mit nevezünk olvadásnak?", "s": "Kémia", "w": ["Folyékonyból szilárd", "Folyékonyból légnemű", "Légneműből folyékony"]},
  {"a": "Folyékonyból szilárd", "p": "Mit nevezünk fagyásnak?", "s": "Kémia", "w": ["Légneműből szilárd", "Szilárdból folyékony", "Folyékonyból légnemű"]},
  {"a": "A rozsda", "p": "Mi támadja meg a vasat a levegőn?", "s": "Kémia", "w": ["A meleg", "A fény", "A szárazság"]},
  {"a": "Víz és levegő", "p": "Mi kell a rozsdásodáshoz?", "s": "Kémia", "w": ["Hő és fény", "Só és cukor", "Olaj és festék"]},
  {"a": "Oxigén", "p": "Melyik gáz kell az égéshez?", "s": "Kémia", "w": ["Nitrogén", "Hidrogén", "Szén-dioxid"]},
  {"a": "Vízzel", "p": "Mivel oltjuk el legkönnyebben a tüzet?", "s": "Kémia", "w": ["Olajjal", "Benzinnel", "Szeszes itallal"]},
  {"a": "A higany", "p": "Melyik fém folyékony szobahőmérsékleten?", "s": "Kémia", "w": ["A vas", "Az ólom", "Az alumínium"]},
  {"a": "Alumíniumból", "p": "Melyik fémből készül a könnyű konzervdoboz?", "s": "Kémia", "w": ["Ólomból", "Rézből", "Rozsdamentes acélból"]},
  {"a": "A rezet", "p": "Melyik fémet használják a vezetékekben?", "s": "Kémia", "w": ["Az ólmot", "A higanyt", "Az alumíniumot"]},
  {"a": "Vasból és szénből", "p": "Miből készül az acél?", "s": "Kémia", "w": ["Rézből és ónból", "Ólomból és cinkből", "Alumíniumból és vasból"]},
  {"a": "Rézből és ónból", "p": "Miből készül a bronz?", "s": "Kémia", "w": ["Vasból és szénből", "Ólomból és cinkből", "Ezüstből és aranyból"]},
  {"a": "Au", "p": "Mi az arany vegyjele?", "s": "Kémia", "w": ["Ag", "Fe", "Cu"]},
  {"a": "Fe", "p": "Mi a vas vegyjele?", "s": "Kémia", "w": ["Va", "Fa", "Ir"]},
  {"a": "O", "p": "Mi az oxigén vegyjele?", "s": "Kémia", "w": ["Ox", "Og", "On"]},
  {"a": "Mengyelejev", "p": "Ki alkotta meg az elemek első rendszerét?", "s": "Kémia", "w": ["Newton", "Lavoisier", "Arkhimédész"]},
  {"a": "Az atommag", "p": "Mi van az atom közepén?", "s": "Kémia", "w": ["A proton", "A molekula", "Az elektron"]},
  {"a": "Az elektron", "p": "Mi kering az atommag körül?", "s": "Kémia", "w": ["A proton", "A neutron", "Egy másik atommag"]},
  {"a": "Negatív", "p": "Milyen töltésű az elektron?", "s": "Kémia", "w": ["Pozitív", "Változó", "Semleges"]},
  {"a": "Savanyú", "p": "Milyen ízű a savas anyag?", "s": "Kémia", "w": ["Édes", "Sós", "Kesernyés"]},
  {"a": "Piros színt", "p": "Mit mutat a lakmuszpapír savban?", "s": "Kémia", "w": ["Kék színt", "Zöld színt", "Sárgás színt"]},
  {"a": "Lúgos", "p": "Milyen kémhatású a szódabikarbóna?", "s": "Kémia", "w": ["Savas", "Semleges", "Íztelen"]},
  {"a": "Só és víz", "p": "Mi keletkezik sav és lúg találkozásakor?", "s": "Kémia", "w": ["Csak gáz", "Olaj és gőz", "Cukor és levegő"]},
  {"a": "Feloldódik", "p": "Mi történik a cukorral a vízben?", "s": "Kémia", "w": ["Megfagy", "Elpárolog", "Kicsapódik"]},
  {"a": "Az olaj", "p": "Melyik anyag nem oldódik vízben?", "s": "Kémia", "w": ["A só", "A cukor", "A szódabikarbóna"]},
  {"a": "Vízből", "p": "Miből van a legtöbb az élő szervezetben?", "s": "Kémia", "w": ["Zsírból", "Fehérjéből", "Szénhidrátból"]},
  {"a": "A penicillint", "p": "Melyik gyógyszert fedezte fel Fleming?", "s": "Feltalálók és felfedezések", "w": ["Az aszpirint", "Az inzulint", "A szulfonamidot"]},
  {"a": "Hőkezelés", "p": "Mit jelent a pasztőrözés?", "s": "Feltalálók és felfedezések", "w": ["Szárítás", "Erjesztés", "Fagyasztás"]},
  {"a": "Jenner", "p": "Ki fedezte fel a himlő elleni védőoltást?", "s": "Feltalálók és felfedezések", "w": ["Pasteur", "Fleming", "Semmelweis"]},
  {"a": "Koch", "p": "Ki fedezte fel a tuberkulózis baktériumát?", "s": "Feltalálók és felfedezések", "w": ["Pasteur", "Fleming", "Semmelweis"]},
  {"a": "Marie Curie", "p": "Ki fedezte fel a rádiumot?", "s": "Feltalálók és felfedezések", "w": ["Ida Noddack", "Lise Meitner", "Dorothy Hodgkin"]},
  {"a": "A polóniumot", "p": "Melyik elemet nevezte el Marie Curie a hazájáról?", "s": "Feltalálók és felfedezések", "w": ["Az uránt", "A rádiumot", "A plutóniumot"]},
  {"a": "Hooke", "p": "Ki fedezte fel a sejtet mikroszkóppal?", "s": "Feltalálók és felfedezések", "w": ["Newton", "Darwin", "Mengyelejev"]},
  {"a": "Mendel", "p": "Ki kutatta a borsó öröklődését?", "s": "Feltalálók és felfedezések", "w": ["Linné", "Darwin", "Pasteur"]},
  {"a": "Linné", "p": "Ki alkotta meg az élőlények kettős nevezéktanát?", "s": "Feltalálók és felfedezések", "w": ["Darwin", "Mendel", "Pasteur"]},
  {"a": "Az elemet", "p": "Mit talált fel Volta?", "s": "Feltalálók és felfedezések", "w": ["A dinamót", "A mágnest", "A transzformátort"]},
  {"a": "A hőlégballont", "p": "Mit alkottak meg a Montgolfier fivérek?", "s": "Feltalálók és felfedezések", "w": ["A gőzhajót", "A repülőgépet", "A léghajómotort"]},
  {"a": "A Lumière fivérek", "p": "Kik tartották az első nyilvános filmvetítést?", "s": "Feltalálók és felfedezések", "w": ["Edison és Tesla", "A Wright fivérek", "A Montgolfier fivérek"]},
  {"a": "Röntgen", "p": "Ki fedezte fel a röntgensugárzást?", "s": "Feltalálók és felfedezések", "w": ["Curie", "Edison", "Becquerel"]},
  {"a": "A Celsius", "p": "Melyik hőmérsékleti skála visel svéd tudósnevet?", "s": "Feltalálók és felfedezések", "w": ["A Kelvin", "A Réaumur", "A Fahrenheit"]},
  {"a": "Kelvinről", "p": "Kiről nevezték el az abszolút hőmérsékleti skálát?", "s": "Feltalálók és felfedezések", "w": ["Newtonról", "Celsiusról", "Fahrenheitről"]},
  {"a": "Harvey", "p": "Ki írta le elsőként a vérkeringést?", "s": "Feltalálók és felfedezések", "w": ["Galénosz", "Paracelsus", "Hippokratész"]},
  {"a": "Rutherford", "p": "Ki fedezte fel az atommagot?", "s": "Feltalálók és felfedezések", "w": ["Bohr", "Thomson", "Mengyelejev"]},
  {"a": "Bohr", "p": "Ki alkotta meg az atom bolygómodelljét?", "s": "Feltalálók és felfedezések", "w": ["Thomson", "Rutherford", "Mengyelejev"]},
  {"a": "A radioaktivitást", "p": "Mit fedezett fel Becquerel?", "s": "Feltalálók és felfedezések", "w": ["A mágnesességet", "A röntgensugarat", "Az elektromosságot"]},
  {"a": "Kettős spirál", "p": "Milyen alakú a DNS?", "s": "Feltalálók és felfedezések", "w": ["Kerek gyűrű", "Egyenes szál", "Háromszög alakú"]},
  {"a": "A fonográfot", "p": "Mit alkotott Edison a hang rögzítésére?", "s": "Feltalálók és felfedezések", "w": ["A rádiót", "A telefont", "A magnetofont"]},
  {"a": "A barométert", "p": "Mit talált fel Torricelli?", "s": "Feltalálók és felfedezések", "w": ["A hőmérőt", "A távcsövet", "A mikroszkópot"]},
  {"a": "Newtonról", "p": "Melyik tudósról nevezték el az erő egységét?", "s": "Feltalálók és felfedezések", "w": ["Wattról", "Joule-ról", "Pascalról"]},
  {"a": "Pascalról", "p": "Melyik tudósról nevezték el a nyomás egységét?", "s": "Feltalálók és felfedezések", "w": ["Wattról", "Newtonról", "Joule-ról"]},
  {"a": "1921-ben", "p": "Melyik évben kapott Einstein Nobel-díjat?", "s": "Feltalálók és felfedezések", "w": ["1905-ben", "1915-ben", "1933-ban"]},
  {"a": "A C-vitamint", "p": "Melyik vitamint nevezik aszkorbinsavnak?", "s": "Magyar tudósok", "w": ["A D-vitamint", "A B-vitamint", "Az A-vitamint"]},
  {"a": "A paprikából", "p": "Melyik növényből nyert Szent-Györgyi sok C-vitamint?", "s": "Magyar tudósok", "w": ["A répából", "A citromból", "A burgonyából"]},
  {"a": "Orvosit", "p": "Milyen Nobel-díjat kapott Szent-Györgyi Albert?", "s": "Magyar tudósok", "w": ["Fizikait", "Kémiait", "Közgazdaságit"]},
  {"a": "Fizikában", "p": "Melyik tudományágban kapott Nobel-díjat Wigner Jenő?", "s": "Magyar tudósok", "w": ["Kémiában", "Irodalomban", "Orvostudományban"]},
  {"a": "Kémiában", "p": "Melyik tudományágban kapott Nobel-díjat Oláh György?", "s": "Magyar tudósok", "w": ["Fizikában", "Orvostudományban", "Közgazdaságtanban"]},
  {"a": "Eötvös Lorándról", "p": "Kiről nevezték el a híres torziós ingát?", "s": "Magyar tudósok", "w": ["Bay Zoltánról", "Jedlik Ányosról", "Szent-Györgyi Albertről"]},
  {"a": "A fülért", "p": "Melyik szerv kutatásáért kapott Nobel-díjat Békésy György?", "s": "Magyar tudósok", "w": ["A szemért", "A szívért", "A veséért"]},
  {"a": "Karikó Katalin", "p": "Melyik magyar kutató munkája segítette az mRNS-vakcinát?", "s": "Magyar tudósok", "w": ["Békésy György", "Hevesy György", "Szent-Györgyi Albert"]},
  {"a": "2023-ban", "p": "Melyik évben kapott Nobel-díjat Karikó Katalin?", "s": "Magyar tudósok", "w": ["2003-ban", "2013-ban", "2020-ban"]},
  {"a": "Hat", "p": "Hány színe van a klasszikus Rubik-kockának?", "s": "Magyar tudósok", "w": ["Négy", "Nyolc", "Tizenkettő"]},
  {"a": "Kilencből", "p": "Hány kis lapból áll a Rubik-kocka egy oldala?", "s": "Magyar tudósok", "w": ["Négyből", "Hatból", "Tizenhatból"]},
  {"a": "Építészmérnökit", "p": "Milyen diplomát szerzett Rubik Ernő?", "s": "Magyar tudósok", "w": ["Gépészmérnökit", "Vegyészmérnökit", "Villamosmérnökit"]},
  {"a": "Háromból", "p": "Hány kockából áll a Rubik-kocka egy éle?", "s": "Magyar tudósok", "w": ["Kettőből", "Négyből", "Ötből"]},
  {"a": "A golyóstollat", "p": "Mit neveznek Argentínában biroménak?", "s": "Magyar tudósok", "w": ["A ceruzát", "A töltőtollat", "Az írógépszalagot"]},
  {"a": "Argentínába", "p": "Melyik országba emigrált Bíró László József?", "s": "Magyar tudósok", "w": ["Kanadába", "Brazíliába", "Franciaországba"]},
  {"a": "A szódavízét", "p": "Melyik ital készítését kötik Jedlik Ányos nevéhez?", "s": "Magyar tudósok", "w": ["A sörét", "A limonádéét", "Az ásványvízét"]},
  {"a": "A fizikát", "p": "Milyen tantárgyat tanított Jedlik Ányos?", "s": "Magyar tudósok", "w": ["A kémiát", "A biológiát", "A matematikát"]},
  {"a": "A gyermekágyi láz ellen", "p": "Melyik betegség ellen küzdött Semmelweis Ignác?", "s": "Magyar tudósok", "w": ["A tüdőgyulladás ellen", "A gyermekbénulás ellen", "A csonttuberkulózis ellen"]},
  {"a": "A Holdról", "p": "Melyik égitestről vert vissza rádiójelet Bay Zoltán?", "s": "Magyar tudósok", "w": ["A Marsról", "A Vénuszról", "A Jupiterről"]},
  {"a": "Lézerre", "p": "Mire van szükség a hologram készítéséhez?", "s": "Magyar tudósok", "w": ["Vakura", "Nagyítóra", "Színes szűrőre"]},
  {"a": "A BASIC-et", "p": "Melyik programozási nyelvet alkotta meg Kemény János?", "s": "Magyar tudósok", "w": ["A COBOL-t", "A PASCAL-t", "A FORTRAN-t"]},
  {"a": "Selye János", "p": "Melyik magyar tudós kutatta a stresszt?", "s": "Magyar tudósok", "w": ["Békésy György", "Hevesy György", "Szent-Györgyi Albert"]},
  {"a": "Semmelweisét", "p": "Melyik magyar tudós nevét viseli a budapesti orvosi egyetem?", "s": "Magyar tudósok", "w": ["Jedlikét", "Eötvösét", "Szent-Györgyiét"]},
  {"a": "A villanyórát", "p": "Mit talált fel Bláthy Ottó Titusz?", "s": "Magyar tudósok", "w": ["A vasalót", "A villanykörtét", "A villanymotort"]}
]
$questions$::jsonb)
  with ordinality as question(item, ordinality);

do $validation$
begin
  if (
    select count(*) from public.quiz_questions
    where category_id = 'magyar_tudomany' and is_active
  ) <> 519 then
    raise exception 'Természet és tudomány must contain exactly 519 active questions';
  end if;

  if exists (
    select 1
    from public.quiz_questions as question
    where question.category_id = 'magyar_tudomany'
      and (
        cardinality(question.wrong_answers) <> 3
        or (
          select count(distinct lower(trim(answer)))
          from unnest(question.wrong_answers) as answer
        ) <> 3
        or exists (
          select 1
          from unnest(question.wrong_answers) as answer
          where lower(trim(answer)) = lower(trim(question.correct_answer))
        )
      )
  ) then
    raise exception 'Természet és tudomány: every question needs three distinct wrong answers';
  end if;

  if exists (
    select 1
    from public.quiz_questions as proposed
    join public.quiz_questions as existing
      on lower(trim(existing.prompt)) = lower(trim(proposed.prompt))
     and existing.id <> proposed.id
    where proposed.category_id = 'magyar_tudomany'
  ) then
    raise exception 'Természet és tudomány: a prompt is already used by another question';
  end if;
end;
$validation$;
