-- Ahogy régen volt: 388 questions in Hungarian.
--
-- Written so the correct answer is never the longest option -- the tell that
-- made the Psychology bank guessable without reading the prompt. All four
-- choices share one type and grammatical form.
insert into public.quiz_questions (
  id,
  category_id,
  prompt,
  correct_answer,
  wrong_answers,
  language_code,
  grade_level,
  subject,
  display_order,
  is_active
)
select
  'regen_volt_' || lpad(question.ordinality::text, 4, '0'),
  'regen_volt',
  question.item ->> 'p',
  question.item ->> 'a',
  array(select jsonb_array_elements_text(question.item -> 'w')),
  'hu',
  null,
  question.item ->> 's',
  question.ordinality::integer,
  true
from jsonb_array_elements($questions$
[
  {"a": "NDK", "p": "Melyik országban gyártották a Trabantot?", "s": "Közlekedés", "w": ["Szovjetunió", "Csehszlovákia", "Lengyelország"]},
  {"a": "Duroplast", "p": "Miből készült a Trabant karosszériája?", "s": "Közlekedés", "w": ["Üvegszálas műanyag", "Horganyzott acél", "Öntött alumínium"]},
  {"a": "Kétütemű", "p": "Hányütemű motor volt a Trabantban?", "s": "Közlekedés", "w": ["Hatütemű", "Nyolcütemű", "Négyütemű"]},
  {"a": "NDK", "p": "Hol gyártották a Wartburgot?", "s": "Közlekedés", "w": ["Szovjetunió", "Románia", "Jugoszlávia"]},
  {"a": "Wartburg", "p": "Melyik autónak volt háromhengeres kétütemű motorja?", "s": "Közlekedés", "w": ["Moszkvics", "Polski Fiat", "Zsiguli"]},
  {"a": "Szovjetunió", "p": "Melyik országban készült a Zsiguli?", "s": "Közlekedés", "w": ["Csehszlovákia", "Bulgária", "Lengyelország"]},
  {"a": "Zsiguli", "p": "Milyen néven ismerték nálunk az első Ladákat?", "s": "Közlekedés", "w": ["Pobeda", "Volga", "Moszkvics"]},
  {"a": "Skoda", "p": "Melyik autómárka volt csehszlovák?", "s": "Közlekedés", "w": ["Dácia", "Trabant", "Wartburg"]},
  {"a": "Dácia", "p": "Melyik autómárka volt román gyártmány?", "s": "Közlekedés", "w": ["Trabant", "Moszkvics", "Skoda"]},
  {"a": "Kispolszki", "p": "Mi volt a kis Polski Fiat beceneve?", "s": "Közlekedés", "w": ["Papírautó", "Bogárhátú", "Nagypolszki"]},
  {"a": "Autóbuszt", "p": "Mit gyártott az Ikarus?", "s": "Közlekedés", "w": ["Kerékpárt", "Villamost", "Motorkerékpárt"]},
  {"a": "Ikarus", "p": "Melyik magyar gyár készítette a csuklós buszokat?", "s": "Közlekedés", "w": ["Rába", "Csepel", "Videoton"]},
  {"a": "Csepel", "p": "Melyik volt a legismertebb magyar kerékpármárka?", "s": "Közlekedés", "w": ["Videoton", "Rába", "Ikarus"]},
  {"a": "Magyar Államvasutak", "p": "Mit jelent a MÁV rövidítés?", "s": "Közlekedés", "w": ["Magyar Autóbusz Vállalat", "Magyar Áruszállító Vállalat", "Magyar Állami Volánjárat"]},
  {"a": "Budapest", "p": "Melyik magyar városban járt metró?", "s": "Közlekedés", "w": ["Szeged", "Debrecen", "Székesfehérvár"]},
  {"a": "Sárga", "p": "Milyen színű a budapesti kisföldalatti?", "s": "Közlekedés", "w": ["Piros", "Világoszöld", "Kék"]},
  {"a": "Piros", "p": "Milyen színű a kettes metró a térképen?", "s": "Közlekedés", "w": ["Zöld", "Sárga", "Világoskék"]},
  {"a": "Kék", "p": "Milyen színű a hármas metró a térképen?", "s": "Közlekedés", "w": ["Sárga", "Piros", "Halványzöld"]},
  {"a": "Zöld", "p": "Milyen színűek voltak a HÉV szerelvényei?", "s": "Közlekedés", "w": ["Sárga", "Piros", "Világoskék"]},
  {"a": "Helyiérdekű vasút", "p": "Mit jelent a HÉV rövidítés?", "s": "Közlekedés", "w": ["Hegyi Érdekű Vasút", "Határon Érkező Vasút", "Helyi Építésű Vasút"]},
  {"a": "Trolibusz", "p": "Melyik jármű megy árammal, de gumikerekű?", "s": "Közlekedés", "w": ["Autóbusz", "Villamos", "Fogaskerekű"]},
  {"a": "Sárga", "p": "Milyen színűek a budapesti villamosok?", "s": "Közlekedés", "w": ["Világoskék", "Zöld", "Piros"]},
  {"a": "Ganz", "p": "Melyik magyar gyár készített villamost és vonatot?", "s": "Közlekedés", "w": ["Csepel", "Ikarus", "Videoton"]},
  {"a": "Szántód és Tihany", "p": "Hol járt a balatoni autós komp?", "s": "Közlekedés", "w": ["Siófok és Keszthely", "Fonyód és Badacsony", "Balatonfüred és Siófok"]},
  {"a": "Malév", "p": "Melyik volt a magyar légitársaság?", "s": "Közlekedés", "w": ["Aeroflot", "Interflug", "Balkan Air"]},
  {"a": "NDK", "p": "Melyik ország légitársasága volt az Interflug?", "s": "Közlekedés", "w": ["Bulgária", "Csehszlovákia", "Lengyelország"]},
  {"a": "Ferihegy", "p": "Hogy hívták Budapest repülőterét?", "s": "Közlekedés", "w": ["Tököl", "Mátyásföld", "Budaörs"]},
  {"a": "Volán", "p": "Melyik vállalat járatta a helyközi buszokat?", "s": "Közlekedés", "w": ["Hungarocamion", "BKV", "MÁV"]},
  {"a": "BKV", "p": "Melyik vállalat járatai vitték az utast Budapesten?", "s": "Közlekedés", "w": ["Malév", "Volán", "MÁV"]},
  {"a": "A fogaskerekű", "p": "Melyik jármű megy fel a Svábhegyre?", "s": "Közlekedés", "w": ["A gyermekvasút", "A sikló", "A libegő"]},
  {"a": "Gyerekek", "p": "Kik adták a szolgálatot az Úttörővasúton?", "s": "Közlekedés", "w": ["Katonák", "Vasutasok", "Nyugdíjasok"]},
  {"a": "Teherautót", "p": "Mit gyártott a Csepel Autógyár?", "s": "Közlekedés", "w": ["Villamost", "Motorkerékpárt", "Kerékpárt"]},
  {"a": "Győr", "p": "Melyik városban működött a Rába gyár?", "s": "Közlekedés", "w": ["Miskolc", "Székesfehérvár", "Szeged"]},
  {"a": "Pannónia", "p": "Melyik volt a legismertebb magyar motorkerékpár?", "s": "Közlekedés", "w": ["Berva", "Simson", "Csepel Danuvia"]},
  {"a": "NDK", "p": "Melyik országból jött a Simson kismotor?", "s": "Közlekedés", "w": ["Bulgária", "Csehszlovákia", "Lengyelország"]},
  {"a": "Furgon", "p": "Milyen jármű volt a Barkas?", "s": "Közlekedés", "w": ["Motorkerékpár", "Személyautó", "Autóbusz"]},
  {"a": "Lengyel", "p": "Melyik ország gyára készítette a Nysa kisbuszt?", "s": "Közlekedés", "w": ["Kelet-német", "Jugoszláv", "Csehszlovák"]},
  {"a": "Volga", "p": "Melyik szovjet autó volt gyakori taxi nálunk?", "s": "Közlekedés", "w": ["Moszkvics", "Csajka", "Zaporozsec"]},
  {"a": "Főtaxi", "p": "Melyik volt a legnagyobb budapesti taxivállalat?", "s": "Közlekedés", "w": ["Volántaxi", "Rádiótaxi", "Budataxi"]},
  {"a": "Olajat", "p": "Mit kellett a kétütemű autók benzinjébe keverni?", "s": "Közlekedés", "w": ["Fagyállót", "Alkoholt", "Vizet"]},
  {"a": "A közlekedést", "p": "Mit szabályoz a KRESZ?", "s": "Közlekedés", "w": ["A munkaidőt", "Az adózást", "Az iskolai rendet"]},
  {"a": "Vasúti étkezde", "p": "Mi volt az Utasellátó?", "s": "Közlekedés", "w": ["Utazási iroda", "Jegypénztár", "Autóbusz-állomás"]},
  {"a": "Kamionnal", "p": "Mivel szállított a Hungarocamion?", "s": "Közlekedés", "w": ["Vonattal", "Hajóval", "Repülőgéppel"]},
  {"a": "NDK", "p": "Melyik országból jöttek az IFA teherautók?", "s": "Közlekedés", "w": ["Románia", "Bulgária", "Csehszlovákia"]},
  {"a": "Szovjetunió", "p": "Melyik országból származott a Moszkvics?", "s": "Közlekedés", "w": ["NDK", "Lengyelország", "Csehszlovákia"]},
  {"a": "A sikló", "p": "Melyik jármű visz fel a budai Várba?", "s": "Közlekedés", "w": ["A gyermekvasút", "A fogaskerekű", "A libegő"]},
  {"a": "A János-hegyre", "p": "Hova visz fel a budapesti libegő?", "s": "Közlekedés", "w": ["A Sas-hegyre", "A Hármashatár-hegyre", "A Gellért-hegyre"]},
  {"a": "Élelmiszert", "p": "Mit lehetett kapni a Közértben?", "s": "Bolt és vásárlás", "w": ["Építőanyagot", "Ruhát", "Bútort"]},
  {"a": "Önkiszolgáló bolt", "p": "Mit jelentett az ABC felirat a bolton?", "s": "Bolt és vásárlás", "w": ["Áruházi bemutatóterem", "Állami bizományi bolt", "Alkatrészraktár"]},
  {"a": "Élelmiszert", "p": "Mit árult a Csemege bolthálózat?", "s": "Bolt és vásárlás", "w": ["Cipőt", "Háztartási gépet", "Bútort"]},
  {"a": "Skála", "p": "Melyik áruház kabalafigurája volt Kópé?", "s": "Bolt és vásárlás", "w": ["Centrum", "Corvin", "Divatcsarnok"]},
  {"a": "Kópé", "p": "Hogy hívták a Skála áruház kabalafiguráját?", "s": "Bolt és vásárlás", "w": ["Mókus", "Manó", "Maci"]},
  {"a": "Áruházlánc", "p": "Mi volt a Centrum?", "s": "Bolt és vásárlás", "w": ["Utazási iroda", "Vendéglátó vállalat", "Takarékpénztár"]},
  {"a": "A Corvin", "p": "Melyik áruház állt a Blaha Lujza téren?", "s": "Bolt és vásárlás", "w": ["A Divatcsarnok", "A Luxus Áruház", "A Skála Metró"]},
  {"a": "Nyugati", "p": "Melyik pályaudvarnál épült a Skála Metró?", "s": "Bolt és vásárlás", "w": ["Keleti", "Déli", "Kelenföld"]},
  {"a": "Ruhát", "p": "Mit árult a Divatcsarnok?", "s": "Bolt és vásárlás", "w": ["Háztartási gépet", "Bútort", "Élelmiszert"]},
  {"a": "Bútort", "p": "Mit árult a Domus áruház?", "s": "Bolt és vásárlás", "w": ["Ruhát", "Háztartási vegyi árut", "Élelmiszert"]},
  {"a": "Rádiót", "p": "Mit árult a Keravill?", "s": "Bolt és vásárlás", "w": ["Ruhaneműt", "Élelmiszert", "Építőanyagot"]},
  {"a": "Szemüveget", "p": "Mit lehetett venni az Ofotértben?", "s": "Bolt és vásárlás", "w": ["Élelmiszert", "Cipőt", "Építőanyagot"]},
  {"a": "Rövidárut", "p": "Mit árult a Röltex?", "s": "Bolt és vásárlás", "w": ["Háztartási gépet", "Élelmiszert", "Bútort"]},
  {"a": "Szenet", "p": "Mit lehetett venni a TÜZÉP-telepen?", "s": "Bolt és vásárlás", "w": ["Háztartási gépet", "Élelmiszert", "Ruhaneműt"]},
  {"a": "Zöldséget", "p": "Mit árult a Zöldért?", "s": "Bolt és vásárlás", "w": ["Cipőt", "Húskészítményt", "Írószert"]},
  {"a": "Használtat", "p": "Milyen árut árult a Bizományi Áruház?", "s": "Bolt és vásárlás", "w": ["Csak külföldit", "Csak újat", "Csak élelmiszert"]},
  {"a": "Cigarettát", "p": "Mit árultak a trafikban?", "s": "Bolt és vásárlás", "w": ["Tejet", "Kenyeret", "Háztartási gépet"]},
  {"a": "A piacon", "p": "Hol vettek a háziasszonyok friss zöldséget?", "s": "Bolt és vásárlás", "w": ["A Keravillban", "A Bizományiban", "A trafikban"]},
  {"a": "Szövetkezet", "p": "Mi volt az ÁFÉSZ?", "s": "Bolt és vásárlás", "w": ["Állami áruház", "Termelőszövetkezet", "Utazási iroda"]},
  {"a": "A betétdíjat", "p": "Mit fizettek vissza az üres üvegért?", "s": "Bolt és vásárlás", "w": ["Az árrést", "A vásárlási előleget", "A forgalmi adót"]},
  {"a": "Cekkerbe", "p": "Mibe pakolták a vásárlást a nejlonzacskó előtt?", "s": "Bolt és vásárlás", "w": ["Bőröndbe", "Vödörbe", "Papírdobozba"]},
  {"a": "Hiánycikk", "p": "Hogy hívták az árut, amit sehol nem lehetett kapni?", "s": "Bolt és vásárlás", "w": ["Kelendő áru", "Idénycikk", "Leértékelt áru"]},
  {"a": "Sorba állni", "p": "Mit kellett tenni, ha banán érkezett a boltba?", "s": "Bolt és vásárlás", "w": ["Előre fizetni", "Utalványt kérni", "Jegyet váltani"]},
  {"a": "Jegyet", "p": "Mit kellett benzinvásárláskor felmutatni az olajválság idején?", "s": "Bolt és vásárlás", "w": ["Utazási engedélyt", "Személyi igazolványt", "Munkakönyvet"]},
  {"a": "Budapest", "p": "Melyik városban nyílt az első magyar McDonald's?", "s": "Bolt és vásárlás", "w": ["Debrecen", "Szeged", "Székesfehérvár"]},
  {"a": "Pénzt", "p": "Mit küldhetett a külföldi rokon az IKKA-n keresztül?", "s": "Bolt és vásárlás", "w": ["Táviratot", "Csomagot", "Levelet"]},
  {"a": "Valutáért", "p": "Miért lehetett vásárolni az Intertouristban?", "s": "Bolt és vásárlás", "w": ["Csak utalványért", "Forintért", "Rubelért"]},
  {"a": "Jugoszláv", "p": "Melyik ország gyára volt a Gorenje?", "s": "Bolt és vásárlás", "w": ["Szovjet", "Csehszlovák", "Kelet-német"]},
  {"a": "Vasárnap", "p": "Melyik napon voltak zárva a boltok?", "s": "Bolt és vásárlás", "w": ["Pénteken", "Csütörtökön", "Szerdán"]},
  {"a": "Patikában", "p": "Hol lehetett gyógyszert venni?", "s": "Bolt és vásárlás", "w": ["A Közértben", "A trafikban", "A Röltexben"]},
  {"a": "A hentesnél", "p": "Kinél vásárolták a húst?", "s": "Bolt és vásárlás", "w": ["A cukrászdában", "A trafikban", "A zöldségesnél"]},
  {"a": "Edényt", "p": "Mit lehetett a háztartási boltban venni?", "s": "Bolt és vásárlás", "w": ["Építőanyagot", "Ruhaneműt", "Élelmiszert"]},
  {"a": "A bolt zárva van", "p": "Mit jelentett a Leltár tábla a bolt ajtaján?", "s": "Bolt és vásárlás", "w": ["Hosszabb nyitvatartás", "Új áru érkezett", "Kedvezményes vásár"]},
  {"a": "Magánbolt", "p": "Mi volt a maszek bolt?", "s": "Bolt és vásárlás", "w": ["Állami bolt", "Szövetkezeti bolt", "Külföldi bolt"]},
  {"a": "Pöttyös", "p": "Milyen mintás a Túró Rudi papírja?", "s": "Márkák és termékek", "w": ["Virágmintás", "Kockás", "Csíkos"]},
  {"a": "Pirosak", "p": "Milyen színűek a pöttyök a Túró Rudi papírján?", "s": "Márkák és termékek", "w": ["Aranyszínűek", "Kékek", "Zöldek"]},
  {"a": "Túró", "p": "Mi van a Túró Rudi belsejében?", "s": "Márkák és termékek", "w": ["Dió", "Lekvár", "Csokikrém"]},
  {"a": "Csokoládé", "p": "Mi van a Túró Rudi külsején?", "s": "Márkák és termékek", "w": ["Darált keksz", "Kókusz", "Cukormáz"]},
  {"a": "Szőlő", "p": "Milyen gyümölcs íze van a Traubisodának?", "s": "Márkák és termékek", "w": ["Alma", "Barack", "Fekete ribizli"]},
  {"a": "Üdítőital", "p": "Mi volt a Bambi?", "s": "Márkák és termékek", "w": ["Rágógumi", "Mosószer", "Gyümölcslekvár"]},
  {"a": "Üdítőital", "p": "Mi volt a Márka?", "s": "Márkák és termékek", "w": ["Fogkrém", "Konzervmárka", "Mosópor"]},
  {"a": "Ostyaszelet", "p": "Milyen édesség a Balaton szelet?", "s": "Márkák és termékek", "w": ["Cukorka", "Töltött bonbon", "Keksz"]},
  {"a": "Csokoládé", "p": "Milyen édesség a Sport szelet?", "s": "Márkák és termékek", "w": ["Cukorka", "Keksz", "Gyümölcszselé"]},
  {"a": "Paprikás", "p": "Milyen ízű a Piros Arany?", "s": "Márkák és termékek", "w": ["Fahéjas kakaós", "Édes", "Mentás"]},
  {"a": "Tubusban", "p": "Miben árulták a Piros Aranyat?", "s": "Márkák és termékek", "w": ["Üvegben", "Konzervdobozban", "Zacskóban"]},
  {"a": "Univer", "p": "Melyik gyár készíti a Piros Aranyat?", "s": "Márkák és termékek", "w": ["Győri Keksz", "Globus", "Szerencsi"]},
  {"a": "Csípős", "p": "Milyen az Erős Pista íze?", "s": "Márkák és termékek", "w": ["Keserű", "Savanyú", "Édes"]},
  {"a": "Konzervet", "p": "Mit gyártott a Globus?", "s": "Márkák és termékek", "w": ["Mosóport", "Cipőt", "Csokoládét"]},
  {"a": "Cipő", "p": "Milyen terméke volt a Tisza márkának?", "s": "Márkák és termékek", "w": ["Rádió", "Kerékpár", "Hűtőszekrény"]},
  {"a": "Martfű", "p": "Melyik városban készült a Tisza cipő?", "s": "Márkák és termékek", "w": ["Kecskemét", "Székesfehérvár", "Szolnok"]},
  {"a": "Farmer", "p": "Milyen ruhadarab volt a Trapper?", "s": "Márkák és termékek", "w": ["Télikabát", "Pulóver", "Kabát"]},
  {"a": "Tornacipő", "p": "Milyen lábbeli volt a Dorkó?", "s": "Márkák és termékek", "w": ["Bőr félcipő", "Papucs", "Csizma"]},
  {"a": "Ötöt", "p": "Hány számot húztak az ötöslottón?", "s": "Márkák és termékek", "w": ["Hatot", "Nyolcat", "Hetet"]},
  {"a": "Kilencvenből", "p": "Hány számból húzták az ötöslottót?", "s": "Márkák és termékek", "w": ["Hetvenből", "Ötvenből", "Száztizenötből"]},
  {"a": "Focira", "p": "Melyik sportra lehetett tippelni a Totón?", "s": "Márkák és termékek", "w": ["Vízilabdára", "Lóversenyre", "Jégkorongra"]},
  {"a": "Arckrémet", "p": "Mit gyártott a Fabulon?", "s": "Márkák és termékek", "w": ["Csokoládét", "Cipőt", "Mosóport"]},
  {"a": "Szappant", "p": "Mit gyártott a Caola?", "s": "Márkák és termékek", "w": ["Rádiót", "Konzervet", "Kerékpárt"]},
  {"a": "Szappan", "p": "Milyen termék volt a Baba?", "s": "Márkák és termékek", "w": ["Üdítőital", "Konzervmárka", "Kekszfajta"]},
  {"a": "Mosópor", "p": "Milyen termék volt a Tomi?", "s": "Márkák és termékek", "w": ["Üdítőital", "Fogkrémfajta", "Csokoládé"]},
  {"a": "Mosópor", "p": "Milyen termék volt a Biopon?", "s": "Márkák és termékek", "w": ["Sajtfajta", "Csokoládészelet", "Üdítőital"]},
  {"a": "Torokfájásra", "p": "Mire használták a Negrót?", "s": "Márkák és termékek", "w": ["Fejfájásra", "Hasfájásra", "Gyomorrontásra"]},
  {"a": "Fekete", "p": "Milyen színű a Negro cukorka?", "s": "Márkák és termékek", "w": ["Zöld", "Piros", "Világosbarna"]},
  {"a": "Csokoládé", "p": "Milyen termék a Boci?", "s": "Márkák és termékek", "w": ["Mosópor", "Tejföl", "Kekszféleség"]},
  {"a": "Csokoládét", "p": "Mit gyártottak Szerencsen?", "s": "Márkák és termékek", "w": ["Cipőt", "Hűtőszekrényt", "Mosóport"]},
  {"a": "Sajt", "p": "Milyen termék a Medve?", "s": "Márkák és termékek", "w": ["Vaj", "Gyümölcsjoghurt", "Tejföl"]},
  {"a": "Kávé", "p": "Milyen termék volt az Omnia?", "s": "Márkák és termékek", "w": ["Kakaó", "Tea", "Gyümölcslé"]},
  {"a": "Pezsgőt", "p": "Mit gyártott a Törley?", "s": "Márkák és termékek", "w": ["Sört", "Ásványvizet", "Bort"]},
  {"a": "A sörről", "p": "Milyen italról volt híres Kőbánya?", "s": "Márkák és termékek", "w": ["Az ásványvízről", "A borról", "A pezsgőről"]},
  {"a": "Munkás", "p": "Melyik volt olcsó, füstszűrő nélküli cigaretta?", "s": "Márkák és termékek", "w": ["Symphonia", "Multifilter", "Sopianae"]},
  {"a": "Fecske", "p": "Melyik magyar cigaretta neve madár?", "s": "Márkák és termékek", "w": ["Sopianae", "Symphonia", "Kossuth"]},
  {"a": "Izzót", "p": "Mit gyártott a Tungsram?", "s": "Márkák és termékek", "w": ["Kerékpárt", "Mosóport", "Konzervet"]},
  {"a": "Televíziót", "p": "Mit gyártott az Orion?", "s": "Márkák és termékek", "w": ["Hűtőszekrényt", "Cipőt", "Mosóport"]},
  {"a": "Televíziót", "p": "Mit gyártott a Videoton?", "s": "Márkák és termékek", "w": ["Hűtőszekrényt", "Konzervet", "Kerékpárt"]},
  {"a": "Lehel", "p": "Melyik márka volt a magyar hűtőszekrény?", "s": "Márkák és termékek", "w": ["Orion", "Videoton", "Tungsram"]},
  {"a": "Hajdú", "p": "Melyik márka volt a magyar mosógép?", "s": "Márkák és termékek", "w": ["Tungsram", "Orion", "Videoton"]},
  {"a": "Rubik Ernő", "p": "Ki találta fel a bűvös kockát?", "s": "Márkák és termékek", "w": ["Kandó Kálmán", "Bláthy Ottó", "Puskás Tivadar"]},
  {"a": "Társasjáték", "p": "Milyen játék a Gazdálkodj okosan?", "s": "Márkák és termékek", "w": ["Sportjáték", "Kártyajáték", "Számítógépes játék"]},
  {"a": "Házat", "p": "Mit lehetett venni a Gazdálkodj okosan! játékban?", "s": "Márkák és termékek", "w": ["Vasutat", "Szigetet", "Repülőt"]},
  {"a": "Dobókockával", "p": "Mivel léptek a Ki nevet a végén? játékban?", "s": "Márkák és termékek", "w": ["Kártyával", "Számolópálcikával", "Homokórával"]},
  {"a": "Pöttyös", "p": "Milyen mintás volt a klasszikus gumilabda?", "s": "Márkák és termékek", "w": ["Kockás", "Virágmintás", "Csíkos"]},
  {"a": "Számítógép", "p": "Milyen gép volt a Commodore 64?", "s": "Márkák és termékek", "w": ["Rádió", "Varrógép", "Hűtőszekrény"]},
  {"a": "Porcelánt", "p": "Mit gyártanak Herenden?", "s": "Márkák és termékek", "w": ["Üveget", "Bőrdíszművet", "Csipkét"]},
  {"a": "Üveget", "p": "Mit gyártottak Ajkán?", "s": "Márkák és termékek", "w": ["Porcelánt", "Csipkét", "Kerékpárt"]},
  {"a": "Kék", "p": "Milyen színű volt a kisdobosok nyakkendője?", "s": "Iskola és úttörőélet", "w": ["Zöld", "Piros", "Fehér"]},
  {"a": "Piros", "p": "Milyen színű volt az úttörők nyakkendője?", "s": "Iskola és úttörőélet", "w": ["Világoskék", "Zöld", "Kék"]},
  {"a": "Nyolc", "p": "Hány osztályos volt az általános iskola?", "s": "Iskola és úttörőélet", "w": ["Hat", "Négy", "Tizenkettő"]},
  {"a": "Ötös", "p": "Hányas volt a legjobb osztályzat?", "s": "Iskola és úttörőélet", "w": ["Egyes", "Négyes", "Tízes"]},
  {"a": "Egyes", "p": "Hányas volt a legrosszabb osztályzat?", "s": "Iskola és úttörőélet", "w": ["Nullás", "Ötös", "Négyes"]},
  {"a": "Oroszt", "p": "Melyik idegen nyelvet tanulta kötelezően minden diák?", "s": "Iskola és úttörőélet", "w": ["Franciát", "Németet", "Spanyolt"]},
  {"a": "Ellenőrzőben", "p": "Miben vezették a jegyeket a szülőknek?", "s": "Iskola és úttörőélet", "w": ["A tájékoztatóban", "A naplóban", "Az olvasókönyvben"]},
  {"a": "Napközi", "p": "Hogy hívták a délutáni iskolai foglalkozást?", "s": "Iskola és úttörőélet", "w": ["Tábor", "Diákotthon", "Kollégium"]},
  {"a": "Tarisznyát", "p": "Mit visz a vállán a ballagó diák?", "s": "Iskola és úttörőélet", "w": ["Iskolatáskát", "Bőröndöt", "Sporttáskát"]},
  {"a": "Pogácsát", "p": "Mit tesznek a ballagó tarisznyájába?", "s": "Iskola és úttörőélet", "w": ["Csokoládét", "Szendvicset", "Almát"]},
  {"a": "Az orgona", "p": "Melyik virág a ballagás jelképe?", "s": "Iskola és úttörőélet", "w": ["A rózsa", "A margaréta", "A szegfű"]},
  {"a": "Zánkán", "p": "Hol volt a nagy úttörőváros a Balatonnál?", "s": "Iskola és úttörőélet", "w": ["Balatonfüreden", "Keszthelyen", "Siófokon"]},
  {"a": "Úttörőtábor", "p": "Milyen tábor működött Csillebércen?", "s": "Iskola és úttörőélet", "w": ["Sportolók tábora", "Nyelvi tábor", "Katonai tábor"]},
  {"a": "Őrs", "p": "Hogy hívták az úttörők legkisebb csoportját?", "s": "Iskola és úttörőélet", "w": ["Század", "Szakasz", "Csapat"]},
  {"a": "Fehéret", "p": "Milyen inget viseltek az úttörők ünnepnap?", "s": "Iskola és úttörőélet", "w": ["Világoskéket", "Kéket", "Zöldet"]},
  {"a": "Előre!", "p": "Mi volt az úttörők köszönése?", "s": "Iskola és úttörőélet", "w": ["Jó munkát!", "Szabadság!", "Szevasz!"]},
  {"a": "Papírt", "p": "Mit gyűjtöttek a gyerekek az iskolában?", "s": "Iskola és úttörőélet", "w": ["Bélyeget", "Falevelet", "Kavicsot"]},
  {"a": "KISZ", "p": "Melyik ifjúsági szervezetbe léptek a nagyobb diákok?", "s": "Iskola és úttörőélet", "w": ["Munkásőrség", "Úttörők", "Kisdobosok"]},
  {"a": "Kommunista", "p": "Mit jelentett a KISZ nevében a K betű?", "s": "Iskola és úttörőélet", "w": ["Központi", "Középiskolai", "Közösségi"]},
  {"a": "Számháború", "p": "Melyik tábori játék ment számokkal?", "s": "Iskola és úttörőélet", "w": ["Akadályverseny", "Kidobós", "Fogócska"]},
  {"a": "Építőtáborba", "p": "Milyen nyári táborba mentek dolgozni a KISZ-esek?", "s": "Iskola és úttörőélet", "w": ["Sporttáborba", "Zenei táborba", "Úttörőtáborba"]},
  {"a": "Újság", "p": "Mi volt a Pajtás?", "s": "Iskola és úttörőélet", "w": ["Rádióműsor", "Társasjáték", "Rajzfilm"]},
  {"a": "Gyereklap", "p": "Mi volt a Kisdobos?", "s": "Iskola és úttörőélet", "w": ["Rajzfilmsorozat", "Társasjáték", "Rádióműsor"]},
  {"a": "Gyereklap", "p": "Mi volt a Dörmögő Dömötör?", "s": "Iskola és úttörőélet", "w": ["Társasjáték", "Bábelőadás", "Rajzfilmsorozat"]},
  {"a": "Rejtvénylap", "p": "Milyen újság volt a Füles?", "s": "Iskola és úttörőélet", "w": ["Napilap", "Mezőgazdasági lap", "Divatlap"]},
  {"a": "Szamár", "p": "Melyik állat szerepelt a Füles címlapján?", "s": "Iskola és úttörőélet", "w": ["Medve", "Sündisznó", "Róka"]},
  {"a": "Vicclap", "p": "Milyen lap volt a Ludas Matyi?", "s": "Iskola és úttörőélet", "w": ["Tudományos lap", "Sportlap", "Divatlap"]},
  {"a": "Hetilap", "p": "Milyen lap volt a Nők Lapja?", "s": "Iskola és úttörőélet", "w": ["Rejtvényújság", "Gyereklap", "Sportújság"]},
  {"a": "Népszabadság", "p": "Melyik volt a párt napilapja?", "s": "Iskola és úttörőélet", "w": ["Szabad Föld", "Esti Hírlap", "Magyar Nemzet"]},
  {"a": "Népsport", "p": "Melyik újság írt a sportról?", "s": "Iskola és úttörőélet", "w": ["Magyar Nemzet", "Népszabadság", "Nők Lapja"]},
  {"a": "A falusiaknak", "p": "Kiknek szólt a Szabad Föld?", "s": "Iskola és úttörőélet", "w": ["A diákoknak", "A sportolóknak", "A katonáknak"]},
  {"a": "Diáklap", "p": "Mi volt a Kincskereső?", "s": "Iskola és úttörőélet", "w": ["Rajzfilm", "Bábszínház", "Társasjáték"]},
  {"a": "Négy", "p": "Hány évig tartott a gimnázium?", "s": "Iskola és úttörőélet", "w": ["Öt", "Hat", "Három"]},
  {"a": "Intőt", "p": "Mit írt a tanár a rossz magaviseletért?", "s": "Iskola és úttörőélet", "w": ["Felmentést", "Dicséretet", "Osztályzatot"]},
  {"a": "Dicséret", "p": "Mi járt a jó magaviseletért?", "s": "Iskola és úttörőélet", "w": ["Rovás", "Intő", "Figyelmeztetés"]},
  {"a": "Krétával", "p": "Mivel írt a tanár a táblára?", "s": "Iskola és úttörőélet", "w": ["Ceruzával", "Filctollal", "Tollal"]},
  {"a": "Kettő", "p": "Hány csatornája volt sokáig a Magyar Televíziónak?", "s": "Televízió és rádió", "w": ["Négy", "Hat", "Tizenkettő"]},
  {"a": "Hétfőn", "p": "Melyik napon nem volt tévéadás?", "s": "Televízió és rádió", "w": ["Vasárnap", "Csütörtökön", "Szerdán"]},
  {"a": "A maci", "p": "Melyik állat küldte aludni a gyerekeket a tévében?", "s": "Televízió és rádió", "w": ["A nyuszi", "A mókus", "A sündisznó"]},
  {"a": "Este", "p": "Napszak szerint mikor ment az Esti mese?", "s": "Televízió és rádió", "w": ["Délben", "Reggel", "Délután"]},
  {"a": "Tudományról", "p": "Miről szólt a Delta című műsor?", "s": "Televízió és rádió", "w": ["Divatról", "Gasztronómiáról", "Mezőgazdaságról"]},
  {"a": "Bűnügyekről", "p": "Miről szólt a Kék fény?", "s": "Televízió és rádió", "w": ["Tudományos hírekről", "Sportról", "Divatról"]},
  {"a": "Szabó László", "p": "Ki vezette évtizedekig a Kék fényt?", "s": "Televízió és rádió", "w": ["Vitray Tamás", "Szilágyi János", "Antal Imre"]},
  {"a": "A rádióban", "p": "Hol ment A Szabó család?", "s": "Televízió és rádió", "w": ["A színházban", "A tévében", "A moziban"]},
  {"a": "Rádiójáték", "p": "Milyen műsor volt A Szabó család?", "s": "Televízió és rádió", "w": ["Táncdalfesztivál", "Rajzfilm", "Vetélkedő"]},
  {"a": "Tehetségkutató", "p": "Milyen műsor volt a Ki mit tud?", "s": "Televízió és rádió", "w": ["Ismeretterjesztő műsor", "Sportközvetítés", "Bűnügyi magazin"]},
  {"a": "Rajzfilm", "p": "Milyen műsor a Magyar népmesék?", "s": "Televízió és rádió", "w": ["Természetfilm", "Rádiójáték", "Vetélkedő"]},
  {"a": "Blöki", "p": "Hogy hívták a Mézga család kutyáját?", "s": "Televízió és rádió", "w": ["Maffia", "Kormos", "Morzsa"]},
  {"a": "Maffia", "p": "Hogy hívták a Mézga család macskáját?", "s": "Televízió és rádió", "w": ["Cirmi", "Blöki", "Lukrécia"]},
  {"a": "Aladár", "p": "Hogy hívták a Mézga család fiát?", "s": "Televízió és rádió", "w": ["Géza", "Dömötör", "Kriszta"]},
  {"a": "Kriszta", "p": "Hogy hívták a Mézga család lányát?", "s": "Televízió és rádió", "w": ["Paula", "Aladár", "Margitka"]},
  {"a": "Paula", "p": "Mi volt a Mézga mama keresztneve?", "s": "Televízió és rádió", "w": ["Kriszta", "Margit", "Erzsébet"]},
  {"a": "Dr. Máris", "p": "Ki volt Mézgáék szomszédja?", "s": "Televízió és rádió", "w": ["Dr. Bubó", "Károly bácsi", "Süsü bácsi"]},
  {"a": "A jövőből", "p": "Honnan üzent MZ/X a Mézga családnak?", "s": "Televízió és rádió", "w": ["A múltból", "A tenger mélyéről", "Külföldről"]},
  {"a": "Róka", "p": "Milyen állat Vuk?", "s": "Televízió és rádió", "w": ["Farkas", "Mókus", "Sündisznó"]},
  {"a": "Kutya", "p": "Milyen állat Frakk?", "s": "Televízió és rádió", "w": ["Sündisznó", "Nyúl", "Macska"]},
  {"a": "Szerénke", "p": "Melyik macska szerepelt a Frakkban?", "s": "Televízió és rádió", "w": ["Hófehérke", "Maffia", "Cirmi"]},
  {"a": "Kockás", "p": "Milyen a Kockásfülű nyúl füle?", "s": "Televízió és rádió", "w": ["Pöttyös", "Csíkos", "Virágmintás"]},
  {"a": "A fülével", "p": "Mivel repült a Kockásfülű nyúl?", "s": "Televízió és rádió", "w": ["Léggömbbel", "Ejtőernyővel", "Repülőgéppel"]},
  {"a": "Pom Pom meséi", "p": "Melyik mesében szerepel Gombóc Artúr?", "s": "Televízió és rádió", "w": ["Vízipók-csodapók", "Magyar népmesék", "Mézga család"]},
  {"a": "A csokoládét", "p": "Mit szeret legjobban Gombóc Artúr?", "s": "Televízió és rádió", "w": ["A mézet", "A fagylaltot", "A sült gesztenyét"]},
  {"a": "Madár", "p": "Milyen állat Gombóc Artúr?", "s": "Televízió és rádió", "w": ["Egér", "Sündisznó", "Medve"]},
  {"a": "Picurnak", "p": "Kinek mesél Pom Pom?", "s": "Televízió és rádió", "w": ["Vuknak", "Gombóc Artúrnak", "Süsünek"]},
  {"a": "Sárkány", "p": "Milyen mesealak Süsü?", "s": "Televízió és rádió", "w": ["Boszorkány", "Óriás", "Törpe"]},
  {"a": "Bagoly", "p": "Milyen madár Dr. Bubó?", "s": "Televízió és rádió", "w": ["Holló", "Veréb", "Harkály"]},
  {"a": "Dr. Bubó", "p": "Ki az orvos a Kérem a következőt! című mesében?", "s": "Televízió és rádió", "w": ["Gombóc Artúr", "Mekk Elek", "Dr. Máris"]},
  {"a": "Ursula", "p": "Ki Dr. Bubó ápolónője?", "s": "Televízió és rádió", "w": ["Szerénke", "Kriszta", "Lukrécia"]},
  {"a": "Kecske", "p": "Milyen állat Mekk Elek?", "s": "Televízió és rádió", "w": ["Sündisznó", "Birka", "Szamár"]},
  {"a": "Mekk Elek", "p": "Ki volt az ezermester a rajzfilmben?", "s": "Televízió és rádió", "w": ["Gombóc Artúr", "Süsü", "Dr. Bubó"]},
  {"a": "A vízben", "p": "Hol él a Vízipók-csodapók főhőse?", "s": "Televízió és rádió", "w": ["A földben", "A fán", "A levegőben"]},
  {"a": "Tyúkok", "p": "Milyen állatok Kukori és Kotkoda?", "s": "Televízió és rádió", "w": ["Kacsák", "Galambok", "Libák"]},
  {"a": "Egy férfi", "p": "Ki a főhőse a Gusztáv rajzfilmeknek?", "s": "Televízió és rádió", "w": ["Egy öreg néni", "Egy kisfiú", "Egy macska"]},
  {"a": "Robot", "p": "Milyen szereplő Mikrobi?", "s": "Televízió és rádió", "w": ["Manó", "Sárkány", "Boszorkány"]},
  {"a": "A kőkorban", "p": "Milyen korban élt Frédi és Béni?", "s": "Televízió és rádió", "w": ["A jövőben", "A középkorban", "Az újkorban"]},
  {"a": "Rímelt", "p": "Miről volt híres a Frédi és Béni magyar szövege?", "s": "Televízió és rádió", "w": ["Idegen szavakkal teli", "Nagyon rövid volt", "Énekelték"]},
  {"a": "Kossuth", "p": "Melyik volt a Magyar Rádió fő adója?", "s": "Televízió és rádió", "w": ["Petőfi", "Danubius", "Bartók"]},
  {"a": "Bartók", "p": "Melyik rádióadó szólt komolyzenét?", "s": "Televízió és rádió", "w": ["Danubius", "Kossuth", "Petőfi"]},
  {"a": "Petőfi", "p": "Melyik rádióadó volt a könnyedebb?", "s": "Televízió és rádió", "w": ["Szabad Európa", "Bartók", "Kossuth"]},
  {"a": "Külföldről", "p": "Honnan sugározták a Szabad Európa Rádiót?", "s": "Televízió és rádió", "w": ["Debrecenből", "Szegedről", "Budapestről"]},
  {"a": "Kívánságműsor", "p": "Milyen műsor volt a Szívküldi?", "s": "Televízió és rádió", "w": ["Hírműsor", "Gyerekműsor", "Bűnügyi magazin"]},
  {"a": "A gyerekeknek", "p": "Kinek szólt Miska bácsi levelesládája?", "s": "Televízió és rádió", "w": ["A sportolóknak", "A katonáknak", "A nyugdíjasoknak"]},
  {"a": "Tornáztak", "p": "Mit csináltak a nézők a Tévétorna alatt?", "s": "Televízió és rádió", "w": ["Bevásároltak", "Főztek", "Kártyáztak"]},
  {"a": "Hírműsor", "p": "Milyen műsor volt a Híradó?", "s": "Televízió és rádió", "w": ["Rajzfilmsorozat", "Vetélkedő", "Sportközvetítés"]},
  {"a": "Sportról", "p": "Miről szólt a Telesport?", "s": "Televízió és rádió", "w": ["A mezőgazdaságról", "Divatról", "Az időjárásról"]},
  {"a": "Az évszám", "p": "Mi változott évente a Stúdió című műsor címében?", "s": "Televízió és rádió", "w": ["A kezdés ideje", "A csatorna", "A műsorvezető"]},
  {"a": "Vasárnap", "p": "Melyik napon ment az A Hét című műsor?", "s": "Televízió és rádió", "w": ["Szerdán", "Hétfőn", "Csütörtökön"]},
  {"a": "Gazdagréten", "p": "Melyik lakótelepen játszódott a Szomszédok?", "s": "Televízió és rádió", "w": ["Újpalotán", "Óbudán", "Békásmegyeren"]},
  {"a": "Teleregény", "p": "Milyen sorozat volt a Szomszédok?", "s": "Televízió és rádió", "w": ["Rajzfilm", "Krimisorozat", "Természetfilm"]},
  {"a": "Rendőr", "p": "Mi volt Linda foglalkozása a sorozatban?", "s": "Televízió és rádió", "w": ["Újságíró", "Tanárnő", "Orvos"]},
  {"a": "Judót", "p": "Melyik sportot űzte Linda a sorozatban?", "s": "Televízió és rádió", "w": ["Vívást", "Kosárlabdát", "Úszást"]},
  {"a": "Görbe Nóra", "p": "Ki játszotta Lindát?", "s": "Televízió és rádió", "w": ["Piros Ildikó", "Béres Ilona", "Pécsi Ildikó"]},
  {"a": "Hajókról", "p": "Miről szólt Az Onedin család?", "s": "Televízió és rádió", "w": ["Repülőkről", "Vonatokról", "Lovasversenyekről"]},
  {"a": "Angol", "p": "Melyik ország sorozata volt Az Onedin család?", "s": "Televízió és rádió", "w": ["Szovjet", "Nyugatnémet", "Francia"]},
  {"a": "Amerikai", "p": "Melyik ország sorozata volt a Dallas?", "s": "Televízió és rádió", "w": ["Francia", "Nyugatnémet", "Angol"]},
  {"a": "Krimi", "p": "Milyen sorozat volt a Derrick?", "s": "Televízió és rádió", "w": ["Történelmi", "Rajzfilm", "Vígjáték"]},
  {"a": "Manó", "p": "Milyen lény Pumukli?", "s": "Televízió és rádió", "w": ["Boszorkány", "Törpe", "Sárkány"]},
  {"a": "Egér", "p": "Milyen állat Jerry a rajzfilmben?", "s": "Televízió és rádió", "w": ["Macska", "Kutya", "Sündisznó"]},
  {"a": "Macska", "p": "Milyen állat Tom a rajzfilmben?", "s": "Televízió és rádió", "w": ["Egér", "Sündisznó", "Kutya"]},
  {"a": "Pénteken", "p": "Melyik este ment a nagy film a tévében?", "s": "Televízió és rádió", "w": ["Kedden", "Csütörtökön", "Hétfőn"]},
  {"a": "Antenna", "p": "Mi kellett a háztetőre a tévéadás vételéhez?", "s": "Televízió és rádió", "w": ["Parabolatányér", "Kábel", "Rádió"]},
  {"a": "Gátőr", "p": "Mi volt Pelikán József munkája A tanúban?", "s": "Film és színház", "w": ["Vasutas", "Tanító", "Postás"]},
  {"a": "Narancsot", "p": "Milyen gyümölcsöt termesztettek A tanú című filmben?", "s": "Film és színház", "w": ["Görögdinnyét", "Szőlőt", "Almát"]},
  {"a": "Savanyúbbnak", "p": "Milyennek mondták a magyar narancsot a filmben?", "s": "Film és színház", "w": ["Illatosabbnak", "Nagyobbnak", "Édesebbnek"]},
  {"a": "Bacsó Péter", "p": "Ki rendezte A tanút?", "s": "Film és színház", "w": ["Szabó István", "Jancsó Miklós", "Makk Károly"]},
  {"a": "Mephisto", "p": "Melyik magyar film nyert Oscar-díjat?", "s": "Film és színház", "w": ["A tanú", "Macskafogó", "Régi idők focija"]},
  {"a": "Szabó István", "p": "Ki rendezte a Mephistót?", "s": "Film és színház", "w": ["Bacsó Péter", "Huszárik Zoltán", "Jancsó Miklós"]},
  {"a": "Mosodás", "p": "Mi volt Minarik Ede foglalkozása?", "s": "Film és színház", "w": ["Hentes", "Cipész", "Villanyszerelő"]},
  {"a": "Futballról", "p": "Melyik sportról szól a Régi idők focija?", "s": "Film és színház", "w": ["Lovaglásról", "Ökölvívásról", "Úszásról"]},
  {"a": "Garas Dezső", "p": "Ki játszotta Minarik Edét?", "s": "Film és színház", "w": ["Kern András", "Koltai Róbert", "Bujtor István"]},
  {"a": "Bendegúz", "p": "Ki a kamasz főszereplő az Indul a bakterházban?", "s": "Film és színház", "w": ["Gyuszi", "Vitay Georgina", "Pelikán József"]},
  {"a": "Rajzfilm", "p": "Milyen film a Macskafogó?", "s": "Film és színház", "w": ["Néma film", "Történelmi film", "Természetfilm"]},
  {"a": "Egér", "p": "Milyen állat Grabowski a Macskafogóban?", "s": "Film és színház", "w": ["Sündisznó", "Macska", "Patkány"]},
  {"a": "A macska", "p": "Melyik állat az ellenség a Macskafogóban?", "s": "Film és színház", "w": ["A patkány", "A sündisznó", "A kutya"]},
  {"a": "Kollégiumban", "p": "Hol játszódik az Abigél?", "s": "Film és színház", "w": ["Katonai táborban", "Kórházban", "Gyárban"]},
  {"a": "Egy szobor", "p": "Ki vagy mi Abigél a történetben?", "s": "Film és színház", "w": ["Egy diáklány", "Egy igazgatónő", "Egy tanárnő"]},
  {"a": "Bujtor István", "p": "Ki játszotta Ötvös Csöpit?", "s": "Film és színház", "w": ["Kern András", "Garas Dezső", "Sinkovits Imre"]},
  {"a": "Rendőr", "p": "Mi volt Ötvös Csöpi foglalkozása?", "s": "Film és színház", "w": ["Tanár", "Vendéglős", "Orvos"]},
  {"a": "A Balaton", "p": "Melyik tó mellett nyomozott Ötvös Csöpi?", "s": "Film és színház", "w": ["A Fertő tó", "A Velencei-tó", "A Tisza-tó"]},
  {"a": "Bujtor István", "p": "Ki volt Latinovits Zoltán féltestvére?", "s": "Film és színház", "w": ["Sinkovits Imre", "Garas Dezső", "Kern András"]},
  {"a": "Jancsó Miklós", "p": "Ki rendezte a Szegénylegényeket?", "s": "Film és színház", "w": ["Bacsó Péter", "Huszárik Zoltán", "Makk Károly"]},
  {"a": "Szaffi", "p": "Melyik rajzfilm készült Jókai regényéből?", "s": "Film és színház", "w": ["Macskafogó", "Vuk", "Lúdas Matyi"]},
  {"a": "Dargay Attila", "p": "Ki rendezte a Vuk című rajzfilmet?", "s": "Film és színház", "w": ["Ternovszky Béla", "Jankovics Marcell", "Nepp József"]},
  {"a": "Pannónia", "p": "Melyik stúdióban készültek a magyar rajzfilmek?", "s": "Film és színház", "w": ["Mafilm", "Objektív Stúdió", "Hunnia"]},
  {"a": "Bujtor István", "p": "Melyik magyar színész volt Bud Spencer hangja?", "s": "Film és színház", "w": ["Sinkovits Imre", "Garas Dezső", "Kern András"]},
  {"a": "Filmhíradó", "p": "Mi ment a főfilm előtt a moziban?", "s": "Film és színház", "w": ["Rajzfilm", "Reklám", "Színházi hír"]},
  {"a": "Kertmoziban", "p": "Hol néztek filmet nyáron a szabadban?", "s": "Film és színház", "w": ["Sportcsarnokban", "Színházban", "Művelődési házban"]},
  {"a": "Kabaré", "p": "Milyen műfajban volt Hofi Géza a legismertebb?", "s": "Film és színház", "w": ["Néptánc", "Operett", "Opera"]},
  {"a": "Vígjáték", "p": "Milyen film a Sose halunk meg?", "s": "Film és színház", "w": ["Krimi", "Természetfilm", "Történelmi film"]},
  {"a": "Koltai Róbert", "p": "Ki rendezte a Sose halunk meg című filmet?", "s": "Film és színház", "w": ["Bacsó Péter", "Szabó István", "Huszárik Zoltán"]},
  {"a": "Cirkuszról", "p": "Miről álmodnak a gyerekek a Keménykalap és krumpliorrban?", "s": "Film és színház", "w": ["Tengerpartról", "Repülőgépről", "Focimeccsről"]},
  {"a": "Lakáj", "p": "Mi volt Hyppolit foglalkozása?", "s": "Film és színház", "w": ["Kertész", "Házmester", "Szakács"]},
  {"a": "Gothár Péter", "p": "Ki rendezte a Megáll az idő című filmet?", "s": "Film és színház", "w": ["Huszárik Zoltán", "Bacsó Péter", "Makk Károly"]},
  {"a": "Színésznő", "p": "Milyen művész volt Törőcsik Mari?", "s": "Film és színház", "w": ["Énekesnő", "Zongoraművész", "Táncosnő"]},
  {"a": "Színész", "p": "Milyen művész volt Sinkovits Imre?", "s": "Film és színház", "w": ["Festő", "Zeneszerző", "Karmester"]},
  {"a": "Színésznő", "p": "Milyen művész volt Ruttkai Éva?", "s": "Film és színház", "w": ["Festőnő", "Írónő", "Operaénekesnő"]},
  {"a": "A Balaton", "p": "Melyik tó volt a magyarok fő nyaralóhelye?", "s": "Nyaralás és szabadidő", "w": ["A Tisza-tó", "A Fertő tó", "A Velencei-tó"]},
  {"a": "Rokonok", "p": "Kik találkoztak a Balatonnál a két Németországból?", "s": "Nyaralás és szabadidő", "w": ["Üzletemberek", "Sportolók", "Diákok"]},
  {"a": "A SZOT", "p": "Melyik szervezet adta az üdülési beutalót?", "s": "Nyaralás és szabadidő", "w": ["A KISZ", "Az IBUSZ", "A Vöröskereszt"]},
  {"a": "Üdülési jegy", "p": "Mi volt a beutaló?", "s": "Nyaralás és szabadidő", "w": ["Vásárlási utalvány", "Vasúti bérlet", "Munkahelyi igazolás"]},
  {"a": "IBUSZ", "p": "Melyik iroda szervezte az utazásokat?", "s": "Nyaralás és szabadidő", "w": ["MÁV", "Hungarocamion", "Malév"]},
  {"a": "Express", "p": "Melyik iroda szervezte a fiatalok útjait?", "s": "Nyaralás és szabadidő", "w": ["Cooptourist", "Budapest Tourist", "IBUSZ"]},
  {"a": "Bulgáriába", "p": "Melyik ország tengerpartjára jártak a magyarok?", "s": "Nyaralás és szabadidő", "w": ["Csehszlovákiába", "Lengyelországba", "Finnországba"]},
  {"a": "Útlevelet", "p": "Mit kellett kérni a nyugati utazáshoz?", "s": "Nyaralás és szabadidő", "w": ["Erkölcsi bizonyítványt", "Anyakönyvi kivonatot", "Munkakönyvet"]},
  {"a": "Világútlevél", "p": "Hogy hívták a mindenkinek járó új útlevelet?", "s": "Nyaralás és szabadidő", "w": ["Piros útlevél", "Kék útlevél", "Szolgálati útlevél"]},
  {"a": "A valutát", "p": "Mit korlátoztak a nyugati utazásnál?", "s": "Nyaralás és szabadidő", "w": ["A vonatjegyet", "Az útitársakat", "A csomagot"]},
  {"a": "Bécsbe", "p": "Hova jártak bevásárolni a magyarok a határon túlra?", "s": "Nyaralás és szabadidő", "w": ["Prágába", "Bukarestbe", "Varsóba"]},
  {"a": "Banánt", "p": "Melyik gyümölcsöt hozták haza Bécsből a magyarok?", "s": "Nyaralás és szabadidő", "w": ["Almát", "Szilvát", "Görögdinnyét"]},
  {"a": "A telken", "p": "Hol nyaraltak a családok saját kis házban?", "s": "Nyaralás és szabadidő", "w": ["A hotelben", "A kempingben", "A szomszédnál"]},
  {"a": "A kertet", "p": "Mit gondoztak sokan hétvégén a városon kívül?", "s": "Nyaralás és szabadidő", "w": ["A garázst", "Az autójukat", "A tetőt"]},
  {"a": "Sátorban", "p": "Hol aludtak a kempingezők?", "s": "Nyaralás és szabadidő", "w": ["Panzióban", "Szállodában", "Vonaton"]},
  {"a": "A hullámvasút", "p": "Melyik játék volt a Vidám Park jelképe?", "s": "Nyaralás és szabadidő", "w": ["Az elvarázsolt kastély", "A céllövölde", "A körhinta"]},
  {"a": "A Városligetben", "p": "Hol volt a budapesti Állatkert?", "s": "Nyaralás és szabadidő", "w": ["A Gellért-hegyen", "A Margitszigeten", "A Népligetben"]},
  {"a": "A Margitszigeten", "p": "Melyik szigeten sétáltak a budapestiek?", "s": "Nyaralás és szabadidő", "w": ["A Szentendrei-szigeten", "A Hajógyári-szigeten", "A Csepel-szigeten"]},
  {"a": "A hévízi", "p": "Melyik tó vize meleg egész évben?", "s": "Nyaralás és szabadidő", "w": ["A Balaton", "A Fertő tó", "A Velencei-tó"]},
  {"a": "Három", "p": "Hány játékos kell az ultihoz?", "s": "Nyaralás és szabadidő", "w": ["Négy", "Tizenkettő", "Hat"]},
  {"a": "Magyar kártyával", "p": "Milyen lapokkal játszottak ultit?", "s": "Nyaralás és szabadidő", "w": ["Római kártyával", "Tarokk-kártyával", "Francia kártyával"]},
  {"a": "Gombokkal", "p": "Mivel játszották a gombfocit?", "s": "Nyaralás és szabadidő", "w": ["Kavicsokkal", "Dobókockákkal", "Fadarabokkal"]},
  {"a": "Diszkóba", "p": "Hova mentek a fiatalok táncolni a nyolcvanas években?", "s": "Nyaralás és szabadidő", "w": ["Művelődési házba", "Cukrászdába", "Operába"]},
  {"a": "Presszóban", "p": "Hol ittak kávét a városban?", "s": "Nyaralás és szabadidő", "w": ["Trafikban", "Mozielőtérben", "Fodrászatnál"]},
  {"a": "Szombat", "p": "Melyik nap lett szabad a heti munkából?", "s": "Nyaralás és szabadidő", "w": ["Szerda", "Hétfő", "Csütörtök"]},
  {"a": "Matracot", "p": "Mit fújtak fel a gyerekeknek a strandon?", "s": "Nyaralás és szabadidő", "w": ["Napernyőt", "Nyugágyat", "Strandlabdát"]},
  {"a": "Áprilisban", "p": "Melyik hónapban volt a felszabadulás ünnepe?", "s": "Ünnepek és szokások", "w": ["Májusban", "Novemberben", "Júniusban"]},
  {"a": "A munkát", "p": "Mit ünnepeltek május 1-jén?", "s": "Ünnepek és szokások", "w": ["A forradalmat", "Az alkotmányt", "A szabadságot"]},
  {"a": "Felvonulás", "p": "Mi volt május 1. fő eseménye Budapesten?", "s": "Ünnepek és szokások", "w": ["Tűzijáték", "Fáklyásmenet", "Körmenet"]},
  {"a": "Majálist", "p": "Mit tartottak május 1-jén a szabadban?", "s": "Ünnepek és szokások", "w": ["Fáklyásmenetet", "Búcsút", "Farsangot"]},
  {"a": "Novemberben", "p": "Melyik hónapban ünnepelték a nagy októberi forradalmat?", "s": "Ünnepek és szokások", "w": ["Szeptemberben", "Decemberben", "Októberben"]},
  {"a": "Az új kenyeret", "p": "Mit ünnepeltek augusztus 20-án a Kádár-korban?", "s": "Ünnepek és szokások", "w": ["A szüretet", "A szabadságot", "A tanév kezdetét"]},
  {"a": "A tűzijáték", "p": "Mi világítja meg augusztus 20-án az eget a Duna felett?", "s": "Ünnepek és szokások", "w": ["A fáklyák", "A reflektorok", "A gyertyák"]},
  {"a": "Szent Istváné", "p": "Melyik szent ünnepe augusztus 20.?", "s": "Ünnepek és szokások", "w": ["Szent Imréé", "Szent Lászlóé", "Szent Erzsébeté"]},
  {"a": "Kokárdát", "p": "Mit tűznek a kabátra március 15-én?", "s": "Ünnepek és szokások", "w": ["Zászlót", "Nemzeti szalagot", "Szegfűt"]},
  {"a": "Három", "p": "Hány színű a kokárda?", "s": "Ünnepek és szokások", "w": ["Tizenkettő", "Négy", "Öt"]},
  {"a": "December 6-án", "p": "Melyik napon jön a Mikulás?", "s": "Ünnepek és szokások", "w": ["December 31-én", "November 30-án", "December 24-én"]},
  {"a": "Az ablakba", "p": "Hova teszik a gyerekek a cipőjüket Mikuláskor?", "s": "Ünnepek és szokások", "w": ["Az asztalra", "A fa alá", "A kandalló elé"]},
  {"a": "Virgácsot", "p": "Mit kap a rossz gyerek a Mikulástól?", "s": "Ünnepek és szokások", "w": ["Almát", "Szenet", "Üres csomagot"]},
  {"a": "Aranyra", "p": "Milyen színűre festik a virgácsot?", "s": "Ünnepek és szokások", "w": ["Kékre", "Pirosra", "Ezüstszínűre"]},
  {"a": "A Jézuska", "p": "Ki hozza a karácsonyfát a magyar gyerekeknek?", "s": "Ünnepek és szokások", "w": ["A Télapó", "A Mikulás", "A karácsonyi manó"]},
  {"a": "Szaloncukrot", "p": "Mit akasztanak édességként a karácsonyfára?", "s": "Ünnepek és szokások", "w": ["Csokoládét", "Mézeskalácsot", "Gyümölcsöt"]},
  {"a": "Sztaniolban", "p": "Miben van a szaloncukor a fán?", "s": "Ünnepek és szokások", "w": ["Dobozban", "Papírzacskóban", "Celofánban"]},
  {"a": "Szenteste", "p": "Melyik ünnep estéjén díszítik a fát?", "s": "Ünnepek és szokások", "w": ["Újév napja", "Karácsony másnapja", "Szilveszter"]},
  {"a": "Locsolkodnak", "p": "Mit csinálnak a fiúk húsvéthétfőn?", "s": "Ünnepek és szokások", "w": ["Betlehemeznek", "Adományt gyűjtenek", "Kántálnak"]},
  {"a": "Hímes tojást", "p": "Mit kapnak a locsoló fiúk?", "s": "Ünnepek és szokások", "w": ["Mézeskalácsot", "Pénzt", "Virágot"]},
  {"a": "Verset", "p": "Mit mondanak a fiúk locsolkodás előtt?", "s": "Ünnepek és szokások", "w": ["Mesét", "Imát", "Köszöntőlevelet"]},
  {"a": "Húsvéthétfőn", "p": "Melyik napon locsolkodnak?", "s": "Ünnepek és szokások", "w": ["Húsvétvasárnap", "Nagyszombaton", "Pünkösdhétfőn"]},
  {"a": "A nőnapot", "p": "Mit ünnepelnek a nők március 8-án?", "s": "Ünnepek és szokások", "w": ["A pedagógusnapot", "A gyereknapot", "Az anyák napját"]},
  {"a": "Virágot", "p": "Mit kaptak a nők a munkahelyen nőnapkor?", "s": "Ünnepek és szokások", "w": ["Süteményt", "Pénzt", "Szabadnapot"]},
  {"a": "Májusban", "p": "Melyik hónapban van az anyák napja?", "s": "Ünnepek és szokások", "w": ["Júniusban", "Márciusban", "Áprilisban"]},
  {"a": "Májusban", "p": "Melyik hónapban van a gyereknap?", "s": "Ünnepek és szokások", "w": ["Áprilisban", "Szeptemberben", "Júliusban"]},
  {"a": "Halottak napján", "p": "Melyik ünnepen gyújtanak gyertyát a sírokon?", "s": "Ünnepek és szokások", "w": ["Húsvétvasárnap", "Szentestén", "Nagyboldogasszony napján"]},
  {"a": "A télnek", "p": "Minek a végét ünnepli a farsang?", "s": "Ünnepek és szokások", "w": ["Az aratásnak", "A tavasznak", "A nyárnak"]},
  {"a": "Jelmezt", "p": "Mit vesznek fel a gyerekek a farsangi bálra?", "s": "Ünnepek és szokások", "w": ["Népviseletet", "Egyenruhát", "Ünneplő ruhát"]},
  {"a": "Mohácson", "p": "Melyik városban híres a busójárás?", "s": "Ünnepek és szokások", "w": ["Hódmezővásárhelyen", "Kalocsán", "Egerben"]},
  {"a": "A telet", "p": "Mit űznek el a busók?", "s": "Ünnepek és szokások", "w": ["A nyarat", "A betegséget", "A szegénységet"]},
  {"a": "Álarcot", "p": "Mit viselnek a busók?", "s": "Ünnepek és szokások", "w": ["Egyenruhát", "Papírsapkát", "Koszorút"]},
  {"a": "Trombitát", "p": "Mit fújnak éjfélkor szilveszterkor?", "s": "Ünnepek és szokások", "w": ["Furulyát", "Szájharmonikát", "Dudát"]},
  {"a": "A tyúkot", "p": "Melyik állatot nem illik megenni újév napján?", "s": "Ünnepek és szokások", "w": ["A malacot", "A halat", "A marhát"]},
  {"a": "Luca napján", "p": "Melyik ünnepen vetnek búzát tányérba?", "s": "Ünnepek és szokások", "w": ["Karácsonykor", "Szentestén", "Mikulás napján"]},
  {"a": "A névnapot", "p": "Mit ünnepeltek nálunk a születésnap mellett?", "s": "Ünnepek és szokások", "w": ["Az évfordulót", "A keresztelőt", "Az esküvő napját"]},
  {"a": "A naptárból", "p": "Miből nézték meg, kinek van névnapja?", "s": "Ünnepek és szokások", "w": ["A rádióból", "Az anyakönyvből", "A telefonkönyvből"]},
  {"a": "Virágot", "p": "Mit visznek a névnapos asszonynak?", "s": "Ünnepek és szokások", "w": ["Pénzt", "Bonbonos dobozt", "Süteményt"]},
  {"a": "Szüreti bált", "p": "Mit tartanak a szüret végén a falvakban?", "s": "Ünnepek és szokások", "w": ["Búcsút", "Fáklyás felvonulást", "Farsangot"]},
  {"a": "Május elsején", "p": "Melyik ünnepen állítanak májusfát?", "s": "Ünnepek és szokások", "w": ["Pünkösdkor", "Húsvétkor", "Szent Iván-napkor"]},
  {"a": "Júniusban", "p": "Melyik hónapban van a pedagógusnap?", "s": "Ünnepek és szokások", "w": ["Áprilisban", "Szeptemberben", "Májusban"]},
  {"a": "Panelból", "p": "Miből épültek a lakótelepi házak?", "s": "Otthon és háztartás", "w": ["Fából", "Nádból", "Vályogból"]},
  {"a": "Kádárról", "p": "Kiről nevezték el a falusi kockaházat?", "s": "Otthon és háztartás", "w": ["Kossuthról", "Rákosiról", "Horthyról"]},
  {"a": "Távfűtés", "p": "Milyen fűtés volt a panelházakban?", "s": "Otthon és háztartás", "w": ["Olajkályha", "Cserépkályha", "Széntüzelés"]},
  {"a": "Szenet", "p": "Mit hordtak fel a pincéből fűtéshez?", "s": "Otthon és háztartás", "w": ["Krumplit", "Vizet", "Befőttet"]},
  {"a": "Palackban", "p": "Miben tárolták a PB-gázt?", "s": "Otthon és háztartás", "w": ["Kannában", "Hordóban", "Műanyag flakonban"]},
  {"a": "A centrifuga", "p": "Mi pörgette ki a vizet a kimosott ruhából?", "s": "Otthon és háztartás", "w": ["A szárítókötél", "A mosóteknő", "A mángorló"]},
  {"a": "Az erkélyre", "p": "Hova teregették a ruhát a panelban?", "s": "Otthon és háztartás", "w": ["A fürdőkádba", "A pincébe", "A lépcsőházba"]},
  {"a": "Fekvőhely", "p": "Mi volt a rekamié?", "s": "Otthon és háztartás", "w": ["Szekrény", "Csillár", "Konyhaszekrény"]},
  {"a": "Bútor", "p": "Mi volt a szekrénysor?", "s": "Otthon és háztartás", "w": ["Konyhagép", "Szőnyeg", "Kályha"]},
  {"a": "Falvédő", "p": "Mi lógott a konyhában a fal védelmére?", "s": "Otthon és háztartás", "w": ["Tükör", "Fényképkeret", "Naptár"]},
  {"a": "Szöveget", "p": "Mit hímeztek a falvédőre?", "s": "Otthon és háztartás", "w": ["Térképet", "Számoszlopot", "Kottát"]},
  {"a": "Éveket", "p": "Mennyit kellett várni egy otthoni telefonra?", "s": "Otthon és háztartás", "w": ["Napokat", "Perceket", "Heteket"]},
  {"a": "Közös vonal", "p": "Mi volt az ikertelefon?", "s": "Otthon és háztartás", "w": ["Külföldi hívás", "Munkahelyi vonal", "Két készülék"]},
  {"a": "Korongon", "p": "Hogyan tárcsáztak a régi telefonon?", "s": "Otthon és háztartás", "w": ["Hangjelre", "Érintőképernyőn", "Gombokkal"]},
  {"a": "Tantuszt", "p": "Mit kellett bedobni a telefonfülkében?", "s": "Otthon és háztartás", "w": ["Jegyet", "Bélyeget", "Zsetonkártyát"]},
  {"a": "Sárga csekkel", "p": "Mivel fizették a villanyszámlát a postán?", "s": "Otthon és háztartás", "w": ["Kék csekkel", "Takarékbetétkönyvvel", "Utalvánnyal"]},
  {"a": "Az OTP", "p": "Melyik pénzintézet őrizte a család megtakarítását?", "s": "Otthon és háztartás", "w": ["Az IBUSZ", "A Vöröskereszt", "A MÁV"]},
  {"a": "Maszek", "p": "Hogy hívták a magánvállalkozót a Kádár-korban?", "s": "Otthon és háztartás", "w": ["Brigádos", "Munkásőr", "Kulák"]},
  {"a": "Fusizás", "p": "Hogy hívták a munkaidő utáni mellékmunkát?", "s": "Otthon és háztartás", "w": ["Társadalmi munka", "Brigádmunka", "Túlóra"]},
  {"a": "Kis magánföld", "p": "Mi volt a háztáji?", "s": "Otthon és háztartás", "w": ["Városi kiskert", "Állami gazdaság", "Közös legelő"]},
  {"a": "Termelőszövetkezet", "p": "Mit jelentett a tsz rövidítés?", "s": "Otthon és háztartás", "w": ["Területi szakszervezet", "Tanácsi szolgáltatás", "Takarékszövetkezet"]},
  {"a": "Munkakönyvben", "p": "Miben tartották számon a munkahelyeket?", "s": "Otthon és háztartás", "w": ["Takarékbetétkönyvben", "Személyi igazolványban", "Ellenőrzőben"]},
  {"a": "Kaláka", "p": "Hogy hívták a rokonok közös házépítését?", "s": "Otthon és háztartás", "w": ["Szövetkezet", "Brigád", "Társadalmi munka"]},
  {"a": "Szovjetunió", "p": "Melyik országból jött a Zenit fényképezőgép?", "s": "Otthon és háztartás", "w": ["NDK", "Csehszlovákia", "Lengyelország"]},
  {"a": "NDK", "p": "Melyik országból jött a Praktica fényképezőgép?", "s": "Otthon és háztartás", "w": ["Bulgária", "Csehszlovákia", "Lengyelország"]},
  {"a": "Diafilmen", "p": "Min nézték a gyerekek a mesét vetítve?", "s": "Otthon és háztartás", "w": ["Videón", "Fényképezőgépen", "Mozivásznon"]},
  {"a": "Diavetítővel", "p": "Mivel vetítették a diafilmet?", "s": "Otthon és háztartás", "w": ["Zseblámpával", "Gyertyával", "Filmfelvevővel"]},
  {"a": "Kazettára", "p": "Mire vették fel a zenét a nyolcvanas években?", "s": "Otthon és háztartás", "w": ["Lemezre", "Filmszalagra", "Papírra"]},
  {"a": "Bakeliten", "p": "Milyen lemezen szólt a zene a lemezjátszón?", "s": "Otthon és háztartás", "w": ["Üveglemezen", "Műanyag szalagon", "Fémlemezen"]},
  {"a": "Vizet", "p": "Mit töltöttek a szódásüvegbe?", "s": "Otthon és háztartás", "w": ["Gyümölcslevet", "Bort", "Sört"]},
  {"a": "Teknőben", "p": "Hol mosott a háziasszony a mosógép előtt?", "s": "Otthon és háztartás", "w": ["Kádban", "Mosogatógépben", "Vödörben"]},
  {"a": "Tyúkot", "p": "Melyik állatot tartották a falusi udvarban?", "s": "Otthon és háztartás", "w": ["Papagájt", "Struccot", "Szarvast"]},
  {"a": "Krumplit", "p": "Mit termesztettek a ház mögötti kertben?", "s": "Otthon és háztartás", "w": ["Rizst", "Kávécserjét", "Gyapotot"]},
  {"a": "Befőttet", "p": "Mit tettek el télire a kamrába?", "s": "Otthon és háztartás", "w": ["Friss húst", "Virágot", "Fagylaltot"]},
  {"a": "Kamra", "p": "Mi volt a spájz?", "s": "Otthon és háztartás", "w": ["Fürdőszoba", "Erkély", "Előszoba"]},
  {"a": "Jéggel", "p": "Mivel tartották hidegen az ételt hűtő nélkül?", "s": "Otthon és háztartás", "w": ["Homokkal", "Nedves ruhával", "Sóval"]},
  {"a": "Társadalmi munka", "p": "Hogy hívták a lakótelepi közös önkéntes munkát?", "s": "Otthon és háztartás", "w": ["Szocialista brigádmunka", "Önkéntes szolgálat", "Kötelező túlóra"]},
  {"a": "Táborban", "p": "Hol nyaraltak a gyerekek a szülők nélkül?", "s": "Nyaralás és szabadidő", "w": ["Kempingben", "Szállodában", "Üdülőszövetkezetben"]},
  {"a": "Törölközőt", "p": "Mit vittek a strandra a napozáshoz?", "s": "Nyaralás és szabadidő", "w": ["Sátrat", "Takarót", "Napozóágyat"]},
  {"a": "Várat", "p": "Mit építettek a gyerekek a strand homokjában?", "s": "Nyaralás és szabadidő", "w": ["Hidat", "Alagutat", "Csatornát"]},
  {"a": "Napolajjal", "p": "Mivel kenték be magukat a strandon?", "s": "Nyaralás és szabadidő", "w": ["Kölnivel", "Fogkrémmel", "Hajszesszel"]},
  {"a": "Hátizsákot", "p": "Mit vittek a hátukon a kirándulók?", "s": "Nyaralás és szabadidő", "w": ["Bőröndöt", "Utazóládát", "Sporttáskát"]},
  {"a": "Kagylót", "p": "Mit gyűjtöttek a gyerekek a Balaton partján?", "s": "Nyaralás és szabadidő", "w": ["Gesztenyét", "Borostyánt", "Fenyőtobozt"]},
  {"a": "A cipésznél", "p": "Hol javíttatták meg a lyukas cipőt?", "s": "Bolt és vásárlás", "w": ["Az órásnál", "A szabónál", "A fodrásznál"]},
  {"a": "A szabóhoz", "p": "Kihez vitték megigazítani a ruhát?", "s": "Bolt és vásárlás", "w": ["Az óráshoz", "A cipészhez", "A fodrászhoz"]},
  {"a": "Füzetet", "p": "Mit vásároltak a papírboltban?", "s": "Bolt és vásárlás", "w": ["Kenyeret", "Mosóport", "Cipőfűzőt"]},
  {"a": "A borbélynál", "p": "Hol nyíratták a hajukat a férfiak?", "s": "Bolt és vásárlás", "w": ["Az órásnál", "A szabóműhelyben", "A cipészműhelyben"]},
  {"a": "A posta", "p": "Melyik vállalat kézbesítette a leveleket?", "s": "Bolt és vásárlás", "w": ["A MÁV", "Az IBUSZ", "A Hungarocamion"]},
  {"a": "Bélyeget", "p": "Mit ragasztottak a levélre feladás előtt?", "s": "Bolt és vásárlás", "w": ["Címkét", "Fényképet", "Utalványt"]},
  {"a": "Táviratban", "p": "Hogyan küldtek sürgős üzenetet a postán?", "s": "Bolt és vásárlás", "w": ["Levélben", "Csomagban", "Ajánlott levélben"]},
  {"a": "Vígjáték", "p": "Milyen műfajú film az Indul a bakterház?", "s": "Film és színház", "w": ["Krimi", "Természetfilm", "Történelmi film"]},
  {"a": "A tanúban", "p": "Melyik filmben szerepel Pelikán József?", "s": "Film és színház", "w": ["Az Abigélben", "A Mephistóban", "A Macskafogóban"]},
  {"a": "Színész", "p": "Milyen művész volt Latinovits Zoltán?", "s": "Film és színház", "w": ["Festő", "Karmester", "Zeneszerző"]},
  {"a": "Tornazsákot", "p": "Mit kellett vinni a tornaórára?", "s": "Iskola és úttörőélet", "w": ["Uzsonnát", "Ellenőrzőt", "Iskolatáskát"]},
  {"a": "Tollal", "p": "Mivel írtak a diákok a füzetbe?", "s": "Iskola és úttörőélet", "w": ["Ecsettel", "Krétával", "Írógéppel"]},
  {"a": "Az ebédlőben", "p": "Hol ebédeltek a napközis gyerekek?", "s": "Iskola és úttörőélet", "w": ["A folyosón", "Az udvaron", "A tornateremben"]}
]
$questions$::jsonb)
  with ordinality as question(item, ordinality);

do $validation$
begin
  if (
    select count(*) from public.quiz_questions
    where category_id = 'regen_volt' and is_active
  ) <> 388 then
    raise exception 'Ahogy régen volt must contain exactly 388 active questions';
  end if;

  if exists (
    select 1
    from public.quiz_questions as question
    where question.category_id = 'regen_volt'
      and (
        cardinality(question.wrong_answers) <> 3
        or (
          select count(distinct lower(trim(answer)))
          from unnest(question.wrong_answers) as answer
        ) <> 3
        or exists (
          select 1
          from unnest(question.wrong_answers) as answer
          where lower(trim(answer)) = lower(trim(question.correct_answer))
        )
      )
  ) then
    raise exception 'Ahogy régen volt: every question needs three distinct wrong answers';
  end if;

  if exists (
    select 1
    from public.quiz_questions as proposed
    join public.quiz_questions as existing
      on lower(trim(existing.prompt)) = lower(trim(proposed.prompt))
     and existing.id <> proposed.id
    where proposed.category_id = 'regen_volt'
  ) then
    raise exception 'Ahogy régen volt: a prompt is already used by another question';
  end if;
end;
$validation$;
